### PR TITLE
LectorJPG: Update theme

### LINKED ISSUE #9781: LectorJPG: Redesign and Cloudflare error
### Source information

LectorJPG 1.4.42 

### Source language

Spanish

### Steps to reproduce

When I enter the source it does not load no matter how many times I try, but if I enter the website everything works fine. https://lectorjpg.com/

Image

### Expected behavior

I don't know why it doesn't let me read if the website works without any problem, I have loaded the font many times and it still doesn't let me read. 

Image

### Actual behavior

Even from the same source I enter the website and it still doesn't seem to work, it simply says Cloudflare error. 

### Mihon/Tachiyomi version

Mihon 0.18.0 

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Closes #9781

User will have to migrate

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/lectorjpg/src/eu/kanade/tachiyomi/extension/es/lectorjpg/LectorJpg.kt [hunk 1]
```diff
@@ -1,81 +1,280 @@
...
+
+    override val supportsLatest = true
 
     override val client = super.client.newBuilder()
         .rateLimitHost(baseUrl.toHttpUrl(), 3, 1)
         .build()
 
-    override fun popularMangaSelector() = "div:not([class]):has(> div.break-words)"
+    private val latestMangaCursor = mutableMapOf<Int, String?>()
+    private val searchMangaCursor = mutableMapOf<Int, String?>()
```
Comment (stevenyomi) [inline src/es/lectorjpg/src/eu/kanade/tachiyomi/extension/es/lectorjpg/LectorJpg.kt]: 1. Does the search cursor not need to be keyed with the keyword, filters, etc?
2. Limit the cache size:

```kotlin
object : LinkedHashMap<Int, String?>() {
    override fun removeEldestEntry(eldest: MutableMap.MutableEntry<Int, String?>) = size > 8
}
```

**Review by stevenyomi — APPROVED** [review]
