### PR TITLE
Geass Comics: Updated site theme (like SkkyToons) (closes #12978)

### LINKED ISSUE #12978: Geass Comics
### Source information

Geass Comics 1.4.2

### Source language

Português ( Brasil )

### Steps to reproduce

Não está aparecendo as obras na extensão, no site está normal

Site: 
Image

Extensão:
Image

### Expected behavior

Aparecer as obras

### Actual behavior

Tá dando o erro 404

### Mihon/Tachiyomi version

Mihon 0.19.3

### Android version

Android 15 

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by WebDitto**
Closes #12978

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt [hunk 1]
```diff
@@ -79,212 +80,317 @@ class GeassComics :
...
 
-    override fun popularMangaRequest(page: Int): Request = GET("$apiUrl/leaderboard?criteria=global&withHentai=${isAdultActive()}", headers)
+        return runCatching { login(email, password) }.getOrDefault("")
+    }
 
-    override fun popularMangaParse(response: Response): MangasPage {
-        val list = response.parseAs<List<MangaDto>>()
-        return MangasPage(list.map { it.toSManga() }, false)
+    private fun login(email: String, password: String): String {
+        val payload = json.encodeToString(LoginRequest(email, password))
```
Comment (AwkwardPeak7) [inline src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt]: use `toJsonString` helper from `keiyoushi.utils` instead

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt [hunk 2]
```diff
@@ -53,8 +57,6 @@ class GeassComics :
 
     private val json: Json = Injekt.get<Json>()
```
Comment (AwkwardPeak7) [inline src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt]: use `keiyoushi.utils.parseAs` for json instead

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt [hunk 3]
```diff
@@ -79,212 +80,317 @@ class GeassComics :
...
-        dto.items.forEach { manga ->
-            manga.lastChapters.forEach { chapter ->
-                val date = chapter.date?.let { parseDate(it) } ?: 0L
-                if (date > 0L) {
-                    chapterDateMap["${manga.id}-${chapter.chapterNumber}"] = date
-                }
+    override fun popularMangaRequest(page: Int): Request {
+        val showNsfw = runCatching {
+            preferences.getBoolean(PREF_ADULT_KEY, false)
+        }.getOrDefault(false)
```
Comment (AwkwardPeak7) [inline src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt]: no need for runCatching?

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt [hunk 4]
```diff
@@ -79,212 +80,317 @@ class GeassComics :
...
-        return GET(urlBuilder.build(), headers)
-    }
+        val showNsfwPref = runCatching {
+            preferences.getBoolean(PREF_ADULT_KEY, false)
+        }.getOrDefault(false)
 
-    override fun searchMangaParse(response: Response) = latestUpdatesParse(response)
-
-    // ========================= Details ====================================
+        if (!showNsfwPref) {
```
Comment (AwkwardPeak7) [inline src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt]: imo filter should take precedence over preference, make it so default filter is null

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
bump versionId if old manga urls are not compatible anymore, (or put logic to make old ones work if it is easily possibe)

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt (hunk 4 above)
Comment (WebDitto) [reply src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt]: The ideia here is, if the option is disabled in preferences, do not show in the filter
By default the filter is null.

**Review by AwkwardPeak7 — APPROVED** [review]
