### PR TITLE
HuntersScans: add image descrambler

### LINKED ISSUE #12297: Hunters scan erro
### Source information

Hunters scan 1.4.54

### Source language

Português brasileiro 

### Steps to reproduce

Está acontecendo o erro de substituição de imagem

### Expected behavior

Image

### Actual behavior

Image

### Mihon/Tachiyomi version

0.19.3 

### Android version

14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes: #12297

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScanDescrambler.kt [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        val sb = StringBuilder()
+
+        for (i in payload.indices) {
+            var keyIndex = (i % key.length) - 1
+            if (keyIndex < 0) keyIndex = key.length + keyIndex
+            val c = payload[i].code - key[keyIndex].code
+            sb.append(c.toChar())
+        }
+
+        return Json.decodeFromString<List<String>>(sb.toString())
```
Comment (AwkwardPeak7) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScanDescrambler.kt]: use `keiyoushi.utils.parseAs`

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScanDescrambler.kt [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+        val payload = String(Base64.decode(payloadB64, Base64.DEFAULT), Charset.forName("ISO-8859-1"))
+        val key = String(Base64.decode(keyB64, Base64.DEFAULT), Charset.forName("ISO-8859-1"))
+        val sb = StringBuilder()
+
+        for (i in payload.indices) {
+            var keyIndex = (i % key.length) - 1
+            if (keyIndex < 0) keyIndex = key.length + keyIndex
+            val c = payload[i].code - key[keyIndex].code
+            sb.append(c.toChar())
+        }
```
Comment (vetleledaal) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScanDescrambler.kt]: Consider using `forEachIndexed` instead, and replacing `var` with `val`.

```suggestion
        payload.forEachIndexed { i, ch ->
            val keyIndex = (i + key.length - 1) % key.length
            val c = ch.code - key[keyIndex].code
            sb.append(c.toChar())
        }
```

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt [hunk 3]
```diff
@@ -58,5 +65,39 @@ class HuntersScans : Madara(
         }
     }
 
-    override val pageListParseSelector = ".read-container img"
+    override fun pageListParse(document: Document): List<Page> {
+        val script = document.selectFirst("script:containsData(_HuntersOpts)")?.data()
+            ?: return super.pageListParse(document)
+
+        val payload = Regex("""payload:\s*"(.*?)"""").find(script)?.groupValues?.get(1)
+        val sk = Regex("""sk:\s*"(.*?)"""").find(script)?.groupValues?.get(1)
```
Comment (vetleledaal) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]: Both of these regexes are invariant- move to class.

**Review by vetleledaal — APPROVED** [review]
