### PR TITLE
Greedscans: fix paid chapters

### LINKED ISSUE #14735: Greed: Hide Locked Chapters
### Source name

greed v1.4.30

### Source language

English

### Describe your suggested feature

In this extension, there are chapters that you cannot read without paying, as in some extensions. Therefore, it would be very good not to show the chapters that we cannot read.  

### Other details

This time I checked it properly and didn't make my previous mistake. There is no hide paid chapter in the extensions settings. Also, if there is no problem with me saying it, can you correct the name of the extension so that the letter G is capitalized?  

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/).
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14735

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt [hunk 1]
```diff
@@ -1,10 +1,33 @@
...
     MangaThemesia(
-        "greed scans",
+        "Greed Scans",
         "https://greedscans.com",
         "en",
+    ),
+    ConfigurableSource {
+
+    private val preferences: SharedPreferences =
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
```
Comment (AaronDeimos) [inline src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt]: Use `keiyoushi.utils.getPreferences`

Comment (darwin-256) [reply src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt]: solved

File: src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt [hunk 2]
```diff
@@ -1,10 +1,30 @@
...
+import androidx.preference.PreferenceScreen
 import eu.kanade.tachiyomi.multisrc.mangathemesia.MangaThemesia
+import eu.kanade.tachiyomi.multisrc.mangathemesia.MangaThemesiaPaidChapterHelper
+import eu.kanade.tachiyomi.source.ConfigurableSource
+import keiyoushi.utils.getPreferences
 
 class GreedScans :
     MangaThemesia(
-        "greed scans",
+        "Greed Scans",
```
Comment (AwkwardPeak7) [inline src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt:12]: override id to keep old one, so users dont have to migrate their titles. you can find the current id from the repo index.json

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt (hunk 2 above)
Comment (AaronDeimos) [reply src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt:12]: It didn't change, though. 
The generation logic always uses a lowercased name.
From mihon
``` kotlin
protected fun generateId(name: String, lang: String, versionId: Int): Long {
        val key = "${name.lowercase()}/$lang/$versionId"
        val bytes = MessageDigest.getInstance("MD5").digest(key.toByteArray())
        return (0..7).map { bytes[it].toLong() and 0xff shl 8 * (7 - it) }.reduce(Long::or) and Long.MAX_VALUE
    }
```

Comment (darwin-256) [reply src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt:12]: So i updated for no reason?

Comment (AaronDeimos) [reply src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt:12]: Yes lol

Comment (AwkwardPeak7) [reply src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt:12]: didn't know/remember this, still better to be explicit ig

Comment (darwin-256) [reply src/en/greedscans/src/eu/kanade/tachiyomi/extension/en/greedscans/GreedScans.kt:12]: so wait do i keep this or no, cuz i just reverted it

**Review by AwkwardPeak7 — APPROVED** [review]
