### PR TITLE
YomuComics: fix Redesign

### LINKED ISSUE #10895: Yomu Comics: `Nenhum resultado encontrado` error / New website URL
### Source information

Yomu Comics 1.4.37

### Source language

Português (Brasil)

### Source new URL

https://yomu.com.br/

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes #10895

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 1]
```diff
@@ -0,0 +1,190 @@
...
+
+import eu.kanade.tachiyomi.source.model.SChapter
+import eu.kanade.tachiyomi.source.model.SManga
+import keiyoushi.utils.tryParse
+import kotlinx.serialization.Serializable
+import java.text.SimpleDateFormat
+import java.util.Locale
+
+@Serializable
+data class HomeDto(
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]: Avoid using data class, just use a regular class.

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 2]
```diff
@@ -0,0 +1,190 @@
...
+    val artist: String? = null,
+    val chapters: List<ChapterDto> = emptyList(),
+) {
+    fun toSManga(): SManga = SManga.create().apply {
+        title = this@ObraDataDto.title
+        thumbnail_url = cover
+        description = synopsis
+        author = this@ObraDataDto.author
+        artist = this@ObraDataDto.artist
+        genre = genres.joinToString(", ")
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]:
```suggestion
        genre = genres.joinToString()
```
`", "` is the default and can be omitted.

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 3]
```diff
@@ -0,0 +1,190 @@
...
+@Serializable
+data class ChapterDto(
+    val id: Int,
+    val index: Double,
+    val name: String,
+    val date: String? = null,
+    val createdAt: String? = null,
+) {
+    fun toSChapter(mangaSlug: String, mangaId: Int): SChapter = SChapter.create().apply {
+        val numberStr = if (index % 1 == 0.0) index.toInt().toString() else index.toString().replace(".", "-")
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]:
```suggestion
        val numberStr = index.toString().removeSuffix(".0").replace(".", "-")
```

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 4]
```diff
@@ -0,0 +1,190 @@
...
+        name = this@ChapterDto.name
+        chapter_number = index.toFloat()
+        url = "/ler/$mangaSlug/capitulo-$numberStr?id=$mangaId"
+        date_upload = DATE_FORMATTER.tryParse(createdAt)
+    }
+
+    companion object {
+        private val DATE_FORMATTER by lazy {
+            SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.ROOT)
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]: Timezone is not set -- either unquote `Z` or explicitly set a timestamp. Both approaches should work.

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 5]
```diff
@@ -0,0 +1,190 @@
...
+    val chaptersCount: Int? = null,
+    val chapters: List<ChapterDto> = emptyList(),
+    val favorites: Int? = null,
+    val userInfo: String? = null,
+) {
+    fun toSManga(slug: String): SManga = SManga.create().apply {
+        title = this@SeriesDto.name
+        thumbnail_url = coverImage ?: posterImage
+        description = sinopse ?: description
+        genre = genres.joinToString(", ") { it.name }
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]:
```suggestion
        genre = genres.joinToString { it.name }
```

`", "` is the default.

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt [hunk 6]
```diff
@@ -1,72 +1,289 @@
...
+    override fun pageListParse(response: Response): List<Page> {
+        val pagesDto = response.parseAs<ChapterPagesDto>()
+
+        return pagesDto.pages.mapIndexed { index, pageDto ->
+            Page(index, "", baseUrl + pageDto.url)
+        }
+    }
+
+    override fun imageUrlParse(response: Response): String {
+        throw UnsupportedOperationException("Not implemented")
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt]:
```suggestion
        throw UnsupportedOperationException()
```

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt [hunk 7]
```diff
@@ -1,72 +1,289 @@
...
+        val chapterNumber = url.pathSegments.last().removePrefix("capitulo-").replace("-", ".")
+
+        return GET("$baseUrl/api/public/chapters/$mangaId/$chapterNumber", headers)
+    }
+
+    override fun pageListParse(response: Response): List<Page> {
+        val pagesDto = response.parseAs<ChapterPagesDto>()
+
+        return pagesDto.pages.mapIndexed { index, pageDto ->
+            Page(index, "", baseUrl + pageDto.url)
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt]:
```suggestion
            Page(index, imageUrl = baseUrl + pageDto.url)
```

**Review by vetleledaal — APPROVED** [review]
