### PR TITLE
Tojimangas: fix extension

### LINKED ISSUE #6791: Tojimangas error loading
### Source information

Tojimangas 1.4.1

### Source language

Spanish

### Steps to reproduce

the font is not working properly https://tojimangas.com/
Screenshot_20241224_102056_Ykai

### Expected behavior

the website is working normally 
Screenshot_20241224_102122_Chrome

### Actual behavior

The website works normally, but the font does not respond as it should 

### Mihon/Tachiyomi version

 Yōkai 1.9.7

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #6791

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/tojimangas/src/eu/kanade/tachiyomi/extension/es/tojimangas/Tojimangas.kt [hunk 1]
```diff
@@ -21,92 +21,156 @@ class Tojimangas : ParsedHttpSource() {
...
-                infoGrid?.selectFirst("span:contains(Estado)")?.text()?.substringAfter("Estado")
-                    ?.trim()?.lowercase()
-            ) {
-                "activo" -> SManga.ONGOING
-                "finalizado" -> SManga.COMPLETED
-                else -> SManga.UNKNOWN
-            }
+        val content = document.selectFirst(".content")
+        thumbnail_url = content?.selectFirst("img")?.absUrl("src")
+        genre = document.select(".meta a").joinToString { a -> a.text() }
```
Comment (vetleledaal) [inline src/es/tojimangas/src/eu/kanade/tachiyomi/extension/es/tojimangas/Tojimangas.kt]:
```suggestion
        genre = document.select(".meta a").joinToString { it.text() }
```

File: src/es/tojimangas/src/eu/kanade/tachiyomi/extension/es/tojimangas/Tojimangas.kt [hunk 2]
```diff
@@ -21,92 +21,156 @@ class Tojimangas : ParsedHttpSource() {
...
+        } catch (_: ParseException) {
+            0L
+        }
     }
 
-    override fun pageListParse(document: Document): List<Page> =
-        document.select(".reader-area img").mapIndexed { idx, img ->
-            Page(idx, imageUrl = img.absUrl("src"))
+    protected open fun parseRelativeDate(date: String): Long {
+        val number = Regex("""(\d+)""").find(date)?.value?.toIntOrNull() ?: return 0
```
Comment (vetleledaal) [inline src/es/tojimangas/src/eu/kanade/tachiyomi/extension/es/tojimangas/Tojimangas.kt]: Extract regex so it does not have to be recompiled on each invocation.

**Review by vetleledaal — CHANGES_REQUESTED** [review]

**Review by vetleledaal — APPROVED** [review]
