### PR TITLE
MangaPark: fixes & improvements

### LINKED ISSUE #7208: Mangapark: Use Upload status when Original work status not available
### Source name

Mangapark

### Source language

multi

### Describe your suggested feature

There are multiple instances where the Original work status isn't available in an entry but the Upload status is. In those cases, the extension throws an "Unknown" status instead of using the Upload status.
The Upload status should be used if the Original work status isn't available

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #7289: Add "Extra Info" from Mangapark to descriptions
### Source name

Mangapark

### Source language

Multi

### Describe your suggested feature

"Extra Info" should be added to the descriptions on mangapark entries.

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #8251: Add SFW Filter Option to MangaPark Extension
### Source name

MangaPark 

### Source language

All

### Describe your suggested feature

The MangaPark website already supports an SFW filter, making it possible to browse without encountering 18+ content. Including this in the extension would make it more versatile, appealing to users who want to use MangaPark but prefer to avoid adult material. It aligns with the website’s functionality and could reduce the need for a separate SFW variant."

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #8471: Mangapark: Covers aren't showing up
### Source name

MangaPark All 1.4.21 18+

### Source language

English

### Describe your suggested feature

Clicking the MangaPark extension should load thumbnails of managa's listed
currently it does not load the thumbnails so page likely change how its stored

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
- fix covers
  - closes #8471
- uncensored covers for hentai
- sfw setting
  - closes #8251
- extra info in description
  - closes #7289
- use upload status if original status is unknown
  - closes #7208
- cleanup title 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Secozzi** [comment]
> [x] Updated `extVersionCode` value in `build.gradle` for individual extensions

Where version bump

File: src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt [hunk 1]
```diff
@@ -75,7 +93,13 @@ class MangaParkComic(
...
             "cancelled" -> SManga.CANCELLED
-            else -> SManga.UNKNOWN
+            else -> when (uploadStatus) {
+                "ongoing" -> SManga.ONGOING
+                "completed" -> SManga.COMPLETED
+                "hiatus" -> SManga.ON_HIATUS
+                "cancelled" -> SManga.CANCELLED
+                else -> SManga.UNKNOWN
+            }
         }
```
Comment (DokterKaj) [inline src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt]: You could do this like [how it's done in Batoto](https://github.com/keiyoushi/extensions-source/blob/5ab52f07040a2659353d7c334973fa8c8bac47a4/src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batoto/BatoTo.kt#L389-L402):
```kt
status = when (val status = originalStatus ?: uploadStatus) {
    "ongoing" -> SManga.ONGOING
    "completed" -> when {
        uploadStatus == "ongoing" -> SManga.PUBLISHING_FINISHED
        else -> SManga.COMPLETED
    }
    "hiatus" -> SManga.ON_HIATUS
    "cancelled" -> SManga.CANCELLED
    else -> SManga.UNKNOWN
}
```

File: src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt [hunk 2]
```diff
@@ -38,33 +38,63 @@ class MangaParkComic(
...
+            summary?.also {
+                append(Jsoup.parse(it).wholeText().trim())
+                append("\n\n")
+            }
+            extraInfo?.takeUnless(String::isBlank)?.also {
+                append("Extra Info:\n")
+                append(Jsoup.parse(it).wholeText().trim())
+                append("\n\n")
+            }
+            altNames?.takeUnless { it.isEmpty() }
```
Comment (vetleledaal) [inline src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt]: Why mix syntax?
```kt
.takeUnless(String::isBlank)
.takeUnless { it.isEmpty() }
```
I prefer the first one, looks less busy. But should at least stay consistent with whatever approach you pick.

File: src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt [hunk 3]
```diff
@@ -96,6 +126,14 @@ class MangaParkComic(
...
             return result.toString()
         }
+
+        private fun useLatestPageAsCover(genres: List<String>?): Boolean {
+            return genres.orEmpty().let {
+                it.contains("hentai") && !it.contains("webtoon")
+            }
+        }
+
+        private val shortenTitleRegex = Regex("""(\[[^]]*]|[({][^)}]*[)}])""")
```
Comment (vetleledaal) [inline src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt]: Why make it so a `(` can be closed by `}`? Consider using `RegexOptions.COMMENTS`, then you can use something like:
```
(
    \(         # Brackets: (...)
        [^)]*
    \)
    |          # OR
    \[         # Brackets: [...]
        [^]]*
    \]
    |          # OR
    \{         # Brackets: {...}
        [^}]*
    \}
)
```
```
# Brackets: (...)
\(
    [^)]*
\)

| # OR

# Brackets: [...]
\[
    [^]]*
\]

| # OR

# Brackets: {...}
\{
    [^}]*
\}
```
```
\([^)]*\)
|
\[[^]]*\]
|
\{[^}]*\}
```

~~You _might_ be able to replace the inner regex with `.*?`, as it will still need to match the closing bracket. This would help making the regex less complex.~~ Will probably cause issues since the current approach is greedy.

It is in any case a difficult regex to optimize without tests or concrete examples.

File: src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt [hunk 4]
```diff
@@ -264,7 +304,7 @@ class MangaPark(
 
                 latch.countDown()
             } else {
-                latch.await()
+                latch.await(10, TimeUnit.SECONDS)
```
Comment (vetleledaal) [inline src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt]: Will this emit some relevant exception/toast for the user? If not- consider explicitly telling the user.

File: src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt [hunk 5]
```diff
@@ -54,13 +54,31 @@ class MangaPark(
...
     private val apiUrl = "$baseUrl/apo/"
 
-    private val json: Json by injectLazy()
+    override val client = network.cloudflareClient.newBuilder().apply {
+        if (preference.getBoolean(ENABLE_NSFW, true)) {
+            addInterceptor(::siteSettingsInterceptor)
+            addNetworkInterceptor(CookieInterceptor(domain, "nsfw" to "2"))
+        }
+        rateLimitHost(apiUrl.toHttpUrl(), 1)
+        addInterceptor { chain ->
```
Comment (vetleledaal) [inline src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaPark.kt]: Consider extracting to a class/function. Already done for `siteSettingsInterceptor`.

File: src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt (hunk 3 above)
Comment (vetleledaal) [reply src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt]: There might be some additional improvements for cleaning titles. I have categorized some titles observed from the site into [a gist](https://gist.github.com/vetleledaal/792e3a420456014688850932e9a9fa19). Of course subjective, but you are free to make your own conclusion.

---

With the stated goal from the gist and to minimize false positives I think it would be better if you have something where:
- the regex only matches the start OR end of a title
- Recursively:
  - remove match
  - trim (or match `\s` in regex)

Comment (AwkwardPeak7) [reply src/all/mangapark/src/eu/kanade/tachiyomi/extension/all/mangapark/MangaParkDto.kt]: https://regex101.com/r/Ww8YNd/1

**Review by vetleledaal — APPROVED** [review]
