### PR TITLE
Add C'moA / SpeedBinb: minor fix

### LINKED ISSUE #1361: Source request (JA): C'moA Comics
### Source name

コミックシーモア

### Source link

https://www.cmoa.jp/

### Source language

japanese

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by manti-X**
Closes #1361 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/cmoa/src/eu/kanade/tachiyomi/extension/ja/cmoa/Cmoa.kt [hunk 1]
```diff
@@ -0,0 +1,239 @@
...
+    override val supportsLatest = true
+
+    private val json = Injekt.get<Json>()
+    private val reader by lazy { SpeedBinbReader(client, headers, json, true) } // 1.7070.1001
+    private val preferences: SharedPreferences by getPreferencesLazy()
+
+    override val client = network.cloudflareClient.newBuilder()
+        .addInterceptor(SpeedBinbInterceptor(json))
+        .addNetworkInterceptor(CookieInterceptor(domain, "safesearch" to "0"))
+        .addNetworkInterceptor(CookieInterceptor(domain, "R18user" to "1"))
```
Comment (AwkwardPeak7) [inline src/ja/cmoa/src/eu/kanade/tachiyomi/extension/ja/cmoa/Cmoa.kt]:
```suggestion
        .addNetworkInterceptor(CookieInterceptor(domain, listOf("safesearch" to "0", "R18user" to "1")))
```

File: src/ja/cmoa/src/eu/kanade/tachiyomi/extension/ja/cmoa/Cmoa.kt [hunk 2]
```diff
@@ -0,0 +1,239 @@
...
+    HttpSource(),
+    ConfigurableSource {
+    override val name = "C'moA"
+    private val domain = "cmoa.jp"
+    override val baseUrl = "https://www.$domain"
+    override val lang = "ja"
+    override val supportsLatest = true
+
+    private val json = Injekt.get<Json>()
+    private val reader by lazy { SpeedBinbReader(client, headers, json, true) } // 1.7070.1001
```
Comment (AwkwardPeak7) [inline src/ja/cmoa/src/eu/kanade/tachiyomi/extension/ja/cmoa/Cmoa.kt]: just pass in `jsonInstance`

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
