### PR TITLE
Nihonkuni:Update selector

### LINKED ISSUE #11787: Nihonkuni No results
### Source information

1.4.16

### Source language

Japanese

### Steps to reproduce

1.Open source Nihonkuni in app

### Expected behavior

You can browse comics

### Actual behavior

No results found

Image

### Mihon/Tachiyomi version

komikku 1.13.3

### Android version

Android10

### Other details

You can browse in the WebView

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AlphaBoom**
Closes #11787 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt [hunk 1]
```diff
@@ -42,6 +43,18 @@ class MangaGun : FMReader("NihonKuni", "https://$DOMAIN", "ja") {
 
     override fun latestUpdatesRequest(page: Int): Request = mangaRequest("last_update", page)
 
+    override fun popularMangaSelector() = "div.manga-grid div.manga-card"
+
+    override fun popularMangaFromElement(element: Element): SManga {
+        return SManga.create().apply {
+            element.select(".manga-title").let {
```
Comment (vetleledaal) [inline src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt]:
```suggestion
            element.selectFirst(".manga-title")!!.let {
```

File: src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt [hunk 2]
```diff
@@ -42,6 +43,18 @@ class MangaGun : FMReader("NihonKuni", "https://$DOMAIN", "ja") {
...
+                setUrlWithoutDomain(it.attr("abs:href"))
+                title = it.text()
+            }
+            thumbnail_url = element.select(".manga-cover").imgAttr()
```
Comment (vetleledaal) [inline src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt]: Use `selectFirst` here too. You may need to flip the logic a bit.

**Review by vetleledaal — APPROVED** [review]
