### PR TITLE
Fix: MangaLivre: erro 403 and 404

### LINKED ISSUE #11532: Manga Livre: `HTTP 403` / `Falha ao contornar o Cloudflare` error
### Source information

1.4.46

### Source language

Português Brasil 

### Steps to reproduce

Entrar na fonte 
Apertar em alguém manga
Erro  para abrir o capítulo 

Image
Image

### Expected behavior

Abrir novamente 

### Actual behavior

Image

### Mihon/Tachiyomi version

18.1.2

### Android version

15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by felipegangorra**
## Description

Fixes the MangaLivre extension which was returning error 403 (Forbidden) and 404 (Not Found) when trying to read chapters.

## Problem

The extension was experiencing two sequential errors:

- Error 403 - Attempts with the alternative .to domain no longer existed
- Error 404 - The site blocked access to URLs with ?style=list

## Solution
- Added interceptor that specifically removes the ?style=list parameter from chapter URLs
- Maintained the .tv domain as per the site's current implementation
- URLs now follow the correct format: https://mangalivre.tv/manga/.../chapter-42/

## Changes
- Increased `overrideVersionCode` from 2 to 3
- Added interceptor to correct chapter URLs

## Tested
- ✅ Manga list works
- ✅ Search works
- ✅ Chapter reading works (error 404 resolved)

Closes #11532

Checklist:

- [✅] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [✅] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [✅] Have not changed source names
- [✅] Have explicitly kept the `id` if a source's name or language were changed
- [✅] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 1]
```diff
@@ -10,7 +12,28 @@ class MangaLivre : Madara(
     "pt-BR",
     SimpleDateFormat("MMMM dd, yyyy", Locale("pt")),
 ) {
-    override val useNewChapterEndpoint = true
 
+    private class MangaLivreInterceptor : Interceptor {
```
Comment (bapeey) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: You can override `chapterUrlSuffix` to remove the param (refresh the chapter list to update the url)

File: src/pt/mangalivre/build.gradle [hunk 2]
```diff
@@ -2,8 +2,8 @@ ext {
     extName = 'Manga Livre'
     extClass = '.MangaLivre'
     themePkg = 'madara'
-    baseUrl = 'https://mangalivre.tv'
-    overrideVersionCode = 1
+    baseUrl = 'https://mangalivre.to'
+    overrideVersionCode = 3
```
Comment (bapeey) [inline src/pt/mangalivre/build.gradle]: Extension its still using the `.tv` domain in source class
```suggestion
    baseUrl = 'https://mangalivre.tv'
    overrideVersionCode = 2
```

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt (hunk 1 above)
Comment (felipegangorra) [reply src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: I tested chapterUrlSuffix but it didn't work for MangaLivre. I believe the problem is that ?style=list is already present in the URLs returned by the site's API; Madara isn't adding it. The interceptor removes the parameter from any URL that contains it, regardless of the origin.

Comment (bapeey) [reply src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Do you refreshed the chapter list after the change?

Comment (felipegangorra) [reply src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: I'll try again to be sure.

Comment (felipegangorra) [reply src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: It's actually working correctly...

Comment (felipegangorra) [reply src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: change made in commit [0ee0661](https://github.com/keiyoushi/extensions-source/pull/11651/commits/0ee06614850f041772bfadda6b167333d472081f)

**Review by AwkwardPeak7 — APPROVED** [review]
