### PR TITLE
HeavenManga: Fix chapter list and add latest tab

### LINKED ISSUE #1164: Heaven Manga, the extension is broken
### Source information

es.HeavenManga-v1.4.6

### Source language

Spanish

### Steps to reproduce

Open the extension, select any title, then try to fetch the chapters.
Same with the search function. 

### Expected behavior

Chapters should load, and the search function works as expected. 

### Actual behavior

Not chapters, and when you search an item appears without no name or thumbnail. 

### Mihon/Tachiyomi version

TachiJ2k 1.7.4 (same problem problems with others forks)

### Android version

Android 13

### Other details

The search function, barely works, and the chapters don't load. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #1164 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/heavenmanga/src/eu/kanade/tachiyomi/extension/es/heavenmanga/HeavenManga.kt [hunk 1]
```diff
@@ -24,99 +29,115 @@ class HeavenManga : ParsedHttpSource() {
...
-    override fun chapterListSelector() = "div.listing-chapters_wrap tr"
+    override fun latestUpdatesRequest(page: Int) = GET(baseUrl, headers)
 
-    override fun popularMangaNextPageSelector() = "ul.pagination a[rel=next]"
+    override fun latestUpdatesParse(response: Response): MangasPage {
+        val document = response.asJsoup()
 
-    override fun latestUpdatesNextPageSelector() = popularMangaNextPageSelector()
+        val mangas = document.selectFirst(latestUpdatesWrapperSelector())!!
+            .select(latestUpdatesSelector())
```
Comment (AwkwardPeak7) [inline src/es/heavenmanga/src/eu/kanade/tachiyomi/extension/es/heavenmanga/HeavenManga.kt:61]: both selectors can be merged?

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/es/heavenmanga/src/eu/kanade/tachiyomi/extension/es/heavenmanga/HeavenManga.kt (hunk 1 above)
Comment (bapeey) [reply src/es/heavenmanga/src/eu/kanade/tachiyomi/extension/es/heavenmanga/HeavenManga.kt:61]: Only the first wrapper is valid

**Review by AwkwardPeak7 — APPROVED** [review]
