### PR TITLE
YushukeMangas: Fix content loading and bump versionID

### LINKED ISSUE #6969: Yushuke Mangas (Pt-Br Source): does not show content!
### Source information

Yushuke Mangas 1.4.1

### Source language

Portuguese Brazilian 

### Steps to reproduce

The source don't show content.

### Expected behavior

Show content!

### Actual behavior

Don't show content!

Screenshot_2025-01-03-23-19-52-785_app mihon debug
Screenshot_2025-01-03-23-20-01-689_app mihon debug
Screenshot_2025-01-03-23-25-18-641_com android chrome

### Mihon/Tachiyomi version

0.17.1-7043

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #6969

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt [hunk 1]
```diff
@@ -95,84 +107,178 @@ class YushukeMangas : ParsedHttpSource() {
...
             Page(index, imageUrl = imageUrl.absUrl("src"))
         }
     }
 
     override fun imageUrlParse(document: Document) = ""
 
-    // ============================== Filters ===============================
+    // ============================== Filters =============================
+
+//    override fun getFilterList() = FilterList(RadioFilter("Status", statusList))
```
Comment (AwkwardPeak7) [inline src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt]: remove

File: src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt [hunk 2]
```diff
@@ -95,84 +107,178 @@ class YushukeMangas : ParsedHttpSource() {
...
 
-    open class GenreFilter(displayName: String, private val vals: Array<String>, state: Int = 0) :
-        Filter.Select<String>(displayName, vals, state) {
+    override fun getFilterList(): FilterList {
+        val filters = mutableListOf(
+            RadioFilter("Status", "status", statusList),
+            RadioFilter("Tipo", "tipo", typeList),
+            GenreFilter("Gêneros", "tags[]", genresList),
+        )
+        return FilterList(filters)
```
Comment (AwkwardPeak7) [inline src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt]:
```suggestion
        return FilterList(
            RadioFilter("Status", "status", statusList),
            RadioFilter("Tipo", "tipo", typeList),
            GenreFilter("Gêneros", "tags[]", genresList),
        )
```

File: src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt [hunk 3]
```diff
@@ -95,84 +107,178 @@ class YushukeMangas : ParsedHttpSource() {
...
+        "Sci-fi", "Seinen", "Shoujo", "Shounen", "Slice of Life", "Sobrenatural", "Super Poderes",
+        "Terror",
+        "Vingança",
+    )
+
+    // ============================== Utilities ===========================
+
+    private inline fun <reified T> Response.parseAs(): T = use {
+        json.decodeFromStream(it.body.byteStream())
+    }
```
Comment (AwkwardPeak7) [inline src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt]:
```suggestion
    private inline fun <reified T> Response.parseAs(): T {
        json.decodeFromStream(body.byteStream())
    }
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
