### PR TITLE
DeviantArt: Preserve token in multi-image posts

### LINKED ISSUE #9147: Deviantart : multi-image posts don't work
### Source information

Deviantart 1.4.8

### Source language

Multiple 

### Steps to reproduce

View a multi-image post like this one on tachiyomi : https://www.deviantart.com/al3ksgts/art/My-Kanojo-is-GROWING-Chapter-1-Part-1-1197685682

### Expected behavior

All images of the post should appear 

### Actual behavior

The first image work but the other have an error 401

### Mihon/Tachiyomi version

SY r583

### Android version

Android 15

### Other details

It seems that not all of the multi-image post don't work.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by DokterKaj**
Closes #9147

Tests:
- `gallery:horminum` "cook and engineer" (Ch 221), "001" (Ch 225): These still work without the token and with the token now added they continue to work
- `gallery:al3ksgts/96690616`: Bugged case provided by reporter, now works

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] ~Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions~
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] ~Added the `isNsfw = true` flag in `build.gradle` when appropriate~
- [x] Have not changed source names
- [ ] ~Have explicitly kept the `id` if a source's name or language were changed~
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] ~Have removed `web_hi_res_512.png` when adding a new extension~

### CODE REVIEW

File: src/all/deviantart/src/eu/kanade/tachiyomi/extension/all/deviantart/DeviantArt.kt [hunk 1]
```diff
@@ -162,16 +154,17 @@ class DeviantArt : HttpSource(), ConfigurableSource {
...
+        return if (buttons == null) {
+            val imageUrl = document.selectFirst("img[fetchpriority=high]")?.absUrl("src")
+            listOf(Page(0, imageUrl = imageUrl))
+        } else {
+            buttons.mapIndexed { i, button ->
                 // Remove everything past "/v1/" to get original instead of thumbnail
-                val imageUrl = button.selectFirst("img")?.absUrl("src")?.substringBefore("/v1/")
+                // But need to preserve the query parameter where the token is
+                val imageUrl = button.selectFirst("img")?.absUrl("src")
+                    ?.replaceFirst(Regex("""/v1(/.*)?(?=\?)"""), "")
```
Comment (AwkwardPeak7) [inline src/all/deviantart/src/eu/kanade/tachiyomi/extension/all/deviantart/DeviantArt.kt:166]: use `HttpUrl.Builder` to remove any path segment, instead of regex

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/all/deviantart/src/eu/kanade/tachiyomi/extension/all/deviantart/DeviantArt.kt (hunk 1 above)
Comment (DokterKaj) [reply src/all/deviantart/src/eu/kanade/tachiyomi/extension/all/deviantart/DeviantArt.kt:166]: I did consider that at first, but the implementation ends up really clunky:
```kt
val thumbnailUrl = button.selectFirst("img")?.absUrl("src")?.toHttpUrl()
val imageUrl = thumbnailUrl?.newBuilder()?.apply { 
    val vIndex = thumbnailUrl.pathSegments.indexOf("v1")
    repeat(thumbnailUrl.pathSize - vIndex) {
        removePathSegment(vIndex)
    }
}?.build()?.toString()
```
Should I do it anyway?

**Review by AwkwardPeak7 — APPROVED** [review]
