### PR TITLE
ReadComicOnline - Update Parsing to Use QuickJS and Make it Configurable

### LINKED ISSUE #8666: ReadComicOnline: No pages found error
### Source information

ReadComicOnline 1.4.35

### Source language

English 

### Steps to reproduce

1. Open any entry in Mihon(as I have checked it using Invincible(2003))
2. Select and chapters to read and then it chapter will not show it will give an error 
3. Error is image could not be loaded 
Image

Image

### Expected behavior

It should just show chapter's image, it is working fine in Aniyomi here is the image attached 

Image

### Actual behavior

Giving an error image could not be loaded 

### Mihon/Tachiyomi version

Mihon v 0.18.0

### Android version

Android 14

### Other details

Working fine with aniyomi preview r8065

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by JakeeLuwi**
Closes #8666 

This would ensure that any future breaking changes made by RCO can be fixed without bumping the extension as long as the problem is in the page list parsing only.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by vetleledaal — DISMISSED** [review]

**Comment by Hiirbaf** [comment]
The code has some problems on 3 lines

**Review by Hiirbaf — COMMENTED** [review]
It has lint issues on the lines 297, 560, 561 and 574, But other than that it's fine.

File: src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt [hunk 1]
```diff
@@ -206,54 +223,63 @@ class Readcomiconline : ConfigurableSource, ParsedHttpSource() {
...
             }
         }
 
-        return encryptedLinks.mapIndexed { idx, rawUrl ->
-            Page(idx, imageUrl = decryptLink(rawUrl, decryptionRegexKeys, ""))
+        return encryptedLinks.mapIndexedNotNull { idx, url ->
+            if (!remoteConfigItem!!.shouldVerifyLinks) {
+                Page(idx, imageUrl = url)
+            } else {
+                client.newCall(GET(url)).execute().use {
```
Comment (AwkwardPeak7) [inline src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt]: use HEAD request

File: src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt [hunk 2]
```diff
@@ -355,8 +383,28 @@ class Readcomiconline : ConfigurableSource, ParsedHttpSource() {
...
+                        .commit()
+
+                if (commitResult) {
+                    // Make it null so remoteConfigItem would request for a link again
+                    remoteConfigItem = null
+                }
+
+                commitResult
+            }
+        }
```
Comment (AwkwardPeak7) [inline src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt:405]: I am against making it configurable, as that may be abused

File: src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/ReadcomiconlinePageListDecrypt.kt
Comment (AwkwardPeak7) [inline src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/ReadcomiconlinePageListDecrypt.kt:1]: unused?

**Comment by JakeeLuwi** [comment]
Current commit won't work as there is no `config.json` on the main repo yet. For testing, use `https://raw.githubusercontent.com/JakeeLuwi/extensions-source/refs/heads/rco/src/en/readcomiconline/config.json` config instead.

**Review by AwkwardPeak7 — APPROVED** [review]
I am still against a remote config but ¯\\\_(ツ)\_/¯
