### PR TITLE
Uzay manga multi src

### LINKED ISSUE #11745: Make `multisrc` of Elder Manga, Uzay Manga, and Tenshi Manga
### Describe why this should be added

Elder Manga, Uzay Manga, and this Tenshi Manga all appear to have same site layout/theme, it would be better to create a multisrc out of it and have all three share the same code.

You can ask in our discord if you face any issue or want to ask questions regarding multisrcs

_Originally posted by @AwkwardPeak7 in https://github.com/keiyoushi/extensions-source/issues/10922#issuecomment-3382120003_

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11748: Elder Manga and Tenshi Manga Images are not loading
### Source information

Tenshi Manga 1.4.1 and Elder Manga 1.4.2

### Source language

Turkish 

### Steps to reproduce

These two sites use the same structure as Uzaymanga. Images don't load on these sites.

### Expected behavior

Image

### Actual behavior

Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Kraptor123**
changes: added uzaymanga as multi-src
it fixed: 
Elder Manga
Tenshi Manga

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

closes https://github.com/keiyoushi/extensions-source/issues/11748
closes https://github.com/keiyoushi/extensions-source/issues/11745

### CODE REVIEW

File: lib-multisrc/uzaymanga/src/eu/kanade/tachiyomi/multisrc/uzaymanga/UzayManga.kt [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+
+        return GET(url, headers)
+    }
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        val body = response.body.string()
+
+        if (body.contains("[]") || body.isBlank()) return MangasPage(emptyList(), false)
+
+        val dto = json.decodeFromString<List<SearchDto>>(body)
```
Comment (AwkwardPeak7) [inline lib-multisrc/uzaymanga/src/eu/kanade/tachiyomi/multisrc/uzaymanga/UzayManga.kt]: use `keiyoushi.utils.parseAs`

File: lib-multisrc/uzaymanga/src/eu/kanade/tachiyomi/multisrc/uzaymanga/UzayManga.kt [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+        }.toList()
+    }
+
+    override fun imageUrlParse(document: Document) = ""
+
+    private fun isMangaPage(document: Document): Boolean =
+        document.selectFirst("div.grid h2 + p") != null
+
+    private fun String.toDate(): Long =
+        try { dateFormat.parse(this)!!.time } catch (_: Exception) { 0L }
```
Comment (AwkwardPeak7) [inline lib-multisrc/uzaymanga/src/eu/kanade/tachiyomi/multisrc/uzaymanga/UzayManga.kt]: use `keiyoushi.utils.tryParse`

File: src/tr/eldermanga/src/eu/kanade/tachiyomi/extension/tr/eldermanga/ElderManga.kt [hunk 3]
```diff
@@ -1,192 +1,11 @@
...
-
-@Serializable
-class SearchDto(val id: Int, val name: String, val image: String)
+import eu.kanade.tachiyomi.multisrc.uzaymanga.UzayManga
+
+class ElderManga : UzayManga(
+    "Elder Manga",
+    "https://eldermanga.com",
+    lang = "tr",
+    versionId = 2,
```
Comment (AwkwardPeak7) [inline src/tr/eldermanga/src/eu/kanade/tachiyomi/extension/tr/eldermanga/ElderManga.kt]: is versionId bump needed?

File: src/tr/tenshimanga/src/eu/kanade/tachiyomi/extension/tr/tenshimanga/TenshiManga.kt [hunk 4]
```diff
@@ -1,192 +1,11 @@
...
-
-@Serializable
-class SearchDto(val id: Int, val name: String, val image: String)
+import eu.kanade.tachiyomi.multisrc.uzaymanga.UzayManga
+
+class TenshiManga : UzayManga(
+    name = "Tenshi Manga",
+    baseUrl = "https://tenshimanga.com",
+    lang = "tr",
+    versionId = 2,
```
Comment (AwkwardPeak7) [inline src/tr/tenshimanga/src/eu/kanade/tachiyomi/extension/tr/tenshimanga/TenshiManga.kt]: is versionId bump needed?

File: src/tr/uzaymanga/src/eu/kanade/tachiyomi/extension/tr/uzaymanga/UzayManga.kt [hunk 5]
```diff
@@ -1,166 +1,11 @@
...
-
-@Serializable
-class SearchDto(val id: Int, val name: String, val image: String)
+import eu.kanade.tachiyomi.multisrc.uzaymanga.UzayManga
+
+class UzayManga : UzayManga(
+    name = "Uzay Manga",
+    baseUrl = "https://uzaymanga.com",
+    lang = "tr",
+    versionId = 2,
```
Comment (AwkwardPeak7) [inline src/tr/uzaymanga/src/eu/kanade/tachiyomi/extension/tr/uzaymanga/UzayManga.kt]: is versionId bump needed?

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
