### PR TITLE
Ikuhentai: fix broken cover, chapters and pages

### LINKED ISSUE #14271: Ikuhentai: No covers, `No chapters found` error
### Source information

Ikuhentai 1.4.2

### Source language

Spanish 

### Steps to reproduce

2.Browse any manga and open a chapter not load.

3.Chapter list loads successfully, but pages (images) fail to load.

Image

Image

### Expected behavior

Images should load chapter and cover mangas

### Actual behavior

Images are not loading  in chapter and cover list

Image

Image

### Mihon/Mihon fork version

0.19.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14271

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 1]
```diff
@@ -1,190 +1,191 @@
...
-            manga.setUrlWithoutDomain(it.attr("href"))
-            manga.title = it.attr("title")
+        val img: Element? = element.selectFirst("img")
+        manga.thumbnail_url = img?.let {
+            it.attr("data-lazy-src").ifEmpty { it.attr("src") }.trim()
+        }
+
+        val link: Element? = element.selectFirst("div.item-thumb > a, div.tab-thumb > a")
+        if (link != null) {
+            manga.setUrlWithoutDomain(link.attr("href"))
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]:
```suggestion
            manga.setUrlWithoutDomain(link.absUrl("href"))
```

Same for `thumbnail_url`, possibly others.

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 2]
```diff
@@ -1,190 +1,191 @@
...
+            manga.title = link.attr("title").ifEmpty { link.text() }.trim()
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]: Already trimmed.
```suggestion
            manga.title = link.attr("title").ifEmpty { link.text() }
```

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 3]
```diff
@@ -1,190 +1,191 @@
...
-
     override fun mangaDetailsParse(document: Document): SManga {
-        val infoElement = document.select("div.site-content").first()!!
+        val infoElement: Element = document.selectFirst("div.site-content") ?: document
 
         val manga = SManga.create()
-        manga.author = infoElement.select("div.author-content").text()
-        manga.artist = infoElement.select("div.artist-content").text()
+        manga.author = infoElement.select("div.author-content").text().trim()
+        manga.artist = infoElement.select("div.artist-content").text().trim()
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]: Already trimmed. Possibly others.
```suggestion
        manga.author = infoElement.select("div.author-content").text()
        manga.artist = infoElement.select("div.artist-content").text()
```

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 4]
```diff
@@ -1,190 +1,191 @@
...
         else -> SManga.UNKNOWN
     }
 
+    override fun chapterListRequest(manga: SManga): Request {
+        val url = baseUrl + manga.url
+        return if (url.endsWith("/")) {
+            POST("${url}ajax/chapters/", headers)
+        } else {
+            POST("$url/ajax/chapters/", headers)
+        }
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]: Remove suffix? Then you can unconditionally use just one `POST()`.

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 5]
```diff
@@ -1,190 +1,191 @@
...
-        val urlElement = element.select("a").first()!!
-        var url = urlElement.attr("href")
-        url = url.replace("/p/1", "")
-        url += "?style=list"
+        val urlElement: Element = element.selectFirst("a")!!
+        var url = urlElement.attr("href").trim()
+        url = url.substringBefore("?style=paged")
+        if (!url.contains("?style=list")) {
+            url += if (url.contains("?")) "&style=list" else "?style=list"
+        }
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]: Use `HttpUrl` to append query params.

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 6]
```diff
@@ -1,190 +1,191 @@
...
         }.build()
         return GET(page.imageUrl!!, imgHeader)
     }
 
-    //    private class Status : Filter.TriState("Completed")
+    private fun parseDate(dateStr: String): Long = try {
+        dateFormat.parse(dateStr)?.time ?: 0L
+    } catch (e: Exception) {
+        0L
+    }
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]: Use `.tryParse()` from `keiyoushi.utils`.

**Review by vetleledaal — CHANGES_REQUESTED** [review]

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 7]
```diff
@@ -1,190 +1,182 @@
...
+        val genres = infoElement.select("div.genres-content a").map { it.text() }
         manga.genre = genres.joinToString(", ")
-        manga.status = parseStatus(infoElement.select("div.post-status > div:nth-child(2) > div.summary-content").text())
 
-        manga.description = document.select("div.description-summary").text()
-        manga.thumbnail_url = document.select("div.summary_image > a > img").attr("data-src")
+        val statusText = infoElement.select("div.post-content_item:has(h5:contains(Estado)) div.summary-content").text()
+        manga.status = parseStatus(statusText)
+
+        manga.description = document.select("div.description-summary").text().trim()
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]:
```suggestion
        manga.description = document.select("div.description-summary").text()
```

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 8]
```diff
@@ -1,190 +1,182 @@
...
+        val urlElement: Element = element.selectFirst("a")!!
+        val url = urlElement.absUrl("href").toHttpUrl().newBuilder().apply {
+            removeAllQueryParameters("style")
+            addQueryParameter("style", "list")
+        }.build().toString()
+
         val chapter = SChapter.create()
         chapter.setUrlWithoutDomain(url)
-        chapter.name = urlElement.text()
+        chapter.name = urlElement.text().trim()
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]:
```suggestion
        chapter.name = urlElement.text()
```

File: src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt [hunk 9]
```diff
@@ -1,190 +1,182 @@
...
-        val basic = Regex("""Chapter\s([0-9]+)""")
-        when {
-            basic.containsMatchIn(chapter.name) -> {
-                basic.find(chapter.name)?.let {
-                    chapter.chapter_number = it.groups[1]?.value!!.toFloat()
-                }
-            }
+        val dateElement: Element? = element.selectFirst("span.chapter-release-date i")
+        dateElement?.let {
+            chapter.date_upload = dateFormat.tryParse(it.text().trim())
```
Comment (vetleledaal) [inline src/es/ikuhentai/src/eu/kanade/tachiyomi/extension/es/ikuhentai/Ikuhentai.kt]:
```suggestion
            chapter.date_upload = dateFormat.tryParse(it.text())
```

**Comment by darwin-256** [comment]
removed all trims

**Review by vetleledaal — APPROVED** [review]
