### PR TITLE
Mintmanga: Fix image loading

### LINKED ISSUE #6616: MintManga (RU): chapter images showing stub picture
### Source information

MintManga 1.4.72

### Source language

Russian

### Steps to reproduce

1. Login to MintManga from webview
1. Open any title from MintManga (picking from Popular section should work)
2. Open any chapter of title
3. Open any page of chapter

### Expected behavior

Chapter should contain actual pictures from chapter, as they present on web view

### Actual behavior

All pages of every chapter show this picture 
Ночные этюды - 4 - 131 Эпилог  Часть 2 - 1

### Mihon/Tachiyomi version

0.17.1 (standard, 3a100c7, 9, 2024-12-06T17:14:05Z) 

### Android version

13 (SDK 33; build TKQ1.221114.001)

### Other details

It might be that patch for AllHentai can be ported to this source extension, as viewing chapters from browser or webview also show that webpage URL carried query parameter `d`, like `https://2.mintmanga.one/.../vol1/1?mtr=true&d=xxxxxxxx`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Dr1ks**
Closes #6616 

Also included a minor fix to correctly identify licensed manga on Mintmanga.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/MintManga.kt [hunk 1]
```diff
@@ -20,6 +21,16 @@ class MintManga : GroupLe("MintManga", "https://1.mintmanga.com", "ru") {
 
     override val baseUrl by lazy { getPrefBaseUrl() }
 
+    override fun getChapterSearchParams(document: Document): String {
+        val html = document.html()
+
+        val userHashRegex = "user_hash.+'(.+)'".toRegex()
```
Comment (vetleledaal) [inline src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/MintManga.kt]: Extract regex to avoid reinitializing on each invocation.

Comment (vetleledaal) [inline src/ru/mintmanga/src/eu/kanade/tachiyomi/extension/ru/mintmanga/MintManga.kt]: Where is `user_hash` stored? in a `<script>`? You can use Jsoup for this, so it's narrowed down a bit:
```kt
val scripts = document.select("script").joinToString("\n") { it.data() }
// or
val script = document.selectFirst("script:containsData(user_hash)")
```

or a combination if `user_hash` is referenced in multiple places.

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt
Comment (AwkwardPeak7) [inline lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:1]: bump `baseVersionCode`

File: src/ru/mintmanga/build.gradle [hunk 2]
```diff
@@ -2,8 +2,8 @@ ext {
     extName = 'MintManga'
     extClass = '.MintManga'
     themePkg = 'grouple'
-    baseUrl = 'https://1.mintmanga.com'
-    overrideVersionCode = 46
+    baseUrl = 'https://2.mintmanga.one'
+    overrideVersionCode = 47
```
Comment (vetleledaal) [inline src/ru/mintmanga/build.gradle]: If you're bumping the base version you don't need to bump this as well.

Comment (Dr1ks) [reply src/ru/mintmanga/build.gradle]: Sorry, I forgot to remove it since I initially prepared the fix only for mintmanga

**Review by vetleledaal — APPROVED** [review]
