### PR TITLE
YugenMangas: Fix content loading

### LINKED ISSUE #10391: Yugen Mangás: `HTTP 404` error
### Source information

Yuzen Mangás 1.4.48

### Source language

Português Brasil - PT-BT

### Source new URL

https://yugenmangasbr.dxtg.online/
(Last updated: 11/11/2025)

### Other details

Image

Image

Image

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #10391

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangas.kt [hunk 1]
```diff
@@ -218,6 +219,29 @@ class YugenMangas : HttpSource(), ConfigurableSource {
...
+            .firstOrNull { script -> GET_JSON_BODY_REGEX.containsMatchIn(script) }
+            ?: throw Exception(warning)
+        val values = GET_JSON_BODY_REGEX.find(script)?.groupValues?.filter(String::isNotBlank)
+        return values?.last()
+            ?.replace(ESCAPE_QUOTATION_MARK_REGEX, "\"")
+            ?: throw Exception("Erro ao analisar os dados")
+    }
+
+    private fun parseRelativeDate(date: String): Long {
+        val number = Regex("""(\d+)""").find(date)?.value?.toIntOrNull() ?: return 0
```
Comment (vetleledaal) [inline src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangas.kt]: Regex is an invariant, extract to class. You also don't need a capture group.

File: src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangas.kt [hunk 2]
```diff
@@ -218,6 +219,29 @@ class YugenMangas : HttpSource(), ConfigurableSource {
...
     }
 
+    private fun Response.getJsonBody(): String {
+        val document = asJsoup()
+        val script = document.select("script").map(Element::data)
+            .firstOrNull { script -> GET_JSON_BODY_REGEX.containsMatchIn(script) }
+            ?: throw Exception(warning)
+        val values = GET_JSON_BODY_REGEX.find(script)?.groupValues?.filter(String::isNotBlank)
+        return values?.last()
+            ?.replace(ESCAPE_QUOTATION_MARK_REGEX, "\"")
```
Comment (vetleledaal) [inline src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangas.kt]: Are you trying to unescape a JSON string here?

Maybe look into approach in https://github.com/keiyoushi/extensions-source/blob/a229f392e13067105dab0b45ddb25b46096a2d18/lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt#L231-L236

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
