### PR TITLE
Vortex Scans: Fix no pages found

### LINKED ISSUE #6930: Vortex Scans No Pages Found
### Source information

Vortex Scans 1.4.41

### Source language

English

### Steps to reproduce

1. Open any series in the Vortex Scans extension
2. Attempt to open any chapter

### Expected behavior

The chapter should open and start loading images.

### Actual behavior

A 'No pages found' message appears.

### Mihon/Tachiyomi version

Mihon v0.17.1

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #6930

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt [hunk 1]
```diff
@@ -1,9 +1,36 @@
...
+    private val json by injectLazy<Json>()
+
+    override fun pageListParse(response: Response): List<Page> {
+        val document = response.asJsoup()
+
+        val images = document.selectFirst("script:containsData(images)")
+            ?.data()
+            ?.substringAfter("\\\"images\\\":")
+            ?.substringBefore(",\\\"next")
+            ?.replace("""\"""", "\"")
```
Comment (AwkwardPeak7) [inline src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]: consider using a regex

Comment (dngonz) [reply src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]: Any approach suggestion? I'm a bit lost

Comment (vetleledaal) [reply src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]:
```kt
"""\\"images\\":(.*?)\\"next""".toRegex()
```

You can get the inner value via `.groupValues[1]` or `.destructured`

Comment (dngonz) [reply src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]: Thanks @vetleledaal already changed your way

File: src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt [hunk 2]
```diff
@@ -1,9 +1,37 @@
...
+
+    private val regexImages = """\\"images\\":(.*?)\\"next""".toRegex()
+
+    override fun pageListParse(response: Response): List<Page> {
+        val document = response.asJsoup()
+
+        val images = document.selectFirst("script:containsData(images)")
+            ?.data()
+            ?.let { regexImages.find(it)!!.groupValues[1].trim(',') }
+            ?.replace("""\"""", "\"")
```
Comment (vetleledaal) [inline src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]: Instead of this `replace`, can you get kotlinx.serialize to do it for you?
```kt
?.let { json.decodeFromString<String>("\"$it\"") }
```

I have not tested it, but you will essentially be offloading the parsing of escape sequences to a proper library.

Comment (dngonz) [reply src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]: Works perfectly

**Review by vetleledaal — APPROVED** [review]
