### PR TITLE
Change URL Swatmanga

### LINKED ISSUE #1380: Manga swat change their url
### Source information

Mangaswat 1.4.43

### Source language

Arabic

### Source new URL

https://swatmanhua.com/

### Other details

I try change link from suroce Settings to the new one but it still not work

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by mohamedotaku**
Close #1380
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — APPROVED** [review]

File: src/ar/mangaswat/src/eu/kanade/tachiyomi/extension/ar/mangaswat/MangaSwat.kt [hunk 1]
```diff
@@ -23,11 +23,11 @@ import java.util.Locale
 
 class MangaSwat : MangaThemesia(
     "MangaSwat",
-    "https://goldragon.me",
+    "https://swatmanhua.com",
```
Comment (AwkwardPeak7) [inline src/ar/mangaswat/src/eu/kanade/tachiyomi/extension/ar/mangaswat/MangaSwat.kt]: create a constant out of the class (top/bottom of this file) for the url and use that here in the constructor and in `defaultBaseUrl `

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/ar/mangaswat/src/eu/kanade/tachiyomi/extension/ar/mangaswat/MangaSwat.kt (hunk 1 above)
Comment (mohamedotaku) [reply src/ar/mangaswat/src/eu/kanade/tachiyomi/extension/ar/mangaswat/MangaSwat.kt]: > create a constant out of the class (top/bottom of this file) for the url and use that here in the constructor and in `defaultBaseUrl `

done

**Review by AwkwardPeak7 — APPROVED** [review]
