### PR TITLE
Hijala: fix scrambled images

### LINKED ISSUE #12647: Hijala (AR): Some chapter images are displayed split
### Source information

Hijala

### Source language

Arabic 

### Steps to reproduce

the chapters don't show correctly on the mihon app we did try with the staf in mihon server to fix it but we did conclusion that it's the extension problem, the problem is that the lastest chapters don't show correctly the get showered like cropped in half 

### Expected behavior

the source should provide the whole chapter not just half

### Actual behavior

it shows only half💔

### Mihon/Tachiyomi version

0.19.3 mihon

### Android version

11

### Other details

Image
Image
Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by xMohnad**
Closes #12647

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ar/hijala/src/eu/kanade/tachiyomi/extension/ar/hijala/Hijala.kt [hunk 1]
```diff
@@ -11,6 +28,105 @@ class Hijala :
...
+                    val pieceRequest = request.newBuilder().url(pieceUrl).build()
+                    client.newCall(pieceRequest).await().use { response ->
+                        response.body.use { body ->
+                            val decoder = ImageDecoder.newInstance(body.byteStream())
+                                ?: throw Exception("Failed to create decoder for $pieceUrl")
+                            try {
+                                decoder.decode() ?: throw Exception("Failed to decode $pieceUrl")
+                            } finally {
+                                decoder.recycle()
+                            }
```
Comment (AwkwardPeak7) [inline src/ar/hijala/src/eu/kanade/tachiyomi/extension/ar/hijala/Hijala.kt]: use `android.graphics.bitmapFactory` instead, as the images on the site appear to be jpegs. Tachiyomi ImageDecoder is only needed when bitmapFactory fails, usually for avif.

also suwayomi doesn't support Tachiyomi ImageDecoder

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
