### PR TITLE
Colored Manga | Fix Latest, Pages Count, Fix Title Search

### LINKED ISSUE #4593: Coloredmanga search or filter not working
### Source information

Coloredmanga 1.4.35

### Source language

English

### Steps to reproduce

1. Open extension
2. Search any series available on the site or use the filter function in general
3. Shows no result found

### Expected behavior

The series I'm searching for should be shown.

### Actual behavior

Screenshot_2024-08-13-16-26-48-06_551f7f0ca926862b368845ce7ee433aa
Shows no result found when the series is clearly available in the website. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

I tried searching for a series that was shown in the home page of the extension but that didn't work either. The series I'm trying to find is nowhere in the front page and scrolling endlessly is painful so I'm hoping the search gets fixed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #4618: ColoredManga Source not loading all pages for Chapter
### Source information

Colored Manga 1.4.35

### Source language

English

### Steps to reproduce

Go to **One Piece (Coloured)** in the Colored Manga source in Mihon.
Open chapter 212.

### Expected behavior

Should see 19 pages total. 

### Actual behavior

Only see 18 pages total. 

### Mihon/Tachiyomi version

Mihon Beta r6820

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #4593 
Closes #4618

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/coloredmanga/src/eu/kanade/tachiyomi/extension/en/coloredmanga/ColoredManga.kt [hunk 1]
```diff
@@ -139,7 +139,8 @@ class ColoredManga : HttpSource() {
             val includeColor = colorIncluded.isEmpty() || colorIncluded.contains(it.version)
             val excludeColor = colorExcluded.isNotEmpty() && colorExcluded.contains(it.version)
 
-            val regularSearch = it.name.contains(title) || it.synopsis.contains(title)
+            val regularSearch = it.name.lowercase().contains(title) || it.synopsis.lowercase().contains(title)
```
Comment (AwkwardPeak7) [inline src/en/coloredmanga/src/eu/kanade/tachiyomi/extension/en/coloredmanga/ColoredManga.kt]:
```suggestion
            val regularSearch = it.name.contains(title, true) || it.synopsis.contains(title, true)

```

File: src/en/coloredmanga/src/eu/kanade/tachiyomi/extension/en/coloredmanga/ColoredManga.kt [hunk 2]
```diff
@@ -139,7 +139,9 @@ class ColoredManga : HttpSource() {
             val includeColor = colorIncluded.isEmpty() || colorIncluded.contains(it.version)
             val excludeColor = colorExcluded.isNotEmpty() && colorExcluded.contains(it.version)
 
-            val regularSearch = it.name.contains(title) || it.synopsis.contains(title)
+            val regularSearch = it.name.contains(title, true) || it.synopsis.contains(title, true)
+
```
Comment (AwkwardPeak7) [inline src/en/coloredmanga/src/eu/kanade/tachiyomi/extension/en/coloredmanga/ColoredManga.kt:143]:
```suggestion

```

**Review by AwkwardPeak7 — APPROVED** [review]
