### PR TITLE
fix(rokaricomics): Fix search and hide paywalled chapters

### LINKED ISSUE #11830: RokariComics: `No results found` error
### Source information

RokariComics 1.4.31

### Source language

English

### Steps to reproduce

1.open the extension
2.no results are found

### Expected behavior

The entries should appear

### Actual behavior

No results are found whereas the already bookmarked entries update and download chapters, though even paid chapters are showing up as well

### Mihon/Tachiyomi version

Mihon 0.19.3

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11843: RokariComics: Hide paywalled chapters
### Source name

RokariComics

### Source language

English

### Describe your suggested feature

The RokariComics extension is picking up the paywalled chapters that it cannot access yet. It'll just show up as no pages found. I request for there to be a feature that can hide the unavailable chapters.

Image

Image

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SuperMario22922**
- Fix 'No results found' by using /?s= search endpoint instead of /manga/
- Add Popular section using homepage 'Popular Today'
- Add Latest section using homepage pagination
- Hide paywalled chapters (chapters with coin cost indicator)

Fixes keiyoushi/extensions-source#11830
Fixes keiyoushi/extensions-source#11843

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/rokaricomics/src/eu/kanade/tachiyomi/extension/en/rokaricomics/RokariComics.kt [hunk 1]
```diff
@@ -1,14 +1,120 @@
...
 ) {
-    override fun chapterListSelector() = "#chapterlist li:has(div.chbox):has(div.eph-num):has(a[href])"
+    // Popular - Use homepage "Popular Today" section (first page only, no pagination)
+    override fun popularMangaRequest(page: Int): Request {
+        return if (page == 1) {
+            GET(baseUrl, headers)
+        } else {
+            // Return empty page for page > 1 since Popular Today is not paginated
+            GET("$baseUrl/page/0/", headers)
+        }
```
Comment (AwkwardPeak7) [inline src/en/rokaricomics/src/eu/kanade/tachiyomi/extension/en/rokaricomics/RokariComics.kt]:
```suggestion
        GET(baseUrl, headers)
```
you already pass `hasNextPage=false`, so no need to provide alternative code path

File: src/en/rokaricomics/src/eu/kanade/tachiyomi/extension/en/rokaricomics/RokariComics.kt [hunk 2]
```diff
@@ -1,14 +1,120 @@
...
+    }
+
+    override fun popularMangaParse(response: Response): MangasPage {
+        if (!response.request.url.toString().endsWith("/page/0/")) {
```
Comment (AwkwardPeak7) [inline src/en/rokaricomics/src/eu/kanade/tachiyomi/extension/en/rokaricomics/RokariComics.kt]: remove condition check, just pass `hasNextPage=false` in `MangasPage`

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
