### PR TITLE
ScansFR : fix chapters download

### LINKED ISSUE #14138: ScansFR api issue
### Source information

1.4.1

### Source language

French

### Steps to reproduce

1. The title list loads
2. The list of chapters loads
3. Webview loads this Link:
https://api.scansfr.com/api/v1/mangas/martial-peak
4. Read the chapter works. 
5. Downloading chapters does not work. 
THX

### Expected behavior

Loading the Webview
Downloading chapters

### Actual behavior

Webview does not load. 
Failed to download. 

### Mihon/Mihon fork version

0.19.4-7580

### Android version

16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by luigidotmoe**
Closes #14138

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/scansfr/src/eu/kanade/tachiyomi/extension/fr/scansfr/ScansFR.kt [hunk 1]
```diff
@@ -183,7 +185,7 @@ class ScansFR :
 
     // =============================== Pages ================================
 
-    override fun pageListRequest(chapter: SChapter): Request = throw UnsupportedOperationException()
+    override fun pageListRequest(chapter: SChapter): Request = GET("$baseUrl${chapter.url}", headers)
```
Comment (bapeey) [inline src/fr/scansfr/src/eu/kanade/tachiyomi/extension/fr/scansfr/ScansFR.kt]: Override `getChapterUrl()` instead

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by EddyOops** [comment]
Hi. The download is not resolved with 1.4.2.  
Webview access is resolved.
Thank you

**Comment by luigidotmoe** [comment]
> Hi. The download is not resolved with 1.4.2. Webview access is resolved. Thank you

Looks like something changed in their API, maybe to break this extension on purpose (since reading also broke, not only downloading). 
Please create a new issue, I'll look into it

**Comment by EddyOops** [comment]
> > Hi. The download is not resolved with 1.4.2. Webview access is resolved. Thank you
> 
> Looks like something changed in their API, maybe to break this extension on purpose (since reading also broke, not only downloading). Please create a new issue, I'll look into it

Thank you 
https://github.com/keiyoushi/extensions-source/issues/14173
