### PR TITLE
WeebDex: Fix chapter title suffix

### LINKED ISSUE #12834: WeebDex chapter title format exception
### Source information

WeebDex 1.4.4

### Source language

English

### Steps to reproduce

Open a manga with chapter numbering that include a letter (e.g., Ch. 26a)

Image

### Expected behavior

Chapter list should have appeared

### Actual behavior

It threw an exception

Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MuhamadSyabitHidayattulloh**
Closes: https://github.com/keiyoushi/extensions-source/issues/12834
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/weebdex/src/eu/kanade/tachiyomi/extension/all/WeebDexHelper.kt [hunk 1]
```diff
@@ -30,4 +30,11 @@ class WeebDexHelper {
     fun parseDate(dateStr: String): Long {
         return dateFormat.tryParse(dateStr)
     }
+
+    fun parseChapterNumber(chapter: String?): Float {
```
Comment (AwkwardPeak7) [inline src/all/weebdex/src/eu/kanade/tachiyomi/extension/all/WeebDexHelper.kt:34]: you are not using this function? forgot to push to git?

**Review by AwkwardPeak7 — APPROVED** [review]
