### PR TITLE
Vortex Scans: Fix `Popular` & update `Latest` tabs

### LINKED ISSUE #10440: Vortex Scans broken parsing
### Source information

Vortex Scans 1.4.47

### Source language

English

### Steps to reproduce

Browse the list of Popular titles.

### Expected behavior

The list of titles should be shown.

### Actual behavior

The list shown is empty. However, the actual list is shown in WebView.

### Mihon/Tachiyomi version

Komikku Beta r10183

### Android version

Android 15

### Other details

The list of Latest titles works fine, it's just the list of Popular titles that's broken.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Smol-Ame**
Closes #10440
* Copied & adjusted Latest request code to fix/override Popular request
* Override Latest request code with current tag (observed via browser network tool)
* Applied suggestion & retested

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt [hunk 1]
```diff
@@ -2,12 +2,41 @@ package eu.kanade.tachiyomi.extension.en.arvenscans
...
 ) {
-    override fun popularMangaRequest(page: Int) = GET(baseUrl, headers)
+    override fun latestUpdatesRequest(page: Int): Request {
+        val url = "$apiUrl/api/posts".toHttpUrl().newBuilder().apply {
+            addQueryParameter("page", page.toString())
+            addQueryParameter("perPage", perPage.toString())
+            if (apiUrl.startsWith("https://api.", true)) {
+                addQueryParameter("tag", "new")
+                addQueryParameter("isNovel", "false")
+            }
```
Comment (bapeey) [inline src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]:
```suggestion
            addQueryParameter("tag", "new")
            addQueryParameter("isNovel", "false")
```

Comment (bapeey) [reply src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt]: Same for `popularMangaRequest` :whip:

**Review by AwkwardPeak7 — APPROVED** [review]
