### PR TITLE
GreenShit: Fix

### LINKED ISSUE #9289: Sussy Toons: `HTTP error 404` when trying to access chapters
### Source information

Sussy toons1.4.60

### Source language

Português (Brasil)

### Steps to reproduce

Quando coloco no capítulo da obra da erro estava entrando normalmente hoje a tarde agora fui tentar ler e o capítulo não está abrindo

### Expected behavior

Deveria abrir , já vi no site e está normal

### Actual behavior

Não está abrindo nenhum capítulo da extensão da Sussy toons

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15

### Other details

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9353: Wind Scan: `No chapters found` error
Image

### Source information

Wind Scan 1.4.45

### Source language

Português(Brazil)

### Steps to reproduce

Some works do not look like chapters even though the website has these chapters 

### Expected behavior

the chapters should open normally since they are on the website

### Actual behavior

On the website they are normal and working

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 14

### Other details

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9367: Maid Scan não encontra as páginas dos capítulos
### Source information

Maid Scan 1.4.50

### Source language

Português brasileiro 

### Steps to reproduce

Ao entrar em um capítulo ele não encontra as páginas mesmo com o site funcionando 

Image

### Expected behavior

Entra no capítulo e aparecer as páginas 

### Actual behavior

Ao entrar no capítulo não carrega e aparecer o erro 404

Image

Image

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 6

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes  #9289
Closes #9353
Closes #9367

Lá vamos nós

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — COMMENTED** [review]
use `T.toJsonString()` from keiyoushi.utils to encode json strings

**Comment by Smol-Ame** [comment]
Guessing this also applies to (recently opened) 9367?

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 1]
```diff
@@ -226,8 +192,27 @@ abstract class GreenShit(
...
+            .set("authorization", "Bearer $token")
+            .build()
+        return GET("$apiUrl$pathSegment", newHeaders)
+    }
+
+    private fun generateToken(scanId: Long, secretKey: String): String {
+        val timestamp = System.currentTimeMillis() / 1000
+        val expiration = timestamp + 3600
+
+        val payload = """{"scan_id":$scanId,"timestamp":$timestamp,"exp":$expiration}"""
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt]: Use `buildJsonObject` to separate concerns when it comes to encoding the values.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 2]
```diff
@@ -284,6 +275,54 @@ abstract class GreenShit(
...
+                Token(tokenDto.value).also {
+                    _cache = it.save()
+                }
+            } ?: throw IOException("Adicione suas credenciais em Extensões > $name > Configurações")
+        }
+
+    val loginClient = network.cloudflareClient
+
+    fun doLogin(credential: Credential): Response {
+        val payload = """{"usr_email":"${credential.email}","usr_senha":"${credential.password}"}""".toRequestBody("application/json".toMediaType())
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt]: Use `buildJsonObject` here too.

**Review by vetleledaal — APPROVED** [review]
