### PR TITLE
YomuComics: fix Unexpected JSON token at offset

### LINKED ISSUE #12397: Yomu Comics - Unexpected JSON token at offset
### Source information

Yomu Comics 1.4.39

### Source language

Portuguese (Brazil)

### Steps to reproduce

Try to update a title or open the webview.

### Expected behavior

If it worked...

### Actual behavior

Image
Image

### Mihon/Tachiyomi version

Komikku 1.13.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes: #12397

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 1]
```diff
@@ -19,10 +19,10 @@ class MangaDto(
     val slug: String,
     val cover: String? = null,
 ) {
-    fun toSManga(): SManga = SManga.create().apply {
+    fun toSManga(baseUrl: String): SManga = SManga.create().apply {
         title = this@MangaDto.title
         thumbnail_url = cover
-        url = "/obra/$slug"
+        url = "$baseUrl/obra/$slug"
```
Comment (AwkwardPeak7) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]: why abs urls?

Comment (FelipeGFA) [reply src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]: if i dont use abs url, toSManga and toSChapter redirects to api and i dont know why

Comment (choppeh) [reply src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]: > if i dont use abs url, toSManga and toSChapter redirects to api and i dont know why

override the `getMangaUrl` and `getChapterUrl` to fix WebView. These two methods are used to redirect to the webpage.

Ex https://github.com/keiyoushi/extensions-source/pull/12405

**Review by AwkwardPeak7 — APPROVED** [review]
