### PR TITLE
Luscious: fix 403 error + Open URL in app (closes #10924)

### LINKED ISSUE #10924: Luscious extensions 403 error
### Source information

Luscious 1.4.22

### Source language

English 

### Steps to reproduce

1. Browse from source
2. Pick random title
3. The chapter list showing, all showed
4. Try to read 1 chapter, any chapter
5. When trying to view anything you get error

Image

### Expected behavior

It should just display the image 

### Actual behavior

Error http 403 

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 16

### Other details

Web view same error

Image

Try with different VPN connection 

Aswell Go to Luscious extension settings, then go into the Language settings, and change the Mirror to "Guest" or "API". Then restart the app 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by CriosChan**
Closes #10924 

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by shaneervin0-png** [comment]
For someone who isn't good with code what do I need to do to fix this bug based on the information mentioned above?

**Comment by Smol-Ame** [comment]
@shaneervin0-png you wait patiently for this PR to be reviewed & approved, then the extension will get an update.

Wait patiently, otherwise migrate to a different source.

File: src/all/luscious/src/eu/kanade/tachiyomi/extension/all/luscious/Luscious.kt [hunk 1]
```diff
@@ -55,6 +56,11 @@ abstract class Luscious(
 
     private val json: Json by injectLazy()
 
+    override fun headersBuilder(): Headers.Builder {
+        return Headers.Builder()
+            .add("Referer", getMirrorPref() ?: "https://www.luscious.net/")
+    }
```
Comment (AwkwardPeak7) [inline src/all/luscious/src/eu/kanade/tachiyomi/extension/all/luscious/Luscious.kt:62]:
```suggestion
    override fun headersBuilder(): Headers.Builder {
        return super.headersBuilder()
            .add("Referer", "$baseUrl/")
    }
```
preserve app provided useragent

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/all/luscious/src/eu/kanade/tachiyomi/extension/all/luscious/Luscious.kt (hunk 1 above)
Comment (CriosChan) [reply src/all/luscious/src/eu/kanade/tachiyomi/extension/all/luscious/Luscious.kt:62]: Thank you for the review !

**Review by AwkwardPeak7 — APPROVED** [review]
