### PR TITLE
HentaiRead: fix page parsing

### LINKED ISSUE #2902: "No page found" Hentairead
### Source information

HentaiRead 1.4.40

### Source language

English

### Steps to reproduce

1. Press any Manga that has the HentaiRead extension can be in the Extension Browser or own Saved Catalog (except downloaded)
2. Choose any chapter of the Manga/Doujin to read

### Expected behavior

Would be able to read said Chapter or Manga (weirdly just a day ago not more than 6 hours ago)

### Actual behavior

Screenshot_2024-05-09-21-58-58-15_afd66b7916d19a60815f56273408b73e

"No pages found" in both the Saved Catalog and on the Extension search

### Mihon/Tachiyomi version

Mihon 0.15.3 and used others like Tachiyomi [OG], Tachiyomi Sy and etc. for cross reference

### Android version

Android 10

### Other details

- Also I have accessed it yesterday it was fine.
- I have accessed it via both the site and Webview both are accesible only the extension have a problem tried other extensions all seems fine
- Curiously enough I have not updated the extension and thought it was the root of the problem but as I have updated it (and subsequently tried it on different Tachi Apps and Mihon) its still shows "No pages found"
- This is not the definite answer probably weird hypothesis but I think I noticed the HentaiRead site had a UI changes? I dont remember some of the minute details but I think there was suppossed to be a pressable chapters (i.e. Chapter 1..... Updated 1/13/24) on a list there rather than using the "Read" icon to see the doujin

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes  #2902

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 1]
```diff
@@ -17,6 +19,8 @@ import java.util.Locale
 
 class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.US)) {
 
+    override val json = Json { ignoreUnknownKeys = true }
```
Comment (AwkwardPeak7) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: what's wrong with the singelton json instance?

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 2]
```diff
@@ -71,9 +74,15 @@ class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateForm
             listOf(
                 SChapter.create().apply {
                     name = "Chapter"
-                    url = manga.url
+                    // There's like 2 non-English entries where this breaks
+                    url = "${manga.url}english/p/1/"
```
Comment (AwkwardPeak7) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: users would have to refresh chapter list, you can override `pageListRequest` to avoide that, altho this isn't really that important

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt (hunk 1 above)
Comment (vetleledaal) [reply src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: I thought it was erroring out, but when retesting that's not the case. I'll remove it. Probably ran into the issue of fixing two things at once 🤐

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 3]
```diff
@@ -76,4 +76,15 @@ class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateForm
             ),
         )
     }
+
+    override fun pageListRequest(chapter: SChapter): Request {
+        // There's like 2 non-English entries where this breaks
+        chapter.url = "${chapter.url}english/p/1/"
+        return super.pageListRequest(chapter)
```
Comment (AwkwardPeak7) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: dont update url in schapter, I belive j2k ends up updating the url in db when this happens. (at least for smanga url)

Comment (vetleledaal) [reply src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: ~~I checked J2K and it seems to work fine. It is in any case desirable to not propagate changes if they decide to change the behavior in the future. I'll copy the object over instead.~~ 

Went with another approach as discussed on Discord.

**Review by AwkwardPeak7 — APPROVED** [review]
