### PR TITLE
ArgosScan: Fixes

### LINKED ISSUE #8992: Argos Scan (PT-Br Source) Don't show content!
### Source information

Argos Scan 1.4.24

### Source language

Portuguese Brazilian 

### Steps to reproduce

Don't show content.

### Expected behavior

Show content.

### Actual behavior

Error in source

Image
Image

### Mihon/Tachiyomi version

0.18.0-7249

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #8992

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/argosscan/src/eu/kanade/tachiyomi/extension/pt/argosscan/ArgosScanDto.kt [hunk 1]
```diff
@@ -1,47 +1,42 @@
...
+    val id: String,
+    val type: String,
+) {
+    fun toSManga(baseUrl: String) = SManga.create().apply {
+        title = details.title.values.first()
+        description = details.description.values.first()
+        genre = details.genres.joinToString()
+        thumbnail_url = "$baseUrl/$thumbnailUrl"
+        status = details.status.toStatus()
+        url = this@MangaDto.id
```
Comment (AwkwardPeak7) [inline src/pt/argosscan/src/eu/kanade/tachiyomi/extension/pt/argosscan/ArgosScanDto.kt]: old urls were saved as relative, so this could break those

**Review by AwkwardPeak7 — APPROVED** [review]
