### PR TITLE
NHentai: fix thumbnails

### LINKED ISSUE #9897: Nhentai cover image doesn't show
### Source information

Nhentai 1.4.52

### Source language

Multi

### Steps to reproduce

The cover image was fine in list
Image
Click a manga
Then the cover image doesn't show
Image

### Expected behavior

The cover image appears

### Actual behavior

The cover image does not appear

Image

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes https://github.com/keiyoushi/extensions-source/issues/9897

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt [hunk 1]
```diff
@@ -255,30 +247,37 @@ open class NHentai(
...
             )
         }
     }
 
+    private fun Document.getHentaiData(): Hentai {
+        val script = selectFirst(hentaiSelector)!!.data()
+        return dataRegex.find(script)!!.groupValues[1].parseAs()
+    }
+
+    private fun Document.getCDNs(thumbnail: Boolean = false): List<String> {
```
Comment (stevenyomi) [inline src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt]: Two nitpicks:
1. Should probably use `getCdns` (or `getCdnUrls`)
2. Don't add a default argument value since there are only 2 call sites

**Review by stevenyomi — APPROVED** [review]
