### PR TITLE
en/AscalonScans: Fix http 403

### LINKED ISSUE #347: AscalonScans: HTTP 403
### Source information

AscalonScans 1.4.27

### Source language

English

### Steps to reproduce

1. Install AscalonScans extension
2. Open the extension
3. HTTP 403, check website in WebView error message appears

### Expected behavior

Display available manhwas etc instead of error message

### Actual behavior

error message appears, but site works fine in webview 

### Tachiyomi version

0.15.2

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #347

The interessing part is that the js challenge itself sometimes fails miserably in the browser, but seems to be working just fine in the interceptor (tested in two different devices).
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        if (origRes.code != 403) return origRes
+        origRes.close()
+
+        val token = fetchToken(chain).sha256()
+
+        val body = FormBody.Builder().add("challenge", token).build()
+        val challengeReq = POST("$baseUrl/hcdn-cgi/jschallenge-validate", headers, body = body)
+        chain.proceed(challengeReq).use {
+            if (it.code != 200) throw IOException("Failed to bypass js challenge!")
+        }
```
Comment (stevenyomi) [inline multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt]: Could you just close it?

File: multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+        return chain.proceed(request)
+    }
+
+    private fun fetchToken(chain: Interceptor.Chain, attempt: Int = 0): String {
+        if (attempt > 5) throw IOException("Failed to fetch challenge token!")
+        val request = GET("$baseUrl/hcdn-cgi/jschallenge", headers)
+        val res = chain.proceed(request).body.string()
+
+        return res.substringAfter("cjs = '").substringBefore("'")
+            .takeUnless { it == "nil" } ?: fetchToken(chain, attempt + 1)
```
Comment (stevenyomi) [inline multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt:46]: Looks like [`tailrec`](https://kotlinlang.org/docs/functions.html#tail-recursive-functions) - do you see a hint in your IDE?

File: multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt (hunk 1 above)
Comment (Claudemirovsky) [reply multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt]: Yeah, no problem. I just prefer using `.use {}` than manually closing it after use, but explicitly closing wouldn't hurt anyway.

File: multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt (hunk 2 above)
Comment (Claudemirovsky) [reply multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt:46]: I'm not using a IDE xD
I'll check if this applies well.

File: multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+        // Same delay as the source
+        Thread.sleep(3000L)
+        val token = fetchToken(chain).sha256()
+
+        val body = FormBody.Builder().add("challenge", token).build()
+        val challengeReq = POST("$baseUrl/hcdn-cgi/jschallenge-validate", headers, body = body)
+
+        val challengeResponse = chain.proceed(challengeReq)
+        if (challengeResponse.code != 200) throw IOException("Failed to bypass js challenge!")
+        challengeResponse.close()
```
Comment (stevenyomi) [inline multisrc/overrides/mangathemesia/ascalonscans/src/AscalonScans.kt]:
```suggestion
        challengeResponse.close()
        if (challengeResponse.code != 200) throw IOException("Failed to bypass js challenge!")
```

**Review by stevenyomi — CHANGES_REQUESTED** [review]

**Review by stevenyomi — APPROVED** [review]
