### PR TITLE
AlucardScans: Rewrite

### LINKED ISSUE #10220: AlucardScans Theme Changed
### Source information

Alucard Scans 1.4.30

### Source language

Turkish

### Steps to reproduce

The site theme has changed, so it cannot be opened through the app.

### Expected behavior

The site theme has changed, so it cannot be opened through the app.

### Actual behavior

The site theme has changed, so it cannot be opened through the app.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Kraptor123**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

closes https://github.com/keiyoushi/extensions-source/issues/10220

### CODE REVIEW

File: src/tr/alucardscans/src/eu/kanade/tachiyomi/extension/tr/alucardscans/Alucardscans.kt [hunk 1]
```diff
@@ -1,12 +1,171 @@
...
+    override val lang = "tr"
+    override val supportsLatest = true
+
+    private val alucardApi = "api/series?sort=views&order=desc&calculateTotalViews=true&page=SAYFA&limit=24"
+    private val latestApi = "api/chapters/latest?page=SAYFA&limit=10"
+
+    override fun headersBuilder(): Headers.Builder = super.headersBuilder()
+        .add("Referer", "$baseUrl/")
+
+    private fun parseDate(dateStr: String?): Long {
```
Comment (AwkwardPeak7) [inline src/tr/alucardscans/src/eu/kanade/tachiyomi/extension/tr/alucardscans/Alucardscans.kt:36]: use `keiyoushi.utils.tryParse` instead

File: src/tr/alucardscans/src/eu/kanade/tachiyomi/extension/tr/alucardscans/Alucardscans.kt [hunk 2]
```diff
@@ -1,12 +1,171 @@
...
+        val html = response.body.string()
+
+        val chaptersRegex = """initialChapters\\":\s*(\[.*?])\s*\}\s*""".toRegex()
+        val match = chaptersRegex.find(html) ?: throw Exception("Bölüm listesi bulunamadı")
+
+        var chaptersJson = match.groupValues[1]
+
+        chaptersJson = chaptersJson.replace("""\"""", "\"").replace("""\\/""", "/")
+
+        val chapters = json.decodeFromString<List<AluChapters>>(chaptersJson)
```
Comment (AwkwardPeak7) [inline src/tr/alucardscans/src/eu/kanade/tachiyomi/extension/tr/alucardscans/Alucardscans.kt]: use `keiyoushi.utils.parseAs` for json

File: src/tr/alucardscans/src/eu/kanade/tachiyomi/extension/tr/alucardscans/Alucardscans.kt [hunk 3]
```diff
@@ -1,12 +1,171 @@
...
 import java.text.SimpleDateFormat
 import java.util.Locale
 
-class Alucardscans : MangaThemesia(
-    "Alucard Scans",
-    "https://alucardscans.com",
-    "tr",
-    dateFormat = SimpleDateFormat("MMMM dd, yyyy", Locale("tr")),
-)
+class Alucardscans : HttpSource() {
```
Comment (AwkwardPeak7) [inline src/tr/alucardscans/src/eu/kanade/tachiyomi/extension/tr/alucardscans/Alucardscans.kt:19]: bump `versionId` if old urls are not compatible

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
