### PR TITLE
FlixScans: api changes

### LINKED ISSUE #1923: Galaxy Manga : Error 404
### Source information

Galaxy Manga 1.4.31

### Source language

Arabic 

### Steps to reproduce

1- Access the source
 2- Error 404

### Expected behavior

Business must appear 

### Actual behavior

Business must appear Error 404 appears

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 12

### Other details

Screenshot_٢٠٢٤٠٣١٦-١٣٣٥٥٨_Mihon

Screenshot_٢٠٢٤٠٣١٦-١٣٤٠٢٥_Mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1956: Flix scans
### Source information

Flix scans 1.4.5

### Source language

English

### Steps to reproduce

1. enter the extension
2. The extension dose not work

### Expected behavior

The extension should load the entries with no problem

### Actual behavior

No entry shows up when browsing the extension
Note: everything was fine in webview

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 8

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes  #1956
closes #1923

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/flixscans/src/eu/kanade/tachiyomi/multisrc/flixscans/FlixScans.kt [hunk 1]
```diff
@@ -169,52 +162,56 @@ abstract class FlixScans(
 
     override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
         if (query.isNotEmpty()) {
-            return postPath("search/serie/${query.trim()}?page=$page")
+            return GET("$apiUrl/search/serie/${query.trim()}?page=$page")
```
Comment (vetleledaal) [inline lib-multisrc/flixscans/src/eu/kanade/tachiyomi/multisrc/flixscans/FlixScans.kt]: I don't think this is sufficient in terms of encoding `query`
`headers` is also missing

File: lib-multisrc/flixscans/src/eu/kanade/tachiyomi/multisrc/flixscans/FlixScans.kt [hunk 2]
```diff
@@ -169,52 +162,56 @@ abstract class FlixScans(
...
 
     override fun searchMangaParse(response: Response) = latestUpdatesParse(response)
 
     override fun mangaDetailsRequest(manga: SManga): Request {
-        val id = manga.url.split("-")[1]
+        val (prefix, id) = with(manga.url.substringAfterLast("/")) {
+            val split = split("-")
+
+            split[0] to split[1]
+        }
```
Comment (vetleledaal) [inline lib-multisrc/flixscans/src/eu/kanade/tachiyomi/multisrc/flixscans/FlixScans.kt]: Pattern used thrice, consider putting it in a function for consistency
