### PR TITLE
HentaiDex: fix global searching

### LINKED ISSUE #6110: HentaiDex global searching not working
### Source information

HentaiDex 1.4.30

### Source language

English

### Steps to reproduce

1. Look up doujin in global search.
2. It shows me the exact same certain doujins instead of the ones I'm searching for.
3. It does the same thing when I try to filter it. It's the exact same doujins and it shows nothing else.

### Expected behavior

The global search shows me what I'm looking for. It should allso filter the tags I selected.

### Actual behavior

It's showing the same exact doujins in global search. The filter option doesn't work at all.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #6110

Override getFilterList() but just to add new header, explaining that you can not do both search and filter

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/hentaidex/src/eu/kanade/tachiyomi/extension/en/hentaidex/HentaiDex.kt [hunk 1]
```diff
@@ -22,4 +29,95 @@ class HentaiDex : MangaThemesia(
...
+                    url.addQueryParameter("type", filter.selectedValue())
+                }
+
+                is OrderByFilter -> {
+                    url.addQueryParameter("order", filter.selectedValue())
+                }
+
+                is GenreListFilter -> {
+                    filter.state
+                        .filter { it.state != Filter.TriState.STATE_IGNORE }
```
Comment (vetleledaal) [inline src/en/hentaidex/src/eu/kanade/tachiyomi/extension/en/hentaidex/HentaiDex.kt]:
```suggestion
                        .filterNot { it.state == Filter.TriState.STATE_IGNORE }
```

File: src/en/hentaidex/src/eu/kanade/tachiyomi/extension/en/hentaidex/HentaiDex.kt [hunk 2]
```diff
@@ -22,4 +29,95 @@ class HentaiDex : MangaThemesia(
...
+                        .forEach {
+                            val value =
+                                if (it.state == Filter.TriState.STATE_EXCLUDE) "-${it.value}" else it.value
```
Comment (vetleledaal) [inline src/en/hentaidex/src/eu/kanade/tachiyomi/extension/en/hentaidex/HentaiDex.kt]:
```suggestion
                            val value = when(genre.state) {
                                Filter.TriState.STATE_EXCLUDE -> "-${genre.value}"
                                else -> genre.value
                            }
```

**Review by vetleledaal — CHANGES_REQUESTED** [review]

**Review by FourTOne5 — APPROVED** [review]

**Review by vetleledaal — APPROVED** [review]
