### PR TITLE
Manhuarm: fix blank text

### LINKED ISSUE #14032: Manhuarm: no text in speech bubbles
### Source information

Manhuarm 1.4.62

### Source language

Multi

### Steps to reproduce

1. Open manhua
2. The chapter only shows blank speech bubbles

### Expected behavior

There should be text for the manhua

### Actual behavior

The chapter show Blank speech bubbles

### Mihon/Mihon fork version

Yōkai 1.9.7.4

### Android version

16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AaronDeimos**
Close: #14032 
Ai assisted

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmUtils.kt [hunk 1]
```diff
@@ -23,31 +23,41 @@ data class Language(
...
+    val cleanScript = script.replace("\\/", "/")
 
-    return try {
-        baseUrl.toHttpUrl().newBuilder().apply {
-            PARAM_REGEX.findAll(script).forEach { match ->
-                val paramName = match.groupValues[1]
-                val decode = match.groupValues[2].isNotBlank()
-                val dataKey = match.groupValues[3]
+    val ocrData = OCR_DATA_REGEX.find(cleanScript)?.groupValues?.get(1)?.let {
+        runCatching { it.parseAs<JsonObject>() }.getOrNull()
```
Comment (vetleledaal) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmUtils.kt]: Can you use a DTO instead of `jsonPrimitive`?

Comment (AaronDeimos) [reply src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmUtils.kt]: This part is useless as the site broke it. I was thinking of keeping it as a fallback, but forget it; the site will find a way to break it anyways, so I will remove it.

**Review by vetleledaal — DISMISSED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
