### PR TITLE
Fix/thunderscans

### LINKED ISSUE #12576: Lava Scans: `No results found` error
### Source information

Lava Scans 1.4.40

### Source language

Arabic 

### Steps to reproduce

the Website works , but the extension is showing ( No Result Found Error) 

Image

### Expected behavior

It's supposed to show the entries 

### Actual behavior

Result Not Found Error 

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #12694: Lava Scans: New website URL (`lavascans.com`)
### Source information

Thunderscans 1.4.40

### Source language

Arabic 

### Source new URL

https://lavascans.com/

### Other details

Please update the Arabic website link for Lavascans 
https://lavascans.com/

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [update url of ar lavascans ].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by xMohnad**
Closes #12694
Closes #12576
 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Smol-Ame** [comment]
Does this resolve 12576 as well?

**Comment by xMohnad** [comment]
@Smol-Ame 
Yes, this also resolves #12576.

File: lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt [hunk 1]
```diff
@@ -140,11 +140,12 @@ abstract class MangaThemesia(
...
     }
 
-    override fun searchMangaSelector() = ".utao .uta .imgu, .listupd .bs .bsx, .listo .bs .bsx"
+    override fun searchMangaSelector() = ".utao .uta .imgu, .listupd .bs .bsx, .listo .bs .bsx, .listupd .manga-card-v"
+    open val searchMangaTitleSelector = ".bigor .tt, h3 a"
 
     override fun searchMangaFromElement(element: Element) = SManga.create().apply {
         thumbnail_url = element.select("img").imgAttr()
-        title = element.select("a").attr("title")
+        title = element.selectFirst(searchMangaTitleSelector)!!.text().ifBlank { element.select("a")!!.attr("title") }
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt]:
```suggestion
        title = element.selectFirst(searchMangaTitleSelector)?.text()?.takeIf { it.isNotBlank() } ?: element.select("a")!!.attr("title")
```

File: lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt
Comment (AwkwardPeak7) [inline lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt:1]: I don't think these are standard mangathemesia selectors. if any other sources has similar/same selectors then please tell me. otherwise it would be better to override the source directly with these selectors instead of changing MangaThemesia

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt
Comment (T3MYA11) [reply lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt:1]: @AwkwardPeak7 
https://azoramoon.com
azora manga has similar selectors

Comment (AwkwardPeak7) [reply lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt:1]: azora moon is not using mangathemesia

File: src/all/thunderscans/src/eu/kanade/tachiyomi/extension/all/thunderscans/ThunderScansFactory.kt [hunk 2]
```diff
@@ -23,6 +26,14 @@ abstract class ThunderScansBase(
 ) : MangaThemesiaAlt(name, baseUrl, lang, mangaUrlDirectory, dateFormat) {
     private val paidChapterHelper = MangaThemesiaPaidChapterHelper()
 
+    open val searchMangaTitleSelector = ".bigor .tt, h3 a"
+
+    override fun searchMangaFromElement(element: Element): SManga {
+        return super.searchMangaFromElement(element).apply {
+            title = element.selectFirst(searchMangaTitleSelector)?.text()?.takeIf { it.isNotBlank() } ?: element.select("a")!!.attr("title")
```
Comment (vetleledaal) [inline src/all/thunderscans/src/eu/kanade/tachiyomi/extension/all/thunderscans/ThunderScansFactory.kt]: `.text()` is always trimmed according to Jsoup docs, so using `String::isNotBlank` is the same is `String::isNotEmpty`.
```suggestion
            title = element.selectFirst(searchMangaTitleSelector)?.text()?.takeIf(String::isNotEmpty) ?: element.select("a")!!.attr("title")
```

Comment (vetleledaal) [inline src/all/thunderscans/src/eu/kanade/tachiyomi/extension/all/thunderscans/ThunderScansFactory.kt]: Is the title a combinaiton of multiple `a` tags? If not:
```suggestion
            title = element.selectFirst(searchMangaTitleSelector)?.text()?.takeIf { it.isNotBlank() } ?: element.selectFirst("a")!!.attr("title")
```

File: src/all/thunderscans/src/eu/kanade/tachiyomi/extension/all/thunderscans/ThunderScansFactory.kt [hunk 3]
```diff
@@ -38,11 +49,33 @@ abstract class ThunderScansBase(
...
+    "https://lavascans.com",
     "ar",
-    dateFormat = SimpleDateFormat("MMM d, yyy", Locale("ar")),
+    dateFormat = SimpleDateFormat("yyyy/MM/dd", Locale("ar")),
 ) {
     override val id = 3209001028102012989
+
+    override fun chapterFromElement(element: Element): SChapter {
+        return super.chapterFromElement(element).apply {
+            name = element.select(".ch-num").text().ifBlank { name }
```
Comment (vetleledaal) [inline src/all/thunderscans/src/eu/kanade/tachiyomi/extension/all/thunderscans/ThunderScansFactory.kt]: `.text()` is also trimmed here.
```suggestion
            name = element.select(".ch-num").text().ifEmpty { name }
```

Comment (vetleledaal) [inline src/all/thunderscans/src/eu/kanade/tachiyomi/extension/all/thunderscans/ThunderScansFactory.kt]: You only expect one chapter number:
```suggestion
            name = element.selectFirst(".ch-num")!!.text().ifBlank { name }
```

Name is also critical, so you can use a non-null assert.

**Review by AwkwardPeak7 — APPROVED** [review]
