### PR TITLE
TruyenHentai18: Update domain and fix loading content

### LINKED ISSUE #9306: Truyện Hentai 18+ changed code and domain
### Source information

Truyện Hentai 18+ 1.4.3

### Source language

Vietnamese

### Source new URL

https://truyenhentai18.app

### Other details

Supersedes #9234 

> New URL: https://truyenhentai18.app
> 
> The source has changed code and domain name for a while, but no one maintains it. 

 _Originally posted by @dejavui in [#9234](https://github.com/keiyoushi/extensions-source/issues/9234#issuecomment-2972613305)_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #9306

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+)
+
+@Serializable
+class MangaDto(
+    val title: String,
+    val slug: String,
+) {
+    fun toSManga() = SManga.create().apply {
+        title = this@MangaDto.title
+        url = "/vi/$slug.html"
```
Comment (AwkwardPeak7) [inline src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt]: are old urls compatible?

Comment (choppeh) [reply src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt]: > are old urls compatible?

Yes, example:
Wayback: https://web.archive.org/web/20250311232714/https://truyenhentai18.pro/the-big-breasted-pirate-4.html

old path segment (https://truyenhentai18.app/vi/the-big-breasted-pirate-4.html) redirect to https://truyenhentai18.app/vi/the-big-breasted-pirate-4.html

Comment (stevenyomi) [reply src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt]: If you silently use the new URL format in the `url` field (which serves as the key of an entry), existing entries might work seamlessly, but when people search for the same title in the source, there will be a new, duplicate entry with the new URL (with the `/vi` prefix). This is not ideal.

Since the manga slug is compatible, you should actually strip the `/vi` prefix when storing the URL and add them back when doing network requests (and in `getMangaUrl()`, etc).

Edit: Same for chapters.

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+@Serializable
+class SearchDto(
+    val data: List<MangaDto>,
+)
+
+@Serializable
+class MangaDto(
+    val title: String,
+    val slug: String,
```
Comment (stevenyomi) [inline src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt]: Make the fields private as you're actually relying on the `toSManga()` function. Same for other DTOs.

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt (hunk 1 above)
Comment (choppeh) [reply src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt]: > If you silentl ...

The prefix `vi` is added in searchMangaParse, but when popular or latest are used, this prefix defaults to `::popularMangaFromElement`, so perhaps forcing the entry to be updated in mangaDetails could be an alternative to maintain consistency

Comment (stevenyomi) [reply src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18Dto.kt]: > so perhaps forcing the entry to be updated in mangaDetails could be an alternative to maintain consistency

The app never updates an entry's `url` field, even if you update it in later detail fetches - it is ignored. The `url` functions as an immutable key - different `url` values are recognized as different entries.

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt [hunk 3]
```diff
@@ -37,13 +37,13 @@ class TruyenHentai18 : ParsedHttpSource() {
     // ============================== Popular ======================================
 
     override fun popularMangaRequest(page: Int) =
-        GET("$baseUrl/vi/truyen-de-xuat" + if (page > 1) "/page/$page" else "", headers)
+        GET("$baseUrl/truyen-de-xuat" + if (page > 1) "/page/$page" else "", headers)
```
Comment (stevenyomi) [inline src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt]:
```suggestion
        GET("$baseUrl/$lang/truyen-de-xuat" + if (page > 1) "/page/$page" else "", headers)
```

Keep the `/vi/` part to avoid an extra redirection.

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt [hunk 4]
```diff
@@ -37,13 +37,13 @@ class TruyenHentai18 : ParsedHttpSource() {
...
 
     override fun popularMangaSelector() = ".container .p-2 .shadow-sm.overflow-hidden"
 
     override fun popularMangaFromElement(element: Element) = SManga.create().apply {
         element.selectFirst("a[title]")!!.let {
-            setUrlWithoutDomain(it.attr("href"))
+            setUrlWithoutDomain(it.absUrl("href").substringAfterLast(lang))
```
Comment (stevenyomi) [inline src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt]: `substringAfterLast()` might break the slug.

Do `setUrlWithoutDomain(it.{attr,absUrl}("href"))` then `url = url.removePrefix("/$lang")`.

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt [hunk 5]
```diff
@@ -111,11 +111,13 @@ class TruyenHentai18 : ParsedHttpSource() {
                 else -> SManga.UNKNOWN
             }
         }
-        setUrlWithoutDomain(document.location())
+        url = document.location().substringAfterLast(lang)
```
Comment (stevenyomi) [inline src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt]: Same as above. `setUrlWithoutDomain()` then remove the prefix.

**Review by AwkwardPeak7 — APPROVED** [review]
