### PR TITLE
Fix TuManhwas.club and change the name to ManhwasMe

### LINKED ISSUE #14507: TuManhwas.Club: `Too many follow-up requests` error, new website URL (`manhwas.me`)
### Source information

Tumanhwasclub 1.4. 1

### Source language

Spanish 

### Source new URL

https://manhwas.me/

### Steps to reproduce

Source does not display any list of manwhas, gives ProtocolException error

Image

Image

### Expected behavior

You should see the list of series

### Actual behavior

Gives ProtocolException error when opening the source

Image
Image

### Mihon/Mihon fork version

0.19.3

### Android version

Android 11

### Other details

In webview the scan web page is displayed

Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14507

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/manhwasme/src/eu/kanade/tachiyomi/extension/es/manhwasme/ManhwasMe.kt [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+
+    override fun popularMangaRequest(page: Int): Request = GET("$baseUrl/search?sort=-views&page=$page", headers)
+
+    override fun popularMangaParse(response: Response): MangasPage {
+        val document = response.asJsoup()
+
+        val mangas = document.select("div.results-grid a.result-card").map { element ->
+            SManga.create().apply {
+                setUrlWithoutDomain(element.absUrl("href"))
+                title = element.selectFirst("div.result-card-title")?.text() ?: ""
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/manhwasme/src/eu/kanade/tachiyomi/extension/es/manhwasme/ManhwasMe.kt]: Must be mandatory

File: src/es/manhwasme/src/eu/kanade/tachiyomi/extension/es/manhwasme/ManhwasMe.kt [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+        GenreFilter(),
+        StatusFilter(),
+        ContentFilter(),
+    )
+
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+
+        return SManga.create().apply {
+            title = document.selectFirst("h1.detail-title")?.text() ?: ""
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/manhwasme/src/eu/kanade/tachiyomi/extension/es/manhwasme/ManhwasMe.kt]: Mandatory too

File: src/es/manhwasme/src/eu/kanade/tachiyomi/extension/es/manhwasme/ManhwasMe.kt [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+        }
+    }
+
+    override fun imageUrlParse(response: Response): String = throw UnsupportedOperationException()
+
+    private fun parseDate(dateStr: String?): Long {
+        if (dateStr == null) return 0L
+
+        return if (dateStr.contains("hace", ignoreCase = true)) {
+            val number = dateStr.replace(Regex("""\D"""), "").toIntOrNull() ?: return 0L
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/manhwasme/src/eu/kanade/tachiyomi/extension/es/manhwasme/ManhwasMe.kt]: Separate regex

File: src/es/tumanhwasclub/src/eu/kanade/tachiyomi/extension/es/tumanhwasclub/TuManhwasClub.kt [hunk 4]
```diff
@@ -1,5 +1,163 @@
...
+import keiyoushi.utils.tryParse
+import okhttp3.HttpUrl.Companion.toHttpUrl
+import okhttp3.Request
+import okhttp3.Response
+import java.text.SimpleDateFormat
+import java.util.Calendar
+import java.util.Locale
 
-class TuManhwasClub : Manga18("TuManhwas.Club", "https://tumanhwas.club", "es")
+class TuManhwasClub : HttpSource() {
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/tumanhwasclub/src/eu/kanade/tachiyomi/extension/es/tumanhwasclub/TuManhwasClub.kt]: Change the class and file names too! Then add override val id so that the extension ID doesn't change (if the manga slug on the old website is still the same), and override versionId if the previous slug changes.

Comment (MuhamadSyabitHidayattulloh) [reply src/es/tumanhwasclub/src/eu/kanade/tachiyomi/extension/es/tumanhwasclub/TuManhwasClub.kt]: If only the url path changes you need to add logic for that, and keep the val id

File: src/es/tumanhwasclub/src/eu/kanade/tachiyomi/extension/es/tumanhwasclub/ManhwasMe.kt [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+import java.util.Calendar
+import java.util.Locale
+
+class ManhwasMe : HttpSource() {
+
+    override val name = "ManhwasMe"
+
+    // Preserves the original TuManhwas.Club source ID so existing users
+    // don't lose their library when the class/name changed.
+    override val id = 8004442288770923365L
```
Comment (AwkwardPeak7) [inline src/es/tumanhwasclub/src/eu/kanade/tachiyomi/extension/es/tumanhwasclub/ManhwasMe.kt:25]: are old urls compatible? check via wayback machine perhaps

Comment (darwin-256) [reply src/es/tumanhwasclub/src/eu/kanade/tachiyomi/extension/es/tumanhwasclub/ManhwasMe.kt:25]: Added support for it

**Review by AwkwardPeak7 — APPROVED** [review]
