### PR TITLE
all/SimplyHentai: Fix http 404 

### LINKED ISSUE #580: Simply Hentai - HTTP404 error
### Source information

Simply Hentai 1.4.6

### Source language

Multi

### Steps to reproduce

1. download and install extension
2. open EN via Browse Source
3. getting error "HTTP 404, check website in webview"

### Expected behavior

Should show normaly

### Actual behavior

Showing error 404

### Tachiyomi version

1.10.2 (SY)

### Android version

13

### Other details

website in webview is work fine. don't know if it domain change or not.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #580

Note: This PR removes the `pt-BR` (Brazillian Portuguese) language from the extension, as the source itself has removed it.
\>imagine bater pra desenho

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/simplyhentai/src/eu/kanade/tachiyomi/extension/all/simplyhentai/SimplyHentai.kt [hunk 1]
```diff
@@ -5,76 +5,63 @@ import android.net.Uri
...
+    private val langName: String,
+) : ConfigurableSource, HttpSource() {
+
     override val name = "Simply Hentai"
 
     override val baseUrl = "https://www.simply-hentai.com"
 
     override val supportsLatest = true
 
-    override val client = network.cloudflareClient
```
Comment (AwkwardPeak7) [inline src/all/simplyhentai/src/eu/kanade/tachiyomi/extension/all/simplyhentai/SimplyHentai.kt]: keep cloudflareclient since we are still using ext-lib 1.4

File: src/all/simplyhentai/src/eu/kanade/tachiyomi/extension/all/simplyhentai/SimplyHentai.kt [hunk 2]
```diff
@@ -156,29 +130,25 @@ open class SimplyHentai(override val lang: String) : ConfigurableSource, HttpSou
...
-            appendQueryParameter("locale", lang)
             GET(build().toString(), headers)
         }
 
     override fun chapterListParse(response: Response) =
         SChapter.create().apply {
             val album = response.decode<SHAlbum>().data
             name = "Chapter"
-            chapter_number = -1f
+            chapter_number = -1F
```
Comment (AwkwardPeak7) [inline src/all/simplyhentai/src/eu/kanade/tachiyomi/extension/all/simplyhentai/SimplyHentai.kt]:
```suggestion
```

**Review by AwkwardPeak7 — DISMISSED** [review]

**Review by beer-psi — APPROVED** [review]
