### PR TITLE
RimuScans: Fix new UI & API and refine premium handling

### LINKED ISSUE #12513: Rimuscans bug
### Source information

Rimu Scans 1.4.32

### Source language

French

### Steps to reproduce

When clicking on a webtoon from this source, the chapter list no longer appears. Search is also broken, although the web view still works. Image

### Expected behavior

The display of webtoons and their contents

### Actual behavior

The website loads in web view, but chapter listing does not work, and search is also broken.

### Mihon/Tachiyomi version

Tachimanga v4.11(405)

### Android version

IOS 26.1

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Nyantad**
Fixes the RimuScans extension by switching to the new JSON API and implements a premium chapter toggle

Closes #12513

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+import eu.kanade.tachiyomi.source.model.SChapter
+import eu.kanade.tachiyomi.source.model.SManga
+import keiyoushi.utils.tryParse
+import kotlinx.serialization.Serializable
+import java.text.SimpleDateFormat
+import java.util.Locale
+import java.util.TimeZone
+
+@Serializable
+data class MangaListDto(
```
Comment (Starmania) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt]:
```suggestion
class MangaListDto(
```

Remove every data class

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+data class MangaDetailsWrapperDto(
+    val manga: MangaDto,
+)
+
+@Serializable
+data class MangaDto(
+    val id: String,
+    val slug: String,
+    val title: String,
+    val alternativeTitles: List<String> = emptyList(),
```
Comment (Starmania) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt:30]: Add alternativeTitles to Manga's description

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+    val order: Int,
+    val url: String,
+)
+
+@Serializable
+data class PaginationDto(
+    val page: Int,
+    val limit: Int,
+    val hasNextPage: Boolean,
+    val hasPrevPage: Boolean,
```
Comment (Starmania) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt]:
```suggestion
    val hasNextPage: Boolean,
```
Remove unused fields (same for ImageDto.id, ChapterDto.id)

**Review by Starmania — COMMENTED** [review]
Thanks for your work !

**Comment by Nyantad** [comment]
Thanks for the review, it should be good now !

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt [hunk 4]
```diff
@@ -1,12 +1,200 @@
...
+import eu.kanade.tachiyomi.source.model.SChapter
+import eu.kanade.tachiyomi.source.model.SManga
+import eu.kanade.tachiyomi.source.online.HttpSource
+import keiyoushi.utils.getPreferencesLazy
+import keiyoushi.utils.parseAs
+import okhttp3.HttpUrl.Companion.toHttpUrl
+import okhttp3.Request
+import okhttp3.Response
+
+class RimuScans : HttpSource(), ConfigurableSource {
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt:20]: are old urls compatible? if not then bump `versionId` to 2

tho, looks like new urls are still in the form: `/manga/slug` so good there, but chapter urls are different. so you would have to add a simple check to `pageListRequest` if url is new and if not, throw exception telling user to refresh chapter list

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt [hunk 5]
```diff
@@ -1,12 +1,200 @@
...
+    private fun mangaPageParse(response: Response): MangasPage {
+        val result = response.parseAs<MangaListDto>()
+        val mangas = result.mangas.map { it.toSManga(baseUrl) }
+        return MangasPage(mangas, result.pagination.hasNextPage)
+    }
+
+    // Details
+
+    override fun mangaDetailsRequest(manga: SManga): Request {
+        val slug = manga.url.removeSuffix("/").substringAfterLast("/")
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt]: use `HttpUrl.pathsegments` to extract slug

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt [hunk 6]
```diff
@@ -1,12 +1,200 @@
...
+        val url = "$baseUrl/api/manga".toHttpUrl().newBuilder()
+            .addQueryParameter("slug", mangaSlug)
+            .build()
+        return GET(url, headers)
+    }
+
+    override fun pageListParse(response: Response): List<Page> {
+        val result = response.parseAs<MangaDetailsWrapperDto>()
+        val chapterNumber = response.request.url.fragment?.toDoubleOrNull()
+            ?: throw Exception("Chapter number not found in request")
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt:150]: it was not passed in the `pageListRequest`?

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt [hunk 7]
```diff
@@ -1,12 +1,200 @@
...
+        }
+    }
+
+    override fun imageUrlParse(response: Response): String = ""
+
+    override fun getMangaUrl(manga: SManga): String = baseUrl + manga.url
+
+    override fun getChapterUrl(chapter: SChapter): String = baseUrl + chapter.url.substringBeforeLast("#")
+
+    override fun fetchPageList(chapter: SChapter): rx.Observable<List<Page>> {
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt]: remove this, and move logic to `pageListRequest`. unless there is a specific reason?

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt [hunk 8]
```diff
@@ -1,12 +1,200 @@
...
+            .build()
+
+        return client.newCall(GET(url, headers)).asObservableSuccess().map { response ->
+            pageListParse(response)
+        }
+    }
+
+    // Filters
+
+    override fun getFilterList() = eu.kanade.tachiyomi.extension.fr.rimuscans.getFilterList()
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt]: rename that function to `getFilters` and import it

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+class ChapterDto(
+    val number: Double,
+    val title: String? = null,
+    val releaseDate: String? = null,
+    val type: String? = null,
+    val images: List<ImageDto> = emptyList(),
+) {
+    fun toSChapter(mangaSlug: String) = SChapter.create().apply {
+        url = "/read/$mangaSlug/${if (number % 1.0 == 0.0) number.toInt() else number}"
+        val numberString = if (number % 1.0 == 0.0) number.toInt().toString() else number.toString()
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt]:
```kt
val numberString = number.toString().substringBefore(".0")
```

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt [hunk 10]
```diff
@@ -0,0 +1,94 @@
...
+        name = when {
+            title == null || title.isBlank() -> "Chapitre $numberString"
+            title.contains("Chapitre", ignoreCase = true) || title.contains("Chapter", ignoreCase = true) -> title.trim()
+            else -> "Chapitre $numberString : ${title.trim()}"
+        }
+        if (type == "PREMIUM") {
+            name = "✨ $name"
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt]: perhaps add a lock emoji instead of this

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt [hunk 11]
```diff
@@ -0,0 +1,94 @@
...
+        }
+        chapter_number = number.toFloat()
+        scanlator = "Rimu Scans"
+        date_upload = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US).apply {
+            timeZone = TimeZone.getTimeZone("UTC")
+        }.tryParse(releaseDate)
```
Comment (AwkwardPeak7) [inline src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt]: put `SimpleDateFormat` as val in the file, so it is not recreated for every chapter

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt (hunk 4 above)
Comment (Starmania) [reply src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScans.kt:20]: I double checked and validated this with my old library. Working fine. No need to bump versionId

File: src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt (hunk 11 above)
Comment (Starmania) [reply src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt]: I came across this pattern multiple times in the repo but `SimpleDateFormat` isn't thread safe. Is it okay ?

Comment (AwkwardPeak7) [reply src/fr/rimuscans/src/eu/kanade/tachiyomi/extension/fr/rimuscans/RimuScansDto.kt]: it is not called in multiple threads simultaneously.

**Comment by Nyantad** [comment]
All PR feedback implemented & I've removed `fetchPageList` as it's now redundant with the updated `pageListRequest`, should be good now

**Review by AwkwardPeak7 — APPROVED** [review]
