### PR TITLE
 fix nhentai cdn script selection

### LINKED ISSUE #9856: Nhentai unable to open hentai
### Source information

Nhentai 1.4.20

### Source language

Multi

### Steps to reproduce

Go into nhentai.

Try to open any doujin.

Fail to open doujin.

### Expected behavior

Doujin opens with all images

### Actual behavior

Doujin fails to open with no message as to why.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MediocreLegion**
Closes #9856

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt [hunk 1]
```diff
@@ -71,7 +71,9 @@ open class NHentai(
 
     private val shortenTitleRegex = Regex("""(\[[^]]*]|[({][^)}]*[)}])""")
     private val dataRegex = Regex("""JSON\.parse\(\s*"(.*)"\s*\)""")
-    private val hentaiSelector = "script:containsData(JSON.parse):not(:containsData(media_server))"
+    private val hentaiSelector = "script:containsData(JSON.parse)"
+    private val cdnRegex = Regex("""image_cdn_urls: (\[.*])""")
+    private val cdnSelector = "script:not(:containsData(JSON.parse))"
```
Comment (stevenyomi) [inline src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt]: The newly added `cdnRegex` and `cdnSelector` can be inlined into `pageListParse()`.

File: src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt [hunk 2]
```diff
@@ -256,17 +258,18 @@ open class NHentai(
...
-        val script2 = document.selectFirst(hentaiSelector)!!.data()
+        val script = document.selectFirst(hentaiSelector)!!.data()
+        val json = dataRegex.find(script)?.groupValues!![1]
+        val data = json.parseAs<Hentai>()
 
-        val mediaServer = Regex("""media_server\s*:\s*(\d+)""").find(script)?.groupValues!![1]
-        val json = dataRegex.find(script2)?.groupValues!![1]
+        val scripts = document.select(cdnSelector).map { it.data() }.filter { it.isNotEmpty() }
+        val cdnJson = scripts.firstNotNullOf { cdnRegex.find(it)?.groupValues!![1] }
+        val cdnList = cdnJson.parseAs<List<String>>()
```
Comment (stevenyomi) [inline src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt]: This function only parses the scripts and doesn't need the DOM at all. Try this:

```kotlin
override fun pageListParse(document: Document) = throw UnsupportedOperationException()

override fun pageListParse(response: Response): List<Page> {
    val html = response.body.string()
    // just run your regex on the html
}
```

**Review by stevenyomi — APPROVED** [review]
