### PR TITLE
Keyoapp: Fix duplicate entries

### LINKED ISSUE #8215: Keyoapp popular manga duplicate entries
### Source information

MSYToon

### Source language

All

### Steps to reproduce

- Install MSYToon
- Open Popular from MSYToon

### Expected behavior

Duplicate entries

### Actual behavior

Unique entries

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 11

### Other details

Maybe add a selector like this

```kt  
open val popularMangaTitleSelector = listOf(
    "Trending",
    "Popular",
    "Popularie"
)

override fun popularMangaSelector(): String = selector(
    "div:contains(%s) + div .group.overflow-hidden.grid",
    popularMangaTitleSelector,
)

// Code from MangaThemesia
private fun selector(selector: String, contains: List<String>): String {
    return contains.joinToString(", ") { selector.replace("%s", it) }
}

```

Bug introduced in #8206

And maybe this will solve the filter in the popularManga list filter in RitharScans
https://github.com/keiyoushi/extensions-source/blob/228b657e25788f904b29cde7561b69d5a38f800b/src/en/ritharscans/src/eu/kanade/tachiyomi/extension/en/ritharscans/RitharScans.kt#L18

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #8215

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/keyoapp/src/eu/kanade/tachiyomi/multisrc/keyoapp/Keyoapp.kt [hunk 1]
```diff
@@ -357,6 +365,10 @@ abstract class Keyoapp(
         return now.timeInMillis
     }
 
+    private fun selector(selector: String, contains: List<String>): String {
+        return contains.joinToString(", ") { selector.replace("%s", it) }
```
Comment (vetleledaal) [inline lib-multisrc/keyoapp/src/eu/kanade/tachiyomi/multisrc/keyoapp/Keyoapp.kt]:
```suggestion
        return contains.joinToString { selector.replace("%s", it) }
```

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
