### PR TITLE
fix(azora): update theme package to 'iken'

### LINKED ISSUE #12641: Azora: `No results found` error, new website design
### Source information

Azora 1.4.53

### Source language

Arabic 

### Steps to reproduce

Image

### Expected behavior

it should work normally and update the manga

### Actual behavior

Image

### Mihon/Tachiyomi version

yokai

### Android version

android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by nasoooor29**
I tested it on my phone it works but the "popular" tab doesn't work everything else is fine

I won't update this PR i don't have autocomplete or the correct setup (IDE, etc), i just have the JVM cli
do i need to upload the binary (i think this would cause a security issue or smth)

Closes #12641
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by xMohnad** [comment]
Does the manga in the library work or does it need to be migrated?

**Comment by nasoooor29** [comment]
on suwayomi i needed to go and migrate them manually, but i don't have any mangas on azora on mihon to check.
@xMohnad

**Comment by nasoooor29** [comment]
ok fixed popular tab without debugger or anything so i will consider it as done.

https://github.com/user-attachments/assets/cb43d954-8e32-4e3c-bf16-986325fa403f

**Comment by xMohnad** [comment]
I think you should add a migration message like this:
https://github.com/keiyoushi/extensions-source/blob/21644084bd20a863cddf91edea6424779d1b307e/src/en/kenscans/src/eu/kanade/tachiyomi/extension/en/kenscans/KenScans.kt#L15-L21

**Comment by xMohnad** [comment]
Migration message is working fine.

Screenshot_2026-01-13-09-12-34-341_app mihon

**Comment by nasoooor29** [comment]
Let me know if you can submit the GitHub review so we can proceed with the merge.

File: src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt [hunk 1]
```diff
@@ -1,21 +1,39 @@
...
+            addQueryParameter("orderDirection", "desc")
+        }.build()
 
-        element.select("a").let {
-            chapter.url = it.attr("href").substringAfter(baseUrl)
-            chapter.name = it.text()
+        return GET(url, headers)
+    }
+    override fun chapterListRequest(manga: SManga): Request {
+        // Migration from old web theme to the new one(madara -> Iken)
```
Comment (AwkwardPeak7) [inline src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt]: add the same check in `mangaDetailsRequest`, or you can just bump `versionId` and avoid these checks

File: src/ar/azora/build.gradle [hunk 2]
```diff
@@ -1,9 +1,9 @@
 ext {
     extName = 'Azora'
     extClass = '.Azora'
-    themePkg = 'madara'
+    themePkg = 'iken'
     baseUrl = 'https://azoramoon.com'
-    overrideVersionCode = 8
+    overrideVersionCode = 9
```
Comment (AwkwardPeak7) [inline src/ar/azora/build.gradle]: final version is caclulated by theme baseversion + extension overrideVersion. madara is quiet high, and iken is not, so you need to calculate the new versionCode according to that

Comment (nasoooor29) [reply src/ar/azora/build.gradle]: updated it to ver 43
because azora is on ver "53->54" 
madara (now at ver 45)->**9**+45=54
iken (now at ver 11)-> **43**+11=54

File: src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt (hunk 1 above)
Comment (nasoooor29) [reply src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt]: i removed the check and added 
```kotlin
    override val versionId = 2;
```

File: src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt [hunk 3]
```diff
@@ -1,21 +1,32 @@
...
-        element.select("a").let {
-            chapter.url = it.attr("href").substringAfter(baseUrl)
-            chapter.name = it.text()
-        }
-        return chapter
+        return GET(url, headers)
+    }
+
+    override fun popularMangaParse(response: Response): MangasPage {
+        return searchMangaParse(response)
```
Comment (cuong-tran) [inline src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt:30]: Add `titleCache` here so it fetches `genres` for Filter to work
```suggestion
        // Fetch genres
        titleCache
        return searchMangaParse(response)
```

**Review by AwkwardPeak7 — APPROVED** [review]

File: src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt (hunk 3 above)
Comment (cuong-tran) [reply src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt:30]: Huh, no changing this? Genre won't load.

Comment (AwkwardPeak7) [reply src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt:30]: I don't like this hack, imo Iken should itself be updated to address this.
