### PR TITLE
Mangakuri (ID): update structure

### LINKED ISSUE #13954: Mangakuri (ID) : HTTP 404 error
### Source information

Mangakuri 1.4.30

### Source language

Indonesia

### Steps to reproduce

1. Click on source
2. It show HTTP 404
3. Open webview
4. Website normal but design change

### Expected behavior

It should show list manhwa available in the website from popular or latest tab

### Actual behavior

It show http 404 error

Image

### Mihon/Mihon fork version

Mihon v0.19.4

### Android version

Android 16

### Other details

The website design change (same design as DreamTeams Scan)

Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MuhamadSyabitHidayattulloh**
Closes #13954 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/MangakuriDto.kt [hunk 1]
```diff
@@ -0,0 +1,56 @@
+package eu.kanade.tachiyomi.extension.id.mangakuri
+
+import kotlinx.serialization.Serializable
+
+@Serializable
+data class SearchResponseDto(
```
Comment (vetleledaal) [inline src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/MangakuriDto.kt]: Use regular `class` when you don't need `data class`.

File: src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/MangakuriDto.kt [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+
+@Serializable
+data class SeriesDetailDto(
+    val title: String,
+    val slug: String,
+    val synopsis: String? = null,
+    val poster_image_url: String? = null,
+    val comic_status: String? = null,
+    val author_name: String? = null,
+    val artist_name: String? = null,
```
Comment (vetleledaal) [inline src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/MangakuriDto.kt]: Use `@SerialName` and keep Kotlin in camelCase.
```suggestion
    @SerialName("comic_status") val comicStatus: String? = null,
    @SerialName("author_name") val authorName: String? = null,
    @SerialName("artist_name") val artistName: String? = null,
```

File: src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt [hunk 3]
```diff
@@ -1,19 +1,208 @@
...
+        TypeFilter(),
+        ColorFilter(),
+        ReadingFilter(),
+        TextFilter("Author", "author"),
+        TextFilter("Artist", "artist"),
+        TextFilter("Publisher", "publisher"),
     )
+
+    private val dateFormat by lazy {
+        SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US)
```
Comment (vetleledaal) [inline src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt]: Need to set timezone.

File: src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt [hunk 4]
```diff
@@ -1,19 +1,208 @@
...
+                date_upload = dateFormat.tryParse(chapter.created_at)
+            }
+        }
+    }
+
+    private fun formatChapterNumber(number: String): String = if (number.endsWith(".00")) {
+        number.substringBefore(".00")
+    } else {
+        number
+    }
```
Comment (vetleledaal) [inline src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt]: Use `.removeSuffix()`.

File: src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt [hunk 5]
```diff
@@ -1,19 +1,208 @@
...
+
+    override fun getChapterUrl(chapter: SChapter): String = "$baseUrl${chapter.url}"
+
+    // ================= Pages =================
+    override fun pageListRequest(chapter: SChapter): Request {
+        val path = chapter.url.removePrefix("/")
+        return GET("$apiUrl/series/$path", headers)
```
Comment (vetleledaal) [inline src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt]: You set the URL directly so you should know that it always starts with `/`.
```suggestion
        return GET("$apiUrl/series${chapter.url}", headers)
```

File: src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt [hunk 6]
```diff
@@ -1,19 +1,208 @@
...
+
+        return GET(url.build(), headers)
+    }
+
+    override fun searchMangaParse(response: Response) = popularMangaParse(response)
+
+    // ================= Details =================
+    override fun mangaDetailsRequest(manga: SManga): Request {
+        val slug = manga.url.removePrefix("/comic/")
+        return GET("$apiUrl/series/comic/$slug", headers)
```
Comment (vetleledaal) [inline src/id/mangakuri/src/eu/kanade/tachiyomi/extension/id/mangakuri/Mangakuri.kt]: ?
```suggestion
        return GET("$apiUrl/series${manga.url}", headers)
```

**Review by AwkwardPeak7 — APPROVED** [review]
