### PR TITLE
WNACG | Added support for ".jpeg" and fixed domain update

### LINKED ISSUE #6050: Wnacg cannot automatically update the domain correctly
### Source information

wnacg 1.4.16

### Source language

Chinese

### Source new URL

https://www.wnacg.com

### Other details

[www.wn01.uk](https://www.wn01.uk/)
[www.wn05.cc](https://www.wn05.cc/)
[www.wn04.cc](https://www.wn04.cc/)
[www.wn03.cc](https://www.wn03.cc/)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #6056: WNACG: Unable to display images with .jpeg suffix
### Source information

WNACG 1.4.16

### Source language

Chinese

### Steps to reproduce

For example, open this URL:
https://www.wn01.uk/photos-index-aid-221139.html

### Expected behavior

This should show message “no pages found”.

### Actual behavior

It shows that message “no pages found”, and the images cannot be opened.

### Mihon/Tachiyomi version

Mihon 0.17.0

### Android version

Android 14

### Other details

Images with .jpeg suffix (not .jpg) will show message “no pages found”.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #6050
Closes #6056

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt
Comment (stevenyomi) [inline src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt:1]: Update `DEFAULT_LIST` to keep in sync with https://stevenyomi.github.io/source-domains/wnacg.txt

File: src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt [hunk 1]
```diff
@@ -71,7 +71,7 @@ class UpdateUrlInterceptor(private val preferences: SharedPreferences) : Interce
 
         val failedResponse = try {
             val response = chain.proceed(request)
-            if (response.isSuccessful) return response
+            if (response.isSuccessful && response.peekBody(Long.MAX_VALUE).string().contains("紳士漫畫")) return response
```
Comment (stevenyomi) [inline src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt]: Could there be a cheaper check? What's the URL that returned successful code?

Comment (stevenyomi) [reply src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt]: Doesn't this effectively blocks away all images? Did you test your changes?

Comment (lamaxama) [reply src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt]: At least check the content-type like this 
` if (response.header("content-type")?.startsWith("text/html") != true) {
            return response
        }`

Comment (stevenyomi) [reply src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt]: Please provide the problematic URL so we can decide what's the proper thing to do.

Comment (KenjieDec) [reply src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt]: Hello, sorry for the late reply. 

> At least check the content-type like this ` if (response.header("content-type")?.startsWith("text/html") != true) { return response }`

Hello, thanks for the suggestion. I'll try that! Thank you.

> Please provide the problematic URL so we can decide what's the proper thing to do.|

> Could there be a cheaper check? What's the URL that returned successful code?

Previous sites such as `hm01.lol`, `hm02.lol`, etc., are mostly parked, not dead, and they do return a status code of 200. And as for `cheaper check`, I'm not really sure, as this is what all I can think of to fix the issue, sorry.

> Doesn't this effectively blocks away all images? Did you test your changes?

Sorry, I'm not quite sure what you mean. What images are you referring to? All images loaded just fine on my phone. 

_I might've misunderstood your suggestion, and I'm sorry if I did, as English is not my primary language. Thank you. :pray:_

Comment (stevenyomi) [reply src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt]:
```suggestion
            if (response.isSuccessful && response.header("Server") != "Parking/1.0") return response
```

Comment (KenjieDec) [reply src/zh/wnacg/src/eu/kanade/tachiyomi/extension/zh/wnacg/Preferences.kt]: > At least check the content-type like this ` if (response.header("content-type")?.startsWith("text/html") != true) { return response }`

Hello, I’ve tried the code you suggested, and it seems that both the working and parked sites return a `text/html` content-type.
I also used `reqbin` to confirm that this behaviour isn’t specific to my device.

**Review by stevenyomi — APPROVED** [review]
