### PR TITLE
KomikCast (ID) : Fix chapter index field for new API format

### LINKED ISSUE #13507: Komik Cast: `Field 'index' is required` error with certain chapters
### Source information

Komik Cast 1.4.76

### Source language

Indonesia

### Steps to reproduce

1. Instal Komik Cast Extension in Mihon
2. Open new chapter form the source
3. Cant enter the New chapter

Image

### Expected behavior

The extension should be able to open the chapter

### Actual behavior

only the latest chapter can't be opened

### Mihon/Mihon fork version

Mohon 0.19.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Veloruze**
Make ChapterData.index nullable to handle chapters without index field. Add chapterIndex fallback field to ChapterItem for new API format. Update version to 77.

Closes #13507

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by vetleledaal — DISMISSED** [review]

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt [hunk 1]
```diff
@@ -95,7 +96,7 @@ fun SeriesItem.toSManga(): SManga = SManga.create().apply {
 }
 
 fun ChapterItem.toSChapter(seriesSlug: String?): SChapter = SChapter.create().apply {
-    val chapterIndex = data.index
+    val chapterIndex = data.index ?: chapterIndex ?: 0f
```
Comment (AwkwardPeak7) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt]:
```suggestion
    val chapterIndex = (data.index ?: chapterIndex)!!
```
it goes in the url, should not be null

**Review by AwkwardPeak7 — APPROVED** [review]
