### PR TITLE
EternalMangas: Move to Multi and fix pages not found

### LINKED ISSUE #3257: EternalMangas - 'No Pages Found'
### Source information

EternalMangas 1.4.1

### Source language

Spanish

### Steps to reproduce

1. Open the extension 
2. Select the work
3. Open a chapter 

### Expected behavior

The chapter pages should load and appear.

### Actual behavior

When I open a chapter it says 'No pages found'.

IMG_20240527_002006_723

### Mihon/Tachiyomi version

TachiJ2K 1.7.4

### Android version

Android 14

### Other details

Also when I look in the extension's filters, the 'update' part doesn't show recent works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Users will have to install the new extension under the `Multi` section, migration is not required.

Closes #3257

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/eternalmangas/src/eu/kanade/tachiyomi/extension/es/eternalmangas/EternalMangas.kt [hunk 1]
```diff
@@ -1,5 +1,85 @@
...
+        }
+
+        return document.select("main > img").mapIndexed { i, img ->
+            Page(i, imageUrl = img.imgAttr())
+        }
+    }
+
+    override fun setupPreferenceScreen(screen: PreferenceScreen) {
+        ListPreference(screen.context).apply {
+            key = LATEST_LANGUAGE_PREF
```
Comment (AwkwardPeak7) [inline src/es/eternalmangas/src/eu/kanade/tachiyomi/extension/es/eternalmangas/EternalMangas.kt]: make source factory with different langauages if possible

File: src/es/eternalmangas/src/eu/kanade/tachiyomi/extension/es/eternalmangas/EternalMangas.kt
Comment (AwkwardPeak7) [inline src/es/eternalmangas/src/eu/kanade/tachiyomi/extension/es/eternalmangas/EternalMangas.kt:1]: you didn't change the package

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/all/eternalmangas/src/eu/kanade/tachiyomi/extension/all/eternalmangas/EternalMangasFactory.kt [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+class EternalMangasFactory : SourceFactory {
+    override fun createSources() = listOf(
+        EternalMangasES(),
+        EternalMangasEN(),
+        EternalMangasPTBR(),
+    )
+}
+
+class EternalMangasES : EternalMangas("es", "es") {
+    override val id = 1533901034425595323
```
Comment (AwkwardPeak7) [inline src/all/eternalmangas/src/eu/kanade/tachiyomi/extension/all/eternalmangas/EternalMangasFactory.kt]: id should still be same since lang and name are same

**Review by AwkwardPeak7 — APPROVED** [review]
