### PR TITLE
MangaWorld: Fix MWCookie requirement

### LINKED ISSUE #7053: MangaWorld extension not working
### Source information

MangaWorld 1.4.8

### Source language

Italian

### Steps to reproduce

1. Update manga library
2. Get failed updating

### Expected behavior

Libray should get updated and i could get access to manga

### Actual behavior

I got error when updating library and when i select a manga it says "no page found"

### Mihon/Tachiyomi version

TachiyomiSY 1.10.0

### Android version

13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by PGgamer2**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

Closes #7053

### CODE REVIEW

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt [hunk 1]
```diff
@@ -28,7 +27,11 @@ abstract class MangaWorld(
 ) : ParsedHttpSource() {
 
     override val supportsLatest = true
-    override val client: OkHttpClient = network.cloudflareClient
+    override val client by lazy {
```
Comment (vetleledaal) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt]: Is `by lazy` required?

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt [hunk 2]
```diff
@@ -28,7 +27,11 @@ abstract class MangaWorld(
...
+        network.cloudflareClient.newBuilder()
+            .addInterceptor(ShittyRedirectionInterceptor(network.cloudflareClient))
```
Comment (vetleledaal) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt]: Maybe mention that MWCookie is required, and this interceptor handles it.

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt (hunk 1 above)
Comment (PGgamer2) [reply lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt]: Oops, that's a remnant from some previous tests I did while solving the issue. Removing it right now.

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt (hunk 2 above)
Comment (PGgamer2) [reply lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/MangaWorld.kt]: Sure, I'll leave a comment

**Review by vetleledaal — DISMISSED** [review]

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+import eu.kanade.tachiyomi.network.GET
+import okhttp3.Cookie
+import okhttp3.Interceptor
+import okhttp3.OkHttpClient
+import okhttp3.Request
+import okhttp3.Response
+import java.io.IOException
+
+class ShittyRedirectionInterceptor(private val client: OkHttpClient) : Interceptor {
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: please change the name :)

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+
+    override fun intercept(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val response = chain.proceed(request)
+        // ignore non-protected requests by checking for any header that doesn't show up when redirecting
+        if (response.headers["vary"] != null) return response
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: not important for now but they can easily break this

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+
+        return try {
+            val results = """document\.cookie="(MWCookie[^"]+)""".toRegex().find(response.body.string())
+                ?: return response
+            val (cookieString) = results.destructured
+            chain.proceed(loadCookie(request, cookieString))
+        } catch (e: Throwable) {
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: no need as app already handles it

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+        }
+    }
+
+    private fun loadCookie(request: Request, cookieString: String): Request {
+        val cookie = Cookie.parse(request.url, cookieString)!!
+        client.cookieJar.saveFromResponse(request.url, listOf(cookie))
+        val headers = request.headers.newBuilder()
+            .add("Cookie", cookie.toString())
+            .build()
+        return GET(request.url.toString(), headers)
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]:
```suggestion
        return GET(request.url, headers)
```

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+class ShittyRedirectionInterceptor(private val client: OkHttpClient) : Interceptor {
+
+    override fun intercept(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val response = chain.proceed(request)
+        // ignore non-protected requests by checking for any header that doesn't show up when redirecting
+        if (response.headers["vary"] != null) return response
+
+        return try {
+            val results = """document\.cookie="(MWCookie[^"]+)""".toRegex().find(response.body.string())
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: extract this regex to class so it isn't created everytime

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt (hunk 4 above)
Comment (PGgamer2) [reply lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: I left the check to avoid using the regex for every single page. Should I change it by checking the body length or should I use the regex for every request?

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt (hunk 3 above)
Comment (PGgamer2) [reply lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: donezo :(

**Comment by Vend0002** [comment]
Nice to see you working also here and hope the fix will be up soon. Love your work :)

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/CookieRedirectInterceptor.kt [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+    private val cookieRegex = Regex("""document\.cookie="(MWCookie[^"]+)""")
+
+    override fun intercept(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val response = chain.proceed(request)
+        // ignore non-protected requests by checking for any header that doesn't show up when redirecting
+        if (response.headers["vary"] != null) return response
+
+        val results = cookieRegex.find(response.body.string())
+            ?: return response
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/CookieRedirectInterceptor.kt]: response is consumed by this point (calling .string()) so returning it would cause exceptions

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt (hunk 4 above)
Comment (PGgamer2) [reply lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: ~I've changed that, now it checks the content type before proceeding (just to be sure) and straight up uses the Regex everytime. If nothing is found it just returns the request.~

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/CookieRedirectInterceptor.kt (hunk 8 above)
Comment (PGgamer2) [reply lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/CookieRedirectInterceptor.kt]: Fixed.

File: lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt (hunk 4 above)
Comment (PGgamer2) [reply lib-multisrc/mangaworld/src/eu/kanade/tachiyomi/multisrc/mangaworld/ShittyRedirectionInterceptor.kt]: Just reverted the content-type check. After a bit of tasking, I realized that it breaks even more easily than the older check, which does the job just fine

**Review by AwkwardPeak7 — APPROVED** [review]
