### PR TITLE
BlackoutComics: Fix auth

### LINKED ISSUE #4492: [PT-BR] Blackout Comics: 500: webview detected(?)
### Source information

Blackout Comics

### Source language

Portuguese (Brazilian)

### Steps to reproduce

1. Open extension
2. Login
3. Error

### Expected behavior

Load mangas

### Actual behavior

image

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #4492

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 1]
```diff
@@ -189,8 +235,53 @@ class BlackoutComics : ParsedHttpSource() {
...
+            Configure seu usuário para acessar o contéudo.
+            """.trimIndent()
+
+            setDefaultValue("")
+
+            setOnPreferenceChangeListener { _, newValue ->
+                preferences.edit()
+                    .putString(USERNAME_PREF, newValue as String)
+                    .apply()
+                true
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: not needed

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 2]
```diff
@@ -189,8 +235,53 @@ class BlackoutComics : ParsedHttpSource() {
...
+            """.trimIndent()
+
+            setDefaultValue("")
+
+            setOnPreferenceChangeListener { _, newValue ->
+                preferences.edit()
+                    .putString(PASSWORD_PREF, newValue as String)
+                    .apply()
+                true
+            }
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: here too

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 3]
```diff
@@ -34,22 +44,58 @@ class BlackoutComics : ParsedHttpSource() {
...
+        chain: Interceptor.Chain,
+    ): Response {
+        val csrf = response.asJsoup()
+            .selectFirst("input[name='_token']")
+            ?.attr("value") ?: ""
+
+        val form = FormBody.Builder()
+            .add("_token", csrf)
+            .add("email", credentials.first)
+            .add("password", credentials.second)
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt:85]: check the credentials if blank, then don't attempt login

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 4]
```diff
@@ -32,24 +42,74 @@ class BlackoutComics : ParsedHttpSource() {
...
+            if (it.request.url.pathSegments.contains("temp")) {
+                throw IOException(
+                    """
+                    Falha ao acessar recurso: Usuário ou senha incorreto.
+                    Altere suas credencias em Extensões > $name > Configuração.
+                    """.trimIndent(),
+                )
+            }
+        }
+        return chain.proceed(popularMangaRequest(0))
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]:
```suggestion
        return chain.proceed(response.request)
```
try the previous request?

Comment (choppeh) [reply src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: > response.request

Previous request is login page. If you're not logged in, it redirects to the login page, which is why I forced popularMangaRequest.

Comment (AwkwardPeak7) [reply src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: it redirects, so save the old request (chain.request() in line 70) and use that?

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 5]
```diff
@@ -32,24 +42,77 @@ class BlackoutComics : ParsedHttpSource() {
...
             .build()
     }
 
+    private val credentials: Pair<String, String> get() {
+        val username = preferences.getString(USERNAME_PREF, "")!!
+        val password = preferences.getString(PASSWORD_PREF, "")!!
+        return username to password
+    }
+
+    private lateinit var originRequest: Request
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: just pass it directly to function instead of global variable

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 6]
```diff
@@ -32,24 +42,77 @@ class BlackoutComics : ParsedHttpSource() {
...
+        originRequest = chain.request()
+        return chain.proceed(originRequest)
+    }
+
+    private fun authenticate(chain: Interceptor.Chain): Response {
+        val response = chain.proceed(chain.request())
+        if (response.request.url.pathSegments.contains("temp")) {
+            return doAuth(response, chain)
+        }
+        return response
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]:
```suggestion
        val request = chain.request()
        val response = chain.proceed(request)
        if (response.request.url.pathSegments.contains("temp")) {
            return doAuth(response, request, chain)
        }
        return response
```
something like this

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
