### PR TITLE
LuaScans: Fix missing chapters due to Timezone issue, closes #8292 & #7863

### LINKED ISSUE #7863: Lua Scans latest free chapter not detected
### Source information

1.4.47

### Source language

English 

### Steps to reproduce

Open or refresh any entry that has had a free chapter unlock 

### Expected behavior

The new chapter that is accessible in webview would appear in the chapter list

### Actual behavior

No new chapter is added

### Mihon/Tachiyomi version

0.17.1

### Android version

android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #8292: Lua Scans Not detecting some chapters
### Source information

Lua Scans 1.4.48

### Source language

English

### Steps to reproduce

1. Navigate to Lua Scans extension.
2. Search for the entry, "I Need to Raise My Sister Properly"
3. Try to read Chapters 79, 82, and 84 on Mihon app.

### Expected behavior

Chapters 79, 82, and 84 should be there, see the WebView image below.

Image

### Actual behavior

Chapters are missing on Tachiyomi app.

Image

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dragon-masterk**
Closes #8292, Closes #7863

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/luascans/src/eu/kanade/tachiyomi/extension/en/luascans/LuaScans.kt [hunk 1]
```diff
@@ -3,16 +3,17 @@ package eu.kanade.tachiyomi.extension.en.luascans
...
+import java.util.TimeZone
 
 class LuaScans : HeanCms(
     "Lua Scans",
     "https://luacomic.org",
     "en",
 ) {
     // Moved from Keyoapp to HeanCms
-    override val versionId = 3
+    override val versionId = 4
```
Comment (bapeey) [inline src/en/luascans/src/eu/kanade/tachiyomi/extension/en/luascans/LuaScans.kt]: This will change the source ID, forcing users to migrate. You must change `overrideVersionCode` in `build.gradle`

**Comment by bapeey** [comment]
Also add `Closes #8292, Closes #7863` in PR description

File: src/en/luascans/src/eu/kanade/tachiyomi/extension/en/luascans/LuaScans.kt (hunk 1 above)
Comment (dragon-masterk) [reply src/en/luascans/src/eu/kanade/tachiyomi/extension/en/luascans/LuaScans.kt]: bumped the version

**Comment by dragon-masterk** [comment]
Updated, let me know if I'm missing anything else

File: src/en/luascans/src/eu/kanade/tachiyomi/extension/en/luascans/LuaScans.kt (hunk 1 above)
Comment (bapeey) [reply src/en/luascans/src/eu/kanade/tachiyomi/extension/en/luascans/LuaScans.kt]: rollback this line

Comment (dragon-masterk) [reply src/en/luascans/src/eu/kanade/tachiyomi/extension/en/luascans/LuaScans.kt]: rolled it back

**Review by AwkwardPeak7 — APPROVED** [review]
