### PR TITLE
MadTheme: Enhance chapter parse

### LINKED ISSUE #3976: MangaBuddy Fetching the wrong series
### Source information

MangaBuddy 1.4.16

### Source language

English

### Steps to reproduce

1. Search for 4 cut hero 
2. Check the chapters and view them.
3. Check the chapters in the webview

### Expected behavior

 Both the web view and extensions should've shown the same 242 chapters.

### Actual behavior

The extension for some reason fetches 5 chapters from some random manga instead.

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dngonz**
Closes #3976

Now instead of just get chapters request by slug first try to get it by id.
Tested on all 14 extension that use it, but if someone found any other error please report.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/madtheme/src/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt [hunk 1]
```diff
@@ -177,30 +174,45 @@ abstract class MadTheme(
...
+        if (chapterRequest.code !in 200..299) {
+            chapterRequest =
+                client.newCall(GET("$baseUrl/api/manga/$bookSlug/chapters?source=detail", headers))
+                    .execute()
         }
 
-        throw Exception("HTTP error ${response.code}")
+        return chapterRequest.asJsoup().select("#chapter-list > li").map {
+            SChapter.create().apply {
+                url = it.selectFirst("a")!!.absUrl("href").removePrefix(baseUrl)
```
Comment (vetleledaal) [inline lib-multisrc/madtheme/src/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt:199]: Why not `setUrlWithoutDomain()`?

Also, some sites have 'external chapters', which requires the full URL. I don't remember the exact details, you can probably find some of the old issues linked to this. You might have to find an archive of the old Tachiyomi ext repo.

Comment (dngonz) [reply lib-multisrc/madtheme/src/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt:199]: That part of the code is from here, not sure where I can find the old ext to know why was like this
https://github.com/keiyoushi/extensions-source/blob/8f29ae5bf0094b3c6549ab52e4418dad633f2e2b/lib-multisrc/madtheme/src/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt#L227-L230

Comment (vetleledaal) [reply lib-multisrc/madtheme/src/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt:199]: My bad, I didn't recognize it without the comment. Using `.removePrefix(baseUrl)` will remove the baseUrl only if it is on the same domain. Otherwise it's an external chapter.

https://github.com/AwkwardPeak7/tachiyomi-extensions/commit/7579ca391f71d50a482b64ef8530ec8f3c3bb181

Here is the related issue:
> image

File: lib-multisrc/madtheme/src/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt [hunk 2]
```diff
@@ -177,30 +174,45 @@ abstract class MadTheme(
     }
 
     override fun chapterListParse(response: Response): List<SChapter> {
-        if (response.code in 200..299) {
+        if (response.request.url.fragment == "idFound") {
```
Comment (AwkwardPeak7) [inline lib-multisrc/madtheme/src/eu/kanade/tachiyomi/multisrc/madtheme/MadTheme.kt:177]: you return this `idFound` in `chapterListRequest` everytime, so when would the later code be called/necessary?

edit: nvm i missread the code

**Review by AwkwardPeak7 — APPROVED** [review]
