### PR TITLE
[Pepper&Carrot] multiples fixes

### LINKED ISSUE #7864: Pepper&carrot chapters not working
### Source information

Pepper&Carrot 1.4.2

### Source language

multi

### Steps to reproduce

Open any chapter of the English comic

### Expected behavior

Could read the chapter

### Actual behavior

Only the chapter cover is detected and displayed. Nothing of the actual chapter

### Mihon/Tachiyomi version

0.17.1

### Android version

android 14

### Other details

Source is a multi, but I don't know it the other languages are effected as well.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by gotson**
This PR fixes multiple small issues for Pepper & Carrot:
- retrieving the translated titles is done by doing a request to framagit.org, which is IP blocked in my country. When unreachable, nothing works. I added fallback in case that happens.
- fix the page list not being parsed properly for episodes. Closes #7864
- fix retrieving chapters, as the website has changed. The parsing of the upload date was failing.
- added support for the Mini Fantasy Theather, single image comics.

since it is used only for translated titles, we can omit that if it is unreachableChecklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrot.kt [hunk 1]
```diff
@@ -150,10 +172,9 @@ class PepperCarrot : HttpSource(), ConfigurableSource {
                         else -> substringBeforeLast('(').trimEnd()
                     }
                 }
-                date_upload = it.selectFirst(Evaluator.Tag("figcaption"))!!.ownText().let {
-                    val date = dateRegex.find(it)!!.value
-                    dateFormat.parse(date)!!.time
-                }
+                date_upload = it.selectFirst(Evaluator.Tag("figcaption"))?.text()?.let { text ->
+                    dateRegex.find(text)?.value?.let { date -> dateFormat.parse(date)?.time }
```
Comment (AwkwardPeak7) [inline src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrot.kt]:
```suggestion
                    dateRegex.find(text)?.value?.let { date -> dateFormat.tryParse(date) }
```
import `keiyoushi.utils.tryParse`

Comment (gotson) [reply src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrot.kt]: thanks for the tip, added!

**Review by vetleledaal — APPROVED** [review]
