### PR TITLE
Fix Shinigami (ID)

### LINKED ISSUE #30: Shinigami (ID) Domain Change
### Source information

Shinigami 1.4.42

### Source language

Indonesia

### Source new URL

https://shinigamitoon.com/

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by C0rvidae**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #30 
Tested on virtual Pixel 6 and real Pixel 6
To test again: set valid User-Agent and VPN in Indonesia to pass Cloudflare in Tachiyomi

### CODE REVIEW

File: multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt [hunk 1]
```diff
@@ -433,7 +433,7 @@ class MadaraGenerator : ThemeSourceGenerator {
         SingleLang("Shayami", "https://shayami.com", "es"),
         SingleLang("Shiba Manga", "https://shibamanga.com", "en"),
         SingleLang("Shield Manga", "https://shieldmanga.io", "en", overrideVersionCode = 3),
-        SingleLang("Shinigami", "https://shinigami.moe", "id", overrideVersionCode = 10),
+        SingleLang("Shinigami", "https://shinigamitoon.com/", "id", overrideVersionCode = 11),
```
Comment (AwkwardPeak7) [inline multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt]:
```suggestion
        SingleLang("Shinigami", "https://shinigamitoon.com", "id", overrideVersionCode = 11),
```
Remove trailing slash

File: multisrc/overrides/madara/shinigami/src/Shinigami.kt [hunk 2]
```diff
@@ -25,7 +25,7 @@ import uy.kohesive.injekt.api.get
 import java.io.IOException
 import java.util.concurrent.TimeUnit
 
-class Shinigami : Madara("Shinigami", "https://shinigami.moe", "id") {
+class Shinigami : Madara("Shinigami", "https://shinigamitoon.com/", "id") {
```
Comment (AwkwardPeak7) [inline multisrc/overrides/madara/shinigami/src/Shinigami.kt]: here too

Comment (C0rvidae) [reply multisrc/overrides/madara/shinigami/src/Shinigami.kt]: Will know for next time, my bad

**Comment by FourTOne5** [comment]
Thanks for the contribution
