### PR TITLE
Yugen Mangás: Update domain and fix pagelist

### LINKED ISSUE #3734: Yugen Mangás alteração de url
### Source information

Yugen Mangás 1.4.39

### Source language

Português Brasil 

### Source new URL

https://yugenapp.lat/

### Other details

Foi alterado a url da Yugen Mangás 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Yush0DAN**
Closes: #3734

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangasDto.kt [hunk 1]
```diff
@@ -76,3 +76,8 @@ data class YugenChapterDto(
 data class YugenGetChaptersBySeriesDto(
```
Comment (AwkwardPeak7) [inline src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangasDto.kt:76]:
```suggestion
class YugenGetChaptersBySeriesDto(
```

File: src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangasDto.kt [hunk 2]
```diff
@@ -73,6 +73,11 @@ data class YugenChapterDto(
 }
 
 @Serializable
-data class YugenGetChaptersBySeriesDto(
+class YugenGetChaptersBySeriesDto(
```
Comment (AwkwardPeak7) [inline src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangasDto.kt]:
```suggestion
data class YugenGetChaptersBySeriesDto(
```

**Review by AwkwardPeak7 — APPROVED** [review]
