### PR TITLE
RawDex (KO): Fix CloudFlare - add date & status selectors

### LINKED ISSUE #14514: [KO] RawDEX: Error 403 and parse information error
### Source information

RawDex 1.4.47

### Source language

Korean

### Steps to reproduce

After you fixed the search issue, I added some manhwa to my library. However, when I tried to read, e.g. "Small Beast," I got an 403 error. Additionally, there are errors with Status showing "unknown" when on website is showing "OnGoing, Competed, etc" and Chapter time is showing "yesterday" on all chapters instead of actual time.

Image

Image

### Expected behavior

Should access the chapter and parse serie info correctly

Image

Image

Image

### Actual behavior

Getting error 403 when trying to read and some small parse problems related to showing information

### Mihon/Mihon fork version

Mihon 0.19.7

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by disk-iq8**
Closes #14514

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ko/rawdex/src/eu/kanade/tachiyomi/extension/ko/rawdex/RawDEX.kt [hunk 1]
```diff
@@ -1,12 +1,18 @@
...
 import eu.kanade.tachiyomi.multisrc.madara.Madara
+import java.text.SimpleDateFormat
+import java.util.Locale
 
 class RawDEX :
     Madara(
         "RawDEX",
         "https://rawdex.net",
         "ko",
+        SimpleDateFormat("dd.MM.yyyy", Locale.US),
```
Comment (vetleledaal) [inline src/ko/rawdex/src/eu/kanade/tachiyomi/extension/ko/rawdex/RawDEX.kt]: No locale-specific patterns used.
```suggestion
        SimpleDateFormat("dd.MM.yyyy", Locale.ROOT),
```

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
