### PR TITLE
Manhastro: fix chapter images

### LINKED ISSUE #1347: Manhastro: Not loading entire chapters
### Source information

Manhastro 1.4.33

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Open the extension 
2. Wait to load 
3. Click on any work 
4. Open a chapter

### Expected behavior

All chapter pages should load in the application.

### Actual behavior

This red warning image appears and only loads a few chapters, but when you open it in the webview the chapter is normal.

English translation of the image:
64 Sem Título_20240217171724

### Mihon/Tachiyomi version

1.7.4 (TachiJ2K)

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #1347

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/manhastro/src/eu/kanade/tachiyomi/extension/pt/manhastro/Manhastro.kt [hunk 1]
```diff
@@ -19,4 +23,16 @@ class Manhastro : Madara(
...
 
     override val useNewChapterEndpoint = true
+
+    override fun pageListParse(document: Document): List<Page> {
+        return document.selectFirst("script:containsData(imageLinks)")?.data()
+            ?.let { imageLinksPattern.find(it)?.groups?.get(1)?.value }
+            ?.let { json.decodeFromString<List<String>>(it) }
+            ?.mapIndexed { i, imageUrlEncoded ->
+                val imageUrl = String(Base64.decode(imageUrlEncoded, Base64.DEFAULT))
+                Page(i, imageUrl = imageUrl)
```
Comment (AwkwardPeak7) [inline src/pt/manhastro/src/eu/kanade/tachiyomi/extension/pt/manhastro/Manhastro.kt]:
```suggestion
                Page(i, document.location(), imageUrl)
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
