### PR TITLE
Invinciblescans: Trial and error the file extension of images.

### LINKED ISSUE #10181: 404 on multiple entries in Invincible ComicsVF
### Source information

Invincible ComicsVF

### Source language

French

### Steps to reproduce

Add a source like "Seuls" or "Spider Girl" and try opening a "Tome"

### Expected behavior

No 404

### Actual behavior

HTTP 404

### Mihon/Tachiyomi version

Latest

### Android version

Android 16

### Other details

In webview everything is fine, the "Tome"s are in the website and can be opened

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Starmania**
Closes #10181 

Bonus: fix the status detection that was containing a typo

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt [hunk 1]
```diff
@@ -114,12 +116,32 @@ class InvincibleComics : HttpSource() {
             ?: error("Failed to extract total pages from script")
 
         return (1..totalPages.toInt()).map { pageNumber ->
-            Page(pageNumber, imageUrl = "$imageBaseUrl${"%03d".format(pageNumber)}.png")
+            Page(pageNumber, "$imageBaseUrl${"%03d".format(pageNumber)}.png")
```
Comment (stevenyomi) [inline src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]: Should try `.jpg` first.

Comment (Starmania) [reply src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]: PNG shound have a higher resolution...

Comment (stevenyomi) [reply src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]: That's what the website does. I guess they just upload either of JPEG and PNG so only one would succeed. You have examples where both exist?

Comment (stevenyomi) [reply src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]: Ideally you should add an interceptor to spot 404 requests with ".jpg" suffix and retry them with ".png" so you don't need one more HEAD request for each image - just do the default GET.

Comment (Starmania) [reply src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]: I didn't found any examples so I rolled back

File: src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt [hunk 2]
```diff
@@ -22,6 +22,20 @@ class InvincibleComics : HttpSource() {
 
     override val supportsLatest = true
 
+    override val client = network.cloudflareClient.newBuilder().addNetworkInterceptor { chain ->
```
Comment (stevenyomi) [inline src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]:
```suggestion
    override val client = network.cloudflareClient.newBuilder().addInterceptor { chain ->
```
You cannot send another request inside a network interceptor.

File: src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt [hunk 3]
```diff
@@ -114,12 +128,12 @@ class InvincibleComics : HttpSource() {
...
 
         return (1..totalPages.toInt()).map { pageNumber ->
-            Page(pageNumber, imageUrl = "$imageBaseUrl${"%03d".format(pageNumber)}.png")
+            Page(pageNumber, imageUrl = "$imageBaseUrl${"%03d".format(pageNumber)}.jpg")
         }
     }
 
     // Page
-    override fun imageUrlParse(response: Response): String = throw UnsupportedOperationException()
+    override fun imageUrlParse(response: Response): String = throw UnsupportedOperationException("Not used")
```
Comment (stevenyomi) [inline src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]: Remove the message.

File: src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt [hunk 4]
```diff
@@ -114,7 +129,7 @@ class InvincibleComics : HttpSource() {
             ?: error("Failed to extract total pages from script")
 
         return (1..totalPages.toInt()).map { pageNumber ->
-            Page(pageNumber, imageUrl = "$imageBaseUrl${"%03d".format(pageNumber)}.png")
+            Page(pageNumber, imageUrl = "$imageBaseUrl${"%03d".format(pageNumber)}.jpg")
```
Comment (AwkwardPeak7) [inline src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]: I would say an a fragment in the url, and check for that fragment in the interceptor, this way we only apply the logic on chapter pages instead of thumbnails
```kt
            Page(pageNumber, imageUrl = "$imageBaseUrl${"%03d".format(pageNumber)}.jpg#page")
```

File: src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt [hunk 5]
```diff
@@ -22,6 +22,21 @@ class InvincibleComics : HttpSource() {
...
+        val res = chain.proceed(chain.request())
+
+        if (res.code != 404) return@addInterceptor res
+
+        res.close()
+        val newRequest = chain.request().newBuilder()
+            .url(chain.request().url.toString().replace(".jpg", ".png"))
+            .build()
+
+        chain.proceed(newRequest)
```
Comment (AwkwardPeak7) [inline src/fr/invinciblecomics/src/eu/kanade/tachiyomi/extension/fr/invinciblecomics/InvincibleComics.kt]:
```suggestion
        val request = chain.request()
        val response = chain.proceed(request)
        
        if (request.url.fragment != "page" || response.code != 404) {
            return@addInterceptor response
        }

        response.close()
        val newRequest =request.newBuilder()
            .url(request.url.toString().replace(".jpg", ".png"))
            .build()

        chain.proceed(newRequest)
```

**Review by AwkwardPeak7 — APPROVED** [review]
