### PR TITLE
MangaGo: fix missing image urls

### LINKED ISSUE #7138: Mangago only loads a few pages
### Source information

Mangago 1.4.24

### Source language

English

### Steps to reproduce

1. Open Eleceed with the mangago extension
2. Wait for pages to load
3. Any page after 5 does not work even though I can see it through webview

### Expected behavior

All pages should load

### Actual behavior

No pages load after page 5

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by valonsodev**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

---

Fixes https://github.com/keiyoushi/extensions-source/issues/7138 

---

Summary:
- Mangago returns a decrypted imgsrcs list from chapter HTML
- Normal manga return image urls for every page.
- In webcomics the imgsrcs only contains urls for 5 images (eg: getting page 3 returns images from 3 to 7), while the other array elements are empty. Thus to get all image urls we need to fetch HTML `pages / 5` times.
- Something in the URL format changed from the previous version
- It's better to use the page selection dropdown for links since it was already used to check how many pages a chapter has.

---

There is some special `synchronized` logic to make the reader experience better since without it the chapter would query all pages from the beginning and take a while to start reading or query unneeded HTML

### CODE REVIEW

**Comment by valonsodev** [comment]
Some mangas use a different URL without a URL part for the first page like `https://.../chapter/79860/2183173/` and were failing, now fixed

File: src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt [hunk 1]
```diff
@@ -29,18 +29,52 @@ import okhttp3.HttpUrl.Companion.toHttpUrl
...
+        val iv: ByteArray,
+        val time: Long,
+    )
+
+    private val chapterStates = mutableMapOf<String, ChapterState>()
+    private val pageContexts = WeakHashMap<Page, PageContext>()
+    private val chunkStateLock = Any()
+    private val chapterJsCache = mutableMapOf<String, ChapterJsDecryptCache>()
+    private val chapterJsCacheLocks = mutableMapOf<String, Any>()
+    private val chapterJsCacheLock = Any()
```
Comment (AwkwardPeak7) [inline src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt]: this kind of state can be removed if user restarts the app, while the page list is still cached. 
I would suggest putting all the necessary information in the page/image url as json encoded fragment, this way you have the relivant/necessary information in the url and can access it in `fetchImageUrl`

Comment (valonsodev) [reply src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt]: I took a slightly different approach with this. Basically, I removed the URL parsing since it was a bit flaky and instead opted to use the page URLs from the dropdown that were already being used, passing them as `Page.url`

Now, in `fetchImageUrl`, if the cache already has the `imageUrl` (from being part of a previously requested chunk), it's returned immediately. If not, Page.url is requested and the cache is filled for that chunk of images. Since it caches all non-empty URLs returned, the chunk size is no longer hardcoded.

If the app is restarted it doesn't matter since we can continue from whatever `Page.url` we are currently on and request the HTML and JS to decrypt again.

The cache is there to not request the HTML many times over when one chunk already contains URLs to `CHUNK_SIZE` images

**Review by AwkwardPeak7 — APPROVED** [review]
