### PR TITLE
weebcentral: add extra info, format manga details

### LINKED ISSUE #7574: Weeb Central feature rework
### Source name

Weeb Central

### Source language

English

### Describe your suggested feature

Right now, Weeb Central does three things wrong:

1. It displays the status of the translations (“Official translations” if the manga has been updated with at least on English volume) in the manga description.
2. That information along with alternative names is displayed _above_ the manga description, which design-wise doesn’t make much sense. The description should take precedence, no?
3. The extension pulls the translation status of each chapter and displays it in the app. Theoretically, that should be a useful feature. Unfortunately, NepNep didn’t update the translation status of most of the already completed series after migrating to WeebCentral, so we end up with many, many fully officially translated series having “unofficial” chapters.

The solutions are fairly simple:

1. Remove the translation status from the manga description. It’s redundant information, especially after adding the per-chapter translation status.
2. Have the description be above everything else.
3. As for this, I am torn. On one hand, its inclusion isn’t all that offensive, even if it is an actual source of misinformation (for which Nep is at fault). On the other hand, it looks plain bad when you know for a fact that a chapter has official translations yet the app tells you otherwise.

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by mrtear**
Checklist:
Closes #7574
Supersedes #7576

weeb

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt [hunk 1]
```diff
@@ -163,7 +167,7 @@ class WeebCentral : ParsedHttpSource() {
         element.selectFirst("svg")?.attr("stroke")?.also { stroke ->
             scanlator = when (stroke) {
                 "#d8b4fe" -> "Official"
-                "#4C4D54" -> "Unofficial"
+                "#4C4D54" -> "unknown"
```
Comment (AwkwardPeak7) [inline src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt]: just remove this, so only "official" appears when necessary

File: src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt [hunk 2]
```diff
@@ -107,27 +107,31 @@ class WeebCentral : ParsedHttpSource() {
...
             )
+
+            val relatedSeries = select("li:has(strong:contains(Related Series)) li")
+            if (relatedSeries.size > 0) {
+                descBuilder.append("\n\nRelated Series(s):")
+                relatedSeries.forEach { series ->
+                    val name = series.selectFirst("a")?.text()
+                    val relation = series.selectFirst("span")?.text()
+                    descBuilder.append("\n").append("• $name $relation")
+                }
```
Comment (AwkwardPeak7) [inline src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt]:
```suggestion
                relatedSeries.forEach { series ->
                    descBuilder.append("\n").append("• ${series.text()")
                }
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt (hunk 1 above)
Comment (Mythos) [reply src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt]: I'd prefer to have it in, as in the current state, the scanlator filter works on a blacklist basis.

With "Unofficial" or "Unknown" I'd be able to only show official chapters, as I prefer to read official translations if possible. (if the website has them marked as official of course)

Without that info that filtering wouldn't be possible anymore, unless someone makes the scanlator filter support both white- and blacklists.

Comment (Norsze) [reply src/en/weebcentral/src/eu/kanade/tachiyomi/extension/en/weebcentral/WeebCentral.kt]: @Mythos rejected

**Comment by scb261** [comment]
Imo, it's better to have "Unknown" or "Unofficial" for the grey checkmarks.

Filtering is quite a good reason for this. Personally, for some manga, I read only official scans. And I'm guessing there are other people who do this.

Another reasoning is that if Nep ever changes the checkmarks to something else, it will be easier to notice. I.e., with the current implementation, if the design of checkmarks ever changes, the source would start showing nothing for official scans, and the user would assume that it's just unofficial/unknown scans.

**Comment by AwkwardPeak7** [comment]
sure

**Review by AwkwardPeak7 — APPROVED** [review]
