### PR TITLE
Fix Mangalionz

### LINKED ISSUE #5732: Mangalionz: http 404
"Mangalionz:titles shows error 404 but works in webview"

Mangalionz 1.4.40

### Source language

Arabic

### Steps to reproduce

1. I opened the extension 
2.checked for recent update
3.opened the webview and finally checked for connection error or problems from the site

### Expected behavior

I updated everything to the latest version but the extension doesn't work and when I enter a manhwa it keep giving me an error 404 while working fine in the webview 

### Actual behavior

The extension kept giving me the same error for everything no chapters showing 

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 14

### Other details

There is no problem from my phone or from the app the site is breaking down the extension for almost 4 months

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by xMohnad**
Removed the `popularMangaFromElement` method because the site now provides thumbnails directly. 

Closes #5732

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ar/mangalionz/src/eu/kanade/tachiyomi/extension/ar/mangalionz/MangaLionz.kt [hunk 1]
```diff
@@ -1,35 +1,84 @@
...
+        super.searchMangaRequest(page, query, filters)
+    }
 
-            selectFirst("img")?.let {
-                manga.thumbnail_url = imageFromElement(it)?.replace("mangalionz", "mangalek")
+    override fun searchMangaParse(response: Response): MangasPage {
+        val body = response.body.string()
+
+        return try {
+            val dto = body.parseAs<SearchResponseDto>()
```
Comment (AwkwardPeak7) [inline src/ar/mangalionz/src/eu/kanade/tachiyomi/extension/ar/mangalionz/MangaLionz.kt]: check request url and decide on json parsing or html. (`response.request.url`)

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/ar/mangalionz/src/eu/kanade/tachiyomi/extension/ar/mangalionz/MangaLionz.kt (hunk 1 above)
Comment (xMohnad) [reply src/ar/mangalionz/src/eu/kanade/tachiyomi/extension/ar/mangalionz/MangaLionz.kt]: the urls are the same, so I used the Content-Type.

**Review by AwkwardPeak7 — APPROVED** [review]
