### PR TITLE
Hiperdex: Fix chapter date parsing

### LINKED ISSUE #10670: Hiperdex: Not parsing chapter dates
### Source information

Hiperdex

### Source language

English

### Steps to reproduce

1. Open any Manga in Hiperdex
2. Look at the list of chapters and their correspondent dates 

### Expected behavior

Each chapter should have the correct date. 

### Actual behavior

Each chapter will have their date as today

### Mihon/Tachiyomi version

Latest mihon

### Android version

11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Smol-Ame**
Closes #10670

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt [hunk 1]
```diff
@@ -11,12 +11,15 @@ import eu.kanade.tachiyomi.multisrc.madara.Madara
 import eu.kanade.tachiyomi.network.interceptor.rateLimit
 import eu.kanade.tachiyomi.source.ConfigurableSource
 import keiyoushi.utils.getPreferences
+import java.text.SimpleDateFormat
+import java.util.Locale
 
 class Hiperdex :
     Madara(
         "Hiperdex",
         "https://hiperdex.tv",
```
Comment (vetleledaal) [inline src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt]: They also switched back to the `.com` domain.

**Comment by KurtzPT** [comment]
The URL can be changed in the options, it shouldn't be a blocker to fix the date issue, so could be this approved? It's making a mess of my library.

**Comment by Smol-Ame** [comment]
@KurtzPT Can you stop unnecessarily commenting? People have lives, I haven't resolved the domain change, and maintainers don't have a schedule to review & approve requests. All the work is done by people volunteering their own time and efforts, wait patiently.

**Comment by KurtzPT** [comment]
@Smol-Ame I'm sorry if I hurt your feeling with a valid comment, my message wasn't worth tagging as spam but whatever makes you feel better.

**Review by AwkwardPeak7 — APPROVED** [review]
