### PR TITLE
fix(poseidonscans): update url and configure premium chapters

### LINKED ISSUE #11624: Poseidon Scans: `No results found` error, missing thumbnails in Latest/Popular tab
### Source information

Poseidon Scans 1.4.47,1.4.48

### Source language

French

### Steps to reproduce

1. Navigate in the Popular tab => Nothing show up (No results found)
2. Navigate in Recents => Some mangas have a broken thumbnail

### Expected behavior

Popular should show some results
Every mangas of Recents should have a Thumbnail

### Actual behavior

See before

### Mihon/Tachiyomi version

0.19.3

### Android version

15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

_Originally posted by @Starmania in https://github.com/keiyoushi/extensions-source/issues/11622#issuecomment-3529394254_

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13557: Poseidon Scans: Error HTTP 403
### Source information

Poseidon Scans 1.4.49

### Source language

French

### Steps to reproduce

Opens Poseidon Scans extension

### Expected behavior

Displays a list of manhwa

### Actual behavior

Displays the error “HTTP 403” even though the site works in the webview.

Image

Image

### Mihon/Mihon fork version

Mihon 0.19.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #14225: URL change : Poseidon Scans
### Source information

Poseidon Scans 1.4.49

### Source language

French 

### Source new URL

https://poseidon-scans.net/

### Other details

_No response_

### Acknowledgements

- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have checked WebView to see the source's main URL is not up-to-date, or has to redirect into the new URL.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues/) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Starmania**
Closes #14225 
Closes #13557
Closes #13573
Closes #11624
Closes #14265

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Starmania** [comment]
I need to partially revert the scrapping of chapter list because it's currently broken.  Manga details were improved and reading chapter is fine.

File: src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt [hunk 1]
```diff
@@ -65,267 +74,54 @@ class PoseidonScans : HttpSource() {
...
-                                }
-                            }
-                            return null
-                        }
-                        if (foundRelevantObject == null) foundRelevantObject = tryParseAndValidate("\"initialData\":{", cleanedDataString)
-                        if (foundRelevantObject == null) foundRelevantObject = tryParseAndValidate("\"manga\":{", cleanedDataString)
-                        if (foundRelevantObject == null) foundRelevantObject = tryParseAndValidate("\"chapter\":{", cleanedDataString)
+    override fun popularMangaParse(response: Response): MangasPage {
+        val document = response.body.string()
+        val mangaDtos = document.extractNextJsRsc<List<PopularMangaData>>()
```
Comment (AwkwardPeak7) [inline src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt]:
```suggestion
        val mangaDtos = response.extractNextJs<List<PopularMangaData>>()
```

File: src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt [hunk 2]
```diff
@@ -342,22 +138,13 @@ class PoseidonScans : HttpSource() {
...
-
-            mangaDto.alternativeNames?.takeIf { it.isNotBlank() }?.let { altNames ->
-                val trimmedAltNames = altNames.trim()
-                if (finalDesc == "Aucune description.") {
-                    finalDesc = "Noms alternatifs: $trimmedAltNames"
-                } else {
-                    finalDesc += "\n\nNoms alternatifs: $trimmedAltNames"
-                }
-            }
+            val finalDesc = potentialDescription?.takeIf { it.isNotBlank() } ?: "Aucune description."
```
Comment (AwkwardPeak7) [inline src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt]:
```suggestion
            val finalDesc = potentialDescription?.takeIf { it.isNotBlank() }
```
leave it null

**Comment by realspinelle** [comment]
Thx

File: src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt [hunk 3]
```diff
@@ -342,22 +137,13 @@ class PoseidonScans : HttpSource() {
             }
 
             if (potentialDescription.isNullOrBlank()) {
-                val jsonDescription = mangaDto.description?.trim()
-                if (!jsonDescription.isNullOrBlank() && jsonDescription.length > 5 && !jsonDescription.startsWith("$")) {
+                val jsonDescription = mangaDto.description.trim()
+                if (jsonDescription.isNotBlank() && jsonDescription.length > 5 && !jsonDescription.startsWith("$")) {
```
Comment (vetleledaal) [inline src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt]: First condition is useless.
```suggestion
                if (jsonDescription.length > 5 && !jsonDescription.startsWith("$")) {
```

File: src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt [hunk 4]
```diff
@@ -481,6 +296,10 @@ class PoseidonScans : HttpSource() {
         return GET(page.imageUrl!!, imageHeaders)
     }
 
+    override fun imageUrlParse(response: Response): String = throw UnsupportedOperationException("Not used.")
```
Comment (vetleledaal) [inline src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt]: Remove text for consistency.
```suggestion
    override fun imageUrlParse(response: Response): String = throw UnsupportedOperationException()
```

File: src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt [hunk 5]
```diff
@@ -443,30 +264,24 @@ class PoseidonScans : HttpSource() {
...
-
-        val imagesDataList = try {
-            imagesListJson.toString().parseAs<List<PageImageUrlData>>()
-        } catch (e: Exception) {
-            throw Exception("Error parsing image list: ${e.message}. JSON: $imagesListJson")
+        val pageDataDto = response.extractNextJs<PageData>()
+            ?: throw Exception("Cant scape data from nextjs")
+        if (pageDataDto.currentChapter.isPremium) {
+            if (pageDataDto.sessionStatus == "unauthenticated") {
+                throw Exception("This chapter is premium. Please connect via the webview to view.")
```
Comment (vetleledaal) [inline src/fr/poseidonscans/src/eu/kanade/tachiyomi/extension/fr/poseidonscans/PoseidonScans.kt]: Prefer using proper names:
```suggestion
            ?: throw Exception("Cant scape data from Next.js")
        if (pageDataDto.currentChapter.isPremium) {
            if (pageDataDto.sessionStatus == "unauthenticated") {
                throw Exception("This chapter is premium. Please connect via the WebView to view.")
```

suggestion applies elsewhere too.

**Comment by Starmania** [comment]
Verified and everything still working

**Review by vetleledaal — APPROVED** [review]
