### PR TITLE
Fix HentaiRead

### LINKED ISSUE #6386: Hentairead chapters not downloading
### Source information

Hentairead

### Source language

English 

### Steps to reproduce

When I tried to dl any chapters it says 

" Unexpected JSON token at offset 2:

Expected start of the object '{', but had '/' instead at path: $[0]

JSON input: [ /* <CDATA[ */

var chapterExt..... "

### Expected behavior

Is supposed be normal to download any chapters.

### Actual behavior

It giving errors and I think its almost a month now.

![Screenshot_2024-11-29-19-12-13-28_afd66b7916d19a60815f56273408b73e

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Closes #6386

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 1]
```diff
@@ -189,14 +189,18 @@ class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateForm
     override fun pageListParse(document: Document): List<Page> {
         launchIO { countViews(document) }
 
-        val pages = document.selectFirst("[id=single-chapter-js-extra]")?.data()
-            ?.substringAfter(":[")
-            ?.substringBefore("],")
-            ?.let { json.decodeFromString<List<PageDto>>("[$it]") }
+        val pageBaseUrl = document.selectFirst("[id=single-chapter-js-extra]")?.data()
+            ?.substringAfter("chapterExtraData = ")
+            ?.substringBefore(";")?.let { json.decodeFromString<ImageBaseUrlDto>(it).baseUrl }
```
Comment (vetleledaal) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: Use a regex for this. It is more flexible.

Current implementation is equivalent to:
```regex
chapterExtraData = (.*?);
```
but you probably want:
```regex
\bchapterExtraData\s*=\s*(.*);
```

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 2]
```diff
@@ -189,14 +189,18 @@ class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateForm
...
+
+        val pages = document.selectFirst("[id=single-chapter-js-before]")?.data()
+            ?.substringAfter("= '")
+            ?.substringBefore("'")
```
Comment (vetleledaal) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: Also use regex here.

current is equivalent to:
```regex
= '(.*?)'
```

but you probably want:
```regex
=\s*'(.*)'
```

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 3]
```diff
@@ -189,14 +189,18 @@ class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateForm
...
+            ?.let { json.decodeFromString<PagesDto>(String(Base64.decode(it, Base64.DEFAULT))) }
             ?: throw Exception("Failed to find page list. Non-English entries are not supported.")
 
-        return pages.mapIndexed { idx, page ->
-            Page(idx, document.location(), page.src)
+        return pages.data.chapter.images.mapIndexed { idx, page ->
+            Page(idx, document.location(), "$pageBaseUrl/${page.src}")
```
Comment (vetleledaal) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt:208]: Does this escape URLs properly?

Assuming the least, it would break in this scenario:
- `page.src` is a filename
- the filename is `example#filename.png`
- it will try to load `$pageBaseUrl/example` instead of `$pageBaseUrl/example%23filename.png`

**Review by vetleledaal — CHANGES_REQUESTED** [review]

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt (hunk 3 above)
Comment (Creepler13) [reply src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt:208]: I think its fine the pages are saved like this 
```json
[{"src":"239236\/66227\/hr_0001.jpg","width":1280,"height":1810}...n]
```
and the baseUrl like this
```json
{ "baseUrl": "https:\/\/henread.xyz" }
```

Comment (vetleledaal) [reply src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt:208]: Thanks for clarifying. If this was escaped, it would turn `/` into `%2F`, which would be wrong.

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 4]
```diff
@@ -185,17 +185,19 @@ class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateForm
         }
     }
 
+    private val chapterExtraDataRegex = Regex("= (\\{[^;]+)")
+    private val pagesDataRegex = Regex(".(ey\\S+).\\s")
```
Comment (vetleledaal) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: Use `"""` to  avoid escaping inside the regex. Since these are sufficiently complex you should show a cut down example of the intended target text.

**Review by AwkwardPeak7 — APPROVED** [review]
