### PR TITLE
TsukiMangas: Fix

### LINKED ISSUE #3831: Tsuki Mangás "hidden" manga not showing
### Source information

Tsuki Mangás 1.4.5

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Open the extension on webview
2. Creat or signin in an account
3. Try searching for 'Dragon-Devouring Mage'

### Expected behavior

it should fetch the manwha after sign-in, as you can check on the site before it doesn't shows it, but after signing it is possible to find it

### Actual behavior

doesn't show up

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes  #3831

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt [hunk 1]
```diff
@@ -38,6 +48,40 @@ class TsukiMangas : HttpSource() {
...
+    @delegate:SuppressLint("SetJavaScriptEnabled")
+    private val token: String by lazy {
+        val latch = CountDownLatch(1)
+        var token = ""
+        Handler(Looper.getMainLooper()).post {
+            val webView = WebView(Injekt.get<Application>())
+            with(webView.settings) {
+                javaScriptEnabled = true
+                domStorageEnabled = true
+                databaseEnabled = true
```
Comment (AwkwardPeak7) [inline src/pt/tsukimangas/src/eu/kanade/tachiyomi/extension/pt/tsukimangas/TsukiMangas.kt:60]:
```suggestion
                databaseEnabled = true
                blockNetworkImage = true
```
if it works with this option that is

**Review by AwkwardPeak7 — APPROVED** [review]
