### PR TITLE
Kagane: Fix chapters error and search

### LINKED ISSUE #10688: Kagane: `field 'page_count'` chapter error / `Unexpected JSON token` search error
### Source information

Kagane 1.4.1

### Source language

English

### Steps to reproduce

1- Migrate manga
2- Get this error:

Image

### Expected behavior

1- Migrate manga
2- Correct or similar manga show's up in the migration search result

### Actual behavior

1- Migrate manga
2- Get this error:

Image

### Mihon/Tachiyomi version

Komikku 1.13.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #10688

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 1]
```diff
@@ -141,76 +138,71 @@ class Kagane : HttpSource(), ConfigurableSource {
...
-        val url = "$baseUrl/search".toHttpUrl().newBuilder().apply {
-            addQueryParameter("name", query)
-            addQueryParameter("page", page.toString())
-        }.build()
+        val body = buildJsonObject { }
+            .toJsonString()
+            .toRequestBody("application/json".toMediaType())
+
+        val url = apiUrl.toHttpUrl().newBuilder().apply {
+            addPathSegments("api/v1/search")
```
Comment (vetleledaal) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]:
```suggestion
        val url = "$apiUrl/api/v1/search".toHttpUrl().newBuilder().apply {
```

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
