### PR TITLE
GocTruyenTranhVui: Using the token of a level 1 account. Login is no longer required.

### LINKED ISSUE #9838: Can't view login-required chapters GocTruyenTranhVui
### Source information

GocTruyenTranhVui 1.4.1

### Source language

Vietnamese

### Steps to reproduce

1/ Logged in through Webview and confirmed that all chapters are accessible.
2/ Open said chapters in Tachiyomi/ Mihon, but errors showed **Không có nội dung. Hãy đăng nhập trong WebView** (aka. No content, please login through Webview)

### Expected behavior

All chapters that are available in Webview after logging in should be available for reading in Tachiyomi as well.

### Actual behavior

This error showed **Không có nội dung. Hãy đăng nhập trong WebView** (aka. No content, please login through Webview)

### Mihon/Tachiyomi version

TachiyomiSY Stable 1.12.0

### Android version

Android 15

### Other details

[related ](https://github.com/keiyoushi/extensions-source/issues/9440)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dejavui**
Checklist:
Closes #9838

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt [hunk 1]
```diff
@@ -33,6 +35,8 @@ class GocTruyenTranhVui : HttpSource() {
 
     override fun headersBuilder(): Headers.Builder = super.headersBuilder()
         .add("Referer", "$baseUrl/")
+        .add("X-Requested-With", "XMLHttpRequest")
+        .add("Authorization", TOKEN_KEY)
```
Comment (stevenyomi) [inline src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt]: Add the headers only in `pageListParse()`.

File: src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt [hunk 2]
```diff
@@ -94,15 +98,22 @@ class GocTruyenTranhVui : HttpSource() {
...
-                url
-            }
+        val regexMangaId = Regex("""comic\s*=\s*\{\s*id:\s*"(\d{10})"""")
+        val matchId = regexMangaId.find(html) ?: throw Exception("Không tìm thấy mangaId") // find mangaId
+        val mangaId = matchId.groups[1]!!.value
+        val nameEn = response.request.url.toString().substringAfter("/truyen/").substringBefore("/")
+        val chapterNumber = response.request.url.toString().substringAfterLast("chuong-")
+        val body = FormBody.Builder().add("comicId", mangaId)
+            .add("chapterNumber", chapterNumber).add("nameEn", nameEn).build()
+        val request = POST("$baseUrl/api/chapter/auth", headers, body)
```
Comment (stevenyomi) [inline src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt]: Move these logic into the `if` branch below.

File: src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt [hunk 3]
```diff
@@ -135,4 +146,7 @@ class GocTruyenTranhVui : HttpSource() {
         SortByList(getSortByList()),
         GenreList(getGenreList()),
     )
+    companion object {
+        private const val TOKEN_KEY = "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBbG9uZSBGb3JldmVyIiwiY29taWNJZHMiOltdLCJyb2xlSWQiOm51bGwsImdyb3VwSWQiOm51bGwsImFkbWluIjpmYWxzZSwicmFuayI6MCwicGVybWlzc2lvbiI6W10sImlkIjoiMDAwMTA4NDQyNSIsInRlYW0iOmZhbHNlLCJpYXQiOjE3NTM2OTgyOTAsImVtYWlsIjoibnVsbCJ9.HT080LGjvzfh6XAPmdDZhf5vhnzUhXI4GU8U6tzwlnXWjgMO4VdYL1_jsSFWd-s3NBGt-OAt89XnzaQ03iqDyA"
```
Comment (stevenyomi) [inline src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt]: Move this constant below the class, into top level and remove the companion object.

Comment (dejavui) [reply src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt]: > Move this constant below the class, into top level and remove the companion object.

Is my change appropriate?

Comment (stevenyomi) [reply src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt]: I actually mean this:

```kotlin
class GocTruyenTranhVui : HttpSource() {
}

private const val TOKEN_KEY = "..." // <-- here
```

Comment (dejavui) [reply src/vi/goctruyentranhvui/src/eu/kanade/tachiyomi/extension/vi/goctruyentranhvui/GocTruyenTranhVui.kt]: > I actually mean this:
> 
> ```kotlin
> class GocTruyenTranhVui : HttpSource() {
> }
> 
> private const val TOKEN_KEY = "..." // <-- here
> ```

ok i changed it

**Review by stevenyomi — APPROVED** [review]
