### PR TITLE
Kagane: Fix multiple Issue

### LINKED ISSUE #13400: Kagane: `HTTP 400` error while browsing
### Source information

Kagane 1.4.17

### Source language

English

### Steps to reproduce

1.  Open the extension
2.  You get error 400

### Expected behavior

You should see the manga and series like normal

### Actual behavior

Image

### Mihon/Mihon fork version

Tachimanga 4.13

### Android version

iOS 26.2.1

### Other details

When searching a series, all series say “null” next to the title.  When using the extension,  webview displays the site correctly after the captcha,  but it still won’t work when refreshing in the app.

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13401: Kagane: several sources aren't listed in the filter
### Source information

Kagane 1.4.17

### Source language

English

### Steps to reproduce

1. Open Kagane extension
2. Open filter option
3. Open sources filter

### Expected behavior

All sources on the website should also be listed in the filter.

Image

### Actual behavior

The Kagane extension only displays a few sources in its list.

Image

### Mihon/Mihon fork version

Mihon 0.19.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13403: Kagane: `JsonDecodingException: Expected start of the array` error
### Source information

Kagane 1.4.17

### Source language

English

### Steps to reproduce

Anything I do produces this error:

> JsonDecodingException:` Expected start of the array '[', but had 'EOF' instead at path: $
JSON Input:

### Expected behavior

I should be able to browse and read. 

### Actual behavior

> JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
JSON Input:

I see this every time. 

### Mihon/Mihon fork version

App ID: app.komikku.beta App version: 1.13.6-10450 (f5aca44449, 78, 2026-02-05T04:28:16Z) Build version: 10450 Android version: 13 (SDK 33; build TP1A.220624.014 release-keys) Device brand: vivo Device manufacturer: vivo Device name: 2058 (2058i) Device model: V2058 WebView: Android System WebView 145.0.7632.26 Current time: 2026-02-15T17:07:37.225389+05:30

### Android version

Android 12

### Other details

[DOC-20260215-WA0003..txt](https://github.com/user-attachments/files/25323752/DOC-20260215-WA0003.txt)

Please forgive me if this is a duplicate. I'm sorry if that's the case. I did not see any other similar issue. 

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13404: Kagane: source name shows as [null]
### Source information

Kagane 1.4.17

### Source language

English

### Steps to reproduce

1. Have "Show source name" enabled in the extension settings
2. Browse latest or popular entries
3. See all the source names after the title show as [null]

### Expected behavior

The source names should show the actual source, like [Tapas] or [Tappytoon].

### Actual behavior

The source names show up as [null]

### Mihon/Mihon fork version

Yokai 1.9.7.4

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13407: Kagane: Ability to toggle whether to display "chapter_no" along with "title"
### Source name

Kagane v1.4.17

### Source language

English

### Describe your suggested feature

Currently for most series, the chapter number is duplicated (Chapter # : Chapter #) and a lot of the times wrong and ahead of the actual chapter number. Kagane usually has chapter number in the `title` field. I understand this feature can be useful in some cases but in most cases it causes issues and messes with third-party tracker sync as well. 

Image

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/).
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FumoRin**
I wanted to apologize for the issues in the last PR. I tried to fix the reported issues with the details below:

- error 400 exclude filter, Closes #13400
- source filter error 400, Closes #13400
- source filters not including all of the source (in-progress), Closes #13401
- null in source title, Closes #13404 
- alternate series caused error 404, json file error (caused by show duplicates doesn't exist anymore), Closes #13403
- Add toggle to handle chapter title parsing, Closes #13407
- Cloudflare failed bypass from reading cold start (still inconsistent) 
- populate scanlator with groups 

I hope someone will help me test this first; it's better to have different people try it

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt [hunk 1]
```diff
@@ -191,27 +191,73 @@ class ChapterDto(
...
+
+                else -> {
+                    when {
+                        chapterNo.isNullOrBlank() -> trimmedTitle
+
+                        trimmedTitle.isEmpty() -> "Chapter $chapterNo"
+
+                        trimmedTitle.matches(
+                            Regex(
+                                "^\\(S\\d+\\)\\s*(Chapter|Episode|Ch|Ep).*",
```
Comment (yuis01) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: wouldn't it be better to show chapter no. for season based content? it would be easier for trackers as well. Just my opinion.

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt [hunk 2]
```diff
@@ -191,27 +191,73 @@ class ChapterDto(
...
+                        ) -> trimmedTitle
+
+                        trimmedTitle.matches(
+                            Regex(
+                                "^(Chapter|Ch\\.|Ch|Episode|Ep\\.|Ep)\\s*\\d+.*",
+                                RegexOption.IGNORE_CASE,
+                            ),
+                        ) -> trimmedTitle
+
+                        trimmedTitle.matches(Regex("^\\d+[\\s\\-:.].*")) -> trimmedTitle
```
Comment (yuis01) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: consider using `^\\d+[\\s.].*` instead. closes #11601. couldn't find an entry where `-` and `:` would required. Feel free to correct me.

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 3]
```diff
@@ -202,7 +202,7 @@ class Kagane :
                     }
 
                     is SourcesFilter -> {
-                        filter.addToJsonObject(this, "source_id")
+                        filter.addToJsonObject(this, "")
```
Comment (D-Brox) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]:
```suggestion
                        filter.addToJsonObject(this)
```

From the network devtools:

Image

Just change the param on the `GenresFilter` class

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt
Comment (D-Brox) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]:
```suggestion
        val sources = if (!preferences.showSource) emptyMap() else cachedMetadata?.sources ?: try {
```

Comment (D-Brox) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: Idk why it's rendering incorrectly on my end, but it should be
```diff
-        val sources = try {
+        val sources = if (!preferences.showSource) emptyMap() else cachedMetadata?.sources ?: try {
```

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Filters.kt
Comment (D-Brox) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Filters.kt]:
```suggestion
    "sources_id",
```

Comment (D-Brox) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Filters.kt]: Idk why it's rendering incorrectly on my end, but it should be
```diff
-    "sources",
+    "source_id",
```

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt (hunk 1 above)
Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: I think that's the use of option `always show chapter number`. I could change the format of that to make it less distruptive, something like this 
```kotlin
"always" -> {
    when {
         chapterNo.isNullOrBlank() -> trimmedTitle
         trimmedTitle.isEmpty() -> "Chapter $chapterNo"
        else -> " ($chapterNo) $trimmedTitle"
    }
}
```

**Comment by Smol-Ame** [comment]
* Add "Closes" before the issue number in your PR description (ex: Closes #13400) to properly link the PR to the request (so it closes when reviewed, approved, and merged)
* Change this to a draft PR if it still needs more work/more testing/more changes

**Comment by FumoRin** [comment]
The source filter has some hardcoded officialSource, so I removed it and use the result from the source. Hopefully, that fixed the source filter not showing all of the sources. Also, I made the changes based on the review, and changed the show scanlations to show source type, because I can't seem to find the endpoint that needs show scanlations in the body.

**Comment by D-Brox** [comment]
`Exclude genres` from the settings still breaks the search (also http error 400)

**Comment by FumoRin** [comment]
mb, I forgot to convert the values from the `excluded genre` from settings into the uuid

**Comment by FumoRin** [comment]
I fixed the `Exclude Genres` outputting error 400, and the sort filter for `relevance` was rewritten to `updated_at`. I also added a checkbox for match all genres/tags. I hope there's no error anymore

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt (hunk 1 above)
Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: nvm there's also another edge case where after season transition the source reset the chapter number. I'll try to find a way for this case

Comment (AwkwardPeak7) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: Check webtoons.com extension, it has chapter number parsing and handles edge cases like this

**Comment by FumoRin** [comment]
I deleted the smart mode for parsing chapter titles, since it's unnecessarily complex. I'll try to figure out a way to handle the season transition and auto webtoon mode in the future when I have some time. As for now, I think there should be no more errors except for a problem with Cloudflare bypass from the cold start. Please review this, and if most of you think it's ready, I'll open the PR.

**Review by AwkwardPeak7 — APPROVED** [review]
