### PR TITLE
Bakai: Fix thumbnail url

### LINKED ISSUE #2522: covers without images
### Source information

Bakai 1.4.3

### Source language

Portuguese 

### Steps to reproduce

the manga covers are not showing

### Expected behavior

Screenshot_20240422-084352

### Actual behavior

Screenshot_20240422-084335-828

### Mihon/Tachiyomi version

0.15.2

### Android version

Android 11

### Other details

This problem isn't stopping me from reading the manga, it's just a bit annoying not knowing what I'm reading based on the manga cover

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #2522

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/bakai/src/eu/kanade/tachiyomi/extension/pt/bakai/Bakai.kt [hunk 1]
```diff
@@ -164,14 +164,23 @@ class Bakai : ParsedHttpSource() {
...
         throw UnsupportedOperationException()
     }
 
+    private fun Element.imgAttr(): String {
+        return when {
+            hasAttr("data-lazy-src") -> attr("abs:data-lazy-src")
+            hasAttr("data-src") -> attr("abs:data-src")
+            hasAttr("data-cfsrc") -> attr("abs:data-cfsrc")
+            else -> attr("abs:src")
+        }.toHttpUrl().toString()
```
Comment (AwkwardPeak7) [inline src/pt/bakai/src/eu/kanade/tachiyomi/extension/pt/bakai/Bakai.kt]: why?

Comment (choppeh) [reply src/pt/bakai/src/eu/kanade/tachiyomi/extension/pt/bakai/Bakai.kt]: ~Some images don't have a protocol (http), so they can't be loaded.~

~In the first commit, I'm checking if there is a protocol prefix and adding it if there isn't, but in the last commit, I noticed that calling toHttpUrl has the same result.~

I removed it, I was wrong.

Some manga have other attributes that contain the image url.

**Comment by vetleledaal** [comment]
Did you create the icon from the 512x512 image? It looks a bit blurry.

I cropped the 512x512 version a bit here: [ic_launcher.zip](https://github.com/user-attachments/files/16323362/ic_launcher.zip)
mipmap-xxxhdpi

**Review by AwkwardPeak7 — APPROVED** [review]
