### PR TITLE
Ken Scans: fix browse, site changing theme

### LINKED ISSUE #10592: Ken scans isn't working
### Source information

Ken scans 1.4.17

### Source language

English 

### Steps to reproduce

1, download the extention
2, open the extention after installation 

### Expected behavior

It working like normal 

### Actual behavior

The default landing page is no results found and when latest is clicked it shows a 404 error. The website still functioning on WebView though 

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Riztard**
Closes #10592

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kenscans/src/eu/kanade/tachiyomi/extension/en/kenscans/KenScans.kt [hunk 1]
```diff
@@ -1,9 +1,43 @@
...
-)
+    "https://kenscans.com",
+    "https://api.kenscans.com",
+) {
+    override fun chapterListRequest(manga: SManga): Request {
+        // Migration from old web theme to the new one(Keyoapp -> Iken)
+        if (manga.url.startsWith("/series/")) {
+            throw Exception("Migrate from $name to $name (same extension)")
+        }
+        return GET("$baseUrl/series/${manga.url}", headers)
```
Comment (vetleledaal) [inline src/en/kenscans/src/eu/kanade/tachiyomi/extension/en/kenscans/KenScans.kt]:
```suggestion
        return super.chapterListRequest(manga)
```

File: src/en/kenscans/src/eu/kanade/tachiyomi/extension/en/kenscans/KenScans.kt [hunk 2]
```diff
@@ -1,9 +1,43 @@
...
+
+        val document = response.asJsoup()
+
+        if (document.selectFirst("svg.lucide-lock") != null) {
+            throw Exception("Unlock chapter in webview")
+        }
+
+        return document.getNextJson("images").parseAs<List<PageParseDto>>().mapIndexed { idx, p ->
+            Page(idx, imageUrl = p.url)
+        }
```
Comment (vetleledaal) [inline src/en/kenscans/src/eu/kanade/tachiyomi/extension/en/kenscans/KenScans.kt]:
```suggestion
        return super.pageListParse(response)
```

File: src/en/kenscans/src/eu/kanade/tachiyomi/extension/en/kenscans/KenScans.kt (hunk 1 above)
Comment (Riztard) [reply src/en/kenscans/src/eu/kanade/tachiyomi/extension/en/kenscans/KenScans.kt]: ah right super. exist forgot about that

**Review by vetleledaal — APPROVED** [review]
