### PR TITLE
zh/BoyLove: Fix scrambled images

### LINKED ISSUE #254: BoyLove 香香腐宅: Scrambled source images now being used in new titles/chapters
### Source information

BoyLove / 香香腐宅 1.4.9

### Source language

Chinese

### Steps to reproduce

1. Install the extension
2. Find a title that **have newly updated chapters after 2024**
3. Open in the app

### Expected behavior

The image should be displayed correctly and completely
E.g (part of normal image): 
image

### Actual behavior

The image from source link now being scrambled, **for the new titles/chapters uploaded after 2024.**
On the website, it uses the script to rearrange the images after page loaded. But since the extension just grab the source image links, the app will only get the unprocessed images.

E.g (part of scrambled image):
image

### Tachiyomi version

0.15.3

### Android version

Android 14

### Other details

When inspecting the page, Some code that might be related to rearrange the image using HTML canvas were found.
<details>
<summary>Details</summary>

```js
function firstMergeImg(scrollTop) {

    var viewportData = $('#viewport0');
    var scrollTop = $(window).scrollTop();
    var itemofftop = $(viewportData).offset().top;
    var winHeight = window.innerHeight;
    var itemBottomOfftop = $(viewportData).offset().top + $(viewportData).height();
    var canvas0 = document.getElementById('viewport0');
    var ww0 = 1280;
    var hh0 = 1819;

    if (scrollTop + winHeight >= itemofftop && scrollTop <= itemBottomOfftop + 2000) {
        if ($(viewportData).hasClass('hasCanvas')) {

        } else {
            $(viewportData).addClass('hasCanvas');
            var num = 8;
            canvas0.width = ww0;
            canvas0.height = hh0;

            var context0 = canvas0.getContext("2d");
            var imgObject0 = new Image();
            do_mergeImg(context0, imgObject0, ww0, hh0, "/bookimages/path/to/source.webp?w=1280_1819", num);
            var canvasKeyW = $('#viewport0').width();
            var canvasKeyH = $('#viewport0').height();
            $('#viewport0').parents('.reader-cartoon-image').css('width', canvasKeyW);
            $('#viewport0').parents('.reader-cartoon-image').css('height', canvasKeyH);
        }

    } else {

        var context0 = canvas0.getContext("2d");
        $(viewportData).removeClass('hasCanvas');
        context0.clearRect(0, 0, ww0, hh0);

        var canvas0 = document.getElementById('viewport0');
        canvas0.width = 0;
        canvas0.height = 0;
    }
```

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #254

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt [hunk 1]
```diff
@@ -37,18 +38,21 @@ class BoyLove : HttpSource(), ConfigurableSource {
...
 
         val mirrors = MIRRORS
         val index = preferences.getString(MIRROR_PREF, "0")!!.toInt().coerceIn(0, mirrors.size - 1)
         "https://" + mirrors[index]
     }
 
-    override val client = network.cloudflareClient.newBuilder()
-        .rateLimit(2)
-        .build()
+    override val client by lazy {
```
Comment (stevenyomi) [inline src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt]: Refrain from abusing lazy when initializing is cheap, since lazy will introduce thread-safe overhead.

File: src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt [hunk 2]
```diff
@@ -111,7 +115,8 @@ class BoyLove : HttpSource(), ConfigurableSource {
 
     private fun fetchPageList(chapterUrl: String): Observable<List<Page>> =
         client.newCall(GET(baseUrl + chapterUrl, headers)).asObservableSuccess().map { response ->
-            val root = response.asJsoup().selectFirst(Evaluator.Tag("section"))!!
+            val doc = response.use { it.asJsoup() }
```
Comment (stevenyomi) [inline src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt]: No need to use, asJsoup() will close it through the ResponseBody.string() call.

File: src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt [hunk 3]
```diff
@@ -121,9 +126,31 @@ class BoyLove : HttpSource(), ConfigurableSource {
...
                     .map { it.attr("data-original").trim().toImageUrl() }
             }
-            urlList.mapIndexed { index, imageUrl -> Page(index, imageUrl = imageUrl) }
+            val parts = doc.getPartsCount()
+            urlList.mapIndexed { index, imageUrl ->
+                val url = if (parts == null) {
+                    imageUrl
+                } else {
+                    imageUrl.toHttpUrl().newBuilder()
+                        .addQueryParameter("parts", "$parts")
```
Comment (stevenyomi) [inline src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt]: Make the key a global scope constant in the descrambler file. I'd also use a longer name just in case it conflicts with source url queries.

An alternative is to use fragment/hash so you don't need to handle removing it from URL query.

File: src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/UnscramblerInterceptor.kt [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+import android.graphics.Canvas
+import android.graphics.Rect
+import okhttp3.Interceptor
+import okhttp3.MediaType.Companion.toMediaType
+import okhttp3.Response
+import okhttp3.ResponseBody.Companion.toResponseBody
+import java.io.ByteArrayOutputStream
+import java.io.InputStream
+
+object UnscramblerInterceptor : Interceptor {
```
Comment (stevenyomi) [inline src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/UnscramblerInterceptor.kt]: Make this a class instead. It's created only once anyway.

**Review by beer-psi — APPROVED** [review]
