### PR TITLE
Japscan: Fix captcha V2

### LINKED ISSUE #13288: Japscan: Timed out decrypting image links
### Source information

Japscan 1.4.56

### Source language

French 

### Steps to reproduce

Search for a Search for a  Japanese comics / manga. 
 I "Tenkuu Shinpan" 
Then solve the Cloudflare by opening webview (that works)

Image

On mihon, the problem appears for this work (Tenkuu Shinpan). 

Image

However, in some works, such as “One Piece,” the error does not occur. To see this, simply repeat the same steps but with the work in question (One Piece). 

Image

### Expected behavior

Unable to read part of the catalog for the extension in question. 

### Actual behavior

When it doesn't work :
 
Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 15

### Other details

Changing the default user agent string, deleting WebView data/cookies, or changing (enabling) DNS does not resolve the issue. 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by CriosChan**
Closes #13288

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt [hunk 1]
```diff
@@ -328,12 +335,18 @@ class Japscan :
...
+            throw Exception("Impossible de passer le captcha. Veuillez réessayer.")
         }
 
-        val pValue = Regex("""p:\s*'([^']*)'""").find(pageContent)?.groups?.get(1)?.value
-        val vValue = Regex("""v:\s*'([^']*)'""").find(pageContent)?.groups?.get(1)?.value
-        val ilValue = Regex("""il:\s*'([^']*)'""").find(pageContent)?.groups?.get(1)?.value
+        val keyValueVariableName = Regex("""\bfor\s*\(\s*var\s+i\s*=\s*0\s*;\s*i\s*<\s*([A-Za-z_$][A-Za-z0-9_$]*)\.length\s*;\s*i\+\+\s*\)\s*s\s*\+=\s*\1\[i\]\s*;""").find(pageContent)?.groups?.get(1)?.value
+        val keyArrayLineRegex = Regex("""(?m)^\s*var\s+$keyValueVariableName\s*=\s*\[.*\] *;?\s*$""")
+        val quoteRegex = Regex(""""([^"]*)"""")
+
```
Comment (vetleledaal) [inline src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt]: Move `keyValueVariableName` and `quoteRegex` to class.

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
