### PR TITLE
HentaiRead: Fix images

### LINKED ISSUE #3307: HentaiRead "Stop This image was hotlinked" issue
### Source information

HentaiRead 1.4.41

### Source language

English

### Steps to reproduce

1. Press any Manga that has the HentaiRead extension can be in the Extension Browser or own Saved Catalog (except downloaded)
2. Choose any chapter of the Manga/Doujin to read

### Expected behavior

Would be able to read said Chapter or Manga

### Actual behavior

Accessable but "Stop This image was hotlinked" in both the Saved Catalog and on the Extension search appears.

Screenshot_2024-05-30-11-18-43-94_afd66b7916d19a60815f56273408b73e

### Mihon/Tachiyomi version

Mihon 0.15.3 and used others like Tachiyomi [OG], Tachiyomi Sy and etc. for cross reference

### Android version

Android 10

### Other details

- Accessed it yesterday it was fine.
- I have accessed it via both the site and Webview both are accesible and its extension can be saved viewed and read like a normal chapter but images are all replaced by"Stop This image was hotlinked" 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Users will have to clear chapter cache, database and maybe app cache (for thumbnails)

Closes #3307 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt [hunk 1]
```diff
@@ -20,6 +21,23 @@ class Hentairead : Madara("HentaiRead", "https://hentairead.com", "en", dateForm
...
+
+    private val cdnHeaders = super.headersBuilder()
+        .add("Accept", "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8")
+        .build()
+
+    override val client = super.client.newBuilder()
+        .addInterceptor { chain ->
+            val request = chain.request()
+            val url = request.url.toString()
+            if (url.startsWith("$cdnDomain/wp-content/uploads/")) {
```
Comment (AwkwardPeak7) [inline src/en/hentairead/src/eu/kanade/tachiyomi/extension/en/hentairead/Hentairead.kt]: domain can be inlined, but is it necessary to put domain here? just checking `/wp-content/uploads/` should be fine no?

**Review by AwkwardPeak7 — APPROVED** [review]
