### PR TITLE
NineAnime: Fix page view

### LINKED ISSUE #6224: NineAnime malfunction
### Source information

NineAnime 1.4.4

### Source language

English

### Steps to reproduce

1. Browse source 
2. Pick nineanime
3. Pick any title
4. Tap read button
5. It kicked back to the title then some error appeared  

### Expected behavior

It should appear manga image so that can read

### Actual behavior

It disturbing from reading a manga

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #6224

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt [hunk 1]
```diff
@@ -160,10 +160,13 @@ class NineAnime : ParsedHttpSource() {
     // Pages
 
     override fun pageListRequest(chapter: SChapter): Request {
-        val id: String = chapter.url.substring(chapter.url.lastIndexOf("/", chapter.url.length - 2))
+        val id: String = chapter.url
+            .substring(chapter.url.lastIndexOf("/", chapter.url.length - 2))
+            .trim { it <= '/' }
```
Comment (vetleledaal) [inline src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt]:
```suggestion
            .trim('/')
```
?

Comment (dngonz) [reply src/en/nineanime/src/eu/kanade/tachiyomi/extension/en/nineanime/NineAnime.kt]: changed 😄

**Review by FourTOne5 — APPROVED** [review]

**Review by vetleledaal — APPROVED** [review]
