### PR TITLE
PeachScan: Deep linking support

### LINKED ISSUE #3130: LuraToon: Add support for deep links
### Source information

1.4.48

### Source language

Brazilian portuguese

### Steps to reproduce

The extension doesn't open direct links in the app because it doesn't have that function. It used to have it, but they removed it. I have no idea why. In contrast, the other extensions from other scans still have the direct link function. I would like the LuraToon extension to bring back this function because the scan is now providing works through private links from their own site. For us, the extension users, to access the content, we need the extension to support the direct link function like the other extensions.

### Expected behavior

I am sending this video of the behavior that the LuraToon extension should have when we click on its link.

https://github.com/keiyoushi/extensions-source/assets/28785851/148ecd42-eed8-4d1b-8fec-250a287a74ff

### Actual behavior

This is the real behavior.

https://github.com/keiyoushi/extensions-source/assets/28785851/7d06c8f9-7503-4686-b273-7ac154579aa3

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 10

### Other details

Screenshot_20240519-111921
Screenshot_20240519-111942

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #3130

I ran a few tests:
 - https://sinensistoon.com;
 - https://lura-toons.com;
 - https://nazarickscan.com.br;
 - https://dangoscan.com.br;
 - https://cerisetoon.com (Cloudflare 🥲) 
 - https://rfdragonscan.com (Cloudflare 🥲)

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/peachscan/src/eu/kanade/tachiyomi/multisrc/peachscan/PeachScan.kt [hunk 1]
```diff
@@ -82,6 +84,18 @@ abstract class PeachScan(
 
     override fun latestUpdatesNextPageSelector() = null
 
+    override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
+        if (query.startsWith(URL_SEARCH_PREFIX)) {
+            val manga = SManga.create().apply { url = "/${query.substringAfter(URL_SEARCH_PREFIX)}" }
```
Comment (AwkwardPeak7) [inline lib-multisrc/peachscan/src/eu/kanade/tachiyomi/multisrc/peachscan/PeachScan.kt]:
```suggestion
            val manga = SManga.create().apply { url = "/${query.substringAfter(URL_SEARCH_PREFIX)}/" }
```
avoid 302 redirect

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/peachscan/src/eu/kanade/tachiyomi/multisrc/peachscan/PeachScan.kt (hunk 1 above)
Comment (choppeh) [reply lib-multisrc/peachscan/src/eu/kanade/tachiyomi/multisrc/peachscan/PeachScan.kt]: I noticed that too, I think it was removed in a refactoring 😅

**Review by AwkwardPeak7 — APPROVED** [review]
