### PR TITLE
Bloom Scans: Fix search results

### LINKED ISSUE #15191: Bloomscans not loading chapter error 403/429
### Source information

Bloomscans 1.4. 31

### Source language

Spanish 

### Steps to reproduce

When trying to read a chapter, it gives an error.

Image
Image

### Expected behavior

You should watch the chapters

### Actual behavior

It gives a display error

Image
Image

### Mihon/Mihon fork version

0.19.9

### Android version

Android 11

### Other details

The webpage is displayed in the webview.

Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Smol-Ame**
* Co-authored by Darksider, updated searchMangaRequest URL builder to match site's current path
* Co-authored by Darksider, override `pageListParse` to handle 403/site verification check on chapter page.
* Tested and works as of this edit, any other issues currently is the source's server/website skill issues currently

#### Important:
* Used Google Gemini to if/else when searching with filters (source's search page is still borked, unable to test), please check the relevant commit carefully.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/bloomscans/src/eu/kanade/tachiyomi/extension/es/bloomscans/Bloomscans.kt [hunk 1]
```diff
@@ -12,6 +17,74 @@ class Bloomscans :
...
+        val url = baseUrl.toHttpUrl().newBuilder()
+
+        // Text Search
+        if (query.isNotEmpty() && filters.isEmpty()) {
+            url.addPathSegment("page")
+            url.addPathSegment(page.toString())
+            url.addQueryParameter("s", query)
+        } else {
+            // Filtered Search
+            url.addPathSegment(mangaUrlDirectory.substring(1))
```
Comment (AwkwardPeak7) [inline src/es/bloomscans/src/eu/kanade/tachiyomi/extension/es/bloomscans/Bloomscans.kt]: this is the same as the multisrc? only build custom url for query search, and deleagte to `super.searchMangaRequest` for filters

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/es/bloomscans/src/eu/kanade/tachiyomi/extension/es/bloomscans/Bloomscans.kt (hunk 1 above)
Comment (al-shamiry) [reply src/es/bloomscans/src/eu/kanade/tachiyomi/extension/es/bloomscans/Bloomscans.kt]: @Smol-Ame you can do something like:

```kt
override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
  if (query.isNotEmpty() && filters.isEmpty()) {
    val url = baseUrl.toHttpUrl().newBuilder()
      .addPathSegment("page")
      .addPathSegment(page.toString())
      .addQueryParameter("s", query)
      .addPathSegment("")
    return GET(url.build(), headers)
  }
  return super.searchMangaRequest(page, query, filters)
}
```

**Review by AwkwardPeak7 — APPROVED** [review]
