### PR TITLE
Japscan: Fix captcha

### LINKED ISSUE #14412: Japscan: `Impossible de récupérer les values clés` error
### Source information

Japscan 1.4.58

### Source language

French

### Steps to reproduce

Searching for Japanese manga/comics.

I'm looking for "One Piece" and others.

Then resolve the Cloudflare issue by opening the web view (with the new version, it resolves itself).

Then error appears "Unable to retrieve key values". 

### Expected behavior

It is impossible to read the entire catalog of the extension in question.

Image

### Actual behavior

Image

### Mihon/Mihon fork version

0.19.7

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by CriosChan**
Closes #14412
Uses the user's webview to solve the CAPTCHA. Does not close automatically after solving it.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by LightEZu** [comment]
it's still not working i have the same problem.

**Comment by CriosChan** [comment]
Dude, I just tested it again and I'm not having any issues. I hope that if you're commenting, it's because you used the PR APK? Also, saying “it doesn't work” doesn't help me at all—at least tell me your Mihon version / the name of your fork, and what error you're getting.

And if you didn't use the APK from the link above, then wait until it's merged and available to everyone, and be patient.

**Comment by Smol-Ame** [comment]
@LightEZu if you don't understand the process, don't unnecessarily comment if you don't have any useful information for contributors.

This PR (proposed change) is still open pending review & approval before it's merged into the repo, which then gives an extension update. If you don't know how to test this PR yourself, then wait patiently & quietly for the extension to get an update.

**Comment by LightEZu** [comment]
> Dude, I just tested it again and I'm not having any issues. I hope that if you're commenting, it's because you used the PR APK? Also, saying “it doesn't work” doesn't help me at all—at least tell me your Mihon version / the name of your fork, and what error you're getting.
> 
> And if you didn't use the APK from the link above, then wait until it's merged and available to everyone, and be patient.

I'm sorry, I didn't mean to sound condescending or rude—I just wanted to say that it wasn't working for me. Sorry again.

**Comment by LightEZu** [comment]
I compiled the APK with Android Studio and it's working!! Thank you very much, and sorry again for what happened earlier.

**Comment by CriosChan** [comment]
Ready for review !

File: src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt [hunk 1]
```diff
@@ -287,71 +285,63 @@ class Japscan :
...
-                val multipartBody = MultipartBody.Builder()
-                    .setType(MultipartBody.FORM)
-                    .addFormDataPart("token", token)
-                    .addFormDataPart("answer", answer.toJsonString())
-
-                val captchaRequest = client.newCall(POST("$internalBaseUrl/validate-captcha/", body = multipartBody.build(), headers = headers.newBuilder().add("Referer", "$internalBaseUrl${chapter.url}").build())).execute()
-                if (captchaRequest.body.string().contains("\"success\": true")) {
-                    request = client.newCall(GET("$internalBaseUrl${chapter.url}")).execute()
-                    pageContent = request.body.string()
+        var request: Response = client.newCall(GET("$internalBaseUrl${chapter.url}")).execute()
```
Comment (vetleledaal) [inline src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt]: Missing `headers`?
```suggestion
        var request: Response = client.newCall(GET("$internalBaseUrl${chapter.url}", headers)).execute()
```

File: src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt [hunk 2]
```diff
@@ -287,71 +285,63 @@ class Japscan :
...
+
+                context.startActivity(intent)
+            } catch (e: Exception) {
+                // Suwayomi etc.
+                throw Exception("Résolvez le captcha de ce chapitre depuis la WebView et réouvrez le chapitre.")
+            }
+            var captchaWait = 0
+            while (captchaWait != 15) {
+                Thread.sleep(5000)
+                request = client.newCall(GET("$internalBaseUrl${chapter.url}")).execute()
```
Comment (vetleledaal) [inline src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt]: Same here-
```suggestion
                request = client.newCall(GET("$internalBaseUrl${chapter.url}", headers)).execute()
```

File: src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt [hunk 3]
```diff
@@ -287,71 +285,63 @@ class Japscan :
...
+                    putExtra("title_key", "Résolvez le captcha, fermez la Webview et réouvrez le chapitre.")
+                }
+
+                context.startActivity(intent)
+            } catch (e: Exception) {
+                // Suwayomi etc.
+                throw Exception("Résolvez le captcha de ce chapitre depuis la WebView et réouvrez le chapitre.")
+            }
+            var captchaWait = 0
+            while (captchaWait != 15) {
```
Comment (vetleledaal) [inline src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt]: This is easy to mess up in the off-by-one sense. Prefer:
```suggestion
            while (captchaWait <= 15) {
```

Maybe revisit the other comparsion against `captchaWait` too.

**Review by vetleledaal — APPROVED** [review]
