### PR TITLE
Manhwaxxl: Fix source

### LINKED ISSUE #3579: Manhwa XXL: No results found
### Source information

Manhwa XXL 1.4.2

### Source language

English 

### Steps to reproduce

1. Open Tachiyomi SY 
2. Head to browse and select said source 

### Expected behavior

You should see the list of available manhwa

### Actual behavior

After clicking on the source it just says "no results found."

### Mihon/Tachiyomi version

Tachiyomi SY preview r561

### Android version

Android 14

### Other details

Manhwa xxl works fine in WebView 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dngonz**
Closes #3579

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/manhwaxxl/src/eu/kanade/tachiyomi/extension/en/manhwaxxl/ManhwaXXL.kt [hunk 1]
```diff
@@ -133,12 +155,12 @@ class ManhwaXXL : ParsedHttpSource() {
...
-    private class GenreFilter(val genres: Array<Genre>) : Filter.Select<String>("Genre", genres.map { it.id }.toTypedArray())
+    private class GenreFilter(val genres: Array<Genre>) :
+        Filter.Select<String>("Genre", genres.map { it.name }.toTypedArray())
 
-    // https://manhwaxxl.com/genres
-    // copy([...document.querySelectorAll("section#page ul li a:not([class])")].map((e) => `Genre("${e.textContent.trim()}", "${e.href.split("/").slice(-1)[0].replace(/#page$/u, "")}"),`).join("\n"))
+    // If you want to add new genres just add the name and id.
+    // You can search more here: https://hentaitnt.net/genres
     private fun getGenreList() = arrayOf(
-        Genre("All", ""),
```
Comment (AwkwardPeak7) [inline src/en/manhwaxxl/src/eu/kanade/tachiyomi/extension/en/manhwaxxl/ManhwaXXL.kt:141]: should keep to not always select action filter, as app defaults to 0 index

File: src/en/manhwaxxl/src/eu/kanade/tachiyomi/extension/en/manhwaxxl/ManhwaXXL.kt [hunk 2]
```diff
@@ -85,42 +90,59 @@ class ManhwaXXL : ParsedHttpSource() {
...
 
     // Manga details page have paginated chapter list. We sacrifice `date_upload`
     // but we save a bunch of calls, since each page is like 12 chapters.
     override fun chapterListParse(response: Response): List<SChapter> {
         val detailsDocument = response.asJsoup()
-        val firstChapter = detailsDocument.selectFirst("ul.chapters-list li.item-chapter a")?.absUrl("href")
-            ?: return emptyList()
-        val document = client.newCall(GET(firstChapter, headers)).execute().asJsoup()
+        val script = detailsDocument.selectFirst("script:containsData(post_id)")?.data()
+            ?: throw java.lang.Exception("Failed to get chapter id")
```
Comment (AwkwardPeak7) [inline src/en/manhwaxxl/src/eu/kanade/tachiyomi/extension/en/manhwaxxl/ManhwaXXL.kt]: import

Comment (dngonz) [reply src/en/manhwaxxl/src/eu/kanade/tachiyomi/extension/en/manhwaxxl/ManhwaXXL.kt]: Sorry @AwkwardPeak7 didn't know what you mean by import

Comment (vetleledaal) [reply src/en/manhwaxxl/src/eu/kanade/tachiyomi/extension/en/manhwaxxl/ManhwaXXL.kt]: `import java.lang.Exception` at the top so the code here can be:
```suggestion
            ?: throw Exception("Failed to get chapter id")
```

**Review by AwkwardPeak7 — APPROVED** [review]
