### PR TITLE
Fix mangaswat

### LINKED ISSUE #11798: MangaSwat: Use homepage Latest instead of API search for Latest updates
### Source name

Manga swat

### Source language

Arabic 

### Other details

The extension "Mangaswat" does not show the latest chapters for any work that has been updated in the wepsite and only show manhwa's that are chapters date are from 2019 

### Acknowledgements

- [x] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a meaningful title with the source name.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by xMohnad**
Close #11798 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Smol-Ame** [comment]
From #11719's discussion:

> ... if you go to it, you'll see that the website is still using "appswat.com" for the API calls, so I think it's best to leave it as that. It re-directs to the right URL...

Is the URL change in your PR really needed?

**Comment by xMohnad** [comment]
> Is the URL change in your PR really needed?

I changed it as a precaution, but I will revert it. If it stops working in the future, it can be updated then.

File: src/ar/mangaswat/src/eu/kanade/tachiyomi/extension/ar/mangaswat/MangaSwat.kt [hunk 1]
```diff
@@ -46,6 +46,7 @@ class MangaSwat :
             .add("Accept", "application/json, text/plain, */*")
             .add("Origin", baseUrl)
             .add("Referer", "$baseUrl/")
+            .set("User-Agent", "ktor-client")
```
Comment (AwkwardPeak7) [inline src/ar/mangaswat/src/eu/kanade/tachiyomi/extension/ar/mangaswat/MangaSwat.kt:49]: they can very easily block this

**Review by AwkwardPeak7 — APPROVED** [review]
