### PR TITLE
Anchira: Fix API changes

### LINKED ISSUE #3079: Anchira Bugged
### Source information

Anchira 1.4.13

### Source language

English

### Steps to reproduce

1. Click on read chapter
2. Kicked out with reminders at the bottom

### Expected behavior

Opens normally and readable

### Actual behavior

IMG_20240517_145241

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by LetrixZ**
Closes #3079

---

Also added an interceptor for when it fails to load a resampled image, added the new CDN url for odd numbered pages and changed the data JSON url.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by LetrixZ** [comment]
I will also take the chance to add the interceptor for images that don't have a resampled option.

Also, there is a new CDN that is used for odd page numbers.

File: src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt [hunk 1]
```diff
@@ -64,7 +65,9 @@ class Anchira : HttpSource(), ConfigurableSource {
         Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
     }
 
-    override fun headersBuilder() = super.headersBuilder().add("X-Requested-With", "XMLHttpRequest")
+    override fun headersBuilder() = super.headersBuilder()
+        .add("Referer", "https://anchira.to/")
+        .add("Origin", "https://anchira.to")
```
Comment (AwkwardPeak7) [inline src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt]: use `baseUrl`

File: src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt [hunk 2]
```diff
@@ -43,7 +44,7 @@ class Anchira : HttpSource(), ConfigurableSource {
 
     override val baseUrl = "https://anchira.to"
 
-    private val apiUrl = "$baseUrl/api/v1"
+    private val apiUrl = "https://api.anchira.to"
```
Comment (AwkwardPeak7) [inline src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt]:
```suggestion
    private val apiUrl = baseUrl.replace("://", "://api.")
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt (hunk 1 above)
Comment (AwkwardPeak7) [inline src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/Anchira.kt]:
```suggestion
        .add("Referer", "$baseUrl/")
        .add("Origin", baseUrl)
```

**Review by AwkwardPeak7 — APPROVED** [review]
