### PR TITLE
SamuraiScan: Fix 404 Error

### LINKED ISSUE #6643: SamuraiScan HTTP 404 Error
### Source information

"SamuraiScan 1.4.47

### Source language

Espanol

### Steps to reproduce

1. Open extension.
2. 404 error page appear
3. Open webview it works as expected.

### Expected behavior

User should be able to see the latest comics on homepage.

### Actual behavior

HTTP 404 error occurs.

### Mihon/Tachiyomi version

Mihon --> 0.17.1

### Android version

Android 14

### Other details

PFA screenshots for your reference.
Screenshot_20241217_034606
Screenshot_20241217_034719

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #6643 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/manhuaonline/src/eu/kanade/tachiyomi/extension/es/manhuaonline/SamuraiScan.kt [hunk 1]
```diff
@@ -17,7 +17,7 @@ class SamuraiScan : Madara(
     override val useLoadMoreRequest = LoadMoreStrategy.Never
     override val useNewChapterEndpoint = true
 
-    override val mangaSubString = "read"
+    override val mangaSubString = "leer"
```
Comment (vetleledaal) [inline src/es/manhuaonline/src/eu/kanade/tachiyomi/extension/es/manhuaonline/SamuraiScan.kt]: Would using `rd` be more correct? It would avoid a redirect in `fetchSearchManga()`

Comment (dngonz) [reply src/es/manhuaonline/src/eu/kanade/tachiyomi/extension/es/manhuaonline/SamuraiScan.kt]: Yes actually, already changed

**Review by vetleledaal — APPROVED** [review]
