### PR TITLE
Baozimhorg: handle new api

### LINKED ISSUE #5386: GoDa manga error
### Source information

GoDa 1.4.31

### Source language

Chinese 

### Steps to reproduce

https://github.com/user-attachments/assets/d9795a8b-eec8-4101-873e-05c69ed3ef64

### Expected behavior

It should work fine as the second one

### Actual behavior

Some chapters, specially the newest one shows error when I click the chapter

### Mihon/Tachiyomi version

0.16.X

### Android version

Android 13

### Other details

Log 10-06 17:31
[komikku_crash_logs.txt](https://github.com/user-attachments/files/17268795/komikku_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by oalieno**
Closes #5386.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/Dto.kt [hunk 1]
```diff
@@ -53,9 +53,12 @@ private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale
...
-class PageListInfoDto(val images: List<ImageDto>)
+class PageListInfoDto(val images: PageListInfoImagesDto)
+
+@Serializable
+class PageListInfoImagesDto(val images: List<ImageDto>)
 
 @Serializable
 class ImageDto(private val url: String, private val order: Int) {
-    fun toPage() = Page(order, imageUrl = url)
+    fun toPage() = Page(order, imageUrl = "https://f40-1-4.g-mh.online$url")
```
Comment (AwkwardPeak7) [inline src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/Dto.kt:63]: ~is the url constant? or can be fetched from somewhere~ well it can be updated again if ever broken...

**Review by AwkwardPeak7 — APPROVED** [review]
