### PR TITLE
RizzComic: handle edge case for slugs

### LINKED ISSUE #8611: Rizz Fables: Error 403 on specific series
### Source information

Rizz Comic, v1.4.41

### Source language

English

### Steps to reproduce

- Open the series "I'm a Mom"
or
"If I Don't Die Soon, I'll Really Become Invincible!"

- Observe the error.

### Expected behavior

The chapter list should load as usual.

### Actual behavior

Opening the above series throws a 403 error, and the chapter list fails to load.

Other series* load fine without issues.

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15

### Other details

I checked in WebView and noticed that the correct slug isn't being used for them.
It's currently opening:
https://rizzfables.com/series/i-m-a-mom

But it should be:
https://rizzfables.com/series/r2311170-i-m-a-mom

Same issue occurs with:
https://rizzfables.com/series/r2311170-if-i-don-t-die-soon-ill-really-become-invincible-

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes #8611

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RizzComic.kt [hunk 1]
```diff
@@ -110,14 +110,17 @@ class RizzComic : MangaThemesiaAlt(
...
             .replace(slugRegex, "-")
             .replace("-s-", "s-")
             .replace("-ll-", "ll-")
+            .replace(slugCleanupRegex, "")
 
         val genreIds get() = genres?.split(",")?.map(String::trim)
 
         companion object {
             private val slugRegex = Regex("""[^a-z0-9]+""")
+            private val slugCleanupRegex = Regex("""^-+|-+$""")
```
Comment (vetleledaal) [inline src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RizzComic.kt]: Trim instead? You can set a custom char https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.text/trim.html

**Review by vetleledaal — APPROVED** [review]
