### PR TITLE
Mediocretoons: update for new site

### LINKED ISSUE #9337: Medíocre Toons: `HTTP 404` error
### Source information

Medíocre Toons 1.4.4

### Source language

Português (Brasil)

### Steps to reproduce

Está dando erro 404 ao tentar abrir um capítulo, no site está normal

https://github.com/user-attachments/assets/f3f3fdad-ed10-49ea-9f0b-73be6f4f76f5

### Expected behavior

Carregar os capítulos normalmente sem ficar dando erro

### Actual behavior

Está dando o Erro 404

### Mihon/Tachiyomi version

Komikku 1.13.1

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11566: Mediocre Toons: Add mirror URL (`.site`)
### Source name

Medíocre toons 

### Source link

https://mediocretoons.site/

### Source language

Português Brasil

### Other details

A new extension for this mediocre website would be good, since the old one continues to have the HTTP 403 problem. 

### Acknowledgements

- [x] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a meaningful title with the source name.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
Closes: #9337
Closes: #11566

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

https://github.com/user-attachments/assets/5a3c7f91-4f52-4172-aa00-e2c541ed6d10

https://github.com/user-attachments/assets/994ebdfa-5a1d-4cea-b083-01dd997c38bc

### CODE REVIEW

**Comment by Smol-Ame** [comment]
"Closes #9337" to properly link the PR to the issue request

**Comment by FelipeGFA** [comment]
> "Closes #9337" to properly link the PR to the issue request

done.

**Comment by choppeh** [comment]
This source is not multi-src, move the code to the mediocretoons package

**Comment by FelipeGFA** [comment]
> This source is not multi-src, move the code to the mediocretoons package

mb, just changed that

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt [hunk 1]
```diff
@@ -1,19 +1,285 @@
...
+        .set("x-app-key", "toons-mediocre-app")
+
+    // ============================== Popular ================================
+    override fun popularMangaRequest(page: Int) =
+        GET("$apiUrl/obras?ordenarPor=views_hoje&limite=20", headers)
+
+    override fun popularMangaParse(response: Response): MangasPage {
+        val dto = response.parseAs<MediocreListDto<List<MediocreMangaDto>>>()
+        val mangas = dto.data.map { it.toSManga() }
+        val hasNext = dto.pagination?.hasNextPage ?: false
```
Comment (choppeh) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt:53]: Are there any subsequent pages? PopularMangaRequest does not have any defined pages.

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt [hunk 2]
```diff
@@ -1,19 +1,285 @@
...
+        return MangasPage(mangas, hasNextPage = hasNext)
```
Comment (choppeh) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt:54]: If there are no next pages in popular manga
```suggestion
        return MangasPage(mangas, hasNextPage = false)
```

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+    } ?: SManga.UNKNOWN
+    return sManga
+}
+
+fun MediocreChapterSimpleDto.toSChapter(): SChapter {
+    return SChapter.create().apply {
+        name = nome
+        chapter_number = numero ?: 0f
+        url = "/capitulo/$id"
+        date_upload = criado_em?.let { MediocreToonsDateParser.parse(it) } ?: 0
```
Comment (choppeh) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt]: Use the tryParse (```import keiyoushi.utils.tryParse``` )

```suggestion
        date_upload = dateFormat.tryParse(criado_em)
```

File: src/pt/mediocretoons/build.gradle [hunk 4]
```diff
@@ -1,9 +1,8 @@
 ext {
     extName = 'Mediocre Toons'
     extClass = '.MediocreToons'
-    themePkg = 'greenshit'
     baseUrl = 'https://mediocretoons.com'
-    overrideVersionCode = 0
+    extVersionCode = 10
```
Comment (choppeh) [inline src/pt/mediocretoons/build.gradle]: The current version is 6
https://github.com/keiyoushi/extensions/blob/82b79ee4509c57a24772966c3ef706433c3536d9/index.json#L23768
```suggestion
    extVersionCode = 7
```

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt [hunk 5]
```diff
@@ -0,0 +1,143 @@
...
+    }
+    descricao?.let { Jsoup.parseBodyFragment(it).let { sManga.description = it.text() } }
+    sManga.status = status?.let {
+        when (it.nome.lowercase()) {
+            "em andamento" -> SManga.ONGOING
+            "completo" -> SManga.COMPLETED
+            "hiato" -> SManga.ON_HIATUS
+            else -> SManga.UNKNOWN
+        }
+    } ?: SManga.UNKNOWN
```
Comment (choppeh) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt]:
```suggestion
    status?.let {
        sManga.status = when (it.nome.lowercase()) {
            "em andamento" -> SManga.ONGOING
            "completo" -> SManga.COMPLETED
            "hiato" -> SManga.ON_HIATUS
            else -> SManga.UNKNOWN
        }
    }
```

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt [hunk 6]
```diff
@@ -0,0 +1,143 @@
...
+    val tem_paginas: Boolean = false,
+    val totallinks: Int = 0,
+    val lido: Boolean = false,
+    val views: Int = 0,
+)
+
+@Serializable
+data class MediocreMangaDto(
+    val id: Int = 0,
+    val nome: String = "",
```
Comment (choppeh) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt]: You can use the ```@SerialName``` to keep the fields in English.

```suggestion
   @SerialName("nome")
    val name: String = "",
```

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt [hunk 7]
```diff
@@ -1,19 +1,285 @@
...
+
+    override fun imageUrlRequest(page: Page): Request {
+        val imageHeaders = headers.newBuilder()
+            .add("Referer", "$baseUrl/")
+            .build()
+        return GET(page.url, imageHeaders)
+    }
+
+    // ============================= Interceptors ============================
+    private fun imageLocation(chain: Interceptor.Chain): Response {
```
Comment (choppeh) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt]: I don't think this feature is necessary. I added this function to GreenShit because the source had more than one path for the images.

```suggestion
```

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt (hunk 1 above)
Comment (FelipeGFA) [reply src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt:53]: yes, it has.

gonna add it:

```
override fun popularMangaRequest(page: Int): Request {
        val url = "$apiUrl/obras".toHttpUrl().newBuilder()
            .addQueryParameter("ordenarPor", "views_hoje")
            .addQueryParameter("limite", "20")
            .addQueryParameter("pagina", page.toString())
            .build()
        return GET(url, headers)
    }
```

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt (hunk 7 above)
Comment (FelipeGFA) [reply src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt]: removing interceptors

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt (hunk 6 above)
Comment (FelipeGFA) [reply src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt]: adding @SerialName

File: .gitignore
Comment (AwkwardPeak7) [inline .gitignore:1]: revert

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by BlackMember08** [comment]
Meu amigo bom dia. Você poderia consertar a extensão manga livre e remangas

**Review by AwkwardPeak7 — APPROVED** [review]
