### PR TITLE
LectorTmo: Fix images not loading

### LINKED ISSUE #5002: TuMangaOnline/LectorManga don't show any chapter
### Source information

TuMangaOnline/LectorManga

### Source language

Spanish

### Steps to reproduce

1.Any Manga
2.Any Chapter
3. Show the same error
4. Webview is okay
Screenshot_2024-09-10-18-09-39-470_app mihon
Screenshot_2024-09-10-18-10-40-006_app mihon

5.But Chapter has error, in navigation with browser. The Chapter URL is random domain
Screenshot_2024-09-10-18-13-42-981_org mozilla firefox

### Expected behavior

Keep navigation on random domain 

### Actual behavior

Keep navigation in frist domain and don't read Chapter in right page

### Mihon/Tachiyomi version

0.16.5

### Android version

12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #5002

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/lectortmo/src/eu/kanade/tachiyomi/extension/es/lectortmo/LectorTmo.kt [hunk 1]
```diff
@@ -108,7 +104,7 @@ abstract class LectorTmo(
             .addInterceptor { chain ->
                 val request = chain.request()
                 val url = request.url
-                if (url.host.contains("japanreader.com")) {
+                if (url.toString().endsWith("#imagereq")) {
```
Comment (vetleledaal) [inline src/es/lectortmo/src/eu/kanade/tachiyomi/extension/es/lectortmo/LectorTmo.kt]:
```suggestion
                if (url.fragment == imagereq") {
```
(needs testing)

**Comment by Smol-Ame** [comment]
Link #5002 when possible :umarucool:

**Review by AwkwardPeak7 — APPROVED** [review]
