### PR TITLE
Lunar Manga (Multi): Fix decryption

### LINKED ISSUE #14543: Lunar Manga No Page Found Issue
### Source information

Lunar Manga 1.4.4

### Source language

All

### Steps to reproduce

Open chapter No Pages Found

Image

### Expected behavior

Chapter No Pages Found 

### Actual behavior

Fix chapter No Pages Found

### Mihon/Mihon fork version

Mihon 0.19.7

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by disk-iq8**
Closes #14543

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/lunaranime/src/eu/kanade/tachiyomi/extension/all/lunaranime/LunarDecryptor.kt [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+        val url = "$apiUrl/api/manga/r/$token?lang=$lang"
+        val response = client.newCall(GET(url)).execute()
+        if (!response.isSuccessful) error("Failed decrypting with ${response.code} while fetching session_data")
+        val res = response.parseAs<LunarPageListResponse>()
+        return res.data?.sessionData ?: error("session_data is empty")
+    }
+
+    private val nextFPushRegex = Regex("""self\.__next_f\.push\(\[1,"(.*?)"\]\)""", RegexOption.DOT_MATCHES_ALL)
+    private val dictRegex = Regex("""\{[^{}]*\}""")
+    fun Response.extractSeeds(): List<Map<String, String>> {
```
Comment (AwkwardPeak7) [inline src/all/lunaranime/src/eu/kanade/tachiyomi/extension/all/lunaranime/LunarDecryptor.kt:51]: `keiyoushi.utils.extractNextJs` doesn't work for this?

Comment (disk-iq8) [reply src/all/lunaranime/src/eu/kanade/tachiyomi/extension/all/lunaranime/LunarDecryptor.kt:51]: welp, we need two length based matches for the two char key, seems messier to call it twice then get the one that isn't the first one on second time, tho extractAppRouterPayloads could work I think, if it was accessible

unless there is another usage I'm missing for the extract one

Comment (disk-iq8) [reply src/all/lunaranime/src/eu/kanade/tachiyomi/extension/all/lunaranime/LunarDecryptor.kt:51]: the 'oe' and 'ew' (dynamic) in $L6 and $L7 is what we need in https://pastebin.com/raw/8wUS9pVh

**Review by AwkwardPeak7 — APPROVED** [review]
