### PR TITLE
Mangago: fix url template & _ domain failing at SNI

### LINKED ISSUE #5441: Mangago: `Android internal error`
### Source information

Mangago 1.4.20

### Source language

English

### Steps to reproduce

1. Download a manga chapter (looks like this happens only in specific ones though)
2. Wait for error to appear

### Expected behavior

The chapter should be downloaded without a problem

### Actual behavior

It gives out this error 
Screenshot_20241008_150442_Komikku

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #13498: Mangago: `getChapterImageUrls failed`, `The image couldn't be loaded` error
### Source information

Mangago 1.4.27

### Source language

English

### Steps to reproduce

1. Open some manga to read.
2. Some of them only load a few first pages.
3. The rest of the pages failed to load.
4. The pages are all available when open on browser.

Image

Image

### Expected behavior

The app should be able to load all pages.

### Actual behavior

The app couldn't load the pages of some manga/manhwa but the page are all available when open in browser.

### Mihon/Mihon fork version

Yōkai 1.9.7.4 / Mihon 0.19.3

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes #13498
closes #5441

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt [hunk 1]
```diff
@@ -322,6 +301,48 @@ class Mangago :
...
 
+    private fun mergeUrlWithTemplate(url: String, template: String): String {
+        val urlSegments = url.trim('/').split("/")
+        val templateSegments = template.trim('/').split("/")
+
+        // Convert a template segment pattern to a regex (replace {placeholder} with .+)
+        fun templateSegmentMatches(templateSeg: String, urlSeg: String): Boolean {
+            val regex = templateSeg.replace(Regex("""\{[^}]+\}"""), ".+")
+            return urlSeg.matches(Regex(regex))
+        }
```
Comment (vetleledaal) [inline src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt]: Consider moving this function out of `mergeUrlWithTemplate`. I don't have any other suggestions than that you should use `HttpUrl`, but I guess you already considered that.

**Review by vetleledaal — DISMISSED** [review]

**Comment by jeonshaniz** [comment]
hi, i don’t know about programming and coding that much. Can you tell me what do i do with this code?

**Comment by tallyhawley** [comment]
is there a reason this hasnt been merged despite being approved 11d ago? this is becoming an increasingly common issue lol

**Comment by AwkwardPeak7** [comment]
Mangago serves different html in different regions. This pr fixes it for the broken version but breaks the region which is working currently.

**Comment by tallyhawley** [comment]
is it not possible to make this backwards compatible? e.g. split implementations per region or even just. a try/catch?

**Comment by AwkwardPeak7** [comment]
Can't do that without the actual response they serve in said region.

**Comment by tallyhawley** [comment]
out of curiosity, what regions are you referring to?

**Comment by tallyhawley** [comment]
i dont really understand why this can't be fixed -- this issue has been occurring on every chapter i've seen uploaded in the last 4-5 days, regardless of my IP location. (previously was only happening when using mobile useragent).

if this change would fix region A but break region B, just fall back to the old implementation if the new one throws? i feel like that is a solvable issue.

**Comment by AwkwardPeak7** [comment]
I never said it can't be fixed. this impl didn't work for another person for whom current version works, so I marked it as draft. I then didn't get time to work on this again. 

> out of curiosity, what regions are you referring to?

NA
