### PR TITLE
EZmanhwa: new lib-multisrc for QiScans and EZmanga

### LINKED ISSUE #14442: Qi Scans: `HTTP 404`, `MissingFieldException` error
### Source information

Qi Scans 1.4.23

### Source language

English 

### Steps to reproduce

1. Go to browse in mihon
2.  in Sources tab click on Qi Scans(1st one in the image)

Image

### Expected behavior

Should be able to see, click on the title and read its chapters normally.

### Actual behavior

404 error pops up, unable to find anything. 

Image

### Mihon/Mihon fork version

Mihon 0.19.7

### Android version

Android 13

### Other details

The webview works and leads to Qi Manhwa(probably a name changing)

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #14448: EZmanga: `HTTP 404`, `Field 'post' is required` error
### Source information

EZmanga 1.4.59

### Source language

English

### Steps to reproduce

1. Click into the extension
2. No results show up for latest/browse
3. Clicking on popular or latest will give you a 404 and tell you to check WebView
4. WebView works fine
5. When updating, the error it gives is: ! Field 'post' is required for type with serial name 'eu.kanade.tachiyomi.multisrc.iken.Post', but it was missing at path: $

Image

Image

Image

Image

### Expected behavior

I should be able to browse through the extension and update the entries I currently have.

### Actual behavior

No results show up when browsing, error 404 is shown when looking at the popular and latest tags, but WebView is completely fine.
As a note, when updating it manually, it first gives off a NullPointerException: null error before giving the ! Field 'post' is required for type with serial name 'eu.kanade.tachiyomi.multisrc.iken.Post', but it was missing at path: $ error. The global update only shows the latter error.

### Mihon/Mihon fork version

TachiyomiSY 1.12.0

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14448, Closes #14442

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by darwin-256** [comment]
i have not tested if migration for manga entries from old version to new will work

**Comment by AaronDeimos** [comment]
> Closes #14448 #14442

This won’t close both issues.
Use: `Closes #14448, Closes #14442`

File: lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+    override val name: String,
+    override val baseUrl: String,
+    final override val lang: String = "en",
+) : HttpSource() {
+
+    /** Full API base, e.g. "https://vapi.ezmanga.org/api/v1" */
+    abstract val apiUrl: String
+
+    /** Requests per second. Override per-source if needed. */
+    open val rateLimitPermits: Int = 3
```
Comment (AwkwardPeak7) [inline lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt]: no need

File: lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+
+    override val supportsLatest = true
+
+    // by lazy defers initialization until first access, ensuring subclass
+    // property overrides (e.g. rateLimitPermits) are set before use.
+    override val client by lazy {
+        network.cloudflareClient.newBuilder()
+            .rateLimit(rateLimitPermits)
+            .build()
+    }
```
Comment (AwkwardPeak7) [inline lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt]: no need

File: lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+import okhttp3.Response
+
+abstract class EZManhwa(
+    override val name: String,
+    override val baseUrl: String,
+    final override val lang: String = "en",
+) : HttpSource() {
+
+    /** Full API base, e.g. "https://vapi.ezmanga.org/api/v1" */
+    abstract val apiUrl: String
```
Comment (AwkwardPeak7) [inline lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt]: consider adding to constructor

File: lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwaDto.kt [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+            if (it % 1.0 == 0.0) it.toInt().toString() else it.toString()
+        } ?: ""
+        val chapterTitle = title?.takeIf { it.isNotBlank() } ?: "Chapter $numStr".trim()
+        name = prefix + chapterTitle
+        chapter_number = number?.toFloat() ?: -1f
+        date_upload = try {
+            createdAt?.let { EZMANHWA_DATE_FORMAT.parse(it)?.time } ?: 0L
+        } catch (e: Exception) {
+            0L
+        }
```
Comment (AwkwardPeak7) [inline lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwaDto.kt]: use `keiyoushi.utils.tryParse` for date

File: lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt [hunk 5]
```diff
@@ -0,0 +1,155 @@
...
+        }
+        return chapters
+    }
+
+    /**
+     * Controls which chapters appear in the list.
+     * Default: hide locked (requiresPurchase) chapters.
+     * Override to add source-specific logic (e.g. a user preference).
+     */
+    open fun shouldShowChapter(chapter: EZManhwaChapterDto): Boolean = chapter.requiresPurchase != true
```
Comment (AwkwardPeak7) [inline lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt]: just move the pref to multisrc, considering you added it to both sources

File: src/en/ezmanga/src/eu/kanade/tachiyomi/extension/en/ezmanga/EZmanga.kt [hunk 6]
```diff
@@ -1,27 +1,87 @@
...
-        )
+    EZManhwa("EZmanga", "https://ezmanga.org"),
+    ConfigurableSource {
+
+    override val apiUrl = "https://vapi.ezmanga.org/api/v1"
+    override val rateLimitPermits = 3
+
+    private val preferences: SharedPreferences by lazy {
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
+    }
```
Comment (AwkwardPeak7) [inline src/en/ezmanga/src/eu/kanade/tachiyomi/extension/en/ezmanga/EZmanga.kt]: use `keiyoushi.utils.getPreferenceLazy`

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt [hunk 7]
```diff
@@ -0,0 +1,160 @@
...
+            throw Exception(
+                "Chapter requires purchase (${data.totalImages} pages). " +
+                    "Log in via webview and purchase to read.",
+            )
+        }
+        return data.images?.mapIndexed { i, img -> Page(i, imageUrl = img.url) }
+            ?: throw Exception("No images found. Chapter may be locked or require login via webview.")
+    }
+
+    override fun imageUrlParse(response: Response) = throw UnsupportedOperationException("Not used")
```
Comment (AaronDeimos) [inline lib-multisrc/ezmanhwa/src/eu/kanade/tachiyomi/multisrc/ezmanhwa/EZManhwa.kt]:
```suggestion
    override fun imageUrlParse(response: Response) = throw UnsupportedOperationException()
```
No message in unsupported exception as per guidelines

File: src/en/ezmanga/src/eu/kanade/tachiyomi/extension/en/ezmanga/EZmanga.kt [hunk 8]
```diff
@@ -1,27 +1,62 @@
...
 
-class EZmanga :
-    Iken(
-        "EZmanga",
-        "en",
-        "https://ezmanga.org",
-        "https://vapi.ezmanga.org",
-    ) {
-    // Migrated from HeanCms to Iken
-    override val versionId = 4
```
Comment (AwkwardPeak7) [inline src/en/ezmanga/src/eu/kanade/tachiyomi/extension/en/ezmanga/EZmanga.kt:14]: why remove instead of bumping?

Comment (darwin-256) [reply src/en/ezmanga/src/eu/kanade/tachiyomi/extension/en/ezmanga/EZmanga.kt:14]: re-added it

**Review by AwkwardPeak7 — APPROVED** [review]
