### PR TITLE
MGKomik: fix cf in popular and search

### LINKED ISSUE #8823: mgkomik: Search feature not working
### Source information

mgkomik 1.4.57

### Source language

id

### Steps to reproduce

Open the mgkomik extension and then search for the comic name but can't and popular mode doesn't appear

### Expected behavior

Open the mgkomik extension and then search for the comic name but can't and popular mode doesn't appear,
Then the latest mode can be opened

### Actual behavior

Open the mgkomik extension and then search for the comic name but can't and popular mode doesn't appear,
Then the latest mode can be opened

### Mihon/Tachiyomi version

yokai last

### Android version

android 11

### Other details

.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9873: MGKomik: Cloudflare verification is not visible on AZ, J2K/Yokai, SY
### Source information

Mgkomik 1.4.58

### Source language

Indonesia

### Steps to reproduce

1. Open extension
2. Open webview
3. Trigger CF and verify
4. Can load normal

### Expected behavior

Can trigger CF

### Actual behavior

Cant load / trigger CF
Image

If I scroll down / refresh is blocked
Image

I don't think this is my network issue, because I can trigger CF on other extensions like the example below.

Image

Image

I know the CF issue will be closed automatically by the bot, but I think this is a problem with the extension, because MGkomik often has problems like this if you look at the update history of this extension.

### Mihon/Tachiyomi version

J2k 1.7.4

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Riztard**
Closes #8823
Closes #9873

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/mgkomik/src/eu/kanade/tachiyomi/extension/id/mgkomik/MGKomik.kt [hunk 1]
```diff
@@ -44,38 +45,25 @@ class MGKomik : Madara(
...
         }
-        return super.searchRequest(page, query, filters)
-    }
 
-    override fun searchMangaSelector() = "${super.searchMangaSelector()}, .page-listing-item .page-item-detail"
+        return manga
+    }
 
-    override fun searchMangaNextPageSelector() = "a.page.larger"
+    override fun popularMangaNextPageSelector() = "body:not(:has(.no-posts))"
```
Comment (stevenyomi) [inline src/id/mgkomik/src/eu/kanade/tachiyomi/extension/id/mgkomik/MGKomik.kt]:
```suggestion
```

Same as base class.

**Review by stevenyomi — APPROVED** [review]
