### PR TITLE
Manhuarm fixes

### LINKED ISSUE #11104: Manhuarm: `HTTP 403`, `No results found` error on Latest/Popular page
### Source information

Manhuarm 1.4.48

### Source language

Multi

### Steps to reproduce

1.Download manhuarm 
2.open manhuarm 

### Expected behavior

Results should be found 

### Actual behavior

No results found 

https://github.com/user-attachments/assets/ffa98bf0-47a3-4c20-b8af-061052ecd1ef

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 13 

### Other details

It is accessible on WebView 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by fadiajlil2099**
- fixed a bug with the header causing java.io.IOException: Failed to bypass Cloudflare
- fixed covers not loading in popular/latest pages

Closes https://github.com/keiyoushi/extensions-source/issues/11104

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by fadiajlil2099** [comment]
> Please fix this broT_T

fix what?

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt [hunk 1]
```diff
@@ -153,7 +165,19 @@ class Manhuarm(
         val ua = customUserAgent.trim()
         if (ua.isNotEmpty()) {
             builder.set("User-Agent", ua)
+        } else {
+            // Set a Firefox UA to better mimic browser requests
```
Comment (AwkwardPeak7) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt]: hardcoding useragent is not good idea. besides app already sets a browser useragent (mobile chrome) as default

Comment (fadiajlil2099) [reply src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt]: I have removed the hardcoded useragent

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt [hunk 2]
```diff
@@ -118,10 +118,22 @@ class Manhuarm(
...
+                isClientWarmedUp = false // Reset warm-up flag when client is rebuilt
+            }
+            if (!isClientWarmedUp) {
+                try {
+                    // Warm up the client by making a request to the base URL to solve Cloudflare challenge
+                    field!!.newCall(GET(baseUrl, headers)).execute().close()
+                    isClientWarmedUp = true
+                } catch (e: Exception) {
+                    // Ignore errors during warm-up
+                }
```
Comment (choppeh) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt]: Could you move this code to the ```Interceptor```? When the HTTP status code is > 400, then you could make a request to baseURL.

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/interceptors/CloudflareWarmupInterceptor.kt [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+            try {
+                val warmupRequest = GET(baseUrl, headers)
+                val warmupResponse = chain.proceed(warmupRequest)
+                warmupResponse.close()
+                isWarmedUp.set(true)
+
+                return chain.proceed(request)
+            } catch (e: Exception) {
+                return chain.proceed(request)
+            }
```
Comment (vetleledaal) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/interceptors/CloudflareWarmupInterceptor.kt]:
```suggestion
            } catch (e: Exception) {}
        return chain.proceed(request)
```

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/interceptors/CloudflareWarmupInterceptor.kt [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+    private val headers: Headers,
+) : Interceptor {
+
+    private val isWarmedUp = AtomicBoolean(false)
+
+    override fun intercept(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val response = chain.proceed(request)
+
+        if (response.code > 400 && !isWarmedUp.get()) {
```
Comment (vetleledaal) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/interceptors/CloudflareWarmupInterceptor.kt]:
```suggestion
        if (!response.isSuccessful && !isWarmedUp.get()) {
```

**Review by AwkwardPeak7 — APPROVED** [review]
