### PR TITLE
Kuroi manga: Fix chapter name

### LINKED ISSUE #7143: Kuroi manga: Chapter names are not visible.
### Source information

Kuroi manga 1.4.37

### Source language

Turkish 

### Steps to reproduce

1. Open source
2. Open any series

### Expected behavior

Chapter names should appear.

### Actual behavior

But the chapter names are not visible.

### Mihon/Tachiyomi version

Mihon 0.17.1

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #7143

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/tr/kuroimanga/src/eu/kanade/tachiyomi/extension/tr/kuroimanga/KuroiManga.kt [hunk 1]
```diff
@@ -26,4 +28,24 @@ class KuroiManga : Madara(
...
+            chapter.name = selectFirst("li > a")!!.text()
+            // Dates can be part of a "new" graphic or plain text
+            // Added "title" alternative
+            chapter.date_upload = selectFirst("img:not(.thumb)")?.attr("alt")?.let { parseRelativeDate(it) }
+                ?: selectFirst("span a")?.attr("title")?.let { parseRelativeDate(it) }
+                ?: parseChapterDate(selectFirst(chapterDateSelector())?.text())
+        }
+
+        return chapter
+    }
```
Comment (AwkwardPeak7) [inline src/tr/kuroimanga/src/eu/kanade/tachiyomi/extension/tr/kuroimanga/KuroiManga.kt]: call `super.chapterFromElement(element)` then modify the name field here

```kt
return super.chapterFromElement(element).apply {
    name = ...
}
```

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/tr/kuroimanga/src/eu/kanade/tachiyomi/extension/tr/kuroimanga/KuroiManga.kt (hunk 1 above)
Comment (dngonz) [reply src/tr/kuroimanga/src/eu/kanade/tachiyomi/extension/tr/kuroimanga/KuroiManga.kt]: Changed, thanks!

**Review by vetleledaal — APPROVED** [review]
