### PR TITLE
Reaper Scans: Update to new website

### LINKED ISSUE #4356: Reaper Scans New Website
### Source information

Reaper Scans 1.4.49

### Source language

English

### Steps to reproduce

Open any comic from the aforementioned source. Or even open the webview.

### Expected behavior

Show chapters.

### Actual behavior

404 Not Found.

### Mihon/Tachiyomi version

Mihon Beta r6789 or any other

### Android version

Android 13

### Other details

Reaper Scans have rewritten their website, thus the extension is no longer working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by webmsgr**
Closes #4356
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 1]
```diff
@@ -66,104 +51,43 @@ class ReaperScans : ParsedHttpSource() {
...
-    override fun popularMangaNextPageSelector(): String = "button[wire:click*=nextPage]"
-
-    override fun popularMangaSelector(): String = "li"
-
-    override fun popularMangaFromElement(element: Element): SManga {
-        return SManga.create().apply {
-            element.select("a.text-white").let {
-                title = it.text()
-                setUrlWithoutDomain(it.attr("href"))
+    override fun popularMangaRequest(page: Int): Request = GET("https://api.reaperscans.com/query?page=$page&perPage=20&series_type=Comic&query_string=&order=desc&orderBy=total_views&adult=true", headers)
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: save `apiUrl` variable in the class instead of repeating it multiple times

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 2]
```diff
@@ -66,104 +51,43 @@ class ReaperScans : ParsedHttpSource() {
...
-        }.toString().toRequestBody(JSON_MEDIA_TYPE)
-
-        val headers = Headers.Builder()
-            .add("x-csrf-token", csrfToken)
-            .add("x-livewire", "true")
-            .build()
-
-        return POST("$baseUrl/livewire/message/$routeName", headers, payload)
-    }
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request = GET("https://api.reaperscans.com/query?page=$page&perPage=20&series_type=Comic&query_string=${query.replace(' ', '+')}&order=desc&orderBy=total_views&adult=true", headers)
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: use `HttpUrl.Builder` to encode the query properly.

also there are filters on the site, will you consider implementing them? (you don't have to just asking)

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 3]
```diff
@@ -66,104 +51,43 @@ class ReaperScans : ParsedHttpSource() {
...
+
+    override fun popularMangaParse(response: Response): MangasPage {
+        val data = response.parseJson<SeriesQueryDto>()
+
+        val mangas = data.data.map {
+            SManga.create().apply {
+                title = it.title
+                // Don't know what "4SRBHm" is for but it seems constant across all series
+                thumbnail_url = "https://media.reaperscans.com/file/4SRBHm/${it.thumbnail}"
+                url = "/series/${it.slug}"
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: are old urls compatible with new ones? if not bump the `versionId` in the class

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 4]
```diff
@@ -177,119 +101,71 @@ class ReaperScans : ParsedHttpSource() {
...
     // Chapters
-    private fun chapterListNextPageSelector(): String = "button[wire:click*=nextPage]"
 
-    override fun chapterListSelector() = "div[wire:id] > div > ul[role=list] > li"
+    override fun chapterListRequest(manga: SManga): Request {
+        // this is extremely hacky.
+        val response = client.newCall(searchMangaRequest(1, manga.title, FilterList())).execute()
+        val data = response.parseJson<SeriesQueryDto>()
+        val seriesId = data.data.first().id
+        return GET("https://api.reaperscans.com/chapter/query?page=1&perPage=30&series_id=$seriesId", headers)
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: please don't...
save the id in the url as fragment during browse. (bump versionId too)
`/series/$slug#$id`

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 5]
```diff
@@ -177,119 +101,71 @@ class ReaperScans : ParsedHttpSource() {
...
-                setUrlWithoutDomain(urlElement.attr("href"))
-                urlElement.select("p").let {
-                    name = it.getOrNull(0)?.text() ?: ""
-                    date_upload = it.getOrNull(1)?.text()?.parseRelativeDate() ?: 0
-                }
+                },
+            )
+            if (data.meta.currentPage != data.meta.lastPage) {
+                data = client.newCall(GET("https://api.reaperscans.com/chapter/query?page=${data.meta.currentPage + 1}&perPage=30&series_id=$seriesId", headers)).execute().parseJson()
+            } else {
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: just put `perPage=9999` and don't worry about it. (unless it doesn't work?)

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 6]
```diff
@@ -177,119 +101,71 @@ class ReaperScans : ParsedHttpSource() {
...
 
     // Page
     override fun pageListParse(document: Document): List<Page> {
-        document.select("noscript").remove()
-        return document.select("img.max-w-full").mapIndexed { index, element ->
-            Page(index, imageUrl = element.imgAttr())
+        return document.select("div.items-center.justify-center > img[data-src]").mapIndexed { index, element ->
+            val imageUrl = element.attr("src").ifEmpty {
+                element.attr("data-src")
+            }
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: use the `imgAttr()` function available in the class

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 7]
```diff
@@ -300,52 +176,13 @@ class ReaperScans : ParsedHttpSource() {
...
     private fun Element.imgAttr(): String = when {
         hasAttr("data-lazy-src") -> attr("abs:data-lazy-src")
         hasAttr("data-src") -> attr("abs:data-src")
         hasAttr("data-cfsrc") -> attr("abs:data-cfsrc")
         else -> attr("abs:src")
     }
 
-    private fun Elements.imgAttr(): String = this.first()!!.imgAttr()
-
     private fun randomString(length: Int): String {
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: remove unnecessary functions which are not used anymore

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 8]
```diff
@@ -356,8 +193,29 @@ class ReaperScans : ParsedHttpSource() {
...
+    override fun searchMangaFromElement(element: Element): SManga = throw UnsupportedOperationException()
+
+    override fun chapterFromElement(element: Element): SChapter = throw UnsupportedOperationException()
+
+    override fun popularMangaSelector(): String = throw UnsupportedOperationException()
+
+    override fun popularMangaNextPageSelector(): String = throw UnsupportedOperationException()
+
+    override fun chapterListSelector() = throw UnsupportedOperationException()
+
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: inherit from `HttpSource` instead of `ParsedHttpSource`

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScansDto.kt [hunk 9]
```diff
@@ -1,21 +1,56 @@
...
 
+import kotlinx.serialization.SerialName
 import kotlinx.serialization.Serializable
-import kotlinx.serialization.json.JsonObject
 
 @Serializable
-data class LiveWireResponseDto(
-    val effects: LiveWireEffectsDto,
-    val serverMemo: JsonObject,
+data class MetaDto(
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScansDto.kt]: use regular classes, data classes are not necessary

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 10]
```diff
@@ -177,119 +101,71 @@ class ReaperScans : ParsedHttpSource() {
     // Details
     override fun mangaDetailsParse(document: Document): SManga {
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: there is an endpoint for details too
`$apiUrl/series/$slug`
`https://api.reaperscans.com/series/ghost-story-club-remake`

**Comment by webmsgr** [comment]
~~Hold off on merging this, found a chapter data endpoint with page urls.~~
Edit: Resolved.

**Comment by bapeey** [comment]
Isn't the theme [HeanCMS](https://github.com/keiyoushi/extensions-source/blob/55b4a3dbecacc8a67286059f73093e2fe6592d73/lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt)?

File: src/en/reaperscans/build.gradle [hunk 11]
```diff
@@ -1,7 +1,9 @@
 ext {
     extName = 'Reaper Scans'
     extClass = '.ReaperScans'
-    extVersionCode = 49
+    themePkg = 'heancms'
+    baseUrl = 'https://reaperscans.com'
+    overrideVersionCode = 50
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/build.gradle]: heancms base version is 25, so adjust the override version accordingly

**Review by AwkwardPeak7 — APPROVED** [review]
