### PR TITLE
SSSScanlator: Add random UA

### LINKED ISSUE #3664: Páginas não está carregando
### Source information

SSSScanlator 1.4.32

### Source language

Português (Brasil)

### Steps to reproduce

As páginas não estão carregando 
Screenshot_20240620-173848

### Expected behavior

As páginas tinha que carregar 

### Actual behavior

Não está carregando as páginas 

### Mihon/Tachiyomi version

Tachiyomi SY 1.10.5

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #3664

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/SSSScanlator.kt [hunk 1]
```diff
@@ -1,36 +1,68 @@
...
+class SSSScanlator :
+    MangaThemesia(
+        "SSSScanlator",
+        "https://sssscanlator.com.br",
+        "pt-BR",
+        dateFormat = SimpleDateFormat("MMMMM dd, yyyy", Locale("pt", "BR")),
+    ),
+    ConfigurableSource {
+
+    private val preferences by lazy {
```
Comment (AwkwardPeak7) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/SSSScanlator.kt]: remove lazy

**Review by AwkwardPeak7 — APPROVED** [review]
