### PR TITLE
Happymh: Fix page list and chapter WebView

### LINKED ISSUE #6102: A strange bug of happymh 嗨皮漫画
### Source information

1.4.12

### Source language

Chinese 

### Steps to reproduce

click a chapter and read 

### Expected behavior

Load the comic like normal 

### Actual behavior

Only can bypass cloudflare some chapters

### Mihon/Tachiyomi version

0.17.0

### Android version

14

### Other details

https://github.com/user-attachments/assets/b555ed17-7d49-4a20-a518-49f52c04b8a5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by anenasa**
Closes #6102

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 1]
```diff
@@ -151,22 +151,26 @@ class Happymh : HttpSource(), ConfigurableSource {
...
         }
     }
 
+    override fun getChapterUrl(chapter: SChapter): String {
+        return baseUrl + chapter.url
+    }
+
     // Pages
 
     override fun pageListRequest(chapter: SChapter): Request {
```
Comment (AwkwardPeak7) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt:166]: throw exception saying to refresh chapter list if old format is detected

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt (hunk 1 above)
Comment (anenasa) [reply src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt:166]: In getChapterUrl() or pageListRequest(), or both?

**Comment by Rstoroniomi** [comment]
這裡無法繞過cloud flare😢

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt (hunk 1 above)
Comment (AwkwardPeak7) [reply src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt:166]: pageListRequest

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by Rstoroniomi** [comment]
我希望修改这款插件，不然看不了漫画。
I hope revise this plug-in，otherwise I cannot read comics.
