### PR TITLE
Batoto: Blacklist k07 server and auto backoff from failed image servers

### LINKED ISSUE #12568: Bato.to k07 server causes read/download failure
### Source information

Bato.to 1.4.58

### Source language

All

### Steps to reproduce

1. Download/read a chapter
2. If an image source originates from k07 server, the chapter fails to download / image fails to load

### Expected behavior

Should correctly fallback to n server

### Actual behavior

Download errors out / image fails to load

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 14

### Other details

Recently, unlike other k servers that return http errors such as 404/503, k07 server began returning `HTTP/1.1 301 Moved Permanently`, and redirects to `plateforme-cabinet-guerin.fr` domain. For example, this [k07 link](https://k07.mbhiz.org/media/mbch/4e0/695aefb5c3860c9edf8b30e4/134930731_1280_2400_372080.webp) would end up at this [plateforme-cabinet-guerin.fr](https://plateforme-cabinet-guerin.fr/media/mbch/4e0/695aefb5c3860c9edf8b30e4/134930731_1280_2400_372080.webp) link. My guess is that this redirection behaviour causes the extension to fail to load images that are on the k07 server, and also the cause of a previous closed ticket 3 days ago #12509 . Perhaps the fallback logic is currently too strict and requires specifically 404 or 503 to trigger?

This issue also affects the v4 extension.

I have also replicated this issue on:
Mihon 0.19.3 (Android 14)
Tachimanga v4.11 (iOS 26.1 & iOS 18.7)
Tachidesk (Suwayomi-Server v2.1.1867, Windows)

Interestingly, in the Mihon app, if i continuously restart the failed download, it eventually succeeds, which is why I assume this issue hasn't been reported. However, Tachimanga and Suwayomi-Server will always fail.

Here is a log snippet from Tachidesk. It would repeat a few times trying to download this image, then error out.
```
2026-01-05 20:59:23.540 [OkHttp https://n10.mbopg.org/...] DEBUG eu.kanade.tachiyomi.network.NetworkHelper - --> GET https://n10.mbopg.org/media/mbch/4e0/695aefb5c3860c9edf8b30e4/134930732_1280_2400_342028.webp h2
2026-01-05 20:59:23.850 [OkHttp https://n10.mbopg.org/...] DEBUG eu.kanade.tachiyomi.network.NetworkHelper - <-- 200 https://n10.mbopg.org/media/mbch/4e0/695aefb5c3860c9edf8b30e4/134930732_1280_2400_342028.webp (310ms, 342028-byte body)
2026-01-05 20:59:24.455 [OkHttp https://k07.mbhiz.org/...] DEBUG eu.kanade.tachiyomi.network.NetworkHelper - --> GET https://k07.mbhiz.org/media/mbch/4e0/695aefb5c3860c9edf8b30e4/134930731_1280_2400_372080.webp h2
2026-01-05 20:59:24.779 [OkHttp https://k07.mbhiz.org/...] DEBUG eu.kanade.tachiyomi.network.NetworkHelper - <-- 301 https://k07.mbhiz.org/media/mbch/4e0/695aefb5c3860c9edf8b30e4/134930731_1280_2400_372080.webp (323ms, unknown-length body)
2026-01-05 20:59:45.804 [DefaultDispatcher-worker-11] WARN  suwayomi.tachidesk.manga.impl.download.Downloader source(7890050626002177109) - downloadChapter(Miss Not-So Sidekick [Official] (757) - Side Story 2 Episode 13 (45146) | state= Queued, tries= 0, progress= 0.0)) - failed due to
java.io.IOException: Failed to connect to plateforme-cabinet-guerin.fr/51.159.97.100:443
	at eu.kanade.tachiyomi.source.online.HttpSource.getImage$suspendImpl(HttpSource.kt:374)
	at eu.kanade.tachiyomi.source.online.HttpSource.getImage(HttpSource.kt)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$6.invokeSuspend(Page.kt:129)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$6.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.Page$getPageImage$6.invoke(Page.kt)
	at suwayomi.tachidesk.manga.impl.util.storage.ImageResponse.getImageResponse(ImageResponse.kt:68)
	at suwayomi.tachidesk.manga.impl.Page.getPageImage(Page.kt:128)
	at suwayomi.tachidesk.manga.impl.Page.getPageImage$default(Page.kt:49)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.ChaptersFilesProvider.downloadImpl(ChaptersFilesProvider.kt:141)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.ChaptersFilesProvider.access$downloadImpl(ChaptersFilesProvider.kt:68)
	at suwayomi.tachidesk.manga.impl.download.fileProvider.ChaptersFilesProvider$downloadImpl$1.invokeSuspend(ChaptersFilesProvider.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
Caused by: java.net.ConnectException: Failed to connect to plateforme-cabinet-guerin.fr/51.159.97.100:443
	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:282)
	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:140)
	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:141)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: getsockopt
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:147)
	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:280)
	... 6 common frames omitted
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by LetianLi**
This PR adds
- An image server blacklist. Image servers on this blacklist are immediately skipped in favor of a fallback server
- A 1 hour backoff to image servers that return a 500 error code (400s will not backoff), these servers are also immediately skipped in favor of the next available fallback server.
- ~Ability to modify the fallback list, blacklist, and enable/disable backoff inside Preferences~
- ~See failed servers or backoff servers inside Preferences.~

Closes #12568, by default k07 is added to the blacklist since this server doesn't give a 500 code and isn't caught by the backoff.

Possible extras that I can do
- Remove all k servers from the fallback list, and add all of them to the default blacklist
- Switch to exponential backoff? I tested with 1 minute initial, but the experience ramped too slowly.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] ~Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions~
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] ~Added the `isNsfw = true` flag in `build.gradle` when appropriate~
- [x] Have not changed source names
- [x] ~Have explicitly kept the `id` if a source's name or language were changed~
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] ~Have removed `web_hi_res_512.png` when adding a new extension~

### CODE REVIEW

**Comment by LetianLi** [comment]
Extension settings screenshot:

**Review by AwkwardPeak7 — COMMENTED** [review]
I don't think preferences are needed. also, our v2 and v4 extension is now merged into one. please update pr to apply changes to that

**Comment by LetianLi** [comment]
I've rebased on top of latest, removed preferences, and updated both v4 and v2 with the code.

**Comment by LetianLi** [comment]
I can quickly fix issue #12663 with a one-line change on line 327 here, I just don't know if that should be a different PR for bookkeeping.

**Comment by AwkwardPeak7** [comment]
Make a new pr, it can be merged together with this one so only one update to users

File: src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/BatoToV4.kt [hunk 1]
```diff
@@ -564,3 +577,53 @@ private const val BROWSE_PAGE_SIZE = 36
 private val seriesIdRegex = Regex("""series/(\d+)""")
 private val titleRegex: Regex =
     Regex("\\([^()]*\\)|\\{[^{}]*\\}|\\[(?:(?!]).)*]|«[^»]*»|〘[^〙]*〙|「[^」]*」|『[^』]*』|≪[^≫]*≫|﹛[^﹜]*﹜|〖[^〖〗]*〗|\uD81A\uDD0D.+?\uD81A\uDD0D|《[^》]*》|⌜.+?⌝|⟨[^⟩]*⟩|/Official|/ Official", RegexOption.IGNORE_CASE)
+
+/**
+ * Manages image server fallback logic, including blacklisting and backoff tracking.
+ */
+private class ImageServerManager() {
```
Comment (AwkwardPeak7) [inline src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/BatoToV4.kt]: class can be shared between the two implementations

File: src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov2/BatoToV2.kt [hunk 2]
```diff
@@ -1150,3 +1159,53 @@ open class BatoToV2(
...
+
+/**
+ * Manages image server fallback logic, including blacklisting and backoff tracking.
+ */
+private class ImageServerManager() {
+    val serverPattern = Regex("https://([a-zA-Z]\\d{2})")
+
+    val fallbackServers = listOf(
+        "n03", "n00", "n01", "n02", "n04", "n05", "n06", "n07", "n08", "n09", "n10",
+        "k03", "k06", "k00", "k01", "k02", "k04", "k05", "k08", "k09",
```
Comment (DTM9025) [inline src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov2/BatoToV2.kt]: I would suggest removing all the k servers as none of them are working at the moment

File: src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/BatoToV4.kt [hunk 3]
```diff
@@ -564,3 +577,53 @@ private const val BROWSE_PAGE_SIZE = 36
...
+    val serverPattern = Regex("https://([a-zA-Z]\\d{2})")
+
+    val fallbackServers = listOf(
+        "n03", "n00", "n01", "n02", "n04", "n05", "n06", "n07", "n08", "n09", "n10",
+        "k03", "k06", "k00", "k01", "k02", "k04", "k05", "k08", "k09",
```
Comment (DTM9025) [inline src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/BatoToV4.kt]: Same here (removing all the k servers).

File: src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/BatoToV4.kt (hunk 1 above)
Comment (LetianLi) [reply src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/BatoToV4.kt]: I've moved it into BatoTo.kt. We still duplicate imageFallbackInterceptor and tryServer, though that doesn't seem to be too easy to share.

File: src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov2/BatoToV2.kt (hunk 2 above)
Comment (LetianLi) [reply src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov2/BatoToV2.kt]: Should I comment it out so we can add them back later? Should I add to the blacklist so they're immediately skipped as well?

Comment (DTM9025) [reply src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov2/BatoToV2.kt]: I think for now putting them in the black list is probably the one that makes the images load in the quickest?

Comment (LetianLi) [reply src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov2/BatoToV2.kt]: Yes

**Review by AwkwardPeak7 — APPROVED** [review]
