### PR TITLE
Yushuke Mangas: Fix chapters list and pages

### LINKED ISSUE #7486: Yushuke Mangas: Unexpected JSON token error
### Source information

Yushuke Mangas 1.4.3

### Source language

Português (Brasil)

### Steps to reproduce

https://github.com/user-attachments/assets/7ecffa01-e844-4347-b32d-28be23fedec0

( Já não tinha saído uma atualização pra arrumar isso uns dias atrás?  )

### Expected behavior

Carregar normalmente os capítulos das obras 

### Actual behavior

Tá dando erro 

### Mihon/Tachiyomi version

Komikku 1.12.4

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #7486 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by lordenecromante** [comment]
I found 2 more errors in the extension, I'll set it as a draft to fix them.

File: src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt [hunk 1]
```diff
@@ -193,8 +200,10 @@ class YushukeMangas : ParsedHttpSource() {
     // ============================== Pages ===============================
 
     override fun pageListParse(document: Document): List<Page> {
-        return document.select(".manga-container .manga-image").mapIndexed { index, imageUrl ->
-            Page(index, imageUrl = imageUrl.absUrl("src"))
+        return document.select("div.select-nav + * picture").mapIndexed { index, pictureElement ->
+            val imgElement = pictureElement.selectFirst("img")
+            val imageUrl = imgElement?.attr("src") ?: ""
```
Comment (AwkwardPeak7) [inline src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt]: filter out to not include broken pages

File: src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt [hunk 2]
```diff
@@ -180,7 +187,7 @@ class YushukeMangas : ParsedHttpSource() {
     }
 
     private fun fetchChapterListPage(mangaId: String, page: Int): Response {
-        val url = "$baseUrl/ajax/carregar_capitulos.php?order=DESC".toHttpUrl().newBuilder()
+        val url = "$baseUrl/ajax/lzmvke.php?order=DESC".toHttpUrl().newBuilder()
```
Comment (AwkwardPeak7) [inline src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt:190]: i feel like this is a cat n mouse, any way to maybe get this endpoint name?

File: src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt (hunk 1 above)
Comment (lordenecromante) [reply src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt]: Fix it.

File: src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt (hunk 2 above)
Comment (lordenecromante) [reply src/pt/yushukemangas/src/eu/kanade/tachiyomi/extension/pt/yushukemangas/YushukeMangas.kt:190]: He doesn't have it, he's constantly changing the site now. First, it was load_chapter, then carregar_capitulos (which means 'load chapters' in Portuguese), and now he added these random letters... He's trying to prevent us from finding the endpoint that loads the chapters and the class for the pages. He created a function to keep changing the class where the pages are located every X time, so I had to use a higher-level class that remains fixed.

**Review by AwkwardPeak7 — APPROVED** [review]
