### PR TITLE
Mangadex: Handle missing isUnavailable chapter field

### LINKED ISSUE #9296: MangaDex - isUnavailable required but doesn't exist
### Source information

MangaDex 1.4.202

### Source language

All

### Steps to reproduce

1. Enable ability to see unavailable chapters
2. Go to /title/8b12f337-66f9-4bf0-b017-5abcf4425a6d (beware, NSFW)
3. Try and open it in the app

### Expected behavior

Should see every chapter

### Actual behavior

Get given this error

Image

Have confirmed someone else experienced it when I went to support to see if it was a DB issue and how to selectively clear a single entry.

### Mihon/Tachiyomi version

0.18.0 (6294521, 11, 2025-03-19T22:40:59Z)

### Android version

14 (SDK 34; build U1TRS34.8-30-18-8)

### Other details

Edit: turns out the setting for seeing unavailable chapters is relevant.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FlaminSarge**
Fixes #9296 

Followup from #9208 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by FlaminSarge** [comment]
We may have to update this again to either true or false if we get word from MD devs that it should default to one of those values instead, but this will at least cover the linked issue for now, though chapters that fall into this category may not show UNAVAILABLE but still be unavailable.

**Comment by FlaminSarge** [comment]
```
[3:29 AM]T10[ꓟꓓ]
:
>There's no isUnavailable field
Caused by the indexing issue. I reindexed the chapter as first troubleshooting step and it now has the field.
>the chapter is unavailable anyways
No idea what causes it, but the md@h endpoint shouldn't respond with 404.
>Should isUnavailable be treated as default true for all chapters unless explicitly set to false?
No idea. Maybe a backend dev knows (?).
```
```
[3:31 AM]T10[ꓟꓓ]
: But yeah, if you want to explicitly handle it then I would handle it like this:
if no isUnavailable field assume it's available.
if it isn't a delayed or link chapter, request the md@h endpoint.
if the endpoint responds with 404 or the data array is empty, then it's a bugged chapter.```

File: src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/ChapterDto.kt [hunk 1]
```diff
@@ -20,7 +20,7 @@ data class ChapterAttributesDto(
     val pages: Int,
     val publishAt: String,
     val externalUrl: String?,
-    val isUnavailable: Boolean?,
+    val isUnavailable: Boolean? = null,
```
Comment (AwkwardPeak7) [inline src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/ChapterDto.kt]:
```suggestion
    val isUnavailable: Boolean = false,
```

Comment (FlaminSarge) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/ChapterDto.kt]: Doublechecking with MD devs that this field can't be explicitly null before I add this.

Comment (FlaminSarge) [reply src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/ChapterDto.kt]: > T10[ꓟꓓ]: From what I can see, the field type on the api's side is boolean.

**Review by AwkwardPeak7 — APPROVED** [review]
