### PR TITLE
TenkaiScan: Change theme

### LINKED ISSUE #2149: TenkaiScan: Error 403
### Source information

TenkaiScan 1.4.35

### Source language

Spanish

### Steps to reproduce

Open source

### Expected behavior

Should show mangas

### Actual behavior

error 403: open in webview

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 12

### Other details

In WebView the page loads correctly
Extension doesn't work with VPN too

Doesn't seem to be clоцdF issue
I can't tell if the website changed its url
The actual url is https://tenkaiscan.net/ anyways

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #2149 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt [hunk 1]
```diff
@@ -1,15 +1,248 @@
...
-    "TenkaiScan",
-    "https://tenkaiscan.net",
-    "es",
-    dateFormat = SimpleDateFormat("dd 'de' MMMM 'de' yyyy", Locale("es")),
-) {
+
+class TenkaiScan : ParsedHttpSource() {
+
+    // Site change theme from Madara to custom theme
     override val versionId = 2
```
Comment (vetleledaal) [inline src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt]:
```suggestion
    override val versionId = 3
```

File: src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt [hunk 2]
```diff
@@ -1,15 +1,248 @@
...
+    override fun getFilterList(): FilterList = FilterList(
+        Filter.Header("NOTA: Los filtros serán ignorados si se realiza una búsqueda por texto."),
+        Filter.Header("Solo se puede aplicar un filtro a la vez."),
+        AlphabeticFilter(),
+        GenreFilter(),
+        StatusFilter(),
+    )
+
+    override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
+        document.selectFirst("div.page-content div.text-details")?.let { element ->
```
Comment (AwkwardPeak7) [inline src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt]:
```suggestion
        document.selectFirst("div.page-content div.text-details")!!.let { element ->
```

File: src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt [hunk 3]
```diff
@@ -1,15 +1,248 @@
...
+
+    override fun getFilterList(): FilterList = FilterList(
+        Filter.Header("NOTA: Los filtros serán ignorados si se realiza una búsqueda por texto."),
+        Filter.Header("Solo se puede aplicar un filtro a la vez."),
+        AlphabeticFilter(),
+        GenreFilter(),
+        StatusFilter(),
+    )
+
+    override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
```
Comment (AwkwardPeak7) [inline src/es/tenkaiscan/src/eu/kanade/tachiyomi/extension/es/tenkaiscan/TenkaiScan.kt:122]: should set thumbnail too

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
