### PR TITLE
Kagane: Fix search and chapters index

### LINKED ISSUE #11003: Kagane: Add Option for Separate Chapter Numbers
### Source name

Kagane

### Source language

English

### Describe your suggested feature

Kagane sometimes messes up chapter names (on their website) by not including the number or using the wrong one (like how on Webtoons there's always two chapter numbers), which leads to a lot of weird behaviour; "missing" chapters and messed up tracking.
So having a separate chapter count (like is already present on their website) would be great.

### Other details

Example of missing the chapter number:
Image

Example of using the wrong number:
Image

Moreover on something like The Witch's Throne which doesn't have any chapter numbers in the first place Comikku is telling me 2015 chapters are missing and tracking is completely broken.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11008: Kagane Search
### Source information

Kagane 1.4.5

### Source language

English

### Steps to reproduce

1. Enter extension
2. Search for any series name

### Expected behavior

The series that is the same as the written name is in the first or nearby lines. 

### Actual behavior

The series whose name is written cannot even be found nearby.  

### Mihon/Tachiyomi version

Komikku 1.13.3

### Android version

Android 11

### Other details

When I search for the series in the browser, I can find it on the same site.  

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #11003 - Force the chapters to follow the correct order
Closes #11008 - This was a filter issue, now should works like the website

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 1]
```diff
@@ -203,7 +205,7 @@ class Kagane : HttpSource(), ConfigurableSource {
 
     override fun chapterListParse(response: Response): List<SChapter> {
         val dto = response.parseAs<ChapterDto>()
-        return dto.content.map { it.toSChapter() }.reversed()
+        return dto.content.mapIndexed { i, it -> it.toSChapter(i) }.reversed()
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]:
```suggestion
        return dto.content.mapIndexed { i, it -> it.toSChapter(i + 1) }.reversed()
```

**Review by AwkwardPeak7 — APPROVED** [review]
