### PR TITLE
HentaiMode (ES): Fix searching and Page

### LINKED ISSUE #10063: NXDOMAIN HENTAIMODE
### Source information

Hentaimode.com 1.4.3

### Source language

Spanish / Español

### Steps to reproduce

NXDOMAIN appears when viewing a chapter

Image

### Expected behavior

All the covers appear, as well as the information of the chapters. So the chapters should show the images and they don't appear.  

### Actual behavior

Pero al abrir un capítulo solo aparece NXDOMAIN

### Mihon/Tachiyomi version

0.19.0

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #14393: Hentaimode: Search results don't match website search results
### Source information

Hentai mode 1.4.3

### Source language

Spanish 

### Steps to reproduce

Enter the extension and search for any title
The search results contains random singular chapters
Missing search results from the source.

Image

### Expected behavior

The search should show all the related titles for the search term

### Actual behavior

The search results in random titles, based on the titles. Additionally, when opening any chapter it gives an nxdomain error

Image

### Mihon/Mihon fork version

0.19.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by disk-iq8**
Closes #14393
Closes #10063

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/hentaimode/src/eu/kanade/tachiyomi/extension/es/hentaimode/HentaiMode.kt [hunk 1]
```diff
@@ -73,7 +73,7 @@ class HentaiMode : ParsedHttpSource() {
 
     override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
         require(query.length >= 3) { "Please use at least 3 characters!" }
-        return GET("$baseUrl/buscar?s=$query")
+        return GET("$baseUrl/buscar?s=$query", headersBuilder().set("Referer", baseUrl).build())
```
Comment (vetleledaal) [inline src/es/hentaimode/src/eu/kanade/tachiyomi/extension/es/hentaimode/HentaiMode.kt]: Extract the headers to the class.

Comment (vetleledaal) [inline src/es/hentaimode/src/eu/kanade/tachiyomi/extension/es/hentaimode/HentaiMode.kt]: Browsers always append a `/` to this header for the root document.
```suggestion
        return GET("$baseUrl/buscar?s=$query", headersBuilder().set("Referer", "$baseUrl/").build())
```

Comment (vetleledaal) [inline src/es/hentaimode/src/eu/kanade/tachiyomi/extension/es/hentaimode/HentaiMode.kt]: Use `HttpUrlBuilder` to properly escape `query`.

**Review by vetleledaal — APPROVED** [review]
