### PR TITLE
AnimeSama: From .org to .eu & fixes

### LINKED ISSUE #12002: animesama url change .org to .eu
### Source information

tachiyomi-fr.animesama-v1.4.10.apk

### Source language

fr

### Source new URL

https://anime-sama.eu/

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by CriosChan**
- From .org to .eu (Closes #12002)
- Fixed links opening in the app
- Repairing genres in filters that no longer had names
- Repairing manga without names before clicking on them

EDIT: Closes #12003

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by CriosChan** [comment]
I'm aware PR #12003 exists, but @gnatali has only changed the URL, my PR changes the URL and takes the opportunity to fix quite a few bugs in the extension at the same time, so I think my PR is more interesting for Keiyoushi.

File: src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt [hunk 1]
```diff
@@ -62,9 +62,9 @@ class AnimeSama : ParsedHttpSource() {
     private fun filtersRequest() = GET("$baseUrl/catalogue", headers)
 
     private fun parseFilters(document: Document) {
-        genreList = document.select("#list_genres label").mapNotNull { labelElement ->
+        genreList = document.select("#list_genres #genreList label").mapNotNull { labelElement ->
             val input = labelElement.selectFirst("input[name=genre[]]") ?: return@mapNotNull null
-            val labelText = labelElement.ownText()
+            val labelText = labelElement.selectFirst("span")?.text() ?: ""
```
Comment (vetleledaal) [inline src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt]: If `labelText` is empty, will `mapNotNull` filter it out? Maybe it should if not.

**Review by vetleledaal — APPROVED** [review]
