### PR TITLE
Fix SussyToons: Add new api, filters and fix search

### LINKED ISSUE #9397: Sussy Toons: Chapters not working / `Falha ao realizar o login`, `HTTP error 404`, `Field resultados is required` error
### Source information

Sussy Toons 1.4.61 

### Source language

Português brasileiro 

### Steps to reproduce

Continuo com o mesmo problema de não reproduzir capítulos 

### Expected behavior

Mostrar os capítulos 

### Actual behavior

O capítulo não abre,mas com um problema novo

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9640: Aurora Scan (PT-BR): New domain URL
### Source information

Aurora Scan 1.4.5

### Source language

Português 

### Source new URL

https://www.serenitytoons.win/

### Other details

Alteração da URL, a antiga não está mais funcionando 

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9861: Trocaram a URL da extensão Maid Scan
### Source information

Maid Scan 1.4.51

### Source language

Português Brasil PT-BR

### Source new URL

https://empreguetes.xyz/

### Other details

Image

Image

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
Closes: #9397
Closes: #9640
Closes: #9861

Greenshit:

- completely refactored
- bump id

SussyToons:
- add new api url
- fix popular
- fix latest
- fix search
- add filters tab

Maidscan:
- add new baseurl
- fix popular
- fix latest
- fix search

Aurorascan:
- add new baseurl
- fix popular
- fix latest
- fix search

Windscan:
- remove dead source

Checklist:

- [] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by choppeh** [comment]
Hey, search for "greenshit" in the Github search engine: https://github.com/search?q=repo%3Akeiyoushi%2Fextensions-source%20greenshit&type=code. This multi-src is used in other sources

**Comment by FelipeGFA** [comment]
> Hey, search for "greenshit" in the Github search engine: https://github.com/search?q=repo%3Akeiyoushi%2Fextensions-source%20greenshit&type=code. This multi-src is used in other sources

omagah, now ill have to fix the others too 😭

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 1]
```diff
@@ -1,240 +1,261 @@
...
+    val scanId: Int? = null,
+    @JsonNames("status", "obr_status")
+    val status: MangaStatus? = null,
+    @JsonNames("tags", "genres")
+    val genres: List<Genre> = emptyList(),
+    @JsonNames("capitulos", "chapters")
+    val chapters: List<ChapterDto>? = null,
 ) {
+    fun toSManga(cdnUrl: String, useWidth: Boolean, includeSlug: Boolean = false, defaultScanId: Int? = null) = SManga.create().apply {
+        title = name ?: "Unknown"
```
Comment (AwkwardPeak7) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt]: title is mandatory, so don't default to unknown

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 2]
```diff
@@ -1,240 +1,261 @@
...
+        url = if (includeSlug && id != null) {
+            val finalSlug = slug?.takeIf { it.isNotEmpty() } ?: name?.toSlug() ?: "unknown"
```
Comment (AwkwardPeak7) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt]: won't this slug be invalid?

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 3]
```diff
@@ -1,240 +1,261 @@
...
-                    else -> "$CDN_URL/scans/$scanId/obras/${this@MangaDto.id}/$thumbnail"
-                }
+    private fun buildThumbnailUrl(cdnUrl: String, useWidth: Boolean, defaultScanId: Int?): String? = thumbnail?.let {
+        when {
+            it.startsWith("http") -> it
+            it.contains("/") -> "$cdnUrl/$it"
+            else -> {
+                val width = if (useWidth) "?width=300" else ""
+                val scanId = scanId ?: defaultScanId ?: 0
+                val mangaId = id ?: 0
```
Comment (AwkwardPeak7) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt]: same here?

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 4]
```diff
@@ -1,240 +1,261 @@
...
-        @SerialName("scan_id")
-        val scanId: Int,
-    )
+    val chapterNumber: String? get() = _chapterNumber?.content
+
+    fun toPageList(cdnUrl: String): List<Page> {
+        if (type == "TEXTO") {
+            val content = text.orEmpty().ifBlank { "Capítulo em texto." }
+            return listOf(Page(0, imageUrl = TextInterceptorHelper.createUrl(name, content)))
+        }
```
Comment (AwkwardPeak7) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:211]: text interceptor is not for novels, filter out novel results from manga lists, and throw from here

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 5]
```diff
@@ -1,240 +1,261 @@
+
```
Comment (AwkwardPeak7) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt]: remove empty line at top

File: src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt [hunk 6]
```diff
@@ -1,17 +1,35 @@
...
 import eu.kanade.tachiyomi.multisrc.greenshit.GreenShit
-import eu.kanade.tachiyomi.network.interceptor.rateLimit
+import eu.kanade.tachiyomi.source.model.FilterList
+import okhttp3.OkHttpClient
+import java.util.concurrent.TimeUnit
 
 class AuroraScan : GreenShit(
     "Aurora Scan",
-    "https://aurorascan.net",
+    "https://www.serenitytoons.win/",
```
Comment (AwkwardPeak7) [inline src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt]: no trailing slash in urls

File: src/pt/aurorascan/build.gradle [hunk 7]
```diff
@@ -2,7 +2,7 @@ ext {
     extName = 'Aurora Scan'
     extClass = '.AuroraScan'
     themePkg = 'greenshit'
-    baseUrl = 'https://aurorascan.net'
+    baseUrl = 'https://www.serenitytoons.win/'
```
Comment (AwkwardPeak7) [inline src/pt/aurorascan/build.gradle]: same here

**Review by AwkwardPeak7 — DISMISSED** [review]

**Comment by AwkwardPeak7** [comment]
@choppeh plz review too thanks

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt (hunk 4 above)
Comment (FelipeGFA) [reply lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:211]: can i ask why?

is there another alternative or novels arent supported anyways?

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt (hunk 2 above)
Comment (FelipeGFA) [reply lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt]: image

the API always returns “obr_id”, “scan_id” and "obr_nome" as standard

but I removed the nullification and added an illegal argument.

File: lib-multisrc/greenshit/build.gradle.kts [hunk 8]
```diff
@@ -2,4 +2,9 @@ plugins {
     id("lib-multisrc")
 }
 
-baseVersionCode = 6
+baseVersionCode = 7
+
+dependencies {
+    api(project(":lib:textinterceptor"))
+}
```
Comment (choppeh) [inline lib-multisrc/greenshit/build.gradle.kts]: Remove this dependency. It is not needed

```suggestion
```

File: src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt [hunk 9]
```diff
@@ -1,17 +1,35 @@
...
 
 class AuroraScan : GreenShit(
     "Aurora Scan",
-    "https://aurorascan.net",
+    "https://www.serenitytoons.win",
     "pt-BR",
-    scanId = 4,
 ) {
+    override val apiUrl = "https://api.sussytoons.wtf"
+    override val cdnUrl = "https://cdn.sussytoons.site"
```
Comment (choppeh) [inline src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt]: Remove this ```overrride```, it's the same super class

```suggestion
```

File: src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt [hunk 10]
```diff
@@ -1,17 +1,35 @@
...
+    override val useWidthInThumbnail = false
+    override val defaultOrderBy = "data"
     override val targetAudience = TargetAudience.Shoujo
+    override val popularGenreId = "1"
+    override val latestGenreId = "1"
```
Comment (choppeh) [inline src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt]: Remove this ```overrride```, it's the same super class

```suggestion
```

File: src/pt/maidscan/src/eu/kanade/tachiyomi/extension/pt/maidscan/MaidScan.kt [hunk 11]
```diff
@@ -1,27 +1,74 @@
...
 
 class MaidScan : GreenShit(
     "Maid Scan",
-    "https://novo.empreguetes.site",
+    "https://empreguetes.xyz",
     "pt-BR",
-    scanId = 3,
 ) {
+    override val apiUrl = "https://api.sussytoons.wtf"
+    override val cdnUrl = "https://cdn.sussytoons.wtf"
```
Comment (choppeh) [inline src/pt/maidscan/src/eu/kanade/tachiyomi/extension/pt/maidscan/MaidScan.kt]: Remove this ```overrride```, it's the same super class

```suggestion
```

File: src/pt/maidscan/build.gradle [hunk 12]
```diff
@@ -2,7 +2,7 @@ ext {
     extName = 'Maid Scan'
     extClass = '.MaidScan'
     themePkg = 'greenshit'
-    baseUrl = 'https://novo.empreguetes.site'
+    baseUrl = 'https://empreguetes.xyz/'
```
Comment (choppeh) [inline src/pt/maidscan/build.gradle]: Remove the slash at the end of the url
```suggestion
    baseUrl = 'https://empreguetes.xyz'
```

File: src/pt/sussyscan/build.gradle [hunk 13]
```diff
@@ -3,7 +3,7 @@ ext {
     extClass = '.SussyToons'
     themePkg = 'greenshit'
     baseUrl = 'https://www.sussytoons.wtf'
-    overrideVersionCode = 56
+    overrideVersionCode = 56
```
Comment (choppeh) [inline src/pt/sussyscan/build.gradle]: Remove extra spaces

```suggestion
    overrideVersionCode = 56
```

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt (hunk 4 above)
Comment (choppeh) [reply lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:211]: > can i ask why?
> 
> is there another alternative or novels arent supported anyways?

novels aren't supported

Comment (FelipeGFA) [reply lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:211]: got it

File: src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt (hunk 9 above)
Comment (FelipeGFA) [reply src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt]: they are diferent from the super class

sussytoons has
```
    protected open val apiUrl = "https://api2.sussytoons.wtf"
    protected open val cdnUrl = "https://cdn.sussytoons.wtf"
```

aurora has
```
    override val apiUrl = "https://api.sussytoons.wtf"
    override val cdnUrl = "https://cdn.sussytoons.site"
```

maid has the same cdn from super class and same api of aurora

Comment (FelipeGFA) [reply src/pt/aurorascan/src/eu/kanade/tachiyomi/extension/pt/aurorascan/AuroraScan.kt]: actually... im reviewing this now and maybe...they all could be the same

still has more testing to do

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 14]
```diff
@@ -252,148 +212,7 @@ abstract class GreenShit(
...
-                append("\n$warning")
-            }
-            setDefaultValue("")
-
-            setOnPreferenceChangeListener { _, _ ->
-                Toast.makeText(screen.context, RESTART_APP_MESSAGE, Toast.LENGTH_LONG).show()
-                true
-            }
-        }.also(screen::addPreference)
-    }
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt:369]: Is this a feature that is not being carried over, or is it obsolete after changing stuff around?

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 15]
```diff
@@ -1,249 +1,209 @@
...
+
+    private fun <T> parseJsonResponse(response: Response, serializer: kotlinx.serialization.KSerializer<T>): T {
+        val jsonElement = response.parseAs<JsonElement>()
+        val unwrapped = if (jsonElement is JsonObject && jsonElement.containsKey("resultado")) {
+            jsonElement["resultado"]!!
+        } else {
+            jsonElement
+        }
+        return jsonInstance.decodeFromJsonElement(serializer, unwrapped)
+    }
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt:60]: Did you consider using a `JsonTransformingSerializer` for this instead? Its `transformDeserialize()` can be used to pre-process responses like this.

Probably a lot of work/testing to change it, so you can just leave it as-is.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 16]
```diff
@@ -1,249 +1,209 @@
...
-        response.parseAs<ResultDto<WrapperChapterDto>>().toSChapterList()
+    override fun getMangaUrl(manga: SManga) = "$baseUrl${manga.url}"
 
-    private fun chapterListParseWeb(response: Response): List<SChapter> {
-        val json = response.parseScriptToJson().let(DETAILS_CHAPTER_REGEX::find)
-            ?.groups?.get(1)?.value
-            ?: return emptyList()
-        return json.parseAs<ResultDto<WrapperChapterDto>>().toSChapterList()
+    override fun mangaDetailsRequest(manga: SManga): Request {
+        val mangaId = manga.url.substringAfter("/obra/").substringBefore("/")
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt:178]: I'm tempted to suggest using a `HttpUrl` object here and get the segments from that. If you are confident in the current implementation you can leave it as-is.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 17]
```diff
@@ -1,240 +1,259 @@
...
+    @JsonNames("status", "obr_status")
+    val status: MangaStatus? = null,
+    @JsonNames("tags", "genres")
+    val genres: List<Genre> = emptyList(),
+    @JsonNames("capitulos", "chapters")
+    val chapters: List<ChapterDto>? = null,
+    val type: String? = null,
 ) {
+    fun toSManga(cdnUrl: String, useWidth: Boolean, includeSlug: Boolean = false, defaultScanId: Int? = null) = SManga.create().apply {
+        title = name ?: throw IllegalArgumentException("Name is required for title")
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt]: You don't have to be this explicit. You can just:
```suggestion
        title = name!!
```

or if every `MangaDto` you deserialize will eventually call `MangaDto.toSManga()` then you can move the constraint to the field itself.

```diff
-val name: String? = null,
+val name: String = null,
```

Comment applies to the slug as well.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 18]
```diff
@@ -1,240 +1,259 @@
...
 class PageDto(
     val src: String,
-    @SerialName("numero")
-    val number: Float? = null,
+    val mime: String? = null,
+    var path: String? = null,
+    @SerialName("numero") private val _numero: JsonPrimitive? = null,
 ) {
-    fun isWordPressContent(): Boolean = number == null
+    val numero: String? get() = _numero?.content
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:226]: I think you can use the field directly with:
```suggestion
    @Serialize(with = SomeCustomSeralizer::class)
    val numero: String? = null,
) {
```

Might be more work than what it's worth.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 19]
```diff
@@ -1,240 +1,259 @@
...
+
+    fun toPageOrNull(cdnUrl: String, mangaId: Int?, chapterNumber: String?): Page? = runCatching { toPage(cdnUrl, mangaId, chapterNumber) }.getOrNull()
+
+    fun toPage(cdnUrl: String, mangaId: Int?, chapterNumber: String?): Page {
+        require(src.isNotBlank()) { "Page src cannot be empty" }
+
+        if (src.startsWith("http://") || src.startsWith("https://")) {
+            return Page(0, "", src)
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt]:
```suggestion
            return Page(0, imageUrl = src)
```

Comment applies to the other use of `Page` as well.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 20]
```diff
@@ -1,240 +1,259 @@
...
-    .joinToString("/")
+fun String?.toSlug(slugSeparator: String = "-"): String {
+    if (this == null) return ""
+    return Normalizer.normalize(this, Normalizer.Form.NFD)
+        .replace("\\p{InCombiningDiacriticalMarks}+".toRegex(), "")
+        .lowercase()
+        .replace("[^a-z0-9\\s-]".toRegex(), "")
+        .replace("\\s+".toRegex(), slugSeparator)
+        .trim(*slugSeparator.toCharArray())
+}
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:271]: Regex here is static, extract them to the class.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt (hunk 14 above)
Comment (FelipeGFA) [reply lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt:369]: nahh, this source doesnt require login anymore

**Review by vetleledaal — APPROVED** [review]
