### PR TITLE
Hentaiteca: Add random UA

### LINKED ISSUE #3752: Hentai Teca: Access denied
### Source information

Hentai Teca 1.4.37

### Source language

Portuguese

### Steps to reproduce

1. Access denied
2. You do not have access to hentaiteca.net.

### Expected behavior

Access allowed

### Actual behavior

Access denied

### Mihon/Tachiyomi version

J2K 1.7.4

### Android version

Android 13

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #3752

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/hentaiteca/src/eu/kanade/tachiyomi/extension/pt/hentaiteca/HentaiTeca.kt [hunk 1]
```diff
@@ -1,20 +1,47 @@
...
     override val client: OkHttpClient = super.client.newBuilder()
+        .setRandomUserAgent(
+            preferences.getPrefUAType(),
+            preferences.getPrefCustomUA(),
+        )
         .rateLimit(1, 2, TimeUnit.SECONDS)
         .build()
+
+    override fun headersBuilder(): Headers.Builder = super.headersBuilder()
+        .set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0")
```
Comment (AwkwardPeak7) [inline src/pt/hentaiteca/src/eu/kanade/tachiyomi/extension/pt/hentaiteca/HentaiTeca.kt]: why hardcode the useragent?

Comment (choppeh) [reply src/pt/hentaiteca/src/eu/kanade/tachiyomi/extension/pt/hentaiteca/HentaiTeca.kt]: > why hardcode the useragent?

Maybe can be removed, but users will have to change the global UA in the app, as the J2K UA is old and cloudflare blocks it

Comment (choppeh) [reply src/pt/hentaiteca/src/eu/kanade/tachiyomi/extension/pt/hentaiteca/HentaiTeca.kt]: > > why hardcode the useragent?
> 
> Maybe can be removed, but users will have to change the global UA in the app, as the J2K UA is old and cloudflare blocks it

Removed

**Review by AwkwardPeak7 — APPROVED** [review]
