### PR TITLE
Philliascans change to madara

### LINKED ISSUE #7441: Philia Scans Issue with Updating/Migrating
### Source information

Phlia Scans 1.4.6

### Source language

English

### Steps to reproduce

1. Try to update library.
2. Error message: ! Unexpected JSON token at offset 0: Expected start of the object '{', but had '<' instead at path: $
JSON input: <!DOCTYPE html>
<html lang="en.....

Alternative:
1. Try to migrate from Philia Scans to Philia Scans
2. 404 Error, but webview works.

### Expected behavior

Update should proceed normally and migration should return entries if they exist (webview works).

### Actual behavior

Errors as described.

### Mihon/Tachiyomi version

App version: 1.11.0 (standard, ffc1e2d, 70, 2024-10-28T03:12:22Z) Preview build: 0 

### Android version

Android 12

### Other details

Not sure if app or extension issue, I do not understand the errors. Apologies if in the wrong sections.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Closes #7441

 Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by mrtear** [comment]
7441

**Comment by Creepler13** [comment]
Thanks. I coundlt find it, because it thought it was written with 2 Ls

**Review by AwkwardPeak7 — COMMENTED** [review]
are the series urls same? if not then bump `versionId`

**Review by vetleledaal — DISMISSED** [review]

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 1]
```diff
@@ -1,9 +1,37 @@
...
-class PhiliaScans : Iken(
+class PhiliaScans : Madara(
     "Philia Scans",
-    "en",
     "https://philiascans.org",
-)
+    "en",
+    SimpleDateFormat("dd/MMM", Locale.US),
+) {
+    override val versionId: Int = 1
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: This is the default. Was this intentional?
```suggestion
    override val versionId: Int = 2
```

Comment (Creepler13) [reply src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: No. Thought default Was 0

**Review by vetleledaal — APPROVED** [review]
