### PR TITLE
DuaLeoTruyen: Change to HttpSource, update domain

### LINKED ISSUE #14171: Dua Leo Truyen HTTP error 404
### Source information

Dua Leo Truyen 1.4.13

### Source language

Vietnamese

### Steps to reproduce

1. Open the source in Browse 
2. Http error 404 appear
3. Check webview - website loads fine, correct url 

### Expected behavior

After opening the source in browse, usually a list of manga should appear (usually either in order of most popular or latest)

### Actual behavior

Http error 404 show up, webview loads fine.

Note: some previousely added manga still work (can update, load webview and chapter as usual), but some will run into the same http error 404. 

### Mihon/Mihon fork version

Yōkai v1.9.7.4

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FiorenMas**
Closed https://github.com/keiyoushi/extensions-source/issues/14171

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/vi/dualeotruyen/src/eu/kanade/tachiyomi/extension/vi/dualeotruyen/DuaLeoTruyen.kt [hunk 1]
```diff
@@ -6,284 +6,239 @@ import android.widget.Toast
...
-    }
+    private val defaultBaseUrl = "https://dualeotruyensg.com"
+    private val preferences: SharedPreferences = getPreferences()
 
-    private var cachedBaseUrl: String = ""
-    private val SharedPreferences.prefBaseUrl: String get() {
-        return cachedBaseUrl.takeIf(String::isNotBlank)
-            ?: getString(BASE_URL_PREF, defaultBaseUrl)!!.also { cachedBaseUrl = it }
-    }
+    override val baseUrl by lazy { getPrefBaseUrl() }
```
Comment (vetleledaal) [inline src/vi/dualeotruyen/src/eu/kanade/tachiyomi/extension/vi/dualeotruyen/DuaLeoTruyen.kt]: This will require the user to restart the app for the change to apply. Use `var` or use `get()` on `baseUrl`.

File: src/vi/dualeotruyen/src/eu/kanade/tachiyomi/extension/vi/dualeotruyen/DuaLeoTruyen.kt [hunk 2]
```diff
@@ -6,284 +6,239 @@ import android.widget.Toast
...
+                val linkElement = element.selectFirst(".chap_name a")!!
+                setUrlWithoutDomain(linkElement.absUrl("href"))
+                name = linkElement.text()
+                date_upload = parseDate(element.selectFirst(".chap_update")?.text())
+            }
         }
-    }
 
-    override fun imageUrlParse(document: Document) = throw UnsupportedOperationException()
+    private fun parseDate(dateStr: String?): Long = DATE_FORMAT.tryParse(dateStr ?: "")
```
Comment (vetleledaal) [inline src/vi/dualeotruyen/src/eu/kanade/tachiyomi/extension/vi/dualeotruyen/DuaLeoTruyen.kt]: Use `.tryParse` directly. It accepts `String?` directly.

**Review by vetleledaal — APPROVED** [review]
