### PR TITLE
HuntersScans: Fix chapter list

### LINKED ISSUE #9747: A fonte hunter scan está faltando capítulos
### Source information

Hunter scan 1.4. 49

### Source language

Português 

### Steps to reproduce

Image

Está faltando capítulos, que estão presente na scan

Image

### Expected behavior

E esperado que apareça todos os capítulos 

### Actual behavior

Não aparece 

Image

### Mihon/Tachiyomi version

0.18.0

### Android version

15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #9747

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by BlackMember08** [comment]
Hello good morning, could you fix the sussy extension, it was working normally a week ago, but it stopped because the site owners changed the site's loadouts, interfering with the extension.

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt [hunk 1]
```diff
@@ -21,5 +24,29 @@ class HuntersScans : Madara(
 
     override val useLoadMoreRequest = LoadMoreStrategy.Always
 
-    override val useNewChapterEndpoint = true
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        launchIO { countViews(document) }
+
+        val mangaUrl = document.location().removeSuffix("/")
```
Comment (stevenyomi) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]: This initial request seems useless. Rewrite `chapterListRequest()` to get the first page.

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt [hunk 2]
```diff
@@ -21,5 +24,29 @@ class HuntersScans : Madara(
...
+        var page = 1
+        val chapters = mutableListOf<SChapter>()
+        do {
+            val url = xhrChaptersRequest(mangaUrl).url.newBuilder()
+                .addQueryParameter("t", "${page++}")
+                .build()
+
+            val request = xhrChaptersRequest(mangaUrl).newBuilder()
+                .url(url)
+                .build()
```
Comment (stevenyomi) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]: Just spell the request out.

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt [hunk 3]
```diff
@@ -21,5 +24,29 @@ class HuntersScans : Madara(
...
+
+            val xhrResponse = client.newCall(request)
+                .execute()
+                .asJsoup()
+
+            val currentPage = xhrResponse.select(chapterListSelector()).map(::chapterFromElement)
+            chapters += currentPage
+        } while (currentPage.isNotEmpty())
```
Comment (stevenyomi) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]: Nit:

```kotlin
while (true) {
    // ...
    if (isEmpty()) return chapters
    mapTo(chapters, ::chapterFromElement)
}
```

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt [hunk 4]
```diff
@@ -21,5 +24,29 @@ class HuntersScans : Madara(
 
     override val useLoadMoreRequest = LoadMoreStrategy.Always
 
-    override val useNewChapterEndpoint = true
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        launchIO { countViews(document) }
+
+        val mangaUrl = document.location().removeSuffix("/")
+        var page = 1
```
Comment (vetleledaal) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]: To avoid mutable variables, you could probably do something like (this suggestion does not take @stevenyomi 's comments into account):
```kt
override fun chapterListParse(response: Response): List<SChapter> {
    val document = response.asJsoup()
    launchIO { countViews(document) }

    val mangaUrl = document.location().removeSuffix("/")
    return fetchAllChapters(mangaUrl)
}

private tailrec fun fetchAllChapters(
    mangaUrl: String,
    page: Int = 1,
    acc: List<SChapter> = emptyList()
): List<SChapter> {
    val url = xhrChaptersRequest(mangaUrl).url.newBuilder()
        .addQueryParameter("t", page.toString())
        .build()

    val request = xhrChaptersRequest(mangaUrl).newBuilder()
        .url(url)
        .build()

    val xhrResponse = client.newCall(request)
        .execute()
        .asJsoup()

    val currentPage = xhrResponse.select(chapterListSelector()).map(::chapterFromElement)

    return if (currentPage.isEmpty()) {
        acc
    } else {
        fetchAllChapters(mangaUrl, page + 1, acc + currentPage)
    }
}
```

Not tested outside seeing it compile.

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt (hunk 1 above)
Comment (stevenyomi) [reply src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]: Or just override `fetchChapterList() = Observable.fromCallable { ... }`  for convenience.

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt [hunk 5]
```diff
@@ -21,5 +26,19 @@ class HuntersScans : Madara(
 
     override val useLoadMoreRequest = LoadMoreStrategy.Always
 
-    override val useNewChapterEndpoint = true
+    override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> = Observable.just(fetchAllChapters(manga))
```
Comment (stevenyomi) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]:
```suggestion
    override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> = Observable.fromCallable { fetchAllChapters(manga) }
```

File: src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt [hunk 6]
```diff
@@ -21,5 +26,19 @@ class HuntersScans : Madara(
...
+
+    private tailrec fun fetchAllChapters(manga: SManga, page: Int = 1, accumulator: List<SChapter> = emptyList()): List<SChapter> {
```
Comment (stevenyomi) [inline src/pt/huntersscans/src/eu/kanade/tachiyomi/extension/pt/huntersscans/HuntersScans.kt]: Just write a simple `while (true)` loop instead of using `tailrec`. The logic is simple enough.

**Review by stevenyomi — APPROVED** [review]
