### PR TITLE
Fix ZeroTheme

### LINKED ISSUE #9596: Ler Toons 1.4.1 (PT-Br Source) `HTTP 404 Error`
### Source information

Ler Toons 1.4.1

### Source language

Portuguese Brazilian

### Steps to reproduce

HTTP 404 Error.

### Expected behavior

Show content.

### Actual behavior

Don't show content.

Image
Image

### Mihon/Tachiyomi version

Komikku r10138

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #9596

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/zerotheme/src/eu/kanade/tachiyomi/multisrc/zerotheme/ZeroThemeDto.kt [hunk 1]
```diff
@@ -108,7 +108,7 @@ class MangaDto(
             else -> SManga.UNKNOWN
         }
         genre = genres?.joinToString { it.name }
-        url = "/comic/$slug"
+        url = "/$slug"
```
Comment (stevenyomi) [inline lib-multisrc/zerotheme/src/eu/kanade/tachiyomi/multisrc/zerotheme/ZeroThemeDto.kt]: This is breaking old entries from the other derived extension. Try passing the subpath in to `toSManga()` to maintain old behavior. Same for chapters.

Comment (stevenyomi) [reply lib-multisrc/zerotheme/src/eu/kanade/tachiyomi/multisrc/zerotheme/ZeroThemeDto.kt]: Or you should use `slug` itself and throw an error in `mangaDetails` and `chapterList` to ask people to migrate old entries.

Comment (stevenyomi) [reply lib-multisrc/zerotheme/src/eu/kanade/tachiyomi/multisrc/zerotheme/ZeroThemeDto.kt]: If you choose to change the URL format, remove the prefix slash to use the `slug` itself.

File: lib-multisrc/zerotheme/src/eu/kanade/tachiyomi/multisrc/zerotheme/ZeroTheme.kt [hunk 2]
```diff
@@ -61,23 +75,49 @@ abstract class ZeroTheme(
 
     // =========================== Details =================================
 
+    override fun getMangaUrl(manga: SManga) = "$baseUrl/$mangaSubString/${manga.url.substringAfterLast("/")}"
```
Comment (stevenyomi) [inline lib-multisrc/zerotheme/src/eu/kanade/tachiyomi/multisrc/zerotheme/ZeroTheme.kt:78]: Note: This method is called in the UI thread, so it might silently fail if it sends web request through `mangaSubString`.

**Review by stevenyomi — APPROVED** [review]
