### PR TITLE
GenzToons: Actually update domain and cdn url

### LINKED ISSUE #5602: The updated Genz toons not able to load/download chapter images/pages on app
### Source information

1.4.35

### Source language

ENGLISH 

### Steps to reproduce

1. Open a comic on the extension 
2. Open a chapter 
3. Download a chapter 

### Expected behavior

Should show or download chapters

### Actual behavior

Unable to show download images even if pages download the show no page found
Screenshot_20241020_020154_eu kanade tachiyomi j2k
Screenshot_20241020_021007_eu kanade tachiyomi j2k

### Mihon/Tachiyomi version

1.7.4

### Android version

14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #5602 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/suryascans/src/eu/kanade/tachiyomi/extension/en/suryascans/GenzToons.kt [hunk 1]
```diff
@@ -42,6 +44,16 @@ class GenzToons :
...
+        val script = document.select("#pages > script").joinToString("\n") { it.data() }
+        val realCdnUrl = CDN_URL_REGEX.find(script)?.groupValues?.get(1)?.takeIf { it.startsWith("http") }
+            ?: "$baseUrl/uploads/"
+        return document.select("#pages > img")
+            .mapIndexed { index, img ->
+                Page(index, document.location(), realCdnUrl + img.attr("uid"))
+            }
+    }
+
     override fun setupPreferenceScreen(screen: PreferenceScreen) {
```
Comment (choppeh) [inline src/en/suryascans/src/eu/kanade/tachiyomi/extension/en/suryascans/GenzToons.kt:57]: What do you think about moving these settings(_**Display paid chapters**_) to the theme. So some issues related to the paid chapter can be closed.

Like this one: #4999

Comment (bapeey) [reply src/en/suryascans/src/eu/kanade/tachiyomi/extension/en/suryascans/GenzToons.kt:57]: yeah but should be another PR imo

**Review by AwkwardPeak7 — APPROVED** [review]
