### PR TITLE
Bakai: Fix path segment

### LINKED ISSUE #7313: Bakai extension error HTTP 404
### Source information

Bakai 1.4.6

### Source language

Portuguese

### Steps to reproduce

When you open the extension, only an HTTP 404 error message appears.

Image

### Expected behavior

Quando abrisse a extensão deveria aparecer os mangás do site

### Actual behavior

Não aparece os mangás para ler

### Mihon/Tachiyomi version

Mihon 0.17.1

### Android version

Android 14

### Other details

O problema da extensão é que não consigo ler novos mangás, mas os mangás que já estavam na minha biblioteca continuam funcionando 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #7313

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/bakai/src/eu/kanade/tachiyomi/extension/pt/bakai/Bakai.kt [hunk 1]
```diff
@@ -189,7 +207,59 @@ class Bakai : ParsedHttpSource() {
...
+    private fun findPathSegment(chain: Interceptor.Chain, request: Request): String {
+        return chain.proceed(GET(baseUrl, headers)).use {
+            val document = it.asJsoup()
+            val pathSegments = request.url.pathSegments
+            val absUrl = when {
+                pathSegments.contains(popularPathSegment) ->
+                    document.selectFirst(popularMangaNextPageSelector())?.absUrl("href")
+
+                pathSegments.contains(searchPathSegment) ->
+                    document.selectFirst("#elSearch form")?.absUrl("action")
```
Comment (vetleledaal) [inline src/pt/bakai/src/eu/kanade/tachiyomi/extension/pt/bakai/Bakai.kt:243]: This form exists on other pages as well (manga details). Would it be beneficial to check every html response for the same form? You could skip the request to `baseUrl` in some cases.

Might be more effort than what it's worth.

Comment (choppeh) [reply src/pt/bakai/src/eu/kanade/tachiyomi/extension/pt/bakai/Bakai.kt:243]: > You could skip the request to baseUrl in some cases.

This interceptor will only be triggered when the home path or the search path is outdated (404/status code != 200) and when requests originate from popularMangaRequest and searchMangaRequest.

> Would it be beneficial to check every html response for the same form?

It stores the last valid path in preferences, so it will only be requested if the path changes.

**Review by AwkwardPeak7 — APPROVED** [review]
