### PR TITLE
SussyToons: Fix chapters and pages

### LINKED ISSUE #7496: SussyToons: Missing Pages
### Source information

SussyToons 1.4.50

### Source language

Português

### Steps to reproduce

1. Install Extension

2. Search: "O Tempo do Renascimento"
https://www.sussytoons.wtf/obra/6067/o-tempo-do-renascimento

Chapter 1 still works, but when you go to chapters 2,3 and 4, there is no image, just the logo

### Expected behavior

Missing Chapter

### Actual behavior

Missing Chapter

### Mihon/Tachiyomi version

TachiyomiYS 1.11.0

### Android version

14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #8799: Sussy Toons: Nenhum capítulo encontrado / No chapters found
### Source information

Sussy Toons 1.4.55

### Source language

Português (Brasil)

### Steps to reproduce

Image
Image
Image

### Expected behavior

Image

Image

### Actual behavior

Image
Image

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 13

### Other details

The "Recent" tab is gone and the chapters are gone too.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes  #8799
Closes  #7496

T**here's no need to increase the version in lib-mult, I just moved the code**

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt [hunk 1]
```diff
@@ -25,6 +32,38 @@ class ResultDto<T>(
...
         .map(MangaDto::toSManga)
 
+    fun toSChapterList(): List<SChapter> = (results as WrapperChapterDto)
+        .chapters.map {
+            SChapter.create().apply {
+                name = it.name
+                it.chapterNumber?.let {
+                    chapter_number = it
+                }
+                url = "/capitulo/${it.id}"
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:42]: You are changing behavior here. Should retain `setUrlWithoutDomain()`.

Comment (choppeh) [reply lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShitDto.kt:42]: I can't use setUrlWithoutDomain because it's not available in the Dto context, it's a function of the HttpSource class

> You are changing behavior here. Should retain `setUrlWithoutDomain()`.

**Review by vetleledaal — APPROVED** [review]
