### PR TITLE
Manga-TR: Add filter support and fix the image could not be loaded error

### LINKED ISSUE #9657: Manga-TR: `The image could not be loaded` / 404 error in WebView
### Source information

Manga-TR 1.4.14

### Source language

Turkish

### Steps to reproduce

1- I open the app.
2- I open any manga from the Manga-TR extension.
3- When I open it from the app, it doesn't load the images.
4- When I open it from WebView, the same manga loads the images.

### Expected behavior

Image => Manga opened in the application

Image => Manga opened in the application

Image => Webview view from within the manga

Image => opened from webview view in the first image

### Actual behavior

I apologize for the poor explanation and english.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by hasanturkylmz**
Closes: #9657

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 1]
```diff
@@ -32,24 +36,107 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
+            AgeRestrictionFilter(),
+            ContentTypeFilter(),
+            SpecialTypeFilter(),
+        )
+
+        if (cachedGenres.isNotEmpty()) {
+            baseFilters += FMReader.GenreList(cachedGenres)
+        } else {
+            baseFilters += Filter.Header("Türleri yüklemek için 'Sıfırla' düğmesine basın")
+            baseFilters += FMReader.GenreList(emptyList())
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]: Why add an empty one?

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 2]
```diff
@@ -32,24 +36,107 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
+        val listEndpoint = if (page <= 1) "$baseUrl/manga-list.html" else "$baseUrl/$requestPath"
+        val url = listEndpoint.toHttpUrl().newBuilder()
+        if (page > 1) {
+            url.addQueryParameter("listType", "pagination")
+            url.addQueryParameter("page", page.toString())
+        }
+
+        val genreFilter = (if (filters.isEmpty()) getFilterList() else filters)
+            .filterIsInstance<FMReader.GenreList>()
+            .firstOrNull()
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]: Use `firstInstanceOrNull()` provided by the `core` module. Same below.

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 3]
```diff
@@ -32,24 +36,107 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
+        }
+
+        val listEndpoint = if (page <= 1) "$baseUrl/manga-list.html" else "$baseUrl/$requestPath"
+        val url = listEndpoint.toHttpUrl().newBuilder()
+        if (page > 1) {
+            url.addQueryParameter("listType", "pagination")
+            url.addQueryParameter("page", page.toString())
+        }
+
+        val genreFilter = (if (filters.isEmpty()) getFilterList() else filters)
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]: Is there any special state in the default filter list that prevents you from using an empty one?

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 4]
```diff
@@ -32,24 +36,107 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
     override fun searchMangaParse(response: Response): MangasPage {
-        val mangas = response.use { it.asJsoup() }
-            .select("div.row a[data-toggle]")
-            .filterNot { it.siblingElements().text().contains("Novel") }
-            .map(::searchMangaFromElement)
-
-        return MangasPage(mangas, false)
+        val path = response.request.url.encodedPath
+        return if (path.contains("/arama.html")) {
+            val mangas = response.use { it.asJsoup() }
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]:
```suggestion
            val mangas = response.asJsoup()
```

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 5]
```diff
@@ -116,4 +203,92 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
+            element.hasAttr("src") -> element.attr("abs:src")
+            element.hasAttr("data-original") -> element.attr("abs:data-original")
+            else -> null
+        }
+    }
+
+    // Simple pageListParse - relies on the selector above
+    override fun pageListParse(document: Document): List<Page> {
+        return document.select(pageListImageSelector).mapIndexed { i, img ->
+            Page(i, document.location(), getImgAttr(img))
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]:
```suggestion
            Page(i, imageUrl = getImgAttr(img))
```

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 6]
```diff
@@ -116,4 +203,92 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
+                ?: doc.selectFirst("div:has(:matchesOwn(Tür Seçiniz))")
+            val anchors = when {
+                container != null -> container.select("a")
+                else -> doc.select("a[href*=manga-list], a[href*=genre], a[href*=tur]")
+            }
+            val items = anchors.map { it.text().trim() }.filter { it.length > 1 }.distinct()
+            if (items.isNotEmpty()) {
+                cachedGenres = items.map { name -> FMReader.Genre(name, name.replace(' ', '+')) }
+            }
+        }.onFailure { }
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]: Use a plain `try {} catch (_: Throwable) {}` block.

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 7]
```diff
@@ -116,4 +203,92 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
+    // Simple pageListParse - relies on the selector above
+    override fun pageListParse(document: Document): List<Page> {
+        return document.select(pageListImageSelector).mapIndexed { i, img ->
+            Page(i, document.location(), getImgAttr(img))
+        }
+    }
+
+    // =========================== List Parse ===========================
+    override fun popularMangaParse(response: Response): MangasPage {
+        ensureGenresLoaded()
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]: There's no reason calling `ensureGenresLoaded()` here.

You should instead try parsing the genres from the `response` if possible instead of sending another request.

File: src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt [hunk 8]
```diff
@@ -116,4 +203,92 @@ class MangaTR : FMReader("Manga-TR", "https://manga-tr.com", "tr") {
...
+        return super.popularMangaParse(response)
+    }
+
+    private fun ensureGenresLoaded() {
+        if (cachedGenres.isNotEmpty()) return
+        runCatching {
+            val doc = client.newCall(GET("$baseUrl/manga-list.html", headers)).execute().asJsoup()
```
Comment (stevenyomi) [inline src/tr/mangatr/src/eu/kanade/tachiyomi/extension/tr/mangatr/MangaTR.kt]: This is called from `getFilterList()` so `execute()` might block the UI rendering thread. You should use `thread {}` to offload it to a background thread.

**Review by stevenyomi — APPROVED** [review]
