### PR TITLE
Fix BlackoutComics selectors

### LINKED ISSUE #1402: BlackoutComic (pt) - thumbnail strange
### Source information

Blackout Comics - 1.4.1

### Source language

português 

### Steps to reproduce

1 - install the extension
2 - open

### Expected behavior

I can't post the image for this reason, you have to look at the extension

I can also be banned.

### Actual behavior

I can't post the image for this reason, you have to look at the extension

I can also be banned.

### Mihon/Tachiyomi version

0.16.3

### Android version

Android 13

### Other details

I recommend that you be alone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #1402 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by choppeh** [comment]
The source added additional HTML tags to "block" data extraction.  And possibly other similar bugs will be opened up because of other changes.

**Review by AwkwardPeak7 — APPROVED** [review]

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 1]
```diff
@@ -48,8 +48,8 @@ class BlackoutComics : ParsedHttpSource() {
 
     override fun popularMangaFromElement(element: Element) = SManga.create().apply {
         setUrlWithoutDomain(element.attr("href"))
-        thumbnail_url = element.selectFirst("img")?.absUrl("src")
-        title = element.selectFirst("p, span.text-comic")?.text() ?: "Manga"
+        thumbnail_url = element.selectFirst("img:not(.hidden)")?.absUrl("src")
+        title = element.selectFirst("p:not(.hidden), span.text-comic")?.text() ?: "Manga"
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]:
```suggestion
        title = element.selectFirst("p:not(.hidden), span.text-comic")!!.text()
```

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 2]
```diff
@@ -97,8 +97,8 @@ class BlackoutComics : ParsedHttpSource() {
     // =========================== Manga Details ============================
     override fun mangaDetailsParse(document: Document) = SManga.create().apply {
         val row = document.selectFirst("section > div.container > div.row")!!
-        thumbnail_url = row.selectFirst("img")?.absUrl("src")
-        title = row.selectFirst("div.trailer-content > h2")?.text() ?: "Manga"
+        thumbnail_url = row.selectFirst("img:not(.hidden)")?.absUrl("src")
+        title = row.selectFirst("div.trailer-content > h2:not(.hidden)")?.text() ?: "Manga"
```
Comment (AwkwardPeak7) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]:
```suggestion
        title = row.selectFirst("div.trailer-content > h2:not(.hidden)")!!.text()
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
