### PR TITLE
ArazNovel: fix chapterlist parse

### LINKED ISSUE #5508: Chaphters not loading
### Source information

ArazNovel tr.araznovel 1.4.39

### Source language

Turkish

### Steps to reproduce

1.Download that source
2.Enter one of the webtoon

### Expected behavior

Chapters Must Be Shown

### Actual behavior

The message "Chapters not found" appears.
image
image

### Mihon/Tachiyomi version

v1.1.1

### Android version

Windows 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by LefanHu**
closes #5508 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

image
image

### CODE REVIEW

File: src/tr/araznovel/src/eu/kanade/tachiyomi/extension/tr/araznovel/ArazNovel.kt [hunk 1]
```diff
@@ -11,21 +11,12 @@ class ArazNovel : Madara("ArazNovel", "https://www.araznovel.com", "tr", SimpleD
...
-                        .flatten()
-                } else {
-                    xhrDocument.select(chapterListSelector()).map { chapterFromElement(it) }
-                }
-            }
-        }
+        val chapterElements = xhrResponse.asJsoup().select("ul.version-chap li.wp-manga-chapter")
+        return chapterElements.map(::chapterFromElement)
     }
 }
```
Comment (AwkwardPeak7) [inline src/tr/araznovel/src/eu/kanade/tachiyomi/extension/tr/araznovel/ArazNovel.kt]: this is essentially the implementation of `chapterListParse` in the `Madara` class, so remove the override and check.

would also need to set `useNewChapterEndpoint` to true and adjust `chapterListSelector`

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/tr/araznovel/src/eu/kanade/tachiyomi/extension/tr/araznovel/ArazNovel.kt (hunk 1 above)
Comment (LefanHu) [reply src/tr/araznovel/src/eu/kanade/tachiyomi/extension/tr/araznovel/ArazNovel.kt]: turns out they use the old endpoint... and selector is the same....
image

File: src/tr/araznovel/src/eu/kanade/tachiyomi/extension/tr/araznovel/ArazNovel.kt [hunk 2]
```diff
@@ -1,31 +1,12 @@
...
-                } else {
-                    xhrDocument.select(chapterListSelector()).map { chapterFromElement(it) }
-                }
-            }
-        }
-    }
-}
+class ArazNovel : Madara(
+    "ArazNovel",
+    "https://www.araznovel.com",
```
Comment (AwkwardPeak7) [inline src/tr/araznovel/src/eu/kanade/tachiyomi/extension/tr/araznovel/ArazNovel.kt]: remove `www` from domain too

**Review by AwkwardPeak7 — APPROVED** [review]
