### PR TITLE
HiveScans/Toons: Fix PageListParse

### LINKED ISSUE #7531: Hive Toon: No Pages Found
### Source information

Hive Scans 1.4.42

### Source language

English

### Steps to reproduce

1. Click on any story
2. Open any chapter
3. "No Pages Found"

### Expected behavior

The pages should load when you open any chapter.

### Actual behavior

Instead, when you click on a chapter, it instantly kicks you out of that chapter and says "No Pages Found."

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Checklist:

Closes #7531

- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/infernalvoidscans/src/eu/kanade/tachiyomi/extension/en/infernalvoidscans/HiveScans.kt [hunk 1]
```diff
@@ -20,6 +22,14 @@ class HiveScans : Iken(
         }
         .build()
 
+    val PageRegex = Regex("""https://storage.\w+.\w+/public//upload/series/(\w+)/(\w+)/(\d+).webp""")
```
Comment (vetleledaal) [inline src/en/infernalvoidscans/src/eu/kanade/tachiyomi/extension/en/infernalvoidscans/HiveScans.kt]: Is the double slash intentional? Is  that something that should be optional in case they fix it?

Unrelated, but we should really have some kind of helper functions to parse next.js' [RSC](https://github.com/ScriptedAlchemy/rsnext/blob/8f5f0ef141a907d083eedb7c7aca52b04f9d258b/packages/next/src/server/app-render/use-flight-response.tsx#L10).

Comment (bapeey) [reply src/en/infernalvoidscans/src/eu/kanade/tachiyomi/extension/en/infernalvoidscans/HiveScans.kt]: Also regex will fail if the slug of the series contains special characters.

```regex
\\\"images\\\":(\[.*?]).*?nextChapter
``` 
this regex captures the entire array; you will need to unescape and deserialize it.

**Comment by Creepler13** [comment]
Not sure if there is a better way to unescape, but it works.

And just ignore the Force Push, i pressed a button i shouldn't have

**Review by AwkwardPeak7 — APPROVED** [review]
