### PR TITLE
MangaGun: Fix page list parse and update domain

### LINKED ISSUE #10560: Mangagun changeurl
### Source information

Mangagun 1.4.14

### Source language

Japanese

### Source new URL

https://nihonkuni.com/

### Other details

The pages werent being refreshed, but i guess thats because the new link... an error 403 is shown

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AlphaBoom**
Closes #10560 

The original domain will redirect to this new one. It also appears that the website's icon and name have been changed. I'm not entirely sure about the reason for these changes, so I will only update the domain name.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Riztard** [comment]
change the name and the icon as well

**Comment by Riztard** [comment]
also need `override val id = ` 
> Have explicitly kept the id if a source's name or language were changed

File: src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt [hunk 1]
```diff
@@ -11,14 +10,18 @@ import eu.kanade.tachiyomi.util.asJsoup
...
 import java.util.Calendar
 
-private const val DOMAIN = "mangagun.net"
+private const val DOMAIN = "nihonkuni.com"
 
-class MangaGun : FMReader("MangaGun", "https://$DOMAIN", "ja") {
+/**
+ * This plugin is for the website originally named MangaGun(漫画軍), which was later renamed to NihonKuni(日本国). Please do not be confused by the names.
+ */
+class MangaGun : FMReader("NihonKuni", "https://$DOMAIN", "ja") {
```
Comment (Riztard) [inline src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt:22]: i might as well suggest it
```suggestion
class MangaGun : FMReader("NihonKuni", "https://$DOMAIN", "ja") {
// Formerly "MangaGun(漫画軍)"
override val id = 3811800324362294701

File: src/ja/mangagun/build.gradle [hunk 2]
```diff
@@ -2,8 +2,8 @@ ext {
     extName = 'MangaGun'
```
Comment (AwkwardPeak7) [inline src/ja/mangagun/build.gradle]: change the extname too

File: src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt [hunk 3]
```diff
@@ -122,16 +124,21 @@ class MangaGun : FMReader("MangaGun", "https://$DOMAIN", "ja") {
     }
 
     override fun pageListParse(document: Document): List<Page> {
-        val ddosProtect = document.select("title").first()?.text()
+        // I haven't encountered this DDoS protection page in a long time. We can consider removing this logic in the future.
```
Comment (AwkwardPeak7) [inline src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt]: you can remove it now

Comment (Riztard) [reply src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt]: is it possible he havent encountered that because he is using it normally? unless he already tried to do mass download

Comment (AlphaBoom) [reply src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt]: Considering that the original DDoS protection detection logic was based on the title, it has likely become invalid now that the website has been renamed. Therefore, it is indeed acceptable to remove this piece of logic.

**Review by AwkwardPeak7 — APPROVED** [review]
