### PR TITLE
Mangahub (ru): fix popular, latest, pages, author

### LINKED ISSUE #1838: MangaHub (RU): Http error 404
### Source information

Mangahub

### Source language

Russian

### Steps to reproduce

HTTP 404 error in the extension but not on the website
Screenshot_20240312-204955_Mihon
Screenshot_20240312-205003_Mihon

### Expected behavior

The extension should work

### Actual behavior

HTTP Error 404

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #1838

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt [hunk 1]
```diff
@@ -33,23 +33,53 @@ open class Mangahub : ParsedHttpSource() {
     override val supportsLatest = true
 
     override val client: OkHttpClient = network.cloudflareClient.newBuilder()
+        .addInterceptor(::confirmAgeInterceptor)
         .rateLimit(2)
         .build()
 
+    private fun confirmAgeInterceptor(chain: Interceptor.Chain): Response {
```
Comment (AwkwardPeak7) [inline src/ru/mangahub/src/eu/kanade/tachiyomi/extension/ru/mangahub/Mangahub.kt:40]: maybe add a guard against image links so it doesn't try to parse everything

**Review by AwkwardPeak7 — APPROVED** [review]
