### PR TITLE
Kagane: Fix MissingFieldException Error

### LINKED ISSUE #10976: Kagane: MissingFieldException Error when trying to access titles or download chapters
### Source information

Kagane 1.4.3

### Source language

English

### Steps to reproduce

1. Try to access / open any title (if not added yet)

OR

2. Try to download any chapter from titles already previously added

### Expected behavior

1. Should be able to view the title and see the list of chapters

OR

2. Able to download selected chapter

### Actual behavior

Continuous loading if only viewing the title not yet added. Cannot add the selected title.
Image

If I try to download a chapter, this error appears:
Image

### Mihon/Tachiyomi version

Komikku version 1.13.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #10976

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

Also fix Popular and Latest search, removing unnecessary request to get pages count and turn false data saver by default

### CODE REVIEW

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt [hunk 1]
```diff
@@ -31,84 +31,68 @@ class SearchDto(
...
+            desc.append("Associated Name(s):\n\n")
+            alternateTitles.forEach { desc.append("• ${it.title}\n") }
         }
 
-        private fun String.toStatus(): Int {
-            return when (this) {
-                "ONGOING" -> SManga.ONGOING
-                else -> SManga.COMPLETED
-            }
+        author = authors.joinToString { it }
```
Comment (vetleledaal) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: Couldn't you just do this?
```suggestion
        author = authors.joinToString()
```

\* not tested

**Review by vetleledaal — DISMISSED** [review]

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt (hunk 1 above)
Comment (dngonz) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: Yep, maybe I was testing something and I left it there, changed.

**Review by vetleledaal — DISMISSED** [review]

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 2]
```diff
@@ -224,15 +224,15 @@ class Kagane : HttpSource(), ConfigurableSource {
     }
 
     override fun fetchPageList(chapter: SChapter): Observable<List<Page>> {
-        var (seriesId, chapterId) = chapter.url.split(";")
+        var (seriesId, chapterId, pageCount) = chapter.url.split(";")
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:228]: before this, count ; in url and throw exception asking user to refresh chapter list if semicolons count isn't 2. (you added page count to the url, which was not there previously, so old urls in db will have them)

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 3]
```diff
@@ -429,7 +429,7 @@ class Kagane : HttpSource(), ConfigurableSource {
         SwitchPreferenceCompat(screen.context).apply {
             key = DATA_SAVER
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:422]: change the key of the preference as well, to ensure everyone starts with data saver off

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
