### PR TITLE
MangoToons: add login + change keystring

### LINKED ISSUE #12798: Mango toons erro de login
### Source information

Mango toons 1.4.3

### Source language

Portugues

### Steps to reproduce

Colocaram login e senha a obras não estão aparecendo 

### Expected behavior

Image

### Actual behavior

Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes #12798

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/mangotoons/src/eu/kanade/tachiyomi/extension/pt/mangotoons/DecryptMango.kt [hunk 1]
```diff
@@ -8,7 +8,7 @@ import javax.crypto.spec.SecretKeySpec
 object DecryptMango {
 
     private const val SALT = "salt"
-    private const val KEY_STRING = "abmPisXlFjOLVTnYhbYQTpkWJtOGKwVttzLqstfjRBNVaEtQYF"
+    private const val KEY_STRING = "abmPisXlFjOLVTnYhbYQTpkWJtOGKwVttzLqstfjRBNVaEtQYG"
```
Comment (vetleledaal) [inline src/pt/mangotoons/src/eu/kanade/tachiyomi/extension/pt/mangotoons/DecryptMango.kt:11]: Can this be extracted automatically? For example, you can look for any of the known strings:
```
Dados inválidos para descriptografia
Formato de dados criptografados inválido
Dados criptografados contêm caracteres inválidos
Falha na descriptografia - resultado vazio (chave incorreta?)
[ENCRYPTED-FETCH] Erro ao descriptografar:
[ENCRYPTED-FETCH] Dados recebidos (primeiros 100 chars):
Erro ao descriptografar resposta
```

... and backtrack until you find a long enough string. Or just try every string if decryption is cheap enough.

You could prioritize the chunks to look through, I did something similar in [Plot Twist No Fansub](https://redirect.github.com/keiyoushi/extensions-source/blob/fc7ed5da1c3edb37a46603fb38ae6390e9718c7a/src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt#L222), although I'm not sure if all of that applies to NextJS.

**Review by vetleledaal — APPROVED** [review]
