### PR TITLE
Fix Ganma: use new API GraphQL

### LINKED ISSUE #6991: GANMA: 404 on manga refresh
### Source information

GANMA! 1.4.2

### Source language

Japanese

### Steps to reproduce

1. Make sure in webview I'm logged in
2. Try to refresh one of my existing ganma mangas
3. HTTP 404 message pops up, new chapters are not pulled down.

### Expected behavior

Manga is checked for new chapters and pulls them down.

### Actual behavior

HTTP 404 error gets returned instead.

### Mihon/Tachiyomi version

Mihon 0.17.1

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by manti-X**
Closes #6991 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by MikeZeDev** [comment]
may i ask about `.filterNot { it.alias.endsWith("_web", ignoreCase = true) }`. Why do you filter them?

**Comment by manti-X** [comment]
> Why do you filter them?

for some reason I can’t fetch the chapter list for these _web series through the api, even though it should work if I don't use the custom UA. So I just filtered them out, since they’re basically chapters bundled into volumes, and users can just read the proper entry instead

**Comment by manti-X** [comment]
nvm I fixed it

**Comment by manti-X** [comment]
Added afterword page now. I forgot about it

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 1]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+    override fun headersBuilder() = super.headersBuilder()
+        .add("X-From", "$baseUrl/web")
+        .add("Content-Type", "application/json;charset=UTF-8")
+        .add("Accept", "application/json, text/plain, */*")
 
-    override fun popularMangaRequest(page: Int) =
-        when (page) {
-            1 -> GET("$baseUrl/api/1.0/ranking", headers)
-            else -> GET("$baseUrl/api/1.1/ranking?flag=Finish", headers)
+    private val json: Json by injectLazy()
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt]: use `response.parseAs` from `keiyoushi.utils`

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 2]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+    private var lastSearchCursor: String? = null
+    private var lastFilterCursor: String? = null
+
+    // https://ganma.jp/web/_next/static/chunks/app/layout-98772c0967d4bfb7.js
+    // Hashes to bypass OnlyPersistedQueryIsAllowed
+    private fun fetchAndParseHashes(): Map<String, String> {
+        val mainPage = client.newCall(GET("$baseUrl/web", headers)).execute()
+        val document = mainPage.asJsoup()
+
+        val mainScriptUrl = document.select("script[src*=/app/layout-]")
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt]: use `selectFirst` if you want the first one, or explicit index. `select().attr` can be ambigious when it select multiple elements.

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 3]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+            .firstOrNull { it.name == "PLAY_SESSION" }
+
+        val finalHeaders = headersBuilder().apply {
+            if (useAppHeaders) {
+                set("User-Agent", "GanmaReader/9.9.1 Android")
+            } else {
+                set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36")
+            }
+            if (sessionCookie != null) {
+                add("Cookie", sessionCookie.toString())
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt]: app will load the cookies itself, no need for this here

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 4]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+        val hash = hashes[operationName] ?: throw Exception("Could not find hash for operation: $operationName")
+
+        val sessionCookie = client.cookieJar.loadForRequest(baseUrl.toHttpUrl())
+            .firstOrNull { it.name == "PLAY_SESSION" }
+
+        val finalHeaders = headersBuilder().apply {
+            if (useAppHeaders) {
+                set("User-Agent", "GanmaReader/9.9.1 Android")
+            } else {
+                set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36")
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt:78]: is hardcoding the useragent necessary? just use the app provided one (set in `super.headersBuilder` so will be there)

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 5]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+            }
+            if (sessionCookie != null) {
+                add("Cookie", sessionCookie.toString())
+            }
+        }.build()
+
+        val payload = buildJsonObject {
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt]: consider using Serializable classes with templates, you can put specific variable classes in place of T.

```kt
@Serializable
class Payload<T>(
    val operationName: String,
    val variables: T,
    val extensions: Extensions
) {
    @Serializable
    class Extensions(
        val persistedQuery: PersistedQuery
    ) {
        @Serializable
        class PersistedQuery(
            val version: Int,
            val sha256Hash: String
        )
    }
}
```

p.s if you feel this may end up being too complex/difficult to properly implement then you can dismiss this.

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 6]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+                }
+            }
+            putJsonObject("extensions") {
+                putJsonObject("persistedQuery") {
+                    put("version", 1)
+                    put("sha256Hash", hash)
+                }
+            }
         }
+        val requestBody = payload.toString().toRequestBody("application/json; charset=utf-8".toMediaType())
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt]: use `.toJsonString` from `keiyoushi.utils` instead of `.toString`

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 7]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+        }
+        return graphQlRequest(operationName, variables, useAppHeaders = true)
     }
 
-    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request =
-        throw UnsupportedOperationException()
+    override fun searchMangaParse(response: Response): MangasPage {
+        val requestBody = response.request.body
+        val requestBodyString = Buffer().use { requestBody?.writeTo(it); it.readUtf8() }
+        val operationName = json.parseToJsonElement(requestBodyString).jsonObject["operationName"]?.jsonPrimitive?.content
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt]: you can parse to JsonObject directly with `keiyoushi.utils.parseAs`
`response.parseAs<JsonObject>()`

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 8]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+        title = this@toSManga.title
+        thumbnail_url = updateImageUrlWidth(this@toSManga.todaysJacketImageURL ?: this@toSManga.rectangleWithLogoImageURL)
+    }
 
-    protected open fun realMangaDetailsRequest(manga: SManga) =
-        GET("$baseUrl/api/1.0/magazines/web/${manga.url.alias()}", headers)
+    override fun mangaDetailsRequest(manga: SManga): Request = GET("$baseUrl/web/magazine/${manga.url}", headers)
 
-    override fun chapterListRequest(manga: SManga) = realMangaDetailsRequest(manga)
+    override fun fetchMangaDetails(manga: SManga): Observable<SManga> {
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt]: just put api request in `mangaDetailsRequest` and webview url in `getMangaUrl`. no need to override this.

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt [hunk 9]
```diff
@@ -23,91 +34,338 @@ class Ganma : HttpSource() {
...
+                hasNextPage = data.pageInfo.hasNextPage
+                cursor = data.pageInfo.endCursor
+            }
+
+            chapters.mapIndexed { index, chapter ->
+                SChapter.create().apply {
+                    url = "${manga.url}/${chapter.storyId}"
+                    name = (chapter.title + chapter.subtitle?.let { " $it" }.orEmpty()).trim()
+                    date_upload = chapter.contentsRelease
+                    chapter_number = (chapters.size - index).toFloat()
```
Comment (AwkwardPeak7) [inline src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt:267]: if chapter names have a parsable number, then avoid putting index as chapter number

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt (hunk 4 above)
Comment (manti-X) [reply src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt:78]: yes, you need a desktop UA to read the web entries. Default app UA doesn't work.

File: src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt (hunk 9 above)
Comment (manti-X) [reply src/ja/ganma/src/eu/kanade/tachiyomi/extension/ja/ganma/Ganma.kt:267]: with regex or isDigit might be possible from the title, e.g. "title": "第15話", but not every title has a number, e.g. "title": "休載特別編" and regex might break if they change it

**Review by AwkwardPeak7 — APPROVED** [review]
