### PR TITLE
UnionMangas: Fix deep linking

### LINKED ISSUE #3150: Union Mangas - Deep Linking not working
### Source information

Union Mangas 1.4.2

### Source language

All

### Steps to reproduce

- Open webpage on the browser
- Click in manga title

### Expected behavior

Open Mihon

### Actual behavior

The warning about the extension is showed

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes  #3150

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/unionmangas/src/eu/kanade/tachiyomi/extension/all/unionmangas/UnionMangas.kt [hunk 1]
```diff
@@ -171,14 +171,12 @@ class UnionMangas(private val langOption: LanguageOption) : HttpSource() {
...
-            return client.newCall(GET("$baseUrl/${langOption.infix}/$mangaUrl", headers))
+        if (query.startsWith(SEARCH_PREFIX)) {
+            val url = "$baseUrl/${langOption.infix}/${query.substringAfter(SEARCH_PREFIX)}"
+            return client.newCall(GET(url, headers))
                 .asObservableSuccess().map { response ->
-                    val manga = mangaDetailsParse(response).apply {
-                        url = mangaUrl
-                    }
-                    MangasPage(listOf(manga), false)
+                    val mangas = try { listOf(mangaDetailsParse(response)) } catch (_: Exception) { emptyList() }
```
Comment (AwkwardPeak7) [inline src/all/unionmangas/src/eu/kanade/tachiyomi/extension/all/unionmangas/UnionMangas.kt:178]: no need to catch exception

File: src/all/unionmangas/src/eu/kanade/tachiyomi/extension/all/unionmangas/UnionMangasDto.kt [hunk 2]
```diff
@@ -116,7 +116,7 @@ class MangaDetailsDto(
 
     val thumbnailUrl get() = "${UnionMangas.apiUrl}$_thumbnailUrl"
     val genres get() = _genres.joinToString { it.name }
-    val status get() = toSMangaStatus(_status.first().name)
+    val status get() = if (_status.isNotEmpty()) toSMangaStatus(_status.first().name) else SManga.UNKNOWN
```
Comment (AwkwardPeak7) [inline src/all/unionmangas/src/eu/kanade/tachiyomi/extension/all/unionmangas/UnionMangasDto.kt]: can do `_status.firstOrNull() ?: ""` which would make the function return unknown anyway

File: src/all/unionmangas/src/eu/kanade/tachiyomi/extension/all/unionmangas/UnionMangas.kt (hunk 1 above)
Comment (choppeh) [reply src/all/unionmangas/src/eu/kanade/tachiyomi/extension/all/unionmangas/UnionMangas.kt:178]: > no need to catch exception

When the  deep link is used, all languanges are requested, but the Source returns sucess (200, Even if it can't find anything) and throws an exception in the parse content

**Review by AwkwardPeak7 — APPROVED** [review]
