### PR TITLE
fix(bakamh): failed to bypass cloudflare

### LINKED ISSUE #9438: Baka Manhua: `Failed to bypass Cloudflare`
### Source information

Baka Manhua 1.4.43

### Source language

Chinese - 中文

### Steps to reproduce

Baka Manhua cannot be searched/viewed

### Expected behavior

should be opening the latest chapter

### Actual behavior

There is an error, but when I check the webview, I can use the connection webpage normally

Image

### Mihon/Tachiyomi version

mihon 0.18.0

### Android version

Android 15

### Other details

Yesterday's update to 1.4.43 worked fine, but this afternoon there was the same problem as before.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by marioplus**
- Add domain configuration supporting custom URLs
- Implement Sec-CH-UA customization with default/custom toggle
- Create preferences interface with domain/Sec-CH-UA controls
- Integrate random user agent library for better compatibility

Closes: #9438

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+    private const val PS_KEY_DOMAIN_OVERRIDE = "$PS_KEY_DOMAIN::OVERRIDE"
+
+    private const val PS_KEY_USE_DEFAULT_SEC_CH_UA = "$PS_KEY_ROOT::USE_DEFAULT_SEC_CH_UA"
+
+    private const val PS_KEY_CUSTOM_SEC_CH_UA = "$PS_KEY_ROOT::CUSTOM_SEC_CH_UA"
+
+    private const val PS_KEY_CUSTOM_SEC_CH_UA_DEFAULT = "$PS_KEY_CUSTOM_SEC_CH_UA::DEFAULT"
+    private const val PS_KEY_CUSTOM_SEC_CH_UA_OVERRIDE = "$PS_KEY_CUSTOM_SEC_CH_UA::OVERRIDE"
+
+    const val DEFAULT_DOMAIN = "https://bakamh.com"
```
Comment (AwkwardPeak7) [inline src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt:17]: does the site need domain override?

File: src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+
+        return httpUrl.newBuilder()
+            .scheme("https")
+            .host(httpUrl.host)
+            .build()
+            .toString()
+            .removeSuffix("/")
+    }
+
+    internal fun SharedPreferences.secChUa(): String {
```
Comment (AwkwardPeak7) [inline src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt]: perhaps it would be better to generate this from the app provided useragent instead of a preference?

File: src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt (hunk 1 above)
Comment (marioplus) [reply src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt:17]: some domain provided by the website do not require a proxy.

File: src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt (hunk 2 above)
Comment (marioplus) [reply src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt]: how to obtain mihon's UA settings?

Comment (marioplus) [reply src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt]: use Interceptor to extract UA from the client and parse it.

Comment (vetleledaal) [reply src/zh/bakamh/src/eu/kanade/tachiyomi/extension/zh/bakamh/BakamhPreferences.kt]: Or just read it from `super.headersBuilder`

https://github.com/keiyoushi/extensions-source/blob/37799ab5c6520b093c702342b3d788cc687b409b/src/all/qtoon/src/eu/kanade/tachiyomi/extension/all/qtoon/QToon.kt#L257-L259

**Review by AwkwardPeak7 — APPROVED** [review]
