### PR TITLE
Hiperdex: Fix http 403 and blocked in WebView

### LINKED ISSUE #11579: HipercooL: `HTTP 403` error
### Source information

HipercooL.1.4.46

### Source language

Português Brasil

### Steps to reproduce

Toda vez que eu tento ler uma obra parece um error HTTP403

### Expected behavior

Nenhum

### Actual behavior

Nenhuma

### Mihon/Tachiyomi version

0.19.3

### Android version

Android15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11690: Hiperdex: `HTTP 403` error
### Source information

Hiperdex 1.4.67

### Source language

English

### Steps to reproduce

1. Click browse -> Sources
2. Click on Hiperdex extension

### Expected behavior

The list viewed normally

### Actual behavior

No list acquired

### Mihon/Tachiyomi version

Komikku 1.13.3

### Android version

Android 15 (LineageOS 22)

### Other details

Opened the webview.. This happened..

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Closes #11690
Closes #11579

Aside from the issue with Cloudflare, they're blocking requests that contain `?m_orderby=`

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by BlackMember08** [comment]
@felipegangorra @FelipeGFA  This same problem occurs in the remanga extensions and free manga, so I mentioned you so you can take a look, as this might be a solution. Thanks for your voice-over efforts and the support of the other contributors.

File: src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/ClearanceInterceptor.kt [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+                .build()
+
+            return newResponse
+        }
+        return response
+    }
+
+    companion object {
+        private val ERROR_CODES = listOf(403, 503)
+        private val SERVER_CHECK = arrayOf("cloudflare-nginx", "cloudflare")
```
Comment (vetleledaal) [inline src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/ClearanceInterceptor.kt]: Do you even need this check? It's already scoped to this extension.

Also, prefer using the documented [`Cf-Ray`](https://developers.cloudflare.com/fundamentals/reference/http-headers/#cf-ray-1) header, or if you specifically want to limit it to challenge pages you can use [`Cf-Mitigated`](https://developers.cloudflare.com/cloudflare-challenges/challenge-types/challenge-pages/detect-response/).

Comment (bapeey) [reply src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/ClearanceInterceptor.kt]: Tried with `Cf-Mitigated` but its not appearing in the response, so will use `Cf-Ray` instead

**Review by vetleledaal — APPROVED** [review]
