### PR TITLE
ru/AComics: Fix NPEs

### LINKED ISSUE #935: AComics: NullPointerException when refreshing manga
### Source information

AComics 1.4.3

### Source language

Russian

### Steps to reproduce

1. Open some comics from acomics.ru
2. Try update information
3. 
Screenshot_2024-02-02-21-56-09-436_eu kanade tachiyomi sy
Screenshot_2024-02-02-21-56-12-446_eu kanade tachiyomi sy

### Expected behavior

I can read comics 

### Actual behavior

I can't read comics 

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

12 SKQ1.211006.001

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Claudemirovsky**
Closes #935

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt [hunk 1]
```diff
@@ -22,177 +22,172 @@ class AComics : ParsedHttpSource() {
...
-            val url = response.request.url.toString().split("/about")[0].split(baseUrl)[1]
-            chapter.url = "$url/$index"
-            res.add(chapter)
+        val doc = response.asJsoup()
+        val count = doc
+            .selectFirst("p:has(b:contains(Количество выпусков:))")!!
+            .ownText()
+            .toInt()
+
+        val comicPath = doc.location().substringAfter(baseUrl).substringBefore("/about")
```
Comment (stevenyomi) [inline src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt]: Avoid using `baseUrl` since the site might redirect to a new domain in the future.

**Review by stevenyomi — CHANGES_REQUESTED** [review]

**Review by stevenyomi — APPROVED** [review]
