### PR TITLE
Fix AstralManga for new site

### LINKED ISSUE #13266: New Astral-Manga website
### Source information

Astral-Manga 1.4.46

### Source language

French

### Steps to reproduce

Open Astral-Manga in Extensions

### Expected behavior

shows a list of manhwa/manga to read.

### Actual behavior

Error HTTP 404.
This is because they changed the structure of the new site. 

### Mihon/Tachiyomi version

Mihon 0.19.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Nyantad**
Closes #13266 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt [hunk 1]
```diff
@@ -1,9 +1,525 @@
...
+        return GET(url, headers)
+    }
+
+    override fun searchMangaParse(response: Response): MangasPage = parseMangaApiResponse(response)
+
+    override fun getFilterList() = getFilters()
+
+    // ========================== Details ==========================
+
+    override fun mangaDetailsRequest(manga: SManga): Request = GET(baseUrl + manga.url, headers)
```
Comment (AwkwardPeak7) [inline src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt]: fetch the `text/x-component` response directly by adding `rsc: 1` header

File: src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt [hunk 2]
```diff
@@ -1,9 +1,525 @@
...
+        val normalized = normalizeRscData(rawRsc)
+
+        val mangaUuid = url.substringAfter("/manga/").substringBefore("/").substringBefore("?")
+        val mangaContext = findMangaContext(normalized, mangaUuid)
+        return SManga.create().apply {
+            this.url = url.removePrefix(baseUrl)
+
+            title = (mangaContext?.let { FIELD_TITLE_REGEX.find(it)?.groupValues?.get(1) })
+                ?: document.selectFirst("main h1")?.text()?.trim()
+                ?: "Unknown"
```
Comment (AwkwardPeak7) [inline src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt]: title is mandatory

File: src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt [hunk 3]
```diff
@@ -1,9 +1,525 @@
...
+     * specific manga's JSON block using its UUID from the URL.
+     */
+    private fun parseMangaDetailsFromRsc(document: Document, url: String): SManga {
+        val rawRsc = extractRscData(document)
+        val normalized = normalizeRscData(rawRsc)
+
+        val mangaUuid = url.substringAfter("/manga/").substringBefore("/").substringBefore("?")
+        val mangaContext = findMangaContext(normalized, mangaUuid)
+        return SManga.create().apply {
+            this.url = url.removePrefix(baseUrl)
```
Comment (AwkwardPeak7) [inline src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt]: use `setUrlWithoutDomain`

File: src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt [hunk 4]
```diff
@@ -1,9 +1,525 @@
...
+    /**
+     * Parse manga details from RSC data on the detail page.
+     * The RSC data contains all manga, so we scope extraction to the
+     * specific manga's JSON block using its UUID from the URL.
+     */
+    private fun parseMangaDetailsFromRsc(document: Document, url: String): SManga {
+        val rawRsc = extractRscData(document)
+        val normalized = normalizeRscData(rawRsc)
+
+        val mangaUuid = url.substringAfter("/manga/").substringBefore("/").substringBefore("?")
```
Comment (AwkwardPeak7) [inline src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt]: use `httpUrl.pathsegment` to extract it

File: src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt [hunk 5]
```diff
@@ -1,9 +1,525 @@
...
+        private val FIELD_TEAMS_REGEX = Regex("\"teams\":\\[(.*?)\\]")
+        private val FIELD_PUBLISH_DATE_REGEX = Regex("\"publishDate\":\"(.*?)\"")
+
+        private val NAME_REGEX = Regex("\"name\":\"(.*?)\"")
+        private val FIELD_TITLE_REGEX = Regex(""""title"\s*:\s*"([^"]+)"""")
+        private val FIELD_DESCRIPTION_REGEX = Regex(""""description"\s*:\s*"([^"]+)"""")
+        private val FIELD_STATUS_REGEX = Regex(""""status"\s*:\s*"([^"]+)"""")
+        private val FIELD_TYPE_REGEX = Regex(""""type"\s*:\s*"([^"]+)"""")
+        private val FIELD_ID_REGEX = Regex(""""id"\s*:\s*"([^"]+)"""")
+    }
```
Comment (AwkwardPeak7) [inline src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt]: perhaps wait for https://github.com/keiyoushi/extensions-source/pull/13508 for helper methods to extract from nextjs/rsc

Comment (Nyantad) [reply src/fr/astralmanga/src/eu/kanade/tachiyomi/extension/fr/astralmanga/AstralManga.kt]: Yeah just waiting for the #13508 to merge to make the change

**Comment by Nyantad** [comment]
Should be good

**Review by AwkwardPeak7 — APPROVED** [review]
