### PR TITLE
SlimeRead: Fix popularManga

### LINKED ISSUE #4855: Slime Read (PT-Br Source) Error HTTP 404. PopularManga URL has been removed.
### Source information

SlimeRead 1.4.12

### Source language

Portuguese Brazilian 

### Steps to reproduce

When entering the source, an HTTP 404 error appears.

Screenshot_2024-08-30-14-18-16-603_app mihon

### Expected behavior

Enter and see the contents of the source.

### Actual behavior

HTTP error 404 appears.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes  #4855

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt [hunk 1]
```diff
@@ -45,6 +47,7 @@ class SlimeRead : HttpSource() {
         network.cloudflareClient.newBuilder()
             .rateLimitHost(baseUrl.toHttpUrl(), 2)
             .rateLimitHost(apiUrl.toHttpUrl(), 1)
+            .rateLimit(3)
```
Comment (AwkwardPeak7) [inline src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt]: why add additional ratelimit over ratelimithost?

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt (hunk 1 above)
Comment (choppeh) [reply src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt]: > why add additional ratelimit over ratelimithost?

CDN links. Maybe it's not necessary?

Comment (AwkwardPeak7) [reply src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt]: this will apply double rate limit over baseurl/apiurl so remove those ratelimits if needed

**Review by AwkwardPeak7 — APPROVED** [review]
