### PR TITLE
AnimeXNovel: Fix chapter list

### LINKED ISSUE #9715: AnimeXNovel: `No chapters found` error
### Source information

animexnovel-v1.4.12

### Source language

Portugues

### Steps to reproduce

1- I open the app
2- I go to the browser
3- I click on animexnovel
4- I click on any manga in the list
5- I drag to update the chapters

### Expected behavior

it should update and show the new chapters

### Actual behavior

When you update the chapters, the message "no chapter found" appears.

### Mihon/Tachiyomi version

TachiyomeSY 1.12.0

### Android version

android 14

### Other details

I have already accessed the source/site via mobile and computer and on the animexnovel website there are already new chapters, but the app is unable to access them.

In this case, the manga I took the screenshot of is: Death March Kara Hajimaru Isekai Kyousoukyoku
In the app it's still on chapter 123, but on the website it's on 127.

obs: There are times when I access the site at different times and it shows up to chapter 127, or 80 or 40. I don't know why it keeps showing different chapters.

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #9715

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/animexnovel/src/eu/kanade/tachiyomi/extension/pt/animexnovel/AnimeXNovel.kt [hunk 1]
```diff
@@ -66,19 +66,27 @@ class AnimeXNovel : ZeistManga(
...
-        val url = "https://www.googleapis.com/blogger/v3/blogs/$blogId/posts".toHttpUrl().newBuilder()
-            .addQueryParameter("key", apiKey)
-            .addQueryParameter("labels", label)
-            .addQueryParameter("maxResults", "500")
-            .build()
-
-        val response = client.newCall(GET(url, headers)).execute()
+        val apiKeys = API_KEYS_REGEX.find(script)?.groupValues?.get(1)?.let { content ->
+            API_KEY_REGEX.findAll(content).map { it.groupValues[1] }.toList()
+        }?.takeIf(List<String>::isNotEmpty) ?: emptyList()
```
Comment (stevenyomi) [inline src/pt/animexnovel/src/eu/kanade/tachiyomi/extension/pt/animexnovel/AnimeXNovel.kt]: I think you mean `?: return emptyList()`.

I think the code (including early returns above this) should actually throw the exception on ~L90 instead of returning an empty list. Try extracting a function returning `Response?` and throw the exception when `null` is returned.

File: src/pt/animexnovel/src/eu/kanade/tachiyomi/extension/pt/animexnovel/AnimeXNovel.kt [hunk 2]
```diff
@@ -66,19 +66,27 @@ class AnimeXNovel : ZeistManga(
...
+            val url = "https://www.googleapis.com/blogger/v3/blogs/$blogId/posts".toHttpUrl().newBuilder()
+                .addQueryParameter("key", apiKey)
+                .addQueryParameter("labels", label)
+                .addQueryParameter("maxResults", "500")
+                .build()
+
+            response = client.newCall(GET(url, headers)).execute()
+            if (response.isSuccessful) {
+                break
+            }
```
Comment (stevenyomi) [inline src/pt/animexnovel/src/eu/kanade/tachiyomi/extension/pt/animexnovel/AnimeXNovel.kt:89]: Close the response.

**Review by stevenyomi — APPROVED** [review]
