### PR TITLE
GeassComics: Add parse for api + imageinterceptor

### LINKED ISSUE #11017: Geass Comics: `Unable to resolve host 'api.geasscomics.xyz'` error
### Source information

Geass comics 

### Source language

Pt-br

### Steps to reproduce

the source is giving an nxdomain error, only seeing it in the webview is normal

### Expected behavior

the comics should appear 

### Actual behavior

is appearing nxdomain

Image

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes: #11017

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComicsDto.kt [hunk 1]
```diff
@@ -1,131 +1,97 @@
...
+    val items: List<MangaDto> = emptyList(),
+    val pagination: PaginationDto? = null,
 )
 
 @Serializable
-class PopularDto(
-    @SerialName("obras")
-    val mangas: List<MangaDto> = emptyList(),
-    val pagination: Pagination = Pagination(),
+data class PaginationDto(
```
Comment (vetleledaal) [inline src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComicsDto.kt]: Use regular class, not data class.

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt [hunk 2]
```diff
@@ -1,118 +1,342 @@
...
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val result = response.parseAs<ChapterListDto>()
+        val mangaId = response.request.url.pathSegments[2]
+
+        return result.items.map {
+            SChapter.create().apply {
+                name = it.title
+                chapter_number = it.chapterNumber
+                val num = if (it.chapterNumber % 1 == 0f) it.chapterNumber.toInt().toString() else it.chapterNumber.toString()
```
Comment (vetleledaal) [inline src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt]:
```suggestion
                val num = it.chapterNumber.toString().removeSuffix(".0")
```

File: src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt [hunk 3]
```diff
@@ -1,118 +1,342 @@
...
 
-    override fun chapterListParse(response: Response): List<SChapter> =
-        response.parseAs<DetailsDto>().toChapters()
+    private fun parseDate(dateStr: String): Long {
+        return try {
+            dateFormat.parse(dateStr)?.time ?: 0L
+        } catch (e: Exception) {
+            0L
+        }
+    }
```
Comment (vetleledaal) [inline src/pt/geasscomics/src/eu/kanade/tachiyomi/extension/pt/geasscomics/GeassComics.kt:190]: Use `tryParse` from `keiyoushi.utils`.

**Review by vetleledaal — APPROVED** [review]
