### PR TITLE
Comicextra: Fixes and Update Filters

### LINKED ISSUE #5788: ComicExtra
### Source information

ComicExtra 1.4.16

### Source language

English 

### Steps to reproduce

Open source, times out.

### Expected behavior

Open source and read comics.

### Actual behavior

Open source, shows the titles but doesn't load the comics. Webview slow to respond also.

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

14

### Other details

New URL: https://azcomix.me/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by suhaien**
Closes #5788 

- Update domain
- Update parsers
- Filter updates
  - Add status filter (ongoing, completed)
  - Search types can now be combined

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 1]
```diff
@@ -23,75 +23,78 @@ class ComicExtra : ParsedHttpSource() {
...
+        title = element.select("div.egb-right a").text()
         thumbnail_url = element.select("img").attr("src")
     }
 
     override fun latestUpdatesFromElement(element: Element) = SManga.create().apply {
-        setUrlWithoutDomain(element.select("div.hlb-t > a").attr("href"))
-        title = element.select("div.hlb-t > a").text()
-        thumbnail_url = fetchThumbnailURL(element.select("div.hlb-t > a").attr("href"))
+        setUrlWithoutDomain(element.select("a.big-link").attr("href"))
+        title = element.select(".big-link").first()?.text().toString()
```
Comment (AwkwardPeak7) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
        title = element.selectFirst(".big-link")!!.text()
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 2]
```diff
@@ -23,75 +23,78 @@ class ComicExtra : ParsedHttpSource() {
...
+        thumbnail_url = fetchThumbnailURL(element.select("a.big-link").attr("href"))
```
Comment (AwkwardPeak7) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]: remove this, as making n calls for n entries isn't good. latest updates can remain without thumbnail

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 3]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
-        }
+        }.build()
+        return GET(url, headers)
     }
 
     override fun popularMangaFromElement(element: Element) = SManga.create().apply {
-        setUrlWithoutDomain(element.select("div.mb-right > h3 > a").attr("href"))
-        title = element.select("div.mb-right > h3 > a").text()
+        setUrlWithoutDomain(element.select("a.eg-image").attr("href"))
+        title = element.select("div.egb-right a").text()
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
        setUrlWithoutDomain(element.selectFirst("a.eg-image")!!.absUrl("href"))
        title = element.selectFirst("div.egb-right a")!!.text()
```

(needs testing)


The reason you want to use `.absUrl()` even if you are using `setUrlWithoutDomain()` is so the responsibility of stripping out the scheme+origin is left to `setUrlWithoutDomain()`. If you blindly use the attribute it will cause issues with relative URLs (including schema relative URLs), as `setUrlWithoutDomain()` does not have enough context.

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 4]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
         thumbnail_url = element.select("img").attr("src")
     }
 
     override fun latestUpdatesFromElement(element: Element) = SManga.create().apply {
-        setUrlWithoutDomain(element.select("div.hlb-t > a").attr("href"))
-        title = element.select("div.hlb-t > a").text()
-        thumbnail_url = fetchThumbnailURL(element.select("div.hlb-t > a").attr("href"))
+        setUrlWithoutDomain(element.select("a.big-link").attr("href"))
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
        setUrlWithoutDomain(element.selectFirst("a.big-link")!!.absUrl("href"))
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 5]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
-            status = parseStatus(document.select("dt:contains(Status:) + dd").text())
-            author = document.select("dt:contains(Author:) + dd").text()
-            description = document.select("div#film-content").text()
-            genre = document.select("dt.movie-dt:contains(Genres:) + dd a").joinToString { it.text() }
+            title = document.select("h1").text()
+            thumbnail_url = document.select("div.anime-image > img").attr("src")
+            status = parseStatus(document.select(".status a").text())
+            author = document.select("td:contains(Author:) + td").text()
+            description = document.select("div.detail-desc-content p").text()
+            genre = document.select("ul.anime-genres > li + li").joinToString { it.text() }
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]: Use `.selectFirst()` Do not use non-null assert outside of for `title`. Ex.:

```kt
document.selectFirst(".status a")?.also {
    status = parseStatus(it.text())
}
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 6]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
     override fun mangaDetailsParse(document: Document): SManga {
         return SManga.create().apply {
-            title = document.select("div.movie-detail span.title-1").text()
-            thumbnail_url = document.select("div.movie-l-img > img").attr("src")
-            status = parseStatus(document.select("dt:contains(Status:) + dd").text())
-            author = document.select("dt:contains(Author:) + dd").text()
-            description = document.select("div#film-content").text()
-            genre = document.select("dt.movie-dt:contains(Genres:) + dd a").joinToString { it.text() }
+            title = document.select("h1").text()
+            thumbnail_url = document.select("div.anime-image > img").attr("src")
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
            thumbnail_url = document.select("div.anime-image > img").absUrl("src")
```

(this comment is independent of the other overlapping comment)

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 7]
```diff
@@ -103,40 +103,20 @@ class ComicExtra : ParsedHttpSource() {
...
     }
 
-    override fun chapterListSelector() = "table.table > tbody#list > tr:has(td)"
+    override fun chapterListSelector() = "ul.basic-list li"
 
     override fun chapterFromElement(element: Element): SChapter {
-        val urlEl = element.select("td:nth-of-type(1) > a").first()!!
-        val dateEl = element.select("td:nth-of-type(2)")
+        val urlEl = element.select("a")
+        val dateEl = element.select("span")
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
        val dateEl = element.selectFirst("span")
```

**Review by vetleledaal — DISMISSED** [review]

**Comment by FunnyTiming** [comment]
This seems to have similarities with en.readcomictop, could you check if it's the same ?

**Comment by suhaien** [comment]
> This seems to have similarities with en.readcomictop, could you check if it's the same ?

Yes, it is the same, I just changed the baseUrl to the comicextra url in the readcomictop extension and it works right away

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 8]
```diff
@@ -103,40 +103,20 @@ class ComicExtra : ParsedHttpSource() {
...
     }
 
-    override fun chapterListSelector() = "table.table > tbody#list > tr:has(td)"
+    override fun chapterListSelector() = "ul.basic-list li"
 
     override fun chapterFromElement(element: Element): SChapter {
-        val urlEl = element.select("td:nth-of-type(1) > a").first()!!
-        val dateEl = element.select("td:nth-of-type(2)")
+        val urlEl = element.select("a")
+        val dateEl = element.selectFirst("span")!!
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]: Remove non-null assert.

**Review by vetleledaal — CHANGES_REQUESTED** [review]

**Review by vetleledaal — DISMISSED** [review]

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 9]
```diff
@@ -103,45 +103,25 @@ class ComicExtra : ParsedHttpSource() {
...
         return chapters
     }
 
-    override fun chapterListSelector() = "table.table > tbody#list > tr:has(td)"
+    override fun chapterListSelector() = "ul.basic-list li"
 
     override fun chapterFromElement(element: Element): SChapter {
-        val urlEl = element.select("td:nth-of-type(1) > a").first()!!
-        val dateEl = element.select("td:nth-of-type(2)")
+        val urlEl = element.select("a")
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]: Should also be `.selectFirst()` since you only expect one element.

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 10]
```diff
@@ -103,45 +103,25 @@ class ComicExtra : ParsedHttpSource() {
...
+        val dateEl = element.selectFirst("span")
 
         val chapter = SChapter.create()
         chapter.setUrlWithoutDomain(urlEl.attr("href").replace(" ", "%20"))
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
        chapter.setUrlWithoutDomain(urlEl.absUrl("href").replace(" ", "%20"))
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 11]
```diff
@@ -103,45 +103,25 @@ class ComicExtra : ParsedHttpSource() {
...
-    override fun chapterListSelector() = "table.table > tbody#list > tr:has(td)"
+    override fun chapterListSelector() = "ul.basic-list li"
 
     override fun chapterFromElement(element: Element): SChapter {
-        val urlEl = element.select("td:nth-of-type(1) > a").first()!!
-        val dateEl = element.select("td:nth-of-type(2)")
+        val urlEl = element.select("a")
+        val dateEl = element.selectFirst("span")
 
         val chapter = SChapter.create()
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]: Style suggestion, so feel free to ignore:
```kt
return SChapter.create().apply {
    // ...
}
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 12]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
 
     override fun mangaDetailsParse(document: Document): SManga {
         return SManga.create().apply {
-            title = document.select("div.movie-detail span.title-1").text()
-            thumbnail_url = document.select("div.movie-l-img > img").attr("src")
-            status = parseStatus(document.select("dt:contains(Status:) + dd").text())
-            author = document.select("dt:contains(Author:) + dd").text()
-            description = document.select("div#film-content").text()
-            genre = document.select("dt.movie-dt:contains(Genres:) + dd a").joinToString { it.text() }
+            title = document.select("h1").text()
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
            title = document.selectFirst("h1")!!.text()
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 13]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
 
     override fun latestUpdatesNextPageSelector() = popularMangaNextPageSelector()
 
-    override fun searchMangaSelector() = popularMangaSelector()
+    override fun searchMangaSelector() = "div.dl-box"
 
-    override fun searchMangaFromElement(element: Element) = popularMangaFromElement(element)
+    override fun searchMangaFromElement(element: Element) = SManga.create().apply {
+        setUrlWithoutDomain(element.select("a.dlb-image").attr("href"))
+        title = element.select("div.dlb-right a.dlb-title").text()
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
        setUrlWithoutDomain(element.selectFirst("a.dlb-image")!!.absUrl("href"))
        title = element.selectFirst("div.dlb-right a.dlb-title")!!.text()
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 14]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
+        thumbnail_url = element.select("a.dlb-image img").attr("src")
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
        element.selectFirst("a.dlb-image img")?.also { thumbnail_url = it.absUrl("src") }
```

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 15]
```diff
@@ -23,75 +23,75 @@ class ComicExtra : ParsedHttpSource() {
...
+        }.build()
+        return GET(url, headers)
     }
 
     override fun popularMangaFromElement(element: Element) = SManga.create().apply {
-        setUrlWithoutDomain(element.select("div.mb-right > h3 > a").attr("href"))
-        title = element.select("div.mb-right > h3 > a").text()
+        setUrlWithoutDomain(element.selectFirst("a.eg-image")!!.absUrl("href"))
+        title = element.selectFirst("div.egb-right a")!!.text()
         thumbnail_url = element.select("img").attr("src")
```
Comment (vetleledaal) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]: This line is outside of your changeset, so update at your own accord:
```suggestion
        element.selectFirst("img")?.also { thumbnail_url = it.absUrl("src") }
```

**Review by vetleledaal — CHANGES_REQUESTED** [review]

File: src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt [hunk 16]
```diff
@@ -103,46 +104,28 @@ class ComicExtra : ParsedHttpSource() {
...
-        val chapter = SChapter.create()
-        chapter.setUrlWithoutDomain(urlEl.attr("href").replace(" ", "%20"))
-        chapter.name = urlEl.text()
-        chapter.date_upload = dateParse(dateEl.text())
-        return chapter
+        val urlEl = element.selectFirst("a")
+        val dateEl = element.selectFirst("span")
+
+        return SChapter.create().apply {
+            urlEl?.also {
```
Comment (AwkwardPeak7) [inline src/en/comicextra/src/eu/kanade/tachiyomi/extension/en/comicextra/ComicExtra.kt]:
```suggestion
            urlEl!!.also {
```
url is mandatory

**Review by AwkwardPeak7 — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
