### PR TITLE
Shinigami: Fix cloudflare + pageListParse

### LINKED ISSUE #334: Shinigami chapter cannot be opened
### Source information

Shinigami 1.4.43

### Source language

Indonesia

### Steps to reproduce

open shinigami and select one (any) then open the chapter 

### Expected behavior

can read comics as usual 

### Actual behavior

when waiting for loading to complete this happens 
Screenshot_20240118_082748_Tachiyomi

### Tachiyomi version

0.15.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Secozzi**
Closes #334

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by beer-psi — DISMISSED** [review]

**Comment by beerpiss** [comment]
Remove the trailing space on Shinigami.kt. https://github.com/keiyoushi/extensions-source/actions/runs/7573763740/job/20641620721?pr=354#step:7:185

File: multisrc/overrides/madara/shinigami/src/Shinigami.kt [hunk 1]
```diff
@@ -148,13 +75,16 @@ class Shinigami : Madara("Shinigami", "https://shinigamitoon.com", "id") {
...
         val chapterData = json.decodeFromString<CDT>(
-            script.substringAfter("var chapter_data = '").substringBefore("'"),
+            CHAPTER_DATA_REGEX.find(script)?.groupValues?.get(1) ?: throw Exception("Unable to get chapter data"),
         )
-
-        val keyMatch = KEY_REGEX.find(deobfuscated)!!.groupValues
-        val key = postId + keyMatch[1] + postId + keyMatch[2] + postId
+        val postId = POST_ID_REGEX.find(script)?.groupValues?.get(1) ?: throw Exception("Unable to get post_id")
+        val otherId = OTHER_ID_REGEX.findAll(script).firstOrNull { it.groupValues[1] != "post" }?.groupValues?.get(2) ?: throw Exception("Unable to get other id")
+
```
Comment (beer-psi) [inline multisrc/overrides/madara/shinigami/src/Shinigami.kt]:
```suggestion

```
Remove the trailing space on this line, it's causing CI linting to fail.

**Review by beer-psi — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
