### PR TITLE
Fix PerfScan : Complete rewrite for new site and API

### LINKED ISSUE #8048: Perf Scan new url
### Source information

Perf Scan 1.4.29

### Source language

French

### Source new URL

https://perf-scan.net/fr

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Nyantad**
Complete rewrite to support the new site and its dedicated API, as the old `HeanCms` version is defunct

Closes #8048

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/perfscan/src/eu/kanade/tachiyomi/extension/fr/perfscan/PerfScan.kt [hunk 1]
```diff
@@ -1,24 +1,136 @@
...
+    override val client: OkHttpClient = network.cloudflareClient
 
-    init {
-        preferences.run {
-            if (contains("pref_url_map")) {
-                edit().remove("pref_url_map").apply()
+    private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US)
+    private val chapterNumberFormat = DecimalFormat("#.##")
+
+    override fun headersBuilder(): Headers.Builder = Headers.Builder()
```
Comment (AwkwardPeak7) [inline src/fr/perfscan/src/eu/kanade/tachiyomi/extension/fr/perfscan/PerfScan.kt]:
```suggestion
    override fun headersBuilder(): Headers.Builder = super.headerBuilder()
```
to include useragent

File: src/fr/perfscan/src/eu/kanade/tachiyomi/extension/fr/perfscan/PerfScan.kt [hunk 2]
```diff
@@ -1,24 +1,136 @@
...
+    // =============================== Latest ===============================
+    override fun latestUpdatesRequest(page: Int): Request {
+        return GET("$apiUrl/series?type=COMIC&page=$page&take=24&latestUpdate=true", headers)
+    }
+
+    override fun latestUpdatesParse(response: Response): MangasPage = popularMangaParse(response)
+
+    // =============================== Search ===============================
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
+        return GET("$apiUrl/series?type=COMIC&title=$query&page=$page&take=24", headers)
```
Comment (AwkwardPeak7) [inline src/fr/perfscan/src/eu/kanade/tachiyomi/extension/fr/perfscan/PerfScan.kt]: use `HttpUrl.Builder` to properly encode the query

File: src/fr/perfscan/src/eu/kanade/tachiyomi/extension/fr/perfscan/PerfScan.kt [hunk 3]
```diff
@@ -1,24 +1,136 @@
...
+        val result = response.parseAs<PerfScanResponse<PerfScanSeriesDetails>>()
+        val seriesSlug = result.data.slug
+        return result.data.chapters
+            .sortedByDescending { it.index }
+            .map { chapter ->
+                SChapter.create().apply {
+                    val chapterIndex = chapterNumberFormat.format(chapter.index)
+                    url = "/series/$seriesSlug/chapter/$chapterIndex"
+                    name = "Chapitre $chapterIndex" + if (!chapter.title.isNullOrEmpty() && chapter.title != "-") " - ${chapter.title}" else ""
+                    date_upload = runCatching { dateFormat.parse(chapter.createdAt)?.time }.getOrNull() ?: 0L
```
Comment (AwkwardPeak7) [inline src/fr/perfscan/src/eu/kanade/tachiyomi/extension/fr/perfscan/PerfScan.kt]:
```suggestion
                    date_upload = dateFormat.tryParse(chapter.createdAt)
```
need to import

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
