### PR TITLE
TB: rewrite for new site

### LINKED ISSUE #6768: [TheBlank] Premium Chapter Toggle & Easy Login
### Source name

The Blank Scanlation

### Source language

English

### Describe your suggested feature

A toggle to enable or disable premium chapters (and a way to differentiate them) kind of like how the Omega Scans extension does it.
And as an added bonus, possibly a way to add in our login credentials?  As the extension works currently, if you are logged out of the site in WebView, the premium chapters disappear when the library is updated and your read history is wiped. This results in the chapters being marked unread and re-downloaded upon signing in again.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11678: The Blank Scanlation: Remove WebView flag workaround from extension settings
### Source name

The Blank Scanlation 1.4.49

### Source language

English

### Describe your suggested feature

Since the WebView Devtools removed the `WebViewXRequestedWithHeaderControl` flag after version 140.0.7339, plus the header fix with Mihon Stable 0.19.3, the two workaround settings in the extension are no longer relevant/needed.

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11893: The Blank Site/Design Change
### Source information

The Blank Scanlation 1.4.49

### Source language

English 

### Steps to reproduce

1. Going to entry for "Blank Scans"
2. Click on webview
3.  Issue site is removed

### Expected behavior

Rather site being removed. Cloudflare check should be popping up

### Actual behavior

Site is removed

### Mihon/Tachiyomi version

1.12.0

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes #11893
closes #11678
closes #6768 // partially?

ended up writing the secretstream version of XCacCha20 Poly1305 algorithm, cuz I couldn't find any java/kotlin library which had this specific version and was not a native library. This version was written by referencing the libsodium c library. (and help from copilot)

It is written in java here purely because there is no proper language server for kotlin in vscode and I didn't wanna write it in the extension or install intellij ide :/

let me know if this is not acceptable, I'll  convert it into kotlin

Thanks to `@MikeZeDev2` for the helpful insights via their haruneko commit ;)

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt [hunk 1]
```diff
@@ -1,109 +1,488 @@
...
-class TheBlank :
-    Madara(
-        "The Blank Scanlation",
-        "https://theblank.net",
-        "en",
-        dateFormat = SimpleDateFormat("dd/MM/yy", Locale.US),
-    ),
-    ConfigurableSource {
+class TheBlank : HttpSource(), ConfigurableSource {
+    override val name = "The Blank"
```
Comment (vetleledaal) [inline src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt:54]: Consider bumping `id` to make it obvious that it's a new version. Otherwise if the name is changed back in the future it will cause issues.

File: src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt [hunk 2]
```diff
@@ -1,109 +1,488 @@
...
 
-    private val preferences = getPreferences()
+    private val preferences by getPreferencesLazy()
 
-    override val client = super.client.newBuilder()
+    override val client = network.cloudflareClient.newBuilder()
+        .addInterceptor { chain ->
+            val request = chain.request()
+            if (request.url.fragment == THUMBNAIL_FRAGMENT) {
+                thumbnailClient.newCall(request).execute()
```
Comment (vetleledaal) [inline src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt:66]: Is the response used? If it's only in the interceptor then the control flow is confusing.

File: src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt [hunk 3]
```diff
@@ -1,109 +1,488 @@
...
+                            append("\uD83D\uDD12 ") // lock emoji
+                        }
+                        append(it.title)
+                    }
+                    date_upload = dateFormat.tryParse(it.createdAt)
+                }
+            }.asReversed()
+    }
+
+    private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'", Locale.ENGLISH)
```
Comment (vetleledaal) [inline src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt]: Not using any locale specific patterns, use:

```suggestion
    private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'", Locale.ROOT)
```

File: src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/decryption/SecretStream.java [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+        public byte[] message;
+        public byte tag;
+        
+        public PullResult(byte[] message, byte tag) {
+            this.message = message;
+            this.tag = tag;
+        }
+    }
+    
+    // crypto_secretstream_xchacha20poly1305_init_pull
```
Comment (vetleledaal) [inline src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/decryption/SecretStream.java:31]: Mention that this is ported from `libsodium` somewhere, either as a general statement or function-by-function.

**Review by vetleledaal — DISMISSED** [review]
We don't really need Kotlin for everything, Java is fine if its already written as such. I think we should just push the update to users and see if they try to break it.

Feel free to ignore comments on code moved over from the old implementation. I won't be reviewing the Java code.

File: src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt (hunk 2 above)
Comment (AwkwardPeak7) [reply src/en/theblank/src/eu/kanade/tachiyomi/extension/en/theblank/TheBlank.kt:66]: just to not ratelimit thumbnails

**Review by vetleledaal — APPROVED** [review]
