### PR TITLE
Yidan: Rewrite and rework the extension.

### LINKED ISSUE #8083: 一耽女孩 / Yidan Girl: Unexpected JSON token error
### Source information

Yidan Girl 1.4.4

### Source language

Chinese

### Steps to reproduce

1. Go to source's Browse page (both Latest and Popular, and search)
2. JsonDecodingException: Unexpected JSON token at offset 0 error

### Expected behavior

It should load the results

### Actual behavior

Gives the Unexpected JSON token error

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 14

### Other details

Don't think #8081 tested their changes

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AlphaBoom**
Closes #8083 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 1]
```diff
@@ -1,135 +1,348 @@
...
+                response.body.source().apply { skip(2) }
+                    .asResponseBody("image/$ext".toMediaType()),
+            ).build()
+        } else {
+            response
+        }
+    }.build()
 
     private val json: Json by injectLazy()
+    private val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
```
Comment (vetleledaal) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt]: Make this static, since the string is not affected by the locale you can use 'no locale':
```suggestion
    private val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.ROOT)
```

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 2]
```diff
@@ -1,135 +1,348 @@
...
     }
 
-    override fun searchMangaParse(response: Response) = popularMangaParse(response)
+    override fun searchMangaParse(response: Response): MangasPage {
+        val searchByKeyword = response.request.url.toString().contains("searchNovel")
+        val records = if (searchByKeyword) {
+            response.parseAs<CommonResponse<List<Record>>>().result
+        } else {
+            response.parseAs<CommonResponse<FilterResult>>().result.list
+        }
```
Comment (vetleledaal) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt]: Consider something like:
```suggestion
        val records = when {
            searchByKeyword -> response.parseAs<CommonResponse<List<Record>>>().result
            else -> response.parseAs<CommonResponse<FilterResult>>().result.list
        }
```

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 3]
```diff
@@ -1,135 +1,347 @@
...
+                    url = "${it.id}"
+                    title = it.novelTitle
+                    thumbnail_url = it.imgUrl
+                }
+            },
+            if (paginated) {
+                records.size >= PAGE_SIZE
+            } else {
+                false
+            },
```
Comment (vetleledaal) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt]: Could this work?
```suggestion
            paginated && records.size >= PAGE_SIZE,
```

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 4]
```diff
@@ -1,135 +1,347 @@
...
+        )
+    }
 
-    override fun fetchMangaDetails(manga: SManga): Observable<SManga> {
-        val request = GET("$baseUrl/prod-api/app-api/vv/mh-list/get?id=${manga.url}", headers)
-        return client.newCall(request).asObservableSuccess().map { mangaDetailsParse(it) }
+    override fun getMangaUrl(manga: SManga): String {
+        return "$baseUrl/pages/comic/info?id=${manga.url}"
```
Comment (vetleledaal) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt]: Consider:
```suggestion
        return "$baseUrl/pages/comic/info".toHttpUrl().newBuilder()
            .addQueryParameter("id", manga.url)
            .toString()
```

whitespace might be off.

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 5]
```diff
@@ -1,135 +1,347 @@
...
+            status = when (comic.overType) {
+                1 -> SManga.ONGOING
+                2 -> SManga.COMPLETED
+                else -> SManga.UNKNOWN
+            }
+        }
+    }
+
+    override fun getChapterUrl(chapter: SChapter): String {
+        return "$baseUrl/pages/comic/content?f=1&s=${chapter.chapter_number.toInt()}"
```
Comment (vetleledaal) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt]: Consider:
```suggestion
        return "$baseUrl/pages/comic/content.toHttpUrl().newBuilder()
            .addQueryParameter("f", "1")
            .addQueryParameter("s", chapter.chapter_number.toInt().toString())
            .toString()
```
whitespace might be off.

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 6]
```diff
@@ -1,135 +1,347 @@
...
+                        // wait the auto register request
+                        if (request?.url?.encodedPath?.contains("api/regUser") == true) {
+                            latch.countDown()
+                        }
+                        return super.shouldInterceptRequest(view, request)
+                    }
+                }
+                webView?.loadUrl(baseUrl)
+            }
+            latch.await(15, TimeUnit.SECONDS)
```
Comment (vetleledaal) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt:305]: Is the user notified if it times out? Should be.

Comment (AlphaBoom) [reply src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt:305]: Now at the end, perform a result check and throw an exception if the userid is not retrieved.

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 7]
```diff
@@ -1,135 +1,345 @@
...
+                .getString(PREF_KEY_MIRROR, "0")!!.toInt().coerceAtMost(mirrors.size - 1)
+            "https://${mirrors[index]}"
+        } else {
+            customBaseUrl.removeSuffix("/")
+        }
     }
 
-    override fun headersBuilder() = Headers.Builder()
-        .add("User-Agent", System.getProperty("http.agent")!!)
+    override val client: OkHttpClient = super.client.newBuilder().addInterceptor { chain ->
```
Comment (AwkwardPeak7) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt]: use `network.cloudflareClient`

File: src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt [hunk 8]
```diff
@@ -1,135 +1,345 @@
...
+        } else {
+            val mainHandler = Handler(Looper.getMainLooper())
+            var latch = CountDownLatch(1)
+            var webView: WebView? = null
+            mainHandler.post {
+                webView = WebView(Injekt.get<Application>()).apply {
+                    with(settings) {
+                        javaScriptEnabled = true
+                        domStorageEnabled = true
+                        databaseEnabled = true
```
Comment (AwkwardPeak7) [inline src/zh/yidan/src/eu/kanade/tachiyomi/extension/zh/yidan/Yidan.kt:280]:
```suggestion
                        databaseEnabled = true
                        blockNetworkImage = true
```

**Review by AwkwardPeak7 — APPROVED** [review]
