### PR TITLE
Iken: move to API

### LINKED ISSUE #14929: Azora: `MissingFieldException` error
### Source information

ar.azora 1.4.62

### Source language

Arabic 

### Steps to reproduce

-Open source 
-Selecte any manga/manhawa..etc
-update or read 
PFA 2 error massage appears 

Image
Image

### Expected behavior

Should update or be readable 

### Actual behavior

I can't update or read 

### Mihon/Mihon fork version

Mihon 0.19.9

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #15017: Iken (Hive Scans, Ken Scans): `MissingFieldException` error in series
### Source information

Ken Scans 1.4.27

### Source language

English

### Steps to reproduce

1. Run an update either manually or an automatic update. For example, the manhwa I Didn't Lull You to Sleep Only for You to Be Obsessed.

Image

2. Update fails and gives an MissingFieldException: Field 'chapterStatus' is required for type with serial name 'eu,kanade,tachiyomi,multisrc.iken. Chapter', but it was missing at path: $.post.chapters[0] error

### Expected behavior

An update should run without throwing an error.

### Actual behavior

Updating the entry fails.

### Mihon/Mihon fork version

TachiSY 1.12.0

### Android version

Android 16

### Other details

Works fine in WebView.

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by xMohnad**
Closes #14929
Closes #15017 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt [hunk 1]
```diff
@@ -322,85 +319,75 @@ abstract class Iken(
...
-
-        return manga.toSManga().apply {
-            if (manga.postContent?.startsWith('$') == true) {
-                body.extractNextJsRsc<DescriptionDto>()?.description.let {
-                    description = manga.getDescription(it)
-                }
-            }
-        }
+    override fun mangaDetailsRequest(manga: SManga): Request {
+        val id = manga.url.substringAfterLast("#")
```
Comment (Ploosh) [inline lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt:325]: Backward-compat question for users with existing library entries: if their saved `manga.url` is just `"some-manga"` (no `#postId` fragment), `substringAfterLast("#")` returns the full string unchanged, and `GET "$apiUrl/api/post?postId=some-manga"` would fail because the API expects a numeric ID. In `chapterListParse` below, `id?.toInt()` on that would also throw `NumberFormatException` inside `launchIO`.

Is the `#id` format already in place for all existing entries (via an earlier migration I'm missing), or will this need a migration hook?

File: lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt [hunk 2]
```diff
@@ -322,85 +319,75 @@ abstract class Iken(
...
+        return GET("$apiUrl/api/chapter?chapterId=$id", headers)
+    }
+
     override fun pageListParse(response: Response): List<Page> {
-        val document = response.asJsoup()
+        val data = response.parseAs<PageResponse>().chapter
 
-        if (document.select("#publicSalt, #challenge").isNotEmpty()) {
-            throw Exception(V_SHIELD_MESSAGE)
+        if (data.isShortLinkLocked) {
```
Comment (Ploosh) [inline lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt:368]: The old `chapterListParse` had a `vShieldRegex` check and the old `pageListParse` selected `#publicSalt, #challenge` to detect the BalooPow challenge page. Those are gone now that both paths use the API. Does the API bypass the vShield challenge entirely, or can it still be served a challenge response? If the latter, users would see a generic JSON parse failure rather than the helpful `V_SHIELD_MESSAGE`.

File: lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Dto.kt [hunk 3]
```diff
@@ -47,7 +47,7 @@ class Manga(
             append(Jsoup.parse(desc.replace("\n", "<br>")).text())
         }
         alternativeTitles?.takeUnless { it.isEmpty() }?.let { altName ->
-            append("\n\n")
+            append("\n\n\n")
```
Comment (Ploosh) [inline lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Dto.kt]: Intentional? The rest of the description builder uses `\n\n` between sections — this is the only triple. If deliberate, a short comment would help; if accidental, worth reverting to keep the diff focused on the API migration.

**Comment by luigidotmoe** [comment]
i assume it'll close #15017 too

**Review by AwkwardPeak7 — APPROVED** [review]
