### PR TITLE
LibGroup: fix crash on null token

### LINKED ISSUE #4057: HentaiLib causes crashes
### Source information

HentaiLib 1.4.48

### Source language

Russian

### Steps to reproduce

1. Press on the extension's source in Sources tab of the Browse page or Search for series with this source enabled
2. Crash

### Expected behavior

No crashes

### Actual behavior

Crash when pressing on the source and in search, have to disable extension to search for anything 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

I believe latest update of the extension to 1.4.48 caused this
Reported this on Mihon's Discord but they said it's an extension issue.

[mihon_crash_logs.txt](https://github.com/user-attachments/files/16257079/mihon_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by nedius**
Closes #4057 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroupDto.kt [hunk 1]
```diff
@@ -266,8 +266,8 @@ class Pages(
 
 @Serializable
 class AuthToken(
-    private val auth: Auth,
-    private val token: Token,
+    private val auth: Auth?,
```
Comment (bapeey) [inline lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroupDto.kt:269]:
```suggestion
    private val auth: Auth? = null,
```
~Set default value or it will fail if the field is not found~ 
nvm `explicitNulls = false` is doing the job ([ref](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-builder/explicit-nulls.html))

**Review by AwkwardPeak7 — APPROVED** [review]
