### PR TITLE
Spicy Scan (ES): Fix receiving json array

### LINKED ISSUE #13341: Spicy scan  unexpected  json token
### Source information

Spicy scan  1.4..1

### Source language

Spanish 

### Steps to reproduce

When you want to read, see which chapter of manwha gives an error

Image

### Expected behavior

It should display any chapters of any series

### Actual behavior

Gives json token error

Image

### Mihon/Mihon fork version

0.19.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by disk-iq8**
Closes #13341

Checklist:

- [] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/spicytheme/src/eu/kanade/tachiyomi/multisrc/spicytheme/Dto.kt [hunk 1]
```diff
@@ -76,6 +84,23 @@ data class ChapterImagesDto(
     val chapterId: Int,
 )
 
+// Get first item only in case of JsonArray
+
+object FirstobjOrObj : KSerializer<ChapterImagesDto> {
```
Comment (AwkwardPeak7) [inline lib-multisrc/spicytheme/src/eu/kanade/tachiyomi/multisrc/spicytheme/Dto.kt]: use a `JsonTransformingSerializer`

**Review by AwkwardPeak7 — APPROVED** [review]
