### PR TITLE
CosmicScansID | Fixed NullPointerException

### LINKED ISSUE #5184: CosmicScans.id: NullPointerException toast on certain entries
### Source information

CosmicScans.id 1.4.34

### Source language

Indonesia

### Steps to reproduce

1. Open certain entries
2. NullPointerException: null toast message appears, appears again when refreshing (see other details below)

### Expected behavior

Shouldn't toast

### Actual behavior

Gives toast

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

I think the toast appears because it couldn't fetch the Status from the site (but don't quote me), here are some titles (currently) doing this:
* The Tales of Heaven And Earth
* My Seven Senior Sister Spoiled Me A Lot
* Roguish Guard in a Medieval Fantasy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #5184

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/cosmicscansid/src/eu/kanade/tachiyomi/extension/id/cosmicscansid/CosmicScansID.kt [hunk 1]
```diff
@@ -56,6 +59,39 @@ class CosmicScansID : MangaThemesia("CosmicScans.id", "https://cosmic1.co", "id"
...
+                    }
+                }
+            }
+                .joinToString { it.trim() }
+
+            status = seriesDetails.selectFirst(seriesStatusSelector)?.text().parseStatus()
+            val thumbnail = seriesDetails.select(seriesThumbnailSelector)
+            if (thumbnail.isNotEmpty()) {
+                thumbnail_url = seriesDetails.select(seriesThumbnailSelector).imgAttr()
+            }
```
Comment (vetleledaal) [inline src/id/cosmicscansid/src/eu/kanade/tachiyomi/extension/id/cosmicscansid/CosmicScansID.kt]: Since `mangaDetailsParse()` is quite a large function I would look into modifying the `imgAttr()` function instead. Or was that not possible with the return typing being `String` and not `String?`?

**Review by vetleledaal — APPROVED** [review]
