### PR TITLE
Magazine Pocket: new scrambling, refactor, preference

### LINKED ISSUE #13938: PocketShonen
### Source information

1.4.11

### Source language

Japanese

### Steps to reproduce

When I try to open/download a chapter, I get an error.

Image

### Expected behavior

The chapter will open

### Actual behavior

The chapter won't open due to some token error.

### Mihon/Mihon fork version

1.19.1

### Android version

14

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by manti-X**
Closes #13938

bruh they are using a WASM now

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt [hunk 1]
```diff
@@ -60,81 +77,81 @@ class MagazinePocket : HttpSource() {
...
-        }
+    override fun fetchLatestUpdates(page: Int): Observable<MangasPage> {
+        if (page > 1) return Observable.just(MangasPage(emptyList(), false))
+        return Observable.fromCallable {
+            val mangas = ArrayList<SManga>()
+
+            for (dayOffset in 0..13) {
+                val calendar = GregorianCalendar(jst).apply {
+                    time = Date()
+                    add(Calendar.DAY_OF_MONTH, -dayOffset)
```
Comment (AwkwardPeak7) [inline src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt]: why fetch everything in a loop and not use page number as offset?

Comment (manti-X) [reply src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt]: There is no pagination indicator and it throws exception if no results with ```latestUpdatesRequest/latestUpdatesParse```

Comment (manti-X) [reply src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt]: Ah I get what you meant

File: src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt [hunk 2]
```diff
@@ -60,81 +77,76 @@ class MagazinePocket : HttpSource() {
...
-            append('-')
-            append(calendar.get(Calendar.DAY_OF_MONTH).toString().padStart(2, '0'))
-        }
+            val dateString = buildString {
+                append(calendar.get(Calendar.YEAR))
+                append('-')
+                append((calendar.get(Calendar.MONTH) + 1).toString().padStart(2, '0'))
+                append('-')
+                append(calendar.get(Calendar.DAY_OF_MONTH).toString().padStart(2, '0'))
+            }
```
Comment (vetleledaal) [inline src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt]: Doesn't Kotlin have some concept of `strftime`? Seems cumbersome.

File: src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt [hunk 3]
```diff
@@ -19,37 +23,50 @@ import okhttp3.Request
...
-    override val baseUrl = "https://pocket.shonenmagazine.com"
+    private val domain = "pocket.shonenmagazine.com"
+    override val baseUrl = "https://$domain"
     override val lang = "ja"
     override val supportsLatest = true
     override val versionId = 2
 
-    private val apiUrl = "https://api.pocket.shonenmagazine.com"
+    private val apiUrl = "https://api.$domain"
     private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ROOT)
```
Comment (vetleledaal) [inline src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt]: This is still using the local timezone?

**Review by AwkwardPeak7 — APPROVED** [review]
