### PR TITLE
Goda (baozimhorg): Update api url

### LINKED ISSUE #10344: GoDA “ParseException: Unparseable date”is displayed after opening the chapter list
### Source information

GoDA 1.4.34

### Source language

Chinese

### Steps to reproduce

1.When opening the manga’s chapter list, it displays “ParseException: Unparseable date: "2025-03-05T19:03:32Z” and the timestamp varies slightly between different manga.
2.I’ve tried “Troubleshooting” and swapping the “Extensions” source URLs, but neither fixed the issue.
3.Switching network environments—whether in China or abroad—still triggers this error.
4.Some manga chapters load normally without any errors.

### Expected behavior

Normal display

### Actual behavior

No chapter list is displayed，only show“ParseException: Unparseable date: "2025-03-05T19:03:32Z”

### Mihon/Tachiyomi version

stable 0.19.1

### Android version

Android 14

### Other details

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dodieboy**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/Dto.kt [hunk 1]
```diff
@@ -40,13 +40,33 @@ class AttributesDto(
...
     }
 }
 
 // Static field, no need for lazy
-private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US).apply {
-    timeZone = TimeZone.getTimeZone("UTC")
+// private val dateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US).apply {
+//    timeZone = TimeZone.getTimeZone("UTC")
+// }
+
```
Comment (Riztard) [inline src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/Dto.kt]: just remove it if it is no longer needed

Comment (dodieboy) [reply src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/Dto.kt]: My bad, forget to remove old code

File: src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/Dto.kt [hunk 2]
```diff
@@ -40,13 +40,28 @@ class AttributesDto(
...
+        },
+    )
+
+    for (format in formats) {
+        try {
+            return format.parse(dateString)!!.time
+        } catch (e: Exception) {
+            // Continue to next format
+        }
+    }
```
Comment (stevenyomi) [inline src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/Dto.kt]:
```suggestion
private val formats = listOf(
    SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    },
    SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    },
)

fun parseDate(dateString: String): Long {
    for (format in formats) {
        val date = format.parse(dateString, ParsePosition(0)) ?: continue
        return date.time
    }
```

**Review by stevenyomi — DISMISSED** [review]

File: src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/GoDaManhua.kt [hunk 3]
```diff
@@ -23,6 +23,8 @@ class GoDaManhua : GoDa("GoDa漫画", "", "zh"), ConfigurableSource {
 
     override val baseUrl: String
 
+    override fun headersBuilder() = super.headersBuilder().add("Referer", "$baseUrl/").add("origin", "$baseUrl/")
```
Comment (vetleledaal) [inline src/zh/baozimhorg/src/eu/kanade/tachiyomi/extension/zh/baozimhorg/GoDaManhua.kt]: Only the `Referer` header has a trailing slash, `Origin` does not.
Casing might matter for fingerprinting purposes if using HTTP/1.1.
```suggestion
    override fun headersBuilder() = super.headersBuilder().add("Referer", "$baseUrl/").add("Origin", baseUrl)
```

**Review by vetleledaal — DISMISSED** [review]

**Review by stevenyomi — APPROVED** [review]
