### PR TITLE
Manga Gezgini(tr): Update Domain, and Fix typo in Genre

### LINKED ISSUE #7602: Wrong genre writing in Doujindesu
### Source information

Doujindesu 1.4.7

### Source language

Indonesia

### Steps to reproduce

1. Go to the Doujindesu source (Indonesian).
2. Click Filter, then expand the genre category.
3. Then you find the genre writing that should be "Defloration" becomes "Defloartion"

### Expected behavior

the genre that says "Defloartion" should be "Defloration"

### Actual behavior

genre writing that should be "Defloration" becomes "Defloartion"

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 11

### Other details

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #7614: Manga Gezgini Domain Change
### Source information

MangaGezgini 1.4.44

### Source language

Turkish 

### Source new URL

mangagezgini.site

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by prem-k-r**
Closes #7614
Closes #7602 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions **(Doujin Desu)**
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions **(Manga Gezgini)**
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — APPROVED** [review]

File: src/id/doujindesu/src/eu/kanade/tachiyomi/extension/id/doujindesu/DoujinDesu.kt [hunk 1]
```diff
@@ -136,7 +136,7 @@ class DoujinDesu : ParsedHttpSource(), ConfigurableSource {
         Genre("Cunnilingus"),
         Genre("Dark Skin"),
         Genre("Daughter"),
-        Genre("Defloartion"),
+        Genre("Defloration"),
```
Comment (TheKingTermux) [inline src/id/doujindesu/src/eu/kanade/tachiyomi/extension/id/doujindesu/DoujinDesu.kt:139]: Ohh i just realize that (⁠・⁠–⁠・⁠;⁠)⁠ゞ
Sorry for the trouble I've caused
I didn't think that I had a typo in writing the genre, because I never use that genre
Well, the writing was still manual and didn't use a script to extract the genre, that was my mistake at that time

**Review by TheKingTermux — COMMENTED** [review]
Sorry...
