### PR TITLE
Happymh: Fix chapter list parsing

### LINKED ISSUE #6540: Happymh  can't refresh to catch the latest episodes, and  can't read the comics
### Source information

Happymh 1.4.14

### Source language

Chinese

### Steps to reproduce

Open the comic book added to the shelf and pull down to refresh the chapter. At this time, "No chapter" will be displayed and click on the chapter to watch, and no picture can be obtained

### Expected behavior

Get the latest chapters normally, and can read comics

### Actual behavior

Can't get the latest chapters properly, can't read comics

### Mihon/Tachiyomi version

0.16.2

### Android version

Android12/Harmonyos 3.0

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AlphaBoom**
Close #6540 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 1]
```diff
@@ -139,38 +145,76 @@ class Happymh : HttpSource(), ConfigurableSource {
...
+                }
+            }
+            .toList()
+            .map { it.flatten().sortedByDescending { chapter -> chapter.chapter_number } }
+            .map {
+                // remove order mark
+                it.forEach { chapter ->
+                    chapter.chapter_number = 0f
+                }
+                it
```
Comment (AwkwardPeak7) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]:
```suggestion
                it.onEach { chapter ->
                    chapter.chapter_number = 0f
                }
```

**Review by AwkwardPeak7 — APPROVED** [review]
