### PR TITLE
Fix Adu Manga URL & date format

### LINKED ISSUE #3762: Adu Manga Extension Tries to Open The Wrong Website
### Source information

Adu Manga

### Source language

Turkish

### Steps to reproduce

Open the Adu Manga Extension

### Expected behavior

The extension should open and we should be able to see the manga series

### Actual behavior

Instead it gives an error page and when we try to open with WebViev it tries to open a site called www.mangacim.com which is a link that doesnt work

Screenshot_20240627_002447_Mihon

Screenshot_20240627_002452_Mihon

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Smol-Ame**
Closes #3762 

* Replaced link with correct link
* ~~Swapped out `tr` locale to `en`~~ Removed `dateFormat` override since site uses English month names

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/tr/adumanga/src/eu/kanade/tachiyomi/extension/tr/adumanga/AduManga.kt [hunk 1]
```diff
@@ -6,7 +6,7 @@ import java.util.Locale
 
 class AduManga : MangaThemesia(
     "Adu Manga",
-    "https://www.mangacim.com",
+    "https://adumanga.com",
     "tr",
-    dateFormat = SimpleDateFormat("MMMM d, yyy", Locale("tr")),
+    dateFormat = SimpleDateFormat("MMMM dd, yyyy", Locale("en")),
```
Comment (AwkwardPeak7) [inline src/tr/adumanga/src/eu/kanade/tachiyomi/extension/tr/adumanga/AduManga.kt]: this is the default format, so remove it

**Review by AwkwardPeak7 — APPROVED** [review]
