### PR TITLE
Manwa: Add preference for mirror selection

### LINKED ISSUE #1224: Manwa shows no results, but webview is okay
### Source information

manwa1.4.4

### Source language

Chinese

### Steps to reproduce

1.Open the app
2.Open manwa
3.No result but webview  is okay

https://github.com/keiyoushi/extensions-source/assets/104707441/ee30fdf1-d79e-4dd8-be07-dbcbacdecd9b

### Expected behavior

It can be used to read

### Actual behavior

No results

### Mihon/Tachiyomi version

TachiyomiJ2K1.7.4

### Android version

Android13

### Other details

It happens only when in China IP, you need click some buttons in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #3160: Request to add “Manwa” domain site
### Source name

Manwa 1.4.4

### Source language

chinese

### Describe your suggested feature

For Mainland China users, a VPN is required to connect to manwa.me.

The following URLs can be linked directly to the website, requesting the addition of a URL:
https://manwav3.xyz/

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by anenasa**
Closes #1224
Closes #3160

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt [hunk 1]
```diff
@@ -43,10 +43,10 @@ class Manwa : ParsedHttpSource(), ConfigurableSource {
     override val name: String = "漫蛙"
     override val lang: String = "zh"
     override val supportsLatest: Boolean = true
-    override val baseUrl = "https://manwa.fun"
     private val json: Json by injectLazy()
     private val preferences: SharedPreferences =
         Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
+    override val baseUrl = "https://${preferences.getString(MIRROR_KEY, MIRROR_ENTRIES[0])}"
```
Comment (stevenyomi) [inline src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt]:
```suggestion
    override val baseUrl = "https://" + MIRROR_ENTRIES.run { this[preferences.getString(MIRROR_KEY, "0").toInt().coerceAtMost(size)] }
```

File: src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt [hunk 2]
```diff
@@ -179,6 +179,14 @@ class Manwa : ParsedHttpSource(), ConfigurableSource {
     override fun imageUrlParse(document: Document): String = throw UnsupportedOperationException()
 
     override fun setupPreferenceScreen(screen: PreferenceScreen) {
+        ListPreference(screen.context).apply {
+            key = MIRROR_KEY
+            title = "使用镜像网址"
+            entries = MIRROR_ENTRIES
+            entryValues = MIRROR_ENTRIES
+            setDefaultValue(MIRROR_ENTRIES[0])
```
Comment (stevenyomi) [inline src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt]:
```suggestion
            entryValues = Array(entries.size, Int::toString)
            setDefaultValue("0")
```

File: src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt [hunk 3]
```diff
@@ -208,6 +216,8 @@ class Manwa : ParsedHttpSource(), ConfigurableSource {
     }
 
     companion object {
+        private const val MIRROR_KEY = "MIRROR"
+        private val MIRROR_ENTRIES = arrayOf("manwa.fun", "manwa.me", "manwav3.xyz", "manwasa.cc", "manwadf.cc")
```
Comment (stevenyomi) [inline src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt]:
```suggestion
        private val MIRROR_ENTRIES get() = arrayOf("manwa.fun", "manwa.me", "manwav3.xyz", "manwasa.cc", "manwadf.cc")
```

**Review by stevenyomi — COMMENTED** [review]
Store number indices as value.

File: src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt [hunk 4]
```diff
@@ -43,10 +43,10 @@ class Manwa : ParsedHttpSource(), ConfigurableSource {
     override val name: String = "漫蛙"
     override val lang: String = "zh"
     override val supportsLatest: Boolean = true
-    override val baseUrl = "https://manwa.fun"
     private val json: Json by injectLazy()
     private val preferences: SharedPreferences =
         Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
+    override val baseUrl = "https://" + MIRROR_ENTRIES.run { this[preferences.getString(MIRROR_KEY, "0").toInt().coerceAtMost(size)] }
```
Comment (stevenyomi) [inline src/zh/manwa/src/eu/kanade/tachiyomi/extension/zh/manwa/Manwa.kt]:
```suggestion
    override val baseUrl = "https://" + MIRROR_ENTRIES.run { this[preferences.getString(MIRROR_KEY, "0")!!.toInt().coerceAtMost(size)] }
```

I missed the `!!`, sorry.

**Review by stevenyomi — APPROVED** [review]
