### PR TITLE
IkigaiMangas: Fix search and images not loading

### LINKED ISSUE #11803: Ikigai Mangas: Search doesn't show the correct entries/only the same entries
### Source information

Ikigaimanga 1.4.28

### Source language

Spanish 

### Steps to reproduce

Al momento de digitar alguna serie, el resultado siempre es el mismo, 

Image

### Expected behavior

Deberia filtrar la series por su nombre al momento de realizar la busqueda en la fuente.

### Actual behavior

Da como resultado las mismas series e imágenes 

Image

### Mihon/Tachiyomi version

0.19. 3

### Android version

Android 11

### Other details

Con webview se conprobo que si filtro la busqueda de la web

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11867: Ikigai mangas no carga capitulos
### Source information

Ikigai mangas 1.4.28

### Source language

Español

### Steps to reproduce

Entrar a ikigai mangas 
Elegir manga
Entra a capítulo 
Error 403
Entro la web y si se ven los capítulos 

### Expected behavior

Entrar a ikigai mangas 
Elegir manga
Entra a capítulo 
Leo el capítulo 

### Actual behavior

Entrar a ikigai mangas 
Elegir manga
Entra a capítulo 
Error 403
Entro al navegador y si se ven los capítulos 
(En la web si se ven los capítulos)

### Mihon/Tachiyomi version

Mihon 0.19.3

### Android version

Android 11

### Other details

Es de las fuentes más usadas porfavor 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Closes #11803
Closes #11867

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt [hunk 1]
```diff
@@ -105,11 +112,8 @@ class IkigaiMangas : HttpSource(), ConfigurableSource {
 
     private val preferences: SharedPreferences = getPreferences()
 
-    private val lazyHeaders by lazy {
-        headersBuilder()
-            .set("Referer", fetchedDomainUrl)
-            .build()
-    }
+    override fun headersBuilder() = super.headersBuilder()
+        .set("Referer", fetchedDomainUrl)
```
Comment (vetleledaal) [inline src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt]:
```suggestion
        .set("Referer", "$fetchedDomainUrl/")
```

File: src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt [hunk 2]
```diff
@@ -173,7 +195,46 @@ class IkigaiMangas : HttpSource(), ConfigurableSource {
         apiUrl.addQueryParameter("column", sortByFilter?.selected ?: "name")
         apiUrl.addQueryParameter("direction", if (sortByFilter?.state?.ascending == true) "asc" else "desc")
 
-        return GET(apiUrl.build(), lazyHeaders)
+        return GET(apiUrl.build(), headers)
+    }
+
+    val scriptUrlRegex = """from"(.*?.js)"""".toRegex()
```
Comment (vetleledaal) [inline src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt]: `.*?.` is effectively `.+?`, you probably meant:
```suggestion
    val scriptUrlRegex = """from"(.*?\.js)"""".toRegex()
```

File: src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt [hunk 3]
```diff
@@ -222,7 +299,7 @@ class IkigaiMangas : HttpSource(), ConfigurableSource {
     }
 
     override fun pageListRequest(chapter: SChapter): Request =
-        GET(fetchedDomainUrl + chapter.url.substringBefore("#"), lazyHeaders)
+        GET(fetchedDomainUrl + chapter.url.substringBefore("#"), headers)
```
Comment (vetleledaal) [inline src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt:302]: Maybe use `HttpUrl` to remove fragment.

Comment (bapeey) [reply src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt:302]: Isn't a bit overkill?

Comment (vetleledaal) [reply src/es/ikigaimangas/src/eu/kanade/tachiyomi/extension/es/ikigaimangas/IkigaiMangas.kt:302]: Probably. Other half of the extension is also working directly with strings, so it's a bigger refactor.

**Review by vetleledaal — APPROVED** [review]
