### PR TITLE
[ru-Acomics] Fix parsing popular and search page

### LINKED ISSUE #6120: AComics: Extension doesnt work
### Source information

AComics 1.4.4

### Source language

Russia

### Steps to reproduce

1. Open search
2. Choose Acomics
3. "No results found"

### Expected behavior

Try search some comics and see then in Acomics source

### Actual behavior

Try search some comics, but acomics dont respond

### Mihon/Tachiyomi version

Mihon 0.17.0

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Pavkazzz**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

Closes #6120

### CODE REVIEW

File: src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt [hunk 1]
```diff
@@ -39,17 +40,32 @@ class AComics : ParsedHttpSource() {
...
+        element.selectFirst("h2 > a")!!.run {
             setUrlWithoutDomain(attr("href") + "/about")
             title = text()
         }
     }
 
-    override fun popularMangaNextPageSelector() = "span.button:not(:has(a)) + span.button > a"
+    override fun popularMangaNextPageSelector(): String? {
+        TODO("Not yet implemented")
+    }
```
Comment (AwkwardPeak7) [inline src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt]: either throw `UnsupportedOperationException` on set to empty string

File: src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt [hunk 2]
```diff
@@ -39,17 +40,32 @@ class AComics : ParsedHttpSource() {
...
+
+    override fun popularMangaParse(response: Response): MangasPage {
+        val document = response.asJsoup()
+
+        val mangas = document.select(popularMangaSelector()).map { element ->
+            popularMangaFromElement(element)
+        }
+
+        return MangasPage(mangas, true)
```
Comment (AwkwardPeak7) [inline src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt]: is there not some end page? maybe check number of entries on page and end page would have less.

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt [hunk 3]
```diff
@@ -39,17 +40,32 @@ class AComics : ParsedHttpSource() {
...
+        thumbnail_url = element.selectFirst("a > img")?.absUrl("data-real-src")
+        element.selectFirst("h2 > a")!!.run {
             setUrlWithoutDomain(attr("href") + "/about")
             title = text()
         }
     }
 
-    override fun popularMangaNextPageSelector() = "span.button:not(:has(a)) + span.button > a"
+    override fun popularMangaNextPageSelector(): String? {
+        TODO("Not yet implemented")
```
Comment (vetleledaal) [inline src/ru/acomics/src/eu/kanade/tachiyomi/extension/ru/acomics/AComics.kt]: You are looking for `a.infinite-scroll` after the last `div.infinite-scroll-content > section.serial-card`. That element only exists if there is more content to load. You can make it as advanced or basic as you want.

**Review by AwkwardPeak7 — APPROVED** [review]
