### PR TITLE
Fix SpectralScan: change url, change source name, preserve id, fix 'popular', 'latest', 'search', 'filters' and 'pages'

### LINKED ISSUE #10553: Spectral Scan: New website URL (Nexus Toons), `Nenhum resultado encontrado` error
### Source name

Spectral Scan 1.4.48

### Source link

https://nexustoons.site/

### Source language

Português Brasileiro - PT-BR 

### Other details

Image
Image

### Acknowledgements

- [x] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a meaningful title with the source name.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes: #10553

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by wesleymoura** [comment]
The site have pornhwa in the library, maybe the NSFW tag need to be true in the build.gradle just to be safe.

**Comment by FelipeGFA** [comment]
> The site have pornhwa in the library, maybe the NSFW tag need to be true in the build.gradle just to be safe.

sure why not

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 1]
```diff
@@ -0,0 +1,311 @@
...
+    // ==================== AJAX Manga List ==========================
+
+    private fun parseMangaListResponse(response: Response): MangasPage {
+        val result = response.parseAs<MangaListResponse>()
+        val document = Jsoup.parse(result.html, baseUrl)
+
+        val mangas = document.select("a.content-card[href*='/manga/']").map { element ->
+            SManga.create().apply {
+                setUrlWithoutDomain(element.attr("href"))
+                title = element.selectFirst(".font-semibold")?.text()?.trim() ?: ""
```
Comment (AwkwardPeak7) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]:
```suggestion
                title = element.selectFirst(".font-semibold")!!.text()
```
title is mandatory

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 2]
```diff
@@ -0,0 +1,311 @@
...
+        return parseMangaListResponse(response)
+    }
+
+    // ==================== Details =======================
+
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+
+        return SManga.create().apply {
+            title = document.selectFirst("h1.item-title, h1")?.text()?.trim() ?: ""
```
Comment (AwkwardPeak7) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]:
```suggestion
            title = document.selectFirst("h1.item-title, h1")!!.text()
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScanDto.kt [hunk 3]
```diff
@@ -74,3 +64,32 @@ val genreList = arrayOf(
...
+    "Manga" to "manga",
+    "Manhwa" to "manhwa",
+    "Manhua" to "manhua",
+    "Webtoon" to "webtoon",
+    "Comic" to "comic",
+    "HQ" to "hq",
+    "Pornhwa" to "pornhwa",
+)
+
+@kotlinx.serialization.Serializable
```
Comment (AwkwardPeak7) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScanDto.kt]: import

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 4]
```diff
@@ -0,0 +1,311 @@
...
+import okhttp3.Response
+import org.jsoup.Jsoup
+import rx.Observable
+import java.io.IOException
+import java.text.SimpleDateFormat
+import java.util.Locale
+
+class NexusScan : HttpSource() {
+
+    // Mantém o ID original para manter a compatibilidade com a extensão anterior (SpectralScan)
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Prefer English code comments, or something that doesn't require translation.
```suggestion
    // SpectralScan (pt-BR) -> Nexus Scan (pt-BR)
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 5]
```diff
@@ -0,0 +1,311 @@
...
+
+    override val baseUrl = "https://nexustoons.site"
+
+    override val supportsLatest = true
+
+    override val client = super.client.newBuilder()
+        .rateLimit(2)
+        .addInterceptor { chain ->
+            chain.proceed(chain.request()).also {
+                if (it.request.url.toString().contains("login")) {
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Do they use slugs? You might run into false positives if some manga has `login` in the title.

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 6]
```diff
@@ -0,0 +1,311 @@
...
+
+    // ==================== AJAX Manga List ==========================
+
+    private fun parseMangaListResponse(response: Response): MangasPage {
+        val result = response.parseAs<MangaListResponse>()
+        val document = Jsoup.parse(result.html, baseUrl)
+
+        val mangas = document.select("a.content-card[href*='/manga/']").map { element ->
+            SManga.create().apply {
+                setUrlWithoutDomain(element.attr("href"))
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]:
```suggestion
                setUrlWithoutDomain(element.absUrl("href"))
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 7]
```diff
@@ -0,0 +1,311 @@
...
+                    it.close()
+                    throw IOException("Faça o login na WebView para acessar o conteúdo")
+                }
+            }
+        }
+        .build()
+
+    private val dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.ROOT)
+
+    private fun ajaxHeaders() = headers.newBuilder()
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Why not `val`?

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 8]
```diff
@@ -0,0 +1,311 @@
...
+
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+
+        return SManga.create().apply {
+            title = document.selectFirst("h1.item-title, h1")?.text()?.trim() ?: ""
+            thumbnail_url = document.selectFirst("img.item-cover-image")?.absUrl("src")
+            description = document.select(".item-description p, .item-description").text()
+
+            genre = document.select(".genre-tag, .hero-genres .genre-tag").joinToString { it.text().trim() }
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: `.text()` is already trimmed.
```suggestion
            genre = document.select(".genre-tag, .hero-genres .genre-tag").joinToString { it.text() }
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 9]
```diff
@@ -0,0 +1,311 @@
...
+
+            // Procura autor/artista nos detalhes
+            document.select(".detail-item").forEach { item ->
+                val label = item.selectFirst(".detail-label")?.text()?.lowercase() ?: ""
+                val value = item.selectFirst(".detail-value")?.text()?.trim()
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]:
```suggestion
                val value = item.selectFirst(".detail-value")?.text()
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 10]
```diff
@@ -0,0 +1,311 @@
...
+                when {
+                    label.contains("autor") || label.contains("author") -> author = value
+                    label.contains("artista") || label.contains("artist") -> artist = value
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Others have also used `.any`, up to you if you want to use it:
```kt
listOf("giây", "giây trước").any { dateString.contains(it, ignoreCase = true) } -> {
listOf("ongoing", "publishing").any { this.contains(it, ignoreCase = true) } -> SManga.ONGOING
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 11]
```diff
@@ -0,0 +1,311 @@
...
+                    Observable.just(allChapters)
+                }
+            }
+    }
+
+    private fun parseChaptersFromHtml(html: String): List<SChapter> {
+        val document = Jsoup.parse(html, baseUrl)
+        return document.select("a.chapter-item[href]").map { element ->
+            SChapter.create().apply {
+                name = element.selectFirst(".chapter-number")?.text()?.trim()
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]:
```suggestion
                name = element.selectFirst(".chapter-number")?.text()
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 12]
```diff
@@ -0,0 +1,311 @@
...
+                if (page.has_next) {
+                    fetchRemainingChapters(slug, allChapters, currentPage + 1)
+                } else {
+                    Observable.just(allChapters)
+                }
+            }
+    }
+
+    private fun parseChaptersFromHtml(html: String): List<SChapter> {
+        val document = Jsoup.parse(html, baseUrl)
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt:259]: This won't get the correct context if the sites uses relative paths. Normally you would use `response.asJsoup()`, but you don't pass that to this function.

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 13]
```diff
@@ -0,0 +1,311 @@
...
+        return document.select("a.chapter-item[href]").map { element ->
+            SChapter.create().apply {
+                name = element.selectFirst(".chapter-number")?.text()?.trim()
+                    ?: element.attr("data-chapter-number")?.let { "Capítulo $it" }
+                    ?: "Capítulo"
+                setUrlWithoutDomain(element.absUrl("href").ifEmpty { element.attr("href") })
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: You shouldn't need `.ifEmpty` if `element` knows what page its on and knows how to resolve relative paths.
```suggestion
                setUrlWithoutDomain(element.absUrl("href"))
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 14]
```diff
@@ -0,0 +1,311 @@
...
+        currentPage: Int,
+    ): Observable<List<SChapter>> {
+        val url = "$baseUrl/ajax/load-chapters/".toHttpUrl().newBuilder()
+            .addQueryParameter("item_slug", slug)
+            .addQueryParameter("page", currentPage.toString())
+            .addQueryParameter("sort", "desc")
+            .addQueryParameter("q", "")
+            .build()
+
+        return client.newCall(GET(url, headers)).asObservableSuccess()
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Don't you also need `ajaxHeaders()` here? You're using the `/ajax/` endpoint.
```suggestion
        return client.newCall(GET(url, ajaxHeaders())).asObservableSuccess()
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 15]
```diff
@@ -0,0 +1,311 @@
...
+
+    override fun chapterListRequest(manga: SManga): Request {
+        val slug = getMangaSlug(manga.url)
+        val url = "$baseUrl/ajax/load-chapters/".toHttpUrl().newBuilder()
+            .addQueryParameter("item_slug", slug)
+            .addQueryParameter("page", "1")
+            .addQueryParameter("sort", "desc")
+            .addQueryParameter("q", "")
+            .build()
+        return GET(url, headers)
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Don't you also need `ajaxHeaders()` here? You're using the `/ajax/` endpoint.
```suggestion
        return GET(url, ajaxHeaders())
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 16]
```diff
@@ -0,0 +1,311 @@
...
+    override fun chapterListParse(response: Response) =
+        parseChaptersFromHtml(response.parseAs<ChapterListResponse>().chapters_html)
+
+    private fun parseChapterDate(dateStr: String): Long {
+        return try {
+            when {
+                dateStr.contains("hoje", ignoreCase = true) -> System.currentTimeMillis()
+                dateStr.contains("ontem", ignoreCase = true) -> System.currentTimeMillis() - 24 * 60 * 60 * 1000
+                dateStr.contains("hora", ignoreCase = true) -> {
+                    val hours = Regex("(\\d+)").find(dateStr)?.value?.toIntOrNull() ?: 1
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Extract regex out of function. You're recompiling it multiple times in this function. You also don't need a capture group. Use `"""` to avoid escaping backslashes.
```kt
val something = Regex(""""\d+""")
```

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 17]
```diff
@@ -0,0 +1,311 @@
...
+                }
+                dateStr.contains("semana", ignoreCase = true) -> {
+                    val weeks = Regex("(\\d+)").find(dateStr)?.value?.toIntOrNull() ?: 1
+                    System.currentTimeMillis() - weeks * 7 * 24 * 60 * 60 * 1000
+                }
+                dateStr.contains("mês", ignoreCase = true) || dateStr.contains("mes", ignoreCase = true) -> {
+                    val months = Regex("(\\d+)").find(dateStr)?.value?.toIntOrNull() ?: 1
+                    System.currentTimeMillis() - months * 30L * 24 * 60 * 60 * 1000
+                }
+                else -> dateFormat.parse(dateStr)?.time ?: 0L
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Use `tryParse` from `keiyoushi.utils`.

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 18]
```diff
@@ -0,0 +1,311 @@
...
+                    System.currentTimeMillis() - days * 24 * 60 * 60 * 1000
+                }
+                dateStr.contains("semana", ignoreCase = true) -> {
+                    val weeks = Regex("(\\d+)").find(dateStr)?.value?.toIntOrNull() ?: 1
+                    System.currentTimeMillis() - weeks * 7 * 24 * 60 * 60 * 1000
+                }
+                dateStr.contains("mês", ignoreCase = true) || dateStr.contains("mes", ignoreCase = true) -> {
+                    val months = Regex("(\\d+)").find(dateStr)?.value?.toIntOrNull() ?: 1
+                    System.currentTimeMillis() - months * 30L * 24 * 60 * 60 * 1000
+                }
```
Comment (vetleledaal) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: Consider using `java.util.Calendar`, you can see an example in Love4u. This is not the only example to draw inspiration from, just the first one I found. Could also check Zbulu, MangaGun, KomikCast, etc.
https://github.com/keiyoushi/extensions-source/blob/c00f88ee7f3e3c762af33c15e567a68b6aa877ce/src/ja/welovemangaone/src/eu/kanade/tachiyomi/extension/ja/welovemangaone/Love4u.kt#L43-L61

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt (hunk 12 above)
Comment (FelipeGFA) [reply src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt:259]: i am passing ```baseUrl``` as the second parameter to ```Jsoup.parse(html, baseUrl)```, which defines the base URI this ensures that ```absUrl("href")```, as you suggested, correctly converts relative paths (such as ```/leitor/123```) to absolute URLs
i checked and confirmed the hrefs are relative, so the current changes is handling them correctly or should i try a different approach?

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt (hunk 7 above)
Comment (FelipeGFA) [reply src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt]: created val for ajaxHeaders

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt [hunk 19]
```diff
@@ -0,0 +1,303 @@
...
+import rx.Observable
+import java.io.IOException
+import java.text.SimpleDateFormat
+import java.util.Calendar
+import java.util.Locale
+
+class NexusScan : HttpSource() {
+
+    // SpectralScan (pt-BR) -> Nexus Scan (pt-BR)
+    override val id = 5304928452449566995L
```
Comment (FelipeGFA) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt:36]: Also @vetleledaal this is correct? im not sure if this wll force user to migrate successfully

https://github.com/keiyoushi/extensions/blob/e9eb866f45acc9ac62a86ebb138162d3e754920f/index.json#L24405C1-L24409C23

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt (hunk 12 above)
Comment (vetleledaal) [reply src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt:259]: I meant relative paths that don't start with `/`, which requires the correct path, not just the domain. If the site doesn't use those then it matters less.

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt (hunk 19 above)
Comment (vetleledaal) [reply src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt:36]: If you keep the id, as you do here, users won't be forced to migrate. If you want to force it then you should remove this override and bump `versionId` by one. Even if the `id` would otherwise be different between `Spectral Scan` and `SpectralScan`, they are too close and may cause confusion.

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt (hunk 12 above)
Comment (FelipeGFA) [reply src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/NexusScan.kt:259]: ajax returns a html snippet and paths are always starts with `/` like: 
```
<a href="/manga/a-lenda-do-general-estelar/" ...>
<img src="https://cdn.nexustoons.site/manga_covers/..." ...>
```
```
<a href="/leitor/172691:kSEKNpGEyIG-mcY6N7FG7DXUFVWFKVNggroinKBbAmo/" ...>
<img src="https://cdn.nexustoons.site/manga_covers/..." ...>
```

so i think Jsoup.parse works just fine

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by JeffDoctor98** [comment]
Deu problema
