### PR TITLE
Fix MangaHub (multisrc) Chapter List Selector

### LINKED ISSUE #8357: Mangahub not showing full chapters
Image

### Source information

"Mangahub 1.4.40"

### Source language

"English"

### Steps to reproduce

1. Open a popular entry with more than 100 chapters;
2. Check the number of chapters on actual site;
3. Check number of chapters on the app.
Issue: Number of chapters do not match and there is an unlabeled chapter on the start.

### Expected behavior

"Number of chapters should match"

### Actual behavior

"Number of chapters do not match"

### Mihon/Tachiyomi version

"0.18.0"

### Android version

"Android 13"

### Other details

They somehow made it so the app cant retrieve past the first page I think.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by JakeeLuwi**
Closes #8357 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt [hunk 1]
```diff
@@ -276,7 +276,7 @@ abstract class MangaHub(
 
     private fun chapterFromElement(element: Element, head: Element): SChapter {
         val chapter = SChapter.create()
-        val potentialLinks = element.select("a[href*='$baseUrl/chapter/']:not([rel*=nofollow]):not([rel*=noreferrer])")
+        val potentialLinks = element.select("a[href*='$baseUrl/chapter/']")
```
Comment (vetleledaal) [inline lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt:279]: This (`:not(...)`) was probably added for a reason. Would it be possible to make this more robust? Check `git blame`, maybe. MangaHub tends to change frequently so the extension breaks.

Comment (JakeeLuwi) [reply lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt:279]: If I'm correct, there was a case before where there are multiple links (anchor) in the selected element that acts as a "fake" link (probably they use it to hardcode ad links) that the extension mistakenly parses. The only indicator that the link is fake is by the attributes specified in `:not`. Fast forward to today, they seem to have stopped doing that but also recently included those attributes on correct links. Some chapters (mostly chapters 1-100) do not have those attributes but the newer ones do, causing them to be excluded when parsing chapter lists.

I can't see any robust way of implementing that as there is no example case of them messing up the chapter list (or any other feature) heavily. The best thing to do right now is to just remove the `:not` selector to make the extension work as intended.

**Review by vetleledaal — APPROVED** [review]
