### PR TITLE
Read Mangas: Fix description

### LINKED ISSUE #7248: Read Mangas: Fix Description
### Source information

Read Mangas 1.4.35

### Source language

Portuguese

### Steps to reproduce

Example:

1. Enter the Read Mangas

Image

2. Enter the title Dominio Absoluto

Image

The title description is incorrect because of the escape word "\\" and you need to adjust the regex to remove the initial quotation marks..

Image

### Expected behavior

Fix description.

### Actual behavior

Just fetches the description '\\'.

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #7248 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt [hunk 1]
```diff
@@ -153,13 +154,16 @@ class ReadMangas() : HttpSource() {
         val document = response.asJsoup()
         return SManga.create().apply {
             title = document.selectFirst("h1")!!.text()
+
             thumbnail_url = document.selectFirst("img.w-full")?.absUrl("src")
+
             genre = document.select("div > label + div > div").joinToString { it.text() }
 
             description = document.select("script").map { it.data() }
                 .firstOrNull { MANGA_DETAILS_DESCRIPTION_REGEX.containsMatchIn(it) }
```
Comment (AwkwardPeak7) [inline src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: you don't need this regex to just check if it contains description

Comment (lordenecromante) [reply src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: Actually, it does need to, because there are multiple script elements inside the document, and we need to find the one that contains the description within.

Comment (choppeh) [reply src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: > Actually, it does need to, because there are multiple script elements inside the document, and we need to find the one that contains the description within.

You can use 

```kt
.firstOrNull { it.contains("description\":\"", ignoreCase = true) }
```

or


```kt
.firstOrNull { it.contains("description", ignoreCase = true) }
```

Comment (lordenecromante) [reply src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: > > Actually, it does need to, because there are multiple script elements inside the document, and we need to find the one that contains the description within.
> 
> You can use
> 
> ```kotlin
> .firstOrNull { it.contains("description\":\"", ignoreCase = true) }
> ```
> 
> or
> 
> ```kotlin
> .firstOrNull { it.contains("description", ignoreCase = true) }
> ```

I'll test it.

Comment (lordenecromante) [reply src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: @choppeh It worked, ty. Fix it.

**Review by AwkwardPeak7 — APPROVED** [review]
