### PR TITLE
fix: fix chapter name setter and add year based date uploaded

### LINKED ISSUE #13231: Readallcomics not showing chapter titles
### Source information

ReadAllComics

### Source language

English

### Steps to reproduce

1. Select any title from Readallcomics source.
2. No chapter title, chapter number or correct upload date from any chapter. Only blank space.

### Expected behavior

Show correct title or chapter number and upload date.

### Actual behavior

No title, chapter number or upload date from any chapter. Only blank space.

### Mihon/Tachiyomi version

0.19.3 Mihon

### Android version

android 16

### Other details

one ui 8.0

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by vcux**
closes https://github.com/keiyoushi/extensions-source/issues/13231

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 1]
```diff
@@ -126,28 +127,29 @@ class ReadAllComics : ParsedHttpSource() {
...
+        val year = elementText.substring(elementText.lastIndexOf('(') + 1, elementText.lastIndexOf(')'))
+        date_upload = dateFormat.tryParse("$year-1-1")
     }
 
-    override fun pageListParse(document: Document): List<Page> {
-        return document.select("body img:not(body div[id=\"logo\"] img)").mapIndexed { idx, element ->
-            Page(idx, "", element.attr("abs:src"))
-        }
+    override fun pageListParse(document: Document): List<Page> = document.select("body img:not(body div[id=\"logo\"] img)").mapIndexed { idx, element ->
+        Page(idx, "", element.attr("abs:src"))
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt:138]:
```suggestion
        Page(idx, imageUrl = element.attr("abs:src"))
```

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 2]
```diff
@@ -126,28 +127,29 @@ class ReadAllComics : ParsedHttpSource() {
 
     override fun chapterFromElement(element: Element) = SChapter.create().apply {
         setUrlWithoutDomain(element.attr("href"))
-        name = element.attr("title")
+        val elementText = element.text()
+        name = elementText
+        // can only get the year from chapter title
+        val year = elementText.substring(elementText.lastIndexOf('(') + 1, elementText.lastIndexOf(')'))
+        date_upload = dateFormat.tryParse("$year-1-1")
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt:134]: I don't think this works if your timezone is negative. Should set timezone explicitly.

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 3]
```diff
@@ -126,28 +127,29 @@ class ReadAllComics : ParsedHttpSource() {
 
     override fun chapterFromElement(element: Element) = SChapter.create().apply {
         setUrlWithoutDomain(element.attr("href"))
-        name = element.attr("title")
+        val elementText = element.text()
+        name = elementText
+        // can only get the year from chapter title
+        val year = elementText.substring(elementText.lastIndexOf('(') + 1, elementText.lastIndexOf(')'))
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]: Avoid juggling indices.
```suggestion
        val year = elementText.substringAfterLast('(').substringBefore(')')
```

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 4]
```diff
@@ -126,28 +127,29 @@ class ReadAllComics : ParsedHttpSource() {
 
     override fun chapterFromElement(element: Element) = SChapter.create().apply {
         setUrlWithoutDomain(element.attr("href"))
-        name = element.attr("title")
+        val elementText = element.text()
+        name = elementText
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]: You can just use `name` directly in this scope.
```suggestion
        name = element.text()
```

**Review by AwkwardPeak7 — APPROVED** [review]
