### PR TITLE
Kisslove: Change api

### LINKED ISSUE #12377: KissLove: `No results found` / `chapter id` error
### Source information

KissLove 1.4.16

### Source language

Japanese

### Steps to reproduce

1. Tried to read chapters on KissLove
2. Can read

### Expected behavior

Shld read manga chapters

### Actual behavior

Cannot read, chapter-id error instead

### Mihon/Tachiyomi version

TachiSY r584

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 2Loong6**
Close: #12377

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt [hunk 1]
```diff
@@ -1,88 +1,111 @@
...
     }
 
-    private fun parseChapterDate(date: String): Long {
-        val value = date.split(' ')[dateValueIndex].toInt()
-        val chapterDate = Calendar.getInstance().apply {
-            set(Calendar.SECOND, 0)
-            set(Calendar.MILLISECOND, 0)
-        }
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request =
+        GET("$baseUrl/api/search?q=$query", sigAppend())
```
Comment (vetleledaal) [inline src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt]: Use `HttpUrlBuilder` so queries are encoded correctly.

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/Dto.kt [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+) {
+    fun toSChapter(slug: String) = SChapter.create().apply {
+        url = "$id/$slug-chapter-$chapter"
+        name = this@Chapter.name?.takeIf { it.isNotBlank() } ?: "Chapter $chapter"
+
+        date_upload = try {
+            Instant.parse(lastUpdate).toEpochMilli()
+        } catch (e: Exception) {
+            0L
+        }
```
Comment (vetleledaal) [inline src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/Dto.kt]: Can you use `SimpleDateFormat` instead? To be explicit about the format. Also use `keiyoushi.utils.tryParse`.

**Review by vetleledaal — APPROVED** [review]
