### PR TITLE
TiaManhwa: Update mangaSubString

### LINKED ISSUE #9290: Tia Manhwa  HTTP error 404
### Source information

Tia Manhwa 1.4. 42

### Source language

Português (Brasil)

### Steps to reproduce

It's been a while since this error has been fixed or updated.

### Expected behavior

I've already checked the website and it's normal.

### Actual behavior

I have already cleared the cache and reopened the application, but the problem still persists. 

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15

### Other details

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #9290

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/tiamanhwa/src/eu/kanade/tachiyomi/extension/pt/tiamanhwa/TiaManhwa.kt [hunk 1]
```diff
@@ -17,7 +17,7 @@ class TiaManhwa : Madara(
         .rateLimit(2)
         .build()
 
-    override val mangaSubString = "manhwa-em-portugues"
+    override val mangaSubString = "pornhwa-em-portugues"
```
Comment (AwkwardPeak7) [inline src/pt/tiamanhwa/src/eu/kanade/tachiyomi/extension/pt/tiamanhwa/TiaManhwa.kt]: why not `manhwa`? which is the path the manga urls have on the site

**Review by vetleledaal — APPROVED** [review]
