### PR TITLE
fix kisslove

### LINKED ISSUE #3197: Kisslove: chapter not found. Http 404
### Source information

Kisslove 1.4.14

### Source language

Japanese

### Steps to reproduce

Open Kisslove, open a manga

### Expected behavior

Load chapter list and read.

### Actual behavior

no chapters
HTTP 404, check website in WebView
IMG_20240523_160304

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13

### Other details

Chapters show correctly in webview
IMG_20240523_160513

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by 2Loong6**
Closes #3197

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt [hunk 1]
```diff
@@ -70,13 +70,24 @@ class KissLove : FMReader("KissLove", "https://klz9.com", "ja") {
...
             .build()
 
         return GET(xhrUrl, headers)
     }
 
+    private fun generateRandomStr(length: Int): String {
+        val characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
+        val charactersLength = characters.length
+        var result = ""
+        for (i in 0..length) {
```
Comment (vetleledaal) [inline src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt]: This would add an extra character.

Also, this can mostly be replaced with:
```kt
return (1..length).map { characters.random() }.joinToString("")
```

Comment (2Loong6) [reply src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt]: Thank you.
It has been changed.

**Review by AwkwardPeak7 — APPROVED** [review]
