### PR TITLE
Kemono & Coomer | Fixed Latest, Added Filters, Increased Post Limit

### LINKED ISSUE #547: Kemono filter
### Source name

Kemono

### Source language

All

### Describe your suggested feature

Added a favorite filter feature so that it can be synchronized with logged in accounts

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #5336: Increase kemono page limit
### Source name

Kemono

### Source language

Multi

### Describe your suggested feature

Browsing the extension I found this profile (https://kemono.su/patreon/user/11946658) it has 61 pages and the extension limit is 50, so I request an increase in the limit. 

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #5336
Closes #547

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt [hunk 1]
```diff
@@ -63,69 +64,120 @@ open class Kemono(
...
-    ): MangasPage {
-        val imgCdnUrl = this.imgCdnUrl
+        val favores = client.newCall(GET("$baseUrl/$apiPath/account/favorites", headers)).execute()
+
+        var favourites: List<KemonoFavouritesDto> = emptyList()
+        if (fav != null) {
+            if (favores.code == 401) throw Exception("You are not Logged In")
+            favourites = favores.parseAs<List<KemonoFavouritesDto>>().filterNot { it.service.lowercase() == "discord" }
+        }
+
```
Comment (AwkwardPeak7) [inline lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt]: only fetch favorites if filter selected

File: lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt [hunk 2]
```diff
@@ -63,69 +64,120 @@ open class Kemono(
...
+                    mangas.sortedBy { it.updatedDate }
+                }
+            }
+        }
+        val maxIndex = mangas.size
+        val fromIndex = (page - 1) * PAGE_CREATORS_LIMIT
+        val toIndex = min(maxIndex, fromIndex + PAGE_CREATORS_LIMIT)
+
+        val final = sorted.subList(fromIndex, toIndex).map { it.toSManga(imgCdnUrl) }
+        return MangasPage(final, toIndex != maxIndex)
```
Comment (AwkwardPeak7) [inline lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt:181]: cache the results in the class to avoid fetching again on next page

File: lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt [hunk 3]
```diff
@@ -232,16 +285,55 @@ open class Kemono(
...
+        private const val PAGE_CREATORS_LIMIT = 50
         const val PROMPT = "You can change how many posts to load in the extension preferences."
 
-        private const val POST_PAGE_SIZE = 50
         private const val POST_PAGES_PREF = "POST_PAGES"
         private const val POST_PAGES_DEFAULT = "1"
-        private const val POST_PAGES_MAX = 50
-
-        private fun List<SManga>.filterUnsupported() = filterNot { it.author == "Discord" }
+        private const val POST_PAGES_MAX = 200
```
Comment (AwkwardPeak7) [inline lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt]: make it 75, 200 is too much calls

File: src/all/coomer/build.gradle [hunk 4]
```diff
@@ -3,7 +3,7 @@ ext {
     extClass = '.Coomer'
     themePkg = 'kemono'
     baseUrl = 'https://coomer.su'
-    overrideVersionCode = 0
+    overrideVersionCode = 1
```
Comment (AwkwardPeak7) [inline src/all/coomer/build.gradle]: no need when bumping baseVersion

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt (hunk 1 above)
Comment (KenjieDec) [reply lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt]: Nevermind my previous reply, thank you

File: lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt (hunk 2 above)
Comment (KenjieDec) [reply lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt:181]: Hello, thanks for the suggestion. But can explain to me on how I could achieve that? Thank you :pray:

Comment (AwkwardPeak7) [reply lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt:181]: basically cache result in variable

https://github.com/keiyoushi/extensions-source/blob/00bab8e7764de72d91c764688666535ffaafa051/src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/Comick.kt#L231-L236

Comment (KenjieDec) [reply lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt:181]: Thank you :pray:

**Review by AwkwardPeak7 — APPROVED** [review]
