### PR TITLE
SpyFakku | Fixed SpyFakku

### LINKED ISSUE #5294: Spyfakku 1.4.7
### Source information

Spyfakku 

### Source language

English 

### Steps to reproduce

Open source, no images, sources shows titles, but doesn't open.

### Expected behavior

To display images and read titles

### Actual behavior

Doesn't let you read.

### Mihon/Tachiyomi version

Tachij2k 1.74 

### Android version

14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #5294

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt [hunk 1]
```diff
@@ -95,116 +97,152 @@ class SpyFakku : HttpSource() {
...
+    }
+
     private fun Hentai.toSManga() = SManga.create().apply {
         title = this@toSManga.title
-        url = "/g/$id"
-        author = (circles?.emptyToNull() ?: artists)?.joinToString { it.name }
-        artist = artists?.joinToString { it.name }
-        genre = tags?.joinToString { it.name }
-        thumbnail_url = "$baseImageUrl/$hash/1/c"
+        url = "/g/$id?$pages&hash=$hash"
```
Comment (AwkwardPeak7) [inline src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt:157]: changing url means users would need to migrate, maybe fetch it in the page list methods(?) since it appears to be used there

Comment (KenjieDec) [reply src/en/spyfakku/src/eu/kanade/tachiyomi/extension/en/spyfakku/SpyFakku.kt:157]: Hello, sorry for the late reply. Does my recent change/commit align with what you're suggesting? Thank you.

**Review by AwkwardPeak7 — APPROVED** [review]
