### PR TITLE
Flame comics: Update data classes to match updated API responses

### LINKED ISSUE #11274: Flame Comics: `MissingFieldException: Field '...' is required` error
### Source information

Flame Comics

### Source language

English

### Steps to reproduce

Update a manga with sourced on Flame Comics or the whole library with one mange being sourced. 

### Expected behavior

Should get the latest chapters.

### Actual behavior

The following error is shown:
```
Field 'images' is required for type with serial name 'eu.kanade.tachiyomi.extension.en.flamecomics.Chapter', but it was missing at path: $.pageProps.chapters[0]
```

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by kiryl-kvit**
Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

Closes #11274

### CODE REVIEW

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 1]
```diff
@@ -176,10 +176,12 @@ class FlameComics : HttpSource() {
...
     override fun mangaDetailsParse(response: Response): SManga = SManga.create().apply {
         val seriesData =
-            json.decodeFromString<MangaPageData>(response.body.string()).pageProps.series
+            json.decodeFromString<MangaDetailsResponseData>(response.body.string()).pageProps.series
         title = seriesData.title
         thumbnail_url = thumbnailUrl(seriesData)
-        description = Jsoup.parseBodyFragment(seriesData.description).wholeText()
+        description = seriesData.description
+            ?.let { Jsoup.parseBodyFragment(it).wholeText() }
+            ?: "No description"
```
Comment (Amejonah1200) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Isn't `description` nullable in `SManga`? Why provide a value here when it's optional?

Consider representing and giving back exactly what the API is giving back. As this extension isn't directly UI related, let the App decide itself of what to display if a description is missing.

Comment (pa2x2) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Yeah, you're right. Thanks

**Review by AwkwardPeak7 — APPROVED** [review]
