### PR TITLE
Jiangzaitoon: update domain, fix blurry thumbnails

### LINKED ISSUE #8771: Jiangzaitoon url changed
### Source information

Jiangzaitonn 1.4.53

### Source language

Turkish

### Source new URL

https://jiangzaitoon.lgbt/

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by vetleledaal**
Madara was also updated to allow overriding `String.getSrcSetImage()`, not bumping the multisrc.

Closes #8771

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/tr/jiangzaitoon/src/eu/kanade/tachiyomi/extension/tr/jiangzaitoon/Jiangzaitoon.kt [hunk 1]
```diff
@@ -22,4 +22,28 @@ class Jiangzaitoon : Madara(
...
+    override fun String.getSrcSetImage(): String? {
+        /* Assumption: URL is absolute
+         * Assumption: descriptor is always in width
+         */
+        return this
+            .split(",")
+            .map(String::trim)
+            .mapNotNull { candidate ->
+                candidate
+                    .trim()
```
Comment (stevenyomi) [inline src/tr/jiangzaitoon/src/eu/kanade/tachiyomi/extension/tr/jiangzaitoon/Jiangzaitoon.kt]: Trimmed twice?

**Review by stevenyomi — APPROVED** [review]
