### PR TITLE
ComiciViewer: support api

### LINKED ISSUE #12777: ComicRide
### Source information

1.4.1

### Source language

Japanese 

### Steps to reproduce

Open the title and pull down to refresh the page.

### Expected behavior

I expect the chapter list to be updated. 

### Actual behavior

When I try to refresh the chapters page, I get an error. 

Image

### Mihon/Tachiyomi version

Mihon 0.19.1

### Android version

14 and 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by manti-X**
Closes #12777 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/comiciviewer/src/eu/kanade/tachiyomi/multisrc/comiciviewer/ComiciViewer.kt [hunk 1]
```diff
@@ -112,52 +160,94 @@ abstract class ComiciViewer(
...
-        val document = response.asJsoup()
-        return SManga.create().apply {
-            title = document.select("h1.series-h-title span").last()!!.text()
-            author = document.select("div.series-h-credit-user").text()
-            artist = author
-            description = document.selectFirst("div.series-h-credit-info-text-text")?.text()
-            genre = document.select("a.series-h-tag-link").joinToString { it.text().removePrefix("#") }
-            thumbnail_url = document.selectFirst("div.series-h-img source")?.attr("data-srcset")?.substringBefore(" ")?.let { "https:$it" }
+        if (apiUrl != null) {
+            val seriesHash = response.request.url.pathSegments.last()
```
Comment (AwkwardPeak7) [inline lib-multisrc/comiciviewer/src/eu/kanade/tachiyomi/multisrc/comiciviewer/ComiciViewer.kt]: response is not being used here, override mangaDetailsRequest

File: lib-multisrc/comiciviewer/src/eu/kanade/tachiyomi/multisrc/comiciviewer/ComiciViewer.kt [hunk 2]
```diff
@@ -166,43 +256,72 @@ abstract class ComiciViewer(
...
-                    throw Exception("Failed to get page list")
+        val newHeaders = super.headersBuilder()
+            .set("Referer", response.request.url.toString())
+            .build()
+
+        var comiciViewerId: String? = null
+        var memberJwt: String? = null
+
+        if (apiUrl != null) {
+            val episodeId = response.request.url.pathSegments.last()
```
Comment (AwkwardPeak7) [inline lib-multisrc/comiciviewer/src/eu/kanade/tachiyomi/multisrc/comiciviewer/ComiciViewer.kt]: same here

**Review by AwkwardPeak7 — COMMENTED** [review]
all mehods have separate code path for apiurl. maybe should make a separate multisrc?

**Review by AwkwardPeak7 — APPROVED** [review]
