### PR TITLE
BlossomManhwa (Multi): Update endpoint and add image decryption 

### LINKED ISSUE #14414: BlossomManhwa: Search/settings (API) crashes the app, new website URL (`cherrymanhwa.com`)
### Source information

blossommanhwa  1.4.4

### Source language

multi

### Source new URL

https://cherrymanhwa.com/

### Other details

Previously the source had a 401 error when opening webview in any series

Image

### Acknowledgements

- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have checked WebView to see the source's main URL is not up-to-date, or has to redirect into the new URL.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues/) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by disk-iq8**
Closes #14414 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/sakuramanhwa/src/eu/kanade/tachiyomi/extension/all/sakuramanhwa/CryptoHelper.kt [hunk 1]
```diff
@@ -98,12 +101,26 @@ class CryptoHelper(
...
-        if (request.headers["NX"] == null && request.url.toString().startsWith(baseUrl)) {
+        if (request.url.fragment == "DECRYPT") {
+            val response = chain.proceed(request)
+            if (!response.isSuccessful || response.body == null) throw Exception("Failed to decrypt image")
+
+            val decryptedBytes = decryptImage(response.body.bytes())
+            return response.newBuilder()
+                .body(decryptedBytes.toResponseBody(response.body.contentType()))
+                .build()
+        } else if (request.headers["NX"] == null && request.url.toString().startsWith(baseUrl)) {
```
Comment (vetleledaal) [inline src/all/sakuramanhwa/src/eu/kanade/tachiyomi/extension/all/sakuramanhwa/CryptoHelper.kt]: Compare against the domain directly, via HttpUrl.
```suggestion
        } else if (request.headers["NX"] == null && request.url.host == baseUrl.toHttpUrl().host) {
```

**Review by AwkwardPeak7 — APPROVED** [review]
