### PR TITLE
MyReadingManga: Update URLs and Selectors for new website layout

### LINKED ISSUE #10026: MyReadingManga: `No results found` / `HTTP 404` error when browsing/searching
### Source information

Myreadingmanga 1.4.58

### Source language

All

### Steps to reproduce

Enter the extension

Use the search or filter function 

### Expected behavior

The results related to the search should appear. 

### Actual behavior

it gives no result 

### Mihon/Tachiyomi version

0.19.0

### Android version

Android 15

### Other details

No results appear in global searches either. 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by rsyh93**
Fixes #10026

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt [hunk 1]
```diff
@@ -46,8 +46,9 @@ open class MyReadingManga(override val lang: String, private val siteLang: Strin
     override val supportsLatest = true
 
     // Popular - Random
+    // Should this use '/popular' ?
```
Comment (AwkwardPeak7) [inline src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt]: if there is popular listing then yes

File: src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt [hunk 2]
```diff
@@ -78,33 +79,34 @@ open class MyReadingManga(override val lang: String, private val siteLang: Strin
...
+        if (document.location().contains("/page/1")) mangaParsedSoFar = 0
         val mangas = document.select(searchMangaSelector()).map { searchMangaFromElement(it) }
             .also { mangaParsedSoFar += it.count() }
-        val totalResults = Regex("""(\d+)""").find(document.select("div.res_info").text())?.groupValues?.get(1)?.toIntOrNull() ?: 0
+        val totalResults = Regex("""([\d,]+)""").find(document.select(".ep-search-count").text())?.groupValues?.get(1)?.replace(",", "")?.toIntOrNull() ?: 0
         return MangasPage(mangas, mangaParsedSoFar < totalResults)
     }
-    override fun searchMangaFromElement(element: Element) = buildManga(element.select("a").first()!!, element.select("img").first())
+
+    // override fun searchMangaFromElement(element: Element) = buildManga(element.select("a").first()!!, element.select("img").first())
```
Comment (AwkwardPeak7) [inline src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt]: remove commented

Comment (rsyh93) [reply src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt]: removed

File: src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt (hunk 1 above)
Comment (rsyh93) [reply src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt]: I realized the popular page does not filter by language, which is probably why it's not used. I will leave this as is and remove my comment.

**Review by AwkwardPeak7 — APPROVED** [review]
