### PR TITLE
ArgosScan: Fix popular manga

### LINKED ISSUE #9954: Argos Scan não  funciona mais
### Source name

Argos Scan

### Source language

Português Brasil  - PT-BR

### Source link

https://argoscomics.online/

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source website is down.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a meaningful title with the source name.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #9954

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/argosscan/src/eu/kanade/tachiyomi/extension/pt/argosscan/ArgosScan.kt [hunk 1]
```diff
@@ -75,18 +71,19 @@ class ArgosScan : ParsedHttpSource() {
 
     // ============================ Search ======================================
 
-    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
-        val url = baseUrl.toHttpUrl().newBuilder()
-            .addQueryParameter("s", query)
-            .build()
-        return GET(url, headers)
+    override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
+        return fetchPopularManga(page).map { (mangas, _) ->
```
Comment (AwkwardPeak7) [inline src/pt/argosscan/src/eu/kanade/tachiyomi/extension/pt/argosscan/ArgosScan.kt]: I belive this will not work of tachi sy, since `MangasPage` isn't a data class there, so it doesn't have `component` functions
```kt
val mangas = fetchPopularManga(page).mangas
...
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by stevenyomi — APPROVED** [review]
