### PR TITLE
Happymh: Fix temporary chapter url issue.

### LINKED ISSUE #6639: Happymh update issue
### Source information

Happymh 1.4.15

### Source language

Chinese

### Steps to reproduce

1. when i update my library on another day.
2. yesterday unread episode will mark as read.

### Expected behavior

unread episode should be remain unread not mark as read or disappear

### Actual behavior

old unread episode mark as read. they just disappear.

### Mihon/Tachiyomi version

0.17.1

### Android version

11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AlphaBoom**
Closes #6639 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 1]
```diff
@@ -194,25 +202,49 @@ class Happymh : HttpSource(), ConfigurableSource {
...
+        return baseUrl + (chapterUrlToCode.get(chapter.url)?.let { "/mangaread/$it" } ?: chapter.url)
     }
 
     // Pages
 
+    private fun fetchChapterCode(chapter: SChapter): String? {
+        val expectPage = chapter.url.substringAfterLast("#").toIntOrNull() ?: 1
+        val pathSegments = chapter.url.substringBeforeLast("#").split("/")
+        val comicId = pathSegments[1]
+        val chapterId = pathSegments[3].toLong()
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]: Just use [`HttpUrl.pathSegments`](https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.html#pathSegments--)

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 2]
```diff
@@ -194,25 +202,49 @@ class Happymh : HttpSource(), ConfigurableSource {
...
 
     override fun getChapterUrl(chapter: SChapter): String {
-        return baseUrl + chapter.url
+        return baseUrl + (chapterUrlToCode.get(chapter.url)?.let { "/mangaread/$it" } ?: chapter.url)
     }
 
     // Pages
 
+    private fun fetchChapterCode(chapter: SChapter): String? {
+        val expectPage = chapter.url.substringAfterLast("#").toIntOrNull() ?: 1
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]: Use [`HttpUrl.fragment`](https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.html#fragment--)

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 3]
```diff
@@ -194,25 +202,49 @@ class Happymh : HttpSource(), ConfigurableSource {
...
+                code = resp.items.find { it.id == chapterId }?.codes
+                end = resp.isPageEnd()
+                page += 1
+            }
+        }
+        if (code == null) {
+            return null
+        }
+        chapterUrlToCode.put(chapter.url, code)
+        return code
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]:
```suggestion
        return code?.also { chapterUrlToCode.put(chapter.url, it) }
```

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 4]
```diff
@@ -194,25 +202,49 @@ class Happymh : HttpSource(), ConfigurableSource {
...
+        if (code == null) {
+            // Do full search for find target code
+            var page = 1
+            var end = false
+            while (!end && code == null) {
+                val resp = fetchChapterByPage(comicId, page)
+                code = resp.items.find { it.id == chapterId }?.codes
+                end = resp.isPageEnd()
+                page += 1
+            }
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt:233]:
```kt
            generateSequence(1) { it + 1 }
                .map { fetchChapterByPage(comicId, it) }
                .takeWhile { !it.isPageEnd() }
                .flatMap { it.items }
                .find { it.id == chapterId }
                ?.codes?.also { code = it }
```

Maybe? Since I can't reproduce the original issue I could not test properly.

**Review by vetleledaal — CHANGES_REQUESTED** [review]

**Review by AlphaBoom — COMMENTED** [review]
Apply suggestions

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt (hunk 4 above)
Comment (AlphaBoom) [reply src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt:233]: The `takeWhile `method discards items that do not meet the specified condition , which means it will discard the data from the last page. In this case, I need a `takeUntil `method, but it seems that Kotlin does not provide one. If I were to implement it specifically, I think it would be better not to use the `Stream `form at all.

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 5]
```diff
@@ -151,41 +153,47 @@ class Happymh : HttpSource(), ConfigurableSource {
...
             .addQueryParameter("lang", "cn")
             .addQueryParameter("order", "asc")
             .addQueryParameter("page", "$page")
             .build()
         return client.newCall(GET(url, headers)).execute().parseAs<ChapterByPageResponse>().data
     }
 
-    private fun fetchChapterByPageObservable(
+    private fun fetchChapterByPage(manga: SManga, page: Int): ChapterByPageResponseData {
+        val comicId = manga.url.substringAfterLast("/")
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]: Convert to `HttpUrl` and get the last element of `pathSegments` instead

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 6]
```diff
@@ -151,41 +153,47 @@ class Happymh : HttpSource(), ConfigurableSource {
...
+                Observable.just(page to it)
             } else {
-                Observable.just(it).concatWith(fetchChapterByPageObservable(manga, page + 1))
+                Observable.just(page to it).concatWith(fetchChapterByPageAsObservable(manga, page + 1))
             }
         }
     }
 
     override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> {
+        val comicId = manga.url.substringAfterLast("/")
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]: Convert to `HttpUrl` and get the last element of `pathSegments` instead

**Review by vetleledaal — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]

**Review by vetleledaal — APPROVED** [review]
