### PR TITLE
NihonKuni: simplify chapter selection

### LINKED ISSUE #14406: nihonkuni failed to load
### Source information

nihonkuni1.4.17

### Source language

japanese

### Steps to reproduce

Failed to read the manga chapter.

### Expected behavior

Read the manga chapter

### Actual behavior

Failed to read the manga chapter.

### Mihon/Mihon fork version

komikku1.13.5

### Android version

android13

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by neoto**
Closes #14406

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt [hunk 1]
```diff
@@ -116,13 +115,10 @@ class MangaGun : FMReader("NihonKuni", "https://$DOMAIN", "ja") {
...
 
     override fun pageListParse(document: Document): List<Page> {
-        val html = document.select("script:containsData(window.chapterImages)").first()!!.data()
-            .substringAfter("window.chapterImages=\"").substringBefore("\"")
-            .replace("\\/", "/")
-            .replace("\\n", "")
-            .replace("\\r", "")
-        return Jsoup.parse(html).select("img.chapter-img").mapIndexed { index, element ->
-            Page(index, imageUrl = element.attr("abs:data-srcset").trim())
+        val images = document.select("img[id~=page\\d+]")
```
Comment (neoto) [inline src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt:118]: Even though I probably could have just changed the id of the container to the new one, I thought that directly targeting the images was more resistant to breakage. It also helps that the new logic is much simpler than before.

File: src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt [hunk 2]
```diff
@@ -116,13 +115,10 @@ class MangaGun : FMReader("NihonKuni", "https://$DOMAIN", "ja") {
...
+
+        return images.mapIndexed { index, element ->
+            Page(index, imageUrl = element.attr("src"))
```
Comment (bapeey) [inline src/ja/mangagun/src/eu/kanade/tachiyomi/extension/ja/mangagun/MangaGun.kt]: Use `abs:src` or `getImgAttr` like in other code places
```suggestion
            Page(index, imageUrl = element.attr("abs:src"))
```

**Review by vetleledaal — APPROVED** [review]
