### PR TITLE
SeriManga: Fix date locale

### LINKED ISSUE #1580: SeriManga is broken
### Source information

SeriManga 1.4.4

### Source language

Turkish

### Steps to reproduce

1. Try to view a manga.
2. It only shows a toast of a date....

### Expected behavior

It should load chapters

### Actual behavior

It doesn't show any chapter.
Screenshot_20240227-153951
Same goes for all manga in this source. 
Also it doesn't load all manga thumbnails.
Screenshot_20240227-154028

### Mihon/Tachiyomi version

1.7.4

### Android version

Android 11

### Other details

The website is fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by sinkableShip**
Closes #1580 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
add try catch around date parsing too so such issue doesn't prevent extension from loading chapters

File: src/tr/serimanga/src/eu/kanade/tachiyomi/extension/tr/serimanga/SeriManga.kt [hunk 1]
```diff
@@ -1,5 +1,6 @@
 package eu.kanade.tachiyomi.extension.tr.serimanga
 
+import android.util.Log
```
Comment (AwkwardPeak7) [inline src/tr/serimanga/src/eu/kanade/tachiyomi/extension/tr/serimanga/SeriManga.kt]:
```suggestion
```

File: src/tr/serimanga/src/eu/kanade/tachiyomi/extension/tr/serimanga/SeriManga.kt [hunk 2]
```diff
@@ -105,12 +109,17 @@ class SeriManga : ParsedHttpSource() {
     override fun chapterFromElement(element: Element) = SChapter.create().apply {
         setUrlWithoutDomain(element.select("a").attr("href"))
         name = "${element.select("span").first()!!.text()}: ${element.select("span")[1].text()}"
-        date_upload = dateFormat.parse(element.select("span")[2].ownText())?.time ?: 0
+        date_upload = try {
+            dateFormat.parse(element.select("span")[2].ownText())?.time ?: 0
+        } catch (e: ParseException) {
+            Log.e("SeriManga", e.toString())
```
Comment (AwkwardPeak7) [inline src/tr/serimanga/src/eu/kanade/tachiyomi/extension/tr/serimanga/SeriManga.kt]:
```suggestion
```

**Review by AwkwardPeak7 — COMMENTED** [review]
no need for log

**Review by AwkwardPeak7 — APPROVED** [review]
