### PR TITLE
ManhwasMen: fix sources not loading mangas

### LINKED ISSUE #4220: [Manhwas Men] No results found
### Source information

eu.kanade.tachiyomi.extension.en.manhwasmen 1.4.36

### Source language

English

### Steps to reproduce

1. install extension
2. check if site is working in normal browser (and yes, it's working)
3. open extension

### Expected behavior

should showing items normally as it should be.

### Actual behavior

it's showing error "no results found" even if I just open extension in popular/lastest.

### Mihon/Tachiyomi version

1.10.5 (SY)

### Android version

Android 14

### Other details

Source is not dead...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by whitebeardhelper**
Closes #4220

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/manhwasmen/src/eu/kanade/tachiyomi/extension/en/manhwasmen/ManhwasMen.kt [hunk 1]
```diff
@@ -66,27 +85,41 @@ class ManhwasMen : Madara("Manhwas Men", "https://manhwas.men", "en") {
...
-                    else -> SManga.UNKNOWN
+        val profileManga = document.selectFirst(".anime-single")!!
+        return SManga.create().apply {
+            title = profileManga.selectFirst(".title")!!.text()
+            thumbnail_url = profileManga.selectFirst("img")!!.attr("abs:src")
+            description = profileManga.selectFirst(".sinopsis")!!.text()
+            status = parseStatus(profileManga.select("span.anime-type-peli").last()!!.text())
+            genre = profileManga.select("p.genres > span").joinToString { it.text() }
+            profileManga.selectFirst(altNameSelector)?.ownText()?.let {
+                if (it.isBlank().not() && it.notUpdating()) {
```
Comment (stevenyomi) [inline src/en/manhwasmen/src/eu/kanade/tachiyomi/extension/en/manhwasmen/ManhwasMen.kt]:
```suggestion
                if (it.isNotBlank() && it.notUpdating()) {
```

**Review by stevenyomi — COMMENTED** [review]
Note: some selectors look like [`es.manhwasnet`](https://github.com/keiyoushi/extensions-source/blob/main/src/es/manhwasnet/src/eu/kanade/tachiyomi/extension/es/manhwasnet/ManhwasNet.kt) and [`es.tumangasnet`](https://github.com/keiyoushi/extensions-source/blob/main/src/es/tumangasnet/src/eu/kanade/tachiyomi/extension/es/tumangasnet/TuMangasNet.kt).

**Review by stevenyomi — APPROVED** [review]
