### PR TITLE
MediocreToons: fix api parse + add login suport through webview

### LINKED ISSUE #12566: Medíocre Toons `HTTP 401`
### Source information

Mediocre Toons 1.4.11

### Source language

Português Brasileiro

### Steps to reproduce

Está com login e senha nas configurações mas não aparace o catálogo de obras

Image

### Expected behavior

Que a extensão funcione normalmente

Image

### Actual behavior

Ocorrência do Erro 401

Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 14

### Other details

As obras aparece na aba recentes mas quando pesquisa algo, não funciona mais.
O site tem dois urls de acesso, o link usado na extensão está tendo erro na verificação cloudflare.

Image
Image
Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes #12566

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt [hunk 1]
```diff
@@ -61,164 +63,100 @@ class MediocreToons : HttpSource(), ConfigurableSource {
...
+                    }
                 }
-            } else {
-                val errorBody = response.body.string()
-                null
             }
-        } catch (e: Exception) {
-            e.printStackTrace()
-            null
+            webView.loadUrl(baseUrl)
```
Comment (AwkwardPeak7) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToons.kt]: use `loadDataWithBaseUrl` and pass empty string for body, you don't need to load the actual site in webview.

**Review by AwkwardPeak7 — APPROVED** [review]
