### PR TITLE
Manhastro: Fix manga status and add icon

### LINKED ISSUE #2033: Manhastro don't show status
### Source information

Manhastro 1.4.37

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Open the app
2. Go to manhastro on sources
3. Chose any manga

### Expected behavior

Show status

### Actual behavior

Don't show status

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 14

### Other details

The same manga on mihon and on manhastro website. In the site has status.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #2033

Checklist:

- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/pt/manhastro/src/eu/kanade/tachiyomi/extension/pt/manhastro/Manhastro.kt [hunk 1]
```diff
@@ -26,6 +26,8 @@ class Manhastro : Madara(
 
     override val mangaDetailsSelectorTitle = "div.summary_content h2"
 
+    override val mangaDetailsSelectorStatus = "div.post-status .post-content_item:nth-child(2) > .summary-content"
```
Comment (vetleledaal) [inline src/pt/manhastro/src/eu/kanade/tachiyomi/extension/pt/manhastro/Manhastro.kt]: Could change position

```suggestion
    override val mangaDetailsSelectorStatus = "div.summary-heading:contains(Status) + div.summary-content"
```

Comment (choppeh) [reply src/pt/manhastro/src/eu/kanade/tachiyomi/extension/pt/manhastro/Manhastro.kt]: Cool, I was just using standard(spec) CSS selectors.

**Review by AwkwardPeak7 — APPROVED** [review]
