### PR TITLE
Hiperdex: Update domain and fix search

### LINKED ISSUE #9742: Hiperdex change url
### Source information

Hiperdex 1.4.60

### Source language

English

### Source new URL

https://hiperdex.tv

### Other details

I screenshot the change and problem

Image
Image
Image
Image
Image

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by whitebeardhelper**
Closes #9742

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Smol-Ame** [comment]
What about the search function?

**Comment by whitebeardhelper** [comment]
Sorry, I didn't notice the functionality wasn't working, working on it now

**Comment by whitebeardhelper** [comment]
@Smol-Ame would you mind reviewing it again, please?

File: src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt [hunk 1]
```diff
@@ -53,6 +59,34 @@ class Hiperdex :
         addRandomUAPreferenceToScreen(screen)
     }
 
+    override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
+        return client.newCall(searchRequest(page, query, filters))
```
Comment (stevenyomi) [inline src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt]: Override these more specific properties and functions instead:
```kotlin
fun searchMangaSelector(): String

val searchMangaUrlSelector: String

// if "#loop-content" check is required
fun searchMangaParse(response: Response): MangasPage
```

File: src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt [hunk 2]
```diff
@@ -59,32 +55,24 @@ class Hiperdex :
...
+                manga.setUrlWithoutDomain(it.attr("abs:href"))
+                manga.title = it.attr("title")
             }
+            selectFirst("img")?.let {
+                manga.thumbnail_url = imageFromElement(it)
+            }
+        }
+
+        return manga
     }
```
Comment (stevenyomi) [inline src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt]: The original `searchMangaUrlSelector` already works. Keep the override of `searchMangaSelector()` and remove the rest.

File: src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt (hunk 1 above)
Comment (whitebeardhelper) [reply src/en/hiperdex/src/eu/kanade/tachiyomi/extension/en/hiperdex/Hiperdex.kt]: Overrode searchMangaFromElement instead of searchMangaParse to correctly retrieve the title, reusing the same element as searchMangaUrlSelector to avoid selecting an additional element solely for the title. Overriding searchMangaParse was unnecessary.

**Review by stevenyomi — APPROVED** [review]
