### PR TITLE
Arven Scans: Update theme

### LINKED ISSUE #10479: Arven Scans not working
### Source information

Arven Scans 1.4.43

### Source language

English 

### Steps to reproduce

Go to Browse/Sources
Select Arven Scans

### Expected behavior

Should show Manga/Manhwa lists

### Actual behavior

Not showing Manga/Manhwa lists
Not showing up in webview either (site working on normal browser)

Image
Image

### Mihon/Tachiyomi version

Mihon 0.19.0 / Yōkai v1.9.7.3

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Smol-Ame**
Closes #10479
* Changed theme from Keyoapp to Madara
* Added `mangaSubString` override

After-edit:
* The extension overall works fine, with searching, reading, viewing an entry after the above changes, but switching this to draft PR due to the issue below, as I have no idea how to proceed next (if someone has a better fix, please feel free to supercede this PR):
* Seems like the source has a pretty harsh rate-limit currently, browsing about 6 new entries (within 20-30 seconds) or updating more than 8-10 entries could get you rate-limited/HTTP 429 error for a minute or two.
* It could also the reason for random "No chapters found" when updating the Library, but I am unsure.

After after-edit:
* Uses newChapterEndpoint
* Added a `1` rate-limit to mitigate/avoid source's rate-limit/HTTP 429 issues.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/arvencomics/src/eu/kanade/tachiyomi/extension/en/arvencomics/ArvenComics.kt [hunk 1]
```diff
@@ -1,12 +1,15 @@
...
+class ArvenComics : Madara(
     "Arven Scans",
     "https://arvencomics.com",
     "en",
 ) {
-    // migrated from Mangathemesia to Keyoapp
-    override val versionId = 2
+    // migrated from Keyoapp to Madara
+    override val versionId = 3
+    override val id = 640484333556017983
```
Comment (bapeey) [inline src/en/arvencomics/src/eu/kanade/tachiyomi/extension/en/arvencomics/ArvenComics.kt]: The point of bumping `versionId` is to change the autogenerated id (so users migrate), so setting the same id again doesn’t make sense.

The 'No chapters found' issue could be due to the rate limit, since the extension doesn’t check the status code in the `xhrChapterResponse`

File: src/en/arvencomics/src/eu/kanade/tachiyomi/extension/en/arvencomics/ArvenComics.kt
Comment (AwkwardPeak7) [inline src/en/arvencomics/src/eu/kanade/tachiyomi/extension/en/arvencomics/ArvenComics.kt:1]: set `useNewChapterEndpoint` to true

since the site makes call to `/ajax/chapters/` endpoint to get chapters

**Review by AwkwardPeak7 — APPROVED** [review]
