### PR TITLE
fix(fr/scanmanga): hide mihon

### LINKED ISSUE #14170: Scan-Manga: `Unexpected error while fetching lel.` error
### Source information

1.4.15

### Source language

French

### Steps to reproduce

1. Read any chapter

### Expected behavior

Load images

### Actual behavior

"Unexpected error while fetching lel."

### Mihon/Mihon fork version

Mihon 0.19.4

### Android version

Android 16

### Other details

Broken at 17h21 UTC+1

Here we go again

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Starmania**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

Closes #14170

### CODE REVIEW

File: src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt [hunk 1]
```diff
@@ -78,6 +78,8 @@ class ScanManga :
             .add("X-Requested-With", "")
     }
 
+    private fun fetchHeadersBuilder(): Headers.Builder = headersBuilder().removeAll("X-Requested-With")
```
Comment (AwkwardPeak7) [inline src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt]: add an interceptor to always remove empty `X-Requested-With` header

**Review by AwkwardPeak7 — APPROVED** [review]
