### PR TITLE
MangaTaro multisrc, fix RoliaScan

### LINKED ISSUE #14627: Rolia Scan: URL Change
### Source information

Rolia Scan 1.4.7

### Source language

English

### Source new URL

https://roliascans.org/

### Other details

Old URL (https://roliascan.com) redirects to the new one but always redirects to the root. 

### Acknowledgements

- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have checked WebView to see the source's main URL is not up-to-date, or has to redirect into the new URL.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues/) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by luigidotmoe**
Closes #14627

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/mangataro/src/eu/kanade/tachiyomi/multisrc/mangataro/Filters.kt [hunk 1]
```diff
@@ -100,7 +101,7 @@ class SortFilter(
     }
 }
 
-private val tags = listOf(
+val mangaTaroTags = listOf(
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangataro/src/eu/kanade/tachiyomi/multisrc/mangataro/Filters.kt]: move these to mangataro source if they are not shared

File: lib-multisrc/mangataro/AndroidManifest.xml
Comment (AwkwardPeak7) [inline lib-multisrc/mangataro/AndroidManifest.xml:1]: move it to the multisrc, along with the urlactivity. see Madara implementation

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by darwin-256** [comment]
Discord_ljC4uAZeJm

you need to change all to .com for roliascan

**Review by AwkwardPeak7 — APPROVED** [review]
