### PR TITLE
Roumanwu: Rewrite to make it works on new website

### LINKED ISSUE #5374: roumanwu 1.4.10 bug
### Source information

1.4.10

### Source language

chinese

### Steps to reproduce

open roumanwu

### Expected behavior

Normal

### Mihon/Tachiyomi version

0.16.*

### Android version

androp11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by oalieno**
Closes #5374.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt [hunk 1]
```diff
@@ -36,41 +42,100 @@ class Roumanwu : HttpSource(), ConfigurableSource {
     private val json: Json by injectLazy()
 
     override fun popularMangaRequest(page: Int) = GET("$baseUrl/home", headers)
-    override fun popularMangaParse(response: Response) = response.nextjsData<HomePage>().getPopular().toMangasPage()
+    override fun popularMangaNextPageSelector(): String? = null
+    override fun popularMangaSelector(): String = "main > div.px-0 > div > div:not(.p-3):not(:last-child):not(:nth-child(4)) > div.grid > div > a"
```
Comment (AwkwardPeak7) [inline src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]: these kind of selectors can be broken easily... (applies to almost all of the selectors here).
Ik these are tailwind selectors and aren't cleanly scrapable, but consider using pseudo selectors to make it a bit cleaner.
try `.grid a[href*=/books/]` 

also take a look at the [documentation](https://jsoup.org/apidocs/org/jsoup/select/Selector.html) to learn about pseudo selectors

File: src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt [hunk 2]
```diff
@@ -36,41 +42,100 @@ class Roumanwu : HttpSource(), ConfigurableSource {
...
+    }
+    override fun chapterListParse(response: Response): List<SChapter> {
+        return super.chapterListParse(response).reversed()
+    }
 
-    override fun chapterListParse(response: Response) = response.nextjsData<BookDetails>().book.getChapterList().reversed()
+    override fun pageListParse(document: Document): List<Page> {
+        val jsonString = document.select("script")
+            .find { it.html().contains("imageUrl") }
+            ?.html()
```
Comment (AwkwardPeak7) [inline src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]:
```suggestion
        val jsonString = document.selectFirst("script:containsData(imageUrl)")?.data()
```

File: src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt [hunk 3]
```diff
@@ -36,41 +42,100 @@ class Roumanwu : HttpSource(), ConfigurableSource {
...
+            ?.let { content ->
+                """(?<=\[1,").*(?="\])""".toRegex()
```
Comment (AwkwardPeak7) [inline src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]: pull out regex to class val so it isn't initialized everytime

File: src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt [hunk 4]
```diff
@@ -36,41 +42,100 @@ class Roumanwu : HttpSource(), ConfigurableSource {
...
-        return if (chapter.images != null) {
-            chapter.getPageList()
-        } else {
-            @Suppress("NAME_SHADOWING")
-            val response = client.newCall(GET(baseUrl + chapter.chapterAPIPath!!, headers)).execute()
-            if (!response.isSuccessful) throw Exception("服务器错误: ${response.code}")
-            response.parseAs<ChapterWrapper>().chapter.getPageList()
-        }
+        return jsonString?.let { str ->
+            val json = Json.parseToJsonElement(str)
```
Comment (AwkwardPeak7) [inline src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]:
```suggestion
            val jo = json.parseToJsonElement(str)
```
use app provided `json` instance

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt [hunk 5]
```diff
@@ -112,19 +177,14 @@ class Roumanwu : HttpSource(), ConfigurableSource {
 
     companion object {
         private const val MIRROR_PREF = "MIRROR"
-        private const val MIRROR_PREF_TITLE = "使用镜像网址"
-        private const val MIRROR_PREF_SUMMARY = "使用镜像网址。重启软件生效。"
+        private const val MIRROR_PREF_TITLE = "使用鏡像網址"
+        private const val MIRROR_PREF_SUMMARY = "使用鏡像網址。重啟軟體生效。"
 
         // 地址: https://rou.pub/dizhi
         private val MIRRORS get() = arrayOf("https://rouman5.com", "https://roum16.xyz")
```
Comment (NeKoOuO) [inline src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]: roum18.xyz

File: src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt (hunk 1 above)
Comment (oalieno) [reply src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]: image

Because under the `div.px-1`, the 2nd, 3rd, 5th are `hotest`, `daily top`, `weekly top`. These three `grid` is for popular.
And the 4th one is `Latest`.
They have no difference in css.
The best i can try is `div.px-1 > div:not(:first-child):not(:last-child):not(:nth-child(4)) .grid a[href*=/books/]` for popular and `div.px-1 > div:nth-child(4) .grid a[href*=/books/]` for latest.
Or if we do `.grid a[href*=/books/]` and set supportsLatest to false, since everything is inside the popular.

Comment (oalieno) [reply src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]: or we do `div:contains(最近更新) .grid a[href*=/books/]`?

Comment (oalieno) [reply src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]: `div:contains(正熱門), div:contains(今日最佳), div:contains(本週熱門) .grid a[href*=/books/]`
`div:contains(最近更新) .grid a[href*=/books/]`
~~seems to work.~~ oh wait, not working. it will match too many div

Comment (oalieno) [reply src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]:
```
div.px-1 > div:contains(正熱門) .grid a[href*=/books/],
div.px-1 > div:contains(今日最佳) .grid a[href*=/books/],
div.px-1 > div:contains(本週熱門) .grid a[href*=/books/]
```

`div.px-1 > div:contains(最近更新) .grid a[href*=/books/]`

Comment (AwkwardPeak7) [reply src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/Roumanwu.kt]: `div:matches(最近更新|本週熱門|今日最佳|正熱門) .grid a[href*=/books/]`

**Review by AwkwardPeak7 — APPROVED** [review]
