### PR TITLE
YomuComics: Redesign

### LINKED ISSUE #13710: Yomu Comics: `HTTP 404`/`No results found` error, new theme/redesign
### Source information

Yomu Comics 1.4.40

### Source language

Portuguese Brazil

### Steps to reproduce

Open any title to read or update it, and it will return an error.

### Expected behavior

It was expected to work.

### Actual behavior

Image
Image
Image

### Mihon/Mihon fork version

Komikku 1.13.5

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes #13710

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsUtils.kt [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+        titleElement?.nextElementSibling(),
+        titleElement?.nextElementSibling()?.nextElementSibling(),
+        titleElement?.parent(),
+        titleElement?.parent()?.parent(),
+    )
+
+    return nearbyElements
+        .flatMap { element -> element.select("span[data-slot=badge]") }
+        .map { it.text() }
+        .filter(String::isNotBlank)
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsUtils.kt]: `.text()` is trimmed, empty check is cheaper.
```suggestion
        .filter(String::isNotEmpty)
```

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 2]
```diff
@@ -3,138 +3,108 @@ package eu.kanade.tachiyomi.extension.pt.sssscanlator
...
 )
 
 @Serializable
-class UpdateMangaDto(
+class LibraryMangaDto(
     val title: String,
-    val slug: String,
     val cover: String? = null,
+    @SerialName("slug")
+    val mangaSlug: String,
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]: Why? Its already scoped within this class.
```suggestion
    val slug: String,
```

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 3]
```diff
@@ -3,138 +3,108 @@ package eu.kanade.tachiyomi.extension.pt.sssscanlator
...
 ) {
     fun toSManga(): SManga = SManga.create().apply {
-        title = this@UpdateMangaDto.title
-        thumbnail_url = cover
-        url = "/obra/$slug"
+        title = this@LibraryMangaDto.title.ifBlank { mangaSlug }
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]: Is this actually empty/blank sometimes? Consider removing or capitalizing the slug.
```suggestion
        title = this@LibraryMangaDto.title
```
```suggestion
        title = this@LibraryMangaDto.title.ifBlank { mangaSlug.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() } }
```
(might need locale)

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt [hunk 4]
```diff
@@ -3,138 +3,108 @@ package eu.kanade.tachiyomi.extension.pt.sssscanlator
...
-        }
-        url = "/obra/$slug"
+fun Double.toChapterNumberString(): String {
+    val integerValue = toLong()
+    return if (this == integerValue.toDouble()) {
+        integerValue.toString()
+    } else {
+        toString()
     }
 }
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComicsDto.kt]:
```suggestion
fun Double.toChapterNumberString(): String {
    return this.toString().removeSuffix(".0")
}
```

... or just inline.

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt [hunk 5]
```diff
@@ -40,266 +29,215 @@ class YomuComics :
...
-    override fun popularMangaParse(response: Response): MangasPage {
-        val homeDto = response.parseAs<HomeDto>()
-        val mangas = homeDto.featuredManga.map { it.toSManga() }
-        return MangasPage(mangas, false)
-    }
+    // Details
 
-    // =============================== Latest ===============================
-    override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/api/updates?page=$page&limit=50", headers)
+    override fun mangaDetailsRequest(manga: SManga): Request = GET(getMangaUrl(manga), headers)
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt]: This is the default
```suggestion
```

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt [hunk 6]
```diff
@@ -40,266 +29,215 @@ class YomuComics :
...
-
-        filters.forEach { filter ->
-            if (filter is SortFilter) {
-                sortStr = filter.toUriPart()
-                if (sortStr == "name") {
-                    orderStr = "asc"
-                }
-            }
-        }
+    override fun getMangaUrl(manga: SManga): String = baseUrl + manga.url
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt]: This is the default.
```suggestion
```

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt [hunk 7]
```diff
@@ -40,266 +29,215 @@ class YomuComics :
...
-                is AdultFilter -> {
-                    if (filter.state) {
-                        url.addQueryParameter("showAdult", "true")
-                    }
-                }
-
-                else -> {}
-            }
-        }
+    override fun chapterListRequest(manga: SManga): Request = mangaDetailsRequest(manga)
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt]: This is the default.
```suggestion
```

File: src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt [hunk 8]
```diff
@@ -40,266 +29,215 @@ class YomuComics :
...
-            "$baseUrl${chapter.url}".toHttpUrl()
+    private fun parseSeriesPage(response: Response): SeriesPageData {
+        val mangaSlug = response.request.url.pathSegments.lastOrNull().orEmpty()
+        val document = response.asJsoup()
+        val payload = extractSeriesPayload(document, mangaSlug)
+
+        val titleElement = document.selectFirst("h1")
+        val title = titleElement?.text().orEmpty().ifBlank {
+            mangaSlug.ifBlank { "Sem titulo" }
+        }
```
Comment (vetleledaal) [inline src/pt/sssscanlator/src/eu/kanade/tachiyomi/extension/pt/sssscanlator/YomuComics.kt]: Don't add infinite fallbacks
```suggestion
        val title = titleElement!!.text()
```

**Review by vetleledaal — APPROVED** [review]
