### PR TITLE
MachineTranslations & Snowmtl: Fix the regex in the translator engine and add font size settings

### LINKED ISSUE #7462: Snowmtl not tranlated
### Source information

Snowmtl 1.4.9

### Source language

All

### Steps to reproduce

1. Open ext
2. Choose one manhua
3. Click on chapter

### Expected behavior

Languages are translated according to the options in the extension.

### Actual behavior

Not translated, still in English. Previously I was on version 1.4.4 and it was working fine before I updated to the latest version 1.4.9. Btw can you increase the font size a bit? 

Image

### Mihon/Tachiyomi version

J2k 1.7.4

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #7462

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AnonymousPtBr** [comment]
Is this Machine Translations in the title the Solar Machine Translations font? If it is the same, I won't open another issue. If not, I'll open a ticket for the same problem! The chapters of the PT-BR version of the font are in English too!

File: lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt [hunk 1]
```diff
@@ -203,9 +230,51 @@ abstract class MachineTranslations(
...
+            entries = sizes.map {
+                "${it}pt" + if (it == DEFAULT_FONT_SIZE) " - ${intl["default_font_size"]}" else ""
+            }.toTypedArray()
+            entryValues = sizes
+            summary = intl["font_size_summary"]
+
+            setDefaultValue(DEFAULT_FONT_SIZE)
+            setValueIndex(0)
+
+            setOnPreferenceChangeListener { _, newValue ->
```
Comment (AwkwardPeak7) [inline lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt:252]: you don't need to set pref manually in here

File: lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt [hunk 2]
```diff
@@ -29,17 +39,34 @@ abstract class MachineTranslations(
...
 
-    override val client = network.cloudflareClient.newBuilder()
-        .addInterceptor(ComposedImageInterceptor(baseUrl, language))
-        .build()
+    private val preferences: SharedPreferences by lazy {
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
+    }
+
+    protected var fontSize: Int
+        get() = preferences.getString(FONT_SIZE_PREF, DEFAULT_FONT_SIZE)!!.toInt()
```
Comment (AwkwardPeak7) [inline lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt:55]: calling pref each time it is accessed? (is it accessed anywhere else other than lazy okhttp init?

**Comment by AwkwardPeak7** [comment]
rebase on main and run build once

File: lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt (hunk 2 above)
Comment (choppeh) [reply lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt:55]: > calling pref each time it is accessed? (is it accessed anywhere else other than lazy okhttp init?

It is also being used when the font is changed

File: lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt [hunk 3]
```diff
@@ -203,9 +230,49 @@ abstract class MachineTranslations(
...
+
+                fontSize = selected.toInt()
+
+                Toast.makeText(
+                    screen.context,
+                    intl["font_size_message"].format(entry),
+                    Toast.LENGTH_LONG,
+                ).show()
+
+                true
```
Comment (AwkwardPeak7) [inline lib-multisrc/machinetranslations/src/eu/kanade/tachiyomi/multisrc/machinetranslations/MachineTranslations.kt]:
```suggestion
                false
```
since your `fontSize` var already saves the pref

**Review by AwkwardPeak7 — APPROVED** [review]
