### PR TITLE
fix MangaStop: add interceptor

### LINKED ISSUE #11786: Manga Stop: `Você precisa acessar o site para ler o capítulo` image on all chapters
### Source information

Manga Stop

### Source language

Manga Stop

### Steps to reproduce

Os Manhwa estão a parecendo normalmente, mas quando vou para visualizar ou baixar, nenhuma página é encontrado, só encontra uma página de informação, a dizer o seguinte: 'Se quiser ler, Vai no site oficial', simplesmente isso, e eu adorei essa extensão, se puder resolver, seria muito bom.

### Expected behavior

Ao acessar a extensão, devemos ter acesso aos manhwa's, funcionando e acessível como sempre. 

### Actual behavior

Os Manhwa estão a parecendo normalmente, mas quando vou para visualizar ou baixar, nenhuma página é encontrado, só encontra uma página de informação, a dizer o seguinte: 'Se quiser ler, Vai no site oficial', simplesmente isso, e eu adorei essa extensão, se puder resolver, seria muito bom.

### Mihon/Tachiyomi version

App ID: app.mihon App version: 0.19.1 (029e36b, 13, 2025-08-07T13:59:01Z) Android version: 15 (SDK 35; build CL6k-15.1.2.128(OP001PF001AZ)) Device brand: TECNO Device manufacturer: TECNO Device name: TECNO-CL6k (CL6k-OP) Device model: TECNO CL6k WebView: Android System WebView 142.0.7444.102 Current time: 2025-11-24T13:44:35.001178+01:00

### Android version

15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
Closes: #11786

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt [hunk 1]
```diff
@@ -18,4 +22,17 @@ class MangaStop : MangaThemesia(
...
         .rateLimit(3)
         .build()
+
+    override fun pageListParse(document: Document): List<Page> {
+        val pages = super.pageListParse(document)
+            .filterNot { it.imageUrl?.contains("mihon", true) == true }
+
+        if (pages.isNotEmpty()) return pages
+
+        return MangaThemesia.JSON_IMAGE_LIST_REGEX.find(document.toString())
```
Comment (vetleledaal) [inline src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt:32]: Maybe use `override fun pageListParse(response: Response)` instead, to avoid back-and-forth with `document`.

EDIT: You may run into issues with reading an already consumed response. Working around that might be more effort than what its worth.

File: src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt [hunk 2]
```diff
@@ -18,4 +22,17 @@ class MangaStop : MangaThemesia(
...
+            ?.groupValues?.get(1)
+            ?.let { json.parseToJsonElement(it).jsonArray }
+            ?.mapIndexed { i, el -> Page(i, document.location(), el.jsonPrimitive.content) }
```
Comment (vetleledaal) [inline src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt]: Do you need the page location? I didn't check if MangaThemesia does anything with it.

If it's not needed I would remove it.
```suggestion
            ?.mapIndexed { i, el -> Page(i, imageUrl = el.jsonPrimitive.content) }
```

Comment (FelipeGFA) [reply src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt]: https://github.com/keiyoushi/extensions-source/blob/8769908c8413e22e6d2b3f0eea664add7d874935/lib-multisrc/mangathemesia/src/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt#L371-L377

 MangaThemesia parent class and imageRequest explicitly uses ```page.url``` to set the ```Referer``` header

File: src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt [hunk 3]
```diff
@@ -23,16 +24,21 @@ class MangaStop : MangaThemesia(
...
+            }
+        }
 
-        return MangaThemesia.JSON_IMAGE_LIST_REGEX.find(document.toString())
-            ?.groupValues?.get(1)
-            ?.let { json.parseToJsonElement(it).jsonArray }
-            ?.mapIndexed { i, el -> Page(i, document.location(), el.jsonPrimitive.content) }
-            .orEmpty()
+        val document = Jsoup.parse(html, response.request.url.toString())
+        return super.pageListParse(document).filterNot {
```
Comment (vetleledaal) [inline src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt]: If you're going to call `super.pageListParse(document: Document)` (instead of `super.pageListParse(response: Response)`), I would just use the previous version.

Comment (FelipeGFA) [reply src/pt/mangastop/src/eu/kanade/tachiyomi/extension/pt/mangastop/MangaStop.kt]: i just reverted to ```pageListParse(document: Document)``` as u said but kept document.location() because ```MangaThemesia.imageRequest``` requires a valid URL for the ```Referer``` header

is that valid?

**Review by vetleledaal — APPROVED** [review]
