### PR TITLE
BlackoutComics: Fix  selectors

### LINKED ISSUE #2275: BlackoutComic (pt) - thumbnail strange
### Source information

Blackout Comics

### Source language

Português 

### Steps to reproduce

1 - install the extension
2 - open

### Expected behavior

I can't post the image for this reason, you have to look at the extension

I can also be banned.

### Actual behavior

Captura de ecrã 2024-04-05 194734

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #2275

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt [hunk 1]
```diff
@@ -97,8 +97,8 @@ class BlackoutComics : ParsedHttpSource() {
     // =========================== Manga Details ============================
     override fun mangaDetailsParse(document: Document) = SManga.create().apply {
         val row = document.selectFirst("section > div.container > div.row")!!
-        thumbnail_url = row.selectFirst("img:not(.hidden)")?.absUrl("src")
-        title = row.selectFirst("div.trailer-content > h2:not(.hidden)")!!.text()
+        thumbnail_url = row.selectFirst("img.img-recen-add2")?.absUrl("src")
+        title = row.selectFirst("div.trailer-content > h2:not(.tachiyomikappa)")!!.text()
```
Comment (vetleledaal) [inline src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: Make sure you're using the same method to hide elements as on the site. Can always find the class name from css/js if they keep changing it.

Comment (choppeh) [reply src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: The source adds an extra element (hidden element) at the same level as the resource you are looking for.

The previous solution reversed the selection logic, it does not contain the hiding class, so it is the resource(thumbnail, title) to be used, because the resource in some cases does not have a css selector

Comment (choppeh) [reply src/pt/blackoutcomics/src/eu/kanade/tachiyomi/extension/pt/blackoutcomics/BlackoutComics.kt]: I don't think there's a comprehensive enough solution.
It's like a Tom & Jerry.

**Review by AwkwardPeak7 — APPROVED** [review]
