### PR TITLE
NineManga(es): Fix pages not loading

### LINKED ISSUE #11810: ninemangaEs: Image data not found
### Source information

NineManga 1.4.23

### Source language

Spanish

### Steps to reproduce

1. Enter ninemangaEs.
2. Choose any manga/chapter.
3. View image.

Image

### Expected behavior

The chapter should load.

### Actual behavior

The chapter is not loading.

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 14

### Other details

logs:

[mihon_crash_logs.txt](https://github.com/user-attachments/files/23746672/mihon_crash_logs.txt)

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Closes #11810

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt [hunk 1]
```diff
@@ -59,10 +60,35 @@ class NineMangaEs : NineManga("NineMangaEs", "https://es.ninemanga.com", "es") {
...
+
+            val documentLocation = document.location()
+
+            if (!redirectUrl.startsWith("http")) {
+                val documentDomain = documentLocation.substringAfter("://").substringBefore("/")
+                redirectUrl = "https://$documentDomain/${redirectUrl.removePrefix("/")}"
+            }
+
+            val headers = headers.newBuilder()
+                .set("Referer", documentLocation)
```
Comment (vetleledaal) [inline src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt:82]:
```suggestion
                .set("Referer", "$documentLocation/")
```

File: src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt [hunk 2]
```diff
@@ -59,10 +60,35 @@ class NineMangaEs : NineManga("NineMangaEs", "https://es.ninemanga.com", "es") {
...
+        if (redirectScript != null) {
+            var redirectUrl = redirectRegex.find(redirectScript)?.groupValues?.get(1)
+                ?: return super.pageListParse(document)
+
+            val documentLocation = document.location()
+
+            if (!redirectUrl.startsWith("http")) {
+                val documentDomain = documentLocation.substringAfter("://").substringBefore("/")
+                redirectUrl = "https://$documentDomain/${redirectUrl.removePrefix("/")}"
+            }
```
Comment (vetleledaal) [inline src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt]: Maybe use `OkHttp` for this, to avoid direct string operations. Is `redirectUrl` always `/`...something or `http`...something? Then you can use:

```suggestion
            if (!redirectUrl.startsWith("http")) {
                redirectUrl = documentLocation.toHttpUrl().newBuilder()
                    .encodedPath(redirectUrl)
                    .build()
                    .toString()
            }
```

---

Looking a bit further up you can probably chain it a bit (`document.location()` is a cheap getter):
```kt
val redirectUrl = redirectRegex.find(redirectScript)
    ?.groupValues?.get(1)
    ?.let { path ->
        path.toHttpUrlOrNull()
        ?: document.location().toHttpUrl().newBuilder()
            .encodedPath(path)
            .build()
    } ?: return super.pageListParse(document)
```

---

^ Needs testing if you want to use it.

File: src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt (hunk 1 above)
Comment (bapeey) [reply src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt:82]: AFAIK, the trailing slash is used when the URL has no path, so in this case it isn't needed

**Review by vetleledaal — APPROVED** [review]

**Review by vetleledaal — APPROVED** [review]
