### PR TITLE
MangaCrab: Fix images not loading

### LINKED ISSUE #10842: Mangacrab  IllegalArgumentException error
### Source information

Mangacrab 1.4.59

### Source language

Spanish

### Steps to reproduce

Se ingresa a la fuente, al monento de querer visualizar cualquier lectura da cualquier serie da error

Image

### Expected behavior

Deberia visualizar las paginas de manwhas

### Actual behavior

No visualiza y da error detallado IllegalArgumentException

Image

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Closes #10842

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/mangacrab/src/eu/kanade/tachiyomi/extension/es/mangacrab/MangaCrab.kt [hunk 1]
```diff
@@ -51,6 +51,15 @@ class MangaCrab :
     override val pageListParseSelector = "div.page-break:not([style*='display:none']) img:not([src])"
 
     override fun imageFromElement(element: Element): String? {
+        val validateAttrValue = element.attributes().firstOrNull { it.value.contains("validate.php") }?.value
```
Comment (vetleledaal) [inline src/es/mangacrab/src/eu/kanade/tachiyomi/extension/es/mangacrab/MangaCrab.kt]: Should use `.startsWith()` to be consistent with future use of `.removePrefix()`.

Or better yet-
use `element.absUrl(it.key).toHttpUrlOrNull()` and check if `.encodedPath` is `/validate.php` (or `.pathSegments.lastOrNull` is `validate.php`, depending on how lenient you want to be).

Something like (pseudo code):
```kt
val url = element.attributes()
    .firstNotNullOfOrNull { attr ->
        element.absUrl(attr.key).toHttpUrlOrNull()
            ?.takeIf { it.encodedPath == "/validate.php" }
    }

val fileUrl = url
    ?.queryParameter("file")
    ?.takeIf { it.isNotBlank() }
    ?.let { file ->
        url.newBuilder()
            .encodedPath("/$file")
            .query(null)
            .build()
    }

// ...

return when {
    fileUrl != null -> fileUrl.toString()
```

---

Might be more work than what it's worth

**Review by vetleledaal — APPROVED** [review]
