### PR TITLE
Fix (Raijin Scans) : Update for site changes

### LINKED ISSUE #7570: Raijin Scans not working
### Source name

Raijin Scans

### Source language

French

### Source link

https://raijinscan.fr/

### Other details

Hi.
Raijiscan changed their domain name. Now it's...
https://raijinscan.fr/
(Before it was certainly  https://raijinscans.com/) 
Could you make the correction? 
Thank you for all your work! 

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source website is down.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a meaningful title with the source name.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9055: Raijin Scans (fr): No results found
### Source information

Raijin Scans 1.4.46

### Source language

French

### Steps to reproduce

Just launch anything related to the source (read a chapter, try to update the list, browse, etc.)

### Expected behavior

Be able to open a chapter, update the titles, or perform a search

### Actual behavior

open a chapter : No pages found
update : No chapters found
browse : No results found

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 13

### Other details

https://raijinscan.fr/

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Nyantad**
Updated the source to support the new site UI, preserving the original source ID because it was treated as a new source.

Closes #9055
Closes #7570

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt [hunk 1]
```diff
@@ -1,9 +1,205 @@
...
-class RaijinScans : Madara("Raijin Scans", "https://raijinscan.fr", "fr", dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.FRENCH)) {
-    override val useNewChapterEndpoint = true
+class RaijinScans : HttpSource() {
+
+    override val name = "Raijin Scans"
+    override val baseUrl = "https://raijinscan.fr"
+    override val lang = "fr"
+    override val supportsLatest = true
+    override val versionId = 2
+    override val id: Long = 8373267671495516033
```
Comment (vetleledaal) [inline src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: Why change both?

File: src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt [hunk 2]
```diff
@@ -1,9 +1,205 @@
...
+    }
+
+    // ========================= Chapter List ==========================
+    override fun chapterListParse(response: Response): List<SChapter> {
+        return response.asJsoup().select("ul.scroll-sm li.item").map(::chapterFromElement)
+    }
+
+    private fun chapterFromElement(element: Element): SChapter = SChapter.create().apply {
+        val link = element.selectFirst("a")!!
+        setUrlWithoutDomain(link.attr("href"))
```
Comment (vetleledaal) [inline src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: To let Jsoup resolve relative URLs:
```suggestion
        setUrlWithoutDomain(link.absUrl("href"))
```
```suggestion
        setUrlWithoutDomain(link.attr("abs:href"))
```

File: src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt [hunk 3]
```diff
@@ -1,9 +1,205 @@
...
+        name = link.attr("title").trim()
+
+        val spans = link.select("> span")
+        date_upload = parseRelativeDateString(spans.getOrNull(1)?.text())
```
Comment (vetleledaal) [inline src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: Can you use some pseudo selectors to move logic out of Kotlin? `:nth-child()` etc.

File: src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt (hunk 1 above)
Comment (Nyantad) [reply src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: Because initially, I bumped versionId due to the change of madara theme to no theme. And after this caused the app to treat it as a new source, so I added the explicit id.

Comment (AwkwardPeak7) [reply src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: yes bumping version id does that. if old urls are compatible/same as new urls, then there is no need to bump version id.
please confirm this, rest is ok

Comment (Nyantad) [reply src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: Thanks for the information, it's good for me now that I change the Id's

Comment (AwkwardPeak7) [reply src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: I should have been more clear.. are old manga urls compatible with new site? if so then keeping same id is fine

Comment (Nyantad) [reply src/fr/raijinscans/src/eu/kanade/tachiyomi/extension/fr/raijinscans/RaijinScans.kt]: my bad, yes according to my tests it's compatible

**Review by AwkwardPeak7 — APPROVED** [review]
