### PR TITLE
Koharu: do not use network on main thread

### LINKED ISSUE #8199: Koharu / SchaleNetwork: android.os.NetworkOnMainThreadException
### Source information

SchaleNetwork 1.4.13

### Source language

Multi

### Steps to reproduce

Not provided.

### Expected behavior

Not provided.

### Actual behavior

Not provided.

### Mihon/Tachiyomi version

TachiyomiAZ

### Android version

Not provided.

### Other details

Reported in Discord, minimal details given.

[log.txt](https://github.com/user-attachments/files/19412047/log.txt)

Most likely need to wrap `.newCall()` with `runBlocking(Dispatchers.IO)`:
https://github.com/keiyoushi/extensions-source/blob/8b7c87bb3d63bb8839fed14895f614b0e63a561b/src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/TurnstileInterceptor.kt#L123
https://github.com/keiyoushi/extensions-source/blob/8b7c87bb3d63bb8839fed14895f614b0e63a561b/src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/TurnstileInterceptor.kt#L179

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #8199

I was able to consistently crash in TachiyomiAZ without this fix. The change has no effect on Mihon.

`close()` might not be required.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/TurnstileInterceptor.kt [hunk 1]
```diff
@@ -120,7 +122,12 @@ class TurnstileInterceptor(
                             try {
                                 val noRedirectClient = client.newBuilder().followRedirects(false).build()
                                 val authHeaders = authHeaders(authHeader)
-                                val response = noRedirectClient.newCall(POST(authUrl, authHeaders)).execute()
+                                val response = runBlocking(Dispatchers.IO) {
+                                    noRedirectClient
+                                        .newCall(POST(authUrl, authHeaders))
+                                        .execute()
+                                        .apply { close() }
```
Comment (AwkwardPeak7) [inline src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/TurnstileInterceptor.kt]: response.use later will close it

**Comment by vetleledaal** [comment]
Not able to confirm that 66e9417 (current PR) fixes the issue, I am just getting 403 responses for SchaleNetwork in TachiyomiAZ today. It still works in Mihon.

I was able to confirm that a227e08 was working in TachiyomiAZ yesterday. If you believe 66e9417 is suitably equivalent, feel free to merge it. Otherwise, just close this PR and let someone else deal with it.

**Review by AwkwardPeak7 — APPROVED** [review]
