### PR TITLE
Kagane | Fixed "Unable to decrypt data", Added New Filters

### LINKED ISSUE #11281: Kagane: `Failed to decode image`, `Unable to decrypt data` error on specific chapters/pages
### Source information

Kagane 1.4.8

### Source language

English

### Steps to reproduce

1. Opened a manhwa
2. Clicked the specific chapter specific page
3. IllegalStateException: Failed to decode image

### Expected behavior

This should happen you can see the content. (This is an example from the downloaded manhwa).

Image

### Actual behavior

This happened instead no image or image shown broken.

Image
Image

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 13

### Other details

Here’s what the file from the issued page looks like if it’s downloaded in a format other than CBZ.

Image

Here's the webview display on the page with the issue.

Image

This issue is quite specific, because out of many pages in a single chapter, mostly only one page has this problem. For the record, I’ve already tried clearing Mihon’s cache, but the issue still persists. The issued page can be loaded and displayed normally if I opened it using a browser. Below are several pages I found experiencing this issue, all of which are from 18+ manhwa series.

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11538: Kagane filter changes
### Source name

Kagane 

### Source language

English

### Describe your suggested feature

This is a screenshot from the website when the scanlations option is disabled 

Image

and this is when it's enabled.

Image

It should be the same in the app: if show scanlations off = don't show scanlations in filters
if scanlations on = show scanlation in filters

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11937: Kagane: Scanlator filter / Show scanlator in search results
### Source name

Kagane

### Source language

English

### Describe your suggested feature

Currently, the only way that you'll know which scanlator came from is checking the description on each search result:

https://github.com/user-attachments/assets/e4b56e1c-dc39-4989-869a-106911a99e2e

There's two known ways to know which scanlator to pick:

1. Display the scanlator name in the search results (using Batoto as an example)

https://github.com/user-attachments/assets/e8611db0-0abb-435b-8abf-6b1572018a85

2. Utilize the scanlator filter (using Comix as an example)

https://github.com/user-attachments/assets/77add069-567d-4d36-8fd8-1e682a5d2b4f

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11942: Kagane: `Unable to decrypt data` on any chapters
### Source information

Kagane 1.4.12

### Source language

English

### Steps to reproduce

Kagane just had their maintenance. Then after that can't access the chapters anymore. Getting an "Unable to decrypt data" error in Webpage view, Downloading Chapters, and reading chapters.

Image
Image
Image

### Expected behavior

Should be able to download, read and access webview.

### Actual behavior

Getting "Unable to decrpyt data" error instead.

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #11942
Closes #11281
Closes #11937
Closes #11538

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 1]
```diff
@@ -73,7 +74,6 @@ class Kagane : HttpSource(), ConfigurableSource {
     override val client = network.cloudflareClient.newBuilder()
         .addInterceptor(ImageInterceptor())
         .addInterceptor(::refreshTokenInterceptor)
-        .rateLimit(2)
```
Comment (KenjieDec) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:76]: Although it doesn't seem that removing the rate limit affects anything, I might be wrong. Please notify me if I'm wrong 🙏

**Review by vetleledaal — APPROVED** [review]
