### PR TITLE
[RU]GroupLe fix chapter loads and manga status

### LINKED ISSUE #6805: [RU]Grouple error while downloading images
### Source information

ReadManga 1.4.72

### Source language

Russian

### Steps to reproduce

1. Download any chapter in any comic/manga

### Expected behavior

Download without errors

### Actual behavior

Receive error "Begin -1, end ****, length ****" where **** - random numbers

Screenshot_20241224_065527_app_mihon_debug_MainActivity

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 10

### Other details

It looks like site changed source code. Extension trying to find "rm_h.readerDoInit" line in the site code to get list of images to download [(link to code)](https://github.com/keiyoushi/extensions-source/blob/f15e50aa0a69bce289fd7d8f01b8620315870e7f/lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt#L316) while site changed it to "rm_h.readerInit".

Other extensions like Usagi 1.4.26, SeiManga 1.4.26, MintManga 1.4.72, and others connected to Grouple should be updated also.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Dr1ks**
Closes #6805 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Steex** [comment]
Could you please update the status parsing a little? Currently a manga that is finished, but not yet fully translated, will have the COMPLETED status anyway. There's a separate status PUBLISHING_FINISHED, which is better for these cases.
Fully translated mangas can be detected by an additional badge with a text "переведено" on it.

Some examples:
- Fully translated: https://web.usagi.one/slayers___super_explosive_demon_story
- Finished, but not translated yet: https://web.usagi.one/slayers__knight_of_aqualord

**Comment by Dr1ks** [comment]
I’ve updated the status parsing to address the issue.

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt [hunk 1]
```diff
@@ -177,17 +177,16 @@ abstract class GroupLe(
...
-                when (infoElement.select("p:contains(Перевод:) span").first()?.text()) {
-                    "продолжается" -> SManga.ONGOING
-                    "начат" -> SManga.ONGOING
-                    "переведено" -> SManga.COMPLETED
-                    "завершён" -> SManga.COMPLETED
-                    "приостановлен" -> SManga.ON_HIATUS
+                when (infoElement.select("span.badge:contains(выпуск)").first()?.text()) {
+                    "выпуск продолжается" -> SManga.ONGOING
+                    "выпуск начат" -> SManga.ONGOING
+                    "выпуск завершён" -> if (infoElement.select("span.badge:contains(переведено)").first()?.text()?.isNotEmpty() == true) SManga.COMPLETED else SManga.PUBLISHING_FINISHED
```
Comment (vetleledaal) [inline lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt]: Use `selectFirst()`, not `select().first()`

Comment (Dr1ks) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt]: Fixed

**Review by vetleledaal — DISMISSED** [review]

**Comment by Dr1ks** [comment]
Make further adjustments, as the AllHentai extension uses slightly different syntax compared to other Grouple extensions.

**Comment by Exinaus** [comment]
What if, theoretically, AllHentai uses different (previous) function because work on this site is still in progress, and when it will be finished they will move from rm_h.readerDoInit to a new rm_h.readerInit like other sites.
What if, instead of just assigning readerMark perform some sort of a check, something like that:
```
if (html.contains("rm_h.readerInit([")) {
   val readerMark = "rm_h.readerInit(["
} elseif (html.contains("rm_h.readerDoInit([")) {
   val readerMark = "rm_h.readerDoInit(["
} else {
   throw Exception("Дизайн сайта обновлен, для дальнейшей работы необходимо обновление дополнения")
}
```

It's more or less universal, cover both options, and adds Error message that easier to understand and report rather than "Begin -1, end 123456 length 987654321"
Or don't, if html.contains are too heavy and it's better to avoid it's usage multiple times.

**Comment by Exinaus** [comment]
P.S. I think MintManga also requires authorization through WebViev. Maybe check should be added for it also, like you did for AllHentai.

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt [hunk 2]
```diff
@@ -213,15 +212,9 @@ abstract class GroupLe(
...
-                .isEmpty() && document.toString()
-                .contains("current_user_country_code = 'RU'")
-            ) || (
-                document.select("img.logo")
-                    .first()?.attr("title")
-                    ?.contains("Allhentai") == true && document.select(".user-avatar").isEmpty()
-                )
+
+        if (document.select(".user-avatar").isEmpty() &&
+            document.title().run { contains("AllHentai") || contains("MintManga") || contains("МинтМанга") }
```
Comment (AwkwardPeak7) [inline lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:217]: any way to do it without depending on title? and why is this check repeated here and at line 310?

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt [hunk 3]
```diff
@@ -313,20 +306,22 @@ abstract class GroupLe(
...
+
+        val readerMark = when {
+            html.contains("rm_h.readerDoInit([") -> "rm_h.readerDoInit(["
+            html.contains("rm_h.readerInit([") -> "rm_h.readerInit(["
+            !response.request.url.toString().contains(baseUrl) -> {
                 throw Exception("Не удалось загрузить главу. Url: ${response.request.url}")
             }
+            else -> {
+                throw Exception("Дизайн сайта обновлен, для дальнейшей работы необходимо обновление дополнения")
+            }
```
Comment (AwkwardPeak7) [inline lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:324]: [maybe this?](https://github.com/KotatsuApp/kotatsu-parsers/commit/04225170d34e486be3925cdb517d32b62c404b6d#diff-b47c4e01a1271f7078a22f4d0a98e7747abf2e163a825c11c9b9852ae86155b4R214-R226)

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt (hunk 2 above)
Comment (Dr1ks) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:217]: I can tweak the checks to use the syntax from the body if it’s needed. About the repeated checks, I just fixed the broken ones that were already there, and I didn’t think they were too much.

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt (hunk 3 above)
Comment (Dr1ks) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:324]: It used to check for another "readerMark" variant, but I couldn’t find it in any current grouple extensions. The way the page parsing works now covers all existing grouple extensions. Or did I misunderstand what you was pointing out?

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt (hunk 2 above)
Comment (Exinaus) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:217]: I think those sites can be accessed without authorization. Only difference will be that chapter images will be replaced with placeholders with "Login to see image" text. Like this: https://2.mintmanga.one/dnevnik_plohih_myslei__A35c96/vol1/60?d=MjE1Nzky&mtr=true
No extra error messages or redirections to login screen to do the check without depending on a title.

I think code at line 310 used to download images of a single chapter, while this line are used by function at 197 line
`override fun fetchChapterList`
They might do different things, download images/getting list of chapters from site.

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt (hunk 3 above)
Comment (Exinaus) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:324]: Maybe he meant using
`data.indexOf("rm_h.readerInit(") `
instead of 
`html.contains("rm_h.readerInit([")`

Comment (AwkwardPeak7) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:324]: the commit I linked uses three different signatures, `rm_h.readerDoInit(`, `rm_h.readerInit( 0,`, `.readerInit(`, so I was wondering if those should be used to check these difference between source versions  (as pointed out by Exinaus 
> theoretically, AllHentai uses different (previous) function because work on this site is still in progress

)
becuase I don't think we should be checking for source title in the multisrc code, or am I misunderstanding something?

Comment (Exinaus) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:324]: That's the name of JavaScript function where site stores all the images for a chapter
Безымянный

Where else it should be checked?

**Review by AwkwardPeak7 — APPROVED** [review]

File: lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt (hunk 2 above)
Comment (AwkwardPeak7) [reply lib-multisrc/grouple/src/eu/kanade/tachiyomi/multisrc/grouple/GroupLe.kt:217]: yea misunderstood the code/intent from the pr diff
