### PR TITLE
DemonSect: Migrate theme

### LINKED ISSUE #4347: Demon Sect erro
### Source information

Demon Sect 1.4.44

### Source language

Português (Brasil)

### Steps to reproduce

A Demon Sect não Funciona no aplicativo, mas está funcionando no Webview 

Aplicativo 
Screenshot_20240730-132911

Webview 
Screenshot_20240730-132921

### Expected behavior

Funcionando normalmente a extensão 

### Actual behavior

A extensão não está carregando normalmente

### Mihon/Tachiyomi version

Mihon 016.5

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #4347

* The URL paths are compatible, but I've added information in case they're not all compatible.

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/prismascans/src/eu/kanade/tachiyomi/extension/pt/prismascans/DemonSect.kt [hunk 1]
```diff
@@ -1,71 +1,40 @@
...
         .build()
 
-    override val useLoadMoreRequest = LoadMoreStrategy.Never
-
-    override val useNewChapterEndpoint = true
-
-    override fun fetchPopularManga(page: Int): Observable<MangasPage> {
-        return client.newCall(popularMangaRequest(page))
-            .asObservable() // Site returns http 404 even if the result is successful
+    override fun fetchMangaDetails(manga: SManga): Observable<SManga> {
```
Comment (AwkwardPeak7) [inline src/pt/prismascans/src/eu/kanade/tachiyomi/extension/pt/prismascans/DemonSect.kt]: add to fetchChapterList instead

**Comment by EnzooFelixDev** [comment]
O que faço para resolver esse problema?

**Comment by Norsze** [comment]
@Dionisooo1 Você não faz nada porque não pode ajudar, você senta e espera alguém consertar.

You don't do anything since you can't help, you sit and wait for someone to fix it.

**Review by AwkwardPeak7 — APPROVED** [review]
