### PR TITLE
LilyManga: Add rateLimit

### LINKED ISSUE #8121: Getting frequent HTTP Error 429 on LilyManga
### Source information

Lily Manga 1.4.44

### Source language

English

### Steps to reproduce

1. Open Mihon app
2. Browse mangas inside Lily Manga source
3. Find a cover that interests me
4. Open said manga so I can check summary and # of chapters
5. Start reading it (if more than, say, 5 chapters) or go back to main source page
6. Repeat steps 3-5 a couple times and get error 429

### Expected behavior

I should be rate limited so I won't be IP banned

### Actual behavior

My IP is banned and I can't access the extension for a couple hours 
(unsure on how many hours, I usually go to sleep when it happens and it works fine the next day)

Image
Image

### Mihon/Tachiyomi version

Mihon 0.17.1

### Android version

Android 14

### Other details

Edited for clarification. I'm not purposefully DDoSing the app nor trying to break it through malicious means. I'm merely trying to find more nice yuri mangas from my favorite source (also thank you devs for fixing the cloudflare issue <3) I have done the same steps while browsing on every other source I have and have never gotten this error.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #8121

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/lilymanga/src/eu/kanade/tachiyomi/extension/en/lilymanga/LilyManga.kt [hunk 1]
```diff
@@ -1,9 +1,23 @@
...
 
-class LilyManga : Madara("Lily Manga", "https://lilymanga.net", "en", SimpleDateFormat("yyyy-MM-dd", Locale.US)) {
+class LilyManga : Madara(
+    "Lily Manga",
+    "https://lilymanga.net",
+    "en",
+    dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.US),
+) {
+    override val client = super.client.newBuilder()
+        .rateLimit(1, 2)
```
Comment (vetleledaal) [inline src/en/lilymanga/src/eu/kanade/tachiyomi/extension/en/lilymanga/LilyManga.kt]:
```suggestion
        .rateLimitHost(baseUrl.toHttpUrl(), 1, 2)
```

I don't think the CDN affects rate limiting. (requires import)

**Review by vetleledaal — APPROVED** [review]
