### PR TITLE
Kagane: Update API Endpoint

### LINKED ISSUE #13330: Kagane: `Unable to resolve host`/`HTTP 404` error, new API/API URL
### Source information

Kagane 1.4.16

### Source language

English

### Steps to reproduce

1. Browse
2. Sources
3. "Kagane"

In WebView the source is working 

### Expected behavior

The source should be working and showing the library

### Actual behavior

Image

### Mihon/Mihon fork version

Mihon 0.19.3

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FumoRin**
> [!WARNING]  
> This PR still needs to be worked on. Most of the changes need to be reviewed first, since I relied on AI to guide me

This PR will close #13330. The extension is tested only to get the most popular and latest manga and read them. Filters need to be worked on, but I have something to do tomorrow. Expect some late follow-up 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by FumoRin** [comment]
PR changed to draft because there's still problem when fetching the image and causing error 404. Highly possible that the URL isn't constructed correctly

**Comment by D-Brox** [comment]
You can check my work on the Filters in https://github.com/D-Brox/extensions-source/tree/kagane-drm , it's mostly on the last commit.

I've also dealt with malformed URLs on the previous commit, so you can take a look there too.

My branch works, however only with a [drm-proxy server](https://github.com/D-Brox/kagane-drm-proxy).

**Comment by FumoRin** [comment]
Thanks for the feedback. I'll try to check at your work as soon as I could get into my PC.

**Comment by FumoRin** [comment]
@D-Brox, I'm merging changes from your work (literally using most of your work since it's much better). The functionality for reading, fetching data, and filtering is now working. The only downside is that if you try to open a filter field for genre, tags, or source, it will take a long time to load the data (around 20 seconds for tags), and could potentially crash the Mihon app. I don't know how to optimize it, but I'll make the PR open anyway and try to work on it if possible.

Here's the logs that might show the issues with filters
```
2026-02-14 15:27:55.381 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background young concurrent copying GC freed 14MB AllocSpace bytes, 16(1580KB) LOS objects, 5% free, 122MB/129MB, paused 402us,69us total 348.304ms
2026-02-14 15:27:56.442 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background concurrent copying GC freed 96MB AllocSpace bytes, 15(2916KB) LOS objects, 33% free, 48MB/72MB, paused 395us,66us total 360.031ms
2026-02-14 15:27:56.764 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background young concurrent copying GC freed 27MB AllocSpace bytes, 4(360KB) LOS objects, 33% free, 46MB/70MB, paused 502us,63us total 105.893ms
2026-02-14 15:27:57.549 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background young concurrent copying GC freed 16MB AllocSpace bytes, 1(128KB) LOS objects, 16% free, 59MB/70MB, paused 837us,75us total 101.317ms
2026-02-14 15:27:58.371 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background concurrent copying GC freed 38MB AllocSpace bytes, 15(3912KB) LOS objects, 27% free, 62MB/86MB, paused 469us,65us total 378.919ms
2026-02-14 15:27:58.614 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background young concurrent copying GC freed 28MB AllocSpace bytes, 2(332KB) LOS objects, 28% free, 59MB/83MB, paused 383us,66us total 118.767ms
2026-02-14 15:27:59.094 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background young concurrent copying GC freed 5468KB AllocSpace bytes, 0(0B) LOS objects, 2% free, 81MB/83MB, paused 429us,70us total 257.785ms
2026-02-14 15:27:59.861 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background concurrent copying GC freed 5442KB AllocSpace bytes, 2(316KB) LOS objects, 22% free, 84MB/108MB, paused 265us,73us total 767.005ms
2026-02-14 15:28:05.193 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background young concurrent copying GC freed 5722KB AllocSpace bytes, 0(0B) LOS objects, 5% free, 102MB/108MB, paused 226us,181us total 461.855ms
2026-02-14 15:28:06.033 22927-22939 app.mihon.dev           app.mihon.dev                        I  Waiting for a blocking GC ProfileSaver
2026-02-14 15:28:06.236 22927-22932 app.mihon.dev           app.mihon.dev                        I  Background concurrent copying GC freed 6511KB AllocSpace bytes, 2(5296KB) LOS objects, 20% free, 93MB/117MB, paused 312us,74us total 871.464ms
2026-02-14 15:28:06.236 22927-22939 app.mihon.dev           app.mihon.dev                        I  WaitForGcToComplete blocked ProfileSaver on Background for 203.410ms
2026-02-14 15:28:21.124 22927-22932 app.mihon.dev           app.mihon.dev                        I  NativeAlloc concurrent copying GC freed 7923KB AllocSpace bytes, 5(172KB) LOS objects, 18% free, 106MB/130MB, paused 211us,176us total 1.107s
2026-02-14 15:28:22.895 22927-22927 Looper                  app.mihon.dev                        W  PerfMonitor longMsg : seq=4430 plan=15:27:54.549 late=6ms wall=28339ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver procState=-1
2026-02-14 15:28:22.895 22927-22927 Looper                  app.mihon.dev                        W  PerfMonitor doFrame : time=28339ms vsyncFrame=0 latency=6ms procState=-1 historyMsgCount=1
2026-02-14 15:28:22.902 22927-22927 Choreographer           app.mihon.dev                        I  Skipped 1333 frames!  The application may be doing too much work on its main thread.
2026-02-14 15:28:22.918 22927-23118 OpenGLRenderer          app.mihon.dev                        I  Davey! duration=28362ms; Flags=0, FrameTimelineVsyncId=12004383, IntendedVsync=44272783284937, Vsync=44272783284937, InputEventId=95072696, HandleInputStart=44272789991791, AnimationStart=44272790033945, PerformTraversalsStart=44278894838638, DrawStart=44278895057638, FrameDeadline=44272799951603, FrameInterval=44272789947791, FrameStartTime=16667382, SyncQueued=44301074281101, SyncStart=44301074443485, IssueDrawCommandsStart=44301127958870, SwapBuffers=44301137716716, FrameCompleted=44301145734024, DequeueBufferDuration=149923, QueueBufferDuration=787461, GpuCompleted=44301145734024, SwapBuffersCompleted=44301141433947, DisplayPresentTime=44270164432099, CommandSubmissionCompleted=44301137716716, 
2026-02-14 15:28:22.982 22927-22927 Looper                  app.mihon.dev                        W  PerfMonitor doFrame : time=80ms vsyncFrame=0 latency=22242ms procState=-1 historyMsgCount=4 (msgIndex=1 wall=28339ms seq=4430 late=6ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
2026-02-14 15:28:23.003 22927-23118 OpenGLRenderer          app.mihon.dev                        I  Davey! duration=22318ms; Flags=0, FrameTimelineVsyncId=12004542, IntendedVsync=44278894167176, Vsync=44301125122714, InputEventId=0, HandleInputStart=44301136825947, AnimationStart=44301136831793, PerformTraversalsStart=44301142985408, DrawStart=44301143170331, FrameDeadline=44278927500509, FrameInterval=44301136583178, FrameStartTime=16666667, SyncQueued=44301184620408, SyncStart=44301197389716, IssueDrawCommandsStart=44301216294639, SwapBuffers=44301217946562, FrameCompleted=44301225278255, DequeueBufferDuration=54231, QueueBufferDuration=421846, GpuCompleted=44301225278255, SwapBuffersCompleted=44301220186331, DisplayPresentTime=44270197755483, CommandSubmissionCompleted=44301217946562, 

```

**Comment by Kickunio** [comment]
Does it still need the drm proxy server for this build ? I get http error 400 after building the apk

**Comment by FumoRin** [comment]
I tested it without using the DRM Proxy Server, and I managed to have it able to read, fetch data, and filter working. Could you provide me with the HTTP request & response from the Mihon debugger?

**Comment by Kickunio** [comment]
I'm using suwayomi, so it seems the problem is only connected with suwayomi.

The only thing I scraped up from the log is:

12:30:02.078 [DefaultDispatcher-worker-1] DEBUG eu.kanade.tachiyomi.network.NetworkHelper -- <-- 400 https://yuzuki.kagane.org/api/v2/search/series?page=0&size=35&sort=updated_at%2Cdesc&scanlations=true (99ms, 168-byte body)
12:30:02.078 [DefaultDispatcher-worker-1] ERROR suwayomi.tachidesk.graphql.AsDataFetcherResult -- asDataFetcherResult: failed due to
eu.kanade.tachiyomi.network.HttpException: HTTP error 400

**Comment by D-Brox** [comment]
@FumoRin The old extension delayed the filters by making you press reset to load them, so maybe you can bring back that. 

I removed it because I just wanted to get it working first

**Comment by D-Brox** [comment]
@Kickunio I made the drm proxy server specifically with Suwayomi in mind lmao

I think they don't have support for POST requests in their cloudflare interceptor, so that's possibly it

**Comment by FumoRin** [comment]
The extension loads faster now. It's not as exact logic from the old extension because there's POST request to get the source list (I don't know why they do that ¯\_(ツ)_/¯ ). The filter field for genre and source still has a bit of a delay when opened, but not as bad as tags' 30+ seconds load time, since it's handling a 190kb JSON file now, compared to 3-4kb for genre and source. But overall, the extension is ready

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt [hunk 1]
```diff
@@ -8,110 +8,210 @@ import kotlinx.serialization.Serializable
...
+                desc.append("• ${it.title}\n")
+            }
+        }
+
+        // Extract authors from staff (roles like "Author", "Artist", "Story", "Art")
+        val authors = seriesStaff.filter {
+            it.role.contains("Author", ignoreCase = true) ||
+                it.role.contains("Story", ignoreCase = true) ||
+                it.role.contains("Art", ignoreCase = true) ||
+                it.role.contains("Artist", ignoreCase = true)
```
Comment (Secozzi) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: These should be added to the `artist` field in SManga

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/ImageInterceptor.kt [hunk 2]
```diff
@@ -1,228 +1,9 @@
...
-
-        val h = u.fold(ByteArray(0)) { acc, chunk -> acc + chunk }
-
-        return if (n) {
-            h + r
-        } else {
-            r + h
-        }
-    }
+    override fun intercept(chain: Interceptor.Chain): Response = chain.proceed(chain.request())
```
Comment (Secozzi) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/ImageInterceptor.kt]: Looks like the interceptor isn't needed at all? Also, remove the files for `Scrambler` and `Randomizer` if they're not needed

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 3]
```diff
@@ -609,6 +653,12 @@ class Kagane : HttpSource(), ConfigurableSource {
             setDefaultValue(false)
         }.let(screen::addPreference)
 
+        EditTextPreference(screen.context).apply {
+            key = DRM_PROXY_SERVER
+            title = "DRM proxy server url"
+            setDefaultValue(PROXY_DEFAULT)
+        }.let(screen::addPreference)
```
Comment (Secozzi) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: What is this used for?

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/ImageInterceptor.kt (hunk 2 above)
Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/ImageInterceptor.kt]: okay will do that

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt (hunk 3 above)
Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: that might be a leftover from @D-Brox that I haven't cleared yet

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt (hunk 1 above)
Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: The source merged the artist and author into one field, and now they didn't even filled the `series_staff` list, so I didn't know how to separate the artist and author to put them into the artist and author.  Should I change it with this snippet or do something else?

```kt
val artists = seriesStaff.filter {
    it.role.contains("Artist", ignoreCase = true) || it.role.contains("Art", ignoreCase = true)
}.map { it.name }.distinct()

artist = listOf(artists.joinToString()).toString()
```

Comment (Secozzi) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: I would really advise against calling `.toString()` on a list directly. The artist field should be a comma separated string so you can do

```kt
artist = seriesStaff.filter {
    it.role.contains("Artist", ignoreCase = true) || it.role.contains("Art", ignoreCase = true)
}
    .map { it.name }
    .distinct()
    .joinToString(", ")
```

Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: Okay thank you. I will do that

**Comment by FumoRin** [comment]
some problem after a long test, it looks like the token isn't able to refresh automatically after expired. So I need to fix that first before merging it

**Comment by FumoRin** [comment]
After a long test by myself, I could say that the extension is ready to be merged. I changed the tags to use text input to make it not render all of the tags' checkboxes (I figured that might be the cause of the 30+ seconds delay). The only problem now is the artist and author mapping, since the source still hasn't included one. I'll just let someone in the future work on it when the source fills the `series_staff` response

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt [hunk 4]
```diff
@@ -8,110 +8,214 @@ import kotlinx.serialization.Serializable
...
+        @SerialName("volume_no")
+        val volumeNo: String?,
     ) {
         fun toSChapter(useSourceChapterNumber: Boolean = false): SChapter = SChapter.create().apply {
-            url = "$seriesId;$id;$pagesCount"
-            name = title
-            date_upload = dateFormat.tryParse(releaseDate)
+            // series_id might be null in the books endpoint, so we extract it from the request URL later
+            val actualSeriesId = seriesId ?: "unknown"
+            url = "$actualSeriesId;$id;$pagesCount"
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt]: pass the actual one to this function

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 5]
```diff
@@ -202,30 +243,52 @@ class Kagane : HttpSource(), ConfigurableSource {
...
     override fun searchMangaParse(response: Response): MangasPage {
         val dto = response.parseAs<SearchDto>()
+        val sources = try {
+            val sourceResponse = metadataClient.newCall(
+                POST(
+                    "$apiUrl/api/v2/sources/list",
+                    apiHeaders,
+                    buildJsonObject { put("source_types", null) }.toJsonString()
+                        .toRequestBody("application/json".toMediaType()),
+                    CacheControl.FORCE_CACHE,
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: this will never be successful if this call was not already made once without `FORCE_CACHE`

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 6]
```diff
@@ -236,45 +299,36 @@ class Kagane : HttpSource(), ConfigurableSource {
...
         )
 
-        return dto.content.map { it -> it.toSChapter(useSourceChapterNumber) }.reversed()
+        return dto.seriesBooks.map { book ->
+            book.toSChapter(useSourceChapterNumber).apply {
+                // Fix the URL to include the actual seriesId
+                url = "/series/$seriesId/reader/${book.id}"
+            }
+        }.reversed()
     }
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:324]: see my other comment, pass the actual id to the function

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 7]
```diff
@@ -283,49 +337,64 @@ class Kagane : HttpSource(), ConfigurableSource {
...
     override fun fetchPageList(chapter: SChapter): Observable<List<Page>> {
-        if (chapter.url.count { it == ';' } != 2) throw Exception("Chapter url error, please refresh chapter list.")
-        var (seriesId, chapterId, pageCount) = chapter.url.split(";")
-
-        val challengeResp = getChallengeResponse(seriesId, chapterId)
+        val chapterId = "$baseUrl${chapter.url}".toHttpUrl().pathSegments.last()
+        val challengeResp = getChallengeResponse(chapterId)
+        Log.d("challenge", challengeResp.accessToken)
+        Log.d("challenge", "${challengeResp.pages.map { page -> page.pageUuid }}")
+        Log.d("challenge", challengeResp.cacheUrl)
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: remove logs

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 8]
```diff
@@ -283,49 +337,64 @@ class Kagane : HttpSource(), ConfigurableSource {
...
 
-    private val fairPlayCertificate by lazy { getCertificate("$apiUrl/api/v1/static/crt.crt") }
+    private val fairPlayCertificate by lazy { getCertificate("$apiUrl/api/v2/static/crt.crt") }
 
     override fun fetchPageList(chapter: SChapter): Observable<List<Page>> {
-        if (chapter.url.count { it == ';' } != 2) throw Exception("Chapter url error, please refresh chapter list.")
-        var (seriesId, chapterId, pageCount) = chapter.url.split(";")
-
-        val challengeResp = getChallengeResponse(seriesId, chapterId)
+        val chapterId = "$baseUrl${chapter.url}".toHttpUrl().pathSegments.last()
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:348]: check if chapter url is old format, and throw exception asking user to refresh chapter list

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 9]
```diff
@@ -334,16 +403,16 @@ class Kagane : HttpSource(), ConfigurableSource {
...
+                .addQueryParameter("is_datasaver", preferences.dataSaver.toString())
+                .build()
         val challengeBody = buildJsonObject {
             put("challenge", challenge)
         }.toJsonString().toRequestBody("application/json".toMediaType())
 
-        return client.newCall(POST(challengeUrl.toString(), apiHeaders, challengeBody)).execute()
+        val headers = apiHeaders.newBuilder().add("x-integrity-token", integrityToken).build()
+
+        return client.newCall(POST(challengeUrl.toString(), headers, challengeBody)).execute()
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:412]:
```suggestion
        return client.newCall(POST(challengeUrl, headers, challengeBody)).execute()
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt (hunk 9 above)
Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:412]: The suggested change gave me the IDE error shown below. What should I do?
```
Argument type mismatch: actual type is 'HttpUrl', but 'String' was expected.
```

Comment (AwkwardPeak7) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:412]: my bad, leave it as is

this suggestion generally applies to `GET` helper

Comment (FumoRin) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:412]: Alright, I'm not touching that

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by Qwerty0uiop** [comment]
There is a source name in title issue, instead the source name in title, there is [Null].
Migration to the new version of the extension doesn't display the previously downloaded chapters.

**Comment by SuperMario22922** [comment]
> There is a source name in title issue, instead the source name in title, there is [Null]. Migration to the new version of the extension doesn't display the previously downloaded chapters.

CleanShot 2026-02-15 at 22 02 48@2x
This is an example of what this means it all has "null" in the brackets

**Comment by DevkotaOSA** [comment]
Cloudbypass error. Loading just fine when I press web. Is there a solution to that? Restarted the app and still same problem despite the web working. In the setting it has a WVD file insert. Does that matter or can I leave it blank? 

Screenshot_20260215_060125_Aniyomi

**Comment by Kickunio** [comment]
For me, on mihon and on suwayomi there's HTTP error 400 when go for latest, popular or filter tabs in source. Webview works ok on both.

**Comment by ghost** [comment]
I'm seeing this on the Komikku app:

> JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
JSON Input:

Should I create another issue? 
What should I do?

**Comment by nekonyappii-sketch** [comment]
> For me, on mihon and on suwayomi there's HTTP error 400 when go for latest, popular or filter tabs in source. Webview works ok on both.

Same, you might want to go to advance and clear cookies and Webview data cause it works for me after that

**Comment by Qwerty0uiop** [comment]
You're having issues because you're still dealing with the old version of the extension, migrate your series to the new version of the extension. That will fix this problem of yours.

**Comment by FiddleMySticks** [comment]
If you guys are having cloudflare issues, clear cookies and webview data and use the default mihon user agent (the one you have by default when you fresh install the app). Fixed my issue and now chapters load just fine.

There is still the problem with the source names being [null].

**Comment by ghost** [comment]
I have updated my extension, that's the first thing I did 😅.

> You're having issues because you're still dealing with the old version of the extension, migrate your series to the new version of the extension. That will fix this problem of yours.

Ok so I refreshed the webview and cookies data, and updated the extension, but now it is saying this:

> Outdated chapter URL. Refresh the chapter list

How do I 'refresh the chapter list'?

**Comment by honggie96** [comment]
> clear cookies and webview data and use the default mihon user agent (the one you have by default when you fresh install the app)

re-install extension and do all above, still got error 400, only work with webview

**Comment by Qwerty0uiop** [comment]
> I have updated my extension, that's the first thing I did 😅.
> 
> > You're having issues because you're still dealing with the old version of the extension, migrate your series to the new version of the extension. That will fix this problem of yours.
> 
> Ok so I refreshed the webview and cookies data, and updated the extension, but now it is saying this:
> 
> > Outdated chapter URL. Refresh the chapter list
> 
> How do I 'refresh the chapter list'?

Then Did you migrate your Manhwa to the new version of extension [kagane], it's as adding it new.

**Comment by FiddleMySticks** [comment]
Yea, you need to remove them from the library and add them again. All the ones that were in the library prior to the update are broken, they need to be re-added

**Comment by ghost** [comment]
> > I have updated my extension, that's the first thing I did 😅.
> > > You're having issues because you're still dealing with the old version of the extension, migrate your series to the new version of the extension. That will fix this problem of yours.
> > 
> > 
> > Ok so I refreshed the webview and cookies data, and updated the extension, but now it is saying this:
> > > Outdated chapter URL. Refresh the chapter list
> > 
> > 
> > How do I 'refresh the chapter list'?
> 
> Then Did you migrate your Manhwa to the new version of extension [kagane], it's as adding it new.

Oh ok so I have to re-add all of the manwha.

**Comment by FiddleMySticks** [comment]
If I were you, I would wait a bit until they fix the [null] issue.

Otherwise, you may need to re-add them again after if they break again :)

**Comment by Qwerty0uiop** [comment]
> > > I have updated my extension, that's the first thing I did 😅.
> > > > You're having issues because you're still dealing with the old version of the extension, migrate your series to the new version of the extension. That will fix this problem of yours.
> > > 
> > > 
> > > Ok so I refreshed the webview and cookies data, and updated the extension, but now it is saying this:
> > > > Outdated chapter URL. Refresh the chapter list
> > > 
> > > 
> > > How do I 'refresh the chapter list'?
> > 
> > 
> > Then Did you migrate your Manhwa to the new version of extension [kagane], it's as adding it new.
> 
> Oh ok so I have to re-add all of the manwha.

Instead of adding them again, just go to the Manhwa page, press the 3 points, press migrate, choose Kegane extension, then select the same Manhwa.

**Comment by ghost** [comment]
@Qwerty0uiop and @FiddleMySticks ok thanks I understand.

**Comment by Qwerty0uiop** [comment]
> > If you guys are having cloudflare issues, clear cookies and webview data and use the default mihon user agent (the one you have by default when you fresh install the app). Fixed my issue and now chapters load just fine.
> > There is still the problem with the source names being [null].
> 
> I did everything but it still says failed to bypass cloudfare 🥲

Try this, if you did migrate the Manhwa to the new version of the extension, too. open webview to open the Manhwa page once.
Then get back to the mihon Manhwa page, it will work then.

**Comment by proler-48** [comment]
The chapters are still not working for me. I've tried clearing both the cookies and webview data. I've also checked whether they work on other titles which are added to the library after the update (they dont)

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt (hunk 3 above)
Comment (D-Brox) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: @Secozzi that was a way to bypass the drm and cloudflare challenges using https://github.com/D-Brox/kagane-drm-proxy, it's possibly needed for suwayomi to work at the moment, since they don't support POST requests in their cloudflare interceptor yet

Comment (Secozzi) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: > @Secozzi that was a way to bypass the drm and cloudflare challenges using https://github.com/D-Brox/kagane-drm-proxy, it's possibly needed for suwayomi to work at the moment, since they don't support POST requests in their cloudflare interceptor yet

There's already https://github.com/keiyoushi/extensions-source/pull/12193, which I made specifically for suwayomi

Comment (D-Brox) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: I know, but kagane now requires a POST request to their new integrity endoint (I haven't tested the new update yet tho)

Comment (Secozzi) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: > (I haven't tested the new update yet tho)

I have, it works just fine in suwayomi.

Comment (D-Brox) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: image

It doesn't tho, it's making a GET request on a POST endpoint (hence "Method not allowed")

**Comment by DevkotaOSA** [comment]
> The chapters are still not working for me. I've tried clearing both the cookies and webview data. I've also checked whether they work on other titles which are added to the library after the update (they dont)

Same, it still saying bypass issue. I know there's still some tweaking to be done so I'll be patient. If there's another pull request please lmk.

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt (hunk 3 above)
Comment (D-Brox) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: Welp

https://github.com/Suwayomi/Suwayomi-Server/pull/1909

**Comment by JochemKuipers** [comment]
for me i can read chapters just fine but searching/migrating the manga is finicky. sometimes it gives results but most of the time i get a 400 error. even when in the webview i get through cloudflare captcha it still gives me the same error. only when i force close the app and delete all cookies can i get results a single time. then it immediatly starts giving me 400 error again

**Comment by Smol-Ame** [comment]
This is a closed/merged PR, there's existing requests & a new PR. Read the issue request + comments for whatever issue you're experiencing, otherwise wait patiently & quietly for a fix if you don't have useful information for contributors to figure out a fix.
