### PR TITLE
SlimeRead: Get api url from page

### LINKED ISSUE #2706: SlimeRead changed API(again)
### Source information

SlimeRead 1.4.7

### Source language

Brazilian Portuguese

### Steps to reproduce

the website's webview is working perfectly along with the rest of the website's functions, it seems that the api has been changed again. 
47825122-cee9-409f-b8c0-b2e68c8f859c

### Expected behavior

With this update it worked for a while but the api changed again.

### Actual behavior

As said above, all site functions working perfectly except the extension itself.

### Mihon/Tachiyomi version

Tachiyomi Stable 0.15.3

### Android version

11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #2706

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt [hunk 1]
```diff
@@ -48,6 +50,29 @@ class SlimeRead : HttpSource() {
 
     private val json: Json by injectLazy()
 
+    private fun getApiUrlFromPage(): String {
+        val initClient = network.client
```
Comment (AwkwardPeak7) [inline src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt:54]: why this? if you want a client without cloudflare interceptor, you woul have to manually remove it from the interceptors

Comment (bapeey) [reply src/pt/slimeread/src/eu/kanade/tachiyomi/extension/pt/slimeread/SlimeRead.kt:54]: the client needs the apiUrl for ratelimit so it needs to use another

**Review by AwkwardPeak7 — APPROVED** [review]
