### PR TITLE
Nekopost - Search Error "HTTP 404" Fix

### LINKED ISSUE #9549: Nekopost - Search Error "HTTP 404"
### Source information

Nekopost 1.4.12

### Source language

Thai / TH

### Steps to reproduce

1. Go to "Browse" section of Mihon.
2. Enter "Nekopost" source.
3. Do a search with any query.

Searching in "Nekopost" source

### Expected behavior

Search results should get shown.

### Actual behavior

- Error occurred with message "HTTP 404, check website in WebView".
- When click "Open in WebView", it just shows the index page ([https://www.nekopost.net/](https://www.nekopost.net/)).

HTTP 404, check website in WebView

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 14

### Other details

- I took a quick look at the source code (and judging from 404 error code), and I think API URL might be wrong.
- Current source code uses "https://www.nekopost.net/api/explore/search" to do a search.
- But I got "https://www.nekopost.net/api/project/search" from searching manually on web browser (Firefox) on desktop (Windows) and using browser's devtools to inspect the POST request.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by keegang6705**
Closes #9549 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/model/SearchRequest.kt [hunk 1]
```diff
@@ -2,8 +2,15 @@ package eu.kanade.tachiyomi.extension.th.nekopost.model
 
 import kotlinx.serialization.Serializable
 
+@Serializable
+data class PagingRequest(
```
Comment (vetleledaal) [inline src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/model/SearchRequest.kt]: Consider naming this something else. Currently it sounds like a standalone request, not a subset of another request.

File: src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/model/RawProjectSearchSummary.kt [hunk 2]
```diff
@@ -1,19 +1,42 @@
...
+    val readerGroup: String = "",
+    val releaseDate: ProjectDate = ProjectDate(),
+    val updateDate: ProjectDate = ProjectDate(),
+    val views: Int = 0,
+    val imageVersion: Int = 0,
+    val noChapter: Int = 0,
+    val coverVersion: Int = 0,
+    val concatCate: String = "",
+    val editorId: Int = 0,
+    val editorName: String = "",
```
Comment (vetleledaal) [inline src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/model/RawProjectSearchSummary.kt]: Don't assign a default for fields that are always sent.

Consider omitting fields you aren't using in the code.

**Comment by vetleledaal** [comment]
Also, use [the default syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when you intend to close issues.

**Review by vetleledaal — APPROVED** [review]
