### PR TITLE
NekoScans: Fix selectors and domain

### LINKED ISSUE #7336: NekoScans the font does not recognize the website
### Source information

NekoScans 1.4.34

### Source language

Spanish 

### Steps to reproduce

The font does not respond correctly no matter how many times I load it 

Image

### Expected behavior

The website is working normally 

Image

### Actual behavior

The website works normally, but the font is not responding and does not load normally. 

### Mihon/Tachiyomi version

Mihon 0.17.1

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #7336 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt [hunk 1]
```diff
@@ -16,6 +23,47 @@ class NekoScans : ZeistManga(
...
+    override val mangaDetailsSelectorArtist = "#extra-info dl:contains(Artista) > dd"
+    override val mangaDetailsSelectorInfo = "span.mr-2.rounded"
+
+    @RequiresApi(Build.VERSION_CODES.N)
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+        val blog = document.selectFirst(mangaDetailsSelector)!!
+        return SManga.create().apply {
+            thumbnail_url = blog.selectFirst("header div.grid > img")!!.attr("abs:src")
+            description = blog.select("script").map { it.data() }
```
Comment (bapeey) [inline src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt]: why not use `mangaDetailsSelectorDescription`

Comment (lordenecromante) [reply src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt]: Fix it

File: src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt [hunk 2]
```diff
@@ -16,6 +23,47 @@ class NekoScans : ZeistManga(
...
+                    val tempText = rawText.replace("\n\n", "##NL##")
+
+                    // Decode HTML characters and restore double newlines
+                    val decodedText = Html.fromHtml(tempText, Html.FROM_HTML_MODE_LEGACY)
+                        .toString()
+                        .replace("##NL##", "\n\n")
+
+                    // Remove everything from "País:" onward
+                    decodedText.substringBefore("País:").trim()
+                }
```
Comment (bapeey) [inline src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt]:
```suggestion
            description = blog.select(mangaDetailsSelectorDescription).text()
```

Try this and remember to test the new changes

Comment (lordenecromante) [reply src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt]: It won't work, the description is inside a script element. I convert it to JSON and extract the information from articleBody, using FROM_HTML_MODE_LEGACY to handle special characters. I remove line breaks beforehand because FROM_HTML_MODE_LEGACY removes them, causing the text to be all joined together.

Comment (bapeey) [reply src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt]: I can find the description in the html 
{4A237DEC-EEF1-4A54-AAEE-B5FBDF298434}

Comment (lordenecromante) [reply src/es/nekoscans/src/eu/kanade/tachiyomi/extension/es/nekoscans/NekoScans.kt]: Fix it

**Review by AwkwardPeak7 — APPROVED** [review]
