### PR TITLE
ManhwaFreakXyz: Migrate theme

### LINKED ISSUE #7710: ManhwaFreak.xyz not working
### Source information

ManhwaFreak.xyz 1.4.30

### Source language

English 

### Steps to reproduce

Open source, shows error 404, however web view directs to site

### Expected behavior

To show titles 

### Actual behavior

Shows 404, even though webview works.

Image

Image

### Mihon/Tachiyomi version

Tachij2k 

### Android version

14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #7710

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt [hunk 1]
```diff
@@ -1,11 +1,133 @@
...
+
+    // ===================== Search ============================
+
+    override fun searchRequest(page: Int, query: String, filters: FilterList): Request {
+        val document = client.newCall(popularMangaRequest(1)).execute().asJsoup()
+        val nonce = document.select("script")
+            .map(Element::data)
+            .firstOrNull { it.contains("'nonce','") }
+            ?.substringAfter("'nonce','")
+            ?.substringBefore("'")
```
Comment (AwkwardPeak7) [inline src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt]: consider moving this logic outside so it can be set on other page loads (popular/latest/maybe details)

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt [hunk 2]
```diff
@@ -1,11 +1,133 @@
...
+import kotlinx.serialization.json.decodeFromStream
+import okhttp3.FormBody
+import okhttp3.HttpUrl.Companion.toHttpUrl
+import okhttp3.Request
+import okhttp3.Response
+import org.jsoup.nodes.Document
+import org.jsoup.nodes.Element
 
-class ManhwaFreakXyz : MangaThemesia(
+class ManhwaFreakXyz : Madara(
```
Comment (vetleledaal) [inline src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt:22]: Bump `versionId`?

File: src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt (hunk 1 above)
Comment (choppeh) [reply src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt]: > consider moving this logic outside so it can be set on other page loads (popular/latest/maybe details)

This can be tricky, because moving this logic somewhere else causes a failure when you run the search directly.

Global search is an example

File: src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt (hunk 2 above)
Comment (choppeh) [reply src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt:22]: > Bump `versionId`?

I didn't do it, because some slugs are equal

File: src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt (hunk 1 above)
Comment (AwkwardPeak7) [reply src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt]: Check if empty and fetch it, maybe in custom getter

File: src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt [hunk 3]
```diff
@@ -1,11 +1,145 @@
...
+            SManga.create().apply {
+                title = it.title
+                thumbnail_url = it.thumbnail
+                setUrlWithoutDomain(it.url)
+            }
+        }
+        return MangasPage(mangas, hasNextPage = false)
+    }
+
+    private var nonce: String = ""
```
Comment (AwkwardPeak7) [inline src/en/manhwafreakxyz/src/eu/kanade/tachiyomi/extension/en/manhwafreakxyz/ManhwaFreakXyz.kt:104]: can it also be set during popular/latest/details?

**Review by AwkwardPeak7 — APPROVED** [review]
