### PR TITLE
Kmanga fix chapter name parsing

### LINKED ISSUE #14302: K Manga: Split chapters use wrong chapter numbers
### Source information

K Manga 1.4.3

### Source language

English

### Steps to reproduce

1. Install the K Manga extension (version 1.4.3)
2. Add a manga that contains split chapters, such as:
   - `I'm a Curse Crafter, and I Don't Need an S-Rank Party!`
   - `The Remarkable Revenge of a Vindictive Villainess`
3. Observe the chapter list. For example, the manga `I'm a Curse Crafter...` shows chapters like:
   ```
   CHAPTER 56(1) That Hero, This Curse Crafter
   CHAPTER 55(3) Locking Swords
   CHAPTER 55(2) Locking Swords
   CHAPTER 55(1) Locking Swords
   ...
   ```
   but the assigned chapter numbers are not the expected `55.3`, `55.2`, `55.1`, etc. after reading (wrong number in history and tracking)

### Expected behavior

Chapters that have a part suffix (e.g., `(1)`, `(2)`, `(3)`) should be numbered as `X.Y` (where X is the main chapter number and Y is the part). For example, `CHAPTER 55(3)` should be `55.3`.

### Actual behavior

The extension currently uses the `index` field from the API as the chapter number, which corresponds to the order in the episode list rather than the actual chapter numbering. This leads to arbitrary numbers like `133` for `CHAPTER 55(3)` instead of the expected `55.3`. This occurs because in `Dto.kt` the `toSChapter` function sets `chapter_number = index.toFloat()`.

### Mihon/Mihon fork version

TachiyomiSY 1.12.0

### Android version

Android 16

### Other details

The issue appears to be in the mapping of episode data to `SChapter`. The `Episode` class has an `index` property which is used as the chapter number. However, for split chapters, the actual chapter number is embedded in the `episode_name`. The current code:

```kotlin
// Dto.kt
fun toSChapter(dateFormat: SimpleDateFormat): SChapter = SChapter.create().apply {
    url = "/title/$titleId/episode/$episodeId"
    val lock = if (isLocked) "🔒 " else ""
    name = lock + episodeName
    chapter_number = index.toFloat()   // <-- problem
    date_upload = dateFormat.tryParse(startTime)
}
```

The chapter number should be parsed from `episodeName` (e.g., extract `55` and `(3)` to form `55.3`) and fallback to index if that fails.

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14302

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kmanga/src/eu/kanade/tachiyomi/extension/en/kmanga/Dto.kt [hunk 1]
```diff
@@ -92,8 +96,34 @@ class Episode(
...
+            ?: splitChapterRegex.find(episodeName)
+            ?: fallbackChapterRegex.find(episodeName)
+
+        chapter_number = if (match != null) {
+            val main = match.groupValues[1]
+            val part = match.groupValues[2]
+
+            if (part.isNotEmpty()) {
+                // Modify the display name visually so "CHAPTER 55(3)" becomes "CHAPTER 55.3"
+                val replacement = match.value.replaceFirst(Regex("""\s*[(（]$part[)）]"""), ".$part")
```
Comment (MuhamadSyabitHidayattulloh) [inline src/en/kmanga/src/eu/kanade/tachiyomi/extension/en/kmanga/Dto.kt]: Seperate this regex to

File: src/en/kmanga/src/eu/kanade/tachiyomi/extension/en/kmanga/Dto.kt [hunk 2]
```diff
@@ -92,8 +96,34 @@ class Episode(
...
+                parsedName = parsedName.replaceRange(match.range, replacement)
+
```
Comment (MuhamadSyabitHidayattulloh) [inline src/en/kmanga/src/eu/kanade/tachiyomi/extension/en/kmanga/Dto.kt]: Source have "10.5(2)"?

**Review by AwkwardPeak7 — APPROVED** [review]
