### PR TITLE
Azora: fix completed filter

### LINKED ISSUE #13644: Azora(AR): NO MANGA on COMPLETED filter
### Source information

Azora  1.4.55

### Source language

Arabic

### Steps to reproduce

Steps to reproduce:
 - Open Azora extension.
 - Apply the COMPLETED filter.
 - No manga results are displayed.

### Expected behavior

When applying the COMPLETED filter, the extension should display all completed manga, similar to the website behavior.

### Actual behavior

Applying the COMPLETED filter returns no results, even though the website displays the completed manga correctly.

### Mihon/Mihon fork version

Mihon 0.19.4

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by xMohnad**
Closes #13644

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt [hunk 1]
```diff
@@ -100,13 +100,21 @@ abstract class Iken(
...
 
         val hasNextPage = data.totalCount > (page * PER_PAGE)
+        if (entries.isEmpty() && hasNextPage) {
+            page += 1
+            val newUrl = response.request.url.newBuilder()
+                .setQueryParameter("page", page.toString())
+                .build()
+            val newResponse = client.newCall(GET(newUrl)).execute()
+            return searchMangaParse(newResponse)
+        }
```
Comment (AwkwardPeak7) [inline lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt:133]: if this is only for azora, move it there

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt (hunk 1 above)
Comment (xMohnad) [reply lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt:133]: This isn’t Azora-specific; it handles any page that ends up empty after filtering novels. It should stay in Iken.kt.

Comment (AwkwardPeak7) [reply lib-multisrc/iken/src/eu/kanade/tachiyomi/multisrc/iken/Iken.kt:133]: then app requests next same page again. keep track of internal page number in class (see [this](https://github.com/keiyoushi/extensions-source/blob/main/src/ar/mangapro/src/eu/kanade/tachiyomi/extension/ar/mangapro/ProChan.kt#L183-L191)), and call it instead of app provided one. also bump iken version

**Review by AwkwardPeak7 — APPROVED** [review]
