### PR TITLE
Manga District: fix thumbnail

### LINKED ISSUE #3126: Manga District: Covers turn white/missing when entering titles
### Source information

Manga District 1.4.40

### Source language

English

### Steps to reproduce

1) Go to source browse page in app
2) Enter any title & let it load
3) The cover (that was displayed in the source browse) turns white/blank

### Expected behavior

Cover should stay covered

### Actual behavior

Cover doesn't cover

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by vetleledaal**
Closes #3126

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/mangadistrict/src/eu/kanade/tachiyomi/extension/en/mangadistrict/MangaDistrict.kt [hunk 1]
```diff
@@ -90,6 +90,13 @@ class MangaDistrict :
         }.let(screen::addPreference)
     }
 
+    override fun imageFromElement(element: Element): String? {
+        return when {
+            element.hasAttr("data-wpfc-original-src") -> element.attr("data-wpfc-original-src")
```
Comment (AwkwardPeak7) [inline src/en/mangadistrict/src/eu/kanade/tachiyomi/extension/en/mangadistrict/MangaDistrict.kt]: use `absUrl`

Comment (vetleledaal) [reply src/en/mangadistrict/src/eu/kanade/tachiyomi/extension/en/mangadistrict/MangaDistrict.kt]: Changed it so it's prefixed with `abs:`, consistent with the super method.

Out of curiosity, when would you use `absUrl` over prefixing the attribute with `abs:`? Personal preference?

Comment (AwkwardPeak7) [reply src/en/mangadistrict/src/eu/kanade/tachiyomi/extension/en/mangadistrict/MangaDistrict.kt]: both are essentially the same, but I think `absUrl` is more clear imo in terms that it is accessing absolute url from the given attribute, whereas `abs:attr` can be misinterpreted for being a literal attribute.

**Review by AwkwardPeak7 — APPROVED** [review]
