### PR TITLE
Anchira: Fix API changes

### LINKED ISSUE #3036: Anchira Bugged
### Source information

Anchira 1.4.12

### Source language

English 

### Steps to reproduce

1. Click on read chapter
2. Loading but then, kicked out
3. Have some reminders below

### Expected behavior

Opens normally

### Actual behavior

IMG_20240515_173339

### Mihon/Tachiyomi version

TachiyomiJ2K 1.7.4

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by LetrixZ**
Closes #3036

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt
Comment (AwkwardPeak7) [inline src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt:1]: remove `data` from rest of dtos too

simple classes should suffice

**Comment by BrutuZ** [comment]
LibraryResponse changed the covers too. PR'd https://github.com/BrutuZ/extensions-source/commit/de2bb1d65d28eccd7cd70050056e9950c406fac0 to your branch as a way to add to this PR

File: src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt [hunk 1]
```diff
@@ -33,19 +35,18 @@ data class Entry(
...
 )
 
 @Serializable
-data class EntryKey(
+class EntryKey(
     val id: Int,
     val key: String? = null,
     val hash: String? = null,
     val url: String? = null,
-    val names: List<String> = emptyList(),
```
Comment (BrutuZ) [inline src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt:46]: Isn't this needed for the gallery-data list on `anchiraData`?

Comment (LetrixZ) [reply src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt:46]: It isn't needed anymore since the image names are now included in the gallery response (again).

File: src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt [hunk 2]
```diff
@@ -3,22 +3,24 @@ package eu.kanade.tachiyomi.extension.en.anchira
 import kotlinx.serialization.SerialName
 import kotlinx.serialization.Serializable
 
+private val nothing = null
+
```
Comment (AwkwardPeak7) [inline src/en/anchira/src/eu/kanade/tachiyomi/extension/en/anchira/AnchiraDto.kt]:
```suggestion
```

**Review by AwkwardPeak7 — APPROVED** [review]
