### PR TITLE
Happymh: Support search filters

### LINKED ISSUE #8223: Happymh: invalid chapter order
### Source information

Happymh:1.4.17

### Source language

chinese

### Steps to reproduce

1. download Happymh plugin
2. Open any comic
3. Slide down and can see that situation

### Expected behavior

Episode 364
Episode 363
Episode 362
Episode 361
Episode 360
Announcement
Episode 359
Episode 358
Episode 357

### Actual behavior

Episode 364
Episode 363
Episode 362
Episode 360
Episode 361
Announcement
Episode 359
Episode 358
Episode 357

### Mihon/Tachiyomi version

Stable 0.18.0

### Android version

Android 14

### Other details

The screenshot
Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #8973: Add category  feature for 嗨皮漫画
### Source name

嗨皮漫画

### Source language

中文

### Describe your suggested feature

Would like to recommned to have category feature for this sources

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AlphaBoom**
Close #8223 
Based on the description of this issue, the Order field returned by the server is inconsistent with the display order on the webpage. Therefore, the logic for sorting by the Order field has been removed.
Close #8973 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 1]
```diff
@@ -119,22 +119,46 @@ class Happymh : HttpSource(), ConfigurableSource {
...
+                url.addQueryParameter(it.key, it.selected)
+            }
+        }
+        val header = headersBuilder().add("referer", "$baseUrl/latest/${url.build().query}").build()
+        url.addQueryParameter("pn", page.toString())
+        return GET(url.build(), header)
     }
 
     override fun searchMangaParse(response: Response): MangasPage {
+        if (response.request.url.toString().contains("/apis/c/index")) {
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]: Check against `response.request.url.pathSegments instead.

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 2]
```diff
@@ -119,22 +119,46 @@ class Happymh : HttpSource(), ConfigurableSource {
...
-        return POST("$baseUrl/v2.0/apis/manga/ssearch", header, body)
+            return POST("$baseUrl/v2.0/apis/manga/ssearch", header, body)
+        }
+        val url = "$baseUrl/apis/c/index".toHttpUrl().newBuilder()
+        filters.filterIsInstance<UriPartFilter>().forEach {
+            if (it.selected.isNotEmpty()) {
+                url.addQueryParameter(it.key, it.selected)
+            }
+        }
+        val header = headersBuilder().add("referer", "$baseUrl/latest/${url.build().query}").build()
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]:
```suggestion
        val headers = headersBuilder().add("Referer", "$baseUrl/latest/${url.build().query}").build()
```

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt [hunk 3]
```diff
@@ -119,22 +119,46 @@ class Happymh : HttpSource(), ConfigurableSource {
...
+                .addEncoded("searchkey", query)
+                .add("v", "v2.13")
+                .build()
 
-        val header = headersBuilder()
-            .add("referer", "$baseUrl/sssearch")
-            .build()
+            val header = headersBuilder()
+                .add("referer", "$baseUrl/sssearch")
+                .build()
```
Comment (vetleledaal) [inline src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]:
```suggestion
            val headers = headersBuilder()
                .add("Referer", "$baseUrl/sssearch")
                .build()
```

File: src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt (hunk 1 above)
Comment (AlphaBoom) [reply src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]: pathSegments returns a List, and to implement this functionality, I'd either need to reassemble it into a String or directly compare the list's values at corresponding positions, which seems to make the implementation more complicate. Please let me know if there's a simpler way or an existing extension method to achieve this quickly.

Comment (vetleledaal) [reply src/zh/happymh/src/eu/kanade/tachiyomi/extension/zh/happymh/Happymh.kt]: Fair. Can you compare against `encodedPath` instead?
```suggestion
        if (response.request.url.encodedPath == "/apis/c/index") {
```

I have not tested it.

**Review by vetleledaal — APPROVED** [review]
