### PR TITLE
YugenMangas: Fix loading content

### LINKED ISSUE #7582: Yugen Mangas: New domain URL
### Source information

Yugen Mangás 1.4.42

### Source language

Portuguese Brazil

### Steps to reproduce

Extension does not load chapters, the message appears failed to bypass cloud flare. There is no cloudflare in the webview and the site works normally.
Already tried change the user agent, but didn't work.

Image

### Expected behavior

Load chapters.

### Actual behavior

Message appears Failed to bypass cloudflare.

### Mihon/Tachiyomi version

Yokai 1.9.7

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #7582
Closes #7612

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by choppeh** [comment]
PR #7612 can be closed

**Comment by vetleledaal** [comment]
> PR #7612 can be closed

You can actually put 'Closes #7612' in the PR body and it will be closed on merge, same as with issues.

File: src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangas.kt [hunk 1]
```diff
@@ -1,142 +1,198 @@
...
     override val name = "Yugen Mangás"
 
-    override val baseUrl = "https://yugenmangasbr.voblog.xyz"
+    override val baseUrl = "https://yugenmangasbr.readmis.com"
 
     override val lang = "pt-BR"
 
     override val supportsLatest = true
 
+    private val preferences by getPreferencesLazy()
```
Comment (AwkwardPeak7) [inline src/pt/yugenmangas/src/eu/kanade/tachiyomi/extension/pt/yugenmangas/YugenMangas.kt]:
```suggestion
    private val preferences by getPreferencesLazy {
        getString(PREF_KEY_RANDOM_UA, "off").let {
            if (it != "off" || getPrefCustomUA().isNullOrBlank()) {
                return@let
            }
            edit().putString(PREF_KEY_RANDOM_UA, "mobile").apply()
        }
    }
```
and remove the `init`

**Review by AwkwardPeak7 — COMMENTED** [review]
use `String.parseAs` and `Response.parseAs` from utils, instead of 
`json.parseToJsonElement` -> `str.parseAs<JsonObject>()`
`json.decodeFromString` -> `str.parseAs`
etc

**Review by AwkwardPeak7 — APPROVED** [review]
