### PR TITLE
Webtoons.com: use api to get chapters

### LINKED ISSUE #9322: Webtoon Extension is not displaying completed for the completed ones
### Source information

Webtoons 1.4.47

### Source language

English

### Steps to reproduce

After opening a webtoon to check its status it should show Completed/Ongoing in the status part.

### Expected behavior

After Opening a webtoon as usual it should show its status as Completed/Ongoing.

### Actual behavior

But for the completed ones we get the status as Unknown instead of "completed" being mentioned there.

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9329: Webtoons.com: `No chapters found` error
### Source information

Webtoons.com 1.4.47

### Source language

Multi (English)

### Steps to reproduce

1. Open Webtoons.com source
2. Tap on any series
3. Refresh series page (drag down to refresh) 

### Expected behavior

New or available chapter(s) should appear and be readable.

### Actual behavior

Toast Notification: "No chapters found" will appear, and no new/available chapter(s) will appear.

### Mihon/Tachiyomi version

Mihon 0.18.0

### Android version

Android 14

### Other details

Additional information: if I already have a Webtoons.com series with chapters already showing, I can click on them and pages will load, irrespective of download status or if it's in my library or not. However, if I refresh the series page, no new chapters will appear. Old chapters that are already showing will not disappear. 
I can still access WebView and read chapters there.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes #9329
closes #9322

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt [hunk 1]
```diff
@@ -231,24 +228,44 @@ open class Webtoons(
         throw UnsupportedOperationException()
     }
 
-    override fun chapterListRequest(manga: SManga) = GET(mobileUrl + manga.url, mobileHeaders)
+    override fun chapterListRequest(manga: SManga): Request {
+        val tooUrl = getMangaUrl(manga).toHttpUrl()
```
Comment (vetleledaal) [inline src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt]: What does `tooUrl` mean?

**Review by vetleledaal — DISMISSED** [review]

File: src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt (hunk 1 above)
Comment (AwkwardPeak7) [reply src/all/webtoons/src/eu/kanade/tachiyomi/extension/all/webtoons/Webtoons.kt]: typo for `toonUrl`
