### PR TITLE
MangaWork: add new multisrc + two sources that inherit

### LINKED ISSUE #12565: Capitoons - Nenhum resultado encontrado
### Source information

Capitoons 1.4.44

### Source language

Portuguese (Brazil)

### Steps to reproduce

Try to update a title or open the webview.

### Expected behavior

Works...

### Actual behavior

Image
Image
Image

### Mihon/Tachiyomi version

Komikku 1.13.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #14396: Pizzaria Scan: `HTTP 404` error
### Source information

Pizzaria Scan 1.4.47

### Source language

Portugues (Brasil)

### Steps to reproduce

ao abrir a extensao ja aparece o erro

### Expected behavior

carrregar as obras

### Actual behavior

error 404

### Mihon/Mihon fork version

Mihon 0.19.7

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes #14396 
closes #12565

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/pt/pizzariascan/src/eu/kanade/tachiyomi/extension/pt/pizzariascan/Pizzariascan.kt [hunk 1]
```diff
@@ -1,197 +1,66 @@
...
 
-class Pizzariascan : ParsedHttpSource() {
+class Pizzariascan :
+    MangaWork(
+        name = "PizzariaScan",
+        baseUrl = "https://pizzariacomics.com",
+        lang = "pt-BR",
+    ) {
 
     override val id: Long = 3359822911747375789
```
Comment (AwkwardPeak7) [inline src/pt/pizzariascan/src/eu/kanade/tachiyomi/extension/pt/pizzariascan/Pizzariascan.kt:14]: are old manga urls compatible? for both sources

**Review by AwkwardPeak7 — APPROVED** [review]
