### PR TITLE
NineManga(es): Fix pages not found again / Update NineManga(en) domain

### LINKED ISSUE #11998: NinemangaEs is not loading the chapters
### Source information

Ninemanga 1.4.24

### Source language

Spanish

### Steps to reproduce

Any manga when tray to read a chapter It doesn't load and closes automatically 

### Expected behavior

The chapter should load

### Actual behavior

The chapters load correctly in the WebView 

### Mihon/Tachiyomi version

Yõkai 1.9.7.3

### Android version

Android 14

### Other details

The error has been going on for about 2 days. 

Image
Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Closes #11998

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt [hunk 1]
```diff
@@ -65,6 +65,15 @@ class NineMangaEs : NineManga("NineMangaEs", "https://es.ninemanga.com", "es") {
     private val redirectRegex = Regex("""window\.location\.href\s*=\s*["'](.*?)["']""")
 
     override fun pageListParse(document: Document): List<Page> {
+        val serverUrl = document.selectFirst("section.section div.post-content-body > a")?.attr("href")
```
Comment (vetleledaal) [inline src/all/ninemanga/src/eu/kanade/tachiyomi/extension/all/ninemanga/NineMangaFactory.kt]:
```suggestion
        val serverUrl = document.selectFirst("section.section div.post-content-body > a")?.absUrl("href")
```

**Review by vetleledaal — APPROVED** [review]
