### PR TITLE
Fix ArgosComics

### LINKED ISSUE #10100: Argos Comic: `HTTP error 404`, `NullPointerException: null`, `No results found` error
### Source information

Argos Comic 1.4.50

### Source language

Portuguese

### Steps to reproduce

1- I open the app
2- I go to the browser
3- I click on Leitor de manga
4- If you already have a manga from this extension added, click on that manga

### Expected behavior

the extension's mangas appear and be able to normally access the mangas and their chapters.

### Actual behavior

When I try to access the mangas of this extension, it appears "no results found" or when I try to access only chapters of the mangas that I have already added of this extension, the error "HTTP error 404" appears

### Mihon/Tachiyomi version

TachiyomeSY 1.12.0

### Android version

android 14

### Other details

I think they changed the addressing of their mangas, because looking at the URL, it used to be something like: "https://argoscomic.com/manga/pico-marcial"
but now it's something like:
"https://argoscomic.com/d7ca82fb-f6d2-4678-b527-0d86400640c3/pico-marcial"

Until this morning I was reading normally, it only changed tonight.

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11909: Argos Comics Error
### Source information

Argos Comics 1.4.51

### Source language

Português

### Steps to reproduce

Image

### Expected behavior

The manga from the website was supposed to appear. 

### Actual behavior

It says that nothing was found and does not indicate the error that caused this.

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #11909
Closes #10100

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComicsDto.kt [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+            SChapter.create().apply {
+                name = it.number.toString()
+                chapter_number = it.number
+                date_upload = DATE_FORMAT.tryParse(it.createdAt)
+                url = "$pathSegment/capitulo/$chapter_number"
+            }
+        }
+    }
+    companion object {
+        private val DATE_FORMAT = SimpleDateFormat("yyyy-MM-dd")
```
Comment (vetleledaal) [inline src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComicsDto.kt]:
```suggestion
        private val DATE_FORMAT = SimpleDateFormat("yyyy-MM-dd", Locale.ROOT)
```

File: src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComics.kt [hunk 2]
```diff
@@ -1,63 +1,250 @@
...
+        val pathSegment = response.request.url.toString().substringAfter(baseUrl)
+        return getJsonBody(response).parseAs<VolumeChapterDto>().toChapterList(pathSegment)
+    }
+
+    // ======================== Pages =============================
+
+    override fun getChapterUrl(chapter: SChapter): String = "$baseUrl${chapter.url}"
+
+    override fun pageListRequest(chapter: SChapter): Request {
+        val segments = chapter.url.split("/").filter(String::isNotBlank)
```
Comment (vetleledaal) [inline src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComics.kt]: If you're working on segments already, you should prefer using `HttpUrl` for this, to avoid matching stuff in the query arguments / fragment. Not tested:

```suggestion
        val segments = "$baseUrl${chapter.url}".toHttpUrl()!!.pathSegments
```

File: src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComics.kt [hunk 3]
```diff
@@ -1,63 +1,250 @@
...
+         * The purpose is to find the beginning of the valid JSON data, ignoring any
+         * preceding code or text. The pattern is defined by the expected first key-field
+         * of the JSON for each response type:
+         *
+         * - 'id': Starts the list of latest projects or search results (e.g., [{"id"...).
+         * - 'projects', 'title', 'groupName', 'pages': Starts other responses (e.g., {"projects"...).
+         */
+        private val MANGA_DATA_REGEX = buildList {
+            add("""\[\{"id".+""".toRegex())
+            add("""\{"(?:${listOf("projects", "title", "groupName", "pages").joinToString("|")})".+""".toRegex())
```
Comment (vetleledaal) [inline src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComics.kt]: It's easier to read if you don't mix DSLs, IMO.
```suggestion
            add("""\{"(?:projects|title|groupName|pages)".+""".toRegex())
```

File: src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComics.kt [hunk 4]
```diff
@@ -1,63 +1,250 @@
...
+         * The token is a unique identifier (a string) found inside the 'createServerReference'
+         * function call within the page's JavaScript source, immediately preceding the
+         * corresponding backend function name (e.g., 'getAllWithoutFilters' for popular).
+         */
+        private val NEXT_ACTION_REGEX = buildList {
+            add("""(?:createServerReference\)\(")([^"]+)"(?:,.+getAllWithoutFilters)""".toRegex()) // popular token
+            add("""(?:"[^\.]+.createServerReference\)\(")([^"]+)"(?:,.+getLastUpdates)""".toRegex()) // latest token
+            add("""(?:(?:,.=.{2}\d+.){4}[^\.]+.createServerReference\)\(")([^"]+)"(?:,.+search)""".toRegex()) // search token
+            add("""(?:getAllChapters"[^\.]+.createServerReference\)\(")([^"]+)"(?:,.+getOne)""".toRegex()) // details token
+            add("""(?:"[^\.]+.createServerReference\)\(")([^"]+)"(?:,.+getPages)""".toRegex()) // pages token
```
Comment (vetleledaal) [inline src/pt/argoscomics/src/eu/kanade/tachiyomi/extension/pt/argoscomics/ArgosComics.kt]: Why put `"` in a capture group? You're not using it as a backreference.

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
