### PR TITLE
FRScan: Fix pages loading

### LINKED ISSUE #1714: FR-Scan: Some manga report 0 pages
### Source information

FR-Scan

### Source language

French

### Steps to reproduce

1. Try `Mashle` : it doesn't work
2. Try `One Piece` : it works

### Expected behavior

All manga should work

### Actual behavior

Some manga works, other don't 

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #1714

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/frdashscan/src/eu/kanade/tachiyomi/extension/fr/frdashscan/FRScan.kt [hunk 1]
```diff
@@ -16,4 +20,23 @@ class FRScan : Madara("FR-Scan", "https://fr-scan.com", "fr", dateFormat = Simpl
...
+        return chapterPreloaded
+            .parseAs<List<String>>()
+            .mapIndexed { index, imageUrl -> Page(index, imageUrl = imageUrl) }
+    }
+
+    private inline fun <reified T> Element.parseAs(): T {
+        return json.decodeFromString(
+            CHAPTER_PAGES_REGEX.find(data())?.groups?.get("pages")!!.value,
+        )
+    }
```
Comment (AwkwardPeak7) [inline src/fr/frdashscan/src/eu/kanade/tachiyomi/extension/fr/frdashscan/FRScan.kt]: no need to make a seperate function.
also:
```
CHAPTER_PAGES_REGEX.find(data())!!.groups.get("pages").value
```

File: src/fr/frdashscan/src/eu/kanade/tachiyomi/extension/fr/frdashscan/FRScan.kt [hunk 2]
```diff
@@ -16,4 +20,23 @@ class FRScan : Madara("FR-Scan", "https://fr-scan.com", "fr", dateFormat = Simpl
...
 
     override val chapterUrlSuffix = ""
+
+    override fun pageListParse(document: Document): List<Page> {
+        val chapterPreloaded = document.selectFirst("#chapter_preloaded_images")
+            ?: return super.pageListParse(document)
+
+        return chapterPreloaded
+            .parseAs<List<String>>()
+            .mapIndexed { index, imageUrl -> Page(index, imageUrl = imageUrl) }
```
Comment (AwkwardPeak7) [inline src/fr/frdashscan/src/eu/kanade/tachiyomi/extension/fr/frdashscan/FRScan.kt]: add page.url too

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
