### PR TITLE
OlympusScanlation: Use site bookmarks to update manga url

### LINKED ISSUE #1819: Olympus scanlation bug need to migrate every new chapter
### Source information

Olympus scanlation 1.4.7

### Source language

Spanish

### Steps to reproduce

When the manga/manwha is added works, but this manga/manwha gets a new chapter you get an error and when you migrate it it apears with the same name in the same source.
Screenshot_2024-03-11-12-07-01-368_eu kanade tachiyomi
Screenshot_2024-03-11-12-07-15-787_eu kanade tachiyomi

### Expected behavior

Work

### Actual behavior

Need to migrate every time you have a new chapter

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #8413: Improvement for Library Titles
### Source name

es.olumpusscanlation

### Source language

Spanish

### Describe your suggested feature

Some of the sources I use to read manga or manhwa do something very common: they occasionally RE-UPLOAD some titles so they don't get reported for copyright infringement (such as changing the name or description, etc.). When this happens, I have to remove the old title (like a manga I'm reading) from my library, add the new title of the same manga, and mark all the chapters as read again. Normally, nothing too serious, since it doesn't happen very often, at least not with all of them. But recently, one of the sites I use most for reading manhwa (Olympus Scanlation) is re-uploading some of its titles EVERY DAY. Literally every day, I have to remove half of the manhwa I read from my library, add them back, and mark the chapters as read. And every day after 12, the titles are re-uploaded, to the point where the library becomes completely useless.

I know this isn't a problem with the app or the fonts, but rather with the pages themselves. But I thought it was worth requesting that keiyoushi implement a solution, something like automatically adding it to your library when a title with the same name is re-uploaded that's already in the library. I don't know much about this; I'm just a regular user, and since I love this app so much, I appreciated being able to contribute in this way.
Thank you very much!

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Users must log in to WebView and add their series to their site bookmarks.

Closes #8413 
Closes #1819 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AwkwardPeak7** [comment]
wouldn't it be better to use site's search to get new slugs? match based on internal id. 
Instead of relying on users adding series to site bookmarks

**Comment by bapeey** [comment]
AFAIK, the site also changes the names of the series sometimes, and its search fails with certain characters (#8039)

**Comment by AwkwardPeak7** [comment]
you could normalize the search query and if search still fails, tell users to migrate.

apart from that, imo should only save internal id for SManga.url, and keep slug map in preferences, update the map while browsing or during updates ( (if current slug fails) by search (or bookmark) method

**Comment by bapeey** [comment]
changed to only save the ID and use the slug map. I don't want to use the search method because it fails too often. Keeping it in draft for testing

File: src/es/olympusscanlation/src/eu/kanade/tachiyomi/extension/es/olympusscanlation/OlympusScanlation.kt [hunk 1]
```diff
@@ -101,10 +122,15 @@ class OlympusScanlation : HttpSource(), ConfigurableSource {
...
-        val hasNextPage = result.current_page < result.last_page
-        return MangasPage(mangaList, hasNextPage)
+        val result = response.parseAs<NewChaptersDto>()
+        val mangaList = result.data.filter { it.type == "comic" }
+            .map {
+                preferences.slugMap = preferences.slugMap.toMutableMap()
+                    .also { map -> map[it.id] = it.slug }
+
+                it.toSManga()
+            }
```
Comment (AwkwardPeak7) [inline src/es/olympusscanlation/src/eu/kanade/tachiyomi/extension/es/olympusscanlation/OlympusScanlation.kt]:
```suggestion
        val slugMap = preferences.slugMap.toMutableMap()
        val mangaList = result.data.filter { it.type == "comic" }
            .map {
                slugMap[it.id] = it.slug

                it.toSManga()
            }
        preferences.slugMap = slugMap
```

File: utils/src/keiyoushi/utils/Json.kt [hunk 2]
```diff
@@ -19,3 +20,9 @@ inline fun <reified T> String.parseAs(json: Json = jsonInstance): T =
  */
 inline fun <reified T> Response.parseAs(json: Json = jsonInstance): T =
     json.decodeFromStream(body.byteStream())
+
+/**
+ * Serializes the object to a JSON String.
+ */
+inline fun <reified T> T.toJson(json: Json = jsonInstance): String =
```
Comment (AwkwardPeak7) [inline utils/src/keiyoushi/utils/Json.kt]:
```suggestion
inline fun <reified T> T.toJsonString(json: Json = jsonInstance): String =
```
make a separate pr for this please

**Review by AwkwardPeak7 — APPROVED** [review]
