### PR TITLE
CreepyScans - add query search

### LINKED ISSUE #1034: CreepyScans search is broken
### Source information

CreepyScans 1.4.33

### Source language

English

### Steps to reproduce

1. Select source at source list page
2. Try to search for anything

### Expected behavior

You're seeing search results

### Actual behavior

You're seeing an error "search is not available"

### Mihon/Tachiyomi version

J2K 1.7.4

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Closes #1034 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: multisrc/overrides/madara/creepyscans/src/CreepyScans.kt [hunk 1]
```diff
@@ -47,9 +56,37 @@ class CreepyScans : Madara(
...
+        filters: FilterList,
+    ): Observable<MangasPage> {
+        return if (query.isNotBlank()) {
+            val form = FormBody.Builder()
+                .add("action", "wp-manga-search-manga")
+                .add("title", query)
+                .build()
+            client.newCall(POST("$baseUrl/wp-admin/admin-ajax.php", headers, form)).asObservableSuccess().map { res ->
+                json.parseToJsonElement(res.body.string()).jsonObject.let { obj ->
+                    if (obj["success"]!!.jsonPrimitive.content == "false") {
```
Comment (beer-psi) [inline multisrc/overrides/madara/creepyscans/src/CreepyScans.kt]:
```suggestion
                    if (obj["success"]!!.jsonPrimitive.boolean == false) {
```
https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/boolean.html

**Review by beer-psi — CHANGES_REQUESTED** [review]

File: multisrc/overrides/madara/creepyscans/src/CreepyScans.kt (hunk 1 above)
Comment (SnakeDoc83) [reply multisrc/overrides/madara/creepyscans/src/CreepyScans.kt]: Right, slipped my mind.

**Review by beer-psi — APPROVED** [review]
