### PR TITLE
Fix Philiascans

### LINKED ISSUE #8943: Philia Scans Theme Changed
### Source information

Philia Scans 1.4.43

### Source language

English 

### Steps to reproduce

Go to browse/sources
Select Philia Scans

### Expected behavior

Should show Manga/Manhwa lists

### Actual behavior

Not showing Manga/Manhwa lists

### Mihon/Tachiyomi version

Mihon 0.18.0 / Yōkai v1.9.7.2

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by manti-X**
Closes #8943 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 1]
```diff
@@ -1,44 +1,235 @@
...
 
-    override val mangaDetailsSelectorTitle: String = "h1.post-title"
-    override val mangaDetailsSelectorStatus: String = "div.summary-heading:contains(Status) + div"
+    override val client: OkHttpClient = network.cloudflareClient
+
+    override fun fetchPopularManga(page: Int): Observable<MangasPage> {
+        return client.newCall(popularMangaRequest(page))
+            .asObservableSuccess()
+            .map { response -> popularMangaParse(response) }
+    }
```
Comment (stevenyomi) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: Identical to the base class. Remove it.

Same for `fetch*` below.

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 2]
```diff
@@ -1,44 +1,235 @@
...
+        Genre("Isekai", "31"), Genre("Josei", "173"),
+        Genre("Josei-None", "302"), Genre("Josei-Seinen", "174"),
+        Genre("Magic", "87"), Genre("Martial Arts", "61"), Genre("Medical", "32"),
+        Genre("Monsters", "99"), Genre("Music", "303"), Genre("Mystery", "35"),
+        Genre("Psychological", "62"), Genre("Regression", "122"), Genre("Romance", "33"),
+        Genre("School Life", "47"), Genre("Sci-Fi", "36"), Genre("Seinen", "48"),
+        Genre("Shoujo", "69"), Genre("Shounen", "55"), Genre("Slice of Life", "37"),
+        Genre("Sports", "45"), Genre("Supernatural", "49"), Genre("Survival", "121"),
+        Genre("Tragedy", "41"), Genre("Villainess", "253"), Genre("War", "120"),
+        Genre("Yuri", "195"),
```
Comment (Riztard) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: better make it one line each

**Review by stevenyomi — APPROVED** [review]
