### PR TITLE
SpectralScan: Fix pages

### LINKED ISSUE #9511: Spectral Scan (PT-Br Source) Error: `Illegal Argument Exception`
### Source information

Spectral Scan 1.4.47

### Source language

Portuguese Brazilian 

### Steps to reproduce

Don't show content.

### Expected behavior

Show content.

### Actual behavior

Don't show content.

Image

### Mihon/Tachiyomi version

komikku Beta r10138

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #9511

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/SpectralScan.kt [hunk 1]
```diff
@@ -32,28 +28,11 @@ class SpectralScan : ParsedHttpSource() {
...
-
-            if (url.fragment.isNullOrBlank().not() && url.fragment!!.contains("page")) {
-                val dto = response.parseAs<ImageSrc>()
-
-                if (dto.isBase64().not()) {
-                    response.close()
-                    return@addInterceptor chain.proceed(GET(dto.url, headers))
+            chain.proceed(chain.request()).also {
+                if (it.request.url.toString().contains("login")) {
+                    throw IOException("Faça o login na WebView para acessar o contéudo")
```
Comment (stevenyomi) [inline src/pt/spectralscan/src/eu/kanade/tachiyomi/extension/pt/spectralscan/SpectralScan.kt:34]:
```suggestion
                    it.close()
                    throw IOException("Faça o login na WebView para acessar o contéudo")
```

Close the response.

**Review by stevenyomi — APPROVED** [review]
