### PR TITLE
Siimanga: Migrate theme

### LINKED ISSUE #3851: Error 400 siikomik
### Source information

Siikomik 1.4.37

### Source language

Indonesian

### Steps to reproduce

1. Open ext
2. Http 400 error: check website in webview
3. Open webview Functioning normally
1. Open comic and chapter
2. Http error 404

### Expected behavior

Functions normally for both extensions and comics being read

### Actual behavior

Http 400: check website in webview
Screenshot_2024-07-03-16-24-10-660_eu kanade tachiyomi j2k

Http error 404
Screenshot_2024-07-03-16-24-42-238_eu kanade tachiyomi j2k

### Mihon/Tachiyomi version

J2k 1.7.4

### Android version

13

### Other details

I think the error was caused by hosting migration and changing the website theme

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #3851

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/siimanga/src/eu/kanade/tachiyomi/extension/id/siimanga/Siikomik.kt [hunk 1]
```diff
@@ -1,25 +1,20 @@
...
-import java.util.Locale
 
-class Siikomik : Madara(
+class Siikomik : MangaThemesia(
     "Siikomik",
     "https://siikomik.com",
     "id",
-    dateFormat = SimpleDateFormat("dd MMMM yyyy", Locale.US),
 ) {
     override val id = 5693774260946188681
```
Comment (AwkwardPeak7) [inline src/id/siimanga/src/eu/kanade/tachiyomi/extension/id/siimanga/Siikomik.kt]: remove id override to actually generate new one

**Review by AwkwardPeak7 — APPROVED** [review]
