### PR TITLE
Manga Livre: Fix placeholder images, chapter list endpoint, page list parsing

### LINKED ISSUE #11684: Manga Livre: `HTTP 403` / `No pages found` error
### Source information

Manga Livre 1.4.47

### Source language

Brazilian Portuguese

### Steps to reproduce

1. Open the extension
2. Open the webview
3. Pass Cloudflare
4. Return to the extension
5. Try reloading again

### Expected behavior

Entries are shown on the home/recent tab

### Actual behavior

It returns a `HTTP 403` error even though everything is working on webview and even entries on the library or search works perfectly fine

Image

Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 13

### Other details

Recently an similar issue on the entries was fixed with pr #11651 but now this new issue was introduced due to possible new changes made by the source

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11981: Cant search or see the feed in Manga Livre
### Source information

Manga Livre 1.4.47

### Source language

Portuguese PT-BR

### Steps to reproduce

1. Check Feed
2. Use WebView and can access normally the website

Image
Image

### Expected behavior

This show the Feed Mangas or search, etc.

### Actual behavior

Not see any mangas and result in a cloudflare error

### Mihon/Tachiyomi version

App ID: eu.kanade.tachiyomi.sy App version: 1.12.0 (standard, 6db1637, 73, 2025-05-11T19:02:06Z) Preview build: 0 Android version: 16 (SDK 36; build BP2A.250605.031.A3.S916BXXS8EYJ3) Device brand: samsung Device manufacturer: samsung Device name: dm2q (dm2qxxx) Device model: SM-S916B WebView: Android System WebView 142.0.7444.171 Current time: 2025-12-04T19:40:44.946-03:00

### Android version

Android  16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11990: Manga Livre - não carrega os capítulos
### Source information

Manga Livre 1.4.47

### Source language

Português (Brasil)

### Steps to reproduce

O site quebrou a extensão, não está aparecendo as imagens das capítulos

Image

### Expected behavior

Funcionar os capítulos normalmente

### Actual behavior

Não está aparecendo os capítulos tá aparecendo só 2 imagens  escrito  "OLA"

### Mihon/Tachiyomi version

Mihon 1.19.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by amebacelestial**
Checklist:

Fixes #11684
Fixes #11981
Fixes #11990

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Implemented custom chapter parser with AJAX fallback
- [x] Implemented custom page parser via JavaScript regex

### CODE REVIEW

**Comment by vetleledaal** [comment]
Does this PR fix any of the open issues related to Manga Livre?
#11684
#11981
#11990

Please add them to the PR description as appropriate. Use the [recognized keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests).

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 1]
```diff
@@ -1,17 +1,118 @@
...
 
-    override val chapterUrlSuffix: String = ""
-    override val useNewChapterEndpoint = true
     override val id: Long = 2834885536325274328
+    override val useLoadMoreRequest = LoadMoreStrategy.Always
+    override val baseUrl by lazy { getPrefBaseUrl() }
+
+    private val preferences: SharedPreferences by lazy {
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
+    }
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Use `getPreferences` from `keiyoushi.utils`.

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 2]
```diff
@@ -1,17 +1,118 @@
...
-    "https://mangalivre.tv",
-    "pt-BR",
-    SimpleDateFormat("MMMM dd, yyyy", Locale("pt")),
-) {
+class MangaLivre :
+    Madara(
+        "Manga Livre",
+        "https://mangalivre.tv",
+        "pt-BR",
+        SimpleDateFormat("dd.MM.yyyy", Locale("pt")),
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Not using any locale specific patterns,
```suggestion
        SimpleDateFormat("dd.MM.yyyy", Locale.ROOT),
```

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 3]
```diff
@@ -1,17 +1,118 @@
...
+        .rateLimit(2)
+        .build()
+
+    override fun headersBuilder() = super.headersBuilder()
+        .set("Origin", baseUrl)
+        .set("X-Requested-With", "XMLHttpRequest")
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val html = response.body.string()
+        var document = Jsoup.parse(html)
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Use `response.asJsoup()` so the correct relative URLs can be resolved. Requires import, so don't blindly accept the suggestion.
```suggestion
        var document = response.asJsoup()
```

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 4]
```diff
@@ -1,17 +1,118 @@
...
+
+        if (document.selectFirst("li.wp-manga-chapter") == null) {
+            val mangaUrl = response.request.url.toString().trimEnd('/')
+            val headers = headersBuilder().set("Referer", mangaUrl).build()
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: You shouldn't need to send the full Referer header. In browsers it is possible to set it up to just send the domain itself.
```suggestion
            val headers = headersBuilder().set("Referer", "$baseUrl/").build()
```

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 5]
```diff
@@ -1,17 +1,118 @@
...
+            val request = POST("$mangaUrl/ajax/chapters/", headers, FormBody.Builder().build())
+
+            client.newCall(request).execute().use { xhr ->
+                if (!xhr.isSuccessful) {
+                    throw IOException("Failed to fetch chapters via AJAX: ${xhr.code}. Open in WebView.")
+                }
+                document = Jsoup.parse(xhr.body.string())
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Use `xhr.asJsoup()` here too.
```suggestion
                document = xhr.asJsoup()
```

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 6]
```diff
@@ -1,17 +1,118 @@
...
+
+        if (document.selectFirst("li.wp-manga-chapter") == null) {
+            val mangaUrl = response.request.url.toString().trimEnd('/')
+            val headers = headersBuilder().set("Referer", mangaUrl).build()
+            val request = POST("$mangaUrl/ajax/chapters/", headers, FormBody.Builder().build())
+
+            client.newCall(request).execute().use { xhr ->
+                if (!xhr.isSuccessful) {
+                    throw IOException("Failed to fetch chapters via AJAX: ${xhr.code}. Open in WebView.")
+                }
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Ideally you wouldn't do any networking in `chapterListParse`. Would it be practical to move network requests to `fetchChapterList`?

Make sure you're not replicating something Madara is handling by default (or hidden behind toggles).

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 7]
```diff
@@ -1,17 +1,118 @@
...
+        val jsonString = IMAGES_REGEX.find(script)?.groupValues?.get(1)
+            ?: throw IOException("Image list not found in script.")
+
+        val jsonArray = JSONArray(jsonString)
+
+        return buildList(jsonArray.length()) {
+            for (i in 0 until jsonArray.length()) {
+                val url = jsonArray.getString(i).trim()
+                if (url.startsWith("http")) {
+                    add(Page(size, "", url))
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]:
```suggestion
                    add(Page(size, imageUrl = url))
```

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 8]
```diff
@@ -1,17 +1,118 @@
...
+                document = Jsoup.parse(xhr.body.string())
+            }
+        }
+
+        val elements = document.select("li.wp-manga-chapter").ifEmpty {
+            document.select("li.chapter-li")
+        }
+
+        if (elements.isEmpty()) {
+            throw IOException("No chapters found. Open in WebView to solve Cloudflare/Turnstile.")
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: If Cloudflare's Turnstile can occur on any request I think it would be better to have some catch-all logic for it in an interceptor. Only if necessary. See the history in #11775, where the Cloudflare specific things were replaced by some cookies.

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 9]
```diff
@@ -1,17 +1,118 @@
...
+    }
+
+    override fun pageListParse(document: Document): List<Page> {
+        val script = document.selectFirst("script:containsData(var imgs)")?.data()
+            ?: throw IOException("Images not found. Open in WebView to solve Cloudflare/Turnstile.")
+
+        val jsonString = IMAGES_REGEX.find(script)?.groupValues?.get(1)
+            ?: throw IOException("Image list not found in script.")
+
+        val jsonArray = JSONArray(jsonString)
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Try using `String.parseAs` from `keiyoushi.utils`. Like:
```kt
return jsonString.parseAs<List<String>>()
    .map(String::trim)
    .filter { it.startsWith("http") }
    .mapIndexed { idx, url ->
        Page(idx, imageUrl = url)
    }
```

File: src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt [hunk 10]
```diff
@@ -1,17 +1,118 @@
...
+
+        return buildList(jsonArray.length()) {
+            for (i in 0 until jsonArray.length()) {
+                val url = jsonArray.getString(i).trim()
+                if (url.startsWith("http")) {
+                    add(Page(size, "", url))
+                }
+            }
+        }.ifEmpty { throw IOException("Image list is empty.") }
```
Comment (vetleledaal) [inline src/pt/mangalivre/src/eu/kanade/tachiyomi/extension/pt/mangalivre/MangaLivre.kt]: Not needed. The app will notify the user if there are no pages.
```suggestion
        }
```

**Review by vetleledaal — APPROVED** [review]
