### PR TITLE
ReadMangas: Theme change

### LINKED ISSUE #6193: Read Mangas (PT-BR SOURCE) New Theme!
### Source information

Read Mangas 1.4.30

### Source language

Portuguese Brazilian 

### Steps to reproduce

The website has been redesigned.

### Expected behavior

Access the works.

### Actual behavior

Does not show the works.

### Mihon/Tachiyomi version

App version: 0.17.0-7001 (standard, 9df21583d, 8, 2024-11-09T21:19:01Z) Android version: 12 (SDK 31; build SKQ1.211019.001 test-keys) Device brand: Redmi Device manufacturer: Xiaomi Device name: joyeuse (joyeuse_eea) Device model: Redmi Note 9 Pro WebView: Android System WebView 132.0.6834.5

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #6511: Read Mangas
### Source information

Read Mangas 1.4.30

### Source language

Português (Brasil)

### Steps to reproduce

Não está aparecendo as obras na extensão, mas no Webview está normal 

Extensão 
Screenshot_20241206-231759

Webview 
Screenshot_20241206-231808

### Expected behavior

Aparecer as obras na extensão

### Actual behavior

Screenshot_20241206-231759

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #6193
Closes #6511

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangasDto.kt [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+    val currentPage: Int,
+    val chapters: List<ChapterDto>,
+    val perPage: Int,
+    val totalPages: Int,
+) {
+    fun hasNext() = currentPage < totalPages
+}
+
+@Serializable
+data class ChapterDto(
```
Comment (vetleledaal) [inline src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangasDto.kt]: Don't use `data class` unless required, use just `class` instead.

**Review by AwkwardPeak7 — APPROVED** [review]
