### PR TITLE
Astralscasns: fix broken chapter images

### LINKED ISSUE #14622: Astral Scans (ID) No Chapters Found
### Source information

Astral Scans (ID) 1.4.31

### Source language

Indonesia

### Steps to reproduce

1. Open random entry/Manhwa
2. No chapter shown
3. Error written: No chapters shown
4. Click webview from the manhwa
Webview shown chapter available in website

### Expected behavior

Chapter should shown

### Actual behavior

No chapter shown, meanwhile in webview the chapter available or shown

Image

### Mihon/Mihon fork version

Mihon 0.19.7

### Android version

Android 16

### Other details

This issue was solved under
https://github.com/keiyoushi/extensions-source/issues/14376

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14622

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by AaronDeimos** [comment]
Version didn't bump because you are working on an old branch that doesn't have the commit from #14548.
So you bumped to 1 when you needed 2.
How did you forget your own commit? They even have the same typo in both PR titles lol.

**Comment by darwin-256** [comment]
> Version didn't bump because you are working on an old branch that doesn't have the commit from #14548. So you bumped to 1 when you needed 2. How did you forget your own commit? They even have the same typo in both PR titles lol.

Sorry lol didn't pay attention

File: src/id/astralscans/src/eu/kanade/tachiyomi/extension/id/astralscans/AstralScans.kt [hunk 1]
```diff
@@ -8,12 +9,15 @@ class AstralScans : MangaThemesia("Astral Scans", "https://astralscans.top", "id
...
-        element.selectFirst(".nomor-bab")?.text()?.takeIf { it.isNotBlank() }?.let { name = it }
-        if (date_upload == 0L) {
-            date_upload = element.selectFirst(".tanggal-bab")?.text().parseChapterDate()
-        }
+    override fun chapterFromElement(element: Element): SChapter = SChapter.create().apply {
+        // Chapter URLs are Base64-encoded in data-u instead of plain <a href> links
+        val dataU = element.selectFirst(".js-link")?.attr("data-u") ?: ""
+        val decoded = if (dataU.isNotEmpty()) String(Base64.decode(dataU, Base64.DEFAULT)) else ""
+        setUrlWithoutDomain(decoded)
+        name = element.selectFirst(".ch-title")?.text() ?: ""
```
Comment (vetleledaal) [inline src/id/astralscans/src/eu/kanade/tachiyomi/extension/id/astralscans/AstralScans.kt]: Name is not optional.
```suggestion
        name = element.selectFirst(".ch-title")!!.text()
```

**Review by vetleledaal — APPROVED** [review]
