### PR TITLE
KomikCast: Fix duplicate images

### LINKED ISSUE #3421: Komik cast show double image
### Source information

Komik cast 1.4.56

### Source language

Indonesian 

### Steps to reproduce

1. open a extension
2. Search some manga like "My Exclusive Tower Guide"
3. Read it and show a double image

### Expected behavior

It will not show a duplicate image

### Actual behavior

Show a duplicate image

### Mihon/Tachiyomi version

Tachiyomij2k v 1.7.4 and tachiyomiSY v 1.10.5

### Android version

Android 12

### Other details

On the web it doesn't display double images but on tahciyomij2k and tachiyomisy it displays double images, I have tried other sources like pojok manga and it is working fine 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by DOTzX**
Close #3421

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt [hunk 1]
```diff
@@ -141,23 +138,8 @@ class KomikCast : MangaThemesia("Komik Cast", "https://komikcast.lol", "id", "/d
...
-            val imageList = json.parseToJsonElement(imageListJson).jsonObject
-
-            var imageServer = "cdn"
-            if (!imageList.containsKey(imageServer)) imageServer = imageList.keys.first()
-            val imageElement = imageList[imageServer]!!.jsonArray.joinToString("")
-            doc = Jsoup.parse(imageElement)
-            cssQuery = "img.size-full"
-        }
-
-        return doc.select(cssQuery)
```
Comment (AwkwardPeak7) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt:160]: is this not needed anymore?

Comment (DOTzX) [reply src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt:160]: Yes, the source change it several years ago. Only lasts a few weeks.

The removed code was implemented in mid-June 2022.

**Review by AwkwardPeak7 — APPROVED** [review]
