### PR TITLE
Ikiru: rewrite for new site

### LINKED ISSUE #9309: Ikiru website redesign and domain change
### Source information

Ikiru 1.4.37

New URL: https://01.ikiru.wtf/

### Source language

Indonesia 

### Steps to reproduce

1. Open the source 
2. The list doesn't show up

### Expected behavior

1. Open the source 
2. Show the list of manga/manhwa/manhua in the latest and popular.

Image

### Actual behavior

No results found 

Image

### Mihon/Tachiyomi version

TachiyomiSY 1.12.0

### Android version

Android 14

### Other details

After they changed the website structure / template the source couldn't be able to detect a manga.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Riztard**
Closes #9309

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 1]
```diff
@@ -1,42 +1,241 @@
...
 
+    override val name = "Ikiru"
+    private val defaultBaseUrl: String = "https://01.ikiru.wtf"
+    override val lang = "id"
+    override val supportsLatest = true
+
+    override val baseUrl: String get() = when {
+        isCi -> defaultBaseUrl
+        else -> preferences.prefBaseUrl
+    }
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: always return `preferences.prefBaseUrl`
```suggestion
    override val baseUrl: String get() = preferences.prefBaseUrl
```

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 2]
```diff
@@ -1,42 +1,241 @@
...
+import okhttp3.RequestBody
 import org.jsoup.nodes.Document
+import org.jsoup.nodes.Element
+import rx.Observable
+import java.text.SimpleDateFormat
+import java.util.Locale
 
-class Ikiru : MangaThemesia("Ikiru", "https://id.ikiru.wtf", "id") {
-
+class Ikiru() : ParsedHttpSource(), ConfigurableSource {
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]:
```suggestion
class Ikiru: ParsedHttpSource(), ConfigurableSource {
```
empty constructor

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 3]
```diff
@@ -1,42 +1,241 @@
...
+            try {
+                val response = client.newCall(
+                    GET("$baseUrl/ajax-call?type=search_form&action=get_nonce", headers),
+                ).execute()
+                val document = response.asJsoup()
+                searchNonce = document.select("input[name=search_nonce]").attr("value")
+            } catch (e: Exception) {
+                Log.e(name, "Error fetching nonce: ", e)
+            }
+        }
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]:
```suggestion
        if (searchNonce.isNullOrEmpty()) {
            val document = client.newCall(
                GET("$baseUrl/ajax-call?type=search_form&action=get_nonce", headers),
            ).execute().asJsoup()
            searchNonce = document.selectFirst("input[name=search_nonce]")!!.attr("value")
        }
```
the extension should fail when nonce isn't found, since the api call will not work without it. so don't wrap in try catch. also fail if it isn't found

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 4]
```diff
@@ -1,42 +1,241 @@
...
+
+        val requestBody: RequestBody = MultipartBody.Builder()
+            .setType(MultipartBody.FORM)
+            .addFormDataPart("query", query)
+            .addFormDataPart("page", "$page")
+            .addFormDataPart("genre", query)
+            .addFormDataPart("nonce", searchNonce ?: "")
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]:
```suggestion
            .addFormDataPart("nonce", searchNonce!!)
```

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 5]
```diff
@@ -1,42 +1,241 @@
...
+            .build()
+
+        val requestHeaders: Headers = Headers.Builder()
+            .add("Content-Type", "multipart/form-data")
+            .build()
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: okhttp will set correct content-type header based on body, so this isn't needed
```suggestion
```

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 6]
```diff
@@ -1,42 +1,241 @@
...
+
+        return POST("$baseUrl/ajax-call?action=advanced_search", requestHeaders, requestBody)
+    }
+
+    override fun searchMangaSelector() = "div.overflow-hidden:has(a.font-medium)"
+
+    override fun searchMangaFromElement(element: Element) = SManga.create().apply {
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt:85]: use `selectFirst` with appropriate `!!` and `?` usage

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 7]
```diff
@@ -1,42 +1,241 @@
...
+    override fun searchMangaNextPageSelector() = "div button:has(svg)"
+
+    // Manga Details
+    private fun Element.getMangaId() = selectFirst("#gallery-list")?.attr("hx-get")
+        ?.substringAfter("manga_id=")?.substringBefore("&")
+
+    override fun mangaDetailsParse(document: Document): SManga {
+        document.select("article > section").let { element ->
+            return SManga.create().apply {
+                thumbnail_url = element.select(".contents img").attr("abs:src")
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: same here, use `selectFirst`

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 8]
```diff
@@ -1,42 +1,241 @@
...
+                title = element.select("h1.font-bold").text()
+                // TODO: prevent status value from browse change back to default
+
+                val altNames = element.select("h1 ~ .line-clamp-1").text()
+                val synopsis = element.select("#tabpanel-description div[data-show='false']").text()
+                val mangaId = "\n\nID: ${document.getMangaId()}" // for fetching chapter list
+                description = when (altNames) {
+                    null -> synopsis + mangaId
+                    else -> "$synopsis\n\nAlternative Title: $altNames$mangaId"
                 }
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]:
```suggestion
                description = buildString {
                    append(synopsis)
                    if (altNames) { // use `altNames != null` when using `selectFirst`
                        append("\n\nAlternative Title: ", altNames)
                    }
                    document.getMangaId()?.also {
                        append("\n\nID: ", it)
                    }
                }
```

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 9]
```diff
@@ -1,42 +1,241 @@
...
+            ?: client.newCall(mangaDetailsRequest(manga)).execute().asJsoup().getMangaId()
+            ?: throw Exception("Could not find manga ID")
+
+        val chapterListUrl = "$baseUrl/ajax-call".toHttpUrl().newBuilder()
+            .addQueryParameter("manga_id", mangaId)
+            .addQueryParameter("page", "") // keep empty for loading hidden chapter
+            .addQueryParameter("action", "chapter_list")
+            .build()
+
+        val response = client.newCall(GET(chapterListUrl.toString(), headers)).execute()
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]:
```suggestion
        val response = client.newCall(GET(chapterListUrl, headers)).execute()
```

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 10]
```diff
@@ -1,42 +1,241 @@
...
+
+        response.asJsoup().select("#chapter-list .cursor-pointer a").asReversed().map { element ->
+            SChapter.create().apply {
+                url = element.attr("href").substringAfter(baseUrl)
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: use `setUrlWithoutDomain`

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 11]
```diff
@@ -1,42 +1,241 @@
...
+    }
+
+    override fun chapterFromElement(element: Element): SChapter = throw UnsupportedOperationException()
+
+    override fun chapterListSelector() = throw UnsupportedOperationException()
+
+    // Pages
+    override fun pageListParse(document: Document): List<Page> {
+        return document.select("main .relative section > img").mapIndexed { i, element ->
+            Page(i, "", element.attr("abs:src"))
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]:
```suggestion
            Page(i, imageUrl = element.attr("abs:src"))
```

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 12]
```diff
@@ -1,42 +1,241 @@
...
+        get() {
+            if (_cachedBaseUrl == null) {
+                _cachedBaseUrl = getString(BASE_URL_PREF, defaultBaseUrl)!!
+            }
+            return _cachedBaseUrl!!
+        }
+        set(value) {
+            _cachedBaseUrl = value
+            edit().putString(BASE_URL_PREF, value).apply()
+        }
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: you are not using the setter anywhere, so remove it, and make this a `val`

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 13]
```diff
@@ -1,42 +1,241 @@
...
+    override fun setupPreferenceScreen(screen: PreferenceScreen) {
+        EditTextPreference(screen.context).apply {
+            key = BASE_URL_PREF
+            title = "Edit source URL"
+            summary = "$baseUrl.Restart aplikasi jika belum berubah \nFor temporary use, if the extension is updated the change will be lost."
+            dialogTitle = title
+            dialogMessage = "Default URL:\n$defaultBaseUrl"
+            setDefaultValue(defaultBaseUrl)
+            setOnPreferenceChangeListener { _, _ ->
+                Toast.makeText(screen.context, "Restart the application to apply the changes", Toast.LENGTH_LONG).show()
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: fyi you can update baseurl here directly, without need for restart. just set `_cachedBaseUrl` to new value

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 14]
```diff
@@ -1,42 +1,241 @@
...
+                return SManga.UNKNOWN
+            }
+            return when (element.lowercase()) {
+                "ongoing" -> SManga.ONGOING
+                "completed" -> SManga.COMPLETED
+                "on hiatus" -> SManga.ON_HIATUS
+                "canceled" -> SManga.CANCELLED
+                else -> SManga.UNKNOWN
+            }
+        }
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: pull out of companion object

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt [hunk 15]
```diff
@@ -1,42 +1,241 @@
...
+
+        private val dateFormat by lazy {
+            SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.ENGLISH)
+        }
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: no need for lazy

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 1 above)
Comment (Riztard) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: I was also wondering why the other ext also use that

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 13 above)
Comment (stevenyomi) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: And just remove `_cachedBaseUrl`, use

```kotlin
override var baseUrl = // initial value
```

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 1 above)
Comment (stevenyomi) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: > I was also wondering why the other ext also use that

https://github.com/keiyoushi/extensions-source/pull/9651#discussion_r2205122173

Quoting my reply:

> The CI workflow can properly handle preferences.
> 
> This pattern is also misused in the repo. I wrote it to handle dynamic pulling URL from network on CI build, not for skipping preferences.

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 10 above)
Comment (Riztard) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: Ah right, that exist. Was wondering I miss something

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 13 above)
Comment (Riztard) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: I was copying what other ext did. Do I only need that for auto fetch?

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 6 above)
Comment (Riztard) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt:85]: Why? What's the pros?

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 13 above)
Comment (stevenyomi) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: Just fix it. It's obvious you're copy-pasting.

Comment (Riztard) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt]: Iam. Thought it was correct since not only 1 ext using it

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt (hunk 6 above)
Comment (stevenyomi) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt:85]: `select()` returns an `Elements` that contains all elements that match the selector, while you want the first. Calling `text()` or `attr()` on `Elements` returns space-joined values (or empty string when the collection is empty), which is not you want.

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt
Comment (stevenyomi) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt:1]: Remove the domain settings too; we can add it if the site changes URL really frequently.

Comment (Riztard) [reply src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/Ikiru.kt:1]: now that i check it, their old url seems redirect to the new one unlike other indo source. so ill remove it

**Review by stevenyomi — APPROVED** [review]
