### PR TITLE
VCPVMP: Move to multisrc and add ChoChoX

### LINKED ISSUE #3821: ChoChoX
### Source name

ChoChoX

### Source link

https://chochox.com/porno/

### Source language

Spanish

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #5859: Vcpvmp error
### Source information

 VCPVMP 

### Source language

Spanish

### Steps to reproduce

1. Search comic
2. Click in comic
3. Images are not displayed

### Expected behavior

The scans should come out correctly. 

### Actual behavior

Comics load but images don't show

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #5859 
Closes #3821 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/chochox/src/eu/kanade/tachiyomi/extension/es/chochox/Chochox.kt [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+class Chochox : VerComics("ChoChoX", "https://chochox.com", "es") {
+
+    override val urlSuffix = "porno"
+    override val genreSuffix = "tag"
+
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
+        var url = baseUrl.toHttpUrl().newBuilder()
+
+        if (query.isNotBlank()) {
+            url = baseUrl.toHttpUrl().newBuilder()
```
Comment (vetleledaal) [inline src/es/chochox/src/eu/kanade/tachiyomi/extension/es/chochox/Chochox.kt]: So this is the only change from the parent function. Can this be controlled with a flag? To include or not include `urlSuffix`.

Or if you want it more configurable, you can use a `searchSuffix` which defaults to `urlSuffix`, but is overwritable.

File: lib-multisrc/vercomics/src/eu/kanade/tachiyomi/multisrc/vercomics/VerComics.kt [hunk 2]
```diff
@@ -8,45 +8,75 @@ import eu.kanade.tachiyomi.source.model.SChapter
...
+    protected open val urlSuffix = ""
+    protected open val genreSuffix = ""
 
-    override fun latestUpdatesNextPageSelector() = throw UnsupportedOperationException()
+    override fun headersBuilder() = super.headersBuilder()
+        .add("Referer", "$baseUrl/")
 
     override fun popularMangaRequest(page: Int) = GET("$baseUrl/$urlSuffix/page/$page", headers)
 
     override fun popularMangaSelector() = "div.blog-list-items > div.entry"
```
Comment (vetleledaal) [inline lib-multisrc/vercomics/src/eu/kanade/tachiyomi/multisrc/vercomics/VerComics.kt]: You can use this selector for all sites:
```css
header:has(>h1):has(~ center > div[role=navigation]) + div > div.entry
```

Or the least strict:
```css
header:has(h1) ~ * .entry
```

or somewhere in-between

**Review by vetleledaal — APPROVED** [review]
