### PR TITLE
[ID] Komik Cast: Fixed API structure with source.

### LINKED ISSUE #13256: Komik Cast: No pages found error
### Source information

Komik Cast 1.4.75

### Source language

Indonesian

### Steps to reproduce

Open Any chapter on any manga

### Expected behavior

The page should shown

### Actual behavior

It's says No pages found

Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 16

### Other details

I also Tried to use VPN, but still the same.
It's working fine when i open it on WebView.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by NepThunder**
Addresses Issues:
closes: #13256, #13258

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt [hunk 1]
```diff
@@ -96,22 +96,21 @@ fun SeriesItem.toSManga(): SManga = SManga.create().apply {
 
 fun ChapterItem.toSChapter(seriesSlug: String?): SChapter = SChapter.create().apply {
     val chapterIndex = data.index
-    val formattedIndex = formatChapterNumber(chapterIndex)
+    val formattedIndex = formatChapterNumber(chapterIndex.toFloat())
```
Comment (AwkwardPeak7) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt]: this formatter is not needed for int. use the int field directly

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by MuhamadSyabitHidayattulloh** [comment]
delete the changes you made and follow this:

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt [hunk 2]
```diff
@@ -130,8 +129,7 @@ class KomikCast : HttpSource() {
 
     override fun pageListParse(response: Response): List<Page> {
         val result = response.parseAs<ChapterDetailResponse>()
-        val images = result.data.dataImages?.toSortedMap(compareBy { it.toIntOrNull() ?: Int.MAX_VALUE })
```
Comment (MuhamadSyabitHidayattulloh) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt:133]: `val images = result.data.data.images ?: emptyList()`

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt [hunk 3]
```diff
@@ -58,13 +58,13 @@ data class ChapterItem(
     val data: ChapterData,
     val createdAt: String? = null,
     val updatedAt: String? = null,
-    @SerialName("dataImages") val dataImages: Map<String, String>? = null,
```
Comment (MuhamadSyabitHidayattulloh) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt:61]: remove this

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt [hunk 4]
```diff
@@ -58,13 +58,13 @@ data class ChapterItem(
...
 )
 
 @Serializable
 data class ChapterData(
-    val index: Float,
+    val index: Int,
     val title: String? = null,
```
Comment (MuhamadSyabitHidayattulloh) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt:66]: add `val images: List<String>? = null,`

Comment (MuhamadSyabitHidayattulloh) [reply src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCastDto.kt:66]: `val index: Float,`

**Comment by MuhamadSyabitHidayattulloh** [comment]
@NepThunder delete all unused imports

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt [hunk 5]
```diff
@@ -9,25 +9,25 @@ import eu.kanade.tachiyomi.source.model.SChapter
 import eu.kanade.tachiyomi.source.model.SManga
 import eu.kanade.tachiyomi.source.online.HttpSource
 import keiyoushi.utils.parseAs
+import keiyoushi.utils.tryParse
+import kotlinx.serialization.SerialName
+import kotlinx.serialization.Serializable
```
Comment (MuhamadSyabitHidayattulloh) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt]: Remove this

File: src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt [hunk 6]
```diff
@@ -9,25 +9,25 @@ import eu.kanade.tachiyomi.source.model.SChapter
...
 import okhttp3.Headers
 import okhttp3.HttpUrl.Companion.toHttpUrl
 import okhttp3.OkHttpClient
 import okhttp3.Request
 import okhttp3.Response
+import java.text.DecimalFormat
+import java.text.SimpleDateFormat
+import java.util.Locale
```
Comment (MuhamadSyabitHidayattulloh) [inline src/id/komikcast/src/eu/kanade/tachiyomi/extension/id/komikcast/KomikCast.kt]: and remove this

**Review by AwkwardPeak7 — APPROVED** [review]
