### PR TITLE
Kisslove: improve code

### LINKED ISSUE #12499: KissLove: Chapters are out of order
### Source information

KissLove 1.4.17

### Source language

Japanese

### Steps to reproduce

1. Open some chapter list of manga (especially the chapter divided into decimal like xx.1 or xx.5)
2. Make sure the sorting method is set to by source

### Expected behavior

Chapters are in the same order as in WebView

### Actual behavior

Chapters are not in the same order as in WebView
chapters with decimals are in reverse order, and chapters with xx.5 are placed after the next whole chapter.

### Mihon/Tachiyomi version

Komikku 1.13.5

### Android version

Android 11

### Other details

idk if this is related to this issue, a small issue is that the integers chapter displays decimal points that are not displayed in the source
in previous version, these were not displayed

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #12599: KissLove: Unable to parse chapters from Jan 2021 and earlier
### Source information

KissLove 1.4.17

### Source language

Japanese

### Steps to reproduce

1. Open the manga "KANZEN KAIHI HEALER NO KISEKI - RAW".
2. Navigate to Chapter 19 (released Jan 24, 2021) or any earlier chapter.
3. Attempt to parse or load the chapter images.

### Expected behavior

The chapter should parse successfully and display images, just like the newer chapters (e.g., Chapter 20 and above).

### Actual behavior

Parsing fails for Chapter 19 (Jan 24, 2021) and all preceding chapters. In contrast, Chapter 20 (Feb 24, 2021) and all newer chapters load correctly, indicating a specific cutoff date for the issue.

### Mihon/Tachiyomi version

Yōkai v1.9.7.3

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by 2Loong6**
Closes #12499
Closes #12599

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt [hunk 1]
```diff
@@ -134,10 +161,71 @@ class KissLove : HttpSource() {
...
+                    .await()
+                    .parseAs<List<Genre>>()
+                    .map {
+                        CheckBoxFilter(it.name)
+                    }
+
+                filterList.add(
+                    GenreFilter(
+                        intl["genre"],
+                        genres,
```
Comment (AwkwardPeak7) [inline src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt]: you don't cache the filters?

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt [hunk 2]
```diff
@@ -134,10 +161,71 @@ class KissLove : HttpSource() {
...
         private const val CLIENT_ID = "KL9K40zaSyC9K40vOMLLbEcepIFBhUKXwELqxlwTEF"
         val DATE_FORMATTER by lazy {
             SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.ENGLISH)
         }
+        private val FILTER_IMG = setOf(
+            "https://1.bp.blogspot.com/-ZMyVQcnjYyE/W2cRdXQb15I/AAAAAAACDnk/8X1Hm7wmhz4hLvpIzTNBHQnhuKu05Qb0gCHMYCw/s0/LHScan.png",
+            "https://s4.imfaclub.com/images/20190814/Credit_LHScan_5d52edc2409e7.jpg",
+            "https://s4.imfaclub.com/images/20200112/5e1ad960d67b2_5e1ad962338c7.jpg",
+        )
+        private val IMG_URL_MAPPING = mapOf(
```
Comment (AwkwardPeak7) [inline src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt:231]: can you explain what this mapping is?

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt [hunk 3]
```diff
@@ -134,10 +161,71 @@ class KissLove : HttpSource() {
...
+    private class GenreFilter(name: String, state: List<CheckBoxFilter>) : Filter.Group<CheckBoxFilter>(name, state)
+
+    private class CheckBoxFilter(name: String) : Filter.CheckBox(name)
+
     companion object {
         private const val CLIENT_ID = "KL9K40zaSyC9K40vOMLLbEcepIFBhUKXwELqxlwTEF"
         val DATE_FORMATTER by lazy {
             SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.ENGLISH)
         }
+        private val FILTER_IMG = setOf(
```
Comment (AwkwardPeak7) [inline src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt:226]: why filter out?

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt (hunk 2 above)
Comment (MikeZeDev) [reply src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt:231]: Its in website source code. They replace old domains on the fly .

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt (hunk 1 above)
Comment (2Loong6) [reply src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt]: thank for review, it has been cached

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt (hunk 3 above)
Comment (2Loong6) [reply src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt:226]: the site code, i guess that some img is internal logic that has been outdated

File: src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt [hunk 4]
```diff
@@ -134,10 +162,87 @@ class KissLove : HttpSource() {
...
+                        }
+
+                    cachedGenres = genres
+                    genres
+                } catch (_: Exception) {
+                    emptyList()
+                }
+            }
+        }
+    }
```
Comment (AwkwardPeak7) [inline src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt]: dont block the thread, as `getFilterList` run on ui thread. fire the request in background coroutine or thread. then return from `getFilterList` immediately, with a filter.header telling user to press reset. when user resets again, `getFilterList` will be called, and this time filters will have been cached, to be returned.

Comment (2Loong6) [reply src/ja/kisslove/src/eu/kanade/tachiyomi/extension/ja/kisslove/KissLove.kt]: changed

**Review by AwkwardPeak7 — APPROVED** [review]
