### PR TITLE
Fix Hive Scans Page Select

### LINKED ISSUE #13548: Hive Scans: `Expected URL scheme` error with chapter pages
### Source information

Hive Scans 1.4.52

### Source language

English

### Steps to reproduce

1. Go to The Constellations Are My Disciples
2. Click on any chapter, most recent 133 for an example
3. The first two pages load, but the rest, pages 3-9 give off an illegal exception error. Trying to download it gives you the same error

Image

### Expected behavior

It should be able to fully load each page and be downloadable.

### Actual behavior

Only two of the pages load and the rest give off an error.

### Mihon/Mihon fork version

TachiyomiSY 1.12.0

### Android version

Android 16

### Other details

Works fine in WebView

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Closes #13548

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/en/infernalvoidscans/src/eu/kanade/tachiyomi/extension/en/infernalvoidscans/HiveScans.kt [hunk 1]
```diff
@@ -27,7 +26,9 @@ class HiveScans :
...
         .set("Cache-Control", "max-age=0")
 
-    override fun pageListParse(response: Response): List<Page> = response.asJsoup().select("img[data-image-index]").mapIndexed { index, element ->
-        Page(index, imageUrl = element.absUrl("src"))
-    }
+    val pageRegex = Regex(""""(http\S+?/public//upload/series/\S+?)\\"""")
+
+    override fun pageListParse(response: Response): List<Page> = pageRegex.findAll(response.body.string()).mapIndexed { index, element ->
+        Page(index, imageUrl = element.groupValues[1])
+    }.toList()
```
Comment (AwkwardPeak7) [inline src/en/infernalvoidscans/src/eu/kanade/tachiyomi/extension/en/infernalvoidscans/HiveScans.kt]: consider parsing it via `extractNextJs` helper under `keiyoushi.utils`

```kt
@Serializable
class Images(
    val images: List<Image>
) {
    @Serializale
    class Image(
        val url: String,
    )
}

// 

val images = response.extratNextJs<Images>()?.images.orEmpty()

**Review by AwkwardPeak7 — APPROVED** [review]
