### PR TITLE
Pink sea unicorn exception and icon

### LINKED ISSUE #3960: add password exception to pink sea unicorn
### Source name

pink sea unicorn 

### Source language

portuguese

### Describe your suggested feature

extension giving out null when updating entries

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by kana-shii**
closes: #3960 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/pt/pinkseaunicorn/src/eu/kanade/tachiyomi/extension/pt/pinkseaunicorn/PinkSeaUnicorn.kt [hunk 1]
```diff
@@ -16,7 +19,19 @@ class PinkSeaUnicorn : Madara(
 
     override val client: OkHttpClient = super.client.newBuilder()
         .rateLimit(1, 2, TimeUnit.SECONDS)
+        .addInterceptor(::checkPasswordProtectedIntercept)
```
Comment (AwkwardPeak7) [inline src/pt/pinkseaunicorn/src/eu/kanade/tachiyomi/extension/pt/pinkseaunicorn/PinkSeaUnicorn.kt]: you can `addNetworkInterceptor` which will receive the redirect url in chain.request, so you can just test that.

Comment (kana-shii) [reply src/pt/pinkseaunicorn/src/eu/kanade/tachiyomi/extension/pt/pinkseaunicorn/PinkSeaUnicorn.kt]: > you can `addNetworkInterceptor` which will receive the redirect url in chain.request, so you can just test that.

You mean basically changing the `.addInterceptor(::checkPasswordProtectedIntercept)` to `.addNetworkInterceptor(::checkPasswordProtectedIntercept)`?

Comment (AwkwardPeak7) [reply src/pt/pinkseaunicorn/src/eu/kanade/tachiyomi/extension/pt/pinkseaunicorn/PinkSeaUnicorn.kt]: yes and check chain.request().url instead of first getting the response

File: src/pt/pinkseaunicorn/src/eu/kanade/tachiyomi/extension/pt/pinkseaunicorn/PinkSeaUnicorn.kt [hunk 2]
```diff
@@ -16,7 +19,19 @@ class PinkSeaUnicorn : Madara(
 
     override val client: OkHttpClient = super.client.newBuilder()
         .rateLimit(1, 2, TimeUnit.SECONDS)
+        .addNetworkInterceptor(::checkPasswordProtectedIntercept)
         .build()
 
+    private fun checkPasswordProtectedIntercept(chain: Interceptor.Chain): Response {
+        val response = chain.proceed(chain.request())
+
+        if (response.request.url.queryParameter("password-protected") != null) {
```
Comment (AwkwardPeak7) [inline src/pt/pinkseaunicorn/src/eu/kanade/tachiyomi/extension/pt/pinkseaunicorn/PinkSeaUnicorn.kt]: I also said to change this, as network interceptor gets the redirect url in the request as well
```
if (chain.request().url.queryParameter("password-protected") != null) {
```

Comment (kana-shii) [reply src/pt/pinkseaunicorn/src/eu/kanade/tachiyomi/extension/pt/pinkseaunicorn/PinkSeaUnicorn.kt]: > I also said to change this, as network interceptor gets the redirect url in the request as well
> 
> ```
> if (chain.request().url.queryParameter("password-protected") != null) {
> ```

Sorry I didn't see the last message
will change it right away

**Review by AwkwardPeak7 — APPROVED** [review]
