### PR TITLE
Yupmanga fix chapter images

### LINKED ISSUE #14825: Yupmanga not loading chapter
### Source information

Yupmanga 1.4. 6

### Source language

Spanish 

### Steps to reproduce

When trying to read and open any chapter of a series, it gives an error and no chapter  loading

Image

### Expected behavior

Chapter loading

### Actual behavior

Gives display error for any mawhas

Image

### Mihon/Mihon fork version

0.19.9

### Android version

Android 11

### Other details

I think the problem is that the page reader to read mangas moves from left to the end of the chapter and the page reader manwhas moves from top to bottom. 

Image

Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14825

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Yupmanga.kt [hunk 1]
```diff
@@ -66,14 +83,18 @@ class Yupmanga : HttpSource() {
...
-            }
-        } ?: emptyList()
+        val mangas = document.selectFirst("div.grid:has(div.comic-card)")
+            ?.select("div.comic-card")
+            ?.mapNotNull { element ->
+                val href = element.selectFirst("a[href]")?.attr("abs:href") ?: return@mapNotNull null
+                val id = href.toHttpUrlOrNull()?.queryParameter("id") ?: return@mapNotNull null
+
+                SManga.create().apply {
+                    title = element.selectFirst("h3")?.text() ?: ""
```
Comment (AwkwardPeak7) [inline src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Yupmanga.kt]: title is also mandatory

File: src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Dto.kt [hunk 2]
```diff
@@ -0,0 +1,27 @@
+package eu.kanade.tachiyomi.extension.es.yupmanga
+
+import kotlinx.serialization.SerialName
+import kotlinx.serialization.Serializable
+
+@Serializable
+class ChapterListDto(
+    val html: String = "",
+    @SerialName("currentPage") private val currentPage: Int = 1,
+    @SerialName("totalPages") private val totalPages: Int = 1,
```
Comment (AaronDeimos) [inline src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Dto.kt]: SerialName redundant — already camelCase.

**Review by vetleledaal — APPROVED** [review]
