### PR TITLE
CatharsisWorld: Fix page decrypt

### LINKED ISSUE #8738: Unexpected json token catharsis world
### Source information

Catharsiswolrld  1.4.44

### Source language

Spanish

### Steps to reproduce

Ingresa a la fuente, al momente de leer algun manwha da el error

### Expected behavior

Deberia visualizar la lectura de manwha

### Actual behavior

Da error al momento de visualizar para leer algun manwha

Image

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by bapeey**
Closes #8738 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/catharsisworld/src/eu/kanade/tachiyomi/extension/es/catharsisworld/CatharsisWorld.kt [hunk 1]
```diff
@@ -51,6 +58,42 @@ class CatharsisWorld : Madara(
         setUrlWithoutDomain(element.selectFirst("a")!!.attr("href"))
     }
 
+    override fun pageListParse(document: Document): List<Page> {
```
Comment (vetleledaal) [inline src/es/catharsisworld/src/eu/kanade/tachiyomi/extension/es/catharsisworld/CatharsisWorld.kt]: Have not looked at the Madara class, but if this is an update/improvement to the current implementation it should be moved there.

If the difference is site specific (selector, variable names) it should be extracted into some overridable variable. If simple enough you might not need to bump Madara.

File: src/es/catharsisworld/src/eu/kanade/tachiyomi/extension/es/catharsisworld/CatharsisWorld.kt [hunk 2]
```diff
@@ -51,6 +58,42 @@ class CatharsisWorld : Madara(
...
+        launchIO { countViews(document) }
+
+        val chapterProtector = document.selectFirst(chapterProtectorSelector)
+            ?: return document.select(pageListParseSelector).mapIndexed { index, element ->
```
Comment (vetleledaal) [inline src/es/catharsisworld/src/eu/kanade/tachiyomi/extension/es/catharsisworld/CatharsisWorld.kt]: Consider just returning the super method here.

File: src/es/catharsisworld/src/eu/kanade/tachiyomi/extension/es/catharsisworld/CatharsisWorld.kt (hunk 1 above)
Comment (MikeZeDev) [reply src/es/catharsisworld/src/eu/kanade/tachiyomi/extension/es/catharsisworld/CatharsisWorld.kt]: > Have not looked at the Madara class, but if this is an update/improvement to the current implementation it should be moved there.
> 
> If the difference is site specific (selector, variable names) it should be extracted into some overridable variable. If simple enough you might not need to bump Madara.

Theme's name is "Kozaku" according to wordpress scanners.
In case you are curious https://github.com/manga-download/haruneko/blob/997739b68b0a45ead51b2e3dab8476cb43a287e5/web/src/engine/websites/templates/Kozaku.ts#L30

I know 4 websites using it

```ts
import '../CatharsisWorld_e2e';
import '../InariManga_e2e';
import '../LectorJPG_e2e';
import '../TempleScanEsp_e2e';
```

Perhaps this website need tweaking to get pages

File: lib-multisrc/madara/src/eu/kanade/tachiyomi/multisrc/madara/Madara.kt [hunk 3]
```diff
@@ -979,6 +979,8 @@ abstract class Madara(
     open val pageListParseSelector = "div.page-break, li.blocks-gallery-item, .reading-content .text-left:not(:has(.blocks-gallery-item)) img"
 
     open val chapterProtectorSelector = "#chapter-protector-data"
+    open val chapterProtectorPasswordPrefix = "wpmangaprotectornonce='"
+    open val chapterProtectorDataPrefix = "chapter_data='"
```
Comment (vetleledaal) [inline lib-multisrc/madara/src/eu/kanade/tachiyomi/multisrc/madara/Madara.kt:983]: Where are these used?

**Review by AwkwardPeak7 — APPROVED** [review]
