### PR TITLE
YupManga (ES): Challenge solving and move token fetch to page list getting

### LINKED ISSUE #14615: Yupmanga No cargan los capitulos
### Source information

Yupmanga 1.4.3

### Source language

Español 

### Steps to reproduce

1. Entro a la fuente
2. Aparecen las portadas
3. Doy click a una de ellas y aparecen todos los capitulos
4. Doy click al capitulo y no carga nada solo aparece HTTP 403

Image

Image

### Expected behavior

Al aparecer los capitulos y entrar en uno de ellos, deberia cargar normal los capitulos y leer

Image

### Actual behavior

Parece todo normal pero al tratar de leer un capitulo aparece error 

### Mihon/Mihon fork version

Mihon 0.19.7

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by disk-iq8**
Evaluation challange seems simple template with varying data xor, not worth a whole js engine, so regex it is, with fingers crossed

```js
var _$ARR=[...];
var _$KEY=String.fromCharCode(...);
var _$RES=0;
for(var _$I=0;_$I<_$ARR.length;_$I++){
    _$RES=(_$RES^_$ARR[_$I]) + _$KEY.charCodeAt(_$I % _$KEY.length);
}
```
Closes #14615 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Yupmanga.kt [hunk 1]
```diff
@@ -189,4 +227,11 @@ class Yupmanga : HttpSource() {
         val success: Boolean,
         val token: String,
     )
+
+    @Serializable
+    data class ChallengeDto(
```
Comment (vetleledaal) [inline src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Yupmanga.kt]: A regular class is fine here. You don't need a data class.

File: src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Yupmanga.kt [hunk 2]
```diff
@@ -139,16 +139,54 @@ class Yupmanga : HttpSource() {
...
+
+        val key = Regex("""fromCharCode\((.*?)\)""").find(js)
+            ?.groupValues?.get(1)
+            ?.split(",")
+            ?.mapNotNull { it.trim().toIntOrNull()?.toChar() }
+            ?.joinToString("")
+            ?: return null
+
+        return solveChallenge(arr, key)
+    }
```
Comment (vetleledaal) [inline src/es/yupmanga/src/eu/kanade/tachiyomi/extension/es/yupmanga/Yupmanga.kt:170]: Move invariant regex to class.

**Review by AwkwardPeak7 — APPROVED** [review]
