### PR TITLE
DoujinHentai: Rework & Fix 404

### LINKED ISSUE #12238: DoujinHentai: `HTTP 404` error
### Source information

Doujinhentai 1.4.47

### Source language

Spanish 

### Steps to reproduce

Ya sea al buscar o a filtrar la lista mas reciente da error 404

Image

Image

### Expected behavior

Deberia visualizar la lista de series de dicha fuente

### Actual behavior

Da error 404, se comprobo con webview y la pagina esta operativa 

Image

Removed NSFW image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ONII404**
Bump overrideVersionCode to 3 and overhaul the DoujinHentai extension to match updated site structure. Update selectors and endpoints (use lista-manga-hentai / lista-de-...), unify popular/latest handling, and implement robust search routing (text search + route-based filters for genre/artist/author/scanlator/letter/type and order). Rework manga details and chapter parsing (author/artist extraction, status, thumbnails, improved chapter naming and scanlator/date parsing using a lazy SimpleDateFormat). Add comprehensive filters (Genre, Type, Artist, Author, Scanlator) and expand genre list. Implement pageListParse with multiple strategies (embedded JSON, pre-rendered images, single-page mode) and fix thumbnail/src handling.

Closes #12238 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 1]
```diff
@@ -22,99 +24,315 @@ class DoujinHentai :
...
+        val subTitle = element.selectFirst("div.flex-1 div.text-sm.font-medium")?.text()?.trim() ?: ""
+        chapter.name = if (subTitle.isNotEmpty() && subTitle != baseName) "$baseName: $subTitle" else baseName
+
+        chapter.scanlator = element.select("div.text-sm.text-right a[href*='/user/']")
+            .firstOrNull()?.text()?.trim()
+
+        val dateText = element.select("div.text-sm.text-right span.font-medium")
+            .lastOrNull()?.text()?.trim()
+        if (!dateText.isNullOrEmpty()) {
+            chapter.date_upload = runCatching { chapterDateFormat.parse(dateText)?.time ?: 0L }.getOrDefault(0L)
```
Comment (darwin-256) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]: use `keiyoushi.utils.tryParse` here

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 2]
```diff
@@ -22,99 +24,315 @@ class DoujinHentai :
...
+    // ── Pages ────────────────────────────────────────────────────────────────
+    override fun pageListParse(document: Document): List<Page> {
+        // Estrategia 1: JSON embebido → const pageUrls = {"1":"url",...};
+        document.select("script").map { it.data() }
+            .firstOrNull { it.contains("pageUrls") }
+            ?.let { script ->
+                val json = Regex("""const pageUrls\s*=\s*(\{[^;]+\})""")
+                    .find(script)?.groupValues?.get(1)
+                if (json != null) {
+                    val pages = Regex(""""(\d+)"\s*:\s*"([^"]+)"""")
```
Comment (darwin-256) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]: Separate regex

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 3]
```diff
@@ -22,99 +24,315 @@ class DoujinHentai :
...
+                        .findAll(json)
+                        .map { Page(it.groupValues[1].toInt() - 1, "", it.groupValues[2].replace("\\/", "/")) }
```
Comment (darwin-256) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
                        .map { Page(it.groupValues[1].toInt() - 1, imageUrl = it.groupValues[2].replace("\\/", "/")) }
```

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 4]
```diff
@@ -22,99 +24,315 @@ class DoujinHentai :
...
+                    if (pages.isNotEmpty()) return pages
+                }
+            }
+
+        // Estrategia 2: imágenes pre-renderizadas en el HTML
+        document.select("div#vertical-pages-container div[data-page] img")
+            .takeIf { it.isNotEmpty() }
+            ?.let { imgs ->
+                return imgs.mapIndexed { idx, img ->
+                    Page(idx, "", img.attr("abs:src").ifEmpty { img.attr("src") })
```
Comment (darwin-256) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
                    Page(idx, imageUrl = img.attr("abs:src").ifEmpty { img.attr("src") })

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 5]
```diff
@@ -22,99 +24,315 @@ class DoujinHentai :
...
+                }
+            }
 
-    override fun mangaDetailsParse(document: Document): SManga = super.mangaDetailsParse(document).apply {
-        title = title.removePrefix("Doujin Hentai:").trim()
+        // Estrategia 3: single page mode
+        return document.select("div.single-page-mode img.manga-image")
+            .mapIndexed { idx, img ->
+                Page(idx, "", img.attr("abs:src").ifEmpty { img.attr("src") }.trim())
```
Comment (darwin-256) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
                Page(idx, imageUrl = img.attr("abs:src").ifEmpty { img.attr("src") })
```

**Review by darwin-256 — COMMENTED** [review]
Also Remove redundant `.trim()` after `.text()`
Jsoup `.text()` is already trimmed: Calling `element.text().trim()` is redundant

**Comment by AaronDeimos** [comment]
Doesn't look like the site is even using Madara anymore, so it might be better to just make it an httpsource instead.

**Comment by ONII404** [comment]
I've made the changes based on your feedback @darwin-256

**Comment by ONII404** [comment]
> Doesn't look like the site is even using Madara anymore, so it might be better to just make it an httpsource instead.

Should I take that as a suggestion or a requirement? This is my first contribution, so I’m not very familiar with the project yet.
I think it would be a good idea, but it would mean more work, especially since the extension is already fully functional.
image

**Comment by AwkwardPeak7** [comment]
it isn't really more work, you have already done most of the parsing work, just need to base on `HttpSource` instead of `Madara`

**Comment by ONII404** [comment]
I've migrated from Madara to ParsedHttpSource. @AaronDeimos @AwkwardPeak7

**Comment by darwin-256** [comment]
> I've migrated from Madara to ParsedHttpSource. @AaronDeimos @AwkwardPeak7 

If you read contributing.md you should have seen that parsedhttpsource is deprecated and you should use httpsource instead

File: src/es/doujinhentai/build.gradle [hunk 6]
```diff
@@ -3,7 +3,7 @@ ext {
     extClass = '.DoujinHentai'
     themePkg = 'madara'
     baseUrl = 'https://doujinhentai.net'
```
Comment (AaronDeimos) [inline src/es/doujinhentai/build.gradle]:
```suggestion
```
Remove

File: src/es/doujinhentai/build.gradle [hunk 7]
```diff
@@ -3,7 +3,7 @@ ext {
...
-    overrideVersionCode = 2
+    overrideVersionCode = 3
```
Comment (AaronDeimos) [inline src/es/doujinhentai/build.gradle]:
```suggestion
    extVersionCode = 49
```
Individual extension requires `extVersionCode`
For extension that use themes final version is calculated as `baseVersionCode + overrideVersionCode`
So current extension version is 48

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 8]
```diff
@@ -1,120 +1,355 @@
...
 import java.util.Locale
 
-class DoujinHentai :
-    Madara(
-        "DoujinHentai",
-        "https://doujinhentai.net",
-        "es",
-        SimpleDateFormat("d MMM. yyyy", Locale.ENGLISH),
-    ) {
+class DoujinHentai : ParsedHttpSource() {
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]: Parsedhttpsource deprecated, use httpsource instead.

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 9]
```diff
@@ -1,120 +1,355 @@
...
+
+        // Estrategia 3: single page mode
+        return document.select("div.single-page-mode img.manga-image")
+            .mapIndexed { idx, img ->
+                Page(idx, imageUrl = img.attr("abs:src").ifEmpty { img.attr("src") })
+            }
+    }
+
+    // ParsedHttpSource requiere imageUrlParse(Document), pero este método nunca se invoca en la práctica.
+    override fun imageUrlParse(document: Document): String = throw UnsupportedOperationException("imageUrlParse no se utiliza")
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
    override fun imageUrlParse(document: Document): String = throw UnsupportedOperationException()
```
Don't add message here as per contribution guidelines

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 10]
```diff
@@ -1,120 +1,355 @@
...
+        Filter.Header("Buscar por scanlator/usuario exacto (ej: NekoCreme, Fritz Translations)"),
+        ScanlatorFilter(),
+        Filter.Separator(),
+        Filter.Header("Filtrar por primera letra del título"),
+        LetterFilter(),
     )
 
-    class GenreSelectFilter :
+    // ── Filter classes ────────────────────────────────────────────────────────
+    open class UriPartFilter(
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]: Nitpick move filters to seprate file

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 11]
```diff
@@ -1,120 +1,355 @@
...
-    override fun popularMangaRequest(page: Int): Request = GET("$baseUrl/list-manga-hentai?orderby=views&page=$page", headers)
-    override fun popularMangaSelector() = "div.col-md-3 a"
     override fun popularMangaFromElement(element: Element): SManga {
         val manga = SManga.create()
-
         manga.setUrlWithoutDomain(element.attr("href"))
-        manga.title = element.select("span.card-title").text().removePrefix("Leer").trim()
-        manga.thumbnail_url = element.select("img").attr("abs:data-src")
-
+        manga.title = element.selectFirst("h3.font-bold")?.text() ?: ""
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]: Title is mandatory

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 12]
```diff
@@ -1,120 +1,355 @@
...
+
+    // ── Manga details ─────────────────────────────────────────────────────────
+    // "Autor(es)"  → <a rel="author" href=".../author/...">
+    // "Artista(s)" → <a href=".../artist/...">  (sin rel="author")
+    // Algunos títulos solo tienen artista, otros solo autor, otros ambos.
+    override fun mangaDetailsParse(document: Document): SManga {
+        val main: Element = document.selectFirst("main#main-content") ?: document.body()
+        val manga = SManga.create()
+
+        manga.title = main.selectFirst("h1")?.text() ?: ""
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]: Same

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt:1]: Bump versionId (`override val versionId = 2`) 
if old urls aren't compatible to force existing users to migrate

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 13]
```diff
@@ -1,120 +1,261 @@
...
 
-        manga.setUrlWithoutDomain(element.attr("href"))
-        manga.title = element.select("span.card-title").text().removePrefix("Leer").trim()
-        manga.thumbnail_url = element.select("img").attr("abs:data-src")
+    override fun headersBuilder() = super.headersBuilder()
+        .add("Referer", "$baseUrl/")
+
+    // ── Helpers ───────────────────────────────────────────────────────────────
+
+    private fun Response.asJsoup(): Document = Jsoup.parse(body.string(), request.url.toString())
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
```
App already has this, just need to import

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 14]
```diff
@@ -1,120 +1,261 @@
...
 
-import eu.kanade.tachiyomi.multisrc.madara.Madara
 import eu.kanade.tachiyomi.network.GET
 import eu.kanade.tachiyomi.source.model.Filter
 import eu.kanade.tachiyomi.source.model.FilterList
+import eu.kanade.tachiyomi.source.model.MangasPage
+import eu.kanade.tachiyomi.source.model.Page
+import eu.kanade.tachiyomi.source.model.SChapter
 import eu.kanade.tachiyomi.source.model.SManga
+import eu.kanade.tachiyomi.source.online.HttpSource
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt:10]:
```suggestion
import eu.kanade.tachiyomi.source.online.HttpSource
import eu.kanade.tachiyomi.util.asJsoup
```

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 15]
```diff
@@ -1,120 +1,261 @@
...
+        .add("Referer", "$baseUrl/")
+
+    // ── Helpers ───────────────────────────────────────────────────────────────
+
+    private fun Response.asJsoup(): Document = Jsoup.parse(body.string(), request.url.toString())
 
+    private fun mangaFromElement(element: Element): SManga {
+        val manga = SManga.create()
+        manga.setUrlWithoutDomain(element.attr("href"))
+        manga.title = element.selectFirst("h3.font-bold")?.text() ?: throw Exception()
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
    private fun mangaFromElement(element: Element): SManga? {
        val manga = SManga.create()
        manga.setUrlWithoutDomain(element.attr("href"))
        manga.title = element.selectFirst("h3.font-bold")?.text() ?: return null
```

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 16]
```diff
@@ -1,120 +1,261 @@
...
+        }
         return manga
     }
 
-    override fun popularMangaNextPageSelector() = "a[rel=next]"
-    override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/list-manga-hentai?orderby=last&page=$page", headers)
+    private fun mangasPageFromDocument(document: Document): MangasPage {
+        val mangas = document
+            .select("div.group.bg-white.rounded-2xl a.block")
+            .map { mangaFromElement(it) }
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
            .mapNotNull { mangaFromElement(it) }
```

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 17]
```diff
@@ -1,120 +1,261 @@
...
+    // ── Manga details ──────────────────────────────────────────────────────────
+    // "Autor(es)"  → <a rel="author" href=".../author/...">
+    // "Artista(s)" → <a href=".../artist/...">  (sin rel="author")
+    // Algunos títulos solo tienen artista, otros solo autor, otros ambos.
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+        val main: Element = document.selectFirst("main#main-content") ?: document.body()
+        val manga = SManga.create()
+
+        manga.title = main.selectFirst("h1")?.text() ?: throw Exception()
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
        manga.title = main.selectFirst("h1")!!.text()
```

File: src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt [hunk 18]
```diff
@@ -1,120 +1,261 @@
...
+import eu.kanade.tachiyomi.source.model.MangasPage
+import eu.kanade.tachiyomi.source.model.Page
+import eu.kanade.tachiyomi.source.model.SChapter
 import eu.kanade.tachiyomi.source.model.SManga
+import eu.kanade.tachiyomi.source.online.HttpSource
+import keiyoushi.utils.tryParse
 import okhttp3.HttpUrl.Companion.toHttpUrl
 import okhttp3.Request
+import okhttp3.Response
+import org.jsoup.Jsoup
```
Comment (AaronDeimos) [inline src/es/doujinhentai/src/eu/kanade/tachiyomi/extension/es/doujinhentai/DoujinHentai.kt]:
```suggestion
```

**Review by AwkwardPeak7 — APPROVED** [review]
