### PR TITLE
Animesama: Fix URL changes

### LINKED ISSUE #12392: AnimeSama: `No results found` on Popular, `No chapters found` / New website URL (`.tv`)
### Source information

Animesama 1.4.12

### Source language

French

### Source new URL

https://anime-sama.tv/

### Steps to reproduce

1. Open animeSama and search for gachiakuta or any other anime. Compare to the website and it will be there but not on the extension

### Expected behavior

Image

### Actual behavior

Image

### Mihon/Tachiyomi version

4.11 (405)

### Android version

Ios 18.1

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by CriosChan**
Closes #12392

This update adds automatic retrieval of the most recent working link for anime-sama from https://anime-sama.pw/ (their official site for tracking their domain name changes). If you would prefer me to retrieve the URL manually rather than automatically in the extension, please let me know. I would also like to know if there is a cleaner way to do this than the way I have done it, which seems a little sketchy to me.

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
you should fetch it in an interceptor. set regular baseurl to the pw domain if `_baseUrl` is null. in the interceptor, if requrest is for pw domain, fetch the actual baseurl (synchronized for thread safety) and modify the request and change url host.

**Comment by Starmania** [comment]
Why not use extension settings as storage ?

**Comment by CriosChan** [comment]
I admit I haven't played around with the extension settings yet. Let's see what AwkwardPeak7 thinks.

File: src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt [hunk 1]
```diff
@@ -30,15 +30,17 @@ class AnimeSama : ParsedHttpSource() {
...
 
     private val cdn = "$baseUrl/s2/scans/"
 
     override val lang = "fr"
 
     override val supportsLatest = true
 
-    override val client: OkHttpClient = network.cloudflareClient
+    override val client: OkHttpClient = network.client.newBuilder()
+        .addInterceptor(AnimeSamaInterceptor(network.client, baseUrl, headers))
```
Comment (AwkwardPeak7) [inline src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt]: keep cloudflareclient

File: src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSamaInterceptor.kt [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+                .url(newUrl)
+                .build()
+        }
+
+        return chain.proceed(request)
+    }
+
+    private fun fetchAnimeSamaURL(): String {
+        val domainListUrl = baseUrl.toHttpUrl()
+        val requestToFetchDomains = GET(domainListUrl, headers)
```
Comment (AwkwardPeak7) [inline src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSamaInterceptor.kt]:
```suggestion
        val requestToFetchDomains = GET(baseUrl, headers)
```

File: src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSamaInterceptor.kt [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+
+        val domainsResponse = client.newCall(requestToFetchDomains).execute()
+        val domainsDocument = domainsResponse.asJsoup()
+        val button = domainsDocument.getElementsByClass("btn-primary").first()
+
+        if (button == null) throw UnsupportedOperationException("Unable to retrieve the most recent URL for anime-sama.")
+
+        val url = button.absUrl("href")
+        return url
```
Comment (AwkwardPeak7) [inline src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSamaInterceptor.kt]:
```suggestion
        return button.absUrl("href")
```

**Review by AwkwardPeak7 — COMMENTED** [review]
probably should override `getMangaUrl` and `getChapterUrl` to use fetched baseurl as well. so webview urls work

File: src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt (hunk 1 above)
Comment (CriosChan) [reply src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt]: I'll put it back, I changed it because I think I made a mistake when I made the first version of the extension, Cloudflare doesn't seem to be used on anime-sama.

Comment (vetleledaal) [reply src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt]: Cloudflare is the default client in Mihon. Some forks/older versions still use the regular `network.client`, so explicitly using the Cloudflare client keeps the experience consistent.

Comment (CriosChan) [reply src/fr/animesama/src/eu/kanade/tachiyomi/extension/fr/animesama/AnimeSama.kt]: Oh, I didn't know that. Thank you for the details!

**Review by AwkwardPeak7 — APPROVED** [review]
