### PR TITLE
Fix manhuaren No value for response

### LINKED ISSUE #97: manhuaren No value for response
### Source information

Manhuaren 1.4.14

### Source language

中文

### Steps to reproduce

Just in all situation returns No value for response and load nothing

### Expected behavior

to load stuff

### Actual behavior

returning No value for response

### Tachiyomi version

0.15.2

### Android version

Harmony os 3(AOSP Android 11)

### Other details

Will this be fix? Or this extension will be removed?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by felixfon**
Closes #97

I have been using this version for many months. 😄 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt [hunk 1]
```diff
@@ -123,20 +149,38 @@ class Manhuaren : HttpSource() {
             .build()
 
         val simSerialNumber = generateSimSerialNumber()
-        val mac = Random.nextUBytes(6)
-            .joinToString(":") { it.toString(16).padStart(2, '0') }
+        // val mac = Random.nextUBytes(6)
```
Comment (AwkwardPeak7) [inline src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt:173]: remove commented code

File: src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt [hunk 2]
```diff
@@ -91,16 +108,25 @@ class Manhuaren : HttpSource() {
...
-        val res = client.newCall(getAnonyUser()).execute()
-        val body = JSONObject(res.body.string())
-        val response = body.getJSONObject("response")
-        val tokenResult = response.getJSONObject("tokenResult")
-        val scheme = tokenResult.getString("scheme")
-        val parameter = tokenResult.getString("parameter")
+        var token = preferences.getString(TOKEN_PREF, null)
+        if (token == null || userId == "-1") {
+            val res = client.newCall(getAnonyUser()).execute()
+            val body = JSONObject(res.body.string())
```
Comment (AwkwardPeak7) [inline src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt]: would it be possible to migrate `org.json` usage to `kotlinx.serialization`

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/ErrorResponseInterceptor.kt [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+            response.close()
+            Result.success(response)
+        } catch (e: Throwable) {
+            if (chain.call().isCanceled()) throw e
+            Result.failure(e)
+        }
+
+        return failedResult.getOrThrow()
+    }
+}
```
Comment (stevenyomi) [inline src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/ErrorResponseInterceptor.kt]:
```kotlin
class ErrorResponseInterceptor(private val baseUrl: String, private val preferences: SharedPreferences) : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()
        val response = chain.proceed(request)
        if (!request.url.toString().startsWith(baseUrl)) return response

        val body = response.body
        val content = body.string() // closes the response
        if ("errorResponse" in Json.parseToJsonElement(content).jsonObject) {
            preferences.edit()
                .remove(TOKEN_PREF)
                .remove(USER_ID_PREF)
                .apply()
            throw IOException("用户ID已自动清除，请重启应用")
        }

        return response.newBuilder().body(content.toResponseBody(body.contentType())).build()
    }
}
```

File: src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt [hunk 4]
```diff
@@ -35,28 +43,37 @@ import javax.crypto.Cipher
...
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
 
     private val gsnSalt = "4e0a48e1c0b54041bce9c8f0e036124d"
     private val encodedPublicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmFCg289dTws27v8GtqIffkP4zgFR+MYIuUIeVO5AGiBV0rfpRh5gg7i8RrT12E9j6XwKoe3xJz1khDnPc65P5f7CJcNJ9A8bj7Al5K4jYGxz+4Q+n0YzSllXPit/Vz/iW5jFdlP6CTIgUVwvIoGEL2sS4cqqqSpCDKHSeiXh9CtMsktc6YyrSN+8mQbBvoSSew18r/vC07iQiaYkClcs7jIPq9tuilL//2uR9kWn5jsp8zHKVjmXuLtHDhM9lObZGCVJwdlN2KDKTh276u/pzQ1s5u8z/ARtK26N8e5w8mNlGcHcHfwyhjfEQurvrnkqYH37+12U3jGk5YNHGyOPcwIDAQAB"
     private val imei: String by lazy(mode = LazyThreadSafetyMode.SYNCHRONIZED) { generateIMEI() }
     private val token: String by lazy(mode = LazyThreadSafetyMode.SYNCHRONIZED) { fetchToken() }
-    private var userId = "-1"
-    private var lastUsedTime = ""
+    private var userId: String = preferences.getString(USER_ID_PREF, null) ?: "-1"
+    private val lastUsedTime: String by lazy(mode = LazyThreadSafetyMode.SYNCHRONIZED) { generateLastUsedTime() }
```
Comment (stevenyomi) [inline src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt]:
```suggestion
    private val lastUsedTime: String by lazy { generateLastUsedTime() }
```

The default mode *is* synchronized.

File: src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt [hunk 5]
```diff
@@ -35,28 +43,37 @@ import javax.crypto.Cipher
...
+
+    override val client: OkHttpClient = network.client
+        .newBuilder()
```
Comment (stevenyomi) [inline src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt:68]:
```suggestion
        .newBuilder()
        .apply { interceptors().removeAll { it.javaClass.simpleName == "BrotliInterceptor" } }
```

Just remove the problematic interceptor instead of handling gzip in your interceptor.

File: src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt (hunk 1 above)
Comment (stevenyomi) [reply src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt:152]: I think it's okay to back these chunks of code up.

Comment (stevenyomi) [reply src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt:173]: I think it's okay to back these chunks of code up.

**Review by stevenyomi — APPROVED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
