### PR TITLE
HolyManga: Fix chapter title

### LINKED ISSUE #7160: HolyManga: published date in chapter title
### Source information

HolyManga 1.4.11

### Source language

English

### Steps to reproduce

Open any manga

### Expected behavior

No date in chapters titles

### Actual behavior

Screenshot_20250113_170956_Mihon

### Mihon/Tachiyomi version

0.17.1

### Android version

13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #7160 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt [hunk 1]
```diff
@@ -1,11 +1,26 @@
...
 class HolyManga : FMReader(
     "HolyManga",
     "https://w34.holymanga.net",
     "en",
 ) {
     override val versionId = 2
+
+    override fun chapterFromElement(element: Element): SChapter {
+        return chapterFromElement(element, "")
+    }
```
Comment (dngonz) [inline src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt]: You don't really need to override this fun

Comment (lordenecromante) [reply src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt]: That's true. Actually, the second override fun was just a regular fun, and the first one was only there to set the default value as "", but I’ve already removed it

File: src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt [hunk 2]
```diff
@@ -1,11 +1,22 @@
...
+import org.jsoup.nodes.Element
 
 class HolyManga : FMReader(
     "HolyManga",
     "https://w34.holymanga.net",
     "en",
 ) {
     override val versionId = 2
+
+    override fun chapterFromElement(element: Element, mangaTitle: String): SChapter {
```
Comment (vetleledaal) [inline src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt]: Can't you just set `chapterUrlSelector` to an empty string? Instead of overriding this function.

In the FMReader class it would take the `else` branch and get the title from an attribute instead:
```kt
open fun chapterFromElement(element: Element, mangaTitle: String = ""): SChapter {
  return SChapter.create().apply {
    if (chapterUrlSelector != "") {
      // ...
    } else {
      element.let {
        setUrlWithoutDomain(it.attr("abs:href"))
        name = element.attr(chapterNameAttrSelector).substringAfter("$mangaTitle ")
      }
    }
    // ...
  }
}
```

Comment (lordenecromante) [reply src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt]: You're absolutely right. Fix it.

**Review by vetleledaal — APPROVED** [review]
