### PR TITLE
SchaleNetwork: Fix http 400

### LINKED ISSUE #6053: Koharu: domain changed
### Source information

SchaleNetwork 1.4.10

### Source language

English

### Source new URL

https://niyaniya.moe/

### Other details

_No response_

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #6053

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt [hunk 1]
```diff
@@ -62,9 +62,22 @@ class Koharu(
 
     private fun remadd() = preferences.getBoolean(PREF_REM_ADD, false)
 
-    override fun headersBuilder() = super.headersBuilder()
-        .add("Referer", "$baseUrl/")
-        .add("Origin", baseUrl)
+    private fun getDomain(): String {
+        try {
+            val host = client.newCall(GET(baseUrl, headers)).execute().request.url.host
```
Comment (AwkwardPeak7) [inline src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt]: disable redirect on a new client and use that, get url from the `location` header

[example](https://github.com/keiyoushi/extensions-source/blob/1817e30e3320fada76605c1866f9714c1ce97610/src/ko/blacktoon/src/eu/kanade/tachiyomi/extension/ko/blacktoon/BlackToon.kt#L37-L38)

**Review by AwkwardPeak7 — APPROVED** [review]
