### PR TITLE
TruyenHentai18: Fix follow new code, update domain

### LINKED ISSUE #12930: Truyện Hentai 18+ changed code and domain
### Source information

Truyen Hentai 18+ 1.4.7

### Source language

Vietnamese

### Source new URL

https://truyenhentai18.net

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FiorenMas**
Closed https://github.com/keiyoushi/extensions-source/issues/12930

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt [hunk 1]
```diff
@@ -38,147 +31,194 @@ class TruyenHentai18 : ParsedHttpSource() {
...
+        }
+        val hasNextPage = document.selectFirst("ul.pagination a[rel=next]") != null
+        return MangasPage(mangas, hasNextPage)
     }
 
-    override fun popularMangaNextPageSelector() = "div.overflow-x-scroll div button"
+    private fun mangaFromElement(element: Element): SManga = SManga.create().apply {
+        val linkElement = element.selectFirst("a")!!
+        setUrlWithoutDomain(linkElement.absUrl("href"))
+        title = element.selectFirst("h2")?.text() ?: ""
```
Comment (vetleledaal) [inline src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt]: Title is not optional.
```suggestion
        title = element.selectFirst("h2")!!.text()
```

File: src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt [hunk 2]
```diff
@@ -38,147 +31,194 @@ class TruyenHentai18 : ParsedHttpSource() {
...
+    override fun getMangaUrl(manga: SManga) = baseUrl + manga.url
+
+    override fun mangaDetailsRequest(manga: SManga): Request {
+        return GET(getMangaUrl(manga), headers)
+    }
+
+    override fun mangaDetailsParse(response: Response): SManga = SManga.create().apply {
+        val document = response.asJsoup()
+
+        title = document.selectFirst("h1")?.text() ?: ""
```
Comment (vetleledaal) [inline src/vi/truyenhentai18/src/eu/kanade/tachiyomi/extension/vi/truyenhentai18/TruyenHentai18.kt]:
```suggestion
        title = document.selectFirst("h1")!!.text()
```

**Review by AwkwardPeak7 — APPROVED** [review]
