### PR TITLE
fix(fr/scanmanga): fix headers and update endpoints

### LINKED ISSUE #12059: Scan-Manga : HTTP 404 and Impossible to Bypass Cloudflare Protection
### Source information

Scan-Manga

### Source language

French 

### Steps to reproduce

1. Open the Scan-manga extension.
2. Open any manhwa or manga.
3. The chapters don’t load.

### Expected behavior

There should not be any issue with: HTTP 404, view the website in WebView.

### Actual behavior

when you click on any manga , manhwa etc , the chapter list doesn’t load and shows: ‘HTTP 404, view the website in WebView.’
Normally, the list of chapters should appear.”

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 16

### Other details

Image
Image
Image
Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Starmania**
Closes #12059

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt [hunk 1]
```diff
@@ -175,6 +200,10 @@ class ScanManga : HttpSource() {
     }
 
     private fun dataAPI(data: String, idc: Int): UrlPayload {
+        if (data.contains("error")) {
+            error("Received error response from data API: ${Regex("\\s+").replace(data, " ").trim()}")
```
Comment (vetleledaal) [inline src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt]: Move regex to class.

Use `"""` to avoid escaping both for the sake of Kotlin and the regex.

**Review by AwkwardPeak7 — APPROVED** [review]
