### PR TITLE
Jinmantiantang: fixed empty date string issue

### LINKED ISSUE #8315: Jinman Tiantang Unable to load chapter list
### Source information

Jinman Tiantang 1.4.46

### Source language

Chinese

### Steps to reproduce

1.Click on a comic with multiple chapters
2. Unable to load chapter list with prompt ParseException: Unparseable date: "''

### Expected behavior

Chapter list should be loaded

### Actual behavior

Unable to load chapter list with prompt ParseException: Unparseable date: "''

### Mihon/Tachiyomi version

Komikku 1.13.0

### Android version

Android15

### Other details

If the comic has more than one chapter, the list will not load and the following prompt will appear. There is no problem loading a comic with only one chapter.

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lamaxama**
Closes #8315

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by kpvc15** [comment]
如何更新?要等extension更新嗎?

**Comment by Smol-Ame** [comment]
@kpvc15 Yes, you have to wait for a future extension update for this fix. Pull requests are proposed fixes/changes to the extension repo, and will need review & approval first before anything is merged in. Wait patiently or migrate to a different source.

File: src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt [hunk 1]
```diff
@@ -230,7 +230,10 @@ class Jinmantiantang : ParsedHttpSource(), ConfigurableSource {
     override fun chapterFromElement(element: Element): SChapter = SChapter.create().apply {
         url = element.select("a").attr("href")
         name = element.select("a li").first()!!.ownText()
-        date_upload = sdf.parse(element.select("a li span.hidden-xs").text().trim())?.time ?: 0
+        date_upload = element.select("a li span.hidden-xs").text().trim()
+            .takeIf { it.isNotBlank() }
+            ?.let { sdf.parse(it)?.time }
+            ?: 0
```
Comment (AwkwardPeak7) [inline src/zh/jinmantiantang/src/eu/kanade/tachiyomi/extension/zh/jinmantiantang/Jinmantiantang.kt]:
```suggestion
        date_upload = sdf.tryParse(element.select("a li span.hidden-xs").text())
```
`import keiyoushi.utils.tryParse`

also nitpick: rename sdf to dateFormat or similar

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by BabyNurse020517** [comment]
I'm still experiencing a Cloudflare loop after the update. Is anyone else having this issue?

**Comment by Smol-Ame** [comment]
@BabyNurse020517 Cloudflare is mostly a personal issue, refer to the Cloudflare guide: https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare

Otherwise, come to the Keiyoushi Discord support channel instead for basic questions/issues.

**Comment by BabyNurse020517** [comment]
> @BabyNurse020517 Cloudflare is mostly a personal issue, refer to the Cloudflare guide: https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare
> 
> Otherwise, come to the Keiyoushi Discord support channel instead for basic questions/issues.

But I’ve tried on three different devices with different user agents, and it still fails
