### PR TITLE
Holymanga : fixes chapters date parsing

### LINKED ISSUE #7861: Holymanga : error while refreshing chapters
### Source information

Holymanga 1.4.12

### Source language

English

### Steps to reproduce

* Try to refresh chapters on a manga
* got NumberformatException  on a date (i.e 2025-02-26)

I got this with all mangas

### Expected behavior

no error :D

### Actual behavior

* Try to refresh chapters on a manga
* got NumberformatException  on a date (i.e 2025-02-26)

I got this with all mangas

### Mihon/Tachiyomi version

0.17.1

### Android version

14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MikeZeDev**
Closes https://github.com/keiyoushi/extensions-source/issues/7861
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt [hunk 1]
```diff
@@ -1,13 +1,35 @@
...
+                }
+            } else {
+                element.let {
+                    setUrlWithoutDomain(it.attr("abs:href"))
+                    name = element.attr(chapterNameAttrSelector).substringAfter("$mangaTitle ")
+                }
+            }
+            date_upload = element.select(chapterTimeSelector).let { if (it.hasText()) parseAbsoluteDate(it.text()) else 0 }
+        }
+    }
```
Comment (vetleledaal) [inline src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt]: Call the super method?

https://github.com/keiyoushi/extensions-source/blob/5988c02c57f04d356a2efbe25d0a1e3d25bc02d9/src/vi/doctruyen3q/src/eu/kanade/tachiyomi/extension/vi/doctruyen3q/DocTruyen3Q.kt#L89-L93

https://github.com/keiyoushi/extensions-source/blob/5988c02c57f04d356a2efbe25d0a1e3d25bc02d9/src/en/xoxocomics/src/eu/kanade/tachiyomi/extension/en/xoxocomics/XoxoComics.kt#L106-L110

File: src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt [hunk 2]
```diff
@@ -1,13 +1,24 @@
...
+    SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH),
 ) {
     override val versionId = 2
 
     override val chapterUrlSelector = ""
+
+    override fun chapterFromElement(element: Element, mangaTitle: String): SChapter {
+        return super.chapterFromElement(element).apply {
+            date_upload = element.select(chapterTimeSelector).let { if (it.hasText()) parseAbsoluteDate(it.text()) else 0 }
+        }
```
Comment (AwkwardPeak7) [inline src/en/holymanga/src/eu/kanade/tachiyomi/extension/en/holymanga/HolyManga.kt]:
```suggestion
        return super.chapterFromElement(element, mangaTitle).apply {
            date_upload = element.select(chapterTimeSelector).text().let { parseAbsoluteDate(it) }
        }
```

**Review by AwkwardPeak7 — APPROVED** [review]
