### PR TITLE
MangaTale: Fix pages not found in downloads

### LINKED ISSUE #3060: MangaTale 1.4.32 "Page not Found" Error
### Source information

MangaTale 1.4.32

### Source language

Indonesia 

### Steps to reproduce

1. Download any their project comic latest chapter 
2. Read any chapter, chapter immediately close and "Page not Found" show in the bottom
Screenshot_2024-05-17-01-59-01-07_551f7f0ca926862b368845ce7ee433aa

### Expected behavior

Chapter image show up and Read smoothly downloaded chapter without loading

### Actual behavior

Chapter immediately close and "page not found" error show even though it has been downloaded

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 13

### Other details

1. There are no errors in the chapter at all when read online or from webview

2. This error only occurs with the comics they work on.  Mirrored comics don't have this problem when downloaded

3. The only chapters that have this error are the chapters released in 2024, 2023 and below do not have this error

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #3060 

Idk if should handle other image types, I only see jpg images in the site

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/MangaTale.kt [hunk 1]
```diff
@@ -2,13 +2,27 @@ package eu.kanade.tachiyomi.extension.id.mangatale
...
 import org.jsoup.nodes.Document
 
 class MangaTale : MangaThemesia("MangaTale", "https://mangatale.co", "id") {
 
     override val client: OkHttpClient = super.client.newBuilder()
         .rateLimit(20, 5)
+        .addInterceptor { chain ->
+            val request = chain.request()
+            val response = chain.proceed(request)
+            if (response.headers("Content-Type").contains("application/octet-stream") && response.request.url.toString().endsWith(".jpg")) {
```
Comment (AwkwardPeak7) [inline src/id/mangatale/src/eu/kanade/tachiyomi/extension/id/mangatale/MangaTale.kt]: you can convert response body to image/jpeg to make sure all other image types get covered

[example](https://github.com/keiyoushi/extensions-source/blob/08f4f9a18318f4f472ab868c7aa84614ca94252b/src/all/tappytoon/src/eu/kanade/tachiyomi/extension/all/tappytoon/Tappytoon.kt#L34-L46)

**Review by AwkwardPeak7 — APPROVED** [review]
