### PR TITLE
[pixiv] Fix user search + filters, add image quality setting

### LINKED ISSUE #481: Pixiv: Add option to load preview image (smaller size image)
### Source name

Pixiv

### Source language

All

### Describe your suggested feature

The current implementation loads full size image, which some individual image can be multiple of megabytes.

By adding option to load preview image instead, it can reduce the loading times.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #1968: pixiv artist search based on user ID
### Source name

Pixiv

### Source language

English/Multi

### Describe your suggested feature

current artist search is non-fuctional, please correct me if i don't quite catch how the feature works. but isn't it supposed to search for artworks caption then narrow the results down to match artist/user name? if so, i'm still unable to search for specific artist works.
wouldn't it be nice also if we could search for artist from the filter menu without a search query and it would return their works, currently doing exactly this would yield no results.

### Other details

Screenshot_2024-03-19-04-53-11-295_eu kanade tachiyomi sy
Screenshot_2024-03-19-04-53-01-351_eu kanade tachiyomi sy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by colblitz**
Changes:

 * Change username search to use /search/users endpoint (closes #1968, #5195)
 * Add setting for image quality and get urls based on setting (closes #481)
 * Add back deeplink support
 * Add some smarts when getting filtered results (and avoid searches that spin forever)
 * Make user filter case insensitive
 * Rename some variable shadowing, minor formatting things

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

Testing:

Tested on Android with Mihon

 * verified popular/latest still work
 * verified deeplinks work (for user and aid)
 * verified user filter works
 * verified user filter + search works

### CODE REVIEW

File: src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt [hunk 1]
```diff
@@ -16,15 +20,21 @@ import okhttp3.HttpUrl.Companion.toHttpUrl
...
+class Pixiv(override val lang: String) : ConfigurableSource, HttpSource() {
     override val name = "Pixiv"
     override val baseUrl = "https://www.pixiv.net"
     override val supportsLatest = true
 
     private val json: Json by injectLazy()
 
+    private val preferences: SharedPreferences by lazy {
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
+    }
```
Comment (AwkwardPeak7) [inline src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt]:
```suggestion
    private val preferences: SharedPreferences by getPreferencesLazy()
```
need to import

**Review by AwkwardPeak7 — APPROVED** [review]
