### PR TITLE
ReadAllComics: fix search & missing chapters

### LINKED ISSUE #13706: ReadAllComics: `No results found` error
### Source information

ReadAllComics 1.4.6 

### Source language

English

### Steps to reproduce

- Open extension in sources tab. 
- No comic is listed

Image

### Expected behavior

Comic list shall be shown

### Actual behavior

No comic is shown

### Mihon/Mihon fork version

mihon App version: 0.19.4

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13739: ReadAllComics Unable to view all chapters and Missing descriptions
### Source information

ReadAllComics 1.4.6

### Source language

English

### Steps to reproduce

1. Select any title from Readallcomics source.
2. Description for the title from the source page is missing 
3. Not all Chapter titles are listed when checking the title

### Expected behavior

1. The title should have the description related to the title which was previously available 
2. All chapters under the title should be visible that is present in the source

Image

### Actual behavior

1. There are no more descriptions even though they are present in the source 
2. The titles only shows about 10 of the latest chapters from the source 

Image

Image

### Mihon/Mihon fork version

Tachiyomi stable 0.15.2

### Android version

Android 16

### Other details

Possible cause for descriptions: Source has been changed so that the description is only visible after interacting with the "show description" option

Possible cause for Missing Chapters: Source modified to only view the latest 10 Chapters and allows you to access the rest of the Chapters by clicking the "View full list" option

Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13740: ReadAllComics Bug in Searching Titles
### Source information

ReadAllComics 1.4.6

### Source language

English

### Steps to reproduce

1. Enter the extension and search for any title
2. The search results contains duplicates and random singular chapters 
3. Missing search results from the source

### Expected behavior

The search should show all the related titles for the search term 

### Actual behavior

1. The search results in duplicates of some titles and random singular chapters from the titles.
2. Not all the search results from the source is visible 

Image

### Mihon/Mihon fork version

Tachiyomi stable 0.15.2

### Android version

Android 16

### Other details

The bug may be related to the changes in the source end where the searches now the show the images of the titles along with the latest Chapter of the title
Also the change of displaying the search results in pages instead of displaying in one page as text links

Image

Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by al-shamiry**
Fixes:

1. Migrate from ParsedHttpSource to HttpSource
2. Popular page was showing `No results found`. Now it asks the user to use the search.
3. Search was showing repeated and broken results. Now it shows the right results with proper pagination.
4. Series description was not showing. Now it shows and is properly sectioned.

Closes #13706
Closes #13739
Closes #13740

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 1]
```diff
@@ -31,125 +28,83 @@ class ReadAllComics : ParsedHttpSource() {
...
-        for (i in (((page - 1) * 24)..endRange)) {
-            mangas.add(
-                searchMangaFromElement(searchPageElements[i]),
-            )
-        }
-
-        return MangasPage(mangas, endRange < searchPageElements.lastIndex)
+    private fun mangaFromElement(element: Element) = SManga.create().apply {
+        val titleAnchor = element.selectFirst("a.cat-title")!!
+        setUrlWithoutDomain(titleAnchor.attr("href"))
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]:
```suggestion
        setUrlWithoutDomain(titleAnchor.absUrl("href"))
```

(yes, you should use both)

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 2]
```diff
@@ -31,125 +28,83 @@ class ReadAllComics : ParsedHttpSource() {
...
+        title = titleAnchor.text()
+        thumbnail_url = element.selectFirst("img.book-cover")?.attr("src")
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]:
```suggestion
        thumbnail_url = element.selectFirst("img.book-cover")?.absUrl("src")
```

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 3]
```diff
@@ -31,125 +28,83 @@ class ReadAllComics : ParsedHttpSource() {
...
+    override fun mangaDetailsParse(response: Response) = SManga.create().apply {
+        val archive = response.asJsoup().selectFirst(".description-archive")!!
+        title = archive.selectFirst("h1")!!.text()
+        thumbnail_url = archive.selectFirst("p img")?.attr("abs:src")
+        val infoStrongs = archive.select(".b > p strong")
+        genre = infoStrongs.firstOrNull()?.text()
+        author = infoStrongs.lastOrNull()?.text()
+        description = archive.selectFirst("#hidden-description")?.also { el ->
+            el.select("hr").prepend("\\n")
+        }?.text()?.replace("\\n", "\n\n")
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]: Would `.wholeText().trim()` help here?

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 4]
```diff
@@ -31,125 +28,83 @@ class ReadAllComics : ParsedHttpSource() {
...
-                if (vol?.tagName() == "span") {
-                    append(vol.text(), "\n")
-                }
-                append(element.text())
-            }
+    // Chapters
+
+    override fun chapterListParse(response: Response): List<SChapter> = response.asJsoup().select(".list-story a").map { element ->
+        SChapter.create().apply {
+            setUrlWithoutDomain(element.attr("href"))
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]:
```suggestion
            setUrlWithoutDomain(element.absUrl("href"))
```

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt [hunk 5]
```diff
@@ -31,125 +28,83 @@ class ReadAllComics : ParsedHttpSource() {
...
-        val year = name.substringAfterLast('(').substringBefore(')')
-        date_upload = dateFormat.tryParse("$year-1-1")
+    override fun pageListParse(response: Response): List<Page> = response.asJsoup().select("body img:not(div[id=logo] img)").mapIndexed { idx, element ->
+        Page(idx, imageUrl = element.attr("abs:src"))
     }
 
-    override fun pageListParse(document: Document): List<Page> = document.select("body img:not(body div[id=\"logo\"] img)").mapIndexed { idx, element ->
-        Page(idx, "", element.attr("abs:src"))
-    }
+    override fun imageUrlParse(response: Response) = ""
```
Comment (vetleledaal) [inline src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]:
```suggestion
    override fun imageUrlParse(response: Response) = throw UnsupportedOperationException()
```

File: src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt (hunk 1 above)
Comment (al-shamiry) [reply src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]: I see we already have `.attr("abs:src")` on lines 72 & 95. Can I use that instead? (`.attr("abs:href")`)

Comment (vetleledaal) [reply src/en/readallcomicscom/src/eu/kanade/tachiyomi/extension/en/readallcomicscom/ReadAllComics.kt]: I meant for `setUrlWithoutDomain` + `absUrl`. It might seem redundant at first, but you delegate resolving relative paths to Jsoup, which has the full context.

Both `absUrl("...")` and `attr("abs:...")` are fine. You can use either.

**Review by vetleledaal — APPROVED** [review]
