### PR TITLE
MangaBox: Fix no pages found error

### LINKED ISSUE #8789: Mangabox (Manganato, Mangabat, Mangakakalot): No pages found error
### Source information

Mangabat 1.4.13

### Source language

English

### Steps to reproduce

1. Tap on any manga with mangabat extension as the source
2. Tap on any chapter
3. No pages found

### Expected behavior

Manga should've loaded normally

### Actual behavior

No pages found

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lamaxama**
Closes: #8789

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/mangabox/src/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt [hunk 1]
```diff
@@ -346,11 +346,11 @@ abstract class MangaBox(
     }
 
     override fun pageListParse(document: Document): List<Page> {
-        val element = document.select("head > script").lastOrNull()
+        val content = document.selectFirst("script:containsData(cdns =)")?.data()
```
Comment (vetleledaal) [inline lib-multisrc/mangabox/src/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt]: Seems brittle. Could you do something like this? Needs testing:
```suggestion
        val content = document.select("script:containsData(cdns =)").joinToString("\n") { it.data() }
```

Mostly to protect against them moving script tags around.

File: lib-multisrc/mangabox/src/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt [hunk 2]
```diff
@@ -346,11 +349,10 @@ abstract class MangaBox(
     }
 
     override fun pageListParse(document: Document): List<Page> {
-        val element = document.select("head > script").lastOrNull()
-            ?: return emptyList()
+        val content = document.select("script:containsData(cdns =)").joinToString("\n") { it.data() }
         val cdns =
-            extractArray(element.html(), "cdns") + extractArray(element.html(), "backupImage")
-        val chapterImages = extractArray(element.html(), "chapterImages")
+            extractArray(content, "cdns") + extractArray(content, "backupImage")
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangabox/src/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt:354]: the content script can only contains `cdns =`, consider updating the selector to also include this `backupImage`, or maybe just get all script tags?

File: src/en/manganelo/build.gradle [hunk 3]
```diff
@@ -3,7 +3,7 @@ ext {
     extClass = '.Manganato'
     themePkg = 'mangabox'
     baseUrl = 'https://www.natomanga.com'
-    overrideVersionCode = 5
+    overrideVersionCode = 6
```
Comment (AwkwardPeak7) [inline src/en/manganelo/build.gradle]: bump the multisrc instead

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/mangabox/src/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt (hunk 2 above)
Comment (lamaxama) [reply lib-multisrc/mangabox/src/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt:354]: cdns, backupImage and chapterImages usually appear together, and I'm using `cdns =`, the current match is no problem.
to be honest, if they want to break the extension, they have a hundred ways.

**Review by AwkwardPeak7 — APPROVED** [review]
