### PR TITLE
baozimhorg: fix illegal State Exception & more

### LINKED ISSUE #9543: GoDa (zh.baozimhorg) - illegal State Exception
### Source information

GoDa (zh.baozimhorg) - 1.4.33

### Source language

Chinese

### Steps to reproduce

1. search any manga
2. it will show "illegalStateException: Check failed."
3. you can always press refresh to reproduce this issue as well

### Expected behavior

able to refresh without any error message

### Actual behavior

This happened when try to go any manga chapter page.

### Mihon/Tachiyomi version

Stable 0.18.0 (2025/3/10 06:40)

### Android version

Andriod 15

### Other details

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dodieboy**
fix #9543

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by dodieboy** [comment]
btw do i need to update extVersionCode if i updated baseVersionCode?

**Comment by stevenyomi** [comment]
SInce you updated baseVersionCode, each override automatically has incremented versionCode. You should not update overrideVersionCode individually.

File: lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt [hunk 1]
```diff
@@ -80,11 +80,13 @@ open class GoDa(
...
     private fun Element.getMangaId() = selectFirst("#mangachapters")!!.attr("data-mid")
 
+    open val elementCheck: Int = 6
+
     override fun mangaDetailsParse(response: Response) = SManga.create().apply {
         val document = response.asJsoup().selectFirst("main")!!
         val titleElement = document.selectFirst("h1")!!
         val elements = titleElement.parent()!!.parent()!!.children()
-        check(elements.size == 6)
+        check(elements.size == elementCheck)
```
Comment (stevenyomi) [inline lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]:
```suggestion
        check(elements[4].tagName() == "p")
```

The element count varies across mirrors, as the linked issue's comments discovered. Let's change it to a more stable check. Remove the `elementCheck` field.

**Review by stevenyomi — CHANGES_REQUESTED** [review]

**Comment by dodieboy** [comment]
If goda api have author and all genre, we will not need that element checker
image

File: lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt (hunk 1 above)
Comment (dodieboy) [reply lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: btw, I move the check to below status since status do not use elements, prevent status from breaking when check is false

Comment (stevenyomi) [reply lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: `check()` will throw an exception. Should the page structure change, moving it below will not make the status data return successfully.

Comment (dodieboy) [reply lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: O, good to know, I still very new to android coding. Decided to do it because when it throw "illegal State Exception" error, the status is showing unkown when it should not affect it.

File: lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt [hunk 2]
```diff
@@ -81,17 +81,20 @@ open class GoDa(
...
-        val elements = titleElement.parent()!!.parent()!!.children()
-        check(elements.size == 6)
+        val elements = document.children()
 
         title = titleElement.ownText()
         status = when (titleElement.child(0).text()) {
             "連載中", "Ongoing" -> SManga.ONGOING
             "完結" -> SManga.COMPLETED
+            "停止更新" -> SManga.ON_HIATUS
+            "休刊" -> SManga.CANCELLED
```
Comment (stevenyomi) [inline lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: 休刊 is "on hiatus".

停止更新 can be mapped to "cancelled".

**Review by stevenyomi — CHANGES_REQUESTED** [review]

File: lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt (hunk 2 above)
Comment (dodieboy) [reply lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: but from the manga that have see have those status, 停止更新 is for manga that is waiting for new seasion and 休刊 is manga that got cancel

Comment (dodieboy) [reply lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: here is a example: it stop updating/transalting due to personal reason and is mark as 休刊
https://m.baozimh.one/manga/qingchunqishilu-js919509

and this is on 停止更新 as the season ended
https://m.baozimh.one/manga/gelougongzhu-nr32104

Comment (stevenyomi) [reply lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: The former one is indeed "on hiatus/休刊" (artist taking a break for personal reasons).

The latter one is where the scanlator team discontinued translating new chapters. You can search the internet to see there was chapter 71 way back in 2023. Mapping it to "cancelled" is the best choice, although it originally refers to the artist/publisher cancelling the series.

Comment (dodieboy) [reply lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt]: my bad, it is so confusing as to me 休刊 mean suspended but base on the below manga 停止更新 mean cancel, so you are right, will make the change now
https://m.baozimh.one/manga/shenwuzhiling-suoyiwenhua

**Review by stevenyomi — APPROVED** [review]
