### PR TITLE
[RU]Desu serialization

### LINKED ISSUE #2815: Desu.me NullPointerException
### Source information

Desu 1.4.23

### Source language

Russian

### Steps to reproduce

1. Open source from sources tab
2. Got `NullPointerException: null`
same when refresh exiting chapter in library

### Expected behavior

When browsing source must populate with items
When refreshing existing item from library no error happened

### Actual behavior

Instead of list of items got `NullPointerException: null` when browsing source
When refreshing existing same error appears 

### Mihon/Tachiyomi version

0.15.3

### Android version

10

### Other details

https://github.com/keiyoushi/extensions-source/blob/f06813aa905bdd745525be4c1b3a0f5c45c2a74d/src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt#L106

Checked actual api, looks like instead of `adult` field `age_limit` used now

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by e-shl**
I will continue serialization sometime later
Closes https://github.com/keiyoushi/extensions-source/issues/2815
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt [hunk 1]
```diff
@@ -119,45 +98,37 @@ class Desu : ConfigurableSource, HttpSource() {
...
-
-        status = when (obj["trans_status"]!!.jsonPrimitive.content) {
-            "continued" -> SManga.ONGOING
-            "completed" -> SManga.COMPLETED
-            else -> when (obj["status"]!!.jsonPrimitive.content) {
-                "ongoing" -> SManga.ONGOING
-                "released" -> SManga.COMPLETED
-                //  "copyright" -> SManga.LICENSED  Hides available chapters!
-                else -> SManga.UNKNOWN
+        val o = this
```
Comment (AwkwardPeak7) [inline src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt]: you can just omit `this` when accessing members, like `image.original` instead of `this.image.original`;

so no need for this

File: src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/dto/Dto.kt [hunk 2]
```diff
@@ -0,0 +1,51 @@
+package eu.kanade.tachiyomi.extension.ru.desu.dto
+
+import kotlinx.serialization.Serializable
+@Serializable
```
Comment (AwkwardPeak7) [inline src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/dto/Dto.kt]:
```suggestion
import kotlinx.serialization.Serializable

@Serializable
```

File: src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/dto/Dto.kt [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+data class SeriesWrapperDto<T>(
```
Comment (AwkwardPeak7) [inline src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/dto/Dto.kt]: conside removing `data` modifier; simple classes should be fine

File: src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/dto/Dto.kt
Comment (AwkwardPeak7) [inline src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/dto/Dto.kt:1]: put this file in the same directory as the source class

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt [hunk 4]
```diff
@@ -62,33 +62,8 @@ class Desu : ConfigurableSource, HttpSource() {
...
-        } else {
-            obj["name"]!!.jsonPrimitive.content
-                .split(" / ")
-                .first()
-        }
-        thumbnail_url = obj["image"]!!.jsonObject["original"]!!.jsonPrimitive.content
-
-        val ratingValue = obj["score"]!!.jsonPrimitive.floatOrNull ?: 0F
+    private fun MangaDetDto.toSManga(genresStr: String? = ""): SManga {
+        val ratingValue = score!!
```
Comment (AwkwardPeak7) [inline src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt:66]: consider not making them nullable in the dto, since you are using non null assertion anyway

File: src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt [hunk 5]
```diff
@@ -119,45 +94,37 @@ class Desu : ConfigurableSource, HttpSource() {
...
+                name
+            } else {
+                russian
+            } + "\n" + ratingStar + " " + ratingValue + " (голосов: " +
+                score_users + ")\n" + altName + o.description
+            genre = ("$category, $rawAgeStop, $genresStr").split(", ").filter { it.isNotEmpty() }.joinToString { it.trim() }
+            status = when (trans_status) {
+                "continued" -> SManga.ONGOING
+                "completed" -> SManga.COMPLETED
+                else -> when (o.status) {
```
Comment (AwkwardPeak7) [inline src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt]: you can access the conflicting dto values using => `this@DtoName.status`

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt (hunk 4 above)
Comment (AwkwardPeak7) [reply src/ru/desu/src/eu/kanade/tachiyomi/extension/ru/desu/Desu.kt:66]: I meant removing the nullability from the dtos (`val something: String?` => `val something: String`)
you can do it in a future pull request

**Review by AwkwardPeak7 — APPROVED** [review]
