### PR TITLE
Kagane: Fix image loading, add more filters, fix NSFW

### LINKED ISSUE #10820: Kagane: add source/tag/genre filters
### Source name

Kagane

### Source language

English 

### Describe your suggested feature

Currently (and even in the recently made pr) the addition on filtering has not been added. Adding this option would be really good.

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11013: Kagane: add scanlator filter option
### Source name

Kagane

### Source language

English

### Describe your suggested feature

Kagane added an option to show or hide scanlators. This should be added as an option  to the app as well

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11158: Kagane: NSFW toggle no longer functions
### Source information

Kagane 1.4.6

### Source language

English

### Steps to reproduce

1. Open source settings
2. Turn on "Show NSFW entries"
3. Browse

### Expected behavior

NSFW entries should be shown.

### Actual behavior

NSFW entries remain hidden

### Mihon/Tachiyomi version

TachiyomiSY 1.12.0 (Based on Mihon 0.18.0)

### Android version

Android 15

### Other details

This issue started very recently, as it was working within the past week.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11160: Kagane: Unable to decrypt data
### Source information

Kagane 1.4 6

### Source language

English

### Steps to reproduce

1. Opened a Manhwa
2. Clicked the specific Chapter
3. Unable to decrypt data

Image

### Expected behavior

This should happen you can see the content. (This is an example of a downloaded mahwa chapter)

Image

### Actual behavior

This happened instead no image.

Image

### Mihon/Tachiyomi version

0.19.1

### Android version

Android 14

### Other details

Same with downloading the chapter "Unable to decrypt data" when I clicked the webview i'm also gettig an error

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by cuong-tran**
Close #11160
Close #11158
Close #10820
Close #11013

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Filters.kt [hunk 1]
```diff
@@ -0,0 +1,454 @@
...
+                    }
+                    put("match_all", false)
+                }
+            }
+        }
+    }
+}
+
+internal interface JsonFilter {
+    fun addToJonObject(builder: JsonObjectBuilder)
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Filters.kt]:
```suggestion
    fun addToJsonObject(builder: JsonObjectBuilder)
```

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Filters.kt [hunk 2]
```diff
@@ -0,0 +1,454 @@
...
+}
+
+private val GENRES by lazy {
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Filters.kt]: no need for lazy

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 3]
```diff
@@ -236,7 +228,7 @@ class Kagane : HttpSource(), ConfigurableSource {
         }
 
         val pages = (0 until pageCount.toInt()).map { page ->
-            val pageUrl = "$apiUrl/api/v1/books".toHttpUrl().newBuilder().apply {
+            val pageUrl = "$imageApiUrl/api/v1/books".toHttpUrl().newBuilder().apply {
```
Comment (FourTOne5) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt]: no need to hardcode the url

Image

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt [hunk 4]
```diff
@@ -172,6 +160,10 @@ class Kagane : HttpSource(), ConfigurableSource {
                         }
                     }
 
+                    is ScanlationsFilter -> {
+                        addQueryParameter("scanlations", filter.state.toString())
```
Comment (AwkwardPeak7) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Kagane.kt:169]: probably should pass this filter from popular and latest too, so the parameter is set.

**Review by vetleledaal — APPROVED** [review]

**Comment by iBlackSugarLatte** [comment]
Thank you so much 🤗 You guus are the best 👏
