### PR TITLE
FuzzyDoodle: Make CloudRecess a multisrc and add/fix some sources

### LINKED ISSUE #1813: [Source Request] FleksyScans
### Source name

FleksyScans

### Source link

https://flexscans.com/

### Source language

English

### Other details

18+/NSFW=Yes

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #2090: Scylla Scans website is back up
### Source information

Scylla Scans 1.4.9

### Source language

English 

### Steps to reproduce

Extension not loading at all

### Expected behavior

Should load

### Actual behavior

Should load

### Mihon/Tachiyomi version

Tachij2k 1.7.4

### Android version

Android 14

### Other details

Website has changed their formating too from previous formating.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
- moved Scylla Scans (en) to this multisrc
- add Fleksy scans (en)
- move HentaiSlayer (ar) to this multisrc
- remove CloudRecess (en) as site appears to be down, can be added again
- move LelScan-VF (fr) to this multisrc

closes #2090
closes #1813

Need a better name for the theme, suggestions are welcome.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/cloudrecess/src/eu/kanade/tachiyomi/multisrc/cloudrecess/CloudRecess.kt [hunk 1]
```diff
@@ -0,0 +1,294 @@
...
+            latestHomePageRequest(page)
+        } else {
+            latestPageRequest(page)
+        }
+
+    protected open fun latestHomePageRequest(page: Int) =
+        GET("$baseUrl/?page=$page", headers)
+
+    protected open fun latestPageRequest(page: Int) =
+        GET("$baseUrl/latest?page=$page")
```
Comment (vetleledaal) [inline lib-multisrc/cloudrecess/src/eu/kanade/tachiyomi/multisrc/cloudrecess/CloudRecess.kt]:
```suggestion
        GET("$baseUrl/latest?page=$page", headers)
```

File: lib-multisrc/cloudrecess/src/eu/kanade/tachiyomi/multisrc/cloudrecess/CloudRecess.kt [hunk 2]
```diff
@@ -0,0 +1,294 @@
...
+        genre = genres.joinToString()
+    }
+
+    protected open fun String?.parseStatus(): Int {
+        this ?: return SManga.UNKNOWN
+
+        return when {
+            listOf("ongoing", "مستمر").any { contains(it, true) } -> SManga.ONGOING
+            listOf("cancelled", "متوقف").any { contains(it, true) } -> SManga.CANCELLED
+            listOf("Completed", "مكتمل").any { contains(it, true) } -> SManga.COMPLETED
```
Comment (vetleledaal) [inline lib-multisrc/cloudrecess/src/eu/kanade/tachiyomi/multisrc/cloudrecess/CloudRecess.kt]: Since `contains` is used as case insensitive it should be lower case here

```suggestion
            listOf("completed", "مكتمل").any { contains(it, true) } -> SManga.COMPLETED
```

**Comment by vetleledaal** [comment]
Looks like https://github.com/jhin1m/fuzzy-doodle , all files under `/public/images/` match
Directory listing at https://flexscans.com/installer/ and https://flexscans.com/vendor/ also matches

It refers to itself as [MangaCMS](https://github.com/jhin1m/fuzzy-doodle/blob/f7eab4a731a76ab08ee5c03258c66cf773453d7d/themes/default/theme.php#L5), but you could also use something like `FuzzyDoodle`

**Review by vetleledaal — DISMISSED** [review]
