### PR TITLE
MangaGeko | Fixed No Title and No Cover

### LINKED ISSUE #11894: MangaGeko: broken search, latest and popular partially broken
### Source information

MangaGeko, 1.4.28

### Source language

English 

### Steps to reproduce

Browse 

### Expected behavior

Everything normal 

### Actual behavior

Search is completely not working:

In Latest, Popular and Filter tab, some of the entries are not showing title and cover image:

When any such entry is opened, the cover appears but not the title:

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 15

### Other details

Extension got an update recently 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #11894

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/mangarawclub/src/eu/kanade/tachiyomi/extension/en/mangarawclub/MangaRawClub.kt [hunk 1]
```diff
@@ -159,8 +151,8 @@ class MangaRawClub : ParsedHttpSource(), ConfigurableSource {
 
     // Manga from Element
     override fun searchMangaFromElement(element: Element): SManga = SManga.create().apply {
-        title = element.selectFirst(".comic-card__title")!!.ownText()
-        thumbnail_url = element.select(".comic-card__cover img").attr("abs:data-src")
+        title = element.selectFirst(".comic-card__title a")!!.text().trim()
```
Comment (vetleledaal) [inline src/en/mangarawclub/src/eu/kanade/tachiyomi/extension/en/mangarawclub/MangaRawClub.kt]:
```suggestion
        title = element.selectFirst(".comic-card__title a")!!.text()
```

`.text()` is already trimmed, according to Jsoup docs.

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
