### PR TITLE
ReadMangas: Fix loading content

### LINKED ISSUE #8221: Read Mangas: New domain URL
### Source information

Read Mangas 1.4.38

### Source language

Português (Brasil)

### Source new URL

https://mangalivre.one

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #8221

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt [hunk 1]
```diff
@@ -279,33 +262,69 @@ class ReadMangas() : HttpSource() {
...
+                $script
+                self.__next_f.map(it => it[it.length - 1]).join('')
+                """.trimIndent(),
+            ) as String
+        }
+
+        return JSON_REGEX.find(content)?.groups?.get(0)?.value
+    }
+
+    private fun Int.isFirst(): Boolean = this == 1
```
Comment (vetleledaal) [inline src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: This seems like an odd function to break out.

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt [hunk 2]
```diff
@@ -179,62 +156,60 @@ class ReadMangas() : HttpSource() {
...
         var page = 1
         do {
-            val response = tryFetchChapterPage(manga, page++)
-            val dto = response
-                .parseAs<List<WrapperResult<ChapterListDto>>>()
-                .firstNotNullOf { it.result }
-                .data.json
+            val response = tryFetchChapterPage(manga, page++, chapterToken)
+            val json = CHAPTERS_REGEX.find(response.body.string())?.groups?.get(0)?.value
+            val dto = json!!.parseAs<ChapterListDto>()
```
Comment (vetleledaal) [inline src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: Will this (non-null assert) mean a failure on page 4 mean chapters from page 1-3 are discarded?

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt [hunk 3]
```diff
@@ -279,33 +262,68 @@ class ReadMangas() : HttpSource() {
...
         "hiatus" -> SManga.ON_HIATUS
         else -> SManga.UNKNOWN
     }
 
+    private fun Response.parseScriptToJson(): String? {
+        val document = asJsoup()
+        val script = document.select("script")
+            .map(Element::data)
+            .filter {
+                it.contains("self.__next_f", ignoreCase = true)
```
Comment (vetleledaal) [inline src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: I don't think it makes sense to use `ignoreCase = true` here, especially since further down you assume the variable `self.__next_f` exists.

**Review by vetleledaal — APPROVED** [review]

**Comment by BlackMember08** [comment]
Hello, it didn't appear to download even when merged!

**Comment by AnonymousPtBr** [comment]
The option to update the font does not appear!

**Comment by Norsze** [comment]
We know, stop spamming @AnonymousPtBr
