### PR TITLE
Batoto: Fix getMangaUrl and null serial chapter parsing

### LINKED ISSUE #12663: Bato.to invalid URL & chapter name error
### Source information

Bato.to 1.4.59

### Source language

English

### Steps to reproduce

Open an entry in webview

### Expected behavior

Able to see the website

### Actual behavior

When viewing in webview you get a 404

### Mihon/Tachiyomi version

TachiyomiSY 1.12.0

### Android version

Android 12

### Other details

In version v4 of the website they've removed the title from the URL so it's just the series number
example: bato.si/title/series/(number string)
There is also an error when a chapter only has a name and not a chapter number. A json error about an invalid chapter gets thrown out when trying to refresh the entry

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by LetianLi**
Closes #12663. 
- Fixes old v2 entries webview from going to "/title//series/mangaId/mangaName" by properly extracting the mangaId. For some reason, `manga.url` is not updating to be just the manga id, so we need to wrap it. 
- Fixes rare null serial occurrence in the chapter list api by making serial nullable.

Example in the api for `comicId=149027`:
```json
"data": {
	"comicId": "149027",
	"id": "2694427",
	"serial": null,
	"dname": "Read Online",
	"title": null,
	"urlPath": "/title/149027/2694427"
}
```
The chapter `name` is "Read Online" and `chapter_number` is not set.

extVersionCode has not been bumped here to reduce user updates, merge this with #12621.

Checklist:

- [ ] ~Updated `extVersionCode` value in `build.gradle` for individual extensions~
- [x] ~Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions~
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] ~Added the `isNsfw = true` flag in `build.gradle` when appropriate~
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] ~Have removed `web_hi_res_512.png` when adding a new extension~

### CODE REVIEW

File: src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/Dto.kt [hunk 1]
```diff
@@ -131,17 +131,19 @@ class ChapterListData(
...
+                    }
                 }
                 append(displayName)
                 if (!title.isNullOrEmpty()) {
                     if (isNotEmpty()) append(": ")
                     append(title)
                 }
             }
-            chapter_number = serial
+            chapter_number = serial ?: 0f
```
Comment (AwkwardPeak7) [inline src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/Dto.kt]: don't set it if it is null

Comment (LetianLi) [reply src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/Dto.kt]: Since the type for chapter_number is "var chapter_number: Float", isn't the default value going to be 0f anyways? The same thing applies to date_upload except it's a long.

Comment (LetianLi) [reply src/all/batoto/src/eu/kanade/tachiyomi/extension/all/batotov4/Dto.kt]: fixed

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by LetianLi** [comment]
Oops, ignore review request
