### PR TITLE
Manhastro: Update domain and add custom settings

### LINKED ISSUE #7202: Manhastro: Missing chapters
### Source information

Manhastro 

### Source language

Portuguese 

### Steps to reproduce

the scan does not have the chapters that are on the website as shown in the prints

Image
Image

### Expected behavior

the scan does not have the chapters that are on the website as shown in the prints

Image
Image

### Actual behavior

the scan does not have the chapters that are on the website as shown in the prints

Image
Image

### Mihon/Tachiyomi version

Mihon 0.17.1

### Android version

Andróide 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #7502: Add login na propria extensão.
### Source name

Manhastro

### Source language

Português (Brasil)

### Describe your suggested feature

Na aba de extensão, ao apertar na ingrenagem, ter não só a lingua mais também a opção de fazer login no site diretamente, sem a necessidade de usar o webview.

Image

Exemplo: 

Image

E ao apertar nessa ingrenagem próximo ao idioma ter acesso ao login. 

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #8587: Manhastro. URL change
### Source information

Manhastro 1.4.48

### Source language

Português( Brasil )

### Source new URL

https://manhastro.net/

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #7609 (it's a PR)
Closes #7502
Closes #7202
Closes #8587 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/manhastro/src/eu/kanade/tachiyomi/extension/pt/manhastro/Manhastro.kt [hunk 1]
```diff
@@ -63,7 +135,243 @@ class Manhastro : Madara(
...
+    }
+
+    // ============================ Auth ====================================
+
+    private val credentials: Credential get() = Credential(
+        email = preferences.getString(USERNAME_PREF, "") as String,
+        password = preferences.getString(PASSWORD_PREF, "") as String,
+    )
+
+    private val defaultClient = OkHttpClient()
```
Comment (AwkwardPeak7) [inline src/pt/manhastro/src/eu/kanade/tachiyomi/extension/pt/manhastro/Manhastro.kt]: use `network.cloudflareclient`

**Review by AwkwardPeak7 — COMMENTED** [review]
is login through webview not possible?

**Comment by choppeh** [comment]
> is login through webview not possible?

Yeah, but when the login cookie in the webView expires and an update occurs, only the last five chapters are retrieved. Then, upon the next login, the refresh of the entries mistakenly marks already read chapters as new ones.

**Comment by yangkai0210007** [comment]
I would like to know about the update of the Manhastro Brazil http, any news?

**Comment by Smol-Ame** [comment]
@yangkai0210007 it's called to wait patiently for this pull request to be reviewed and approved.

If you don't have anything useful to comment, don't comment.

**Comment by yangkai0210007** [comment]
Hahaha sorry man, you didn't need all those words, you're very violent hahaha forget it bro, I'm new to this extension thing, I didn't know that

**Comment by yangkai0210007** [comment]
I just install the extensions and read the mangas, otherwise I know nothing, sorry, have a great weekend to everyone at keiyoushi

**Review by AwkwardPeak7 — APPROVED** [review]
