### PR TITLE
Keyoapp: Fix manga details

### LINKED ISSUE #6128: Tags & Description Errors in Arvenscans & Necroscans [theme]
### Source information

en.arvencomics 1.4.33 | en.necroscans 1.4.9

### Source language

English

### Steps to reproduce

1. Open Arven/Necro Ext.
2. View Any Manhwa
3. Shows `Null` Tag (for all entries | both ext.) & Missing Description (for some entries | both ext.)

### Expected behavior

- Do not show `null` tag
- Display the description, tag(along with type), author & artist name if it is present on the site

### Actual behavior

`ArvenScans`

| Example 1 | Example 1 |
| --------- | ----------  |
| arven1 | arven2 |

`NecroScans`

| Example 2 | Example 2 |
| --------- | ----------  |
| necro1 | necro2 |

### Mihon/Tachiyomi version

SY Preview r574

### Android version

Android 14

### Other details

> It only shows the description when it’s inside the box (check example 2).

| Example 1 | Example 1 |
| --------- | ----------  |
| necro1 | brave_HVwVz9EQ4x |

| Example 2 | Example 2 |
| --------- | ----------  |
| necro2 | brave_ahP0x4wfE8 |

As for tags, I have a request: if possible, please add `tags` along with their `type` for forks that support `auto webtoon mode` to work properly.

| brave_3p8geG8hp6 | brave_P3jlMetYao |
| --------- | ----------  |

_Apologies if this is too much, and for not creating two separate issues for it._ 🙂

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #6977: Extra null Tag and missing Status in Animated Glitched Comics
### Source information

Animated Glitched Comics

### Source language

English 

### Steps to reproduce

Open any Manhwa in the library 

### Expected behavior

1. Shouldn't show null tag
2. Status should show correctly (Ongoing/Completed..)

### Actual behavior

1. Extra null tag as first tag
2. Status is unknown for all entries 

### Mihon/Tachiyomi version

0.17.1

### Android version

14

### Other details

IMG_20250104_153427
IMG_20241220_211523

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #6128
Closes #6977

Tested with `en.necroscans`, `en.arvencomics` and `en.animatedglitchedcomics`

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/keyoapp/src/eu/kanade/tachiyomi/multisrc/keyoapp/Keyoapp.kt [hunk 1]
```diff
@@ -209,12 +209,12 @@ abstract class Keyoapp(
     override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
         title = document.selectFirst("div.grid > h1")!!.text()
         thumbnail_url = document.getImageUrl("div[class*=photoURL]")
-        description = document.selectFirst("div.grid > div.overflow-hidden > p")?.text()
-        status = document.selectFirst("div[alt=Status]").parseStatus()
-        author = document.selectFirst("div[alt=Author]")?.text()
-        artist = document.selectFirst("div[alt=Artist]")?.text()
+        description = document.selectFirst("p.rounded-lg")?.text()
```
Comment (vetleledaal) [inline lib-multisrc/keyoapp/src/eu/kanade/tachiyomi/multisrc/keyoapp/Keyoapp.kt]: If you're already relying on locale for the other fields, why not?:
```css
div:containsOwn(Synopsis) ~ div
```

**Review by vetleledaal — DISMISSED** [review]

File: lib-multisrc/keyoapp/src/eu/kanade/tachiyomi/multisrc/keyoapp/Keyoapp.kt (hunk 1 above)
Comment (dngonz) [reply lib-multisrc/keyoapp/src/eu/kanade/tachiyomi/multisrc/keyoapp/Keyoapp.kt]: Also changed

**Review by vetleledaal — APPROVED** [review]
