### PR TITLE
Fix 404s for QiScans

### LINKED ISSUE #12332: Qi Scans: `HTTP 404` with specific chapters
### Source information

Extension name: Qi Scans Extension version: 1.4.13 

### Source language

English 

### Steps to reproduce

Open latest chapter any series, gets http error 404

### Expected behavior

Show chapter 

### Actual behavior

gets http error 404

### Mihon/Tachiyomi version

App ID: app.mihon App version: 0.19.3 

### Android version

Android version: 15

### Other details

Only in the latest chapter 
If you open in WebView you get http 404 but opening the chapter from WebView it works fine.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Xyndra**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

Closes #12332

### CODE REVIEW

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 1]
```diff
@@ -66,7 +66,9 @@ class QiScans : Iken(
         }
 
         return document.getNextJson("images").parseAs<List<PageParseDto>>().sortedBy { it.order }.mapIndexed { idx, p ->
-            Page(idx, imageUrl = p.url)
+            // Some new(~Jan 2026) chapters use this format which leads to 404s
+            val url = p.url.replace("https://media.qiscans.org/file/qiscans/upload/series", "https://media.qiscans.org/upload/series")
```
Comment (bapeey) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]:
```suggestion
            val url = p.url.replaceFirst("/file/qiscans/", "/")
```

**Comment by Xyndra** [comment]
Note for anyone testing: you need to go to `More > Data and storage > Clear chapter cache` for this to start applying

**Review by vetleledaal — APPROVED** [review]
