### PR TITLE
GigaViewer: Add paginated chapter list parse support

### LINKED ISSUE #9842: GigaViewer theme extensions: `No chapters found` error
### Source information

Sunday Webry 1.6

### Source language

Japanese

### Steps to reproduce

1. Launching the Mihon application
2. Launch of the Sunday Webry extension
3. Selecting a title
4. Lack of chapters

### Expected behavior

That there will be a list of chapters

### Actual behavior

Chapters are missing 

### Mihon/Tachiyomi version

Mihon 0.18.0

### Android version

14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by hatozuki-programmer**
Adds support for a new version of the chapter list parse for paginated GigaViewer sources that can be enabled by setting `isPaginated = true` for the source. The old chapter list parse has been left as the default for any sources that may still be using it.
This fixes the `No chapters found` error for MAGCOMI, Kurage Bunch, Comic Days, Sunday Web Every, Shonen Jump+, Comiplex, Comic Gardo, and Tonari no Young Jump.

Closes #9842

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt [hunk 1]
```diff
@@ -180,6 +181,73 @@ abstract class GigaViewer(
...
+        val chapters = mutableListOf<SChapter>()
+
+        var offset = 0
+
+        // make initial request
+        var result = paginatedChaptersRequest(referer, aggregateId, offset)
+        var resultData = json.decodeFromString<GigaViewerEpisodesDto>("{\"episodes\": ${result.body.string()}}")
+
+        // repeat until the offset is too large to return any chapters, resulting in an empty list
+        while (resultData.episodes.isNotEmpty()) {
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt]: Use a `while (true)` loop and make the request in the loop. Break when the episodes are empty.

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt [hunk 2]
```diff
@@ -180,6 +181,73 @@ abstract class GigaViewer(
...
+                    name = element.title
+                    if (chapterListMode == CHAPTER_LIST_PAID && element.status?.label != IS_FREE) {
+                        name = YEN_BANKNOTE + name
+                    } else if (chapterListMode == CHAPTER_LIST_LOCKED && element.status?.label == UNPUBLISHED) {
+                        name = LOCK + name
+                    }
+                    date_upload = element.display_open_at?.toDate() ?: 0L
+                    scanlator = publisher
+                    setUrlWithoutDomain("/episode/${element.readable_product_id}")
+                }
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt]: Extract this logic to a `toSManga()` function inside the DTO class. Then make the relevant properties private.

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt [hunk 3]
```diff
@@ -180,6 +181,73 @@ abstract class GigaViewer(
...
+            }
+            // increase offset and make next request
+            offset += resultData.episodes.size
+            result = paginatedChaptersRequest(referer, aggregateId, offset)
+            resultData = json.decodeFromString<GigaViewerEpisodesDto>("{\"episodes\": ${result.body.string()}}")
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt]:
```suggestion
            resultData = result.parseAs<List<GigaViewerPaginationReadableProduct>>()
```

Doesn't this work? Why wrap it by string concatenation?

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt [hunk 4]
```diff
@@ -180,6 +181,73 @@ abstract class GigaViewer(
...
+        }
+
+        result.close()
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt]:
```suggestion
```

`parseAs()` and `string()` both closes the response inside them.

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt [hunk 5]
```diff
@@ -315,12 +383,13 @@ abstract class GigaViewer(
...
     private fun String.toDate(): Long {
-        return runCatching { DATE_PARSER.parse(this)?.time }
+        return runCatching { (if (isPaginated) DATE_PARSER_COMPLEX else DATE_PARSER_SIMPLE).parse(this)?.time }
             .getOrNull() ?: 0L
     }
 
     companion object {
-        private val DATE_PARSER by lazy { SimpleDateFormat("yyyy/MM/dd", Locale.ENGLISH) }
+        private val DATE_PARSER_SIMPLE by lazy { SimpleDateFormat("yyyy/MM/dd", Locale.ENGLISH) }
+        private val DATE_PARSER_COMPLEX by lazy { SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.ENGLISH) }
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt]: Move this to the DTO file (at top-level) and remove the lazy (top-level elements are automatically lazy loaded).

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt [hunk 6]
```diff
@@ -24,3 +24,34 @@ data class GigaViewerPage(
...
     val width: Int = 0,
 )
+
+@Serializable
+data class GigaViewerEpisodesDto(
+    val episodes: List<GigaViewerPaginationReadableProduct> = emptyList(),
+)
+
+@Serializable
+data class GigaViewerPaginationReadableProduct(
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt]: Use a plain `class` instead of `data class` unless you're using `==`, `copy()` or `hashCode()`.

**Comment by hatozuki-programmer** [comment]
Thank you for the feedback. I've implemented the requested changes.

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt [hunk 7]
```diff
@@ -315,21 +371,19 @@ abstract class GigaViewer(
     }
 
     private fun String.toDate(): Long {
-        return runCatching { DATE_PARSER.parse(this)?.time }
+        return runCatching { (if (isPaginated) DATE_PARSER_COMPLEX else DATE_PARSER_SIMPLE).parse(this)?.time }
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewer.kt]: This should use `DATE_PARSER_SIMPLE` only. Plus, remove this `toDate()` and use `DATE_PARSER_SIMPLE.tryParse()` at the call site.

https://github.com/keiyoushi/extensions-source/blob/98a4e1540993d487aa254e7626bb688d06731cda/core/src/main/kotlin/keiyoushi/utils/Date.kt#L7

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt [hunk 8]
```diff
@@ -24,3 +31,56 @@ data class GigaViewerPage(
...
+    val display_open_at: String?,
+    val event_free_open_limit: String?,
+    val free_term_start_at: String?,
+    val open_limit: String?,
+    val readable_product_id: String = "",
+    val status: GigaViewerPaginationReadableProductStatus?,
+    val thumbnail_alt: String = "",
+    val thumbnail_uri: String = "",
+    val title: String = "",
+    val viewer_uri: String = "",
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt]: Make the fields `private`, and remove the unused ones.

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt [hunk 9]
```diff
@@ -24,3 +31,56 @@ data class GigaViewerPage(
...
+
+@Serializable
+class GigaViewerPaginationReadableProductStatus(
+    val buy_price: Int?,
+    val label: String?,
+    val rental_end_at: String?,
+    val rental_price: Int?,
+    val rental_term: Int?,
+    val private_reason_message: String?,
+    val type: String?,
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt]: Remove unused fields.

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt [hunk 10]
```diff
@@ -24,3 +31,56 @@ data class GigaViewerPage(
...
+    val viewer_uri: String = "",
+) {
+    fun toSChapter(chapterListMode: Int, publisher: String) = SChapter.create().apply {
+        name = title
+        if (chapterListMode == CHAPTER_LIST_PAID && status?.label != IS_FREE) {
+            name = YEN_BANKNOTE + name
+        } else if (chapterListMode == CHAPTER_LIST_LOCKED && status?.label == UNPUBLISHED) {
+            name = LOCK + name
+        }
+        date_upload = display_open_at?.toDate() ?: 0L
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt]: Use `tryParse()`.

File: lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt [hunk 11]
```diff
@@ -24,3 +31,56 @@ data class GigaViewerPage(
...
+        scanlator = publisher
+        url = "/episode/$readable_product_id"
+    }
+
+    companion object {
+        // chapter status labels
+        private const val IS_FREE = "is_free"
+        private const val IS_RENTABLE = "is_rentable"
+        private const val IS_PURCHASABLE = "is_purchasable"
+        private const val UNPUBLISHED = "unpublished"
```
Comment (stevenyomi) [inline lib-multisrc/gigaviewer/src/eu/kanade/tachiyomi/multisrc/gigaviewer/GigaViewerDto.kt]: Inline these constants. If you want to note down the possible values, add a comment beside the field.

**Comment by hatozuki-programmer** [comment]
Changes from the second round of feedback have been implemented.

**Review by stevenyomi — APPROVED** [review]
