### PR TITLE
Fix GreenShit

### LINKED ISSUE #9001: Erro no sussy toons
### Source information

Sussy toons-1.4.58

### Source language

Português (Brasil)

### Steps to reproduce

Entrar na extensão pelos recentes.

### Expected behavior

Abrir os mangas sem filtragem atualizados recentemente. 

### Actual behavior

Ele abre os mangas como se estivesse filtrados só por shoujo/romance. 

### Mihon/Tachiyomi version

0.18.0

### Android version

13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9007: Mediocre Toons: No chapters found / Details do mangá não foi encontrado error
### Source information

Mediocre Toons 1.4.2

### Source language

Português ( Brasil )

### Steps to reproduce

Não está carregando os capítulos das obras

https://github.com/user-attachments/assets/71f3e725-8b95-4a89-9e24-7514f21d9cbf

### Expected behavior

Aparecer os capítulos na extensão, no site está carregando normalmente

### Actual behavior

Image

### Mihon/Tachiyomi version

Komikku 1.13.1

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes  #9001
Closes #9007

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 1]
```diff
@@ -105,11 +107,18 @@ abstract class GreenShit(
         val url = "$apiUrl/obras/novos-capitulos".toHttpUrl().newBuilder()
             .addQueryParameter("pagina", page.toString())
             .addQueryParameter("limite", "24")
-            .addQueryParameter("gen_id", "4")
+            .addQueryParameterIf(targetAudience != TargetAudience.All, "gen_id", targetAudience.toString())
             .build()
         return GET(url, headers)
     }
 
+    private fun HttpUrl.Builder.addQueryParameterIf(condition: Boolean, name: String, value: String): HttpUrl.Builder {
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt]: Is this argument order a well-known convention? Otherwise I would say the condition / predicate should be at the end. Especially when you read the function name plainly, 'Add query parameter {name}:{value} if {condition}'.

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 2]
```diff
@@ -105,11 +107,18 @@ abstract class GreenShit(
...
+        if (condition) {
+            addQueryParameter(name, value)
+        }
+        return this
+    }
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt]: Might be too terse, but consider:
```suggestion
    private fun HttpUrl.Builder.addQueryParameterIf(condition: Boolean, name: String, value: String): HttpUrl.Builder =
        applyIf(condition) { addQueryParameter(name, value) }
```

**Review by vetleledaal — DISMISSED** [review]

File: lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt [hunk 3]
```diff
@@ -105,11 +107,18 @@ abstract class GreenShit(
         val url = "$apiUrl/obras/novos-capitulos".toHttpUrl().newBuilder()
             .addQueryParameter("pagina", page.toString())
             .addQueryParameter("limite", "24")
-            .addQueryParameter("gen_id", "4")
+            .addQueryParameterIf(targetAudience != TargetAudience.All, "gen_id", targetAudience.toString())
```
Comment (vetleledaal) [inline lib-multisrc/greenshit/src/eu/kanade/tachiyomi/multisrc/greenshit/GreenShit.kt:127]: Why not:
```suggestion
            .applyIf(targetAudience != TargetAudience.All) { addQueryParameter("gen_id", targetAudience.toString()) }
```

**Comment by vetleledaal** [comment]
My bad, I see now `.applyIf` is not applicable in that context. I was thinking of:

https://github.com/JetBrains/kotlin/blob/af048b8b13734b0109e55a677f29369b01d706e9/core/util.runtime/src/org/jetbrains/kotlin/utils/addToStdlib.kt#L277-L278

Feel free to restore to the original implementation, I would say it's preferable, even.

**Review by vetleledaal — APPROVED** [review]
