### PR TITLE
[PT-BR] - Mediocretoons api modify and fix popular mangas

### LINKED ISSUE #14388: Mediocre Toons http error 502
### Source information

Mediocre Toons 1.4.16

### Source language

Potuguês Brasileiro

### Steps to reproduce

1. Vou em navegar e abro a extensão
2. Aparece o Erro HTTP 502

### Expected behavior

Quando eu entrasse na extensão na aba recente apareceria os mangás na tela, e os mangás que estão na minha biblioteca, quando eu os abrisse, apareceria os capítulos 

### Actual behavior

Quando eu abro a extensão na aba recentes, aparece a mensagem de erro, e quando eu abro algum capítulo que já está na biblioteca, também dá erro.

### Mihon/Mihon fork version

Mihon Beta r7630

### Android version

Android 16

### Other details

Na Webview funciona normal, somente no mihon está com problemas

Image
Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by rod-moraes**
Update Mediocre Toons extension: bump version code to 17, change API URL, and refactor popular manga request parsing

closes: https://github.com/keiyoushi/extensions-source/issues/14388

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt [hunk 1]
```diff
@@ -84,6 +74,9 @@ data class MediocreMangaDto(
     val status: MediocreStatusDto? = null,
     @SerialName("total_capitulos") val totalChapters: Int = 0,
     @SerialName("capitulos") val chapters: List<MediocreChapterSimpleDto> = emptyList(),
+    @SerialName("criada_em") val createdAt: String? = null,
+    @SerialName("atualizada_em") val updatedAt: String? = null,
+    @SerialName("capitulo_numero") val homeChapterNumber: Float? = null,
```
Comment (bapeey) [inline src/pt/mediocretoons/src/eu/kanade/tachiyomi/extension/pt/mediocretoons/MediocreToonsDto.kt]: You don't need to map all the fields if you're not going to use them

**Review by vetleledaal — APPROVED** [review]
