### PR TITLE
SanaScans: fix latest infinite loading

### LINKED ISSUE #13163: Sana scans cant show any more manga titles after update
### Source information

sana scans 1.4.16

### Source language

english

### Steps to reproduce

1. update sana scans extension
2. open latest or popular manga
3. scroll down the list and cant load anymore manga

Image

### Expected behavior

after scrolling down we get more manga titles on past update like a day or week ago

### Actual behavior

infinite loading symbol

### Mihon/Tachiyomi version

komikku stable 1.13.5

### Android version

android 12

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AaronDeimos**
Close: #13163 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/sanascans/src/eu/kanade/tachiyomi/extension/en/sanascans/SanaScans.kt [hunk 1]
```diff
@@ -73,18 +76,43 @@ class SanaScans : HttpSource(), ConfigurableSource {
...
+            .addQueryParameter("isNovel", "false")
+            .build()
+
+        return GET(url, headers)
+    }
 
     override fun latestUpdatesParse(response: Response): MangasPage {
-        val document = response.asJsoupXml()
+        val body = response.body.string()
+        val json = body.parseAs<JsonObject>()
```
Comment (AwkwardPeak7) [inline src/en/sanascans/src/eu/kanade/tachiyomi/extension/en/sanascans/SanaScans.kt]:
```suggestion
        val json = response.parseAs<JsonObject>()
```

**Review by AwkwardPeak7 — APPROVED** [review]
