### PR TITLE
DemonSect: Add interceptor

### LINKED ISSUE #3324: Demon Sect: No Results founded
### Source information

Demon Sect 1.4.42

### Source language

Brazilian Portuguese - Português (Brasil)

### Steps to reproduce

1. Click in the "Demon Sect" extension font

### Expected behavior

Normally, all from this scan appear 

### Actual behavior

Screenshot_20240531_182810_Mihon

Dont appear

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #3324

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/prismascans/src/eu/kanade/tachiyomi/extension/pt/prismascans/DemonSect.kt [hunk 1]
```diff
@@ -21,6 +22,14 @@ class DemonSect : Madara(
     override val id: Long = 8168108118738519332
 
     override val client: OkHttpClient = super.client.newBuilder()
+        .addInterceptor { chain ->
+            val response = chain.proceed(chain.request())
+            val request = response.request
+            if (request.url.toString().contains("login", ignoreCase = true)) {
```
Comment (bapeey) [inline src/pt/prismascans/src/eu/kanade/tachiyomi/extension/pt/prismascans/DemonSect.kt]: I think it's better to check the path segment instead of the string in the full url

**Review by AwkwardPeak7 — APPROVED** [review]
