### PR TITLE
Valir Scans: fix new site routes and parser

### LINKED ISSUE #14436: Valir Scans URL structure change
### Source information

Valir Scans 1.4.18

### Source language

English

### Source new URL

https://valirscans.org/

### Other details

The domain is correct, but the structure is not.
Old link: https://valirscans.org/series/63ce0a4bb9d
New link: https://valirscans.org/series/comic/the-cutest-little-villainess

### Acknowledgements

- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have checked WebView to see the source's main URL is not up-to-date, or has to redirect into the new URL.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues/) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by SuperMario22922**
The previous PR for valir scans only changed the URL/domain to the new one but the actual structure of the page has changed when they migrated to the new domain which this PR fixes

Closes #14436

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by vetleledaal — COMMENTED** [review]
You need to put one of the [recognized keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) before each issue you intend to close. GitHub doesn't recognize a list of issues.

i.e. `Closes #100, Closes #101`. Not `Closes #100, #101`.

**Comment by SuperMario22922** [comment]
> You need to put one of the [recognized keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) before each issue you intend to close. GitHub doesn't recognize a list of issues.
> 
> i.e. `Closes #100, Closes #101`. Not `Closes #100, #101`.

but i only had 1 issue i was trying to close in the first place?

**Comment by vetleledaal** [comment]
My bad, was mixing up tabs.

**Comment by SuperMario22922** [comment]
> My bad, was mixing up tabs.

oh lol no problem 👍

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScansDto.kt [hunk 1]
```diff
@@ -0,0 +1,56 @@
+package eu.kanade.tachiyomi.extension.en.valirscans
+
+import kotlinx.serialization.SerialName
+import kotlinx.serialization.Serializable
+
+@Serializable
+data class BookSchema(
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScansDto.kt]: Use regular classes.
```suggestion
class BookSchema(
```

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 2]
```diff
@@ -1,16 +1,331 @@
...
+                        return html.substring(valueStart, index + 1)
+                    }
+                }
+            }
+        }
+
+        error("Could not find JSON end for marker: $marker")
+    }
+
+    private fun String.unescapeJson(): String = json.decodeFromString("\"$this\"")
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]:
```suggestion
    private fun String.unescapeJson(): String = "\"$this\"".parseAs<String>()
```

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 3]
```diff
@@ -1,16 +1,331 @@
...
+        "ONGOING" -> SManga.ONGOING
+        "COMPLETED" -> SManga.COMPLETED
+        "HIATUS" -> SManga.ON_HIATUS
+        "CANCELLED", "CANCELED", "DROPPED" -> SManga.CANCELLED
+        else -> SManga.UNKNOWN
+    }
+
+    private fun formatChapterNumber(number: Float): String = chapterNumberFormatter.format(number)
+
+    private fun String?.parseDate(): Long = this?.let { dateFormat.parse(it)?.time } ?: 0L
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: Use `.tryParse` instead. From `keiyoushi.utils`.

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 4]
```diff
@@ -1,16 +1,331 @@
...
+
+        val title = selectFirst("h3")?.text()
+            ?.ifBlank { null }
+            ?: selectFirst("img[alt]")?.attr("alt")
+                ?.ifBlank { null }
+            ?: return null
+
+        return SManga.create().apply {
+            this.title = title
+            url = normalizeSeriesPath(detailLink.attr("href"))
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: Haven't looked much into `normalizeSeriesPath`, but normally you would do:
```suggestion
            setUrlWithoutDomain(detailLink.absUrl("href"))
```

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 5]
```diff
@@ -1,16 +1,331 @@
...
+    }
+
+    private fun sanitizePath(path: String): String {
+        val withoutDomain = path
+            .removePrefix(baseUrl)
+            .removePrefix("https://valirscans.com")
+            .removePrefix("https://valirscans.org")
+
+        return "/" + withoutDomain.removePrefix("/").substringBefore("#")
+    }
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: Have you considered relying more heavily on `HttpUrl` here? String operations tend to be more brittle. And you're not handling relative paths not starting with `/` (requires knowing the document location) -- Jsoup does this for you.

Might not be practical to take into consideration.

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 6]
```diff
@@ -1,16 +1,331 @@
...
+            }
+            else -> cleanPath
+        }.substringBefore("?")
+    }
+
+    private fun sanitizePath(path: String): String {
+        val withoutDomain = path
+            .removePrefix(baseUrl)
+            .removePrefix("https://valirscans.com")
+            .removePrefix("https://valirscans.org")
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: Are these just for cleaning up old library URLs? Consider adding a small comment. Otherwise these lines may mistakenly be updated when the domain changes.

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScansDto.kt [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+@Serializable
+data class ReaderChapterDto(
+    val pages: List<ReaderPageDto> = emptyList(),
+)
+
+@Serializable
+data class ReaderPageDto(
+    val pageNumber: Int,
+    val imageUrl: String,
+)
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScansDto.kt:69]: These should also be regular classes.

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 8]
```diff
@@ -1,16 +1,340 @@
...
+        "ONGOING" -> SManga.ONGOING
+        "COMPLETED" -> SManga.COMPLETED
+        "HIATUS" -> SManga.ON_HIATUS
+        "CANCELLED", "CANCELED", "DROPPED" -> SManga.CANCELLED
+        else -> SManga.UNKNOWN
+    }
+
+    private fun formatChapterNumber(number: Float): String = chapterNumberFormatter.format(number)
+
+    private fun String?.parseDate(): Long = dateFormat.tryParse(this)
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: Can these 'proxy' functions be skipped? `parseDate` is only used once. Might be some merit to using `formatChapterNumber`.

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 9]
```diff
@@ -1,16 +1,340 @@
...
+
+    override fun pageListParse(response: Response): List<Page> {
+        val html = response.use { it.body.string() }
+        val chapter = extractEscapedJsonValue(html, ESCAPED_CHAPTER_MARKER, '{')
+            .unescapeJson()
+            .parseAs<ReaderChapterDto>()
+
+        return chapter.pages.map { page ->
+            Page(page.pageNumber - 1, imageUrl = page.imageUrl.toAbsoluteUrl())
+        }
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: FYI, the apps will ignore the page number passed here. Consider using `mapIndexed`, or if needed sort it first.

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 10]
```diff
@@ -1,16 +1,340 @@
...
+            .firstOrNull { it?.type == "Book" }
+
+        val detailData = runCatching {
+            extractEscapedJsonValue(html, ESCAPED_SERIES_MARKER, '{')
+                .unescapeJson()
+                .parseAs<SeriesDetailsDto>()
+        }.getOrNull()
+
+        return SManga.create().apply {
+            title = schema?.name ?: document.selectFirst("h1")?.text().orEmpty()
```
Comment (vetleledaal) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: Title can't be empty.
```suggestion
            title = schema?.name ?: document.selectFirst("h1")!!.text()
```

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 11]
```diff
@@ -1,16 +1,340 @@
...
+
+    override val baseUrl = "https://valirscans.org"
+
+    override val lang = "en"
+
+    override val supportsLatest = true
+
+    override val client = network.cloudflareClient
+
+    private val json: Json by injectLazy()
```
Comment (AwkwardPeak7) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: use `keiyoushi.utils.parseAs` for json parsing

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 12]
```diff
@@ -1,16 +1,340 @@
...
+
+    private val preferences: SharedPreferences by getPreferencesLazy()
+
+    private val baseHttpUrl by lazy { "$baseUrl/".toHttpUrl() }
```
Comment (AwkwardPeak7) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: no need for lazy

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 13]
```diff
@@ -1,16 +1,340 @@
...
+
+    override fun headersBuilder() = Headers.Builder()
```
Comment (AwkwardPeak7) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]:
```suggestion
    override fun headersBuilder() = super.headersBuilder()
```
keep app provided useragent

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 14]
```diff
@@ -1,16 +1,340 @@
...
+        val schema = document.select("script[type=application/ld+json]")
+            .asSequence()
+            .map { runCatching { it.data().parseAs<BookSchema>() }.getOrNull() }
+            .firstOrNull { it?.type == "Book" }
+
+        val detailData = runCatching {
+            extractEscapedJsonValue(html, ESCAPED_SERIES_MARKER, '{')
+                .unescapeJson()
+                .parseAs<SeriesDetailsDto>()
+        }.getOrNull()
```
Comment (AwkwardPeak7) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: consider use `keiyoushi.utils.extractNextJs` for nextjs flight data parsing

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 15]
```diff
@@ -1,16 +1,340 @@
...
+
+    private fun Element.extractThumbnailUrl(): String {
+        val candidate = attr("abs:src")
+            .ifBlank { attr("abs:srcset").substringBefore(" ") }
+
+        if (!candidate.contains("/_next/image?url=")) {
+            return candidate
+        }
+
+        val encodedUrl = candidate.substringAfter("url=", "").substringBefore("&")
```
Comment (AwkwardPeak7) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: use `HttpUrl.queryParameter` to extract specific query value (url)

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 16]
```diff
@@ -1,16 +1,340 @@
...
+        val decodedUrl = URLDecoder.decode(encodedUrl, StandardCharsets.UTF_8)
+        return decodedUrl.toAbsoluteUrl(ownerDocument()?.location() ?: baseUrl)
+    }
+
+    private fun String.toAbsoluteUrl(base: String = baseUrl): String = resolveUrl(this, base.toHttpUrlOrNull() ?: baseHttpUrl)?.toString() ?: this
+
+    private fun normalizeSeriesPath(path: String): String {
```
Comment (AwkwardPeak7) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: what is the purpose of this? isn't manga.url always same format? or is it for old url format?

File: src/en/valirscans/build.gradle
Comment (AwkwardPeak7) [inline src/en/valirscans/build.gradle:1]: remove `themepkg` and change to appropriate `extVersionCode`

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt (hunk 16 above)
Comment (SuperMario22922) [reply src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: since url format was changed when they migrated to new site

example from the linked issue
Old link: https://valirscans.org/series/63ce0a4bb9d
New link: https://valirscans.org/series/comic/the-cutest-little-villainess

Comment (AwkwardPeak7) [reply src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: so old slugs (e.g `63ce0a4bb9d`) work with new site?

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt [hunk 17]
```diff
@@ -152,9 +158,10 @@ class ValirScans :
 
     override fun pageListParse(response: Response): List<Page> {
         val html = response.use { it.body.string() }
-        val chapter = extractEscapedJsonValue(html, ESCAPED_CHAPTER_MARKER, '{')
-            .unescapeJson()
-            .parseAs<ReaderChapterDto>()
+        val document = Jsoup.parse(html, response.request.url.toString())
+        val chapter = document.extractNextJs<ChapterPageDto> { element ->
```
Comment (AwkwardPeak7) [inline src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: no need for `Document` for `extractNextJs`. It works with `Response` directly also if the site supports it, pass `rsc: 1` header to the request to only get nextjs data and not full html

File: src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt (hunk 16 above)
Comment (SuperMario22922) [reply src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: there is no redirect for old urls to new urls like
`https://valirscans.org/series/63ce0a4bb9d` does not redirect to `https://valirscans.org/series/comic/the-cutest-little-villainess` on the new site so users will need to re-migrate into the same source to update the url

couldn't find a way to do this automatically though :(

Comment (AwkwardPeak7) [reply src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: then there is no need for this method, bump `versionId` so users are forced to migrate

Comment (SuperMario22922) [reply src/en/valirscans/src/eu/kanade/tachiyomi/extension/en/valirscans/ValirScans.kt]: alr bumped version id and got rid of the method

**Review by AwkwardPeak7 — APPROVED** [review]
