### PR TITLE
Komiku (ID): update url and selector

### LINKED ISSUE #14256: Komiku: `HTTP 521` error
### Source information

Komiku 1.4.19

### Source language

Indonesia

### Steps to reproduce

Cant open the source but the web sources still fine its just i cant open the extension

### Expected behavior

Shouldve been able to open komiku extension

### Actual behavior

It shows http 521 and told me to open via webview

### Mihon/Mihon fork version

Mihon 0.19.7

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MuhamadSyabitHidayattulloh**
Closes #14256 
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 1]
```diff
@@ -1,300 +1,166 @@
...
-        Filter.Header("$name Project List page"),
-        ProjectList(projectFilter),
-    )
-
-    private val projectFilter = arrayOf(
-        Status("Show all manga", ""),
-        Status("Show only project manga", "project-filter-on"),
-    )
+    // =========================== Manga Details ============================
+    override fun mangaDetailsRequest(manga: SManga): Request = GET(baseUrl + manga.url, headers)
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt:72]: Default
```suggestion
```

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 2]
```diff
@@ -1,300 +1,166 @@
...
-        thumbnail_url = document.select("div.ims > img").attr("abs:src")
-
-        // add series type(manga/manhwa/manhua/other) thinggy to genre
-        val seriesTypeSelector = "table.inftable tr:contains(Jenis) a, table.inftable tr:has(a[href*=category\\/]) a, a[href*=category\\/]"
-        document.select(seriesTypeSelector).firstOrNull()?.text()?.let {
-            if (it.isEmpty().not() && genre!!.contains(it, true).not()) {
-                genre += if (genre!!.isEmpty()) it else ", $it"
+            document.select("table.inftable tr:contains(Judul Indonesia) td + td").text().let {
+                if (it.isNotEmpty()) {
+                    description = (if (description.isNullOrEmpty()) "" else "$description\n\n") + "Judul Indonesia: $it"
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt]: Use `buildString` for `description`.

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 3]
```diff
@@ -1,300 +1,166 @@
...
+                }
             }
+
+            author = document.select("table.inftable td:contains(Pengarang)+td, table.inftable td:contains(Komikus)+td").text().takeIf { it.isNotEmpty() }
+            genre = document.select("ul.genre li.genre a span").joinToString { it.text() }.takeIf { it.isNotEmpty() }
+            status = parseStatus(document.select("table.inftable tr > td:contains(Status) + td").text())
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt]: You only expect one element -- use `.selectFirst()`.

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 4]
```diff
@@ -1,300 +1,166 @@
...
-        name = element.select("a").text()
-
-        val timeStamp = element.select("td.tanggalseries")
-        date_upload = if (timeStamp.text().contains("lalu")) {
-            parseRelativeDate(timeStamp.text().trim())
-        } else {
-            parseDate(timeStamp.last()!!)
+    // ============================= Chapters ===============================
+    override fun chapterListRequest(manga: SManga): Request = GET(baseUrl + manga.url, headers)
+
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt:103]: Default
```suggestion
```

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 5]
```diff
@@ -1,300 +1,166 @@
...
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        return document.select("#Daftar_Chapter tr:has(td.judulseries)").map { element ->
+            SChapter.create().apply {
+                setUrlWithoutDomain(element.selectFirst("a")!!.attr("href"))
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt]:
```suggestion
                setUrlWithoutDomain(element.selectFirst("a")!!.absUrl("href"))
```

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 6]
```diff
@@ -1,300 +1,166 @@
...
+                    parseRelativeDate(timeStamp.text())
+                } else {
+                    dateFormat.tryParse(timeStamp.last()?.text())
+                }
+            }
         }
     }
 
-    private fun parseDate(element: Element): Long = SimpleDateFormat("dd/MM/yyyy", Locale.US).parse(element.text())?.time ?: 0
+    private val dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.US)
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt]:
```suggestion
    private val dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.ROOT)
```

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 7]
```diff
@@ -1,300 +1,166 @@
...
 
         return calendar.timeInMillis
     }
 
-    // pages
-    override fun pageListParse(document: Document): List<Page> = document.select("#Baca_Komik img").mapIndexed { i, element ->
-        Page(i, "", element.attr("abs:src"))
+    // =============================== Pages ================================
+    override fun pageListRequest(chapter: SChapter): Request = GET(baseUrl + chapter.url, headers)
+
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt:140]: Default
```suggestion
```

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 8]
```diff
@@ -1,300 +1,166 @@
...
+        Type(),
+        Order(),
+        Genre1(),
+        Genre2(),
+        Status(),
+    )
+
+    // ============================= Utilities ==============================
+    private fun mangaListParse(response: Response): MangasPage {
+        val document = response.asJsoup().apply { setBaseUri(baseUrl) }
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt]: Is `setBaseUri` needed here?

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 9]
```diff
@@ -1,300 +1,166 @@
...
+        val mangas = document.select("div.bge").map { element ->
+            SManga.create().apply {
+                title = element.selectFirst("h3")!!.text()
+                setUrlWithoutDomain(element.selectFirst("a:has(h3)")!!.attr("href"))
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt]:
```suggestion
                setUrlWithoutDomain(element.selectFirst("a:has(h3)")!!.absUrl("href"))
```

File: src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt [hunk 10]
```diff
@@ -1,300 +1,166 @@
...
+                thumbnail_url = element.select("img").attr("abs:src").substringBefore("?")
```
Comment (vetleledaal) [inline src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt]: Use `HttpUrl` to remove query.

**Review by vetleledaal — APPROVED** [review]
