### PR TITLE
Comix : Updated chapter deduplication to prioritise "Official?" group

### LINKED ISSUE #13160: Comix: `Missing # chapters` when Deduplicate Chapters is enabled, "Official?" chapters aren't prioritized
### Source information

Comix 1.4 7

### Source language

English

### Steps to reproduce

After the extension update, chapters from the official translation have gone missing. I checked the website, but the chapters are still there.

Image

### Expected behavior

Image

It should show all the official translation as per website

### Actual behavior

Now most of the chapters with an official translations are missing.

Image
Image
Image
Image
Image
Image

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 14

### Other details

I'm afraid if I also update my other titles from comix it will become like this. Please fix. Thanks guys!

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Sloweneuh**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

Closes #13160

Note : It will prioritise the boolean first, and then the "Official?" group, so for manga with both, the group name will be the publisher.

### CODE REVIEW

File: src/en/comix/src/eu/kanade/tachiyomi/extension/en/comix/Comix.kt [hunk 1]
```diff
@@ -219,13 +219,20 @@ class Comix :
...
                 chapterMap[key] = ch
             } else {
-                // Prefer official scan group
-                val officialNew = (ch.scanlationGroupId == 9275 || ch.isOfficial == 1)
-                val officialCurrent = (current.scanlationGroupId == 9275 || current.isOfficial == 1)
+                // Prefer official flag first, then "Official?" group, then votes/updatedAt
+                val newIsOfficial = ch.isOfficial == 1
+                val currentIsOfficial = current.isOfficial == 1
+                val newIsGroup10702 = ch.scanlationGroupId == 10702
+                val currentIsGroup10702 = current.scanlationGroupId == 10702
```
Comment (vetleledaal) [inline src/en/comix/src/eu/kanade/tachiyomi/extension/en/comix/Comix.kt:226]: Is `9275` no longer used?

If still relevant please add a comment just mapping out the groups. Like:

```
// 9275 - "some_group_name"
// 10702 - "Official?"
```

**Review by vetleledaal — APPROVED** [review]
