### PR TITLE
HattoriManga:  Theme change

### LINKED ISSUE #86: Hattori Manga: HTTP ERROR 404
### Source information

Hattori Manga 1.4.32

### Source language

Turkish

### Steps to reproduce

1. Open Tachiyomi
2. Open Hattori manga to read the manga you want

### Expected behavior

it should open the wanted manga in the app.

### Actual behavior

But the source does not work and gives an HTTPS ERROR 404 warning.

### Tachiyomi version

0.15.2

### Android version

Android 10 

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #86

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt [hunk 1]
```diff
@@ -1,23 +1,308 @@
...
+    override val supportsLatest: Boolean = true
+
+    override val versionId: Int = 2
+
+    private val json: Json by injectLazy()
+
+    private var csrfToken: String = ""
+
+    override val client: OkHttpClient = network.cloudflareClient.newBuilder()
+        .rateLimit(4)
```
Comment (AwkwardPeak7) [inline src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt]: rate limit should be the last interceptor

File: src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt [hunk 2]
```diff
@@ -1,23 +1,308 @@
...
+
+    override fun latestUpdatesNextPageSelector() =
+        throw UnsupportedOperationException()
+
+    override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/latest-chapters")
+
+    override fun latestUpdatesSelector() =
+        throw UnsupportedOperationException()
+
+    override fun fetchLatestUpdates(page: Int): Observable<MangasPage> {
```
Comment (AwkwardPeak7) [inline src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt]: dont override fetch for this, can be done in request and parse

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]
inherit from `HttpSource` and avoide overriding the `fetch` methods

File: src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt [hunk 3]
```diff
@@ -1,23 +1,288 @@
...
+        val filters = mutableListOf<Filter<*>>()
+
+        if (genresList.isNotEmpty()) {
+            filters += GenreList("Türler", genresList)
+        } else {
+            filters += listOf(
+                Filter.Separator(),
+                Filter.Header("Türleri göstermeyi denemek için 'Sıfırla' düğmesine basın"),
+            )
+        }
```
Comment (AwkwardPeak7) [inline src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt]:
```suggestion
        filters += if (genresList.isNotEmpty()) {
            filters += GenreList("Türler", genresList)
        } else {
            Filter.Header("Türleri göstermeyi denemek için 'Sıfırla' düğmesine basın")
        }
```

File: src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt [hunk 4]
```diff
@@ -1,23 +1,285 @@
...
+            }
+            MangasPage(mangas, false)
+        }
+    }
+
+    override fun getFilterList(): FilterList {
+        val filters = mutableListOf<Filter<*>>()
+
+        filters += if (genresList.isNotEmpty()) {
+            filters += GenreList("Türler", genresList)
```
Comment (AwkwardPeak7) [inline src/tr/hattorimanga/src/eu/kanade/tachiyomi/extension/tr/hattorimanga/HattoriManga.kt]:
```suggestion
            GenreList("Türler", genresList)
```

**Review by AwkwardPeak7 — APPROVED** [review]
