### PR TITLE
Fix DisasterScans

### LINKED ISSUE #6127: Disaster scans website changes
### Source information

Disaster Scans v1.4.32

### Source language

English

### Steps to reproduce

1. install the source
2. Try to browse the source or read an entry from the source

### Expected behavior

You should be able to read from the source

### Actual behavior

Error 404

### Mihon/Tachiyomi version

Yokai v1.8.5.9

### Android version

Android 15

### Other details

The website UI/UX has changed a lot so the extension doesn't work anymore

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Closes #6127

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 1]
```diff
@@ -1,209 +1,124 @@
...
 
-        val chapterPages = document.select("#__NEXT_DATA__").html()
-            .parseAs<NextData<ApiChapterPages>>()
-            .props.pageProps.chapter.pages
+        val titleElement = document.selectFirst("section h1")
+        titleElement?.text()?.let { title = it }
 
-        val pages = chapterPages.parseAs<List<String>>()
+        description = titleElement?.parent()?.parent()?.nextElementSibling()?.nextElementSibling()?.text()
+        val genres = titleElement?.parent()?.parent()?.nextElementSibling()?.select("span")
```
Comment (AwkwardPeak7) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: any better way to select them?

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 2]
```diff
@@ -1,209 +1,124 @@
...
+            SChapter.create().apply {
+                name = "Chapter ${chapter.ChapterNumber} - ${chapter.ChapterName}"
+                setUrlWithoutDomain(
+                    baseUrl.toHttpUrl().newBuilder().apply {
+                        addPathSegment("comics")
+                        addPathSegment(mangaID)
+                        addPathSegment("${chapter.chapterID}-chapter-${chapter.ChapterNumber}")
+                    }.build().toString(),
+                )
+                date_upload = dateFormat.parse(chapter.chapterDate)?.time ?: 0
```
Comment (AwkwardPeak7) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: wrap in try catch

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 3]
```diff
@@ -1,209 +1,124 @@
...
-        private const val fallbackCdnUrl = "https://f005.backblazeb2.com/b2api/v1/b2_download_file_by_id?fileId="
-        private const val cdnPref = "cdn_pref"
-        val titleSpecialCharactersRegex = "[^a-z0-9]+".toRegex()
-        val trailingHyphenRegex = "-+$".toRegex()
-        val dateFormat by lazy {
-            SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.ENGLISH)
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val found = chapterDataRegex.find(response.body.string())?.destructured
+        val chapterData = found?.component1()?.replace("\\", "") ?: return listOf()
+        val mangaID = found.component2()
```
Comment (AwkwardPeak7) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: you don't need to call component* functions directly

```kt
val (chapterData, mangaId) = chapterDataRegex.find(response.body.string())
    ?.destructured ?: return emptyList()

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt (hunk 3 above)
Comment (Creepler13) [reply src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: Ah, cool. Didnt know this was possible

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt (hunk 1 above)
Comment (Creepler13) [reply src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: I tried something, 
there a no identifying classes or ids.
Its hell

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 4]
```diff
@@ -1,209 +1,133 @@
...
-            .let { MangasPage(it, false) }
+    private fun mangaFromElement(element: Element): SManga = SManga.create().apply {
+        setUrlWithoutDomain(element.absUrl("href"))
+        thumbnail_url = element.selectFirst("img")?.absUrl("src")
     }
 
-    override fun mangaDetailsRequest(manga: SManga): Request {
-        return GET("$apiUrl${manga.url}", headers)
+    override fun popularMangaFromElement(element: Element): SManga = mangaFromElement(element).apply {
+        title = element.selectFirst("h5")?.text().toString()
```
Comment (vetleledaal) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: `.text()` returns String already. Do not use `.toString()` to mask null values. Instead, sinde the title field is critical you can do:
```suggestion
        title = element.selectFirst("h5")!!.text()
```
(not tested)

I see the same pattern being used elsewhere. Search for `.text().toString()` and handle those as well.

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 5]
```diff
@@ -1,209 +1,133 @@
...
+    override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
+        author = document.selectFirst("span:contains(Author) + span")?.text()
 
-        val chapterPages = document.select("#__NEXT_DATA__").html()
-            .parseAs<NextData<ApiChapterPages>>()
-            .props.pageProps.chapter.pages
+        val infoBlock = document.selectFirst("section div div")
 
-        val pages = chapterPages.parseAs<List<String>>()
+        if (infoBlock != null) {
```
Comment (vetleledaal) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: Consider `?.also { ... }`

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 6]
```diff
@@ -1,209 +1,133 @@
...
-                    preferences.putCdnUrl(cdnUrlFromPage)
-                    cdnUrlFromPage
-                } else {
-                    it
+            with(infoBlockChildren[1].select("span")) {
+                status = when (this.removeAt(0)?.text()?.lowercase()) {
+                    "ongoing" -> SManga.ONGOING
+                    else -> SManga.UNKNOWN
                 }
+                genre = this.joinToString(", ") { it.text() }
```
Comment (vetleledaal) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: `, ` is the default and can be omitted.
```suggestion
                genre = this.joinToString { it.text() }
```

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 7]
```diff
@@ -1,209 +1,133 @@
...
-        private const val cdnPref = "cdn_pref"
-        val titleSpecialCharactersRegex = "[^a-z0-9]+".toRegex()
-        val trailingHyphenRegex = "-+$".toRegex()
-        val dateFormat by lazy {
-            SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.ENGLISH)
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val (chapterData, mangaId) = chapterDataRegex.find(response.body.string())
+            ?.destructured ?: return emptyList()
+
+        return json.decodeFromString<List<ChapterDTO>>(chapterData.replace("\\", "")).map { chapter ->
```
Comment (vetleledaal) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: See if the approach in VortexScans works for this use case too:
https://github.com/keiyoushi/extensions-source/blob/64ea3602c060586ebfcb76cd8388b04b3d5b43b3/src/en/arvenscans/src/eu/kanade/tachiyomi/extension/en/arvenscans/VortexScans.kt#L27-L32

File: src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt [hunk 8]
```diff
@@ -98,10 +94,17 @@ class DisasterScans : ParsedHttpSource() {
...
-            ?.destructured ?: return emptyList()
+        var mangaId = ""
+        val chapters = chapterDataRegex.find(response.body.string())
+            ?.destructured
+            ?.let {
+                mangaId = it.component2()
+                it.component1().replace("\\", "")
+            }
+            ?.let { json.decodeFromString<List<ChapterDTO>>(it) }
+            ?: throw Exception("Cant parse chapter list")
```
Comment (AwkwardPeak7) [inline src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: vetle probably meant to use `json.decodeFromString<String>(...)` to unescape the json string. you don't need to call component* functions individually

Comment (Creepler13) [reply src/en/disasterscans/src/eu/kanade/tachiyomi/extension/en/disasterscans/DisasterScans.kt]: i think i got it now. I hope

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by noctaia** [comment]
The PR did not fix the extension sadly.
While trying to fetch the chapter list from any entry, there is an error:
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Expected beginning of the string, but got \ at path: $[0]
JSON input: [{\"chapterID\":45023,\"ChapterN..... 
```

**Comment by Smol-Ame** [comment]
@andy3469 make a new issue request instead of commenting on a merged PR.
