### PR TITLE
Koharu: Moved to src/all | Spyfakku: Fixed Errors, Added "Per page" Filter | Pururin: Re-added, Fixed Some Details

### LINKED ISSUE #5738: spyfakku eror jsondecodingexceotion
### Source information

https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

### Source language

English 

### Steps to reproduce

Fix this issue

### Expected behavior

Screenshot_2024-10-28-16-05-21-52_551f7f0ca926862b368845ce7ee433aa

### Actual behavior

fix please 

### Mihon/Tachiyomi version

0.17.0

### Android version

11

### Other details

fix okay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #5914: Koharu: Filter non-English content
### Source information

Koharu 1.4.8

### Source language

English

### Steps to reproduce

1. Open Koharu
2. Search for content with the universal tag "Japanese"
3. Open any of the results

### Expected behavior

Since the source is marked as English, the Japanese stuff shouldn't appear.

### Actual behavior

Japanese content appears.

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #5957: SchaleNetwork Filter by Page does not behave correctly
### Source information

SchaleNetwork 1.4.9

### Source language

English

### Steps to reproduce

1. Open SchaleNetwork
2. Fill `>20` as input for `Filter by pages` field
3. Tap `Filter` button

### Expected behavior

Only entries with more than 20 pages shown

### Actual behavior

Entries with less than 20 pages still appear

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 14

### Other details

- Inputting `pages:>20` as input for `Filter by Pages` field yields the same result as above
- Inputting `pages:>20` as input for `Search` returns nothing
- Inputting `pages:>20` as input for `Search` _directly on their website_ works properly and will show entries with more than 20 pages 
- Inputting number as input for Filter by Pages field, without `<` or `>` (e.g `20`) will show entries with _exact number of pages_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #5984: SchaleNetwork Add Open by Default Links
### Source name

SchaleNetwork

### Source language

English

### Describe your suggested feature

Add SchaleNetwork mirrors to open by default menu for Android App Settings

Mirror Details: https://rentry.org/schalenet

Mirrors: 
https://hoshino.one/
https://shupogaki.moe/
https://seia.to/
https://niyaniya.moe/

Dead Mirror that can be removed: https://koharu.to/

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #5738
Closes #5914
Closes #5957
Closes #5984

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt [hunk 1]
```diff
@@ -28,19 +28,20 @@ import uy.kohesive.injekt.injectLazy
 import java.text.SimpleDateFormat
 import java.util.Locale
 
-class Koharu : HttpSource(), ConfigurableSource {
-    override val name = "SchaleNetwork"
+class Koharu(
+    override val lang: String = "all",
+    private val searchLang: String = "",
+    override val id: Long = 2385208600973708857,
+) : HttpSource(), ConfigurableSource {
```
Comment (FourTOne5) [inline src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt]: Make it an abstract class and override the id for "en" so we don't need to hardcode the id for "all" and "jp"

File: src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt [hunk 2]
```diff
@@ -143,6 +144,7 @@ class Koharu : HttpSource(), ConfigurableSource {
         val url = apiBooksUrl.toHttpUrl().newBuilder().apply {
             val terms: MutableList<String> = mutableListOf()
 
+            if (lang != "all") terms += "language!:\"$searchLang\""
```
Comment (FourTOne5) [inline src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt:148]: Make the query into a variable?

**Review by FourTOne5 — CHANGES_REQUESTED** [review]

File: src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt (hunk 2 above)
Comment (KenjieDec) [reply src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt:148]: Sorry, I don't understand what you mean by that. Could you please explain further? Thank you :pray:

File: src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt (hunk 1 above)
Comment (KenjieDec) [reply src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt]: Hello, can I just use `override val id = if (lang == "en") 1484902275639232927 else super.id` instead of converting the `Koharu` class to an abstract class? Thank you.

Comment (FourTOne5) [reply src/all/koharu/src/eu/kanade/tachiyomi/extension/all/koharu/Koharu.kt]: That's actually better honestly.

**Review by AwkwardPeak7 — APPROVED** [review]
