### PR TITLE
YakshaScans: Fix 403 Error

### LINKED ISSUE #6634: Http 403 check website in webview for YakshaScans
### Source information

YakshaScans 1.4.37

### Source language

English

### Steps to reproduce

1. Click series I want to read, and click chapter>Get 403 error
2. Pull down to reload, doesnt update for new chapters>get 403
3. Click webview, loads fine, no captcha and chapters work fine
4. Click source>403, but webview works

Screenshot_20241215_234851_TachiyomiSY
Screenshot_20241215_234913_TachiyomiSY
Screenshot_20241215_234937_TachiyomiSY

### Expected behavior

Clicking chapter should load the chapter to read or reloading a chapter for new chapters should show the new chapters

### Actual behavior

403 error upon clicking & updating chapters, also doesn't show new chapters.

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 14

### Other details

I do have mihon downloaded and updated to 0.17.1 and it's the same issue, I use SY as my main though.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #6634

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by vetleledaal — APPROVED** [review]

File: src/en/yakshascans/src/eu/kanade/tachiyomi/extension/en/yakshascans/YakshaScans.kt [hunk 1]
```diff
@@ -12,8 +19,45 @@ class YakshaScans : Madara(
...
+
+        val challengeResponse = chain.proceed(challengeReq)
+        challengeResponse.close()
+        if (challengeResponse.code != 200) throw IOException("Failed to bypass js challenge!")
+
+        return chain.proceed(request)
+    }
+
+    private tailrec fun fetchToken(chain: Interceptor.Chain, attempt: Int = 0): String {
+        if (attempt > 5) throw IOException("Failed to fetch challenge token!")
```
Comment (AwkwardPeak7) [inline src/en/yakshascans/src/eu/kanade/tachiyomi/extension/en/yakshascans/YakshaScans.kt:46]: ~`attempt` doesn't seem to be updated anywhere?~
