### PR TITLE
LeituraManga: Fix mangaDetails, chapters and pages

### LINKED ISSUE #13633: Leitura Manga: `HTTP 404` error on series, `Nenhuma página encontrada` error
### Source information

Leitura mangá 

### Source language

Português 

### Steps to reproduce

Atualizei o aplicativo e quando eu fui ler meu mangá o que eu uso é o leitura mangá não está pegando, mas o site está funcionando.

Image
Image

### Expected behavior

Abrir

### Actual behavior

Não abre

### Mihon/Mihon fork version

19.4

### Android version

Android 11

### Other details

Image
Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #13633

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — COMMENTED** [review]
consider extracting nextjs chunks via `keiyoushi.utils.extractNextJs`

File: src/pt/leituramanga/src/eu/kanade/tachiyomi/extension/pt/leituramanga/LeituraManga.kt [hunk 1]
```diff
@@ -97,38 +112,93 @@ class LeituraManga : HttpSource() {
...
+                self.__next_f.map(it => it[it.length - 1]).join('')
+                """.trimIndent(),
+            ) as String
+        }
+
+        val encryptedContent = extractNextJs<EncryptedContent>()
+
+        val payload = when {
+            encryptedContent != null && encryptedContent.payload.startsWith(PREFIX_SALT) -> encryptedContent.payload
+            else -> ENCRYPTED_CONTENT_REGEX.find(script)?.groupValues?.last()
```
Comment (AwkwardPeak7) [inline src/pt/leituramanga/src/eu/kanade/tachiyomi/extension/pt/leituramanga/LeituraManga.kt:191]: I asked for `extractNextJs` so usage of QuickJs may be avoided when possible.

Comment (choppeh) [reply src/pt/leituramanga/src/eu/kanade/tachiyomi/extension/pt/leituramanga/LeituraManga.kt:191]: I couldn't remove QuickJS because the encrypted content doesn't always follow a single JavaScript object structure:

Example
```json
{"payload": "U2FsdGVkX1..."}
```
or
```json
{"payload": "$4"}
["U2FsdGVkX1..."]
```

In the 2nd example, it is something like a reference

**Review by AwkwardPeak7 — APPROVED** [review]
