### PR TITLE
Philia Scans (EN) fixed

### LINKED ISSUE #14188: Philia Scans: `No results found` error on Popular page & search results
### Source information

Philia Scans 1.4.46

### Source language

English

### Steps to reproduce

When I want to refresh the manga from the popular section, the error 404 appear and the same appear in the webview

Image
Image

### Expected behavior

The 404 error appear from only the popular section of the extention and not from the recent section

This is from the recent section :

Image

### Actual behavior

And this is from the popular section :

Image

### Mihon/Mihon fork version

Tachimanga v4.14(437)

### Android version

IOS26

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14188

### Changes made:
* Fixed chapter parsing (prevented `NullPointerException` caused by hidden chapter lists in the new UI)
* Disabled `useNewChapterEndpoint` as chapters are now embedded directly in the HTML
* Fixed Popular and Latest routing to point to the new `/all-mangas/` and `/recently-updated/` pages
* Re-wrote the Search and Filter system to match the site's new layout:
  * Text searches now POST to the `live_search` AJAX endpoint
  * Genre filters now route directly to their specific `/manga-genre/{genre}` URL paths
  * Removed broken/obsolete filters (Type, Sort, Year)
* Incremented `overrideVersionCode`

## Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 1]
```diff
@@ -19,68 +25,104 @@ class PhiliaScans :
...
-    override fun popularMangaRequest(page: Int): Request {
-        val url = baseUrl.toHttpUrl().newBuilder()
-            .addQueryParameter("post_type", "wp-manga")
-            .addQueryParameter("s", "")
-            .addQueryParameter("sort", "most_viewed")
-            .addQueryParameter("paged", page.toString())
-            .build()
-        return GET(url, headers)
-    }
+    override val versionId: Int = 4
```
Comment (bapeey) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: This will force users to migrate the manga they have saved. Is that what you wanted to do?

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 2]
```diff
@@ -19,68 +25,104 @@ class PhiliaScans :
...
+
+            // Safety check to ensure we actually got JSON back
+            if (!jsonString.trim().startsWith("{")) return MangasPage(emptyList(), false)
+
+            val jsonObject = json.parseToJsonElement(jsonString).jsonObject
+            val results = jsonObject["results"]?.jsonArray ?: return MangasPage(emptyList(), false)
+
+            val mangas = results.mapNotNull { element ->
+                val html = element.jsonPrimitive.content
+                val doc = Jsoup.parse(html)
```
Comment (bapeey) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: If it's not a full html use `parseBodyFragment` instead. Also, pass the baseUrl so Jsoup can handle absolute URLs

```suggestion
                val doc = Jsoup.parseBodyFragment(html, baseUrl)
```

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 3]
```diff
@@ -19,68 +25,104 @@ class PhiliaScans :
...
-    override fun popularMangaNextPageSelector() = ".pagination li:not(.disabled) .page-link[rel=next]"
+    override fun popularMangaNextPageSelector() = ".pagination a.page-link[rel=next]"
 
     override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/recently-updated/?page=$page", headers)
 
+    private fun getSearchNonce(): String {
+        if (searchNonce.isNotEmpty()) return searchNonce
+        try {
+            val document = client.newCall(GET(baseUrl, headers)).execute().asJsoup()
+            val script = document.select("script:containsData(liveSearchData)").firstOrNull()?.data()
```
Comment (bapeey) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]:
```suggestion
            val script = document.selectFirst("script:containsData(liveSearchData)")?.data()
```

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 4]
```diff
@@ -21,66 +27,102 @@ class PhiliaScans :
...
 
     override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/recently-updated/?page=$page", headers)
 
+    private fun getSearchNonce(): String {
+        if (searchNonce.isNotEmpty()) return searchNonce
+        try {
+            val document = client.newCall(GET(baseUrl, headers)).execute().asJsoup()
+            val script = document.selectFirst("script:containsData(liveSearchData)")?.data()
+            if (script != null) {
+                searchNonce = script.substringAfter("\"nonce\":\"").substringBefore("\"")
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: Is this nonce on every page? Can you try to extract it from a network interceptor instead? To hopefully remove the need for an extra request.

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 5]
```diff
@@ -21,66 +27,102 @@ class PhiliaScans :
...
     override fun popularMangaSelector() = ".original .unit"
     override val popularMangaUrlSelector = ".info a.c-title"
     override val popularMangaUrlSelectorImg = ".poster img:not(.flag-icon)"
-    override fun popularMangaNextPageSelector() = ".pagination li:not(.disabled) .page-link[rel=next]"
+    override fun popularMangaNextPageSelector() = ".pagination a.page-link[rel=next]"
 
     override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/recently-updated/?page=$page", headers)
 
+    private fun getSearchNonce(): String {
+        if (searchNonce.isNotEmpty()) return searchNonce
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: Can this nonce be reused? If yes then this caching is fine.

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 6]
```diff
@@ -21,66 +27,102 @@ class PhiliaScans :
...
-                is GenreList -> {
-                    filter.state.filter { it.state }.forEachIndexed { index, item ->
-                        url.addQueryParameter("genre[$index]", item.id)
-                    }
+    override fun searchMangaParse(response: Response): MangasPage {
+        if (response.request.url.encodedPath.contains("admin-ajax.php")) {
+            val jsonString = response.body.string()
+
+            // Safety check to ensure we actually got JSON back
+            if (!jsonString.trim().startsWith("{")) return MangasPage(emptyList(), false)
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: Not needed. More expressive error message is preferred.

More expressive being `.parseToJsonElement` exploding.

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 7]
```diff
@@ -21,66 +27,102 @@ class PhiliaScans :
...
+
+            val jsonObject = json.parseToJsonElement(jsonString).jsonObject
+            val results = jsonObject["results"]?.jsonArray ?: return MangasPage(emptyList(), false)
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: Use a DTO?

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 8]
```diff
@@ -107,115 +149,63 @@ class PhiliaScans :
...
 
-    override fun chapterListSelector() = "li.item:not(:has(a[href='#'])):not(:has(.fa-coins))"
+    override fun chapterListSelector() = "div.list-body-hh li.free-chap"
 
     override fun chapterFromElement(element: Element): SChapter = SChapter.create().apply {
         val urlElement = element.selectFirst("a")!!
         setUrlWithoutDomain(urlElement.absUrl("href"))
-        name = element.selectFirst("zebi")!!.text()
+        name = element.selectFirst("zebi")?.text()?.removeSuffix(":")?.trim()
+            ?: urlElement.ownText().trim().ifEmpty { urlElement.text().trim() }
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]: Both are already trimmed.
```suggestion
            ?: urlElement.ownText().ifEmpty { urlElement.text() }
```

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 9]
```diff
@@ -107,115 +162,69 @@ class PhiliaScans :
...
-    )
-
-    override val genreConditionFilterOptions: Map<String, String> = mapOf(
-        intl["genre_condition_filter_or"] to "",
-        intl["genre_condition_filter_and"] to "and",
-    )
 }
+
+@Serializable
+data class SearchResponseDto(
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]:
```suggestion
class SearchResponseDto(
```

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 10]
```diff
@@ -21,66 +25,117 @@ class PhiliaScans :
...
+            val mangas = dto.results.mapNotNull { html ->
+                val doc = Jsoup.parseBodyFragment(html, baseUrl)
+                val a = doc.selectFirst("a") ?: return@mapNotNull null
+                val img = doc.selectFirst("img")
+                val title = doc.selectFirst(".search-result-title")?.text()
+                    ?: img?.attr("alt")
+                    ?: return@mapNotNull null
+
+                SManga.create().apply {
+                    setUrlWithoutDomain(a.attr("href"))
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]:
```suggestion
                    setUrlWithoutDomain(a.absUrl("href"))
```
```suggestion
                    setUrlWithoutDomain(a.attr("abs:href"))
```

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 11]
```diff
@@ -21,66 +25,117 @@ class PhiliaScans :
...
+                    this.title = title
+                    thumbnail_url = img?.attr("src")
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]:
```suggestion
                    thumbnail_url = img?.absUrl("src")
```
```suggestion
                    thumbnail_url = img?.attr("abs:src")
```

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 12]
```diff
@@ -21,66 +25,117 @@ class PhiliaScans :
...
     override fun searchMangaSelector() = popularMangaSelector()
-    override fun searchMangaParse(response: Response): MangasPage = popularMangaParse(response)
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        if (response.code == 404) return MangasPage(emptyList(), false)
+
+        if (response.request.url.encodedPath.contains("admin-ajax.php")) {
+            val jsonString = response.body.string()
+
+            val dto = json.decodeFromString<SearchResponseDto>(jsonString)
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt:130]:
```suggestion
            val dto = jsonString.parseAs<SearchResponseDto>()
```
(requires import, maybe)

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 13]
```diff
@@ -21,66 +25,117 @@ class PhiliaScans :
...
+        }
+
+        return popularMangaRequest(page)
     }
 
     override fun searchMangaSelector() = popularMangaSelector()
-    override fun searchMangaParse(response: Response): MangasPage = popularMangaParse(response)
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        if (response.code == 404) return MangasPage(emptyList(), false)
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt:125]: Make sure the `fetch*` method is overridden so it uses `.asObservable()` instead of `.asObservableSuccess()`.

Haven't checked the other functions, but if they are all valid then you should do something similar there.

File: src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt [hunk 14]
```diff
@@ -21,66 +25,117 @@ class PhiliaScans :
...
+    private var searchNonce: String = ""
+
+    private val nonceRegex = """liveSearchData[^}]*"nonce"\s*:\s*"([^"]+)"""".toRegex()
+
+    override val client = super.client.newBuilder()
+        .addInterceptor { chain ->
+            val response = chain.proceed(chain.request())
+            if (searchNonce.isEmpty() && response.header("Content-Type")?.contains("text/html") == true) {
+                // Peek the body so it isn't consumed for the actual parsing downstream
+                val bodyString = response.peekBody(1024 * 1024L).string()
```
Comment (vetleledaal) [inline src/en/philiascans/src/eu/kanade/tachiyomi/extension/en/philiascans/PhiliaScans.kt]:
```suggestion
                val bodyString = response.peekBody(Long.MAX_VALUE).string()
```

**Review by vetleledaal — APPROVED** [review]
