### PR TITLE
AlgodaoDoce: Fix status

### LINKED ISSUE #7220: Algodão Doce: Fix status showing as "Unknown"
### Source name

Algodão Doce

### Source language

Portuguese

### Describe your suggested feature

The status in all manga from this extension is showing up as unknown even when it does have the status on the website.

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #7220 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/algodaodoce/src/eu/kanade/tachiyomi/extension/pt/algodaodoce/AlgodaoDoce.kt [hunk 1]
```diff
@@ -11,5 +14,111 @@ class AlgodaoDoce : Madara(
     dateFormat = SimpleDateFormat("MMMM d, yyyy", Locale("pt", "BR")),
 ) {
     override val useLoadMoreRequest = LoadMoreStrategy.Never
+
     override val useNewChapterEndpoint = true
+
+    override fun mangaDetailsParse(document: Document): SManga {
```
Comment (AwkwardPeak7) [inline src/pt/algodaodoce/src/eu/kanade/tachiyomi/extension/pt/algodaodoce/AlgodaoDoce.kt]: call super method then change anything needed here

```
override fun mangaDetailsParse(document: Document): SManga {
    return super.mangaDetailsParse(document).apply {
        ...
    }
}

Comment (lordenecromante) [reply src/pt/algodaodoce/src/eu/kanade/tachiyomi/extension/pt/algodaodoce/AlgodaoDoce.kt]: Fix it. I only updated the mangaDetailsSelectorStatus.

**Review by AwkwardPeak7 — APPROVED** [review]
