### PR TITLE
TheManga (ID): Update for redesign

### LINKED ISSUE #13314: TheManga HTTP 404
### Source information

TheManga 1.4.45

### Source language

Indonesia

### Steps to reproduce

Image

Image

### Expected behavior

The chapter or manga title is supposed to be available, but it isn’t there and instead it shows HTTP 404

### Actual behavior

Http 404

### Mihon/Mihon fork version

Mihon 1.19.3

### Android version

Android 15

### Other details

I already checked and there were no reports using the keyword Themanga.

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AaronDeimos**
Close: #13314 
Ai assisted

- New site design doesn't have popular or any sorting.
- It only shows latest manga, So set `supportsLatest` to false.
- The manga urls are same, Chapter urls changed.

- So added compatibility support for the old chapter urls.

I don't know the language so used ai to translate the error message let me know if i should change it

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt [hunk 1]
```diff
@@ -1,8 +1,172 @@
...
+        return GET(url, headers)
+    }
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        val document = response.document()
+
+        val mangas = document.select("a.manga-card").map { element ->
+            SManga.create().apply {
+                setUrlWithoutDomain(element.attr("href"))
+                title = element.selectFirst(".card-title")?.text().orEmpty()
```
Comment (AwkwardPeak7) [inline src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt]:
```suggestion
                title = element.selectFirst(".card-title")!.text()
```
title is mandatory

File: src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt [hunk 2]
```diff
@@ -1,8 +1,172 @@
...
+        val hasNextPage = document.selectFirst("a[rel=next]") != null
+        return MangasPage(mangas, hasNextPage)
+    }
+
+    // =========================== Manga Details ============================
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.document()
+
+        return SManga.create().apply {
+            title = document.selectFirst(".hero-title")?.text().orEmpty()
```
Comment (AwkwardPeak7) [inline src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt]: same here

File: src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt [hunk 3]
```diff
@@ -1,8 +1,172 @@
...
+    // ============================== Chapters ==============================
+    override fun chapterListRequest(manga: SManga): Request = GET("$baseUrl${manga.url}?all=1", headers)
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.document()
+
+        return document.select(".chapter-row").map { element ->
+            SChapter.create().apply {
+                setUrlWithoutDomain(element.attr("data-href"))
+                name = element.selectFirst(".chapter-title")?.text().orEmpty()
```
Comment (AwkwardPeak7) [inline src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt]: same here

File: src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt [hunk 4]
```diff
@@ -1,8 +1,172 @@
...
+                date_upload = element.selectFirst("[data-local-time]")
+                    ?.attr("data-local-time")
+                    ?.let(dateFormat::tryParse) ?: 0L
+            }
```
Comment (AwkwardPeak7) [inline src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt]: simply pass the nullable string to tryParse directly

File: src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt [hunk 5]
```diff
@@ -1,8 +1,172 @@
...
+    // ============================== Filters ===============================
+    override fun getFilterList(): FilterList = FilterList(
+        StatusFilter(),
+        GenreFilter(),
+        Filter.Separator(),
+        OtherFilterGroup(),
+    )
+
+    // ============================== Utils ===============================
+    private fun Response.document(): Document = Jsoup.parse(body.string(), request.url.toString())
```
Comment (AwkwardPeak7) [inline src/id/themanga/src/eu/kanade/tachiyomi/extension/id/themanga/TheManga.kt]: use `Response.asJsoup()` instead

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
