### PR TITLE
Azora: Fix description text

### LINKED ISSUE #7163: Azora: No descriptions in titles
### Source information

Azora  1.4.44

### Source language

Arabic 

### Steps to reproduce

when i enter a manhwa page i find the story section is empty

### Expected behavior

when i enter a manhwa page i have to find the summary of the story

### Actual behavior

the summary section is always empty on this extension

### Mihon/Tachiyomi version

Tachiyomi 0.15.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #7163 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt [hunk 1]
```diff
@@ -8,6 +8,7 @@ class Azora : Madara("Azora", "https://azoramoon.com", "ar") {
     override val mangaSubString = "series"
     override val useNewChapterEndpoint = false
     override fun chapterListSelector() = "li.wp-manga-chapter:not(.premium-block)" // Filter fake chapters
+    override val mangaDetailsSelectorDescription = "div.tab-summary > div.summary_content_wrap > div > div.post-content > div.manga-summary"
```
Comment (vetleledaal) [inline src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt]: That selector is very specific and will likely break in the future.

Consider:
```suggestion
    override val mangaDetailsSelectorDescription = ".manga-summary"
```

Comment (lordenecromante) [reply src/ar/azora/src/eu/kanade/tachiyomi/extension/ar/azora/Azora.kt]: Fix it

**Review by vetleledaal — APPROVED** [review]
