### PR TITLE
BacaKomik: fix NullPointerException

### LINKED ISSUE #10035: BacaKomik: `NullPointerException:null` error on Latest tab
### Source information

BacaKomik  1.14.12

### Source language

Indonesia

### Steps to reproduce

I cant do anything

### Expected behavior

Image

### Actual behavior

This extensions need fix

Image

### Mihon/Tachiyomi version

TachiyomiSY 1.12.0

### Android version

Android 10

### Other details

Please fix dear admin, thankyou for your help 🙏

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MuhamadSyabitHidayattulloh**
Closes: https://github.com/keiyoushi/extensions-source/issues/10035
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt [hunk 1]
```diff
@@ -59,7 +59,7 @@ class BacaKomik : ParsedHttpSource() {
         val manga = SManga.create()
         manga.setUrlWithoutDomain(element.select("div.animposx > a").first()!!.attr("href"))
         manga.title = element.select(".animposx .tt h4").text()
-        manga.thumbnail_url = element.select("div.limit img").imgAttr()
+        manga.thumbnail_url = element.select("div.limit img").imgAttr() ?: ""
```
Comment (AwkwardPeak7) [inline src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt]:
```suggestion
        manga.thumbnail_url = element.selectFirst("div.limit img")?.imgAttr()
```
thumbnail is nullable

File: src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt [hunk 2]
```diff
@@ -115,7 +115,7 @@ class BacaKomik : ParsedHttpSource() {
         manga.genre = genres.joinToString(", ")
         manga.status = parseStatus(document.select(".infox .spe span:contains(Status)").text())
         manga.description = descElement.select("p").text().substringAfter("bercerita tentang ")
-        manga.thumbnail_url = document.select(".thumb > img:nth-child(1)").imgAttr()
+        manga.thumbnail_url = document.select(".thumb > img:nth-child(1)").imgAttr() ?: ""
```
Comment (AwkwardPeak7) [inline src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt]: here too

File: src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt [hunk 3]
```diff
@@ -330,7 +330,7 @@ class BacaKomik : ParsedHttpSource() {
         else -> attr("abs:src")
     }
 
-    private fun Elements.imgAttr(): String = this.first()!!.imgAttr()
+    private fun Elements.imgAttr(): String? = this.first()?.imgAttr()
```
Comment (AwkwardPeak7) [inline src/id/bacakomik/src/eu/kanade/tachiyomi/extension/id/bacakomik/BacaKomik.kt]:
```suggestion
    private fun Element.imgAttr(): String = this.imgAttr()
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
