### PR TITLE
MyHentaiComics: fix extension

### LINKED ISSUE #2878: MyHentaiComics - HTTP Error: 404
### Source information

MyHentaiComics 1.4.2

### Source language

English

### Steps to reproduce

1. Open the extension

2. Immediately a "HTTP 404" message pops up

### Expected behavior

The extension should work properly, offering your manga/comics catalog to select and read/download.

### Actual behavior

The extension doesn't work. It does not show its respective manga/comics catalog.

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 12

### Other details

I uninstalled and reinstalled the extension, as well as clearing cache and cookies, but it didn't work.

In "**WebView**" the site is running smoothly, but not so in the extension within the app.

Pictures of the problem:
Screenshot_20240506-222047_Mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by dngonz**
Closes #2878

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/myhentaicomics/src/eu/kanade/tachiyomi/extension/en/myhentaicomics/MyHentaiComics.kt [hunk 1]
```diff
@@ -22,85 +21,62 @@ class MyHentaiComics : ParsedHttpSource() {
...
-            GET("$baseUrl/index.php/search?q=$query&page=$page", headers)
-        } else {
-            var url = baseUrl
-            for (filter in if (filters.isEmpty()) getFilterList() else filters) {
-                when (filter) {
-                    is GenreFilter -> url += filter.toUriPart() + "?page=$page"
-                    else -> {}
-                }
+        if (query.isNotEmpty()) {
+            return GET("$baseUrl/search/$page?query=$query", headers)
```
Comment (AwkwardPeak7) [inline src/en/myhentaicomics/src/eu/kanade/tachiyomi/extension/en/myhentaicomics/MyHentaiComics.kt]: use httpurl builder

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/en/myhentaicomics/src/eu/kanade/tachiyomi/extension/en/myhentaicomics/MyHentaiComics.kt [hunk 2]
```diff
@@ -22,85 +22,67 @@ class MyHentaiComics : ParsedHttpSource() {
...
+        val tags = document.selectFirst("div.comic-description")
+
         return SManga.create().apply {
-            artist = tags.first.joinToString { it.text().substringAfter(" ") }
-            author = artist
-            genre = tags.second.joinToString { it.text() }
-            thumbnail_url = document.select("img.g-thumbnail").first()!!.attr("abs:src").replace("/thumbs/", "/resizes/")
+            author = tags?.selectFirst("div:containsOwn(Artists) a")?.text()
+            genre = tags?.select("div:containsOwn(Categories) a")?.joinToString { it.text() }
+            status = SManga.COMPLETED
```
Comment (vetleledaal) [inline src/en/myhentaicomics/src/eu/kanade/tachiyomi/extension/en/myhentaicomics/MyHentaiComics.kt:82]: Also set `update_strategy` to `UpdateStrategy.ONLY_FETCH_ONCE`?

Comment (dngonz) [reply src/en/myhentaicomics/src/eu/kanade/tachiyomi/extension/en/myhentaicomics/MyHentaiComics.kt:82]: Added

**Review by vetleledaal — APPROVED** [review]
