### PR TITLE
Taurus Fansub: fixes after domain and layout change

### LINKED ISSUE #11793: Taurus Fansub: New website URL
### Source information

Taurus fansub 1.4.51

### Source language

Español 

### Source new URL

https://lectortaurus.com/

### Other details

_No response_

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes the extension after the site moved to a new domain and changed its layout.

- Updated domain
- Fixed selectors for popular/latest and manga details
- Fixed manga genre parsing so genre filtering works properly
- Corrected date format typo

Closes #11793 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt [hunk 1]
```diff
@@ -2,17 +2,16 @@ package eu.kanade.tachiyomi.extension.es.taurusfansub
...
 import java.util.Locale
 import java.util.concurrent.TimeUnit
 
 class TaurusFansub : Madara(
     "Taurus Fansub",
-    "https://taurus.topmanhuas.org",
+    "https://lectortaurus.com",
     "es",
-    dateFormat = SimpleDateFormat("dd/MM/yyy", Locale.ROOT),
+    dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.ROOT),
```
Comment (vetleledaal) [inline src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt:15]: FYI, this is not a typo and [actually allowed](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) according to the docs.

> For parsing, if the number of pattern letters is more than 2, the year is interpreted literally, regardless of the number of digits.

You don't need to change anything, just resolve on ACK.

File: src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt [hunk 2]
```diff
@@ -21,21 +20,24 @@ class TaurusFansub : Madara(
...
-            "Completado" -> { SManga.COMPLETED }
-            else -> { SManga.UNKNOWN }
-        }
-        manga.artist = document.select("div.site-content div.summary_content div.tags-content").text()
+    override fun parseGenres(document: Document): List<Genre> {
+        return document.select(".genres-filter .options a")
+            .mapNotNull { element ->
+                val id = element.attr("href")
+                    .substringAfter("genre=", "")
+                    .substringBefore("&")
```
Comment (vetleledaal) [inline src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt]: Use `HttpUrl` for this,
```kt
val id = element.absUrl("href").toHttpUrlOrNull()?.queryParameter("genre")
```

File: src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt (hunk 1 above)
Comment (ghost) [reply src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt:15]: Thanks for the clarification, resolved!

File: src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt (hunk 2 above)
Comment (ghost) [reply src/es/taurusfansub/src/eu/kanade/tachiyomi/extension/es/taurusfansub/TaurusFansub.kt]: Refactored to use `HttpUrl` as suggested, thanks!

**Review by vetleledaal — APPROVED** [review]
