### PR TITLE
Fix InfraFandub extension

### LINKED ISSUE #10774: the infraFandub source gives an error
### Source information

InfraFandub 1.4.45 

### Source language

Spanish 

### Steps to reproduce

The source is not responding but if I go to the website everything seems to be in correct order 
https://infrafandub.com/

Image

Image

### Expected behavior

The website is navigated normally, but the font does not respond, no matter how much I load it, and it gives an error. 

### Actual behavior

So the source directly gives an error but the web page works 

### Mihon/Tachiyomi version

Mihon 0.19.1 

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Useles5**
Closes:  #10774

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/infrafandub/src/eu/kanade/tachiyomi/extension/es/infrafandub/InfraFandub.kt [hunk 1]
```diff
@@ -19,5 +21,28 @@ class InfraFandub : Madara(
...
+    override val mangaDetailsSelectorThumbnail = "aside.sidebar img.series-cover"
+    override val mangaDetailsSelectorStatus = "div.series-details div.detail-item:contains(Estado) span.detail-value"
+
+    override fun chapterListSelector() = "div.chapters-list a.chapter-item"
+
+    override fun chapterFromElement(element: Element): SChapter {
+        val chapter = SChapter.create()
+        with(element) {
+            chapter.setUrlWithoutDomain(attr("href"))
+            chapter.name = selectFirst("span.chapter-number")?.text() ?: ""
```
Comment (AwkwardPeak7) [inline src/es/infrafandub/src/eu/kanade/tachiyomi/extension/es/infrafandub/InfraFandub.kt]:
```suggestion
            chapter.setUrlWithoutDomain(absUrl("href"))
            chapter.name = selectFirst("span.chapter-number")!!.text()
```

**Review by vetleledaal — APPROVED** [review]
