### PR TITLE
[EN] Mangakakalot fix: Resolves 403 and other previous issues.

### LINKED ISSUE #8714: Mangakakalot (or Mangabox theme): Implement/tweak rate-limit
### Source information

Mangakakalot 1.4.12

### Source language

English

### Steps to reproduce

Happens with the daily update

### Expected behavior

Should update every manga entry

### Actual behavior

At a certain point, the latter part of the list gets error 429 (mangakakalot only)

### Mihon/Tachiyomi version

Beta r7213

### Android version

Android 12

### Other details

Need ratelimit/slowdown to get the list fully checked

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13106: Mangakakalot: `HTTP 429` / `HTTP 403` error
### Source information

Mangakakalot 1.4.16

### Source language

English

### Steps to reproduce

1. Open Any Manga Title on Mangakakalot
2. Try to reload
3. It will show a popup "HTTP 403, check website on WebView"
4. Opening it via WebView, the page is loading

Image

### Expected behavior

If you reload the manga it will also show the HTTP 403 error and there is no any update.

### Actual behavior

Reloading the manga to get new chapter will popup the HTTP 403 error.

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13185: HTTP 403 error Mangakakalot chapter refresh
### Source information

Mangakakalot 1.4.16

### Source language

English

### Steps to reproduce

1. Open any entry in mangakakalot 
2. Swipe down to refresh 
3. See error appear

### Expected behavior

Chapters should refresh.

### Actual behavior

Chapters do not refresh 
Already loaded chapters from before issue can be read. No new chapters can be pulled.

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 16

### Other details

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13224: HTTP 403, Check website in Web View
### Source information

MangaKakalot

### Source language

English

### Steps to reproduce

I cannot update any of the chapters. Even after opening in Webview (the website does load and I am able to clear the capcha prompted), I still encounter the same error

### Expected behavior

The error should clear after opening in webview

### Actual behavior

The error still persists.

### Mihon/Tachiyomi version

Mihon 0.19.3

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by NepThunder**
### Cause:
- URL slug is ID-based instead of title-based
- ~~Chapter data is provided via API instead of embedded in HTML~~
- ~~Images were protected by Hotlink protection~~
- ~~API was behing WAF+anti-bot~~

### Changes:
- Solves broken chapter loading caused by the URL structure migration.
- Fixes 404 errors for old entries and maintains backward compatibility.
- Fixes ID-based slug, converts them to title based
- Fixes image download failures in large chapters.
- ~~Adds referrer to bypass hotlink protection~~
- ~~Fixes Cloudflare blocking for chapter and manga API requests.~~

Addresses issues:
closes: #13224 
closes #8714 
closes #13106 [closed] 
closes #13185 [closed]

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt [hunk 1]
```diff
@@ -1,30 +1,208 @@
...
-        private const val MIGRATE_MESSAGE = "Migrate this entry from \"Mangakakalot\" to \"Mangakakalot\" to continue reading"
+
+    override fun mangaDetailsParse(document: Document): SManga {
+        val manga = super.mangaDetailsParse(document)
+
+        val pageUrl = document.location()
+        val actualSlug = if (pageUrl.contains("/manga/")) {
+            pageUrl.substringAfter("/manga/")
+                .substringBefore("?")
+                .substringBefore("#")
```
Comment (vetleledaal) [inline src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt]: Use `HttpUrl` for this.

File: src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt [hunk 2]
```diff
@@ -1,30 +1,208 @@
...
+        return manga
+    }
+
+    /* ================================
+     * Chapter List
+     * ================================ */
+
+    override fun chapterListRequest(manga: SManga): Request {
+        val currentSlug = manga.url.substringAfterLast("/")
+        val isIdSlug = currentSlug.matches(Regex("^[a-z]{2}\\d+$"))
```
Comment (vetleledaal) [inline src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt]: Move regex to class.

File: src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt [hunk 3]
```diff
@@ -1,30 +1,208 @@
...
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val chapters = mutableListOf<SChapter>()
+        val body = response.body.string()
+        if (body.isEmpty()) return chapters
+
+        val json = JSONObject(body)
+        if (!json.optBoolean("success")) return chapters
+
+        val data = json.optJSONObject("data") ?: return chapters
+        val jsonChapters = data.optJSONArray("chapters") ?: return chapters
```
Comment (vetleledaal) [inline src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt]: Use DTOs for this.

File: src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt [hunk 4]
```diff
@@ -1,30 +1,208 @@
...
+
+    /* ================================
+     * Page List
+     * ================================ */
+
+    override fun pageListParse(document: Document): List<Page> = document
+        .select("div.container-chapter-reader img")
+        .mapIndexedNotNull { i, img ->
+            val url = img.attr("abs:src").ifEmpty { img.attr("abs:data-src") }
+            if (url.isNotEmpty()) Page(i, "", url) else null
```
Comment (vetleledaal) [inline src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt]:
```suggestion
            if (url.isNotEmpty()) Page(i, imageUrl = url) else null
```

File: src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt [hunk 5]
```diff
@@ -1,30 +1,208 @@
...
+    override fun intercept(chain: Interceptor.Chain): Response {
+        val req = chain.request()
+        val url = req.url.toString()
+
+        if (url.contains("/api/manga/")) {
+            val segments = req.url.pathSegments
+            val idx = segments.indexOf("manga")
+
+            if (idx != -1 && idx + 1 < segments.size) {
+                val slug = segments[idx + 1]
```
Comment (vetleledaal) [inline src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt]: Don't juggle indices here. You can use similar logic as you use elsewhere.
```kt
        val slug = req.url.pathSegments
            .dropWhile { it != "manga" }
            .getOrNull(1)
```

File: src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt [hunk 6]
```diff
@@ -1,30 +1,208 @@
...
+            val item = jsonChapters.getJSONObject(i)
+            val chapter = SChapter.create()
+
+            chapter.name = item.optString("chapter_name", "Chapter")
+            chapter.chapter_number = item.optDouble("chapter_num", 0.0).toFloat()
+            chapter.url = "/manga/$slug/${item.optString("chapter_slug")}"
+
+            item.optString("updated_at").takeIf { it.isNotEmpty() }?.let {
+                chapter.date_upload =
+                    runCatching { jsonDateFormat.parse(it)?.time }.getOrNull() ?: 0L
```
Comment (vetleledaal) [inline src/en/mangakakalot/src/eu/kanade/tachiyomi/extension/en/mangakakalot/Mangakakalot.kt]: Use `.tryParse` from `keiyoushi.utils`.

**Review by AwkwardPeak7 — COMMENTED** [review]
why not implement this in the multisrc instead? considering all of mangabox sources are clones of each other

**Comment by NepThunder** [comment]
TL;DR
The user may have saved manga from other mirror sites and the manga.url has id-slug, hence the error during fetching and same goes while fetching the pages. MangaBox is not the issue, Saved info is.

The MangaBox works fine, the issue arose when mangakakalot stop using id based slug and changed that to title-based one.
So, majority of my changes are related to that. another issue rises when the user has saved the manga/manhwa/manhua and the database has old url and info saved, i tried to change it permanently but my 2 brain cells aren't smart enough and spent 4-5 hours or maybe more, testing and trying it and no progress. My database is that of old, hence i tested on my library.

All in all understand that the saved manga info is what is causing the issue for mangakakalot, while other site like mangabat, manganato, they also use title-based slug so they don't have any error as their url is in title-based.

**Comment by NepThunder** [comment]
@AwkwardPeak7 The current extension works fine if we switch to it's mirror "mangakakalove.com" but only fails with "mangakakalot.gg". Either we can merge this issue as this update will fix the previous broken url or we can close this PR.

**Review by AwkwardPeak7 — APPROVED** [review]
