### PR TITLE
Fix auth token getting for user id set.

### LINKED ISSUE #8520: MangaLib: hide locked chapters
### Source information

MangaLib 1.4.111

### Source language

Russian

### Steps to reproduce

1. Find manga with locked chapters (right now "TBATE" or "Начало после конца" have locked chapter until 20.04.2025)
2. Try to download locked chapter

### Expected behavior

1. Hide locked chapters.
2. Some message in the [error] log or notification for authorized through WebView users would be nice, since some people might want to unlock it early with the option to disable such notification.

### Actual behavior

App trying to download locked chapter with "Field 'pages' is required for type with serial name 'eu.kanade.tachiyomi.multisrc.libgroup.Pages', but it was missing at path: $data" error message.

Image

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 10

### Other details

Just in case, that's how API response for locked chapter looks like, if it's hard to find one at the time someone want's to fix this:

```
{
	"217": {
		"id": 3562120,
		"index": 218,
		"item_number": 218,
		"volume": "6",
		"number": "39",
		"number_secondary": "6",
		"name": "Заблокированные элементы",
		"branches_count": 1,
		"branches": [
			{
				"id": 3562120,
				"branch_id": null,
				"created_at": "2025-04-18T00:32:04.000000Z",
				"teams": [
					{
						"id": 815,
						"slug": "gl-alliance",
						"slug_url": "815--gl-alliance",
						"model": "team",
						"name": "GL▰Alliance",
						"cover": {
							"filename": "cover",
							"thumbnail": "https://cover.imglib.info/uploads/team/gl-alliance/cover/cover_thumb.jpg",
							"default": "https://cover.imglib.info/uploads/team/gl-alliance/cover/cover_250x350.jpg",
							"md": "https://cover.imglib.info/uploads/team/gl-alliance/cover/cover_250x350.jpg"
						}
					}
				],
				"expired_type": 1,
				"user": {
					"username": "RyuketsuSora",
					"id": 103532
				},
				"restricted_view": {
					"is_open": false,
					"expired_at": "2025-04-20T19:01:00.000000Z",
					"price": null
				}
			}
		]
	}
}
```

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #14103: HentaiLib empty user id param while create chapter url
### Source information

HentaiLib 1.4.57

### Source language

Russian

### Steps to reproduce

1.  Install HentaiLib 1.4.57
2.  Sing in on hentailib.me via WebView
3.  Try to open some title chapter
4.  Get 404 Error

### Expected behavior

Chapter load success.

### Actual behavior

404 Not found error

### Mihon/Mihon fork version

Mihon 0.19.4

### Android version

13

### Other details

This error produced because url need the ui (user id) param to be setted. Example: <br>
* https://hentailib.me/ru/33052--adabana/read/v3/c28.6? - doesn't work
* https://hentailib.me/ru/33052--adabana/read/v3/c28.6 - doesn't work
* https://hentailib.me/ru/33052--adabana/read/v3/c28.6?ui=$ACTUAL_USER_ID - work's fine 
For some reason same thing on Mangalib doesn't produce error, but behavior the same - no ui param.

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by hdsef**
Closes #14103 
Closes #8520

* Changed lib-multisrc\libgroup\src\eu\kanade\tachiyomi\multisrc\libgroup\LibGroup.k

* Changed mangalib, hentailib, yaoilib version

* Changed libgroup version

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt [hunk 1]
```diff
@@ -124,7 +124,7 @@ abstract class LibGroup(
         val req = chain.request().newBuilder()
         val url = chain.request().url.toString()
         if (url.contains(apiDomain) && !url.contains("/api/auth/me")) {
-            if (bearerToken.isNullOrBlank()) {
+            if (bearerToken.isNullOrBlank() || bearerToken == "none") {
```
Comment (MuhamadSyabitHidayattulloh) [inline lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt]: Suggestion: You can add ignoreCase check here.

**Comment by Exinaus** [comment]
Sorry for the reply, but i think you need to change `baseVersionCode` to update all extensions in multisrc, and `overrideVersionCode` if you need to update only one of multisrc extensions. It's one or the other, not all of them simultaneously.

Also, since you are updating libgroup extensions, maybe you can look at issue 8520 - it's about error from locked premium chapters on libgroup sites.

File: src/ru/hentailib/build.gradle [hunk 2]
```diff
@@ -3,7 +3,7 @@ ext {
     extClass = '.HentaiLib'
     themePkg = 'libgroup'
     baseUrl = 'https://hentailib.me'
-    overrideVersionCode = 20
+    overrideVersionCode = 21
```
Comment (MuhamadSyabitHidayattulloh) [inline src/ru/hentailib/build.gradle]: you bumped the multisrc, no need to bump extensions individually

File: lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt (hunk 1 above)
Comment (hdsef) [reply lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt]: Remove this evaluation

File: src/ru/hentailib/build.gradle (hunk 2 above)
Comment (hdsef) [reply src/ru/hentailib/build.gradle]: Revert ext version changed

File: lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt (hunk 1 above)
Comment (Smol-Ame) [reply lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt]: If you applied the suggestion, then hit Resolve conversation for said suggestion.

If you have an issue with said suggestion, comment why.

**Comment by hdsef** [comment]
@Exinaus - It's okay if it would look like this?
image

**Comment by Exinaus** [comment]
> @Exinaus - It's okay if it would look like this? 

Usual behavior on other extensions are just hide and ignore those chapters, like they doesn't exist. Show only unlocked chapters.
You can also add option in settings between hiding those chapters or displaying them like that, If it's not hard or too much to ask.
But this option are also great

**Comment by Exinaus** [comment]
I remembered a rather unique situation for this site: when a single manga chapter has multiple translations, and one of them is blocked. It took me some time to find a working example: https://mangalib.me/ru/manga/240671--sog-ajugo-sip-eo?from=catalog&section=chapters&ui=10495447
It feels like not displaying locked chapters are the best way of handling situation like that.

**Comment by hdsef** [comment]
Thanks for quite a good testing example. Now it's looks like this<br>
1. All translator and show paid
image <br>
2. All translator and hide paid
image <br>
3. One translator and hide paid (35 missing because default is Assley Team for this chapter)
image <br>
4. One translator and show paid
image <br>
5. Attempting to open a chapter that hasn't been bought yet.
image <br>

**Comment by Exinaus** [comment]
On 1st screenshot there is a free chapter 37 from Lexiopia, and it's missing on second screen.
Just double checking, since chapter 36 doesn't have same issue, and it's in a similar locked+open situation to 37. Maybe just a way it were cropped. Then ignore what i said.
And thanks for fixing that issue.

**Comment by hdsef** [comment]
Yep, some miss cropping. Focus on chapter 36.

**Review by vetleledaal — APPROVED** [review]
