### PR TITLE
fix(en/mangafire): rework mangafire extension

### LINKED ISSUE #7604: MangaFire: Customizable Chapter Count Filter
### Source name

MangaFire

### Source language

English

### Describe your suggested feature

I'd like to request a feature improvement for the existing 'Chapter Count' filter. The current limit of 50 can be restrictive, and I've noticed that the website's search URL allows for a custom minimum chapter count using the '&minchap' parameter. I would appreciate it if the filter could be updated to allow users to input a custom minimum chapter count, providing more flexibility in search results. This would be a valuable addition to the extension's functionality.

https://github.com/user-attachments/assets/7d38c62d-74f3-4e87-afff-b24e88717d4b

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Secozzi**
Closes #7604

Besides code cleanup, it also fixes some things:
* Full description will now show
* Add missing genre select mode filter
* Year filter will now automatically update
* A faulty volume chapter won't appear if the entry doesn't have any volumes

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — DISMISSED** [review]

File: src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt [hunk 1]
```diff
@@ -135,6 +112,32 @@ class MangaFire(
...
+    private fun searchMangaNextPageSelector() = ".page-item.active + .page-item .page-link"
+
+    private fun searchMangaSelector() = ".original.card-lg .unit .inner"
+
+    private fun searchMangaFromElement(element: Element) = SManga.create().apply {
+        element.selectFirst(".info > a")!!.let {
+            setUrlWithoutDomain(it.attr("href"))
+            title = it.ownText()
+        }
+        thumbnail_url = element.selectFirst("img")!!.attr("src")
```
Comment (vetleledaal) [inline src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt]: Thumbnail is not critical, remove non-null assert.

File: src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt [hunk 2]
```diff
@@ -147,137 +150,115 @@ class MangaFire(
...
-        val mangaTitle = root.child(1).ownText()
-        title = mangaTitle
-        description = document.run {
-            val description = selectFirst(Evaluator.Class("description"))!!.ownText()
-            when (val altTitle = root.child(2).ownText()) {
-                "", mangaTitle -> description
-                else -> "$description\n\nAlternative Title: $altTitle"
+        with(document.selectFirst(".main-inner:not(.manga-bottom)")!!) {
+            title = selectFirst("h1")!!.text()
+            thumbnail_url = selectFirst(".poster img")!!.attr("src")
```
Comment (vetleledaal) [inline src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt]: Thumbnail is not critical, remove non-null assert.

File: src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt [hunk 3]
```diff
@@ -147,137 +150,115 @@ class MangaFire(
...
+                    append("\n\nAlternative title: ${it.text()}")
+                }
+            }.trim()
+
+            with(selectFirst(".meta")!!) {
+                author = selectFirst("span:contains(Author:) + span")?.text()
+                val type = selectFirst("span:contains(Type:) + span")?.text()
+                val genres = selectFirst("span:contains(Genres:) + span")?.text()
+                genre = listOfNotNull(type, genres).joinToString()
             }
```
Comment (vetleledaal) [inline src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt]: `author` and `genre` is not essential, so non-null should be removed.

File: src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt [hunk 4]
```diff
@@ -147,137 +150,115 @@ class MangaFire(
...
+            .select(if (isVolume) ".vol-list > .item" else "li")
+
+        val ajaxReadList = client.newCall(getAjaxRequest("read", mangaId, type))
+            .execute().parseAs<ResponseDto<AjaxReadDto>>().result.html
+            .toBodyFragment()
+            .select("ul a")
+
+        val chapterList = ajaxMangaList.zip(ajaxReadList) { m, r ->
+            val link = r.selectFirst("a")!!
+            if (!r.attr("href").substringAfterLast("/").contains(type)) {
```
Comment (vetleledaal) [inline src/all/mangafire/src/eu/kanade/tachiyomi/extension/all/mangafire/MangaFire.kt]: Are you getting this from the fragment or path? Might be better to parse with `HttpUrl`.

**Comment by vetleledaal** [comment]
Also, for `thumbnail_url`- you should get the absolute URL.

**Review by vetleledaal — APPROVED** [review]
