### PR TITLE
HentaiDexy: Fix domain and API request

### LINKED ISSUE #7467: HentaiDexy changed URL
### Source information

Hentaidexy 1.4.32

### Source language

English

### Source new URL

https://dexyscan.com

### Other details

Extension package name: "en.hentaidexy"

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #7467 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt [hunk 1]
```diff
@@ -63,7 +61,7 @@ class Hentaidexy : HttpSource() {
 
     // latest
     override fun latestUpdatesRequest(page: Int): Request {
-        return GET("$apiUrl/api/v1/mangas?page=$page&limit=100&sort=-updatedAt", headers)
+        return GET("$baseUrl/api/mangas?page=$page&limit=100&sort=-createdAt", headers)
```
Comment (vetleledaal) [inline src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Please confirm that this is correct. 

Usually 'created' is sorted by when an entry was added. 
And 'updated' is usually sorted by when the latest chapter was added. (This is preferred)

File: src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt [hunk 2]
```diff
@@ -81,14 +79,14 @@ class Hentaidexy : HttpSource() {
     }
 
     override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
-        return GET("$apiUrl/api/v1/mangas?page=$page&altTitles=$query&sort=createdAt", headers)
+        return GET("$baseUrl/api/mangas?page=$page&altTitles=$query&sort=createdAt", headers)
```
Comment (vetleledaal) [inline src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Use HttpUrl for proper encoding

File: src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt [hunk 3]
```diff
@@ -146,7 +144,7 @@ class Hentaidexy : HttpSource() {
     // page list
     override fun pageListRequest(chapter: SChapter): Request {
         val chapterId = chapter.url.substringAfterLast('/')
```
Comment (vetleledaal) [inline src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Use HttpUrl to parse

File: src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt (hunk 1 above)
Comment (lordenecromante) [reply src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: I was using a proxy, and created was the API call, but I tested with updated, and it worked. Since it's the best practice, I left it as updated. Fix it.

File: src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt (hunk 2 above)
Comment (lordenecromante) [reply src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Fix it

File: src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt (hunk 3 above)
Comment (lordenecromante) [reply src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Fix it

Comment (vetleledaal) [reply src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Maybe I was a bit unclear, I meant for finding the `chapterId`, not building the URL. You can use something like `.pathSegments.last()`

Comment (lordenecromante) [reply src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Got it, Fix it.

File: src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt [hunk 4]
```diff
@@ -132,7 +150,7 @@ class Hentaidexy : HttpSource() {
 
         return chapterListResponse.chapters.map { chapter ->
             SChapter.create().apply {
-                url = "/manga/$mangaId/chapter/${chapter._id}"
+                url = "$baseUrl/manga/$mangaId/chapter/${chapter._id}"
```
Comment (vetleledaal) [inline src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: You should avoid making this absolute unless necessary as migration becomes more difficult. 

If you need the absolute url elsewhere you can use `"$baseUrl${chapter.url}".toHttpUrl()...`

Comment (lordenecromante) [reply src/en/hentaidexy/src/eu/kanade/tachiyomi/extension/en/hentaidexy/Hentaidexy.kt]: Fix it

**Review by vetleledaal — APPROVED** [review]
