### PR TITLE
MangaTop -> MangaScans: update domain

### LINKED ISSUE #4445: New site name - MangaTop
### Source information

MangaTop 1.4.1

### Source language

English

### Source new URL

https://mangascans.to/

### Other details

I experience this problem yesterday. The MangaTop extension is still updating the "Latest Tab," however when I click on a certain series it fails to load the chapters, its just loading for a long time. Then I checked the WebView and found out that there is a new name for the site (Mangascans) and new url. I already ask about this in the discord support and suggested me to make this hoping that this will be fixed by changing the url since there is a new site name. Thank you!!
Screenshot_2024-08-06-14-37-59-764_app mihon
Screenshot_2024-08-06-14-37-54-914_app mihon
Screenshot_2024-08-06-14-38-24-498_app mihon

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes  #4445

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/mangatop/src/eu/kanade/tachiyomi/extension/en/mangatop/MangaScans.kt [hunk 1]
```diff
@@ -28,16 +28,18 @@ import java.text.SimpleDateFormat
...
+    override val name = "MangaScans"
 
-    override val baseUrl = "https://mangatop.to"
+    override val baseUrl = "https://mangascans.to"
 
     override val lang = "en"
 
     override val supportsLatest = true
 
+    override val id = 85127596998931837
```
Comment (TheKingTermux) [inline src/en/mangatop/src/eu/kanade/tachiyomi/extension/en/mangatop/MangaScans.kt:41]: I'm sorry if I'm bothering you, but I've been meaning to ask you for a while, how do I get this ID?

Comment (AwkwardPeak7) [reply src/en/mangatop/src/eu/kanade/tachiyomi/extension/en/mangatop/MangaScans.kt:41]: https://github.com/keiyoushi/extensions/blob/repo/index.json

Comment (TheKingTermux) [reply src/en/mangatop/src/eu/kanade/tachiyomi/extension/en/mangatop/MangaScans.kt:41]: > https://github.com/keiyoushi/extensions/blob/repo/index.json

Ohh there it turns out, thank you for answering my question
