### PR TITLE
Fix SirenKomik

### LINKED ISSUE #6421: Not loading image properly
### Source information

Siren Komik 1.4.34

### Source language

Indonesia 

### Steps to reproduce

1. Open the Siren Komik extension
2. Open chapter from any title
3. Each chapter features the same image

### Expected behavior

Display manga images normally

### Actual behavior

Showing the same image instead of the manga image it should be

### Mihon/Tachiyomi version

Mihon 0.17.0

### Android version

Android 12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Closes : #6421

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/id/mangkomik/src/eu/kanade/tachiyomi/extension/id/mangkomik/SirenKomik.kt [hunk 1]
```diff
@@ -27,6 +27,8 @@ class SirenKomik : MangaThemesia(
 
     override fun chapterListSelector() = ".list-chapter a"
 
+    override val pageSelector: String = "Deactivate html search"
```
Comment (vetleledaal) [inline src/id/mangkomik/src/eu/kanade/tachiyomi/extension/id/mangkomik/SirenKomik.kt]: Are you using this because it will never match, or because this is actually the elements on the page?

If the former, you should make it more obvious, and use a selector that will always fail (along with a comment):
```css
> :not(*)
```

**Review by AwkwardPeak7 — APPROVED** [review]
