### PR TITLE
FenixManhwas: Redesign

### LINKED ISSUE #10306: Fênix Manhwas HTTP error 404/ No Results Found
### Source information

fênix mamhwas 1.4.44

### Source language

portuguese

### Steps to reproduce

1. I go to the browser.
2. I click on the "fênix mamhwas" source.
3 . Two tabs appear: "Recent" and "Browse,"

### Expected behavior

the manga list should appear in the "browse" and "Recent" tab.

### Actual behavior

the "browse" and "Recent" tab is empty and when I click on any of the tabs, it shows the error

### Mihon/Tachiyomi version

TachiyomeSY 1.12.0

### Android version

android 14

### Other details

I've already checked the website and the webview, and they're fine.
These are basically "No Results Found" and "HTTP 404" errors.

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #10306

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/fenixmanhwas/src/eu/kanade/tachiyomi/extension/pt/fenixmanhwas/FenixManhwas.kt [hunk 1]
```diff
@@ -1,12 +1,142 @@
...
+                element.selectFirst("small")?.text()?.let(::parseRelativeDate)?.let {
+                    date_upload = it
+                }
+                setUrlWithoutDomain(element.selectFirst("a")!!.absUrl("href"))
+            }
+        }
+    }
+
+    private fun parseRelativeDate(date: String): Long {
+        val number = Regex("""(\d+)""").find(date)?.value?.toIntOrNull() ?: return 0
```
Comment (stevenyomi) [inline src/pt/fenixmanhwas/src/eu/kanade/tachiyomi/extension/pt/fenixmanhwas/FenixManhwas.kt]: This regex should be a class member.

File: src/pt/fenixmanhwas/src/eu/kanade/tachiyomi/extension/pt/fenixmanhwas/FenixManhwas.kt [hunk 2]
```diff
@@ -1,12 +1,142 @@
...
+    // ========================== Pages ==========================
+
+    override fun pageListParse(response: Response): List<Page> {
+        val document = response.asJsoup()
+        return document.select(".chapter-content img.lozad").mapIndexed { index, element ->
+            Page(index, imageUrl = element.absUrl("data-src"))
+        }
+    }
+
+    override fun imageUrlParse(response: Response): String = ""
```
Comment (stevenyomi) [inline src/pt/fenixmanhwas/src/eu/kanade/tachiyomi/extension/pt/fenixmanhwas/FenixManhwas.kt]: Throw UOE.

**Review by stevenyomi — APPROVED** [review]
