### PR TITLE
Reaperscans: fix chapterListRequest

### LINKED ISSUE #7730: Reaper scan http 500
### Source information

1.4.56

### Source language

English 

### Steps to reproduce

1.Open extension and webview for captcha
2. Open manhwa to refresh no chapter and got HTTP 500
3. Open webview manhwa is okay

### Expected behavior

Can see the chapters and refresh the title 

### Actual behavior

No chapter and http 500

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Closes #7730

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 1]
```diff
@@ -41,6 +42,20 @@ class ReaperScans : HeanCms("Reaper Scans", "https://reaperscans.com", "en") {
         return GET(url.build(), headers)
     }
 
+    override fun chapterListRequest(manga: SManga): Request = GET(
+        "$apiUrl/chapters/".toHttpUrl().newBuilder().apply {
+            addPathSegment(manga.url.substringAfterLast("#"))
```
Comment (vetleledaal) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: Something like
```kt
manga.url.toHttpUrlOrNull()?.fragment
```
?

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 2]
```diff
@@ -41,6 +42,20 @@ class ReaperScans : HeanCms("Reaper Scans", "https://reaperscans.com", "en") {
...
+            addQueryParameter("page", "1")
+            addQueryParameter("perPage", "1000")
+            fragment(manga.url.substringAfterLast("/").substringBefore("#"))
```
Comment (vetleledaal) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: Something like
```kt
manga.url.toHttpUrlOrNull()?.pathSegments.last()
```
?

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt (hunk 1 above)
Comment (Creepler13) [reply src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: yeah that makes sense. I was just lazy and copied the solution from the multi-src

File: src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt [hunk 3]
```diff
@@ -41,6 +43,19 @@ class ReaperScans : HeanCms("Reaper Scans", "https://reaperscans.com", "en") {
         return GET(url.build(), headers)
     }
 
+    override fun chapterListRequest(manga: SManga): Request = GET(
+        "$apiUrl/chapters/".toHttpUrl().newBuilder().apply {
+            (baseUrl + manga.url).toHttpUrlOrNull()?.fragment?.let { addPathSegment(it) }
```
Comment (AwkwardPeak7) [inline src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt]: make httpUrl in a variable and reuse it here and down (fragment)

**Review by vetleledaal — APPROVED** [review]
