### PR TITLE
LibGroup: fix chapters

### LINKED ISSUE #5609: YaoiLib - chapters disappear once alernative translation is added
### Source information

YaoiLib 1.4.35

### Source language

Russian

### Steps to reproduce

open the souce, open manga with multiple translations

### Expected behavior

show all chapters (with all translations)

### Actual behavior

Screenshot_2024-10-19-21-58-42-257_eu kanade tachiyomi sy
Screenshot_2024-10-19-21-58-52-072_eu kanade tachiyomi sy
scanlator filter doesn't work

### Mihon/Tachiyomi version

Tachiyomi SY Stable 1.10.5

### Android version

Android 8.1.0

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Dr1ks**
Closes #5609 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt [hunk 1]
```diff
@@ -313,37 +313,32 @@ abstract class LibGroup(
     override fun chapterListParse(response: Response): List<SChapter> {
         val slugUrl = response.request.url.toString().substringAfter("manga/").substringBefore("/chapters")
         val chaptersData = response.parseAs<Data<List<Chapter>>>()
-        if (chaptersData.data.isEmpty()) {
-            throw Exception("Нет глав")
-        }
-
+            .also { if (it.data.isEmpty()) throw Exception("Нет глав") }
```
Comment (vetleledaal) [inline lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt]: If you return an empty list here, the app will use the localized string.

File: lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt [hunk 2]
```diff
@@ -313,37 +313,32 @@ abstract class LibGroup(
...
-                        chapters.add(it.value.toSChapter(slugUrl, currentBranch.value.branchId, isScanUser()))
+        return chaptersData.data.flatMap { chapter ->
+            when {
+                chapter.branchesCount > 1 && sortingList == "ms_mixing" -> {
+                    listOf(
+                        chapter.branches
+                            .firstOrNull { it.branchId == defaultBranchId }
+                            ?.let { chapter.toSChapter(slugUrl, defaultBranchId, isScanUser()) }
+                            ?: chapter.toSChapter(slugUrl, chapter.branches.first().branchId, isScanUser()),
+                    )
```
Comment (AwkwardPeak7) [inline lib-multisrc/libgroup/src/eu/kanade/tachiyomi/multisrc/libgroup/LibGroup.kt]:
```suggestion
                    val branch = chapter.branches
                        .firstOrNull { it.branchId == defaultBranchId }?.branchId
                        ?: chapter.branches.first().branchId
                        
                    listOf(
                        chapter.toSChapter(slugUrl, branch, isScanUser()),
                    )
```

**Review by AwkwardPeak7 — APPROVED** [review]
