### PR TITLE
fix: Scan VF

### LINKED ISSUE #3380: Scan VF: Search issue
### Source information

Scan VF 1.4.12

### Source language

French

### Steps to reproduce

1. Use the search
2. Click on a manga

### Expected behavior

Chapter should be there

### Actual behavior

No chapters

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Other details

The search add a /manga in the url

For example: https://www.scan-vf.net/manga/one_piece
Instead of: https://www.scan-vf.net/one_piece

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Mylloon**
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

Close #3380

### CODE REVIEW

File: lib-multisrc/mmrcms/src/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMS.kt [hunk 1]
```diff
@@ -211,8 +211,9 @@ constructor(
     protected fun parseSearchDirectory(page: Int): MangasPage {
         val manga = searchDirectory.subList((page - 1) * 24, min(page * 24, searchDirectory.size))
             .map {
+                val itemPathUsed = if (itemPath.isEmpty()) "$itemPath/" else ""
                 SManga.create().apply {
-                    url = "/$itemPath/${it.data}"
+                    url = "/$itemPathUsed${it.data}"
```
Comment (AwkwardPeak7) [inline lib-multisrc/mmrcms/src/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMS.kt]: don't change the multisrc for this, you can override the function in the source class instead

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
