### PR TITLE
[EN] AsuraScan Fix: Loads Unlocked Chapter Via Unlock Token

### LINKED ISSUE #13180: Asura Scans: Unable to read unlocked chapter despite being accessible via WebView login
### Source information

Asura Scans: 1.4.52

### Source language

English

### Steps to reproduce

Asura Scans allows unlocking one chapter for free after maintaining a 3-day consecutive comment streak. I successfully unlocked a chapter and confirmed that it is accessible when logged in through WebView.
However, after returning to Mihon and refreshing the chapter list, the unlocked chapter still cannot be opened from the entry’s chapter list. It shows the following error:
“Login through WebView, then go back to the entry and refresh the chapter list to see if it sees/can access the premium chapters…”

### Expected behavior

The unlocked chapter should open normally after logging in through WebView and refreshing the chapter list.

### Actual behavior

The chapter remains inaccessible and shows the error message, even though it opens correctly in WebView.

### Mihon/Tachiyomi version

Mihon 0.9.3

### Android version

Android 15, Funtouch 15

### Other details

I don't have Asura Subscription.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by NepThunder**
Changes made:
- ~~added user info caching~~
- removed the pre-emptive check and refactored logic
- ~~added Token UI beside chapter to let the user know if the chapter can be unlocked via token for early access chapter~~
- ~~changed the image loading architecture~~
- ~~and few other changes~~

closes #13180 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt [hunk 1]
```diff
@@ -289,16 +296,28 @@ class AsuraScans : ParsedHttpSource(), ConfigurableSource {
...
         val baseName = if (chTitle.isBlank()) chNumber else "$chNumber - $chTitle"
-        name = if (isPremiumChapter && !hasPremiumAccess()) "🔒 $baseName" else baseName
+
+        if (isPremiumChapter) {
+            val userInfo = getUserInfo()
+            val availableTokens = userInfo?.data?.streak?.available_tokens ?: 0
+
+            name = when {
+                hasPremiumAccess() -> "⭐ $baseName"
+                availableTokens > 0 -> "🪙 $baseName (Tokens: $availableTokens)"
```
Comment (AwkwardPeak7) [inline src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt]: these kind of labels in chapter name can mess with downloads

File: src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt [hunk 2]
```diff
@@ -357,55 +377,117 @@ class AsuraScans : ParsedHttpSource(), ConfigurableSource {
...
-            Page(index, imageUrl = imageUrl)
+            val pageData = PremiumPageData(
+                mediaId = page.id,
+                chapterId = chapterId,
+                unlockToken = unlockToken,
+            )
+
+            val cacheKey = "premium_page_${chapterId}_${page.id}"
+            premiumPageCache[cacheKey] = pageData
+            Page(index, url = "$PREMIUM_PAGE_MARKER$cacheKey")
```
Comment (AwkwardPeak7) [inline src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt]: json encode the data and put it in the url as fragment.

```kt
Page(index, url = "http://premium#${pageData.toJsonString()}")
```

File: src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt [hunk 3]
```diff
@@ -428,6 +510,7 @@ class AsuraScans : ParsedHttpSource(), ConfigurableSource {
     }
 
     private fun getXsrfToken(): String {
+        val cookies = client.cookieJar.loadForRequest(baseUrl.toHttpUrl())
```
Comment (AwkwardPeak7) [inline src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt]: unused in this function?

File: src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt [hunk 4]
```diff
@@ -357,55 +377,117 @@ class AsuraScans : ParsedHttpSource(), ConfigurableSource {
...
+                null
+            }
+        }.getOrNull()
+
+        cachedUserInfo = userInfo
+        lastUserInfoCheck = now
+        return userInfo
     }
 
+    private fun buildApiRequest(url: String, jsonPayload: String, xsrfToken: String): Request = Request.Builder()
```
Comment (AwkwardPeak7) [inline src/en/asurascans/src/eu/kanade/tachiyomi/extension/en/asurascans/AsuraScans.kt]: consider using `POST` helper function

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by NepThunder** [comment]
Requires more testing, so changing it to draft.

**Review by AwkwardPeak7 — APPROVED** [review]
