### PR TITLE
RCO: Fail to get image links.

### LINKED ISSUE #8468: ReadComicOnline : Timeout getting image links
### Source information

ReadComicOnline 1.4.30

### Source language

English

### Steps to reproduce

1. Go into any entry from the source
2. Open a chapter
3. Loads for some time before it exits the reader & says "Timeout getting image links"

### Expected behavior

The chapter should be loaded instead of Error Message 

### Actual behavior

Throwing "Timeout getting image links" error

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 14

### Other details

This issue was same as the #8420 , After the fix it was working for some time and it arises again.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lamaxama**
Closes #8468

It seems that RCO only intentionally breaks users who are not logged in, so recommend users attempt to log in via webview.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt [hunk 1]
```diff
@@ -236,8 +236,8 @@ class Readcomiconline : ConfigurableSource, ParsedHttpSource() {
 
         val html = document.outerHtml()
         val match = KEY_REGEX.find(html)
-        val key1 = match?.groups?.get(1)?.value ?: throw Exception("Fail to get image links.")
-        val key2 = match?.groups?.get(2)?.value ?: throw Exception("Fail to get image links.")
+        val key1 = match?.groups?.get(1)?.value ?: throw Exception("Fail to get image links. Logging in via WebView may fix this issue.")
```
Comment (AwkwardPeak7) [inline src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt:239]: imo shouldn't say this

File: src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt [hunk 2]
```diff
@@ -444,6 +444,6 @@ class Readcomiconline : ConfigurableSource, ParsedHttpSource() {
         private const val QUALITY_PREF = "qualitypref"
         private const val SERVER_PREF_TITLE = "Server Preference"
         private const val SERVER_PREF = "serverpref"
-        private val KEY_REGEX = """\.attr\(\s*['"]src['"]\s*,\s*([\w]+)\(\s*([\w]+)\[\s*currImage""".toRegex()
+        private val KEY_REGEX = """\.attr\(\s*['"]src['"]\s*,\s*([\w]+)\(\s*([\w]+)\[\s*(cImgIndex|currImage|currIndex)""".toRegex()
```
Comment (AwkwardPeak7) [inline src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt]: try: `(\w+)\s*\((\w+)\s*\[\s*\w+\]\s*\)`

Comment (lamaxama) [reply src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt]: Not working, they left a trap for this.

```
//beau(_lstImgs, '');
var currImage = 0;
//$('#divImage').html("<br><img onerror='onErrorImg(this);' onload='onLoadImg(this);' id='imgCurrent' style='cursor: pointer' src='" + fobnkG2ebH1(_gqb2YNx[currImage]) + "&t=" + new Date().getTime() + "' />");
```

`//........fobnkG2ebH1(_gqb2YNx[currImage])` is the trap

However, I can replace (cImgIndex|currImage|currIndex) with \w+

File: src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt (hunk 1 above)
Comment (lamaxama) [reply src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt:239]: The last and current site changes have not affected logged-in users. The site has two sets of templates for logged-in and logged-out users, and the changes were only made to the code for logged-out users both times. 
Therefore, I suggest keeping this message.

File: src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt (hunk 2 above)
Comment (AwkwardPeak7) [reply src/en/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt]:
```js
let regexp = /(\w+)\s*\((\w+)\s*\[\s*\w+\]\s*\)/;
let matches = SetImage.toString().match(regexp);
let imageArray = eval(matches[2]);
let decodingFunc = eval(matches[1]);
imageArray.map(image => decodingFunc(image));
```
try this in the webview directly

again thanks to ArseneLapin

edit: can do it if they break again

**Review by AwkwardPeak7 — APPROVED** [review]
