### PR TITLE
fix(buondua): enhance Cloudflare challenge bypass

### LINKED ISSUE #8079: Buon Dua: image Download and display error.
### Source information

https://buondua.com/

### Source language

ALL

### Steps to reproduce

When I try to download something in this extension, it doesn't let me and says I need to pass CloudFire. But when I open the WebView to do it, the page loads correctly, but no captcha or anything like that appears. I clear the cache repeatedly, but it still doesn't work.

Image

### Expected behavior

What I expect to happen is for the download to work correctly and for me to be able to see the images in the extension or its display properly, but none of that works.

### Actual behavior

Instead, the downloads don't work, and I can't see the images in the extension within the app either. Everything shows an error.

### Mihon/Tachiyomi version

App version: 0.17.1 (standard, 3a100c7, 9, 2024-12-06T17:14:05Z) Android version: 13 (SDK 33; build KI7-V7510AACDGHJKLMN-T-GL-250218V5302) Device brand: TECNO Device manufacturer: TECNO Device name: TECNO-KI7 (KI7-GL) Device model: TECNO KI7 WebView: Android System WebView 133.0.6943.138

### Android version

ANDROID 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by marioplus**
- Add rate limiting (max 10 requests/second)
- Implement random User-Agent rotation
- Inject Referer header
- Version bump 2 → 3

closes: #8079

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/buondua/src/eu/kanade/tachiyomi/extension/all/buondua/BuonDua.kt [hunk 1]
```diff
@@ -1,25 +1,41 @@
...
 
+    override val client = network.cloudflareClient.newBuilder()
+        .rateLimitHost(baseUrl.toHttpUrl(), 10, 1, TimeUnit.SECONDS)
+        .setRandomUserAgent(UserAgentType.MOBILE)
+        .addInterceptor { chain ->
+            val request = chain.request().newBuilder()
+                .header("Referer", "$baseUrl/")
+                .build()
+            chain.proceed(request)
+        }
```
Comment (choppeh) [inline src/all/buondua/src/eu/kanade/tachiyomi/extension/all/buondua/BuonDua.kt]: Replace the interceptor with ``` headersBuilder()```

```suggestion
```

https://github.com/keiyoushi/extensions-source/blob/228b657e25788f904b29cde7561b69d5a38f800b/lib-multisrc/goda/src/eu/kanade/tachiyomi/multisrc/goda/GoDa.kt#L30

File: src/all/buondua/src/eu/kanade/tachiyomi/extension/all/buondua/BuonDua.kt [hunk 2]
```diff
@@ -77,7 +95,9 @@ class BuonDua() : ParsedHttpSource() {
         chapter.setUrlWithoutDomain(element.select(".is-current").first()!!.attr("abs:href"))
         chapter.chapter_number = 0F
         chapter.name = element.select(".article-header").text()
-        chapter.date_upload = SimpleDateFormat("H:m DD-MM-yyyy", Locale.US).parse(element.select(".article-info > small").text())?.time ?: 0L
+        chapter.date_upload =
+            SimpleDateFormat("H:m DD-MM-yyyy", Locale.US).parse(element.select(".article-info > small").text())?.time
+                ?: 0L
```
Comment (choppeh) [inline src/all/buondua/src/eu/kanade/tachiyomi/extension/all/buondua/BuonDua.kt]: Move the ```SimpleDateFormat``` to the ```companion object``` or class variable: 
```kt
companion object {
     private val dateFormat = SimpleDateFormat("H:m DD-MM-yyyy", Locale.US)
}
// or
private val dateFormat = SimpleDateFormat("H:m DD-MM-yyyy", Locale.US)
``` 

And use the ```keiyoushi.utils.tryParse```  from utils
```suggestion
        chapter.date_upload = dateFormat.tryParse(element.select(".article-info > small").text())
```

You need to import:
```kt 
import keiyoushi.utils.tryParse
```

https://github.com/keiyoushi/extensions-source/blob/228b657e25788f904b29cde7561b69d5a38f800b/lib-multisrc/mangabox/src/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt#L314

**Comment by Smol-Ame** [comment]
Put "Closes #8079" in the PR description instead so it links properly

**Review by AwkwardPeak7 — APPROVED** [review]
