### PR TITLE
ReYume: fix issue from changing site theme

### LINKED ISSUE #7868: Reyume
### Source information

Reyume 1.4.36

### Source language

Indonesia

### Steps to reproduce

1. Open ext
2. Select a comic
3. Open chapter

### Expected behavior

Everything works normally

### Actual behavior

"Unknown error" appears and the cover doesn't appear. But the chapter works fine.
Previously I opened an issue #4984 But after they changed the web appearance/theme(?), it actually made the chapters appear now. The only problem is the cover not appearing and "unknown error" And the chapters that appear are not from the first (for example, the manga "Shangri La" only appear from chapter 90-latest).

https://github.com/user-attachments/assets/bba78276-3773-4f0a-be4b-ece857488158

### Mihon/Tachiyomi version

J2k 1.7.4

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Riztard**
Closes #7868

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/zeistmanga/src/eu/kanade/tachiyomi/multisrc/zeistmanga/ZeistManga.kt [hunk 1]
```diff
@@ -175,6 +176,7 @@ abstract class ZeistManga(
                 .joinToString { it.text() }
             author = profileManga.selectFirst(mangaDetailsSelectorAuthor)?.text()
             artist = profileManga.selectFirst(mangaDetailsSelectorArtist)?.text()
+            status = parseStatus(profileManga.selectFirst(mangaDetailsSelectorStatus)?.text() ?: "")
```
Comment (Riztard) [inline lib-multisrc/zeistmanga/src/eu/kanade/tachiyomi/multisrc/zeistmanga/ZeistManga.kt:179]: should i update base version for this?

Comment (stevenyomi) [reply lib-multisrc/zeistmanga/src/eu/kanade/tachiyomi/multisrc/zeistmanga/ZeistManga.kt:179]: Yes.

File: src/id/inazumanga/src/eu/kanade/tachiyomi/extension/id/inazumanga/ReYume.kt [hunk 2]
```diff
@@ -1,16 +1,21 @@
...
-import eu.kanade.tachiyomi.multisrc.makaru.Makaru
-import eu.kanade.tachiyomi.source.model.Page
-import eu.kanade.tachiyomi.util.asJsoup
-import okhttp3.Response
+import eu.kanade.tachiyomi.multisrc.zeistmanga.ZeistManga
 
-class ReYume : Makaru("ReYume", "https://www.re-yume.my.id", "id") {
-    override fun pageListParse(response: Response): List<Page> {
-        val document = response.asJsoup()
+class ReYume : ZeistManga("ReYume", "https://www.re-yume.my.id", "id") {
```
Comment (stevenyomi) [inline src/id/inazumanga/src/eu/kanade/tachiyomi/extension/id/inazumanga/ReYume.kt:5]: Manga URL not changed so didn't bump `versionId`?

Comment (Riztard) [reply src/id/inazumanga/src/eu/kanade/tachiyomi/extension/id/inazumanga/ReYume.kt:5]: yea

**Review by stevenyomi — APPROVED** [review]
