### PR TITLE
Zaimanhua: Fix login check & add chapter comments

### LINKED ISSUE #9089: Zaimanhua：希望再漫画插件增加在章节末尾添加吐槽页功能 #6378
### Source name

再漫画

### Source language

Chinese

### Describe your suggested feature

类似拷贝漫画和动漫之家的插件，允许阅读到章节末尾的时候显示当前章节的吐槽评论

Image

### Other details

之前提过一个issue：https://github.com/keiyoushi/extensions-source/issues/6378 ，当时再漫画本身不支持该功能，现已支持

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by zhongfly**
Close #9089

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt [hunk 1]
```diff
@@ -176,12 +187,17 @@ class Zaimanhua : HttpSource(), ConfigurableSource {
...
             }
-            return Observable.just(
-                result.data.data.images.mapIndexed { index, it ->
+            return Observable.fromCallable {
+                val pageList = result.data.data.images.mapIndexed { index, it ->
                     val fragment = json.encodeToString(ImageRetryParamsDto(chapter.url, index))
                     Page(index, imageUrl = "$it#$fragment")
-                },
-            )
+                }.toMutableList()
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]:
```suggestion
                val images = result.data.data.images
                val pageList = images.mapIndexedTo(ArrayList(images.size + 1)) { index, it ->
val fragment = json.encodeToString(ImageRetryParamsDto(chapter.url, index))
Page(index, imageUrl = "$it#$fragment")
                }
```

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt [hunk 2]
```diff
@@ -203,6 +219,63 @@ class Zaimanhua : HttpSource(), ConfigurableSource {
         }
     }
 
+    private fun commentsInterceptor(chain: Interceptor.Chain): Response {
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]: Move to separate file.

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt [hunk 3]
```diff
@@ -203,6 +219,63 @@ class Zaimanhua : HttpSource(), ConfigurableSource {
...
+            canvas.save()
+            canvas.translate(COMMENT_UNIT_F, y.toFloat())
+            layout.draw(canvas)
+            canvas.restore()
+            y += layout.height + COMMENT_UNIT
+        }
+
+        val output = ByteArrayOutputStream()
+        bitmap.compress(Bitmap.CompressFormat.PNG, 0, output)
+        val body = output.toByteArray().toResponseBody("image/png".toMediaType())
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]: https://github.com/keiyoushi/extensions-source/blob/b80e212494e77a63c262056449ce67c8af70bc50/src/zh/roumanwu/src/eu/kanade/tachiyomi/extension/zh/roumanwu/ScrambledImageInterceptor.kt#L45-L48

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt [hunk 4]
```diff
@@ -203,6 +219,63 @@ class Zaimanhua : HttpSource(), ConfigurableSource {
...
+        return response.newBuilder().body(body).build()
+    }
+
+    override fun imageRequest(page: Page): Request {
+        if (page.url == COMMENTS_FLAG) {
+            return GET(page.imageUrl!!, apiHeaders).newBuilder()
+                .tag(String::class, COMMENTS_FLAG)
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]: You can use `url.pathSegments[n] == "viewpoint"` to pinpoint the comment requests.

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt [hunk 5]
```diff
@@ -170,3 +179,46 @@ data class ImageRetryParamsDto(
     val url: String,
     val index: Int,
 )
+
+@Serializable
+data class CanReadDto(
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt]:
```suggestion
class CanReadDto(
```

Same for other classes.

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt [hunk 6]
```diff
@@ -170,3 +179,46 @@ data class ImageRetryParamsDto(
...
+    val canRead: Boolean?,
+)
+
+@Serializable
+data class CommentDataDto(
+    @Serializable(with = LastStringFromArrayListSerializer::class)
+    val list: List<String>,
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt]: Use `List<JsonPrimitive>` or something like that.

https://github.com/keiyoushi/extensions-source/blob/b80e212494e77a63c262056449ce67c8af70bc50/src/zh/toptoon/src/eu/kanade/tachiyomi/extension/zh/toptoon/ToptoonDto.kt#L34-L42

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt (hunk 4 above)
Comment (zhongfly) [reply src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]: > You can use `url.pathSegments[n] == "viewpoint"` to pinpoint the comment requests.

Using `COMMENTS_FLAG` is simpler, as it requires no additional modifications here even if the interface changes. Furthermore, `page.url` here is a string, not a URL object. To use `pathSegments[n] == “viewpoint”`, we must convert it to URL and check that `pathSegments` is not less than `n` before `pathSegments[n] == “viewpoint”`.

Comment (stevenyomi) [reply src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]: > Furthermore, `page.url` here is a string, not a URL object.

I mean checking `request.url.pathSegments` in the interceptor.

> Using `COMMENTS_FLAG` is simpler, as it requires no additional modifications here even if the interface changes.

Not quite sure about that, but I'll merge it regardless.

You're using 2 different ways to tag pages: `Page.url == COMMENTS_FLAG` to tag comments and `Page.imageUrl.fragment != null` to tag retries, which looks very dirty.

**Review by stevenyomi — APPROVED** [review]
