### PR TITLE
NHentai | Fixed some images not showing for some titles

### LINKED ISSUE #6057: NHentai.net : The app trying to open file with .jpg.webp extension while it's supposed to be .webp OR .jpg and causes error for reading and downloading
### Source information

tachiyomi-all.nhentai-v1.4.46.apk

### Source language

All

### Steps to reproduce

I don't have all of the title affected but one of them is titled [Zikataro] Jiyuu ni Sex Dekiru Joshi Rikujou-bu | A Girls’ Athletics Club Where You Can Have Sex Anytime [English] link : https://nhentai.net/g/538696/
1. Open the chapter in Mihon app 
2. 1st page will show error "the image couldn't be loaded"
3. Click "Open in WebView"
4. The page trying to open : https://i2.nhentai.net/galleries/3120497/1.jpg.webp which is not a real file, the correct link should be https://i2.nhentai.net/galleries/3120497/1.jpg (changing/editing the link to .jpg does open the page supposed to be showed)
5. Usually only first and/or last page have this error but I didn't remember all of the title affected by this

### Expected behavior

The app should pull https://i2.nhentai.net/galleries/<Title ID>/<Page Number>.jpg

### Actual behavior

The app trying to pull https://i2.nhentai.net/galleries/<Title ID>/<Page Number>.jpg.webp

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 13

### Other details

Idk if this is nhentai fault ot app fault because for a few hour yesterday (9PM GMT+7) the website also fail to preview first/last pages of some titles but it's fixed in website while the in app viewer still broken and prevent chapter download

Seems like the error caused by the first page of some title have .jpg extension instead of the usual .webp, and the app didn't know what to do added.webp behind the link, because other page open just fine and they use .webp extension

What shows in app
Screenshot_20241114_211555

Opening link in WebView/Browser
Screenshot_20241114_211620
Screenshot_20241114_211628

After editing the link to .jpg
Screenshot_20241114_211650
IMG_20241114_212029

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #6057

Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt [hunk 1]
```diff
@@ -207,22 +210,25 @@ open class NHentai(
     override fun searchMangaNextPageSelector() = latestUpdatesNextPageSelector()
 
     override fun mangaDetailsParse(document: Document): SManga {
-        val fullTitle = document.select("#info > h1").text().replace("\"", "").trim()
+        val script = document.select("script:containsData(JSON.parse)").first()!!.data()
```
Comment (AwkwardPeak7) [inline src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt]:
```suggestion
        val script = document.selectFirst("script:containsData(JSON.parse)")!!.data()
```

File: src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt [hunk 2]
```diff
@@ -207,22 +210,25 @@ open class NHentai(
...
+
+        val json = Regex("""JSON.parse\("([^*]*)"\)""").find(script)?.groupValues!![1]
```
Comment (AwkwardPeak7) [inline src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt]: move the regex to class to reuse

File: src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt [hunk 3]
```diff
@@ -247,10 +258,23 @@ open class NHentai(
...
-            Page(i, "", img.attr("abs:data-src").replace("t.nh", "i.nh").replace("t\\d+.nh".toRegex(), "i$mediaServer.nh").replace("t.", "."))
+        val mediaServer = Regex("""media_server\s*:\s*(\d+)""").find(script)?.groupValues!![1]
+        val json = Regex("""JSON.parse\("([^*]*)"\)""").find(script2)?.groupValues!![1]
+
+        val data = json.parseAs<Hentai>()
+        return data.images.pages.mapIndexed { i, image ->
+            Page(
+                i,
+                "",
+                "${baseUrl.replace("://", "://i$mediaServer.")}/galleries/${data.media_id}/${i + 1}" +
```
Comment (AwkwardPeak7) [inline src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt]:
```suggestion
                imageUrl = "${baseUrl.replace("://", "://i$mediaServer.")}/galleries/${data.media_id}/${i + 1}" +
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
