### PR TITLE
Coomer Fix "Low Resolution" Preference error

### LINKED ISSUE #3412: low resolution pictures doesn't load in Coomer
### Source information

Coomer 1.4.11

### Source language

Multi 

### Steps to reproduce

I checked the low resolution option in the extension and cleared up the cach.
Screenshot_2024-06-04-15-32-06-54_551f7f0ca926862b368845ce7ee433aa

### Expected behavior

Low resolution pictures should load up faster but it never does.

### Actual behavior

Always get the error "this image couldn't be loaded"
Screenshot_2024-06-04-15-31-48-80_551f7f0ca926862b368845ce7ee433aa

Clicking on open in WebView show the higher resolution image.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KenjieDec**
Fixes #3412

Checklist:
- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt [hunk 1]
```diff
@@ -194,12 +194,14 @@ open class Kemono(
 
     override fun imageRequest(page: Page): Request {
         val imageUrl = page.imageUrl!!
-        if (!preferences.getBoolean(USE_LOW_RES_IMG, false)) return GET(imageUrl, headers)
-        val index = imageUrl.indexOf('/', startIndex = 8) // https://
+
+        if (!preferences.getBoolean("USE_LOW_RES_IMG", false)) return GET(imageUrl, headers)
```
Comment (AwkwardPeak7) [inline lib-multisrc/kemono/src/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt]: use the constant val for key instead

**Review by AwkwardPeak7 — APPROVED** [review]
