### PR TITLE
HeanCMS: Add login preference

### LINKED ISSUE #2056: Omega Scans: add ability to read paid chapters
### Source information

Omega Scans 1.4.39

### Source language

English

### Steps to reproduce

1. Login to omega scans with user details
2. Open a manga with paid chapter

### Expected behavior

The chapter should open

### Actual behavior

Get an error saying paid chapter unavailable

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 9

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### LINKED ISSUE #2079: omega scans not fully working
### Source information

omega scans 1.4.39

### Source language

English

### Steps to reproduce

Open: Trapped in the Academy's Eroge, ch.11

Image fails to load,

Download chapter: `Expected URL scheme 'http' or 'https' but no scheme wa...`

### Expected behavior

Click chapter receive bacon

### Actual behavior

No bacon received

### Mihon/Tachiyomi version

0.16.4-6564

### Android version

Android 10

### Other details

Tried migrating and reinstalling extension. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
The extension is sending the Authorization header, but i can't test if this actually get the pages (maybe @vinaysb can help)

Closes #2056
Closes #2079

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by vinaysb** [comment]
Thanks for the PR @bapeey!

Just tried it out, the login does work. But the images do not load anymore. Based on some tinkering I did, I think its because the images them self do not need the auth token (atleast this is the case for omega scans).

**Comment by bapeey** [comment]
I removed the authHeaders from imageRequest, is working now?

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 1]
```diff
@@ -70,6 +76,37 @@ abstract class HeanCms(
...
+        if (preferences.loginPref && enableLogin) {
+            val token = getToken()
+            if (token.isNotBlank()) {
+                builder.add("Authorization", "Bearer $token")
+            }
+        }
+        builder.build()
+    }
+
+    private fun getToken(): String {
```
Comment (vetleledaal) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt]: Might be better to make this nullable so you don't rely on the string being blank elsewhere. Unless you have observed the response containing an empty string and want to handle that as well.
```suggestion
    private fun getToken(): String? {
```

**Comment by vinaysb** [comment]
Yes it works right now 👍

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 2]
```diff
@@ -70,6 +76,36 @@ abstract class HeanCms(
...
+    private fun getToken(): String? {
+        val body = HeanCmsLoginPayloadDto(preferences.user, preferences.password)
+            .let { json.encodeToString(listOf(it)) }
+            .toRequestBody()
+
+        val loginHeaders = headersBuilder()
+            .add("Next-Action", "cecce9cf69dc6eb35c5b01f633f6b1032d38c61b")
+            .build()
+
+        val response = client.newCall(POST("$baseUrl/login", loginHeaders, body)).execute()
```
Comment (AwkwardPeak7) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt]: they appear to have `/login` endpoint in the api, which returns the token and expiration date; just post the `HeanCmsLoginPayloadDto` without list.

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 3]
```diff
@@ -70,6 +76,36 @@ abstract class HeanCms(
...
+        if (preferences.loginPref && enableLogin) {
+            val token = getToken()
+            if (token != null) {
+                builder.add("Authorization", "Bearer $token")
+            }
+        }
+        builder.build()
+    }
+
+    private fun getToken(): String? {
```
Comment (AwkwardPeak7) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt:95]: instead of logging in everytime, maybe login once and save the token in the sharedpreference along with expiration date. and if the token is near expiration, refresh it by logging in again

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by bapeey** [comment]
@vinaysb can you test again?

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 4]
```diff
@@ -343,6 +384,27 @@ abstract class HeanCms(
...
+
+        if (enableLogin) {
+            SwitchPreferenceCompat(screen.context).apply {
+                key = LOGIN_PREF
+                title = intl["pref_login_title"]
+                summary = intl["pref_login_summary"]
+                setDefaultValue(LOGIN_PREF_DEFAULT)
+            }.also(screen::addPreference)
+
+            EditTextPreference(screen.context).apply {
```
Comment (AwkwardPeak7) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt:398]: force clear the token cache if username or password is updated

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 5]
```diff
@@ -343,6 +384,27 @@ abstract class HeanCms(
             summaryOff = intl["pref_show_paid_chapter_summary_off"]
             setDefaultValue(SHOW_PAID_CHAPTERS_DEFAULT)
         }.also(screen::addPreference)
+
+        if (enableLogin) {
+            SwitchPreferenceCompat(screen.context).apply {
```
Comment (AwkwardPeak7) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt]: imo instead of another preference, check if both email and password are not empty to use login credentials

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 6]
```diff
@@ -70,6 +76,39 @@ abstract class HeanCms(
         .add("Origin", baseUrl)
         .add("Referer", "$baseUrl/")
 
+    private fun authHeaders(): Headers {
+        val builder = headersBuilder()
+        if (preferences.loginPref && enableLogin) {
```
Comment (AwkwardPeak7) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt]:
```suggestion
        if (enableLogin && preferences.loginPref) {
```
check local value first before hitting the preference

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 7]
```diff
@@ -70,6 +76,39 @@ abstract class HeanCms(
...
+
+    private fun getToken(): String? {
+        val body = FormBody.Builder()
+            .add("email", preferences.user)
+            .add("password", preferences.password)
+            .build()
+
+        val response = client.newCall(POST("$apiUrl/login", headers, body)).execute()
+
+        if (!response.isSuccessful) return null
```
Comment (AwkwardPeak7) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt]: maybe throw if bad request like invalid username or password

File: lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt [hunk 8]
```diff
@@ -100,7 +100,7 @@ abstract class HeanCms(
 
         val response = client.newCall(POST("$apiUrl/login", headers, body)).execute()
 
-        if (!response.isSuccessful) return null
+        if (!response.isSuccessful) throw Exception(intl["invalid_credentials_error"])
```
Comment (AwkwardPeak7) [inline lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt]: I was think throw the actual error from api;
```
result.errors?.let { errors ->
    val message = errors.firstOrNull()?.message ?: intl["login_failed_unknown_error"]
    
    throw Exception(message)
}
```

Comment (bapeey) [reply lib-multisrc/heancms/src/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt]: another DTO if response is not successful or ~add 'errors' to 'HeanCmsTokenPayloadDto' and throw if exists~ (that's ugly)

**Comment by vinaysb** [comment]
@bapeey it is still working

**Review by AwkwardPeak7 — APPROVED** [review]
