### PR TITLE
LeerCapitulo: Fix script not found

### LINKED ISSUE #4628: Problem with opening chapters leercapitulo
### Source information

1.4.9

### Source language

Español 

### Steps to reproduce

Opening any chapter, whether old or new, as well as accessing the page from the application, the error occurs.
Screenshot_2024-08-14-14-29-02-679_eu kanade tachiyomi
Uploading Screenshot_2024-08-14-14-28-54-286_eu.
![Screenshot_2024-08-14-14-28-54-286_eu kanade tachiyomi
kanade.tachiyomi.jpg…]()

### Expected behavior

Load the chapter or chapters, the main page is checked from browsers and no error occurs 

### Actual behavior

The extension loads the pages correctly and when accessing the browser, it also shows the selected chapter.

### Mihon/Tachiyomi version

0.15.3

### Android version

14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt [hunk 1]
```diff
@@ -33,10 +33,12 @@ class LeerCapitulo : ParsedHttpSource() {
 
     override val baseUrl = "https://www.leercapitulo.co"
 
-    override val client = super.client.newBuilder()
+    override val client = network.cloudflareClient.newBuilder()
         .rateLimitHost(baseUrl.toHttpUrl(), 1, 3)
         .build()
 
+    private val notRateLimitClient = network.cloudflareClient.newBuilder().build()
```
Comment (vetleledaal) [inline src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt]:
```suggestion
    private val notRateLimitClient = network.cloudflareClient
```

Should be the same unless I'm missing some subtle difference.

File: src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt [hunk 2]
```diff
@@ -177,17 +179,24 @@ class LeerCapitulo : ParsedHttpSource() {
...
 
-        val scriptUrl = document.selectFirst("section.bodycontainer > script[src$=.js]")?.attr("abs:src")
-            ?: throw Exception("Script not found")
+        val scripts = document.select("head > script[src^=/assets/][src$=.js]")
+
+        var dataScript: String? = null
 
-        val scriptData = client.newCall(GET(scriptUrl, headers)).execute().body.string()
+        for (script in scripts) {
+            val scriptData = notRateLimitClient.newCall(GET(script.attr("abs:src"), headers)).execute().body.string()
```
Comment (vetleledaal) [inline src/es/leercapitulo/src/eu/kanade/tachiyomi/extension/es/leercapitulo/LeerCapitulo.kt]: Would it make sense to cache this for a short while, like the index of the correct script? Not as in filtering out, but rather changing the order scripts are requested.

**Review by vetleledaal — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
