### PR TITLE
MangaEsp: Update domain and add alternative names

### LINKED ISSUE #1468: Mangaesp pages list not charging
### Source information

MangaEsp 1.4.1

### Source language

Spanish

### Steps to reproduce

Go to mangaesp source
Select any manhwa
Select a chapter

### Expected behavior

Pages displayed

### Actual behavior

Pages not found

### Mihon/Tachiyomi version

Aniyomi 0.15.2.4

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by bapeey**
Closes #1468 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/mangaesp/src/eu/kanade/tachiyomi/extension/es/mangaesp/MangaEsp.kt [hunk 1]
```diff
@@ -165,40 +161,22 @@ class MangaEsp : HttpSource() {
             ?: throw Exception("No se pudo encontrar los detalles del manga")
         val unescapedJson = mangaDetailsJson.replace("\\", "")
```
Comment (AwkwardPeak7) [inline src/es/mangaesp/src/eu/kanade/tachiyomi/extension/es/mangaesp/MangaEsp.kt]: why not use`unescape` function here too?

File: src/es/mangaesp/src/eu/kanade/tachiyomi/extension/es/mangaesp/MangaEspDto.kt [hunk 2]
```diff
@@ -1,91 +1,119 @@
...
+    private val slug: String,
+    @SerialName("created_at") private val date: String,
+) {
+    fun toSChapter(seriesSlug: String, dateFormat: SimpleDateFormat): SChapter {
+        return SChapter.create().apply {
+            name = if (this@ChapterDto.name.isNullOrBlank()) {
+                "Capítulo ${number.toString().removeSuffix(".0")}"
+            } else {
+                "Capítulo ${number.toString().removeSuffix(".0")} - ${this@ChapterDto.name}"
+            }
```
Comment (AwkwardPeak7) [inline src/es/mangaesp/src/eu/kanade/tachiyomi/extension/es/mangaesp/MangaEspDto.kt]:
```suggestion
            name = "Capítulo ${number.toString().removeSuffix(".0")}"
            if (!this@ChapterDto.name.isNullOrBlank()) {
                name += " - ${this@ChapterDto.name}"
            }
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
