### PR TITLE
Add MangoTheme multisrc: Fix mangotoons, imperio and add bladetoons

### LINKED ISSUE #13320: Mango Toons: `Unexpected JSON token` error
### Source information

Mango toons 1.4.5

### Source language

Português brasileiro 

### Steps to reproduce

Os capítulos não abre, mas no Webview abrem normalmente

### Expected behavior

Image

### Actual behavior

Image

### Mihon/Mihon fork version

Mihon 0.19.3 

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #13979: Sagrado Império da Britannia: New website design/URL (`imperiodabritannia.net`), `Failed to bypass Cloudflare` error
### Source information

Sagrado império da britannia 1.4.52

### Source language

Português Brasil 

### Source new URL

https://imperiodabritannia.net/

### Other details

_No response_

### Acknowledgements

- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have checked WebView to see the source's main URL is not up-to-date, or has to redirect into the new URL.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues/) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #14070: Source request (PT-BR): BladeToons
### Source name

BladeToons

### Source link

https://bladetoons.com/

### Source language

PT BR

### Other details

_No response_

### Acknowledgements

- [x] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a meaningful title with the source name.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by FelipeGFA**
closes #14070
closes #13979
closes #13320

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by choppeh** [comment]
you can use an interceptor to decrypt the response before the json parser: https://github.com/choppeh/extensions-source/blob/dcb3bea592dcfaa3a94226cf9b855958884ffcd9/src/pt/imperiodabritannia/src/eu/kanade/tachiyomi/extension/pt/imperiodabritannia/AESDecryptInterceptor.kt

**Comment by FelipeGFA** [comment]
> you can use an interceptor to decrypt the response before the json parser: https://github.com/choppeh/extensions-source/blob/dcb3bea592dcfaa3a94226cf9b855958884ffcd9/src/pt/imperiodabritannia/src/eu/kanade/tachiyomi/extension/pt/imperiodabritannia/AESDecryptInterceptor.kt

i added a [interceptor](https://github.com/keiyoushi/extensions-source/pull/14096/changes/764e1f0fc208ec985bd8717c7bd5a8cfae597233) for decrypt

File: lib-multisrc/mangotheme/src/eu/kanade/tachiyomi/multisrc/mangotheme/MangoTheme.kt [hunk 1]
```diff
@@ -0,0 +1,464 @@
...
+
+    protected abstract fun getFormatFilterOptions(): Array<Pair<String, String>>
+
+    protected abstract fun getStatusFilterOptions(): Array<Pair<String, String>>
+
+    protected abstract fun getTagFilterOptions(): List<MangoThemeTagFilterOption>
+
+    protected val preferences by getPreferencesLazy()
+
+    protected val json by lazy { jsonInstance }
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangotheme/src/eu/kanade/tachiyomi/multisrc/mangotheme/MangoTheme.kt]: use `keiyoushi.utils.parseAs` and `keiyoushi.utils.toJsonString` instead

File: lib-multisrc/mangotheme/src/eu/kanade/tachiyomi/multisrc/mangotheme/MangoTheme.kt [hunk 2]
```diff
@@ -0,0 +1,464 @@
...
+                    .build(),
+            )
+
+            if (retriedResponse.code != 401) {
+                return@Interceptor retriedResponse
+            }
+            retriedResponse.close()
+        }
+
+        throw java.io.IOException(loginRequiredMessage)
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangotheme/src/eu/kanade/tachiyomi/multisrc/mangotheme/MangoTheme.kt]: import

File: lib-multisrc/mangotheme/src/eu/kanade/tachiyomi/multisrc/mangotheme/MangoThemeDTO.kt [hunk 3]
```diff
@@ -0,0 +1,228 @@
...
+    val sucesso: Boolean = false,
+    val dados: T? = null,
+    val obras: T? = null,
+    val obra: T? = null,
+    val data: T? = null,
+    val capitulos: T? = null,
+    val capitulo: T? = null,
+    val formatos: T? = null,
+    val status: T? = null,
+    val tags: T? = null,
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangotheme/src/eu/kanade/tachiyomi/multisrc/mangotheme/MangoThemeDTO.kt]: use `JsonNames` annotation instead

**Review by AwkwardPeak7 — DISMISSED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
