### PR TITLE
Insasnoscan Fix and domain change

### LINKED ISSUE #14891: Insanos Scan
### Source information

es.insanosscan

### Source language

Español

### Source new URL

https://insanoslibrary.com/

### Other details

_No response_

### Acknowledgements

- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have checked WebView to see the source's main URL is not up-to-date, or has to redirect into the new URL.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues/) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14891

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 1]
```diff
@@ -1,5 +1,127 @@
...
+            .add("action", "adar_search")
+            .add("nonce", nonce)
+            .add("query", query)
+            .build()
+        return POST("$baseUrl/wp-admin/admin-ajax.php", headers, body)
+    }
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        val root = JSONObject(response.body.string())
+        val data = root.optJSONArray("data") ?: return MangasPage(emptyList(), false)
```
Comment (AwkwardPeak7) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: use kotlinx serialization classes for json

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 2]
```diff
@@ -1,5 +1,127 @@
...
+        name = element.selectFirst("span.chapter-row__num")?.text()
+            ?: element.selectFirst("span.chapter-row__title")?.text()
+            ?: "Capítulo"
+        date_upload = parseDate(element.selectFirst("span.chapter-row__date")?.text())
+    }
+
+    private fun parseDate(raw: String?): Long {
+        if (raw.isNullOrBlank()) return 0L
+        return runCatching {
+            val sdf = java.text.SimpleDateFormat("dd MMM yyyy", java.util.Locale("es"))
```
Comment (AwkwardPeak7) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: put date format in class as val, so it is not recreated everytime.
also use `keiyoushi.utils.tryParse` for dates

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by darwin-256** [comment]
Moved from ParsedHttpSource to HttpSource and added setting to filter paid chapters

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 3]
```diff
@@ -1,5 +1,219 @@
...
+    override fun popularMangaRequest(page: Int): Request = GET("$baseUrl/manga/?orderby=views&page=$page", headers)
+
+    override fun popularMangaParse(response: Response): MangasPage {
+        val document = response.asJsoup()
+        val mangas = document.select("article.catalog-card").map { element ->
+            SManga.create().apply {
+                val link = element.selectFirst("a.catalog-card__link")!!
+                setUrlWithoutDomain(link.attr("href"))
+                title = element.selectFirst("h2.catalog-card__title")!!.text()
+                thumbnail_url = element.selectFirst("img.catalog-card__cover")?.attr("src")
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: Absolute url

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 4]
```diff
@@ -1,5 +1,219 @@
...
+        val body = FormBody.Builder()
+            .add("action", "adar_search")
+            .add("nonce", nonce)
+            .add("query", query)
+            .build()
+        return POST("$baseUrl/wp-admin/admin-ajax.php", headers, body)
+    }
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        val root = json.parseToJsonElement(response.body.string()).jsonObject
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: Use parseAs utils for json parser

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 5]
```diff
@@ -1,5 +1,219 @@
...
+    override fun mangaDetailsRequest(manga: SManga): Request = GET("$baseUrl${manga.url}", headers)
+
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+        return SManga.create().apply {
+            title = document.selectFirst("h1.series-main-title")!!.text()
+            thumbnail_url = document.selectFirst("img.series-cover-img")?.attr("src")
+            description = document.selectFirst("div.synopsis-content")?.text()
+            status = when (
+                document.selectFirst("span.data-badge--status")?.text()?.trim()?.lowercase()
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: text() already includes trim()

File: src/es/insanosscan/build.gradle [hunk 6]
```diff
@@ -1,10 +1,8 @@
 ext {
-    extName = 'Insanos Scan'
+    extName = 'InsanosScan'
     extClass = '.InsanosScan'
-    themePkg = 'mangathemesia'
-    baseUrl = 'https://insanosmanhua.com'
-    overrideVersionCode = 0
-    isNsfw = false
+    extVersionCode = 31
+    containsNsfw = false
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/insanosscan/build.gradle]:
```suggestion
    isNsfw = false
```

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 7]
```diff
@@ -1,5 +1,219 @@
...
+import uy.kohesive.injekt.api.get
+import java.text.SimpleDateFormat
+import java.util.Locale
 
-class InsanosScan : MangaThemesia("Insanos Scan", "https://insanosmanhua.com", "es")
+class InsanosScan :
+    HttpSource(),
+    ConfigurableSource {
+
+    override val name = "InsanosScan"
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt:35]: If you change the name, don't forget to add the override id. And if the old URL is not compatible, add the override versionId.

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 8]
```diff
@@ -1,5 +1,219 @@
...
+    // ========================= Nonce =========================
+
+    private val nonce: String by lazy {
+        val doc = client.newCall(GET(baseUrl, headers)).execute().use { it.asJsoup() }
+        val b64 = doc.selectFirst("script#adar-main-js-extra")
+            ?.attr("src")
+            ?.removePrefix("data:text/javascript;base64,")
+            ?: return@lazy ""
+        val js = String(android.util.Base64.decode(b64, android.util.Base64.DEFAULT))
+        Regex(""""nonce"\s*:\s*"([^"]+)"""").find(js)?.groupValues?.get(1) ?: ""
```
Comment (MuhamadSyabitHidayattulloh) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: Seperate regex

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 9]
```diff
@@ -1,5 +1,227 @@
...
+    override val baseUrl = "https://insanoslibrary.com"
+    override val lang = "es"
+    override val supportsLatest = true
+    override val versionId = 2
+
+    override val client = network.cloudflareClient
+
+    private val dateFormat = SimpleDateFormat("dd MMM yyyy", Locale("es"))
+
+    private val json = Json { ignoreUnknownKeys = true }
```
Comment (AwkwardPeak7) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: use keiyoushi.utils.parseAs for json

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 10]
```diff
@@ -1,5 +1,227 @@
...
+
+    // ========================= Preferences =========================
+
+    private val preferences: SharedPreferences by lazy {
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
+    }
```
Comment (AwkwardPeak7) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: use keiyoushi.utils.getPreference or one of the alternative

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 11]
```diff
@@ -1,5 +1,227 @@
...
+
+    // ========================= Nonce =========================
+
+    private val nonce: String by lazy {
+        val doc = client.newCall(GET(baseUrl, headers)).execute().use { it.asJsoup() }
+        val b64 = doc.selectFirst("script#adar-main-js-extra")
+            ?.attr("src")
+            ?.removePrefix("data:text/javascript;base64,")
+            ?: return@lazy ""
+        val js = String(android.util.Base64.decode(b64, android.util.Base64.DEFAULT))
```
Comment (AwkwardPeak7) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: import

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt [hunk 12]
```diff
@@ -1,5 +1,227 @@
...
+        val body = FormBody.Builder()
+            .add("action", "adar_search")
+            .add("nonce", nonce)
+            .add("query", query)
+            .build()
+        return POST("$baseUrl/wp-admin/admin-ajax.php", headers, body)
+    }
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        val root = response.parseAs<JsonObject>()
```
Comment (AwkwardPeak7) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScan.kt]: consider using kotlinx serialization classes

File: src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScanActivity.kt [hunk 13]
```diff
@@ -0,0 +1,37 @@
...
+
+class InsanosScanActivity : Activity() {
+
+    override fun onCreate(savedInstanceState: Bundle?) {
+        super.onCreate(savedInstanceState)
+
+        val pathSegments = intent?.data?.pathSegments
+        if (pathSegments != null && pathSegments.size >= 2) {
+            val slug = pathSegments[1]
+            val query = slug.replace('-', ' ')
```
Comment (AwkwardPeak7) [inline src/es/insanosscan/src/eu/kanade/tachiyomi/extension/es/insanosscan/InsanosScanActivity.kt]: consider passing full url

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
