### PR TITLE
BigSolo : Fix extension #11226

### LINKED ISSUE #11226: Big Solo : No page found
### Source information

Big Solo Latest

### Source language

French

### Steps to reproduce

Open a chapter

### Expected behavior

It loads

### Actual behavior

No page found

Image

The Webview shows the chapter normally

### Mihon/Tachiyomi version

Latest Mihon 

### Android version

16

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by CriosChan**
Closes #11226 

Reversal of changes made by PR #11156, as BigSolo is no longer based on “ScanR” and corrects changes made to the backend.
Source name from "Big Solo" to "BigSolo" (this revert name change from PR #11156)

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt [hunk 1]
```diff
@@ -1,10 +1,163 @@
...
+import okhttp3.Response
+import java.net.URI
+
+class BigSolo : HttpSource() {
+
+    companion object {
+        private const val SERIES_DATA_SELECTOR = "#series-data-placeholder"
+    }
+
+    override val name = "Big Solo"
```
Comment (apix0n) [inline src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt]: "BigSolo" and not "Big Solo"

File: src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt [hunk 2]
```diff
@@ -1,10 +1,163 @@
...
+            }
+        }
+
+        return MangasPage(mangaList, false)
+    }
+
+    // Details
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+        val jsonData = document.selectFirst(SERIES_DATA_SELECTOR)!!.html()
```
Comment (apix0n) [inline src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt]: can you try using the /data/series/{slug} endpoint instead of html parsing?

File: src/fr/bigsolo/AndroidManifest.xml [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+            android:exported="true"
+            android:theme="@android:style/Theme.NoDisplay">
+            <intent-filter>
+                <action android:name="android.intent.action.VIEW" />
+
+                <category android:name="android.intent.category.DEFAULT" />
+                <category android:name="android.intent.category.BROWSABLE" />
+
+                <data
+                    android:host="bigsolo.org"
```
Comment (vetleledaal) [inline src/fr/bigsolo/AndroidManifest.xml:17]: Should include the `www` subdomain as well. It's indexed on search indexes and doesn't automatically redirect.

File: src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSoloDto.kt [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+import eu.kanade.tachiyomi.source.model.SManga
+import kotlinx.serialization.SerialName
+import kotlinx.serialization.Serializable
+
+/**
+ * Data Transfer Objects for BigSolo extension
+ */
+
+@Serializable
+data class SeriesResponse(
```
Comment (vetleledaal) [inline src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSoloDto.kt]: Regular classes are fine here.

```suggestion
class SeriesResponse(
```

File: src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSoloDto.kt [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+    val active: Boolean,
+)
+
+// DTO to SManga extension functions
+fun Serie.toDetailedSManga(): SManga = SManga.create().apply {
+    title = this@toDetailedSManga.title
+    description = this@toDetailedSManga.description
+    artist = this@toDetailedSManga.artist
+    author = this@toDetailedSManga.author
+    genre = this@toDetailedSManga.tags.joinToString(", ")
```
Comment (vetleledaal) [inline src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSoloDto.kt]: `, ` is the default and can be omitted.
```suggestion
    genre = this@toDetailedSManga.tags.joinToString()
```

File: src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt [hunk 6]
```diff
@@ -1,10 +1,162 @@
...
+    }
+
+    // Details
+    override fun mangaDetailsParse(response: Response): SManga {
+        val document = response.asJsoup()
+        val splitedPath = URI(document.baseUri()).path.split("/")
+        val slug = splitedPath[1]
+        val serieJson =
+            client.newCall(GET("$baseUrl/data/series/$slug", headers))
+                .execute()
```
Comment (vetleledaal) [inline src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt]: You're not really using the response, so I'm tempted to suggest this should be done in `mangaDetailsRequest()` instead. This would allow you to skip a request.

Keep the same URL format in the SManga model to prevent duplicate library entries.

File: src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt [hunk 7]
```diff
@@ -1,10 +1,165 @@
...
+        }
+
+        return MangasPage(mangaList, false)
+    }
+
+    // Details
+    override fun fetchMangaDetails(manga: SManga): Observable<SManga> {
+        val splitedPath = URI(manga.url).path.split("/")
+        val slug = splitedPath[1]
+        return client.newCall(GET("$baseUrl/data/series/$slug", headers))
```
Comment (AwkwardPeak7) [inline src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt]: this should be done in `mangaDetailsRequest`

File: src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt [hunk 8]
```diff
@@ -1,10 +1,165 @@
...
+        val mangaList = mutableListOf<SManga>()
+
+        val fragment = response.request.url.fragment
+        val searchQuery = fragment ?: ""
+
+        for (serie in allSeries) {
+            if (searchQuery.startsWith("SLUG:") && serie.slug == searchQuery.removePrefix("SLUG:")) {
+                mangaList.add(serie.toDetailedSManga())
+                break
+            }
```
Comment (AwkwardPeak7) [inline src/fr/bigsolo/src/eu/kanade/tachiyomi/extension/fr/bigsolo/BigSolo.kt]: return early

**Comment by CriosChan** [comment]
Thank you all for your reviews!

**Review by AwkwardPeak7 — APPROVED** [review]
