### PR TITLE
smbc: add extension for smbc-comics.com

### LINKED ISSUE #9648: SMBC is not listed on Hiveworks anymore
### Source information

Hiveworks 1.4.10

### Source language

English

### Steps to reproduce

[SMBC](https://www.smbc-comics.com/) is no longer affiliated with Hiveworks, per this announcement: https://news.ycombinator.com/item?id=43269614

As a result, when searching for SMBC in the Hiveworks source, it does not appear in the results, and cannot be added. However, the SMBC website remains compatible with the Hiveworks extension, so if you already have the comic added, it still works and new updates can still be fetched.

### Expected behavior

It should be possible to add SMBC in Mihon.

It's not clear to me what the correct way to do this is. There are a few options:
1. Create a new SMBC extension, copy the Hiveworks code to it
2. Have a new SMBC extension and the existing Hiveworks extension both import shared logic from a library
3. Hardcode SMBC as a search result in Hiveworks (probably wrong as SMBC is not actually a Hiveworks comic anymore)

If somebody can advise on which approach would be considered the best, I can implement it.

### Actual behavior

You get no search results when you search for SMBC in the Hiveworks source

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15 (GrapheneOS) 2025061600

### Other details

See also https://github.com/keiyoushi/extensions-source/pull/9003. I didn't realize it at the time but the timing suggests that that issue was caused as a side effect of SMBC leaving Hiveworks.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by solkaz**
Adds an extension for Saturday Morning Breakfast Comics

Closes #9648

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Smol-Ame** [comment]
Put "Closes #9648" in your PR description as the related issue.

**Comment by solkaz** [comment]
@Smol-Ame Fixed

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+import okhttp3.Request
+import okhttp3.Response
+import org.jsoup.nodes.Document
+import org.jsoup.nodes.Element
+import rx.Observable
+import java.text.ParseException
+import java.text.SimpleDateFormat
+import java.util.Locale
+
+class SaturdayMorningBreakfastComics : ParsedHttpSource() {
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Extend `HttpSource` instead.

Also add a comment to say it is split from `HiveWorks`.

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+        SimpleDateFormat("MMMM d, yyyy", Locale.ENGLISH)
+    }
+
+    /**
+     *  When fetching the archive page (/comics/archive/), the server responds with a 500
+     *  error code alongside HTML code where the list of chapters can be fetched. If we don't catch
+     *  the error here, it'll be treated as an any other failed request would; therefore we check
+     *  if the archive page specifically is being fetched, and change the error code if that's the case
+     */
+    private fun errorIntercept(chain: Interceptor.Chain): Response {
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Can override `fetchChapterList` and use `asObservable` instead of `asObservableSuccess`. Then this is not needed.

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+        if (image.hasAttr("title")) {
+            val text = wordWrap(image.attr("title"))
+            pages.add(Page(1, "", text.image()))
+        }
+        pages.add(Page(2, "", document.select(AFTERCOMIC_SELECTOR).attr("abs:src")))
+
+        return pages
+    }
+
+    private fun parseDate(dateStr: String): Long {
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Use `SimpleDateFormat.tryParse(String?)` provided by the `core` module.

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 4]
```diff
@@ -0,0 +1,174 @@
...
+
+        return Observable.just(MangasPage(arrayListOf(manga), false))
+    }
+
+    override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> = Observable.just(MangasPage(emptyList(), false))
+
+    override fun fetchMangaDetails(manga: SManga): Observable<SManga> = Observable.just(manga)
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val chapterList = super.chapterListParse(response).distinct()
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Is there any duplicate items? The behavior of calling `distinct()` on `SManga` is undefined.

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 5]
```diff
@@ -0,0 +1,174 @@
...
+        return chapterList.mapIndexed {
+                i, ch ->
+            ch.apply { chapter_number = chapterList.size.toFloat() - i }
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Behavior looks weird. Should number the chapters from 1 then reverse the list. Fix it after you extend `HttpSource`.

File: src/en/saturdaymorningbreakfastcomics/build.gradle [hunk 6]
```diff
@@ -0,0 +1,8 @@
+ext {
+    extName = 'SaturdayMorningBreakfastComics'
+    extClass = '.SaturdayMorningBreakfastComics'
+    extVersionCode = 3
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/build.gradle]:
```suggestion
    extVersionCode = 1
```

File: src/en/saturdaymorningbreakfastcomics/build.gradle [hunk 7]
```diff
@@ -0,0 +1,8 @@
+ext {
+    extName = 'SaturdayMorningBreakfastComics'
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/build.gradle]:
```suggestion
    extName = 'Saturday Morning Breakfast Comics'
```

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 8]
```diff
@@ -0,0 +1,174 @@
...
+    companion object {
+        private const val THUMBNAIL_URL =
+            "https://fakeimg.ryd.tools/550x780/ffffff/6e7b91/?font=museo&text=SMBC"
+
+        const val LATIN_ALT_TEXT_URL =
+            "https://fakeimg.ryd.tools/1500x2126/ffffff/000000/?font=museo&font_size=42"
+
+        const val IMAGE_SELECTOR = "img#cc-comic"
+
+        const val AFTERCOMIC_SELECTOR = "#aftercomic > img"
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Inline these.

**Review by stevenyomi — COMMENTED** [review]
Should remove all SMBC-related logic from Hiveworks and throw an exception (in their `chapterListRequest`) to let users download this new extension and migrate. And bump Hiveworks too.

Also remove the code mentioned https://github.com/keiyoushi/extensions-source/pull/9003#discussion_r2144166320.

cc @raxod502

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt (hunk 1 above)
Comment (stevenyomi) [reply src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Should also add a comment in Hiveworks to say SMBC is split to separate extension.

Comment (solkaz) [reply src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: As this is my first extension (and also my first time using Kotlin): can you explain why `HttpSource` is preferred over `ParsedHttpSource` in this case?

Comment (stevenyomi) [reply src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Shortly put, you're not using most of its methods, and we are deprecating that class whatever source website you're targeting. (I updated the contribution guide a few days ago)

If you want to know more, `ParsedHttpSource` is designed for traditional server-rendered websites where DOM structures and CSS selectors are very simple. Many websites now have some Ajax/API calls and complex page structures, so people usually need to override methods from `HttpSource`. Besides, there's really not much boilerplate code to write to achieve a `ParsedHttpSource` - basically `response.asJsoup().select(selector).map(toSManga)`, which is a lot more readable than a bunch of pre-defined abstract methods.

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 9]
```diff
@@ -0,0 +1,146 @@
...
+            artist = "Zach Weinersmith"
+            author = "Zach Weinersmith"
+            status = SManga.ONGOING
+            url = "comic/archive/"
+            description =
+                "SMBC is a daily comic strip about life, philosophy, science, mathematics, and dirty jokes."
+            thumbnail_url = "https://fakeimg.ryd.tools/550x780/ffffff/6e7b91/?font=museo&text=SMBC"
+        }
+
+        return Observable.just(MangasPage(arrayListOf(manga), false))
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]:
```suggestion
        return Observable.just(MangasPage(listOf(manga), false))
```

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 10]
```diff
@@ -0,0 +1,146 @@
...
+        return client.newCall(GET("$baseUrl/${manga.url}"))
+            .asObservable()
+            .doOnNext { response ->
+                if (response.code == 500) {
+                    response.newBuilder().code(200).build()
+                } else {
+                    response
+                }
+            }
+            .map { response ->
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]:
```suggestion
            .map { response ->
                if (!response.isSuccessful && response.code != 500) {
                    response.close()
                    throw Exception("HTTP ${response.code}")
                }
```

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 11]
```diff
@@ -0,0 +1,146 @@
...
+                val document = response.asJsoup()
+                val pages = mutableListOf<Page>()
+                val image = document.select("img#cc-comic")
+                pages.add(Page(0, "", image.attr("abs:src")))
+                if (image.hasAttr("title")) {
+                    pages.add(Page(1, "", wordWrap(image.attr("title")).image()))
+                }
+                pages.add(Page(2, "", document.select("#aftercomic > img").attr("abs:src")))
+                pages
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: Use `pageListParse()`.

The default `pageListRequest()` is already what you're using (in fact, `baseUrl + chapter.url` which is more correct) so you can omit that.

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 12]
```diff
@@ -0,0 +1,146 @@
...
+        }
+    }
+
+    override fun fetchPopularManga(page: Int): Observable<MangasPage> {
+        val manga = SManga.create().apply {
+            title = "Saturday Morning Breakfast Comics"
+            artist = "Zach Weinersmith"
+            author = "Zach Weinersmith"
+            status = SManga.ONGOING
+            url = "comic/archive/"
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]:
```suggestion
            url = "/comic/archive"
```

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 13]
```diff
@@ -0,0 +1,146 @@
...
+    override fun fetchSearchManga(
+        page: Int,
+        query: String,
+        filters: FilterList,
+    ): Observable<MangasPage> = Observable.just(MangasPage(emptyList(), false))
+
+    override fun fetchMangaDetails(manga: SManga): Observable<SManga> = Observable.just(manga)
+
+    override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> {
+        return client.newCall(GET("$baseUrl/${manga.url}"))
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]:
```suggestion
        return client.newCall(chapterListRequest(manga))
```

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt (hunk 1 above)
Comment (stevenyomi) [reply src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]: You should add comments before both classes to mention their link.

File: src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt [hunk 14]
```diff
@@ -0,0 +1,146 @@
...
+            }
+            .map { response ->
+                response.asJsoup().select("option[value*=\"comic/\"]")
+                    .mapIndexed { index, element ->
+                        val chapter = SChapter.create()
+                        chapter.url = "/${element.attr("value")}"
+                        val (date, title) = element.text().split(" - ")
+                        chapter.name = title
+                        chapter.date_upload = dateFormat.tryParse(date)
+                        chapter.chapter_number = index.toFloat()
```
Comment (stevenyomi) [inline src/en/saturdaymorningbreakfastcomics/src/eu/kanade/tachiyomi/extension/en/saturdaymorningbreakfastcomics/SaturdayMorningBreakfastComics.kt]:
```suggestion
                        chapter.chapter_number = (index + 1).toFloat()
```

**Review by stevenyomi — APPROVED** [review]
