### PR TITLE
 Flamecomics: Fix images

### LINKED ISSUE #9778: Flame Comics chapter images not loading, webview works
### Source information

Flame Comics 1.4.42

### Source language

English

### Steps:
1. Open any entry from Flame Comics (For reproducibility, The Chaotic God of Extraordinary Strength, chapter 82)
2. See that images do not load
3. Open image in webview
4. See error `"url" parameter is valid but upstream response is invalid`

### Expected behavior

Images should load as expected

### Actual behavior

Images do not load in chapter view, recieve error message `"url" parameter is valid but upstream response is invalid` when viewing image webview

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 15

### Other details

Downloading also fails

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
Closes #9778

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 1]
```diff
@@ -51,21 +51,18 @@ class FlameComics : HttpSource() {
...
 
-    private fun imageApiUrlBuilder(dataUrl: String) = baseUrl.toHttpUrl().newBuilder().apply {
-        addPathSegment("_next")
-        addPathSegment("image")
-    }.build().toString() + "?url=$dataUrl"
+    private fun imageApiUrlBuilder() = cdn.toHttpUrl().newBuilder().apply {
+        addPathSegment("uploads")
+        addPathSegment("images")
+        addPathSegment("series")
+    }
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]:
```suggestion
    private fun imageApiUrlBuilder() = "$cdn/uploads/images/series".toHttpUrl().newBuilder()
```

Improves grep-ability, and works since all segments are static.

**Review by vetleledaal — DISMISSED** [review]

**Review by stevenyomi — APPROVED** [review]
