### PR TITLE
Toomics: Fix content loading

### LINKED ISSUE #6357: toomics.com
### Source name

Toomics

### Source language

Multiple

### Source link

https://toomics.com

### Other details

This is what it says in the repo, but if you open the web and reload the page, it says no results found, the page is empty, it doesn't work, it seems to be pulling from https://globel.toomics.com/, but the site works, the repo doesn't work. 

Screenshot_2024-11-28-04-09-37-76_423fe07c33ed17f15a4e92e5e3a15972
Screenshot_2024-11-28-04-05-18-19_423fe07c33ed17f15a4e92e5e3a15972
Screenshot_2024-11-28-04-05-03-22_423fe07c33ed17f15a4e92e5e3a15972
Screenshot_2024-11-28-04-05-25-78_423fe07c33ed17f15a4e92e5e3a15972
Screenshot_2024-11-28-04-05-07-45_423fe07c33ed17f15a4e92e5e3a15972
Screenshot_2024-11-28-04-09-30-52_423fe07c33ed17f15a4e92e5e3a15972
Screenshot_2024-11-28-04-04-52-62_423fe07c33ed17f15a4e92e5e3a15972

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #6357

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt [hunk 1]
```diff
@@ -32,87 +42,105 @@ abstract class ToomicsGlobal(
...
 
     override fun popularMangaFromElement(element: Element): SManga = SManga.create().apply {
         title = element.select("h4[class$=title]").first()!!.ownText()
-        // sometimes href contains "/ab/on" at the end and redirects to a chapter instead of manga
-        setUrlWithoutDomain(element.select("a").attr("href").removeSuffix("/ab/on"))
-        thumbnail_url = element.select("img").attr("src")
+        setUrlWithoutDomain(element.absUrl("href"))
+        thumbnail_url = element.selectFirst("img")?.let { img ->
+            when {
+                img.hasAttr("data-original") -> img.attr("data-original")
```
Comment (vetleledaal) [inline src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt:67]: Use absUrl

File: src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt [hunk 2]
```diff
@@ -32,87 +42,105 @@ abstract class ToomicsGlobal(
...
+        title = element.selectFirst("strong")!!.text().trim()
+        thumbnail_url = element.selectFirst("img")?.absUrl("src")
+
+        element.selectFirst("a.relative")!!.attr("href").let { href ->
+            val toonId = href
+                .substringAfter("Base.setFamilyMode('N', '")
+                .substringBefore("'")
+                .let { url -> URLDecoder.decode(url, "UTF-8") }
+                .substringAfter("?toon=")
+                .substringBefore("&")
```
Comment (vetleledaal) [inline src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt]: Use HttpUrl?

File: src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt [hunk 3]
```diff
@@ -32,87 +42,105 @@ abstract class ToomicsGlobal(
...
     override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
-        val header = document.select("#glo_contents header.ep-cover_ch div.title_content")
+        val header = document.selectFirst("#glo_contents section.relative:has(img[src*=thumb])")!!
 
-        title = header.select("h1").text()
-        author = header.select("p.type_box span.writer").text()
-        artist = header.select("p.type_box span.writer").text()
-        genre = header.select("p.type_box span.type").text().replace("/", ",")
-        description = header.select("h2").text()
+        title = header.select("h2").text()
```
Comment (vetleledaal) [inline src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt]: Use selectFirst

File: src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt [hunk 4]
```diff
@@ -32,87 +42,105 @@ abstract class ToomicsGlobal(
...
+        header.selectFirst(".mb-0.text-xs.font-normal")?.let {
+            val info = it.text().trim().split("|")
```
Comment (vetleledaal) [inline src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt]: .text() is already trimmed.

File: src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt [hunk 5]
```diff
@@ -32,87 +42,105 @@ abstract class ToomicsGlobal(
...
+            artist = info.first()
+            author = info.last()
+        }
+
+        genre = header.select("dt:contains(genres) + dd").text().replace("/", ",")
+        description = header.select(".break-noraml.text-xs").text()
```
Comment (vetleledaal) [inline src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt]: selectFirst?

File: src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt [hunk 6]
```diff
@@ -155,6 +185,40 @@ abstract class ToomicsGlobal(
         return GET(page.imageUrl!!, newHeaders)
     }
 
+    // ================================== Interceptors =================================
+
+    private fun ageVerificationWarning(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val response = chain.proceed(request)
+        if (response.request.url.pathSegments.any { it.equals("age_verification", true) }) {
+            throw IOException("Use WebView for age verification")
```
Comment (vetleledaal) [inline src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt]: What is the age verification? Cookies? Js challenge? Should automate it if it's not a captcha / login thing.

**Review by vetleledaal — CHANGES_REQUESTED** [review]

File: src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt [hunk 7]
```diff
@@ -42,77 +52,92 @@ abstract class ToomicsGlobal(
...
-        val rbody = "toonData=$query&offset=0&limit=20".toRequestBody(null)
-
-        return POST("$baseUrl/$siteLang/webtoon/ajax_search", newHeaders, rbody)
+    override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
+        val response = client.newCall(searchMangaRequest(page, query, filters)).execute()
+        val searchDto = json.decodeFromStream<SearchDto>(response.body.byteStream())
+        val document = Jsoup.parseBodyFragment(searchDto.content.clearHtml(), baseUrl)
+        val mangas = document.select(searchMangaSelector()).map(::searchMangaFromElement)
+        return Observable.just(MangasPage(mangas, false))
     }
```
Comment (AwkwardPeak7) [inline src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt]: why override fetch?

Comment (choppeh) [reply src/all/toomics/src/eu/kanade/tachiyomi/extension/all/toomics/ToomicsGlobal.kt]: I overrode the wrong method, actually, I should override the searchMangaParse

**Review by AwkwardPeak7 — APPROVED** [review]

**Review by vetleledaal — APPROVED** [review]
