### PR TITLE
MangaHub (multisrc) - Fix "API Limit Exceeded"

### LINKED ISSUE #6573: API limit exceeded
### Source information

MangaHub 1.4.38

### Source language

English 

### Steps to reproduce

When I open a manga to read it it shows a message like "API limit exceeded"

### Expected behavior

I should be able to read the manga

### Actual behavior

It's showing API limit exceeded and closes the manga

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #6605: 1manga.co: API rate limit excessed error
### Source information

1manga.co (EN) 

### Source language

English 

### Steps to reproduce

1 open the source 
2 searched for no game no life manga
3 open it till chapter 7

### Expected behavior

open other chapters or download them

### Actual behavior

Screenshot_20241214_113417_Mihon

### Mihon/Tachiyomi version

0.17.1

### Android version

android 13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by JakeeLuwi**
This PR will fix around 11 extensions.
Closes #6573
Closes #6605

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt [hunk 1]
```diff
@@ -27,6 +27,7 @@ import okhttp3.OkHttpClient
 import okhttp3.Request
 import okhttp3.RequestBody.Companion.toRequestBody
 import okhttp3.Response
+import okio.IOException
```
Comment (vetleledaal) [inline lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: Why not `java.io.IOException`?

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt [hunk 2]
```diff
@@ -104,9 +105,32 @@ abstract class MangaHub(
             baseUrl.toHttpUrl()
         }
 
-        // Clear key cookie
-        val cookie = Cookie.parse(url, "mhub_access=; Max-Age=0; Path=/")!!
-        client.cookieJar.saveFromResponse(url, listOf(cookie))
+        val regex = Regex("mhub_access=([^;]+)")
```
Comment (vetleledaal) [inline lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: Extract regex to avoid recompilation.

Comment (AwkwardPeak7) [inline lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: put regex in class

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt [hunk 3]
```diff
@@ -104,9 +105,32 @@ abstract class MangaHub(
...
+                }
+
+                break; // Break out of loop since we got an allegedly valid API key
+            } catch (_: IOException) {
+                throw IOException("An error occurred while obtaining a new API key") // Show error
+            }
+        }
 
         // Set required cookie (for cache busting?)
         val recently = buildJsonObject {
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: shouldn't this logic be above?

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt [hunk 4]
```diff
@@ -104,9 +105,32 @@ abstract class MangaHub(
...
+
+            try {
+                val response = client.newCall(GET("$url$query", headers)).execute()
+                val returnedKey = response.headers["set-cookie"]?.let { regex.find(it)?.groupValues?.get(1) }
+
+                if (returnedKey == oldKey) {
+                    continue // Site gave an old key so we try again
+                }
+
+                break; // Break out of loop since we got an allegedly valid API key
```
Comment (vetleledaal) [inline lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: I think this can be simplified somewhat:
```suggestion
                // Break if we got an allegedly valid API key, otherwise try again
                if (returnedKey != oldKey) break
```

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt (hunk 3 above)
Comment (JakeeLuwi) [reply lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: By above, what do you mean?

Comment (AwkwardPeak7) [reply lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: `recently` cookie logic above your refresh logic?

**Comment by AwkwardPeak7** [comment]
also  #6605

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt (hunk 3 above)
Comment (JakeeLuwi) [reply lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: From my testing, the placement doesn't really matter as long as the block executes the `recently` logic since it isn't needed when refreshing API keys. ~~Was planning to actually remove it but unsure if this would affect the `graphql` api in some way.~~ Turns out it isn't needed at all.

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt (hunk 1 above)
Comment (JakeeLuwi) [reply lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt]: Auto imported by IDE, will change on next commit.

**Review by vetleledaal — DISMISSED** [review]

File: lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt [hunk 5]
```diff
@@ -104,32 +102,27 @@ abstract class MangaHub(
...
+            val cookie = Cookie.parse(url, "mhub_access=; Max-Age=0; Path=/")!!
+            client.cookieJar.saveFromResponse(url, listOf(cookie))
 
-        val request = GET("$url?reloadKey=1", headers)
-        client.newCall(request).execute()
+            // We try requesting again with param if the first one fails
+            val query = if (i == 2) "?reloadKey=1" else ""
+
+            try {
+                val response = client.newCall(GET("$url$query", headers)).execute()
```
Comment (AwkwardPeak7) [inline lib-multisrc/mangahub/src/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt:118]:
```suggestion
                val response = client.newCall(GET("$url$query", headers)).execute().close()
```
close the response

**Review by AwkwardPeak7 — DISMISSED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
