### PR TITLE
Removed FlameComics Multisrc/Added individuall solution

### LINKED ISSUE #6230: flame comic back
### Source information

flame comic 1.4.34

### Source language

English 

### Steps to reproduce

flame comic is back as per their recent announcement 
Screenshot_20241123_090551
but extension is still down despite the website is on
Screenshot_20241123_090355
so hope you can fix the extension error soon .

### Expected behavior

extention showing an 404 error while website is up 
Screenshot_20241123_093358

### Actual behavior

it should be up with both extensions and webview too but it's down on extension .

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

Screenshot_20241123_090551
Screenshot_20241123_090551
Screenshot_20241123_093358

Hope it get fix soon .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Creepler13**
I removed the Multisrc since they changed their website and it seemed custom

The only problem that i have is that the version is now  lower than before, because its no longer using a Multisrc

Would close #6230

Checklist:

- [?] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [?] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

### CODE REVIEW

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 1]
```diff
@@ -4,62 +4,166 @@ import android.graphics.Bitmap
...
+class FlameComics : ParsedHttpSource() {
 
     override val client = super.client.newBuilder()
         .rateLimit(2, 7)
         .addInterceptor(::composedImageIntercept)
         .build()
 
-    override val pageSelector = "div#readerarea img:not(noscript img)[class*=wp-image]"
+    // Flame Scans -> Flame Comics
+    override val id = 6350607071566689772
```
Comment (bapeey) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: if old URLs aren't compatible with the new version remove this and bump `versionId` to force the migration

File: src/en/flamecomics/build.gradle [hunk 2]
```diff
@@ -1,9 +1,7 @@
 ext {
     extName = 'Flame Comics'
     extClass = '.FlameComics'
-    themePkg = 'mangathemesia'
-    baseUrl = 'https://flamecomics.xyz'
-    overrideVersionCode = 4
+    extVersionCode = 5
```
Comment (vetleledaal) [inline src/en/flamecomics/build.gradle]:
```suggestion
    extVersionCode = 35
```

This will prompt existing users to update the extension. The value is +1 from the previous version:
```
baseVersionCode + overrideVersionCode =
30 + 4 = 34
// ext-lib is 1.4, so extension version is 1.4.34
```

You could also find the current version from https://keiyoushi.github.io/extensions/

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 3]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+    override val name = "Flame Comics"
+    private val host = "flamecomics.xyz"
+    override val baseUrl = "https://$host"
+    override val lang = "en"
+    override val supportsLatest = true
+    override val versionId: Int = 2
 
-    // Flame Scans -> Flame Comics
-    override val id = 6350607071566689772
+    private val cdn = "https:cdn.$host"
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Missing `//`

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 4]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+    private val removeSpecialCharsregex = Regex("[^A-Za-z0-9 ]")
 
-    // Split Image Fixer Start
-    private val composedSelector: String = "#readerarea div.figure_container div.composed_figure"
+    private fun getRealUrl(string: String?): String {
+        if (string == null) return ""
+        var url = URLDecoder.decode(string.substringAfter("url="), "utf8")
+        url = url.substringBefore("?")
+        url = url.substringBefore("&")
+        return url
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: `String.toHttpUrlOrNull()` could be useful here.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 5]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+        if (lastPage < 0) lastPage = 0
+        return MangasPage(manga.subList(page * 20, lastPage), lastPage < manga.size)
+    }
+
+    override fun searchMangaNextPageSelector(): String? = null
+    override fun popularMangaNextPageSelector(): String? = null
+    override fun latestUpdatesNextPageSelector(): String? = null
+
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request =
+        GET("$baseUrl/browse?search=$query&page=$page")
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Use `String.toHttp().newBuilder()`, that way you can properly escape queries.

Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Missing `headers` passed to `GET`.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 6]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+    override fun popularMangaRequest(page: Int): Request = GET(baseUrl, headers)
+    override fun latestUpdatesRequest(page: Int): Request = GET(baseUrl, headers)
+
+    override fun searchMangaSelector(): String = throw UnsupportedOperationException()
+    override fun popularMangaSelector(): String = "div[class^=SeriesCard_imageContainer] img"
+    override fun latestUpdatesSelector(): String =
+        "div[class^=SeriesCard_chapterImageContainer] img"
+
+    override fun popularMangaFromElement(element: Element): SManga = SManga.create().apply {
+        title = element.attr("abs:alt").substringAfter("$baseUrl/").replaceFirst("/", "")
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Using `abs:` for the `alt` attribute seems wrong.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 7]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+        val url = element.attr("abs:src")
+        thumbnail_url = getRealUrl(url).substringBefore("&")
+        setUrlWithoutDomain(getRealUrl(url).substringBefore("/thumb"))
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Use `HttpUrl`

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 8]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+
+    override fun latestUpdatesFromElement(element: Element): SManga =
+        popularMangaFromElement(element)
+
+    override fun searchMangaFromElement(element: Element): SManga = popularMangaFromElement(element)
+
+    override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
+        val seriesData = getJsonData<PageData>(document)?.props?.pageProps?.series
+
+        title = seriesData?.title + ""
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Should only set title if it's available.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 9]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+
+        thumbnail_url = "$cdn/series/${seriesData?.series_id}/${seriesData?.cover}"
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Since `seriesData` might be null you should handle this differently.

```suggestion
        seriesData?.let {
            thumbnail_url = "$cdn/series/${it.series_id}/${it.cover}"
        }
```

(although you can wrap more of the surrounding code into this `let` block, maybe use a different name than `it` in that case)

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 10]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+
+        description = seriesData?.description
+
+        when (seriesData?.status) {
+            "Ongoing" -> status = SManga.ONGOING
+            "Dropped" -> status = SManga.CANCELLED
+            "Hiatus" -> status = SManga.ON_HIATUS
+            "Completed" -> status = SManga.COMPLETED
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Make case insensitive.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 11]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+                name = n
             }
+        }
+    }
+
+    override fun pageListParse(document: Document): List<Page> {
+        return document.select("div[class$=mantine-Stack-root] img").mapIndexed { idx, img ->
+            var url = img.attr("abs:src")
+            url = URLDecoder.decode(url.substringAfter("url="), "utf8")
+            Page(idx, imageUrl = url.substringBefore("?"))
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Use `HttpUrl`

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 12]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+        val doc = response.asJsoup()
+        val jsonData = doc.getElementById("__NEXT_DATA__")?.data() ?: return listOf<SChapter>()
+        val pageData = json.decodeFromString<PageData>(jsonData)
+        return pageData.props.pageProps.chapters.map { chapter ->
+            SChapter.create().apply {
+                setUrlWithoutDomain("/series/${pageData.props.pageProps.series.series_id}/${chapter.token}")
+                date_upload = chapter.release_date * 1000
+                var n = "Chapter ${chapter.chapter.toInt()} - "
+                if (chapter.title != null) n += chapter.title
+                name = n
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]:
```suggestion
                name = buildString {
                    append("Chapter ${chapter.chapter.toInt()}")
                    chapter.title?.let { append(" - $it") }
                }
```

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 13]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+        setUrlWithoutDomain(getRealUrl(url).substringBefore("/thumb"))
+    }
+
+    override fun latestUpdatesFromElement(element: Element): SManga =
+        popularMangaFromElement(element)
+
+    override fun searchMangaFromElement(element: Element): SManga = popularMangaFromElement(element)
+
+    override fun mangaDetailsParse(document: Document): SManga = SManga.create().apply {
+        val seriesData = getJsonData<PageData>(document)?.props?.pageProps?.series
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: You should return early if it doesn't find `seriesData`, as all the fields rely on this being set. (or see other comment for `thumbnail_url`)

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 14]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+            "Completed" -> status = SManga.COMPLETED
+            else -> SManga.UNKNOWN
+        }
+
+        author = seriesData?.author
+    }
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val doc = response.asJsoup()
+        val jsonData = doc.getElementById("__NEXT_DATA__")?.data() ?: return listOf<SChapter>()
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Can `.getJsonData()` be reused here?

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 15]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
+        val pageData = json.decodeFromString<PageData>(jsonData)
+        return pageData.props.pageProps.chapters.map { chapter ->
+            SChapter.create().apply {
+                setUrlWithoutDomain("/series/${pageData.props.pageProps.series.series_id}/${chapter.token}")
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: If `token` is regularly updated it will cause entries to be marked as unread, at least when it can't detect the chapter number.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 16]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
-class FlameComics : MangaThemesia(
-    "Flame Comics",
-    "https://flamecomics.xyz",
-    "en",
-    mangaUrlDirectory = "/series",
-) {
+class FlameComics : ParsedHttpSource() {
+    override val name = "Flame Comics"
+    private val host = "flamecomics.xyz"
+    override val baseUrl = "https://$host"
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: It should be fine to repeat the `host` here and in `cdn`. Semantically you're saying that the CDN must be under the main domain, which isn't always the case.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 17]
```diff
@@ -4,62 +4,158 @@ import android.graphics.Bitmap
...
-            .select(composedSelector)
-            .firstOrNull() != null
+    override fun chapterFromElement(element: Element): SChapter =
+        throw UnsupportedOperationException()
+
+    override fun chapterListSelector(): String = throw UnsupportedOperationException()
+    override fun imageUrlParse(document: Document): String = ""
+
+    override fun searchMangaParse(response: Response): MangasPage {
+        val query = removeSpecialCharsregex.replace(response.request.url.queryParameter("search").toString().lowercase(), "")
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Are you removing special characters since you're not using `HttpUrl` elsewhere, or because the site doesn't support it?

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/JsonClasses.kt
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/JsonClasses.kt:1]: Should be named something like `FlameComicsDto.kt`

**Review by vetleledaal — CHANGES_REQUESTED** [review]

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt (hunk 17 above)
Comment (Creepler13) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: I had a problem while Migrating, because the apostrophe in the old title and in the new were different.
And its easier to search, because it will find the manga since it wont matter if you add special chars or not

**Comment by Creepler13** [comment]
I also changed to HttpSource and only use the JSON data, because there are only 12 popular entries and now i can simply sort all by views

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 18]
```diff
@@ -4,62 +4,172 @@ import android.graphics.Bitmap
...
+            "completed" -> SManga.COMPLETED
+            else -> SManga.UNKNOWN
+        }
+    }
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val mangaPageData = getJsonData<MangaPageData>(response.asJsoup()) ?: return listOf()
+        return mangaPageData.props.pageProps.chapters.map { chapter ->
+            SChapter.create().apply {
+                setUrlWithoutDomain(
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt:216]: URL should be in format:
```kt
setUrlWithoutDomain("/series/$seriesId/$token")
```
Sending `chapterNum` is in any case a bad idea, as the remote can use it to detect keiyoushi users.

This is of course assuming that the token will be static for that chapter.

---

For the actual resource you request it would be (with `HttpUrl` for proper escaping?):
```kt
val x = "/_next/data/$buildId/series/$seriesId.json?id=$seriesId"
val x = "/_next/data/$buildId/series/$seriesId/$token.json?id=$seriesId&token=$token"
```

You don't want to use this format (`_next/...` + `getMangaUrl()` + `getChapterUrl()`) saved in in the internal database, as that would move the entry/chapter on each new `buildId`.

You can check the "Hachi" extension on how to get the `buildId` for NextJS, although I may have over-complicated it a bit.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComicsDto.kt [hunk 19]
```diff
@@ -0,0 +1,90 @@
...
+    @Serializable(with = keystoListSerializer::class)
+    val images: List<Page>,
+)
+
+@Serializable
+class Page(
+    val name: String,
+)
+
+class keystoListSerializer : KSerializer<List<Page>> {
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComicsDto.kt]: What is `keysto`?

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt (hunk 18 above)
Comment (vetleledaal) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt:216]: Regex you can use to get seriesid/token from user-facing URLs:
```kt
private val patternMangaUrl = """/series/(?<seriesId>[0-9]+)(?:/(?<token>[0-9A-Za-z]+))?""".toRegex()
```

Comment (Creepler13) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt:216]: The chapters appear to each have an `id`. I could try to use them since they seem more permanent than the tokens or would that have the same problem as with `chapterNum`?

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComicsDto.kt (hunk 19 above)
Comment (Creepler13) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComicsDto.kt]: It just means keys to List, because the Images are saved in a wierd format in the json

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt (hunk 18 above)
Comment (vetleledaal) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt:216]: I don't see `chapterNum` as unique enough. You have special chapters, multiple groups, etc. For `tokens`- I think it should be safe to rely on since the public URL is shown with this token, and people might bookmark it. Meaning they should maintain compatibility with it in the future.

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComicsDto.kt (hunk 19 above)
Comment (vetleledaal) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComicsDto.kt]: Then, following camelCase, you should use:
```suggestion
class keysToListSerializer : KSerializer<List<Page>> {
```

**Comment by Creepler13** [comment]
I implemented the way hachi does it

**Comment by vetleledaal** [comment]
The chapter URL saved in the database is wrong:
image
This will cause issues when `buildId` updates.

---

For comparison, Hachi saves the 'friendly' URL:
image

**Comment by Creepler13** [comment]
This should fix it. I dont know to to look

**Comment by vetleledaal** [comment]
> This should fix it. I dont know to to look

If your host app (Mihon) is a debug build, you can use 'App Inspection' in Android Studio. You can search for it with Ctrl + Shift + A.

**Review by vetleledaal — APPROVED** [review]
