### PR TITLE
SussyToons: Fix loading pages

### LINKED ISSUE #7048: Sussy Toon: field 'resultados' is required error
### Source information

Sussytoons 1.4.45

### Source language

Portuguese

### Steps to reproduce

the chapters should open, but this error appears in all the mangas
Screenshot_20250107-184044_Mihon

### Expected behavior

the chapters should open

### Actual behavior

No chapters are opening, but the website is working normally

### Mihon/Tachiyomi version

0.17.1

### Android version

12

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #7090: Sussy's domain change
### Source information

Sussy Scan 1.4.45

### Source language

Português Brasil - PT-BR

### Source new URL

https://www.sussyscan.com/

### Other details

Screenshot_2025-01-09-16-51-06-016_com android chrome

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #7048
Closes #7090

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/sussyscan/src/eu/kanade/tachiyomi/extension/pt/sussyscan/SussyToons.kt [hunk 1]
```diff
@@ -331,9 +390,24 @@ class SussyToons : HttpSource() {
...
     companion object {
-        const val CDN_URL = "https://usc1.contabostorage.com/23b45111d96c42c18a678c1d8cba7123:cdn"
+        const val CDN_URL = "https://cdn.sussytoons.site"
         const val OLDI_URL = "https://oldi.sussytoons.site"
+        const val mangaPagePrefix = "mangaPage:"
+        const val chapterPagePrefix = "chapterPage:"
+        const val pageImagePrefix = "pageImage:"
+
+        val chapterUrlRegex = """push\("(?<chapterUrl>[^"]*capitulo[^"]*)/?"\.concat""".toRegex()
+        val pageUrlRegex = """\.get\("(?<pageUrl>[^"]*capitulo[^(/?")]*)/?"\.concat""".toRegex()
```
Comment (vetleledaal) [inline src/pt/sussyscan/src/eu/kanade/tachiyomi/extension/pt/sussyscan/SussyToons.kt]: Avoid using named capture groups, they are not supported by the current minSDK (21).

**Review by vetleledaal — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]

**Comment by BlackMember08** [comment]
Muito obrigado mano pelo seu trabalho que Deus te abençoe :)

**Comment by npkiler** [comment]
meu consagrado te agradeço muito msm
