### PR TITLE
Fix Realm Oasis

### LINKED ISSUE #7606: Realm Oasis: Popular and Latest tabs broken
### Source information

realme oasis 1.4.37

### Source language

English 

### Steps to reproduce

The Realm Oasis extension in the Mihon app is currently broken. 

we can still read manhwa saved in our library .

But the extension itself is not working—when we 

Image

Image

Image

try to open it, you get a 404 error (page not found).

Webview is also broken, so we can't search for new titles or browse the extension.

### Expected behavior

extention should be working and title should be showing and we should have access to all in webview too but it's not working 

### Actual behavior

we can still read manhwa saved in our library .

But the extension itself is not working—when we 
try to open it, you get a 404 error (page not found).

Webview is also broken, so we can't search for new titles or browse the extension.

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 14 

### Other details

we can still read manhwa saved in our library .

But the extension itself is not working—when we 
try to open it, you get a 404 error (page not found).

Webview is also broken, so we can't search for new titles or browse the extension.

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Xyndra**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [?] Have explicitly kept the `id` if a source's name or language were changed: I can't see id
- [x] Have tested the modifications by compiling and running the extension through Android Studio: even tested that bookmarks stay
- [?] Have removed `web_hi_res_512.png` when adding a new extension: hopefully

What I did:
 - "$baseUrl/Index/live_search" -> "$baseUrl/search" (because of Creepler13, but seems to work)
 - add API header "Referer" - seems to have been the main issue
 - move package from old name rizzcomics

### CODE REVIEW

**Comment by Xyndra** [comment]
Closes #7606

**Comment by Xyndra** [comment]
seems like I also changed some of the filters capitalization to fit the website, but after some testing I am now seeing that the API doesn't care about capitalization

File: src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt [hunk 1]
```diff
@@ -1,4 +1,4 @@
-package eu.kanade.tachiyomi.extension.en.rizzcomic
+package eu.kanade.tachiyomi.extension.en.realmoasis
```
Comment (bapeey) [inline src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: Don't change package name or users will not get the update

Comment (Xyndra) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: but then is it supposed to stay as rizzcomic internally forever? that seems a bit weird

Comment (bapeey) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: It is what it is 🤷‍♂️

Comment (Creepler13) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: I think you can take the id that is generated based of the name and make it permanent to allow these changes

Comment (Creepler13) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: it should be 2800985175674503515

Comment (bapeey) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: That prevent users from having to migrate their mangas, but they still won't receive the update and will need to install the apk again. I don't see any important reason to do that

Comment (Xyndra) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: Hi @Creepler13, I am new to this repository so I don't really know what you mean by that. Could you potentially help me figure out the steps needed to do this, if I can do anything in the first place

Comment (Creepler13) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: > That prevent users from having to migrate their mangas, but they still won't receive the update and will need to install the apk again. I don't see any important reason to do that

Ah i thought the id was also for that. @Xyndra  iam also not that experienced as you see

Comment (Xyndra) [reply src/en/realmoasis/src/eu/kanade/tachiyomi/extension/en/realmoasis/RealmOasis.kt]: Okay, I reverted the package change. Could someone please review the other changes?

File: src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt [hunk 2]
```diff
@@ -54,7 +54,7 @@ class RealmOasis : MangaThemesia(
     private val apiHeaders by lazy {
         headersBuilder()
             .set("X-Requested-With", "XMLHttpRequest")
-            .set("X-API-Request", "1")
+            .set("Referer", "https://realmoasis.com/comics")
             .build()
```
Comment (vetleledaal) [inline src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:59]: BaseUrl + mangaUrlDirectory?

Comment (Xyndra) [reply src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:59]: oops, will fix

File: src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt [hunk 3]
```diff
@@ -54,7 +54,7 @@ class RealmOasis : MangaThemesia(
     private val apiHeaders by lazy {
         headersBuilder()
             .set("X-Requested-With", "XMLHttpRequest")
-            .set("X-API-Request", "1")
+            .set("Referer", "$baseUrl$mangaUrlDirectory")
```
Comment (AwkwardPeak7) [inline src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:58]: need to adjust the interceptor for `X-Requested-With` handling too

Comment (Xyndra) [reply src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:58]: Why would you need to adjust anything? It seems to work fine

Comment (Xyndra) [reply src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:58]: The webpage also has the XMLHttpRequest thing set

Comment (AwkwardPeak7) [reply src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:58]: the interceptor removes the header unless it is the api request, you need to adjust that logic as currently it checks `X-API-Request` which you removed

Comment (AwkwardPeak7) [reply src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:58]: just don't remove `X-API-Request`

Comment (Xyndra) [reply src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:58]: ohh, I didn't know there was an interceptor in between the code and page

Comment (Xyndra) [reply src/en/rizzcomic/src/eu/kanade/tachiyomi/extension/en/rizzcomic/RealmOasis.kt:58]: okay, fixed it

**Review by AwkwardPeak7 — APPROVED** [review]

**Comment by Xyndra** [comment]
why is it not merging?

**Comment by AwkwardPeak7** [comment]
patience :)

**Comment by Xyndra** [comment]
ah, ok
