### PR TITLE
DragonTranslation.net (ES): Migrate to HttpSource

### LINKED ISSUE #7618: DragonTranslation.net (ES): NullPointerException
### Source information

DragonTranslation.net 1.4.39

### Source language

Spanish

### Steps to reproduce

1) Enter the extension 
2) An error appears (null....)

Image

### Expected behavior

Manhwas should appear

### Actual behavior

Manhwas don't load and an error appears, a few hours ago this did not happen
Webview works, I don't know if it's a URL change since I don't remember the previous one but just in case I'll leave the current link: https://dragontranslation.net/ 

Image

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 15

### Other details

The error also appears when updating the library

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by dngonz**
Closes #7618

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by bapeey** [comment]
can you also change it to `ParsedHttpSource`? site it's no longer using Madara

File: src/es/dragontranslationnet/src/eu/kanade/tachiyomi/extension/es/dragontranslationnet/DragonTranslationNet.kt [hunk 1]
```diff
@@ -87,4 +121,18 @@ class DragonTranslationNet : Madara("DragonTranslation.net", "https://dragontran
             )
         }
     }
+
+    override fun imageUrlParse(document: Document): String = throw UnsupportedOperationException()
+
+    // Filters
+
+    override fun getFilterList() = FilterList(emptyList())
```
Comment (AwkwardPeak7) [inline src/es/dragontranslationnet/src/eu/kanade/tachiyomi/extension/es/dragontranslationnet/DragonTranslationNet.kt]: no need

File: src/es/dragontranslationnet/src/eu/kanade/tachiyomi/extension/es/dragontranslationnet/DragonTranslationNet.kt [hunk 2]
```diff
@@ -1,83 +1,117 @@
...
+        setUrlWithoutDomain(element.selectFirst("a.lanzador")!!.attr("href"))
+        thumbnail_url = element.selectFirst("img")?.attr("abs:src")
+        title = element.selectFirst("h2")!!.text()
     }
 
+    // Latest
+
+    override fun latestUpdatesSelector(): String = throw UnsupportedOperationException()
+
+    override fun latestUpdatesNextPageSelector(): String = throw UnsupportedOperationException()
```
Comment (AwkwardPeak7) [inline src/es/dragontranslationnet/src/eu/kanade/tachiyomi/extension/es/dragontranslationnet/DragonTranslationNet.kt]: consider using `HttpSource` directly since you aren't really using parsed methods that much

File: src/es/dragontranslationnet/src/eu/kanade/tachiyomi/extension/es/dragontranslationnet/DragonTranslationNet.kt [hunk 3]
```diff
@@ -1,84 +1,103 @@
...
-            select(chapterUrlSelector).first()?.let { urlElement ->
-                chapter.url = urlElement.attr("abs:href")
-                chapter.name = urlElement.select("p.chapter-manhwa-title").text()
-                chapter.date_upload = parseChapterDate(select("span.chapter-release-date").text())
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        return document.select("ul.list-group a").map {
+            SChapter.create().apply {
+                name = it.selectFirst("li")!!.text()
+                setUrlWithoutDomain(it.attr("href"))
```
Comment (vetleledaal) [inline src/es/dragontranslationnet/src/eu/kanade/tachiyomi/extension/es/dragontranslationnet/DragonTranslationNet.kt]:
```suggestion
                setUrlWithoutDomain(it.absUrl("href"))
```
```suggestion
                setUrlWithoutDomain(it.attr("abs:href"))
```

**Review by vetleledaal — APPROVED** [review]
