### PR TITLE
Holonometria: update URL and other fixes

### LINKED ISSUE #8669: Holonometria URL change
### Source information

HOLONOMETRIA

### Source language

English, Japanese, Indonesian

### Source new URL

https://holoearth.com/en/alt/holonometria/manga/

### Other details

Extension's search and every manga in library points to main page of the site (holoearth.com/alt/) in Webview.

JP: https://holoearth.com/alt/holonometria/manga/
ID: https://holoearth.com/id/alt/holonometria/manga/

Image
Image

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by scb261**
Note: I do not take credit for this code. Someone else fixed it, but they didn't want it on their GH profile.

Closes #8669

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/holonometria/src/eu/kanade/tachiyomi/extension/all/holonometria/Holonometria.kt [hunk 1]
```diff
@@ -22,31 +21,23 @@ class Holonometria(
...
 
-    override val baseUrl = "https://alt.hololive.tv"
+    override val baseUrl = "https://holoearth.com"
 
     override val supportsLatest = false
 
-    override val client = network.cloudflareClient.newBuilder()
-        .readTimeout(60, TimeUnit.SECONDS)
-        .build()
+    override fun popularMangaRequest(page: Int) = GET("$baseUrl/${langPath}alt/holonometria/manga/")
```
Comment (AwkwardPeak7) [inline src/all/holonometria/src/eu/kanade/tachiyomi/extension/all/holonometria/Holonometria.kt]:
```suggestion
    override fun popularMangaRequest(page: Int) = GET("$baseUrl/${langPath}alt/holonometria/manga/", headers)
```
pass headers to `GET` here and elsewhere

File: src/all/holonometria/src/eu/kanade/tachiyomi/extension/all/holonometria/Holonometria.kt [hunk 2]
```diff
@@ -80,45 +71,17 @@ class Holonometria(
...
+    override fun chapterListParse(response: Response): List<SChapter> =
+        super.chapterListParse(response).reversed()
 
     override fun chapterFromElement(element: Element) = SChapter.create().apply {
         setUrlWithoutDomain(element.selectFirst("a")!!.attr("href"))
-        name = element.select(".ttl").text()
-        date_upload = element.selectFirst(".data--date")?.text().parseDate()
-        scanlator = element.selectFirst(".data--category")?.text()
+        name = element.select(".manga-detail__list-title").text()
+        date_upload = element.selectFirst(".manga-detail__list-date")?.text()?.trim().parseDate()
```
Comment (AwkwardPeak7) [inline src/all/holonometria/src/eu/kanade/tachiyomi/extension/all/holonometria/Holonometria.kt]:
```suggestion
        date_upload = dateFormat.tryParse(element.selectFirst(".manga-detail__list-date")?.text())
```
need to import, and remove the old `parseDate` function

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by AwkwardPeak7** [comment]
also link #8669 in your pr description

**Comment by scb261** [comment]
Done. ~~Didn't realize how bad GH search is, I only searched for "holo', and it didn't show anything.~~

**Review by AwkwardPeak7 — APPROVED** [review]
