### PR TITLE
Shinigami: Rewrite for new site

### LINKED ISSUE #7867: Shinigami new
### Source information

Shinigami 1.4.70

### Source language

Indonesia

### Source new URL

https://app.shinigami.asia/

### Other details

For now, the old website can still be accessed, but it is likely that in the next few days it will Migration to the new website. 
**"Edit" its broken now**
I don't know whether to categorize this as a new extension or a url change because the appearance has changed quite drastically, such as the feature that requires you to log in to access chapters.

### Acknowledgements

- [x] I have updated all installed extensions.
- [x] I have opened WebView and checked that the source URL has not changed yet.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Riztard**
closes #7867 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 1]
```diff
@@ -83,70 +64,213 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+    }
+
+    private inline fun <reified T> Response.parseAs(): T = use {
+        json.decodeFromString(it.body.string())
+    }
+
+    private fun String.toDate(): Long {
+        return runCatching { DATE_FORMATTER.parse(this)?.time }.getOrNull()
+            ?: 0
+    }
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: use `parseAs` and `tryParse` (for date) from utils

```kt
import keiyoushi.utils.parseAs
import keiyoushi.utils.tryParse
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 2]
```diff
@@ -2,73 +2,54 @@ package eu.kanade.tachiyomi.extension.id.shinigami
...
 
-    override fun headersBuilder() = super.headersBuilder().apply {
-        add("Sec-Fetch-Dest", "document")
-        add("Sec-Fetch-Mode", "navigate")
-        add("Sec-Fetch-Site", "same-origin")
-        add("Upgrade-Insecure-Requests", "1")
-        add("X-Requested-With", randomString((1..20).random())) // added for webview, and removed in interceptor for normal use
+    private val preferences: SharedPreferences by lazy {
+        Injekt.get<Application>().getSharedPreferences("source_$id", 0x0000)
     }
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
    private val preferences: SharedPreferences by getPreferencesLazy()
```
need to import

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 3]
```diff
@@ -83,70 +64,213 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+
+        val hasNextPage = rootObject.meta.page < rootObject.meta.totalPage
+
+        return MangasPage(projectList, hasNextPage)
+    }
+
+    private fun popularMangaFromObject(obj: ShinigamiBrowseDataDto): SManga = SManga.create().apply {
+        title = obj.title.toString()
+        thumbnail_url = obj.thumbnail
+        url = "$apiUrl/$API_BASE_PATH/manga/detail/" + obj.mangaId
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: save relative urls, or just save the id only

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 4]
```diff
@@ -2,73 +2,54 @@ package eu.kanade.tachiyomi.extension.id.shinigami
...
+import java.util.Locale
 
-class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), ConfigurableSource {
+class Shinigami : ConfigurableSource, HttpSource() {
     // moved from Reaper Scans (id) to Shinigami (id)
     override val id = 3411809758861089969
 
+    override val name = "Shinigami"
+
     override val baseUrl by lazy { getPrefBaseUrl() }
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: I don't think baseurl pref is needed, since it is using the api internally

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 5]
```diff
@@ -83,70 +64,213 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val result = response.parseAs<ShinigamiChapterListDto>()
+
+        return result.chapterList.map(::chapterFromObject)
+    }
+
+    private fun chapterFromObject(obj: ShinigamiChapterListDataDto): SChapter = SChapter.create().apply {
+        date_upload = obj.date.toDate()
+        name = "Chapter ${obj.name.toString().replace(".0","")} ${obj.title}"
+        url = "$apiUrl/$API_BASE_PATH/chapter/detail/" + obj.chapterId
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: save relative urls or just the id

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 6]
```diff
@@ -83,70 +64,213 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
-        return List(length) { charPool.random() }.joinToString("")
+    override fun pageListParse(response: Response): List<Page> {
+        val result = response.parseAs<ShinigamiPageListDto>()
+
+        return result.pageList.chapterPage.pages.mapIndexed { index, imageName ->
+            Page(index = index, imageUrl = "$cdnUrl${result.pageList.chapterPage.path}$imageName")
+        }
+    }
+
+    override fun fetchImageUrl(page: Page): Observable<String> = Observable.just(page.imageUrl!!)
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: not needed?

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt [hunk 7]
```diff
@@ -0,0 +1,71 @@
+package eu.kanade.tachiyomi.extension.id.shinigami
+
+import kotlinx.serialization.SerialName
+import kotlinx.serialization.Serializable
+
+@Serializable
+data class ShinigamiBrowseDto(
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt]: use regular classes instead of data class

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+data class ShinigamiMangaDetailDto(
+    val data: ShinigamiMangaDetailDataDto,
+)
+
+@Serializable
+data class ShinigamiMangaDetailDataDto(
+    val description: String = "",
+//    @SerialName("alternative_title") val alternativeTitle: String = "",
+    val status: Int = 0,
+    val taxonomy: Map<String, List<TaxonomyItemDto>> = emptyMap(),
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt:34]: maybe use a custom serializer to serialize it into object directly?

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 4 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: im using it for referer. can just be normal baseurl but they have history of changing frequently. even with their current new site they got 3 different one

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 1 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: oo new keiyoushi utils

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 2 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: oo this too. new keiyoushi utils

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 6 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: yea, forgot to remove from their previous api based ext

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 9]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
-            ?: throw Exception("Unable to deobfuscate chapter_data script")
+        if (query.isNotEmpty()) {
+            url.addQueryParameter("q", query)
+        }
+
+        // TODO: search by tag/genre/status/etc
 
-        val keyMatch = KEY_REGEX.find(deobfuscated)?.groupValues
-            ?: throw Exception("Unable to find key")
+        return GET(url.toString(), apiHeaders)
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
        return GET(url.build(), apiHeaders)
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 10]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+        url = obj.mangaId.toString()
+    }
 
-        val fixedUrl = urlElement.attr("abs:href")
+    override fun latestUpdatesRequest(page: Int): Request {
+        val url = "$apiUrl/$API_BASE_PATH/manga/list".toHttpUrl().newBuilder()
+            .addQueryParameter("page", page.toString())
+            .addQueryParameter("page_size", "30")
+            .addQueryParameter("sort", "latest")
+            .toString()
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
            .build()
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 11]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+        .add("DNT", "1")
+        .add("Origin", baseUrl)
+        .add("Sec-GPC", "1")
+
+    override fun popularMangaRequest(page: Int): Request {
+        val url = "$apiUrl/$API_BASE_PATH/manga/list".toHttpUrl().newBuilder()
+            .addQueryParameter("page", page.toString())
+            .addQueryParameter("page_size", "30")
+            .addQueryParameter("sort", "popularity")
+            .toString()
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
            .build()
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 12]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
-        val postId = POST_ID_REGEX.find(script)?.groupValues?.get(1) ?: throw Exception("Unable to get post_id")
-        val otherId = OTHER_ID_REGEX.findAll(script).firstOrNull { it.groupValues[1] != "post" }?.groupValues?.get(2) ?: throw Exception("Unable to get other id")
-        val key = otherId + keyMatch[1] + postId + keyMatch[2] + postId
-        val salt = chapterData.s.decodeHex()
+    override fun searchMangaParse(response: Response): MangasPage = popularMangaParse(response)
 
-        val unsaltedCiphertext = Base64.decode(chapterData.ct, Base64.DEFAULT)
-        val ciphertext = salted + salt + unsaltedCiphertext
+    override fun getMangaUrl(manga: SManga): String {
+        return "$baseUrl/series/" + manga.url
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
        return "$baseUrl/series/${manga.url}"
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 13]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
-        val data = json.decodeFromString<List<String>>(decrypted)
-        return data.mapIndexed { idx, it ->
-            Page(idx, document.location(), it)
+    override fun mangaDetailsRequest(manga: SManga): Request {
+        // Migration from old web urls to the new api based
+        if (manga.url.startsWith("/series/")) {
+            throw Exception("Migrate dari $name ke $name (ekstensi yang sama)")
         }
+
+        return GET("$apiUrl/$API_BASE_PATH/manga/detail/" + manga.url, apiHeaders)
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
        return GET("$apiUrl/$API_BASE_PATH/manga/detail/${manga.url}", apiHeaders)
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 14]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+        }
     }
 
     companion object {
-        private val KEY_REGEX by lazy { Regex("""_id\s+\+\s+'(.*?)'\s+\+\s+post_id\s+\+\s+'(.*?)'\s+\+\s+post_id""") }
-        private val CHAPTER_DATA_REGEX by lazy { Regex("""var chapter_data\s*=\s*'(.*?)'""") }
-        private val POST_ID_REGEX by lazy { Regex("""var post_id\s*=\s*'(.*?)'""") }
-        private val OTHER_ID_REGEX by lazy { Regex("""var (\w+)_id\s*=\s*'(.*?)'""") }
-        private const val RESTART_APP = "Untuk menerapkan perubahan, restart aplikasi."
+        private const val API_BASE_PATH = "v1"
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: inline it

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 15]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+    }
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val result = response.parseAs<ShinigamiChapterListDto>()
+
+        return result.chapterList.map(::chapterFromObject)
+    }
+
+    private fun chapterFromObject(obj: ShinigamiChapterListDataDto): SChapter = SChapter.create().apply {
+        date_upload = obj.date.toDate()
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
        date_upload = dateFormat.tryParse(obj.date)
```
save `SimpleDateFormat` in a class val and access it here like so, instead of creating it each time inside `toDate`

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 16]
```diff
@@ -83,70 +56,198 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+        url = obj.chapterId
+    }
+
+    override fun pageListRequest(chapter: SChapter): Request {
+        // Migration from old web urls to the new api based
+        if (chapter.url.startsWith("/series/")) {
+            throw Exception("Migrate dari $name ke $name (ekstensi yang sama)")
+        }
+
+        return GET("$apiUrl/$API_BASE_PATH/chapter/detail/" + chapter.url, apiHeaders)
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
        return GET("$apiUrl/$API_BASE_PATH/chapter/detail/${chapter.url}", apiHeaders)
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt [hunk 17]
```diff
@@ -0,0 +1,70 @@
...
+
+@Serializable
+class ShinigamiMangaDetailDto(
+    val data: ShinigamiMangaDetailDataDto,
+)
+
+@Serializable
+class ShinigamiMangaDetailDataDto(
+    val description: String = "",
+//    @SerialName("alternative_title") val alternativeTitle: String = "",
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt]: remove comment?

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt:1]: you can use this to serialize json with different things in `data`:
```kt
@Serializable
class Data<T>(val data: T)
```
"{data: [a, b]}" or "{data: {a: b}}"
```kt
response.parseAs<Data<List<SomeClass>>
response.parseAs<Data<AnotherClass>
```

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 14 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: was separating it in case they make another version like their perevious api but maybe better inline for now

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt (hunk 17 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/ShinigamiDto.kt]: maybe ill just remove it, curently their alt title just the same as the title

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 13 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: btw is there any downside for using "+" instead of that? i was using it cuz its kinda easier to read

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 18]
```diff
@@ -83,70 +56,195 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
-    // Tags are useless as they are just SEO keywords.
-    override val mangaDetailsSelectorTag = ""
+    override fun headersBuilder(): Headers.Builder = Headers.Builder()
+        .add("X-Requested-With", randomString((1..20).random())) // added for webview, and removed in interceptor for normal use
 
-    override val chapterUrlSelector = "div.chapter-link:not([style~=display:\\snone]) a"
+    private fun randomString(length: Int): String {
+        val charPool = ('a'..'z') + ('A'..'Z')
+        return List(length) { charPool.random() }.joinToString("")
+    }
```
Comment (vetleledaal) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: More performant and succinct:
```suggestion
    private fun randomString(length: Int) = buildString {
        val charPool = ('a'..'z') + ('A'..'Z')
        repeat(length) { append(charPool.random()) }
    }
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 19]
```diff
@@ -83,70 +56,195 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
 
-        val fixedUrl = urlElement.attr("abs:href")
+        return MangasPage(projectList, hasNextPage)
+    }
 
-        setUrlWithoutDomain(fixedUrl)
+    private fun popularMangaFromObject(obj: ShinigamiBrowseDataDto): SManga = SManga.create().apply {
+        title = obj.title.toString()
+        thumbnail_url = obj.thumbnail
+        url = obj.mangaId.toString()
```
Comment (vetleledaal) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: `.toString()` hides that the value might be null.
```suggestion
        title = obj.title!!
        thumbnail_url = obj.thumbnail
        url = obj.mangaId!!
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 20]
```diff
@@ -83,70 +56,195 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
-        val data = json.decodeFromString<List<String>>(decrypted)
-        return data.mapIndexed { idx, it ->
-            Page(idx, document.location(), it)
+        return GET(url.build(), apiHeaders)
+    }
+
+    override fun searchMangaParse(response: Response): MangasPage = popularMangaParse(response)
+
+    override fun getMangaUrl(manga: SManga): String {
+        return "$baseUrl/series/${manga.url}"
```
Comment (vetleledaal) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt:118]: Does `manga.url` contain special characters? Might not encode correctly if yes. Consider `HttpUrlBuilder`.

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 21]
```diff
@@ -83,70 +56,195 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
 
-    private fun randomString(length: Int): String {
-        val charPool = ('a'..'z') + ('A'..'Z')
-        return List(length) { charPool.random() }.joinToString("")
+    override fun mangaDetailsParse(response: Response): SManga {
+        val mangaDetailsResponse = response.parseAs<ShinigamiMangaDetailDto>()
+        val mangaDetails = mangaDetailsResponse.data
+
+        return SManga.create().apply {
+            author = mangaDetails.taxonomy["Author"]?.joinToString(", ") { it.name }.orEmpty()
```
Comment (vetleledaal) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: `, ` is the default and can be omitted:
```suggestion
            author = mangaDetails.taxonomy["Author"]?.joinToString { it.name }.orEmpty()
```

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 22]
```diff
@@ -83,70 +56,195 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
...
+        }
+
+        return GET("$apiUrl/v1/chapter/detail/${chapter.url}", apiHeaders)
+    }
+
+    override fun pageListParse(response: Response): List<Page> {
+        val result = response.parseAs<ShinigamiPageListDto>()
+
+        return result.pageList.chapterPage.pages.mapIndexed { index, imageName ->
+            Page(index = index, imageUrl = "$cdnUrl${result.pageList.chapterPage.path}$imageName")
```
Comment (vetleledaal) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt:183]: Consider using `HttpUrlBuilder`.

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 20 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt:118]: its something like this average UUID, unless you mean like broad special characters so "-" will be included. or you mean multiple one like expecting name with @ & %

d3b05787-4c8e-42bb-ba9a-6b2fafd92f3c
1aba726d-fb23-4e05-aafa-f6b5bb67c489
16778db0-17c0-43c4-aa4a-3a4a0df5ec0b

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt [hunk 23]
```diff
@@ -83,70 +56,195 @@ class Shinigami : Madara("Shinigami", "https://shinigami09.com", "id"), Configur
         .rateLimit(3)
         .build()
 
-    // Tags are useless as they are just SEO keywords.
-    override val mangaDetailsSelectorTag = ""
+    override fun headersBuilder(): Headers.Builder = Headers.Builder()
```
Comment (AwkwardPeak7) [inline src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]:
```suggestion
    override fun headersBuilder(): Headers.Builder = super.headersBuilder()
```
to keep useragent

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 20 above)
Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt:118]: a

Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt:118]: a

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 13 above)
Comment (AwkwardPeak7) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: each + internally uses a new string builder, while string template uses one string builder

File: src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt (hunk 4 above)
Comment (AwkwardPeak7) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: I mean, this pref doesn't control the api url, which is actually being used, having a pref just for referer isn't necessary

Comment (Riztard) [reply src/id/shinigami/src/eu/kanade/tachiyomi/extension/id/shinigami/Shinigami.kt]: maybe, can add later if really necessary. im adding it cuz the referer is needed to load the image, just not sure if they will block the older url if they change it

**Review by AwkwardPeak7 — APPROVED** [review]
