### PR TITLE
Qi Scans: improve sorting, text decoding, and paid chapter UX

### LINKED ISSUE #13960: Qi Scans: Chapter pages out of order
### Source information

Qi Scans

### Source language

English

### Steps to reproduce

1. Read chapter 62 of Zombie Apocalypse 82-08 in Qi Scans.
2. The images are placed randomly.
3. Open the chapter page in your browser.
4. The images are in order, and the chapter can be properly read.

### Expected behavior

The images should be placed in order.

### Actual behavior

The images are out of order.

### Mihon/Mihon fork version

0.19.4-7580

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by nobottomline**
## Changes
- reworked `Sort` filter to support both `orderBy` and `orderDirection`
- added and mapped sort options to the API:
  - `Most Views` -> `totalViews`
  - `Latest` -> `lastChapterAddedAt`
  - `Newly Added` -> `createdAt`
  - `Title (A-Z)` -> `postTitle` + `asc`
  - `Title (Z-A)` -> `postTitle` + `desc`
- switched latest endpoint parsing to `/api/posts` (`tag=latestUpdate`) for more reliable latest updates
- improved paid chapter handling:
  - keep display toggle enabled by default
  - show a clear paid/locked message instead of NEXT-data parsing error
  - keep locked chapter detection before JSON parsing
- decoded HTML entities in manga text fields (`title`, `author`, `artist`, `description`, `genre`) to fix encoded strings like `&#8217;`
- bumped `overrideVersionCode` from `5` to `6`

## Notes
- no source rename
- no ID/language changes
- no workflow changes included in this PR

## Testing
- built and tested with:
  - `./gradlew :src:en:qiscans:assembleDebug`

## Checklist
- [x] Updated `overrideVersionCode` as needed
- [x] Have not changed source names
- [x] Have explicitly kept the `id` (no name/lang changes)
- [x] Tested modifications by compiling the extension

### CODE REVIEW

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 1]
```diff
@@ -35,16 +42,58 @@ class QiScans :
...
 
+    override fun searchMangaParse(response: Response): MangasPage = super.searchMangaParse(response).apply {
+        mangas.forEach(::normalizeMangaTextFields)
+    }
+
+    override fun fetchMangaDetails(manga: eu.kanade.tachiyomi.source.model.SManga): Observable<eu.kanade.tachiyomi.source.model.SManga> = super.fetchMangaDetails(manga).map {
+        it.apply(::normalizeMangaTextFields)
+    }
+
     override fun latestUpdatesRequest(page: Int): Request {
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: this same as default in Iken

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 2]
```diff
@@ -35,16 +42,58 @@ class QiScans :
...
+
+    @Serializable
+    class LatestPostDto(
+        private val id: Int,
+        val slug: String,
+        @SerialName("postTitle") private val title: String,
+        @SerialName("featuredImage") private val thumbnailUrl: String? = null,
+        val isNovel: Boolean = false,
+    ) {
+        fun toManga() = eu.kanade.tachiyomi.source.model.SManga.create().apply {
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: import instead

**Comment by xMohnad** [comment]
see #13865

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 3]
```diff
@@ -35,16 +42,58 @@ class QiScans :
...
+        it.apply(::normalizeMangaTextFields)
+    }
+
     override fun latestUpdatesRequest(page: Int): Request {
-        val url = "$apiUrl/api/query".toHttpUrl().newBuilder().apply {
-            // 'query' instead of 'posts'
+        val url = "$apiUrl/api/posts".toHttpUrl().newBuilder().apply {
             addQueryParameter("page", page.toString())
             addQueryParameter("perPage", "18")
-            addQueryParameter("orderBy", "updatedAt")
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: this same as default in Iken

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 4]
```diff
@@ -35,16 +42,58 @@ class QiScans :
 
     override fun popularMangaParse(response: Response): MangasPage = searchMangaParse(response)
 
+    override fun searchMangaParse(response: Response): MangasPage = super.searchMangaParse(response).apply {
+        mangas.forEach(::normalizeMangaTextFields)
+    }
+
+    override fun fetchMangaDetails(manga: eu.kanade.tachiyomi.source.model.SManga): Observable<eu.kanade.tachiyomi.source.model.SManga> = super.fetchMangaDetails(manga).map {
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: use import instead

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 3 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Addressed in 19ac766a3. Removed the redundant latest override and now rely on the default Iken implementation.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 4 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Addressed in 19ac766a3. Replaced the fully qualified SManga type with an import.

**Comment by nobottomline** [comment]
@xMohnad Addressed both review comments in 19ac766a3 and resolved the threads. Could you please take another look when you have time?

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 5]
```diff
@@ -15,4 +28,90 @@ class QiScans :
...
+    override val statusFilterOptions: Options =
+        listOf(
+            "All" to "",
+            "Ongoing" to "ONGOING",
+            "Hiatus" to "HIATUS",
+            "Dropped" to "DROPPED",
+            "Completed" to "COMPLETED",
+        )
+
+    override val typeFilterOptions: Options = emptyList()
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: why? type filter works fine in qiscans

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 6]
```diff
@@ -15,4 +28,90 @@ class QiScans :
     override val client = super.client.newBuilder()
         .rateLimit(3, 1, TimeUnit.SECONDS)
         .build()
+
+    override val statusFilterOptions: Options =
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: same as default; COMING_SOON and MASS_RELEASED work fine.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 7]
```diff
@@ -15,4 +28,90 @@ class QiScans :
...
+
+    private fun Document.isLockedChapterPage(): Boolean {
+        if (selectFirst("svg.lucide-lock") != null) return true
+
+        val text = body().text()
+        return text.contains("unlock chapter", ignoreCase = true) ||
+            text.contains("chapter locked", ignoreCase = true) ||
+            text.contains("paid chapter", ignoreCase = true) ||
+            text.contains("purchase", ignoreCase = true) ||
+            text.contains("coins", ignoreCase = true)
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: assume that one of these phrases appears in the manga title or elsewhere

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 8]
```diff
@@ -15,4 +28,90 @@ class QiScans :
...
+            "Latest" to "lastChapterAddedAt",
+            "Most Views" to "totalViews",
+            "Newly Added" to "createdAt",
+            "Title" to "postTitle",
+        )
+
+    override val sortDirectionOptions: Options =
+        listOf(
+            "Descending" to "desc",
+            "Ascending" to "asc",
```
Comment (xMohnad) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: else same as default

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 5 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Addressed. Restored default filters (type/status/sort direction) and narrowed paid-chapter detection to the lock icon to avoid false positives.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 6 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Addressed. Restored default filters (type/status/sort direction) and narrowed paid-chapter detection to the lock icon to avoid false positives.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 7 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Addressed. Restored default filters (type/status/sort direction) and narrowed paid-chapter detection to the lock icon to avoid false positives.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 8 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Addressed. Restored default filters (type/status/sort direction) and narrowed paid-chapter detection to the lock icon to avoid false positives.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 9]
```diff
@@ -15,4 +26,55 @@ class QiScans :
...
+            }
+    }
+
+    private fun normalizeMangaTextFields(manga: SManga) {
+        manga.title = decodeHtmlEntities(manga.title)
+        manga.author = manga.author?.let(::decodeHtmlEntities)
+        manga.artist = manga.artist?.let(::decodeHtmlEntities)
+        manga.description = manga.description?.let(::decodeHtmlEntities)
+        manga.genre = manga.genre?.let(::decodeHtmlEntities)
+    }
```
Comment (vetleledaal) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: If this returns the `SManga` instead of `Unit` then you could probably simplify `fetchMangaDetails` to `.map(::normalizeMangaTextFields)`.

**Review by vetleledaal — DISMISSED** [review]

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 10]
```diff
@@ -15,4 +26,55 @@ class QiScans :
...
+
+    override fun setupPreferenceScreen(screen: PreferenceScreen) {
+        SwitchPreferenceCompat(screen.context).apply {
+            key = SHOW_LOCKED_CHAPTER_PREF_KEY
+            title = "Display paid chapters"
+            summaryOn = "Paid chapters will appear."
+            summaryOff = "Only free chapters will be displayed."
+            setDefaultValue(true)
+        }.also(screen::addPreference)
+    }
```
Comment (AwkwardPeak7) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt:59]: this already exists in the iken class, why repeat here?

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt [hunk 11]
```diff
@@ -15,4 +26,55 @@ class QiScans :
...
+            } else {
+                throw Exception("Unable to retrieve NEXT data")
+            }
+
+        return images.images
+            .sortedBy { it.order ?: Int.MAX_VALUE }
+            .mapIndexed { idx, p ->
+                Page(idx, imageUrl = p.url.replace(" ", "%20"))
+            }
+    }
```
Comment (AwkwardPeak7) [inline src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: this is basically identical to the one in iken

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 9 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Good point, addressed in e8fa62bdb. `normalizeMangaTextFields` now returns `SManga`, and `fetchMangaDetails` now uses `.map(::normalizeMangaTextFields)`.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 11 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt]: Addressed in e8fa62bdb. `pageListParse` now delegates to `super.pageListParse(response)` and only customizes the locked-chapter error message for QiScans.

File: src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt (hunk 10 above)
Comment (nobottomline) [reply src/en/qiscans/src/eu/kanade/tachiyomi/extension/en/qiscans/QiScans.kt:59]: Kept this override intentionally because QiScans needs different preference UX: title/summaries plus default enabled (`true`) for paid chapter display. Iken default is a generic toggle with default disabled.

**Review by vetleledaal — APPROVED** [review]
