### PR TITLE
SenManga Fix

### LINKED ISSUE #13849: sen manga is unavailable
### Source information

sen manga 1.4.7

### Source language

Japanese

### Steps to reproduce

The extension cannot load any content.

### Expected behavior

It can be used normally.

### Actual behavior

Unable to use

### Mihon/Mihon fork version

mihon 1.9.4

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #13849

Search give generic because it's broken on site also genres don't work and some sorting system are broken also site refuses to display some cover for some reason.
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/senmanga/src/eu/kanade/tachiyomi/extension/ja/senmanga/Dto.kt [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    fun toSManga() = SManga.create().apply {
+        this.title = this@SeriesDto.title
+        this.url = slug
+        this.thumbnail_url = cover
+        this.description = this@SeriesDto.description
+        this.genre = this@SeriesDto.genre
+        this.status = parseStatus(this@SeriesDto.status)
+    }
+
+    private fun parseStatus(statusString: String?): Int {
```
Comment (MuhamadSyabitHidayattulloh) [inline src/ja/senmanga/src/eu/kanade/tachiyomi/extension/ja/senmanga/Dto.kt]: Using lowercase is better than giving ignorecase status one by one

File: src/ja/senmanga/src/eu/kanade/tachiyomi/extension/ja/senmanga/Dto.kt [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        if (statusString == null) return SManga.UNKNOWN
```
Comment (MuhamadSyabitHidayattulloh) [inline src/ja/senmanga/src/eu/kanade/tachiyomi/extension/ja/senmanga/Dto.kt]: Put it in return when as well for null status

**Review by AwkwardPeak7 — APPROVED** [review]
