### PR TITLE
FoamGirl: Fix  pages loading

### LINKED ISSUE #6116: FoamGirl: 'for input string' error for certain entries
### Source information

FoamGirl 1.4.1

### Source language

Multi

### Steps to reproduce

1. Open these entry on Browse (NSFW warning, bikini)
`Ai Shinozaki 篠崎愛, FRIDAY 2022.12.23 (フライデー 2022年12月23日号)(17P)`
`Umi Shinonome 東雲うみ, Young Jump 2022 No.45 (ヤングジャンプ 2022年45号)(6P)`
2. Click the chapter (GALLLERY)
3. It result `for input string: "random code"` error

eweqweqwe
eqweqw

### Expected behavior

Clicking the chapter opens the gallery

### Actual behavior

`for input string: "random code"` error

### Mihon/Tachiyomi version

Mihon 0.17.0 / Aniyomi 0.16.4.3 / Komikku 1.12.1

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by choppeh**
Closes #6116

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt [hunk 1]
```diff
@@ -119,7 +147,11 @@ class FoamGirl() : ParsedHttpSource() {
         }
     }
 
+    private fun String.isNumber() = NUMB_REGEX.matches(this)
```
Comment (vetleledaal) [inline src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt]: Avoid regex if possible.

This is equivalent to `^\d+$`:
```suggestion
    private fun String.isNumber() = isNotEmpty() && all { it.isDigit() }
```

File: src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt [hunk 2]
```diff
@@ -83,6 +94,23 @@ class FoamGirl() : ParsedHttpSource() {
...
+        val pages = document.select("#image_div img").mapIndexed { index, element ->
+            Page(index, imageUrl = element.absUrl("src"))
+        }.toList()
+
+        val nextPageUrl = document.selectFirst(".page-numbers[title=Next]")?.absUrl("href")
+            ?: return pages
+
+        if (HAS_NEXT_PAGE_REGEX.containsMatchIn(nextPageUrl).not()) {
+            return pages
+        }
```
Comment (vetleledaal) [inline src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt]: Can be combined?:

```suggestion
        val nextPageUrl = document.selectFirst(".page-numbers[title=Next]")
            ?.absUrl("href")
            ?.takeIf { HAS_NEXT_PAGE_REGEX in it }
            ?: return pages
```

File: src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt [hunk 3]
```diff
@@ -65,10 +67,19 @@ class FoamGirl() : ParsedHttpSource() {
...
+
+        if (baseIndex.isNumber()) {
+            return getPagesListByNumber(imageCount, imageUrl, baseIndex)
+        }
+        return getPageListByDocument(document)
+    }
+
+    private fun getPagesListByNumber(imageCount: Int, imageUrl: HttpUrl, baseIndex: String): MutableList<Page> {
+        val imagePrefix = baseIndex.toLong() / 10
+        val pages = mutableListOf<Page>()
```
Comment (vetleledaal) [inline src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt]: This is mostly outside of your changeset, so you can just ignore it, but consider using a (more) functional approach here.
```kt
private fun getPagesListByNumber(imageCount: Int, imageUrl: HttpUrl, baseIndex: String): List<Page> {
    val imagePrefix = baseIndex.toLong() / 10
    return (0 until imageCount).map { index ->
        Page(
            index,
            imageUrl = imageUrl.newBuilder().apply {
                removePathSegment(imageUrl.pathSize - 1)
                addPathSegment("${imagePrefix}${index + 2}.jpg")
            }.build().toString(),
        )
    }
}
```
or
```kt
private fun getPagesListByNumber(imageCount: Int, imageUrl: HttpUrl, baseIndex: String): List<Page> {
    val imagePrefix = baseIndex.toLong() / 10
    return List(imageCount) { index ->
        Page(
            index,
            imageUrl = imageUrl.newBuilder().apply {
                removePathSegment(imageUrl.pathSize - 1)
                addPathSegment("${imagePrefix}${index + 2}.jpg")
            }.build().toString(),
        )
    }
}
```

File: src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt [hunk 4]
```diff
@@ -65,10 +67,19 @@ class FoamGirl() : ParsedHttpSource() {
...
-        val pages = mutableListOf<Page>()
         val imageCount = document.select(".post_title_topimg").text().substringAfter("(").substringBefore("P").toInt()
         val imageUrl = document.select(".imageclick-imgbox").attr("href").toHttpUrl()
-        val imagePrefix = imageUrl.pathSegments.last().substringBefore(".").toLong() / 10
+        val baseIndex = imageUrl.pathSegments.last().substringBefore(".")
+
+        if (baseIndex.isNumber()) {
+            return getPagesListByNumber(imageCount, imageUrl, baseIndex)
+        }
+        return getPageListByDocument(document)
```
Comment (vetleledaal) [inline src/all/foamgirl/src/eu/kanade/tachiyomi/extension/all/foamgirl/FoamGirl.kt]:
```suggestion
        return if (baseIndex.isNumber()) {
            getPagesListByNumber(imageCount, imageUrl, baseIndex)
        } else {
            getPageListByDocument(document)
        }
```

**Review by vetleledaal — CHANGES_REQUESTED** [review]

**Review by vetleledaal — APPROVED** [review]
