### PR TITLE
Plot Twist No Fansub Fix

### LINKED ISSUE #14955: Plot twist no fansub new url
### Source information

Plot Twist No Fansub 1.4.10

### Source language

Spanish

### Source new URL

https://plotnofansub.com

### Other details

With this new direction on Discord, they began uploading new episodes

Image

### Acknowledgements

- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have checked WebView to see the source's main URL is not up-to-date, or has to redirect into the new URL.
- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues/) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by darwin-256**
Closes #14955

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by Justatrashbag** [comment]
No se quien seas, pero gracias por ir actualizando la extensión de los de plot, uno aquí ni idea como hacerlo xD

**Comment by MikeZeDev** [comment]
"/wp-json/plot/v1/getcaps7",

endpoint is similar to https://github.com/keiyoushi/extensions-source/blob/main/src/es/mangasnosekai/src/eu/kanade/tachiyomi/extension/es/mangasnosekai/MangasNoSekai.kt

In fact the only thing different are the chapter endpoint path and the chapter endpoint action.

**Comment by darwin-256** [comment]
> "/wp-json/plot/v1/getcaps7",
> 
> endpoint is similar to https://github.com/keiyoushi/extensions-source/blob/main/src/es/mangasnosekai/src/eu/kanade/tachiyomi/extension/es/mangasnosekai/MangasNoSekai.kt
> 
> In fact the only thing different are the chapter endpoint path and the chapter endpoint action.

So should I rewrite it so it matches like other script? Seems like more work when the script already works

**Comment by MikeZeDev** [comment]
> > "/wp-json/plot/v1/getcaps7",
> > endpoint is similar to https://github.com/keiyoushi/extensions-source/blob/main/src/es/mangasnosekai/src/eu/kanade/tachiyomi/extension/es/mangasnosekai/MangasNoSekai.kt
> > In fact the only thing different are the chapter endpoint path and the chapter endpoint action.
> 
> So should I rewrite it so it matches like other script? Seems like more work when the script already works

Dont worry i was just trying to help. Its up to people reviewing this to decide. I just like the concept of templates.

File: src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt [hunk 1]
```diff
@@ -1,251 +1,241 @@
...
-    override fun setupPreferenceScreen(screen: PreferenceScreen) {
-        screen.addRandomUAPreference()
-    }
-
     override fun headersBuilder() = super.headersBuilder()
         .add("Referer", "$baseUrl/")
-        .setRandomUserAgent()
 
-    override fun popularMangaRequest(page: Int): Request = GET(baseUrl, headers)
+    private val json = Json { ignoreUnknownKeys = true }
```
Comment (AwkwardPeak7) [inline src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt]: use `keiyoushi.utils.parseAs` for json

File: src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt [hunk 2]
```diff
@@ -1,251 +1,241 @@
...
-                .replaceFirst("/reader/", "/plotwist/manga/")
-            setUrlWithoutDomain(mangaUrl)
-            thumbnail_url = select("img").imgAttr()
-            title = select("img").attr("title")
+        val mangas = document.select("div.page-listing-item figure").map { element ->
+            SManga.create().apply {
+                val a = element.selectFirst("a")!!
+                setUrlWithoutDomain(a.attr("href"))
+                title = a.attr("title").takeIf { it.isNotEmpty() }
+                    ?: element.selectFirst("figcaption")?.text() ?: ""
```
Comment (AwkwardPeak7) [inline src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt]: title is mandatory

File: src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt [hunk 3]
```diff
@@ -1,251 +1,241 @@
...
-    override fun searchMangaSelector(): String = "div.td-cpt-manga"
+        if (!isTextSearch) return popularMangaParse(response)
 
-    override fun searchMangaNextPageSelector(): String? = null
+        val mangas = document.select("div.c-tabs-item__content").map { element ->
+            SManga.create().apply {
+                val a = element.selectFirst(".post-title a") ?: element.selectFirst("a")!!
+                setUrlWithoutDomain(a.attr("href"))
+                title = a.text().takeIf { it.isNotEmpty() }
+                    ?: element.selectFirst("a")?.attr("title") ?: ""
```
Comment (AwkwardPeak7) [inline src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt]: same here

File: src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt [hunk 4]
```diff
@@ -1,251 +1,241 @@
...
+        val pages = document.select("div.page-break img").mapIndexed { i, img ->
+            Page(i, imageUrl = img.imgAttr())
+        }
 
-    override fun getFilterList(): FilterList = FilterList(
-        Filter.Header("Haga click en \"Filtrar\" para ver todos los mangas."),
-    )
+        if (pages.isEmpty()) {
+            throw Exception("No se encontraron páginas. Posible captcha o error de carga.")
+        }
```
Comment (AwkwardPeak7) [inline src/es/plottwistnofansub/src/eu/kanade/tachiyomi/extension/es/plottwistnofansub/PlotTwistNoFansub.kt]: dont throw here, let app throw it's own error

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Review by AwkwardPeak7 — APPROVED** [review]
