### PR TITLE
zh/boylove: Update and remove obsolete mirror links

### LINKED ISSUE #2219: Boylove no images
### Source information

Boylove 1.4.10

### Source language

Chinese

### Steps to reproduce

Open any manga
Click on any chapter
It says "the images couldn't be loaded"

### Expected behavior

Images should load for every chapter

### Actual behavior

It doesnt load 

### Mihon/Tachiyomi version

0.16.0

### Android version

Android 10

### Other details

Can view images in webview

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by morallkat**
This PR remove and update the obsolete mirrors for Boylove/香香腐宅

New links are coming from https://boylovepage.github.io/boylove_page/, their default redirect page since Jan 2024. 

For the time being, the original boylove.cc server has raised its protection level, which causes the extension to be unable to bypass Cloudflare in some areas. The new links may solve this temporarily.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt [hunk 1]
```diff
@@ -206,7 +206,8 @@ class BoyLove : HttpSource(), ConfigurableSource {
         private const val MIRROR_PREF = "MIRROR"
 
         // redirect URL: https://fuhouse.club/bl
-        private val MIRRORS get() = arrayOf("boylov.xyz", "boylove3.cc", "boylove.cc", "boylove1.cc", "boylove2.cc", "boylove.today")
-        private val MIRRORS_DESC get() = arrayOf("boylov.xyz", "boylove3.cc", "boylove.cc (非大陆地区)", "boylove1.cc", "boylove2.cc", "boylove.today")
+        // link source URL: https://boylovepage.github.io/boylove_page
+        private val MIRRORS get() = arrayOf("boylove.cc", "fuzai.cc", "boylove1.mobi", "boylove3.cc", "boyloves.space", "boylove4.xyz", "boyloves.fun", "boylove.today", "fuzai.one", "xxfuzai.xyz")
+        private val MIRRORS_DESC get() = arrayOf("boylove.cc（非大陆）", "fuzai.cc（非大陆）", "boylove1.mobi", "boylove3.cc", "boyloves.space", "boylove4.xyz", "boyloves.fun", "boylove.today", "fuzai.one", "xxfuzai.xyz")
```
Comment (stevenyomi) [inline src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt]: Put a mainland-accessible domain as the first one.

Comment (morallkat) [reply src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt]: done.

File: src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt [hunk 2]
```diff
@@ -206,7 +206,8 @@ class BoyLove : HttpSource(), ConfigurableSource {
         private const val MIRROR_PREF = "MIRROR"
 
         // redirect URL: https://fuhouse.club/bl
-        private val MIRRORS get() = arrayOf("boylov.xyz", "boylove3.cc", "boylove.cc", "boylove1.cc", "boylove2.cc", "boylove.today")
-        private val MIRRORS_DESC get() = arrayOf("boylov.xyz", "boylove3.cc", "boylove.cc (非大陆地区)", "boylove1.cc", "boylove2.cc", "boylove.today")
+        // link source URL: https://boylovepage.github.io/boylove_page
+        private val MIRRORS get() = arrayOf("boylove1.mobi", "boylove3.cc", "boyloves.space", "boylove4.xyz", "boyloves.fun", "boylove.today", "fuzai.one", "xxfuzai.xyz", "boylove.cc", "fuzai.cc")
+        private val MIRRORS_DESC get() = arrayOf("boylove1.mobi", "boylove3.cc", "boyloves.space", "boylove4.xyz", "boyloves.fun", "boylove.today", "fuzai.one", "xxfuzai.xyz", "boylove.cc（非大陆）", "fuzai.cc（非大陆）")
```
Comment (stevenyomi) [inline src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt]: Swap `boylove.cc` to index 2 so existing users don't need to change this setting.

Comment (morallkat) [reply src/zh/boylove/src/eu/kanade/tachiyomi/extension/zh/boylove/BoyLove.kt]: resolved.

**Review by stevenyomi — APPROVED** [review]
