### PR TITLE
Fix InfinityScans

### LINKED ISSUE #5561: InfinityScans Theme Change
### Source information

InfinityScans 1.4.4

### Source language

English

### Steps to reproduce

1. Go to Sources
2. Select InfinityScans

### Expected behavior

1. Go to Sources
2. Select InfinityScans
3. Shows Manga lists

### Actual behavior

Not Showing Manga Lists

### Mihon/Tachiyomi version

Yokai 1.8.5.9 / Mihon 0.16.5

### Android version

Android 14

### Other details

Before the Theme Changed InfinityScans Extension, Mangas did not Show Thumbnails (return null)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by 1aam2am1**
Checklist:

Closes #5561

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt [hunk 1]
```diff
@@ -49,59 +47,114 @@ class InfinityScans : HttpSource() {
...
         add("Sec-Fetch-Mode", "cors")
         add("Sec-Fetch-Site", "same-origin")
-        add("X-Requested-With", "XMLHttpRequest")
+        add("X-requested-with", "XMLHttpRequest")
     }.build()
 
     private val json: Json by injectLazy()
 
     // Popular
+    override fun fetchPopularManga(page: Int): Observable<MangasPage> {
```
Comment (bapeey) [inline src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt]: Use the request and parse methods instead

Comment (1aam2am1) [reply src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt]: Ack,
fetchPopularManga
fetchLatestUpdates
reverted to use request and parse methods

fetchSearchManga is impossible to revert as in parse method we don't know about query or filters.

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt [hunk 2]
```diff
@@ -49,59 +47,106 @@ class InfinityScans : HttpSource() {
         add("Sec-Fetch-Dest", "empty")
         add("Sec-Fetch-Mode", "cors")
         add("Sec-Fetch-Site", "same-origin")
-        add("X-Requested-With", "XMLHttpRequest")
+        add("X-requested-with", "XMLHttpRequest")
```
Comment (vetleledaal) [inline src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt:50]: Why change? Casing doesn't matter for HTTP/2 in any case

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt [hunk 3]
```diff
@@ -49,59 +47,106 @@ class InfinityScans : HttpSource() {
...
+
+    override fun fetchSearchManga(
+        page: Int,
+        query: String,
+        filters: FilterList,
+    ): Observable<MangasPage> {
+        return client.newCall(fetchJson("api/comics"))
+            .asObservableSuccess()
+            .map { response ->
+                val data = response.parseAs<ResponseDto<SearchResultDto>>().result
```
Comment (vetleledaal) [inline src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt:91]: Consider extracting this scope into another function, so you don't have too deep indentation.

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/WebviewInterceptor.kt [hunk 4]
```diff
@@ -55,7 +55,7 @@ class WebviewInterceptor(private val baseUrl: String) : Interceptor {
 
             webview.webViewClient = object : WebViewClient() {
                 override fun shouldInterceptRequest(view: WebView?, request: WebResourceRequest?): WebResourceResponse? {
-                    if (request?.url.toString().contains("$baseUrl/ajax/turnstile")) {
+                    if (request?.url.toString().contains("$baseUrl/api/verification")) {
```
Comment (vetleledaal) [inline src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/WebviewInterceptor.kt:58]: Can you do this without converting to string? I'm assuming `contains` is used to detect the path regardless of query parameters.

```kt
request?.url.encodedPath == "/api/verification"
```

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt (hunk 3 above)
Comment (1aam2am1) [reply src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt:91]: Hm...
I don't see any meaning to extracting this part, as it doesn't duplicate between any function and it doesn't add any clarity to what the code does.

From my point of view this function is somewhat big, and maybe need to be broken up, but it is one whole entity.

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/WebviewInterceptor.kt (hunk 4 above)
Comment (1aam2am1) [reply src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/WebviewInterceptor.kt:58]: I don't know why exactly it is checked to that way.
I only updated the requested url to match the reality.

Should I change it, as it now works.

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt (hunk 3 above)
Comment (vetleledaal) [reply src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt:91]: This is of course subjective, but extracting it would make it [follow the parent function more closely](https://github.com/mihonapp/mihon/blob/3bd8d3ecb7023d1b01930ab0f91482c23e89c946/source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/online/HttpSource.kt#L143). It almost seem like you could remove the custom `fetch*` function here entirely. If that is possible that would be the ideal. Mostly because of the deprecation of RxJava.

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/WebviewInterceptor.kt (hunk 4 above)
Comment (vetleledaal) [reply src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/WebviewInterceptor.kt:58]: It's not critical, so leaving it as-is is also valid.

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt (hunk 3 above)
Comment (vetleledaal) [reply src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt:91]: I just saw your other comment. In that case there's no straight forward way to do it.

> fetchSearchManga is impossible to revert as in parse method we don't know about query or filters.

**Review by vetleledaal — APPROVED** [review]

File: src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt (hunk 2 above)
Comment (1aam2am1) [reply src/en/infinityscans/src/eu/kanade/tachiyomi/extension/en/infinityscans/InfinityScans.kt:50]: No thoughts. I didn't know http specification, and I was seeing that it sends small. So I changed it.
