### PR TITLE
Readmangas: Fixed to the pagination of the chapters and the domain

### LINKED ISSUE #6719: Please change the domain of the read mangas extension
### Source information

Read Mangas 1.4.32

### Source language

Português Brasil - PT-BR

### Source new URL

https://app.loobyt.com/

### Other details

Screenshot_2024-12-20-12-49-34-077_com android chrome
Screenshot_2024-12-20-12-52-27-151_app komikku
Screenshot_2024-12-20-12-52-44-535_app komikku

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lordenecromante**
Closes #6719 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt [hunk 1]
```diff
@@ -247,13 +247,16 @@ class ReadMangas() : HttpSource() {
 
     override fun pageListParse(response: Response): List<Page> {
         val document = response.asJsoup()
-        val script = document.select("script").map { it.data() }
-            .firstOrNull { IMAGE_URL_REGEX.containsMatchIn(it) }
-            ?: return emptyList()
+        val scripts = document.select("script").map { it.data() }
```
Comment (vetleledaal) [inline src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: This will allow you to run the regex once:

```suggestion
        val scripts = document.select("script").joinToString("\n") { it.data() }
```

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt [hunk 2]
```diff
@@ -247,13 +247,16 @@ class ReadMangas() : HttpSource() {
...
+        val pages = mutableListOf<Page>()
```
Comment (vetleledaal) [inline src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: Avoid using mutable objects if possible. Since you are just return it here you should be able to use an immutable list.

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt (hunk 1 above)
Comment (lordenecromante) [reply src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: Fix it

File: src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt (hunk 2 above)
Comment (lordenecromante) [reply src/pt/readmangas/src/eu/kanade/tachiyomi/extension/pt/readmangas/ReadMangas.kt]: Fix it.

**Review by vetleledaal — APPROVED** [review]
