### PR TITLE
Westmanga (ID): update domain

### LINKED ISSUE #13770: West Manga: `JsonDecodingException` error, new website URL (`westmanga.tv`)
### Source information

West Manga 1.4.38

### Source language

Indonesia

### Source new URL

https://westmanga.tv

### Steps to reproduce

when starting west manga

error JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $ JSON input:

### Expected behavior

go to the newest or most popular page

### Actual behavior

not opening the page but error

 JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $ JSON input:

### Mihon/Mihon fork version

TachiyomiSY 1.12.0 and Tadami 0.27

### Android version

Android 13

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by MuhamadSyabitHidayattulloh**
Close #13770 
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt [hunk 1]
```diff
@@ -71,7 +71,7 @@ class WestManga : HttpSource() {
                 // old urls compatibility
                 setUrlWithoutDomain(
                     baseUrl.toHttpUrl().newBuilder()
-                        .addPathSegment("manga")
+                        .addPathSegment("comic")
```
Comment (AwkwardPeak7) [inline src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt]: dont change this, this is here so old urls from madara times continue to work. plus changing it now will make it so all series are no longer marked as "in library"

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt [hunk 2]
```diff
@@ -86,8 +86,7 @@ class WestManga : HttpSource() {
 
     override fun mangaDetailsRequest(manga: SManga): Request {
         val path = "$baseUrl${manga.url}".toHttpUrl().pathSegments
-        assert(path.size == 3) { "Migrate from $name to $name" }
-        val slug = path[1]
+        val slug = path.filter { it.isNotBlank() }.last()
```
Comment (AwkwardPeak7) [inline src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt]: Should revert these too

**Review by AwkwardPeak7 — APPROVED** [review]
