### PR TITLE
ClipStudioReader: refactor / FireCross: fix chapter list parsing, preference / DreComics: fix date

### LINKED ISSUE #14306: FireCross: cannot fetch chapters
### Source information

FireCross 1.4.1

### Source language

Japanese

### Steps to reproduce

example: manga with title "精霊幻想記"

1. Search "精霊幻想記" in the source > found "精霊幻想記" > but have no chapter
Image

2. Search "精霊幻想記" in FireCross website (["精霊幻想記"'s page](https://firecross.jp/ebook/series/235)) > there are free chapters

Image

### Expected behavior

Tachiyomi: FireCross source should have the same number of chapters as the website

### Actual behavior

not same number of chapters

### Mihon/Mihon fork version

Komikku Stable 1.13.5

### Android version

Android 16

### Other details

_No response_

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by manti-X**
Closes #14306

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt [hunk 1]
```diff
@@ -103,11 +100,8 @@ abstract class ClipStudioReader : HttpSource() {
                 addQueryParameter("vm", "4")
                 addQueryParameter("file", pageFileName)
                 addQueryParameter("param", authkey)
-                // Custom params
-                addQueryParameter("csr_sw", faceData.scrambleWidth.toString())
-                addQueryParameter("csr_sh", faceData.scrambleHeight.toString())
-            }.build()
-            Page(i, url = pageXmlUrl.toString())
+            }.fragment("${faceData.scrambleWidth}/${faceData.scrambleHeight}")
```
Comment (vetleledaal) [inline lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt:103]: Mixing `key=value` and just `value` in the fragment. Intentional?

(`key` and `value` above being placeholders, `key` incidentally colliding with actual use)

Comment (manti-X) [reply lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt:103]: yea? I'm just passing it to ```imageUrlParse``` or wdym?

Comment (AwkwardPeak7) [reply lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt:103]: Vetle probably means to ask, above you pass `key=$obfuscationKey`, and here `${faceData.scrambleWidth}/${faceData.scrambleHeight}`. mixing = and / in different fragments. is this intentional.

File: lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt
Comment (AwkwardPeak7) [inline lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt:1]: please bump all sources which depend on this lib

Comment (manti-X) [reply lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt:1]: I already did, only two sources

File: lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt (hunk 1 above)
Comment (manti-X) [reply lib/clipstudioreader/src/keiyoushi/lib/clipstudioreader/ClipStudioReader.kt:103]: i'm not mixing anything. Those two never see each other: ```key=$obfuscationKey``` goes directly into the ```Deobfuscator``` interceptor while ```${faceData.scrambleWidth}/${faceData.scrambleHeight}``` solely passes it to ```imageUrlParse``` where I build the fragment ```size=$scrambleArray/$scrambleGridW/$scrambleGridH``` for ```ImageInterceptor```

**Review by AwkwardPeak7 — APPROVED** [review]
