### PR TITLE
Fix Comic Growl

### LINKED ISSUE #8302: Comic Growl
### Source information

Comic Growl 1.4.6

### Source language

Multi

### Steps to reproduce

Open source.

### Expected behavior

Load titles.

### Actual behavior

No results found.

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 14

### Other details

New site layout and coin system.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by heddxh**
WIP.

Fix #8302 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 1]
```diff
@@ -1,63 +1,330 @@
...
+        private fun getImageFromElement(element: Element): String {
+            val match = imageUrlRegex.find(element.selectFirst("source")!!.attr("data-srcset"))
+                ?: throw Exception("Cover image url not found")
+            return "https:" + match.value
+        }
+
+        private val DATE_PARSER by lazy { SimpleDateFormat("yyyy-MM-dd", Locale.JAPAN) }
+
+        /**
+         * Parse date from string like "3月31日" to UNIX Epoch time.
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Something like `SimpleDateFormat("M月d日", Locale.ROOT)`?

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 2]
```diff
@@ -1,63 +1,330 @@
...
+            return DATE_PARSER.tryParse(this)
+        }
+    }
+
+    override val client = super.client.newBuilder()
+        .addNetworkInterceptor(::imageDescrambler)
+        .build()
 
-    override fun popularMangaRequest(page: Int): Request = GET(baseUrl, headers)
+    override fun popularMangaRequest(page: Int) = GET("$baseUrl/ranking/manga")
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Should still send headers by default. Here and for every other call to `GET`.
```suggestion
    override fun popularMangaRequest(page: Int) = GET("$baseUrl/ranking/manga", headers)
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 3]
```diff
@@ -1,63 +1,330 @@
...
-        title = element.select("h5").text()
-        thumbnail_url = element.select("div > img").attr("data-src")
-        setUrlWithoutDomain(element.attr("href"))
+    override fun popularMangaSelector() = ".ranking-item"
+
+    override fun popularMangaFromElement(element: Element): SManga {
+        return SManga.create().apply {
+            url = element.selectFirst("a")!!.attr("href")
+            title = element.selectFirst(".title-text")!!.text()
+            author = element.selectFirst(".author-link")!!.text()
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Author is not critical, remove non-null assert.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 4]
```diff
@@ -1,63 +1,330 @@
...
 
-    override fun popularMangaFromElement(element: Element) = SManga.create().apply {
-        title = element.select("h5").text()
-        thumbnail_url = element.select("div > img").attr("data-src")
-        setUrlWithoutDomain(element.attr("href"))
+    override fun popularMangaSelector() = ".ranking-item"
+
+    override fun popularMangaFromElement(element: Element): SManga {
+        return SManga.create().apply {
+            url = element.selectFirst("a")!!.attr("href")
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Use:
```suggestion
            setUrlWithoutDomain(element.selectFirst("a")!!.absUrl("href"))
```

With relative URLs you don't have to override `mangaDetailsRequest()`. You would use both `setUrlWithoutDomain()` and `.absUrl()` so Jsoup is responsible of parsing the actual path.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 5]
```diff
@@ -1,63 +1,330 @@
...
-        thumbnail_url = element.select("div.thumb-container img").attr("data-src")
-        setUrlWithoutDomain(element.attr("href"))
+    override fun mangaDetailsParse(document: Document): SManga {
+        val infoElement = document.selectFirst(".series-h-info")!!
+        val updateDateElement = infoElement.selectFirst("series-h-tag-label")
+        return SManga.create().apply {
+            title = infoElement.select("h1 > span")[1]!!.text()
+            author = infoElement.selectFirst(".series-h-credit-user-item > .article-text")!!.text() // TODO: get 脚本/漫画
+            description = infoElement.selectFirst(".series-h-credit-info-text-text > div > p > span > span")!!.text()
+            thumbnail_url = getImageFromElement(document.getElementsByClass("series-h-img").first()!!)
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Not critical, remove non-null assert.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 6]
```diff
@@ -1,63 +1,330 @@
...
-        title = element.select("div.data h3").text()
-        thumbnail_url = element.select("div.thumb-container img").attr("data-src")
-        setUrlWithoutDomain(element.attr("href"))
+    override fun mangaDetailsParse(document: Document): SManga {
+        val infoElement = document.selectFirst(".series-h-info")!!
+        val updateDateElement = infoElement.selectFirst("series-h-tag-label")
+        return SManga.create().apply {
+            title = infoElement.select("h1 > span")[1]!!.text()
+            author = infoElement.selectFirst(".series-h-credit-user-item > .article-text")!!.text() // TODO: get 脚本/漫画
+            description = infoElement.selectFirst(".series-h-credit-info-text-text > div > p > span > span")!!.text()
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Consider something like:
```kt
description = infoElement.selectFirst("#series-explain-area p").text()
```

Use `.wholeText().trim()` if you need to keep line breaks as-is.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 7]
```diff
@@ -1,63 +1,330 @@
...
-    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
-        if (query.isNotEmpty()) {
-            val url = "$baseUrl/search".toHttpUrl().newBuilder().addQueryParameter("q", query)
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        return document.select(chapterListSelector()).mapIndexed { index, element ->
+            chapterFromElement(element).apply {
+                chapter_number = index.toFloat()
+                if (url.isEmpty()) { // Login required
+                    throw Exception("Some chapters don't have url, login and refresh again")
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: User doesn't care about the exact reason. Can simplify:
```suggestion
                    throw Exception("Missing chapters, login and refresh again")
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 8]
```diff
@@ -1,63 +1,330 @@
...
+            }
+        }
+    }
 
-            return GET(url.build(), headers)
+    override fun chapterListSelector() = ".article-ep-list-item-img-link"
+
+    override fun chapterFromElement(element: Element): SChapter {
+        return SChapter.create().apply {
+            url = element.attr("data-href")
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
            setUrlWithoutDomain(element.absUrl("data-href"))
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 9]
```diff
@@ -1,63 +1,330 @@
...
+            name = element.selectFirst(".series-ep-list-item-h-text")!!.text()
+            date_upload = element.selectFirst(".series-ep-list-date-time")!!.attr("datetime").toDate()
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Not critical, remove non-null assert.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 10]
```diff
@@ -1,63 +1,330 @@
...
+
+    override fun pageListParse(document: Document): List<Page> {
+        val pageList = mutableListOf<Page>()
+
+        val viewer = document.selectFirst("#comici-viewer")!!
+        val comiciViewerId = viewer.attr("comici-viewer-id")
+        val memberJwt = viewer.attr("data-member-jwt")
+        val requestUrl = baseUrl.toHttpUrl().newBuilder()
+            .addPathSegment("book")
+            .addPathSegments("contentsInfo")
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
        val requestUrl = "$baseUrl/book/contentsInfo".toHttpUrl().newBuilder()
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 11]
```diff
@@ -1,63 +1,330 @@
...
+            .addQueryParameter("comici-viewer-id", comiciViewerId)
+            .addQueryParameter("user-id", memberJwt)
+            .addQueryParameter("page-from", "0")
+
+        // Initial request to get total pages
+        val initialRequest = GET(requestUrl.addQueryParameter("page-to", "1").build())
+        client.newCall(initialRequest).execute().use { initialResponse ->
+            if (initialResponse.code != 200) {
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Check for `.isSuccessful` instead.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 12]
```diff
@@ -1,63 +1,330 @@
...
+            client.newCall(getAllPagesRequest).execute().use {
+                if (it.code != 200) {
+                    throw Exception("Failed to get page list")
+                }
+                val result = json.parseToJsonElement(it.body.string())
+                val resultJson = result.jsonObject["result"]!!.jsonArray
+                resultJson.forEach { resultJsonElement ->
+                    val jsonObject = resultJsonElement.jsonObject
+                    // Add fragment to let interceptor to descramble the image
+                    val scramble = jsonObject["scramble"]!!.jsonPrimitive.content.drop(1).dropLast(1).replace(", ", "-")
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Use a DTO for this.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 13]
```diff
@@ -1,63 +1,330 @@
...
+                    )
+                }
+            }
+        }
+        return pageList
+    }
+
+    override fun imageRequest(page: Page): Request {
+        val newHeaders = headersBuilder()
+            .set("Referer", baseUrl)
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Browsers format it like:
```suggestion
            .set("Referer", "$baseUrl/")
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 14]
```diff
@@ -1,63 +1,330 @@
...
+            .build()
+        return GET(page.imageUrl!!, newHeaders)
+    }
+
+    private fun imageDescrambler(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val rawRequest = request.newBuilder().url(request.url.newBuilder().fragment(null).build()).build()
+        val response = chain.proceed(rawRequest)
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Fragment is already omitted when sent over the wire, no?
```suggestion
        val response = chain.proceed(request)
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 15]
```diff
@@ -1,63 +1,330 @@
...
+                    (tiles[count].y + 1) * tileHeight,
+                )
+                canvas.drawBitmap(rawImage, srcRect, desRect, null)
+                count++
+            }
+        }
+        return descrambledImg
+    }
+
+    private data class TilePos(val x: Int, val y: Int) // Left-top corner position
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Don't need a data class for this.
```suggestion
    private class TilePos(val x: Int, val y: Int) // Left-top corner position
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 16]
```diff
@@ -1,63 +1,330 @@
...
+    private fun imageDescrambler(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val rawRequest = request.newBuilder().url(request.url.newBuilder().fragment(null).build()).build()
+        val response = chain.proceed(rawRequest)
+
+        if (request.url.fragment.isNullOrEmpty()) {
+            return response
+        }
+
+        val scramble = request.url.fragment!!
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
        val scramble = request.url.fragment
            ?: return response
```
... assuming `fragment` is null when not set.

**Review by vetleledaal — COMMENTED** [review]
Will probably do another round of comments when this is not a draft PR.

**Comment by heddxh** [comment]
Thank you for your detailed review, fixing...

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 4 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Didn't know this before, thank you!

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 1 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Here I find I can get some thing like "2025-03-31 00:00:00" from attr, that is more simple.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 7 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Except throw exception, how can I communicate with UI layer to display snackbar or something to notify user that they need login to see missing chapters?

Can I add somewhat "dummy" url for chapters that need login or behind paywall, and add icons in the chapter title?

Comment (vetleledaal) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Ah, in that case you would use a setting to toggle if paid chapters should be visible. If hidden, the user is not notified on missing chapters. If visible, you show the chapters with 🔒 or similar.

A dummy URL works and just error (with `throw`) if the user does not have access. I think you should use a unique URL for each, otherwise it might mark all locked chapters as read if one of them is read.

Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: OK, I override `pageListRequest` to check if it's a dummy url and throw exception.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/PageResponse.kt [hunk 17]
```diff
@@ -0,0 +1,16 @@
...
+import kotlinx.serialization.Serializable
+
+@Serializable
+data class PageResponse(
+    val totalPages: Int,
+    val result: List<PageResponseResult>,
+)
+
+@Serializable
+data class PageResponseResult(
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/PageResponse.kt]: Don't need data class.
```suggestion
class PageResponseResult(
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ImageDescrambler.kt [hunk 18]
```diff
@@ -0,0 +1,70 @@
...
+     */
+    fun interceptor(chain: Interceptor.Chain): Response {
+        val request = chain.request()
+        val response = chain.proceed(request)
+
+        val scramble = request.url.fragment ?: return response // return if no scramble fragment
+        val tiles = buildList {
+            scramble.split("-").forEachIndexed { index, s ->
+                val scrambleInt = s.toInt()
+                add(index, TilePos(scrambleInt / 4, scrambleInt.mod(4)))
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ImageDescrambler.kt]: Does this not work in Kotlin?
```suggestion
                add(index, TilePos(scrambleInt / 4, scrambleInt % 4))
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 19]
```diff
@@ -1,63 +1,216 @@
...
-        thumbnail_url = element.select("div.thumb-container img").attr("data-src")
-        setUrlWithoutDomain(element.attr("href"))
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        return document.select(chapterListSelector()).mapIndexed { index, element ->
+            chapterFromElement(element).apply {
+                chapter_number = index.toFloat()
+                if (url.isEmpty()) { // need login, set a dummy url and append lock icon for chapter name
+                    val isLock = element.selectFirst(".g-payment-article")?.hasClass("wait-free-enabled") ?: false
+                    url = "$DUMMY_URL_PREFIX-$name"
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Seems like you are using the variable (`name`) before it is set.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 20]
```diff
@@ -1,63 +1,216 @@
...
-        title = element.select("div.data h3").text()
-        thumbnail_url = element.select("div.thumb-container img").attr("data-src")
-        setUrlWithoutDomain(element.attr("href"))
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        return document.select(chapterListSelector()).mapIndexed { index, element ->
+            chapterFromElement(element).apply {
+                chapter_number = index.toFloat()
+                if (url.isEmpty()) { // need login, set a dummy url and append lock icon for chapter name
+                    val isLock = element.selectFirst(".g-payment-article")?.hasClass("wait-free-enabled") ?: false
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
                    val isLock = element.selectFirst(".g-payment-article:has(".wait-free-enabled") ?: false
```
(needs testing)

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 21]
```diff
@@ -1,63 +1,216 @@
...
+    }
+
+    // ========================================= Helper Functions =====================================
+
+    companion object {
+        private const val PUBLISHER = "BUSHIROAD WORKS"
+
+        private val imageUrlRegex by lazy { Regex("^.*?webp") }
+
+        private val DATE_PARSER by lazy { SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ROOT) }
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt:181]: Set timestamp if known.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 22]
```diff
@@ -1,63 +1,216 @@
...
+        return SChapter.create().apply {
+            setUrlWithoutDomain(element.absUrl("data-href"))
+            name = element.selectFirst(".series-ep-list-item-h-text")!!.text()
+            setUploadDate(element.selectFirst(".series-ep-list-date-time"))
+            scanlator = PUBLISHER
+        }
+    }
+
+    override fun pageListRequest(chapter: SChapter): Request {
+        if (chapter.url.startsWith(DUMMY_URL_PREFIX)) {
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Could you use a fragment instead?

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 23]
```diff
@@ -1,63 +1,216 @@
...
-        setUrlWithoutDomain(element.attr("href"))
+    override fun mangaDetailsParse(document: Document): SManga {
+        val infoElement = document.selectFirst(".series-h-info")!!
+        val authorElements = infoElement.select(".series-h-credit-user-item .article-text")
+        val updateDateElement = infoElement.selectFirst(".series-h-tag-label")
+        return SManga.create().apply {
+            title = infoElement.select("h1 > span")[1]!!.text()
+            author = authorElements.joinToString { it.text() }
+            description = infoElement.selectFirst(".series-h-credit-info-text-text p")?.wholeText()?.trim()
+            setImageUrlFromElement(document.getElementsByClass("series-h-img").first())
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
            setImageUrlFromElement(document.selectFirst(".series-h-img"))
```

Probably need to do something about null.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 24]
```diff
@@ -1,63 +1,216 @@
...
+        setUrlWithoutDomain(element.absUrl("href"))
+        title = element.selectFirst(".manga-title")!!.text()
+        setImageUrlFromElement(element)
+    }
+
+    override fun latestUpdatesRequest(page: Int) = GET(baseUrl, headers)
+
+    override fun latestUpdatesNextPageSelector() = null
+
+    override fun latestUpdatesSelector() = "div.feature-list:nth-child(2) > .feature-item"
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Avoid using offset if possible.
```suggestion
    override fun latestUpdatesSelector() = "h2:contains(新) + .feature-list > .feature-item"
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 25]
```diff
@@ -1,63 +1,216 @@
...
-    override fun popularMangaFromElement(element: Element) = SManga.create().apply {
-        title = element.select("h5").text()
-        thumbnail_url = element.select("div > img").attr("data-src")
-        setUrlWithoutDomain(element.attr("href"))
+    override fun mangaDetailsParse(document: Document): SManga {
+        val infoElement = document.selectFirst(".series-h-info")!!
+        val authorElements = infoElement.select(".series-h-credit-user-item .article-text")
+        val updateDateElement = infoElement.selectFirst(".series-h-tag-label")
+        return SManga.create().apply {
+            title = infoElement.select("h1 > span")[1]!!.text()
```
Comment (vetleledaal) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
            title = infoElement.select("h1 > span:not(.g-hidden)")!!.text()
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 23 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: null check is in the helper function

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 22 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: Like this?
```kotlin
url = response.request.url.newBuilder().fragment("$index-$DUMMY_URL_SUFFIX").build().toString()
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 19 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: `chapterFromElement` has set `name` before. Anyway, I will use fragment there.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 20 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: If pure css selector is preferred, then I will change to: `.g-payment-article.wait-free-enabled`

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 21 above)
Comment (heddxh) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt:181]: Sorry I don't get it. I think I have set it at: https://github.com/keiyoushi/extensions-source/pull/9009/files#diff-657823937b2f6cb331c7ab4a536572adb64f19a6db8a0219635f6a33ff728bb2R216

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt (hunk 22 above)
Comment (vetleledaal) [reply src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```kt
val x = baseUrl.toHttpUrl().newBuilder().fragment("$DUMMY_URL_PREFIX-$index").build()
setUrlWithoutDomain(x.toString())

if ("$baseUrl${chapter.url}".toHttpUrl().fragment.startsWith(DUMMY_URL_PREFIX)) {
```

Probably fine as is, since it's just a sentinel value, you are not exactly encoding something that matters.

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 26]
```diff
@@ -1,63 +1,218 @@
...
-        setUrlWithoutDomain(element.attr("href"))
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val document = response.asJsoup()
+        return document.select(chapterListSelector()).mapIndexed { index, element ->
+            chapterFromElement(element).apply {
+                chapter_number = index.toFloat()
+                if (url.isEmpty()) { // need login, set a dummy url and append lock icon for chapter name
+                    val hasLockElement = element.selectFirst(".g-payment-article.wait-free-enabled")
+                    url = response.request.url.newBuilder().fragment("$index-$DUMMY_URL_SUFFIX").build().toString()
+                    println(url)
```
Comment (AwkwardPeak7) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 27]
```diff
@@ -1,63 +1,218 @@
...
+        return SChapter.create().apply {
+            setUrlWithoutDomain(element.absUrl("data-href"))
+            name = element.selectFirst(".series-ep-list-item-h-text")!!.text()
+            setUploadDate(element.selectFirst(".series-ep-list-date-time"))
+            scanlator = PUBLISHER
+        }
+    }
+
+    override fun pageListRequest(chapter: SChapter): Request {
+//        if (chapter.url.startsWith(DUMMY_URL_PREFIX)) {
```
Comment (AwkwardPeak7) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]:
```suggestion
```

File: src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt [hunk 28]
```diff
@@ -1,63 +1,218 @@
...
+    // ========================================= Helper Functions =====================================
+
+    companion object {
+        private const val PUBLISHER = "BUSHIROAD WORKS"
+
+        private val imageUrlRegex by lazy { Regex("^.*?webp") }
+
+        private val DATE_PARSER by lazy { SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.ROOT) }
+
+        private val json: Json by injectLazy()
```
Comment (AwkwardPeak7) [inline src/all/comicgrowl/src/eu/kanade/tachiyomi/extension/all/comicgrowl/ComicGrowl.kt]: you don't need to set and pass it to `parseAs`

**Comment by heddxh** [comment]
Sorry for late update. Now could it be merged?

**Review by AwkwardPeak7 — APPROVED** [review]
