### PR TITLE
Comic Fury: Fix chapterListParse not parsing all pages.

### LINKED ISSUE #14147: Comic Fury: Comics missing if there are more than 4 pages in the page list
### Source information

Comic Fury 1.4.6

### Source language

Multi

### Steps to reproduce

Open a series that has more than 4 pages of comics (e.g. https://comicfury.com/read/normalsville/archive)

### Expected behavior

Comics from all pages should appear in the chapter list.

### Actual behavior

Only comics from pages 1, 2, 3, and the last page will appear.

### Mihon/Mihon fork version

Mihon 0.19.4

### Android version

Android 16

### Other details

This is because the page selector element, which the Comic Fury extension uses to find the URL for each page, gets truncated once the page count exceeds 4. In this instance it leads to all the comics on page 4 being skipped.

Image

### Acknowledgements

- [x] I have searched [existing issues](https://github.com/keiyoushi/extensions-source/issues) both open & closed, and confirm that this is a new unreported issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.19.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated the extension to the latest version (as listed on the [extensions listing](https://keiyoushi.github.io/extensions/) page).
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will correctly fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ColouMods**
Currently, the Comic Fury extension uses the page selector element to fetch the URLs for all chapter pages at once. However this breaks if a series has more than 5 pages of comics, since the element will be truncated (in this example page 4 will be missed).

image

To fix this, I reworked the code for parsing the pages so it now iterates through the pages one at a time, only fetching the URL of the page directly after the current (since that will always be present in the page selector).

Closes #14147

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFury.kt [hunk 1]
```diff
@@ -66,41 +67,46 @@ class ComicFury(
...
         val chapters = mutableListOf<SChapter>()
 
         if (jsp.selectFirst(archiveSelector) != null) {
-            jsp.select(archiveSelector).eachAttr("abs:href").map { url ->
-                chapters.addAll(collect(url))
-                currentPage.select(nextArchivePageSelector).eachAttr("abs:href")
-                    .mapNotNull { nextUrl -> chapters.addAll(collect(nextUrl)) }
+            jsp.select(archiveSelector).eachAttr("abs:href").forEach { url ->
+                val currentPage = client.newCall(GET(url, headers)).execute().asJsoup()
+                chapters.addAll(collect(currentPage))
```
Comment (AwkwardPeak7) [inline src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFury.kt:106]: I haven't looked at the site but shouldn't the collect method get all chapters? why iterate over archiveselector list?

Comment (ColouMods) [reply src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFury.kt:106]: Some series on the site have the list of comic pages directly on the archive page, however other series split the pages into groups (which the site calls 'chapters' but I think are called 'archives' here to avoid confusion with Mihon's chapters - I wasn't the one who named the selectors so I dunno). So for those series you need iterate through list of chapters, _then_ iterate through the list of comics _inside_ those chapters (which is what the collect method does).

Now there _is_ an issue with the way this works (applies to both the existing code and my reworked one) where, presumably, if a series has more than 100 chapters the chapter list also gets split into pages, so this `forEach` would only parse the first page of chapters. I would have fixed this myself, however when I looked on the site I couldn't actually find any series with anywhere close to 100 chapters (though I don't know the site that well either so maybe there are ones out there). I'd basically have to guess how the page is laid out in order to fix it, and I'd have no way to test it to see if it actually works, so I just left it as-is. It'd probably be better to fix in a seperate PR anyway.

**Review by AwkwardPeak7 — APPROVED** [review]
