### PR TITLE
Sixmh: Fix search

### LINKED ISSUE #10050: 6Manhua: no results found
### Source information

6Manhua 1.4.14

### Source language

Chinese

### Steps to reproduce

1. Enter the name (any) into the search box.
2. No results found.

### Expected behavior

The title should appear after searching its name.

### Actual behavior

Shows "No results found" even when the title is confirmed to be on the site. 

### Mihon/Tachiyomi version

1.9.7.3

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by tanaka-shizuku3**
Closes #10050

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/sixmh/src/eu/kanade/tachiyomi/extension/zh/sixmh/SixMH.kt [hunk 1]
```diff
@@ -21,6 +24,11 @@ class SixMH : MCCMSWeb("六漫画", "https://www.liumanhua.com") {
         thumbnail_url = element.selectFirst("img")?.absUrl("src")
     }
 
+    override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
+        val request = super.searchMangaRequest(page, query, filters)
+        return GET(request.url, headers)
```
Comment (stevenyomi) [inline src/zh/sixmh/src/eu/kanade/tachiyomi/extension/zh/sixmh/SixMH.kt:30]:
```suggestion
        // Use mobile user agent
        return GET(request.url, headers)
```

**Review by stevenyomi — APPROVED** [review]
