### PR TITLE
Nekopost search unwanted output when no result fix, also add ability to search with URL

### LINKED ISSUE #12666: Nekopost: Search By URL
### Source name

Nekopost

### Source language

Thai

### Describe your suggested feature

add ability to search by URL 

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #12671: Nekopost Json error shen search result is blank
### Source information

Nekopost

### Source language

Thai

### Steps to reproduce

1search with name that not exist

### Expected behavior

show no out put

### Actual behavior

show json decode error

### Mihon/Tachiyomi version

app.mihon.dev App version: 0.19.3-7480 (5b88f8819, 16, 2025-12-06T16:25:09Z)

### Android version

Android 13

### Other details

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by keegang6705**
Closes #12666
Closes #12671

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt [hunk 1]
```diff
@@ -123,63 +202,42 @@ class Nekopost : HttpSource() {
...
+        val cleanQuery = query.trim()
+        val projectIdRegex = Regex("""nekopost\.net/manga/(\d+)""")
+        val matchResult = projectIdRegex.find(cleanQuery)
+
+        val keyword = if (matchResult != null) {
+            val projectId = matchResult.groupValues[1]
+            try {
+                val response = client.newCall(GET("$projectDataEndpoint/$projectId", commonHeaders)).execute()
+                val projectInfo: RawProjectInfo = json.decodeFromString(response.body.string())
+                projectInfo.projectInfo.projectName
```
Comment (AwkwardPeak7) [inline src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt]: override `fetchSearchManga` and directly return the deeplink result (smanga), instead of simulating a search with fetched name

File: src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt [hunk 2]
```diff
@@ -27,62 +28,138 @@ import java.text.SimpleDateFormat
...
 
-    private val latestMangaEndpoint = "https://api.osemocphoto.com/frontAPI/getLatestChapter/m"
     private val projectDataEndpoint = "https://api.osemocphoto.com/frontAPI/getProjectInfo"
     private val fileHost = "https://www.osemocphoto.com"
 
-    private val existingProject = HashSet<String>()
-    private var firstPageNulled = false
+    private val dateFormat by lazy { SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale("th")) }
+
+    private val commonHeaders by lazy { headersBuilder().build() }
```
Comment (AwkwardPeak7) [inline src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt]: default `headers` value is already this, use that instead

File: src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt [hunk 3]
```diff
@@ -27,62 +28,138 @@ import java.text.SimpleDateFormat
...
+
+    override fun searchMangaParse(response: Response): MangasPage =
+        parseProjectList(response, filterTypes = setOf("m"), hasNextPage = false)
+
+    private fun parseProjectList(
+        response: Response,
+        filterTypes: Set<String>?,
+        hasNextPage: Boolean,
+    ): MangasPage {
+        val projectList: RawProjectSearchSummaryList = json.decodeFromString(response.body.string())
```
Comment (AwkwardPeak7) [inline src/th/nekopost/src/eu/kanade/tachiyomi/extension/th/nekopost/Nekopost.kt]: consider using `keiyoushi.utils.parseAs` and remove usage of direct instance of `json` in this source

**Review by AwkwardPeak7 — CHANGES_REQUESTED** [review]

**Comment by keegang6705** [comment]
i found bug on api response parsing system let me fix that first

**Review by AwkwardPeak7 — APPROVED** [review]
