### PR TITLE
Quantum Scans/Toon: Redesign

### LINKED ISSUE #9390: Quantum Scans not loading specific Manhwa
### Source information

Quantum Scans 1.4.38 

### Source language

English 

### Steps to reproduce

1. browse source (latest / popular same issue) 
2. Search for - Unrivaled Spear Demon
3. Nothing found 

### Expected behavior

Unrivaled Spear Demon - should actually be found. 

### Actual behavior

Search results (or manual search) the title - Unrivaled Spear Demon - not able to find. 

### Mihon/Tachiyomi version

Mihon 0.18.0

### Android version

Android 14

### Other details

If you open up webview and look for the title - Unrivaled Spear Demon - is there and not locked up behind paywall.

Tried advanced settings:
Clear cookies
Clear WebView data

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #9514: Quantum Scans: New domain URL & theme
### Source information

Quantum Scans 1.4.38 

### Source language

English 

### Steps to reproduce

1. Open up the extension
2. See 404 and 500 HTTP error.  

WebView is working fine. 

Image

Image

Image

### Expected behavior

Load Manhwa / Manga. 

### Actual behavior

I am greeted with 404 and 500 HTTP error. 

### Mihon/Tachiyomi version

Mihon 0.18.0

### Android version

Android 14

### Other details

First happened this:
https://github.com/keiyoushi/extensions-source/issues/9390

And now this here... 

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by manti-X**
Closes #9514 
Closes #9390 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/GenreDto.kt [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package eu.kanade.tachiyomi.extension.en.quantumscans
+
+import kotlinx.serialization.Serializable
+
+@Serializable
+data class GenreDto(val id: Int, val name: String)
```
Comment (stevenyomi) [inline src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/GenreDto.kt]:
```suggestion
class GenreDto(val id: Int, val name: String)
```

File: src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt [hunk 2]
```diff
@@ -1,20 +1,150 @@
...
+
+        val urlRegex = Regex("""(https?://[^"]+?\.(?:jpg|jpeg|png|webp))""")
+
+        val imageUrls = urlRegex.findAll(scriptContent)
+            .map { it.groupValues[1].replace("\\\\", "") }
+            .filter { it.contains("/series/") || it.contains("/uploads/") }
+            .distinct()
+            .toList()
+
+        if (imageUrls.isEmpty()) {
```
Comment (stevenyomi) [inline src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt]: Invert this condition so the `return imageUrls...` happens here.

File: src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt [hunk 3]
```diff
@@ -1,20 +1,150 @@
...
+                    .map { Pair(it.name, it.id.toString()) }
+            } catch (e: Throwable) {
+            } finally {
+                fetchGenresAttempts++
+            }
+        }
+    }
+
+    override fun getFilterList(): FilterList {
+        if (genresList.isEmpty() && fetchGenresAttempts == 0) {
```
Comment (stevenyomi) [inline src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt]: You probably want `fetchGenresAttempts < 3` here and remove the check in `fetchGenres()`.

File: src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt (hunk 2 above)
Comment (manti-X) [reply src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt]: Switched to a better parser

**Comment by stevenyomi** [comment]
@manti-X Remember to mark PR as ready for review after you address the comments.

File: src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt [hunk 4]
```diff
@@ -1,20 +1,132 @@
...
+    override fun latestUpdatesRequest(page: Int): Request {
+        val url = "$apiUrl/api/query".toHttpUrl().newBuilder().apply { // 'query' instead of 'posts'
+            addQueryParameter("page", page.toString())
+            addQueryParameter("perPage", "18")
+            addQueryParameter("orderBy", "updatedAt")
+        }.build()
+        return GET(url, headers)
+    }
+
+    override fun pageListParse(response: Response): List<Page> {
```
Comment (stevenyomi) [inline src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt]: The result seems to be easier to parse (grepping `{}` objects per line) when you add header `rsc: 1`.

The data can be inspected with https://rsc-parser.vercel.app/

File: src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt [hunk 5]
```diff
@@ -1,20 +1,123 @@
...
+    override fun pageListRequest(chapter: SChapter): Request {
+        return GET(baseUrl + chapter.url, headersBuilder().add("rsc", "1").build())
+    }
+
+    override fun pageListParse(response: Response): List<Page> {
+        return response.body.string().lines()
+            .mapNotNull { line ->
+                val jsonStartIndex = line.indexOf('{').takeIf { it != -1 } ?: return@mapNotNull null
+                val jsonString = line.substring(jsonStartIndex)
+                runCatching { jsonString.parseAs<PageDto>().takeIf { it.url.isNotEmpty() } }.getOrNull()
```
Comment (stevenyomi) [inline src/en/quantumscans/src/eu/kanade/tachiyomi/extension/en/quantumscans/QuantumScans.kt]: Use a plain `try` block.

**Review by stevenyomi — APPROVED** [review]
