### PR TITLE
zaimanhua: update scanlator assignment logic & fix webview url

### LINKED ISSUE #9794: 再漫画/Zaimanhua: 某些漫画无限重命名/Infinite Renaming Loop in Certain Comic
### Source information

zaimanhua

### Source language

Chinese

### Steps to reproduce

1.《超萌吸血鬼不能好好吸血》
2.下载单行本1-7卷

### Expected behavior

1.其中1、2、3、4、7卷会加前缀“单行本_”
2.再次刷新列表
3.文件名应该不变化。

### Actual behavior

文件名被自动重命名为“第X卷”，前缀被删除。重新下载无法解决该问题，只会被重命名后加(2)一类的后缀。

### Mihon/Tachiyomi version

r7308

### Android version

Android 15

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by zhongfly**
fix #9794

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt [hunk 1]
```diff
@@ -55,7 +55,7 @@ class ChapterGroupDto(
         val current = System.currentTimeMillis()
         return data.map {
             it.toSChapterInternal().apply {
-                if (!isDefaultGroup) scanlator = groupName
+                scanlator = if (!isDefaultGroup) groupName else ""
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt]: Prepend group name to chapter name instead, like DMZJ. Set `scanlator` to an empty string.

https://github.com/keiyoushi/extensions-source/blob/d33db2f36816cda3869a55b776cb9c71bb2a88f3/src/zh/dmzj/src/eu/kanade/tachiyomi/extension/zh/dmzj/ApiV4.kt#L105

Context: https://github.com/keiyoushi/extensions-source/pull/5092#discussion_r2232701227

Comment (zhongfly) [reply src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt]: If change to `"$groupName: $name"`,and mihon still have the bug
All the comics that have already been added to the library will change like this, which is terrible:
image

Comment (zhongfly) [reply src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt]: On the other hand, I think it would be convenient to put the categories into the `scanlator` so that we can filter to view only a certain category, and a bunch of chapter names won't have the same “Other Series: xxxxx” at the beginning.

Comment (stevenyomi) [reply src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/ZaimanhuaDto.kt]: Then just put "连载" for the default group and you don't even need to worry about the empty scanlator thing. As a benefit, you can even filter out the default group using the scanlator filter.

File: src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt [hunk 2]
```diff
@@ -125,6 +126,11 @@ class Zaimanhua : HttpSource(), ConfigurableSource {
     }
 
     // Detail
+    // webview "/details/mangaId"
+    override fun getMangaUrl(manga: SManga): String {
+        return "$baseUrl/details/${manga.url}"
```
Comment (stevenyomi) [inline src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]:
```suggestion
        return "$mobileBaseUrl/pages/comic/detail?id=${manga.url}"
```

Comment (zhongfly) [reply src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]: it's same thing

Comment (stevenyomi) [reply src/zh/zaimanhua/src/eu/kanade/tachiyomi/extension/zh/zaimanhua/Zaimanhua.kt]: It's to avoid redirection on mobile devices.

**Review by stevenyomi — APPROVED** [review]
