### PR TITLE
SussyScan: Fix load mangas

### LINKED ISSUE #2869: Problemas na extensão sussy scan
### Source information

Sussy scan

### Source language

Português brasil

### Steps to reproduce

Os mangás não carregam e pede para verificar o site na webview mais a webview está funcionando bem

### Expected behavior

Os mangás deveriam carregar para ler

### Actual behavior

E não está funcionando

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Other details

Screenshot_20240506-115905

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by choppeh**
Closes #2869

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Comment by vetleledaal** [comment]
You can still see the dateFormat under manga details -> read more -> you may also like. It looks like this:
image

**Comment by ttony2chopper** [comment]
> You can still see the dateFormat under manga details -> read more -> you may also like. It looks like this: image

The source hides the date. It seems that the manga have been reuploaded, so there is still a relative date.

File: src/pt/sussyscan/src/eu/kanade/tachiyomi/extension/pt/sussyscan/SussyScan.kt [hunk 1]
```diff
@@ -9,13 +9,14 @@ class SussyScan : Madara(
...
 ) {
     override val client = super.client.newBuilder()
         .rateLimit(2)
         .build()
 
     override val useNewChapterEndpoint = true
 
-    override val mangaSubString = "sus"
+    // There's no manga thumbnail in manga page, keeps thumbnail from popular, latest and search
+    override val mangaDetailsSelectorThumbnail = "#thumbnail-empty"
```
Comment (AwkwardPeak7) [inline src/pt/sussyscan/src/eu/kanade/tachiyomi/extension/pt/sussyscan/SussyScan.kt]: you can get the thumbnail from `og:image` in `<head>`, [like so](https://github.com/keiyoushi/extensions-source/blob/67e57a9817ce66dc9a678e7a8a81976e3e61a922/src/tr/mangaoku/src/eu/kanade/tachiyomi/extension/tr/mangaoku/MangaOku.kt#L16-L26)

**Review by AwkwardPeak7 — APPROVED** [review]
