### PR TITLE
Flame Comics: fix chapters naming

### LINKED ISSUE #6384: Flame Comics: chapter name doesn't match site
### Source information

Flame Comics 1.4.36

### Source language

English

### Steps to reproduce

1. Open any manga having chapters with non-integer chapter number, e.g. "The 31st Piece Overturns the Board" with "Chapter 1.5"

### Expected behavior

1. Show actual name
2. Store downloaded chapter under actual real name

### Actual behavior

1. Shows incorrect name - "Chapter 1" instead of "Chapter 1.5"
2. While downloaded real "Chapter 1" is being overwritten with wrong "Chapter 1(.5)"

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by mralien**
Closes #6384 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt [hunk 1]
```diff
@@ -223,7 +225,7 @@ class FlameComics : HttpSource() {
                 chapter_number = chapter.chapter.toFloat()
                 date_upload = chapter.release_date * 1000
                 name = buildString {
-                    append("Chapter ${chapter.chapter.toInt()} ")
+                    append("Chapter ${chapterNumberFormat.format(chapter.chapter)} ")
```
Comment (vetleledaal) [inline src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: Wouldn't `chapter.chapter.toString().removeSuffix(".0")` be better?

Comment (mralien) [reply src/en/flamecomics/src/eu/kanade/tachiyomi/extension/en/flamecomics/FlameComics.kt]: I guess it would. Didn't even think about it in this case. Thanks for suggestion.

Updated PR

**Review by vetleledaal — APPROVED** [review]
