### PR TITLE
AllManga: Fix manga and chapter URLs

### LINKED ISSUE #6682: Allmanga: manga pages url change
### Source information

Allmanga 1.4.7

### Source language

English

### Steps to reproduce

1. Open Chapters or the manga page
2. Pages dont load
3. Open webview (error pages shows)

### Expected behavior

See the manga pages load

### Actual behavior

Pages dont load
Also there's a error page on webview

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 10

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by Dr1ks**
Closes #6682 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/allanime/src/eu/kanade/tachiyomi/extension/en/allanime/Dto.kt [hunk 1]
```diff
@@ -53,7 +53,7 @@ class SearchManga(
 ) {
     fun toSManga() = SManga.create().apply {
         title = englishName ?: name
-        url = "/manga/$id/${name.titleToSlug()}"
```
Comment (AwkwardPeak7) [inline src/en/allanime/src/eu/kanade/tachiyomi/extension/en/allanime/Dto.kt]: this would break the "in library mark", override `getMangaUrl` and `getChapterUrl` instead to return correct webview/share urls

**Review by AwkwardPeak7 — APPROVED** [review]
