### PR TITLE
Fix MagazinePocket

### LINKED ISSUE #8917: Magazine Pocket: `No results found` error / website theme change
### Source information

Magazine Pocket 1.4.6

### Source language

Japanese

### Steps to reproduce

1. Install source
2. Open source

### Expected behavior

List of mangas loads up.

### Actual behavior

Shows "No results found", although the site is available in WebView.

### Mihon/Tachiyomi version

0.18.0

### Android version

Bluestacks - Android 9

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by manti-X**
Closes #8917 

Similar to KManga, just with different selectors, etc...

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt [hunk 1]
```diff
@@ -1,36 +1,454 @@
...
+    override val versionId = 2
+
+    private val apiUrl = "https://api.pocket.shonenmagazine.com"
+    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.JAPAN)
+    private val pageLimit = 25
+
+    override fun headersBuilder() = super.headersBuilder()
+        .add("Referer", "$baseUrl/")
+
+    override val client = super.client.newBuilder()
```
Comment (AwkwardPeak7) [inline src/ja/magazinepocket/src/eu/kanade/tachiyomi/extension/ja/magazinepocket/MagazinePocket.kt]:
```suggestion
    override val client = network.cloudflareClient.newBuilder()
```

**Review by AwkwardPeak7 — APPROVED** [review]
