### PR TITLE
Manhuarm Fixes

### LINKED ISSUE #11040: Manhuarm: Fix bad base64
### Source information

Manhuarm 1.4.48

### Source language

English

### Steps to reproduce

1. download manhuaarms
3. turn on flaresolver
4. go to browse
5. click a manhua
6. then click a chapter 

### Expected behavior

should load up the chapter

### Actual behavior

it shows bad base 64 for some manhuas for example I’ve Been Invincible For A Long Time and Prices Depreciated, And I Became The World’s Richest Person is having this issue and some of the other manhuas on the site

### Mihon/Tachiyomi version

Suwayomi Server preview version  v2.1.1960

### Android version

N/A

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by fadiajlil2099**
Closes https://github.com/keiyoushi/extensions-source/issues/11040 , https://github.com/keiyoushi/extensions-source/issues/11104 ,https://github.com/keiyoushi/extensions-source/issues/11258

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

**Review by AwkwardPeak7 — DISMISSED** [review]

**Comment by choppeh** [comment]
@fadiajlil2099 Could you share a manhwa and the chapter with the problem?

**Comment by fadiajlil2099** [comment]
@choppeh 
 I’ve Been Invincible For A Long Time  around chapters 571 and before that 
 and Prices Depreciated, And I Became The World’s Richest Person  all of it
 but as of this moment It seem like all chapters are not loading from either the original extension or the one with my changes maybe they changed something again or it's just my network, if you can check and see if the original is loading chapters fine if not when i have time I will try to fix it.

**Comment by fadiajlil2099** [comment]
I have updated (#manga-ocr-display-script-js-extra) to ("script") which fixed the new loading of chapters issues caused by site update

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmDto.kt [hunk 1]
```diff
@@ -15,29 +13,58 @@ import kotlinx.serialization.json.jsonArray
...
+            val decoded = Base64.decode(trimmedData, Base64.DEFAULT).toString(Charsets.UTF_8)
+
+            // Validate that decoded content is valid JSON
+            if (decoded.isBlank() || decoded.trim().isEmpty()) {
+                return@lazy "[]"
+            }
+
+            decoded
+        } catch (e: IllegalArgumentException) {
+            "[]"
```
Comment (choppeh) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmDto.kt]:
```suggestion
```

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmDto.kt [hunk 2]
```diff
@@ -15,29 +13,58 @@ import kotlinx.serialization.json.jsonArray
...
+
+            // Validate Base64 format (only contains valid Base64 characters)
+            if (!trimmedData.matches(Regex("^[A-Za-z0-9+/]*={0,2}$"))) {
+                return@lazy "[]"
+            }
+
+            val decoded = Base64.decode(trimmedData, Base64.DEFAULT).toString(Charsets.UTF_8)
+
+            // Validate that decoded content is valid JSON
+            if (decoded.isBlank() || decoded.trim().isEmpty()) {
```
Comment (choppeh) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmDto.kt]:
```suggestion
            if (decoded.isBlank()) {
```

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmDto.kt [hunk 3]
```diff
@@ -47,59 +74,108 @@ data class Dialog(
...
     } ?: text
+
     val centerY get() = height / 2 + y
     val centerX get() = width / 2 + x
 }
 
 private object DialogListSerializer :
     JsonTransformingSerializer<List<Dialog>>(ListSerializer(Dialog.serializer())) {
+
     override fun transformDeserialize(element: JsonElement): JsonElement {
```
Comment (choppeh) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/ManhuarmDto.kt:51]: There are no errors in Serializer. The main problem with serialization is invalid JSONs coming from the source itself.

Ex:
Source: https://manhuarm.com/manga/i-was-already-invincible/chapter-185/

WwogIHsKICAgICJpbWFnZSI6ICJzcGxpdF8wMDYud2VicCIsCiAgICAidGV4dHMiOiBbCiAgICAgIHsKICAgICAgICAiYm94IjogWwogICAgICAgICAgNDc4LAogICAgICAgICAgMTcxNCwKICAgICAgICAgIDIzNiwKICAgICAgICAgIDEzNwogICAgICAgIF0sCiAgICAgICAgInRleHQiOiAiRm9yZ2V0IGl0LCBjaGVlcnMgdG8gdGhhdCEiCiAgICAgIH0KICAgIF0KICB9LAogIHsKICAgICJpbWFnZSI6ICJzcGxpdF8wMDcud2VicCIsCiAgICAidGV4dHMiOiBbCiAgICAgIHsKICAgICAgICAiYm94IjogWwogICAgICAgICAgNDQ1LAogICAgICAgICAgNzkzLAogICAgICAgICAgMjYxLAogICAgICAgICAgNjMKICAgICAgICBdLAogICAgICAgICJ0ZXh0IjogIlRoaXMhIFRoaXM…xsIGJlIGxlZnQgdG8gWW91ciBNYWplc3R5LiIKICAgICAgfQogICAgXQogIH0sCiAgewogICAgImltYWdlIjogInNwbGl0XzAxMC53ZWJwIiwKICAgICJ0ZXh0cyI6IFsKICAgICAgewogICAgICAgICJib3giOiBbCiAgICAgICAgICA0NTAsCiAgICAgICAgICAxNjA2LAogICAgICAgICAgMjk5LAogICAgICAgICAgMjAwCiAgICAgICAgXSwKICAgICAgICAidGV4dCI6ICJTZW5pb3IgWWUgZGlkIG5vdCBhYnNvcmIgdGhlIHNwaXJpdHVhbCBlbmVyZ3kgb2YgdGhlIGltcGVyaWFsIGNhcGl0YWwgZm9yIGhpcyBvd24gY3VsdGl2YXRpb24hIgogICAgICB9CiAgICBdCiAgfSwKICB7CiAgICAiaW1hZ2UiOiAic3BsaXRfMDI0LndlYnAiLAogICAgInRleHRzIjogW10KICB9Cl0=

Decode the above base64 at https://www.base64decode.org/
And use this site for validation at: https://jsonformatter.curiousconcept.com/#

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt [hunk 4]
```diff
@@ -159,9 +159,9 @@ class Manhuarm(
     override fun pageListParse(document: Document): List<Page> {
         val pages = super.pageListParse(document)
         val chapterId = document.selectFirst("#wp-manga-current-chap")!!.attr("data-id")
-        val nonce = document.selectFirst("#manga-ocr-display-script-js-extra")!!.data().let {
-            NONCE_REGEX.find(it)!!.groupValues.last()
-        }
+        val nonce = document.select("script").firstOrNull { it.html().contains("const nonce") }?.let {
+            NONCE_REGEX.find(it.html())?.groupValues?.get(1)
+        } ?: "18b0e544f4" // fallback nonce from site reference
```
Comment (choppeh) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt]: throw an exception here, the request cannot be performed without a valid nonce

File: src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt [hunk 5]
```diff
@@ -159,9 +159,9 @@ class Manhuarm(
     override fun pageListParse(document: Document): List<Page> {
         val pages = super.pageListParse(document)
         val chapterId = document.selectFirst("#wp-manga-current-chap")!!.attr("data-id")
-        val nonce = document.selectFirst("#manga-ocr-display-script-js-extra")!!.data().let {
-            NONCE_REGEX.find(it)!!.groupValues.last()
-        }
+        val nonce = document.select("script").firstOrNull { it.html().contains("const nonce") }?.let {
+            NONCE_REGEX.find(it.html())?.groupValues?.get(1)
```
Comment (choppeh) [inline src/all/manhuarm/src/eu/kanade/tachiyomi/extension/all/manhuarm/Manhuarm.kt]: The regex (NONCE_REGEX) needs to be updated

**Comment by choppeh** [comment]
The popular and latest doesn't work. You need to update the selectors

**Comment by fadiajlil2099** [comment]
@choppeh 
I have tried to fix the issues that you stated to my best, since I'm still new to kotlin i may overcomplicated some parts or missed some minor thing, I tried to fix this extension because some of my favorite manhua are here and since it broke I tried to fix it my self and when it worked i though i may as well create a pr to help other.
as of now I have updated the nonce regex , fixed The popular and latest doesn't work, and also added a custom user agent setting for the extension since some time it will need a specific one to work but that user agent can cause loop in other extensions.
so thank you for been patient and taking time to review the code.

**Comment by AwkwardPeak7** [comment]
@choppeh

**Comment by choppeh** [comment]
lgtm, but  I recommend changing the ```.rateLimit(3)``` to ```.rateLimit(2, 1)```. This source is slow, and I think it's better to reduce the number of requests.

**Comment by fadiajlil2099** [comment]
i have changed the ratelimit to (2, 1)

**Review by AwkwardPeak7 — APPROVED** [review]
