### PR TITLE
Mana/newtoki: add referer

### LINKED ISSUE #1242: Not loading Images ( Newtoki)
### Source information

Newtoki 1.4.29

### Source language

Korean

### Steps to reproduce

Solve captcha
Click any chapter (Old and New)
It says no image

### Expected behavior

Can load images 

### Actual behavior

Screenshot_2024-02-14-02-38-54-05_afd66b7916d19a60815f56273408b73e

### Mihon/Tachiyomi version

0.16.0

### Android version

Android 10

### Other details

Webview is okay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Secozzi**
Closes #1242

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/ManaToki.kt [hunk 1]
```diff
@@ -18,6 +18,9 @@ object ManaToki : NewToki("ManaToki", "comic", manaTokiPreferences) {
 
     override val baseUrl get() = "https://$MANATOKI_PREFIX$domainNumber.net"
 
+    override fun headersBuilder() = super.headersBuilder()
+        .add("Referer", "$baseUrl/")
+
```
Comment (beer-psi) [inline src/ko/newtoki/src/eu/kanade/tachiyomi/extension/ko/newtoki/ManaToki.kt]:
```suggestion
```

No need when you've already added referer to the base `NewToki` class.

**Review by beer-psi — CHANGES_REQUESTED** [review]

**Review by stevenyomi — APPROVED** [review]

**Comment by jaenihan** [comment]
Does this fix the issue? Would I have to do something to update?

**Comment by Secozzi** [comment]
Yes, you just need to update your newtoki extension
