### PR TITLE
west manga (id): update for new site

### LINKED ISSUE #9281: West Manga Not Showing Any Manga
### Source information

West Manga 1.4.35

### Source language

Indonesia

### Steps to reproduce

1. Open West Manga

### Expected behavior

When open West Manga it should show bunch of manga, That's how mihon works duh

### Actual behavior

And now it doesn't bring up any manga at all

### Mihon/Tachiyomi version

0.18.0

### Android version

Android 11

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by AwkwardPeak7**
closes #9281

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt [hunk 1]
```diff
@@ -1,53 +1,213 @@
...
-    override val hasProjectPage = true
+    private fun apiRequest(url: HttpUrl): Request {
+        val timestamp = (System.currentTimeMillis() / 1000).toString()
+        val message = "wm-api-request"
+        val key = timestamp + "GET" + url.encodedPath + accessKey + secretKey
+        val mac = Mac.getInstance("HmacSHA256")
+        val secretKeySpec = SecretKeySpec(key.toByteArray(Charsets.UTF_8), "HmacSHA256")
+        mac.init(secretKeySpec)
+        val hash = mac.doFinal(message.toByteArray(Charsets.UTF_8))
+        val signature = hash.joinToString("") { "%02x".format(it) }
```
Comment (vetleledaal) [inline src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt:222]: More Kotlin-ish?
```suggestion
        val secretKeySpec = SecretKeySpec(key.toByteArray(Charsets.UTF_8), "HmacSHA256")
        val signature = Mac.getInstance("HmacSHA256")
            .init(secretKeySpec)
            .doFinal(message.toByteArray(Charsets.UTF_8))
            .joinToString("") { "%02x".format(it) }
```

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt [hunk 2]
```diff
@@ -1,53 +1,213 @@
...
-            thumbnail_url = seriesDetails.select(seriesThumbnailSelector).imgAttr()
+        return apiRequest(url)
+    }
+
+    override fun getChapterUrl(chapter: SChapter): String {
+        val slug = "$baseUrl${chapter.url}".toHttpUrl().pathSegments[0]
+        val url = baseUrl.toHttpUrl().newBuilder().apply {
+            addPathSegment("view")
+            addPathSegment(slug)
+        }.build()
```
Comment (vetleledaal) [inline src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt]: I don't think you need `.apply` here. Static string can also be moved:
```suggestion
        val url = "$baseUrl/view".toHttpUrl().newBuilder()
            .addPathSegment(slug)
            .build()
```
or:
```suggestion
        val url = baseUrl.toHttpUrl().newBuilder()
            .addPathSegment("view")
            .addPathSegment(slug)
            .build()
```

The same can be said for `pageListRequest()`.

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt [hunk 3]
```diff
@@ -1,53 +1,213 @@
...
+
+    override fun chapterListRequest(manga: SManga) =
+        mangaDetailsRequest(manga)
+
+    override fun chapterListParse(response: Response): List<SChapter> {
+        val data = response.parseAs<Data<Manga>>().data
+
+        return data.chapters.map {
+            SChapter.create().apply {
+                url = "/${it.slug}/"
```
Comment (vetleledaal) [inline src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt]: Assuming slug does not contain reserved characters. Either:
\- encode with `HttpUrlBuilder`
or
\- simplify `pageListRequest()` and `getChapterUrl()`

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt [hunk 4]
```diff
@@ -1,53 +1,213 @@
...
+                    "KR" -> add("Manhwa")
+                }
+                if (data.color) {
+                    add("Colored")
                 }
+                data.genres.forEach { add(it.name) }
+            }.joinToString()
+            description = buildString {
+                append(
+                    Jsoup.parseBodyFragment(data.synopsis).wholeText(),
```
Comment (vetleledaal) [inline src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt]: Consider trimming. `.wholeText()` does not automatically trim like `.text()`.

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt [hunk 5]
```diff
@@ -1,53 +1,213 @@
...
+    }
+
+    override fun mangaDetailsParse(response: Response): SManga {
+        val data = response.parseAs<Data<Manga>>().data
+
+        return SManga.create().apply {
+            // old urls compatibility
+            url = "/manga/${data.slug}/"
+            title = data.title
+            thumbnail_url = data.cover
```
Comment (vetleledaal) [inline src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt:129]: Is the returned URL always absolute?

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt (hunk 1 above)
Comment (AwkwardPeak7) [reply src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt:222]: these are java methods so can't be chained

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt (hunk 3 above)
Comment (AwkwardPeak7) [reply src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt]: saved like this for old url compatibility, and it should correctly be encoded in the `pageListRequest` no?

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt (hunk 5 above)
Comment (AwkwardPeak7) [reply src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt:129]: yes, on a different baseurl/cdn

File: src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt (hunk 3 above)
Comment (vetleledaal) [reply src/id/westmanga/src/eu/kanade/tachiyomi/extension/id/westmanga/WestManga.kt]: If the slug includes `/` it will not extract the slug correctly in the other functions. Probably something similar goes for `?#&%`
