### PR TITLE
Kagane: Add excluded genres & Fix chapter number

### LINKED ISSUE #11275: Kagane chapter number
### Source information

Kagane 1.4.8

### Source language

English

### Steps to reproduce

1. open title with chapter number not same as chapter id number. like `6. ch 3.2  `
2a. display chapter number
2b. tracker after read
2c. when migrate with more chapter number

### Expected behavior

display, track,migrate with ch number correctly

### Actual behavior

a. display chapter number instead of `ch 3.2` its `ch 6`
b. tracker after read is wrong
c. when migrate with more chapter number it detect it wrong/bigger number

### Mihon/Tachiyomi version

Tachiyomi SY r583

### Android version

A14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #11278: Kagane : Genre preference filter
### Source name

Kagane

### Source language

English 

### Describe your suggested feature

On their website we can choose some genre that can be blacklisted from the Home page / Recent Update / Popular.

Image

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by cuong-tran**
Close #11278
Close #11275

**Chapter number**: `number_sort` from DTO is not actual chapter number.

References for chapter number:
|                             |   Chapter title has number  |   Order number is matching with chapter title  |   Decimal chapter number is matching  |   Prologue chapter number is matching  |                                                              |                                                                                                                                                                                                                                                                                                                                            |
|-----------------------------|-----------------------------|------------------------------------------------|---------------------------------------|----------------------------------------|--------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|   Asura Scans               |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/3YAB5O0FO1QWFXEI9GN2W7JSG5   https://kagane.org/series/3SAU5U0FO7RD46LJ5GN2C7CSA5                                                                                                                                                                                                                              |
|   BookLive                  |   Yes                       |   Yes                                          |                                       |                                        |                                                              |   https://kagane.org/series/38AEODWU7F9YZRG1N9COLGMS65                                                                                                                                                                                                                                                                                     |
|   Comikey                   |   Yes                       |   No                                           |   No                                  |                                        |   Use title                                                  |   https://kagane.org/series/3PZGSA8C2177TL5994K0IKORX5   https://kagane.org/series/3HZXSX8C2O7EIAM9W4K0FKFRP5                                                                                                                                                                                                                              |
|   DENPA BOOKS               |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3SAIPRGUUFFRNFZXNMCYZHQSA5   https://kagane.org/series/3EAMQATU3OSOXPWKW5CLIIUSM5                                                                                                                                                                                                                              |
|   Dark Horse Comics         |   Yes                       |   Yes                                          |   -                                   |   No                                   |   Use order_number                                           |   https://kagane.org/series/32AR1U4UMUI3241ACEC6C3ZS05                                                                                                                                                                                                                                                                                     |
|   Day Comics                |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/35ZXCMSIXHI6KC4APPQKUUFR35   https://kagane.org/series/38ZSDR3EIVC6DV4UDAM5ZVAR65   https://kagane.org/series/3AZ3CPSIX9I9LD7A7PQKXU1RI5                                                                                                                                                                       |
|                             |                             |                                                |                                       |                                        |   Chapter got reset with season 2                            |   https://kagane.org/series/3RZ4CAGI5R6DIAL8Z7QYIU2RZ5                                                                                                                                                                                                                                                                                     |
|   Digital Manga             |   Yes                       |   Yes                                          |   Yes                                 |   -                                    |                                                              |   https://kagane.org/series/38AWQWMUCJN7WO5FRUCEEIES65                                                                                                                                                                                                                                                                                     |
|   Diva Scans                |   Yes                       |   Yes                                          |   No decimal chapters found           |   Yes                                  |                                                              |   https://kagane.org/series/3UAURAQUUDX6NF4PLMCIIJCSC5                                                                                                                                                                                                                                                                                     |
|   EZ Manga                  |   Yes                       |   Yes                                          |   Not found                           |   Not Found                            |                                                              |   https://kagane.org/series/3GA5TG1XTJNX02FFRLF3OL3SO5                                                                                                                                                                                                                                                                                     |
|   FAKKU                     |   Yes                       |   Yes                                          |   Yes                                 |   None                                 |                                                              |   https://kagane.org/series/3JAMQLTUPJMFGYNERHCLTIUSR5                                                                                                                                                                                                                                                                                     |
|   Flame Comics              |   No                        |   Yes                                          |                                       |                                        |   Use order_number                                           |   https://kagane.org/series/3OAB5APFAJZSOGARRSNHI7JSW5   https://kagane.org/series/3IA85LPFAYZ6QI4RGSNHT76SQ5   https://kagane.org/series/3YAJ5CPFAUZCPHKRCSNHK7RSG5   https://kagane.org/series/3XAC5YPFAOZ7PH5RWSNHG7KSF5                                                                                                                |
|   Grim Scans                |   Yes                       |   Mostly                                       |   No                                  |   Yes                                  |   Use title                                                  |   https://kagane.org/series/3IA26KUVSODH91PVWKDMS80SQ5   https://kagane.org/series/3BAE6HUVSJDG91OVRKDMP8MSJ5                                                                                                                                                                                                                              |
|   Hive Toons                |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3VAO60UVD1EB13JW9VDM88WSD5                                                                                                                                                                                                                                                                                     |
|   INKR Comics               |   Some                      |   No                                           |   None                                |   No                                   |   This is fucked up, it mix all kind, even   Use title       |   https://kagane.org/series/3GZ0L2KAA8KAUMIC6SIC0D8RO5   https://kagane.org/series/3GZYLJKAA2KWUMEC0SICRDGRO5   https://kagane.org/series/3GZKLHKAAEKXUMFCMSICPDSRO5   https://kagane.org/series/34ZPL7KAA8KWUMEC6SIC5DXR25   https://kagane.org/series/3HZ2LGKAAAKYUMGCISICOD0RP5   https://kagane.org/series/3KZILKKAAKKYUMGCSSICSDQRS5  |
|   Irodori Comics            |   Yes                       |   Yes                                          |   None                                |   None                                 |                                                              |                                                                                                                                                                                                                                                                                                                                            |
|   J-Novel Club              |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3UAUQX4U0DPD57LHL2C6FICSC5                                                                                                                                                                                                                                                                                     |
|   Kana                      |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3RAM1VCUUFRKKCSJNMCUD3USZ5                                                                                                                                                                                                                                                                                     |
|   Kenscans                  |   Yes                       |   Yes                                          |   -                                   |   -                                    |                                                              |   https://kagane.org/series/3PA865TVOF8DNFL0NGDL386SX5                                                                                                                                                                                                                                                                                     |
|   Kodansha Comics           |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3EAX0LJU7OAPKCXSW9CBT2FSM5   https://kagane.org/series/39A81RZUGFEP35XWNYCRZ36S75                                                                                                                                                                                                                              |
|   Kodoku Studio             |   Yes                       |   Yes                                          |   None                                |   None                                 |                                                              |                                                                                                                                                                                                                                                                                                                                            |
|   Lezhin                    |   Yes                       |   Yes                                          |                                       |   No                                   |   Use title                                                  |   https://kagane.org/series/3IZ8TXKC4YZ0TL8RG6KCFL6RQ5                                                                                                                                                                                                                                                                                     |
|   Luna Toons                |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/3JAV6H7VLJC7PH5URDD9P8DSR5                                                                                                                                                                                                                                                                                     |
|   Madarascans               |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/3DA153IV5UFW46EXC7DA179SL5                                                                                                                                                                                                                                                                                     |
|   MangaDex                  |   No                        |                                                |   Actual decimal is good              |                                        |   Use order_number                                           |   https://kagane.org/series/3IAMNRJUQFMKKCSENICBZFUSQ5   https://kagane.org/series/3DAYNOIU8FCHJBPUN0CAWFGSL5                                                                                                                                                                                                                              |
|   Manhuaus                  |   Yes                       |   Yes                                          |   None                                |   Yes                                  |                                                              |   https://kagane.org/series/3SAJSEEHQGDY46GVOIPWMKRSA5                                                                                                                                                                                                                                                                                     |
|   Manta                     |   Yes                       |   No                                           |   -                                   |   No                                   |   Use title                                                  |   https://kagane.org/series/38ZSTB5COU5XIAF7CGK7JLAR65   https://kagane.org/series/3LZ1TO5COY5OSKW7GGK7WL9RT5   https://kagane.org/series/35Z5TM5COD4PMEX6LGK7UL3R35                                                                                                                                                                       |
|   MediBang                  |   Yes                       |   Yes                                          |   Yes                                 |   -                                    |                                                              |   https://kagane.org/series/32A0OEWU9UI6UM4AC1COMG8S05                                                                                                                                                                                                                                                                                     |
|   Number Nine               |   Yes                       |   Yes                                          |   None                                |   None                                 |                                                              |                                                                                                                                                                                                                                                                                                                                            |
|   Nyx Scans                 |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/3PAK63UV7FXBZRJPN9DM18SSX5                                                                                                                                                                                                                                                                                     |
|   Omega Scans               |   Yes                       |   No                                           |   -                                   |   -                                    |   Use title                                                  |   https://kagane.org/series/3UAYRM1UAY9B02J1GSC3UJGSC5   https://kagane.org/series/3BAVRA1UAO9L02T1WSC3IJDSJ5                                                                                                                                                                                                                              |
|   One Peace Books           |   Yes                       |   Yes                                          |   Yes                                 |   -                                    |                                                              |   https://kagane.org/series/3GALNCLU9JWXJBFOR1CDKFTSO5                                                                                                                                                                                                                                                                                     |
|   Paradise Scans            |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/34AMT41XZ1R3XP1J9RF32LUS25                                                                                                                                                                                                                                                                                     |
|   Philia Scans              |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3JAKRS1UZJTKJBSLRRC3AJSSR5   https://kagane.org/series/33AYRL1UZFTLGYTLNRC3TJGS15                                                                                                                                                                                                                              |
|   Pocket Comics             |   Yes                       |   No                                           |   -                                   |   No                                   |   Use title                                                  |   https://kagane.org/series/3DZJCM2UEUWAIAIOCWC4UURRL5                                                                                                                                                                                                                                                                                     |
|   Ponent Mon                |   Yes                       |   Yes                                          |   -                                   |   -                                    |                                                              |                                                                                                                                                                                                                                                                                                                                            |
|   Qi Scans                  |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/3IAIOATU4Y6B57J8G6CLIGQSQ5                                                                                                                                                                                                                                                                                     |
|   Reset Scans               |   Yes                       |   No                                           |   No                                  |   No                                   |   Use title                                                  |   https://kagane.org/series/3KA95YWFGL5ERJM7TYNOG77SS5   https://kagane.org/series/35AD5XWFG95WQIE77YNOF7LS35                                                                                                                                                                                                                              |
|   Rizz Fables               |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/3VA89LOIWJU2QI0MROQGT16SD5                                                                                                                                                                                                                                                                                     |
|   Rokari Comics             |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/3SAF83S4D1IOEWWA9V2K10NSA5                                                                                                                                                                                                                                                                                     |
|   Seven Seas Entertainment  |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/30AP0SJU0DQVRJDIL2CBA2XS85   https://kagane.org/series/3PAY1XAU7Y015792G9CSF3GSX5   https://kagane.org/series/3DAF1UAU7Y078052G9CSC3NSL5                                                                                                                                                                       |
|   Shusuisha                 |   Yes                       |   Yes                                          |   None                                |   None                                 |                                                              |                                                                                                                                                                                                                                                                                                                                            |
|   Siren Scans               |   Yes                       |   No                                           |   No                                  |   -                                    |   Use title                                                  |   https://kagane.org/series/3YAWRAQUL12R13Z49DCIIJESG5                                                                                                                                                                                                                                                                                     |
|   Square Enix Manga         |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |   This one has better order_number than in title (prologue)  |   https://kagane.org/series/3AAXOC1U3O2YXPG4W5C3KGFSI5   https://kagane.org/series/3UAGOY1U3U2YXPG4C5C3GGOSC5                                                                                                                                                                                                                              |
|   StoneScape                |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/3FA76KOVPF0VIAD2NHDGS85SN5   https://kagane.org/series/3YAI6IOVPD0MIAU2LHDGQ8QSG5                                                                                                                                                                                                                              |
|   TOKYOPOP                  |   Yes                       |   Yes                                          |   Yes                                 |   -                                    |                                                              |   https://kagane.org/series/3HAXQUTU5F269144N7CLCIFSP5                                                                                                                                                                                                                                                                                     |
|   Tapas                     |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/3SZ9SRQCJOE9EW7WWBKIZK7RA5   https://kagane.org/series/3SZBSOQCJDF0TL8XLBKIWKJRA5   https://kagane.org/series/3CZ4SOQCJ7EGPHOW5BKIWK2RK5   https://kagane.org/series/31ZXSWQCJ7EV13DW5BKIEKFR95                                                                                                                |
|                             |                             |                                                |                                       |                                        |   This one doesn’t has number in title                       |   https://kagane.org/series/3LZBSMQCJJFE13MXRBKIUKJRT5   https://kagane.org/series/3UZ5SOQCJJGE57MYRBKIWK3RC5                                                                                                                                                                                                                              |
|   Tappytoon                 |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/30ZOEH6FXBMBPHJEJPN8PWWR85                                                                                                                                                                                                                                                                                     |
|   Temple Scan               |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/3PAK6I2V8143KC1690D4Q8SSX5                                                                                                                                                                                                                                                                                     |
|   Thunderscans              |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/30A29EDIK1TOKCWL9CQVM10S85                                                                                                                                                                                                                                                                                     |
|   Titan Manga               |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3YA5ORWUNY5GTLO7GFCOZG3SG5   https://kagane.org/series/34A0PMGUWYIXASFAGOCYUH8S25                                                                                                                                                                                                                              |
|   Toomics                   |   Yes                       |   No                                           |                                       |   No                                   |   Use title                                                  |   https://kagane.org/series/39ZPJM42JBNJ35RFJB06UBXR75                                                                                                                                                                                                                                                                                     |
|   UDON Entertainment        |   Yes                       |   Yes                                          |   Yes                                 |                                        |                                                              |   https://kagane.org/series/37APNRUUQOS1579KWICMZFXS55                                                                                                                                                                                                                                                                                     |
|   VAST Visual               |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/37APNRUUQOS1579KWICMZFXS55                                                                                                                                                                                                                                                                                     |
|   VIZ Media                 |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/35AF0OJU1DSG80OKL3CBW2NS35                                                                                                                                                                                                                                                                                     |
|   Vortex Scans              |   Yes                       |   Yes                                          |   -                                   |   Yes                                  |                                                              |   https://kagane.org/series/36AB5V2F3O2XSKF4W5N4D7JS45   https://kagane.org/series/3LAB5C2F3U2ASKI4C5N4K7JST5                                                                                                                                                                                                                              |
|   Webcomics                 |   Yes                       |   No                                           |                                       |   No                                   |   Use title                                                  |   https://kagane.org/series/3DAE6F5VNUF3AS1XCFD7N8MSL5                                                                                                                                                                                                                                                                                     |
|   Webtoon                   |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/3LZJGLEL8874CU2960TWTYRRT5   https://kagane.org/series/3BZ0ZYQCIO3IIAQ5WAKIGR8RJ5                                                                                                                                                                                                                              |
|   Witch Scans               |   Yes                       |   No                                           |                                       |                                        |   Use title                                                  |   https://kagane.org/series/3VAAOYQUPJKCNFKCRHCIGGISD5   https://kagane.org/series/3DAIOOQUPJKJNFRCRHCIWGQSL5                                                                                                                                                                                                                              |
|   Yen Press                 |   Yes                       |   Yes                                          |   Yes                                 |   Yes                                  |                                                              |   https://kagane.org/series/3KAP1WAUFDKOLDWCLXCSE3XSS5   https://kagane.org/series/3MA80AJUR1MYIAGE9JCBI26SU5                                                                                                                                                                                                                              |

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt [hunk 1]
```diff
@@ -83,14 +83,11 @@ class ChapterDto(
...
         @SerialName("pages_count")
         val pagesCount: Int,
-        @SerialName("number_sort")
-        val number: Float,
     ) {
         fun toSChapter(): SChapter = SChapter.create().apply {
             url = "$seriesId;$id;$pagesCount"
             name = title
             date_upload = dateFormat.tryParse(releaseDate)
-            chapter_number = number
```
Comment (Riztard) [inline src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt:93]: btw if this removed, some title doesnt have number. idk which one better. wrong number or without number

Comment (cuong-tran) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt:93]: Can you reference some links? I will check what can be done?

Comment (Riztard) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt:93]: https://kagane.org/series/3HAAOPDUQDC4JB2ULICVXGISP5

Comment (Riztard) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt:93]: maybe if from mangadex can use the number, cuz like this one it has 24.5
https://kagane.org/series/36A1OPIUMU0LZRT2CECAXG9S45

Comment (cuong-tran) [reply src/en/kagane/src/eu/kanade/tachiyomi/extension/en/kagane/Dto.kt:93]: Good idea, MangaDex and a few more sources has correct `number_sort`

**Review by AwkwardPeak7 — DISMISSED** [review]

**Review by vetleledaal — APPROVED** [review]
