### PR TITLE
MangaGeko | Added New Filters, Fixed Filters

### LINKED ISSUE #11814: MangaGeko: `No results found` on Popular page & when searching with Filter
### Source information

Mangageko 1.4.27

### Source language

English

### Steps to reproduce

1. Opening mgeko
2. Put filters or use popular filter
3. Use eyes to see page

Image

### Expected behavior

Loading the comics

### Actual behavior

No results found

### Mihon/Tachiyomi version

0.19.3

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [x] I have tried the [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [x] If this is an issue with the app itself, I should be opening an issue in the app repository.
- [x] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by KenjieDec**
Closes #11814
Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [ ] Have removed `web_hi_res_512.png` when adding a new extension

### CODE REVIEW

File: src/en/mangarawclub/src/eu/kanade/tachiyomi/extension/en/mangarawclub/MangaRawClub.kt [hunk 1]
```diff
@@ -179,5 +231,29 @@ class MangaRawClub : ParsedHttpSource() {
...
+            key = PREF_HIDE_NSFW
+            title = "Hide NSFW"
+            summary = "Hides NSFW entries"
+            setDefaultValue(false)
+        }.also(screen::addPreference)
+    }
+
+    private inline fun <reified T> Response.parseAs(): T {
+        return jsonInstance.decodeFromString(body.string())
+    }
```
Comment (AwkwardPeak7) [inline src/en/mangarawclub/src/eu/kanade/tachiyomi/extension/en/mangarawclub/MangaRawClub.kt]: import from `keiyoushi.utils` instead

**Review by AwkwardPeak7 — APPROVED** [review]
